import type { TopicPractice } from "../../types.ts";

// Prime-factor Venn diagram for A = 2^4 × 3 × 5^2 = 1200 and B = 2^2 × 3^3 × 11 = 1188.
// A only: 2, 2, 5, 5 · both: 2, 2, 3 · B only: 3, 3, 11.
const primeVenn = `<svg viewBox="0 0 400 220" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Venn diagram of prime factors. A only contains 2, 2, 5, 5. The overlap contains 2, 2, 3. B only contains 3, 3, 11."><rect x="0" y="0" width="400" height="220" fill="#ffffff"/><rect x="10" y="10" width="380" height="200" fill="none" stroke="#334155" stroke-width="1.5"/><circle cx="150" cy="115" r="80" fill="#c7d2fe" fill-opacity="0.6" stroke="#1f2937" stroke-width="2"/><circle cx="250" cy="115" r="80" fill="#fde68a" fill-opacity="0.6" stroke="#1f2937" stroke-width="2"/><text x="80" y="38" font-size="14" font-family="sans-serif" fill="#1f2937" font-weight="bold">A</text><text x="312" y="38" font-size="14" font-family="sans-serif" fill="#1f2937" font-weight="bold">B</text><text x="110" y="105" font-size="14" font-family="sans-serif" fill="#1f2937" text-anchor="middle">2   2</text><text x="110" y="135" font-size="14" font-family="sans-serif" fill="#1f2937" text-anchor="middle">5   5</text><text x="200" y="100" font-size="14" font-family="sans-serif" fill="#1f2937" text-anchor="middle">2</text><text x="200" y="122" font-size="14" font-family="sans-serif" fill="#1f2937" text-anchor="middle">2</text><text x="200" y="144" font-size="14" font-family="sans-serif" fill="#1f2937" text-anchor="middle">3</text><text x="290" y="105" font-size="14" font-family="sans-serif" fill="#1f2937" text-anchor="middle">3   3</text><text x="290" y="135" font-size="14" font-family="sans-serif" fill="#1f2937" text-anchor="middle">11</text></svg>`;

// Right-angled triangle: opposite 5.4 cm (vertical), adjacent 8.2 cm (horizontal), angle θ at the left. Scale 25 px per cm.
const trigBounds = `<svg viewBox="0 0 300 190" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Right-angled triangle with horizontal side 8.2 cm, vertical side 5.4 cm and angle theta at the bottom left between the horizontal side and the hypotenuse"><rect x="0" y="0" width="300" height="190" fill="#ffffff"/><polygon points="30,160 235,160 235,25" fill="#bae6fd" stroke="#1f2937" stroke-width="2"/><polyline points="223,160 223,148 235,148" fill="none" stroke="#1f2937" stroke-width="1.5"/><path d="M 62 160 A 32 32 0 0 0 56.7 142.4" fill="none" stroke="#1f2937" stroke-width="1.5"/><text x="70" y="153" font-size="14" font-family="sans-serif" fill="#1f2937">θ</text><text x="132" y="178" font-size="13" font-family="sans-serif" fill="#1f2937" text-anchor="middle">8.2 cm</text><text x="243" y="97" font-size="13" font-family="sans-serif" fill="#1f2937">5.4 cm</text></svg>`;

export const practice: TopicPractice = {
  // ------------------------------------------------------------------ quiz
  quiz: [
    {
      kind: "short",
      id: "number-bounds-quiz-q01",
      question:
        "Write 1800 as a product of its prime factors in index form, {{2^a * 3^b * 5^c}}. Give the values of a, b and c, in that order.",
      answer: { type: "list", values: [3, 2, 2], ordered: true, display: "{{1800 = 2^3 * 3^2 * 5^2}}, so a = 3, b = 2, c = 2" },
      traps: [
        { spec: { type: "list", values: [2, 2, 2], ordered: true }, feedback: "That gives {{2^2 * 3^2 * 5^2 = 900}}, not 1800. Keep dividing by 2 until you can't: 1800 → 900 → 450 → 225." },
      ],
      solution: ["1800 ÷ 2 = 900, ÷ 2 = 450, ÷ 2 = 225 — three 2s.", "225 ÷ 3 = 75, ÷ 3 = 25 — two 3s.", "25 = 5 × 5 — two 5s.", "{{1800 = 2^3 * 3^2 * 5^2}}: a = 3, b = 2, c = 2."],
      commonError: "Stopping a factor tree early and leaving a composite number such as 4, 9 or 25 at the end of a branch.",
      difficulty: "warmup",
      guideRef: "prime-factors-hcf-lcm",
      hints: ["Divide by the smallest prime repeatedly before moving on to the next prime.", "How many times can you halve 1800 and still get a whole number?"],
      strategy: "Factor tree / repeated division",
    },
    {
      kind: "short",
      id: "number-bounds-quiz-q02",
      question: "Find the highest common factor (HCF) and the lowest common multiple (LCM) of 126 and 150. Give the HCF first.",
      answer: { type: "list", values: [6, 3150], ordered: true, display: "HCF = 6, LCM = 3150" },
      traps: [
        { spec: { type: "list", values: [6, 18900], ordered: true }, feedback: "18 900 = 126 × 150 is a common multiple, but not the *lowest*. Divide by the HCF: 18 900 ÷ 6 = 3150." },
        { spec: { type: "list", values: [3150, 6], ordered: true }, feedback: "Right numbers, wrong order — the HCF (the smaller one) goes first." },
      ],
      solution: [
        "{{126 = 2 * 3^2 * 7}} and {{150 = 2 * 3 * 5^2}}.",
        "HCF: primes in both, lowest powers: 2 × 3 = 6.",
        "LCM: every prime, highest powers: {{2 * 3^2 * 5^2 * 7 = 3150}}.",
      ],
      solutions: [
        { label: "Prime factors", steps: ["HCF = product of the overlap = 2 × 3 = 6.", "LCM = product of everything in the Venn diagram = 2 × 3 × 3 × 7 × 5 × 5 = 3150."] },
        { label: "Use HCF × LCM = product", steps: ["Find HCF = 6 first.", "LCM = 126 × 150 ÷ 6 = 18 900 ÷ 6 = 3150."] },
      ],
      difficulty: "warmup",
      guideRef: "prime-factors-hcf-lcm",
      hints: ["Write both numbers as products of primes.", "HCF uses the primes they share; LCM uses every prime, each at its highest power."],
      strategy: "Prime-factor Venn diagram",
    },
    {
      kind: "mcq",
      id: "number-bounds-quiz-q03",
      question: "Round 0.020549 to 3 significant figures.",
      options: ["0.0205", "0.0206", "0.021", "0.02"],
      answerIndex: 0,
      explanation:
        "Leading zeros are not significant, so the first significant figure is the 2. The three significant figures are 2, 0, 5 and the next digit is 4, so round down: 0.0205. 0.0206 comes from double rounding (0.020549 → 0.02055 → 0.0206) — always round once, from the original number. 0.021 is only 2 significant figures and 0.02 is only 1.",
      difficulty: "warmup",
      guideRef: "rounding-estimation",
      hints: ["Where does the first *significant* figure start — do leading zeros count? Which single digit decides the rounding?"],
    },
    {
      kind: "short",
      id: "number-bounds-quiz-q04",
      question:
        "By rounding each number to 1 significant figure, work out an estimate for {{(6.12 * 19.8)/0.512}}.",
      answer: { type: "number", value: 240 },
      traps: [
        { spec: { type: "number", value: 60 }, feedback: "You multiplied by 0.5 instead of dividing. Dividing by 0.5 *doubles* a number: 120 ÷ 0.5 = 240." },
        { spec: { type: "number", value: 120 }, feedback: "You treated 0.512 as 1. To 1 s.f. it is 0.5, and 120 ÷ 0.5 = 240." },
      ],
      solution: ["6.12 ≈ 6, 19.8 ≈ 20, 0.512 ≈ 0.5.", "6 × 20 = 120.", "120 ÷ 0.5 = 240."],
      commonError: "Rounding 0.512 to 1 (or to 0) instead of 0.5, or multiplying by 0.5.",
      difficulty: "core",
      guideRef: "rounding-estimation",
      hints: ["Round each number to 1 s.f. first — what is 0.512 to 1 s.f.?", "Dividing by 0.5 is the same as multiplying by what?"],
      strategy: "Estimate first",
    },
    {
      kind: "short",
      id: "number-bounds-quiz-q05",
      question:
        "A bottle holds 1.75 litres of soya milk, correct to 2 decimal places. Write down the lower bound and the upper bound of the volume, in that order. Give your answers in litres.",
      answer: { type: "list", values: [1.745, 1.755], ordered: true, display: "1.745 litres and 1.755 litres" },
      traps: [
        { spec: { type: "list", values: [1.74, 1.76], ordered: true }, feedback: "Those are 0.01 either side. The bounds are only *half* a unit (0.005) either side of 1.75." },
        { spec: { type: "list", values: [1.745, 1.754], ordered: true }, feedback: "The upper bound is 1.755 itself — it is the boundary, even though 1.755 would round up. Don't use 1.754 or 1.7549…" },
      ],
      solution: ["Accurate to 0.01 litres, so half the unit is 0.005 litres.", "Lower bound: 1.75 − 0.005 = 1.745 litres.", "Upper bound: 1.75 + 0.005 = 1.755 litres."],
      difficulty: "warmup",
      guideRef: "error-intervals",
      hints: ["The measurement is to the nearest 0.01 litres. What is half of that?"],
      strategy: "Half the unit either side",
    },
    {
      kind: "mcq",
      id: "number-bounds-quiz-q06",
      question: "A number x is **truncated** to 1 decimal place. The result is 3.7. Which is the error interval for x?",
      options: ["3.65 ≤ x < 3.75", "3.7 ≤ x < 3.8", "3.6 < x ≤ 3.7", "3.7 ≤ x ≤ 3.8"],
      answerIndex: 1,
      explanation:
        "Truncating chops off the later digits, so every number from 3.7 up to (but not including) 3.8 truncates to 3.7: 3.7 ≤ x < 3.8. The interval 3.65 ≤ x < 3.75 is for *rounding* to 1 d.p.; 3.7 ≤ x ≤ 3.8 wrongly includes 3.8, which truncates to 3.8; 3.6 < x ≤ 3.7 goes the wrong way — truncation chops downwards, so x is never below the value shown.",
      difficulty: "core",
      guideRef: "error-intervals",
      hints: ["Truncating is not rounding — what does 3.79 truncate to?", "What is the smallest number that truncates to 3.8?"],
    },
    {
      kind: "short",
      id: "number-bounds-quiz-q07",
      question:
        "A rectangular photo measures 15 cm by 9 cm, each correct to the nearest centimetre. Work out the upper bound for the area of the photo. Give your answer in cm².",
      answer: { type: "number", value: 147.25 },
      traps: [
        { spec: { type: "number", value: 135 }, feedback: "135 cm² uses the rounded lengths. For the upper bound of the area use the upper bound of each length." },
        { spec: { type: "number", value: 135.5 }, feedback: "You added 0.5 to the area. The bounds belong to the *lengths*: 15.5 × 9.5." },
        { spec: { type: "number", value: 160 }, feedback: "16 × 10 adds a whole centimetre to each side. The bounds are only half a unit away: 15.5 and 9.5." },
      ],
      solution: ["Upper bounds: 15.5 cm and 9.5 cm.", "Upper bound of area = 15.5 × 9.5 = 147.25 cm²."],
      commonError: "Working out 15 × 9 = 135 and then adding 0.5.",
      difficulty: "core",
      guideRef: "bounds-calculations",
      hints: ["To make a product as big as possible, make each factor as big as possible.", "What is the upper bound of a length given to the nearest cm?"],
      strategy: "Consider extremes",
    },
    {
      kind: "short",
      id: "number-bounds-quiz-q08",
      question:
        "Wei Ling runs 150 m, correct to the nearest 10 m, in a time of 20 seconds, correct to the nearest second. Work out the lower bound for her average speed. Give your answer in m/s correct to 3 significant figures.",
      answer: { type: "number", value: 7.07, tolerance: 0.005 },
      traps: [
        { spec: { type: "number", value: 7.25 }, feedback: "145 ÷ 20 = 7.25 uses the lower distance but the rounded time. For the smallest speed, divide the smallest distance by the *largest* time, 20.5 s." },
        { spec: { type: "number", value: 7.44, tolerance: 0.005 }, feedback: "This is lower distance ÷ lower time. Dividing by a smaller number makes the answer bigger — use the upper bound of the time." },
      ],
      solution: ["Distance bounds: 145 m to 155 m. Time bounds: 19.5 s to 20.5 s.", "Lower bound of speed = lower distance ÷ upper time.", "145 ÷ 20.5 = 7.073… = 7.07 m/s (3 s.f.)."],
      commonError: "Using lower ÷ lower for the lower bound of a quotient.",
      difficulty: "core",
      guideRef: "bounds-calculations",
      hints: ["Speed = distance ÷ time. Which bound of the distance makes the speed smallest?", "Dividing by a *bigger* number gives a smaller answer — which bound of the time?", "Lower speed = 145 ÷ 20.5."],
      strategy: "Consider extremes",
    },
    {
      kind: "mcq",
      id: "number-bounds-quiz-q09",
      question: "a and b are both rounded measurements. Which calculation gives the **upper bound** of a − b?",
      options: [
        "upper bound of a − upper bound of b",
        "lower bound of a − lower bound of b",
        "upper bound of a − lower bound of b",
        "lower bound of a − upper bound of b",
      ],
      answerIndex: 2,
      explanation:
        "To make a difference as big as possible, start as big as you can and take away as little as you can: upper a − lower b. Upper − upper is the tempting slip: subtracting a *bigger* b makes the answer smaller. Lower a − upper b gives the lower bound.",
      difficulty: "core",
      guideRef: "bounds-calculations",
      hints: ["Try it with numbers: 10 − 3 versus 10 − 2. Which is bigger?", "Taking away less leaves more."],
      strategy: "Try small cases",
    },
    {
      kind: "short",
      id: "number-bounds-quiz-q10",
      question:
        "A 4-digit PIN uses the digits 0–9. The first digit must be odd, the last digit must be even, and no digit may be repeated. How many different PINs are possible?",
      answer: { type: "number", value: 1400 },
      traps: [
        { spec: { type: "number", value: 2500 }, feedback: "5 × 10 × 10 × 5 allows repeated digits. Once two digits are used, the middle positions have 8 and then 7 choices." },
        { spec: { type: "number", value: 1800 }, feedback: "Filling left to right (5 × 9 × 8 × …) gives the middle digits too many choices. Fill the two restricted ends first, then the middle." },
      ],
      solution: ["First digit (odd): 5 choices. Last digit (even): 5 choices — an odd and an even digit can never clash.", "Second digit: any of the 8 digits not yet used.", "Third digit: 7 choices.", "5 × 8 × 7 × 5 = 1400."],
      commonError: "Filling the positions left to right, so the middle digits are counted before the restricted last digit has been chosen.",
      difficulty: "core",
      guideRef: "number-problems",
      hints: ["Which positions have restrictions? Fill those first.", "Can the first and last digits ever be the same digit? How many digits are left for the middle two places?"],
      strategy: "Product rule for counting",
    },
  ],

  // ---------------------------------------------------------------- papers
  papers: [
    {
      id: "number-bounds-p1",
      title: "Practice Paper 1",
      questions: [
        {
          kind: "short",
          id: "number-bounds-p1-q01",
          question: "Write 252 as a product of its prime factors in the form {{2^a * 3^b * 7^c}}. Give a, b and c, in that order.",
          answer: { type: "list", values: [2, 2, 1], ordered: true, display: "{{252 = 2^2 * 3^2 * 7}}" },
          solution: ["252 ÷ 2 = 126, ÷ 2 = 63.", "63 ÷ 3 = 21, ÷ 3 = 7.", "{{252 = 2^2 * 3^2 * 7}}: a = 2, b = 2, c = 1."],
          difficulty: "warmup",
          guideRef: "prime-factors-hcf-lcm",
          hints: ["Halve 252 as many times as you can, then divide by 3."],
          strategy: "Factor tree / repeated division",
        },
        {
          kind: "short",
          id: "number-bounds-p1-q02",
          question: "Round 52 649 to 2 significant figures.",
          answer: { type: "number", value: 53000, display: "53 000" },
          traps: [
            { spec: { type: "number", value: 53 }, feedback: "Rounding keeps the size of the number — the zeros are placeholders. 52 649 ≈ 53 000, not 53." },
            { spec: { type: "number", value: 52000 }, feedback: "The third figure is 6, so round *up*: 53 000." },
          ],
          solution: ["The first two significant figures are 5 and 2 (ten-thousands and thousands).", "The next digit is 6, so round up: 53 000."],
          difficulty: "warmup",
          guideRef: "rounding-estimation",
          hints: ["Which place value is the second significant figure in?"],
        },
        {
          kind: "short",
          id: "number-bounds-p1-q03",
          question: "Priya's mass is 64 kg, correct to the nearest kilogram. Write down the lower bound and the upper bound of her mass, in that order, in kg.",
          answer: { type: "list", values: [63.5, 64.5], ordered: true, display: "63.5 kg and 64.5 kg" },
          traps: [{ spec: { type: "list", values: [63, 65], ordered: true }, feedback: "Half a unit either side, not a whole unit: 64 ± 0.5." }],
          solution: ["Nearest 1 kg, so half the unit is 0.5 kg.", "Lower bound 63.5 kg, upper bound 64.5 kg."],
          difficulty: "warmup",
          guideRef: "error-intervals",
          hints: ["What is half of 1 kg?"],
          strategy: "Half the unit either side",
        },
        {
          kind: "short",
          id: "number-bounds-p1-q04",
          question: "Use your calculator to work out {{(sqrt(17.4) + 2.3^2)/(4.1 - 1.75)}}. Give your answer correct to 3 significant figures.",
          answer: { type: "number", value: 4.03 },
          traps: [
            { spec: { type: "number", value: 6.42, tolerance: 0.005 }, feedback: "Only {{2.3^2}} was divided by 2.35. Put brackets round the whole numerator (or use the fraction button)." },
          ],
          solution: ["Numerator: {{sqrt(17.4)}} = 4.1713… and {{2.3^2}} = 5.29, total 9.4613…", "Denominator: 4.1 − 1.75 = 2.35.", "9.4613… ÷ 2.35 = 4.0260… = 4.03 (3 s.f.)."],
          commonError: "Typing the calculation without brackets so only part of the numerator is divided.",
          difficulty: "warmup",
          guideRef: "rounding-estimation",
          hints: ["Work out the top and the bottom separately, or put the whole numerator in brackets."],
        },
        {
          kind: "short",
          id: "number-bounds-p1-q05",
          question:
            "At the Sentosa light show, one fountain jet fires every 40 seconds and another fires every 75 seconds. Both fire together at 20:00. How many seconds later do they next fire together?",
          answer: { type: "number", value: 600 },
          traps: [
            { spec: { type: "number", value: 5 }, feedback: "5 is the HCF. You need a time that is a multiple of *both* 40 and 75 — the LCM." },
            { spec: { type: "number", value: 3000 }, feedback: "40 × 75 = 3000 is a common multiple, but not the first one. The LCM is 3000 ÷ 5 = 600." },
          ],
          solution: ["{{40 = 2^3 * 5}} and {{75 = 3 * 5^2}}.", "LCM = highest power of every prime = {{2^3 * 3 * 5^2 = 600}}.", "They next fire together after 600 seconds (10 minutes, at 20:10)."],
          difficulty: "core",
          guideRef: "prime-factors-hcf-lcm",
          hints: ["Is this an HCF or an LCM problem? Are the times getting bigger or being split up?", "Write 40 and 75 as products of primes, then take the highest power of each prime."],
          strategy: "HCF or LCM? Decide first",
        },
        {
          kind: "short",
          id: "number-bounds-p1-q06",
          question:
            "Hana has 84 roses and 126 orchids. She makes identical bunches using all the flowers, with no flowers left over. What is the greatest number of bunches she can make?",
          answer: { type: "number", value: 42 },
          traps: [{ spec: { type: "number", value: 252 }, feedback: "252 is the LCM. Splitting into equal groups with nothing left over needs the *highest common factor*." }],
          solution: ["{{84 = 2^2 * 3 * 7}}, {{126 = 2 * 3^2 * 7}}.", "HCF = 2 × 3 × 7 = 42.", "42 bunches, each with 2 roses and 3 orchids."],
          difficulty: "core",
          guideRef: "prime-factors-hcf-lcm",
          hints: ["The number of bunches must divide into 84 *and* into 126.", "You want the biggest such number — HCF or LCM?"],
          strategy: "HCF or LCM? Decide first",
        },
        {
          kind: "written",
          id: "number-bounds-p1-q07",
          question:
            "{{A = 2^3 * 3^2 * 5}} and {{B = 2 * 3^3 * 7}}.\n\n(a) Find the HCF of A and B.\n\n(b) Show that the LCM of A and B is 7560.",
          marks: 3,
          modelAnswer:
            "(a) The primes in both are 2 and 3; take the lowest powers: HCF = {{2^1 * 3^2}} = 18.\n\n(b) The LCM uses every prime at its highest power: {{2^3 * 3^3 * 5 * 7}} = 8 × 27 × 35 = 216 × 35 = 7560.",
          markScheme: [
            { point: "HCF = 2 × 3² = 18", keywords: ["18", "2 × 3²", "lowest power"] },
            { point: "LCM written as 2³ × 3³ × 5 × 7 (highest powers of every prime)", keywords: ["2³ × 3³ × 5 × 7", "highest power", "27", "8"] },
            { point: "Evaluated correctly to 7560 with working shown", keywords: ["7560", "216 × 35", "8 × 27 × 35"] },
          ],
          commonError: "Taking the highest powers for the HCF, or multiplying A × B for the LCM.",
          difficulty: "core",
          guideRef: "prime-factors-hcf-lcm",
          hints: ["Put the prime factors in a Venn diagram: what goes in the overlap?", "HCF = the overlap; LCM = everything in both circles.", "LCM = {{2^3 * 3^3 * 5 * 7}}; multiply it out carefully."],
          strategy: "Prime-factor Venn diagram",
        },
        {
          kind: "short",
          id: "number-bounds-p1-q08",
          question: "By rounding each number to 1 significant figure, work out an estimate for {{(sqrt(99.2) * 4.92^2)/0.198}}.",
          answer: { type: "number", value: 1250 },
          traps: [
            { spec: { type: "number", value: 50 }, feedback: "You multiplied by 0.2 instead of dividing. 250 ÷ 0.2 = 250 × 5 = 1250." },
            { spec: { type: "number", value: 500 }, feedback: "Check {{4.92^2}}: 4.92 ≈ 5, and {{5^2}} = 25, not 10." },
          ],
          solution: ["99.2 ≈ 100, so {{sqrt(100)}} = 10.", "4.92 ≈ 5, so {{5^2}} = 25.", "0.198 ≈ 0.2.", "10 × 25 ÷ 0.2 = 250 ÷ 0.2 = 1250."],
          difficulty: "core",
          guideRef: "rounding-estimation",
          hints: ["Round each number to 1 s.f. before doing anything else.", "Dividing by 0.2 is the same as multiplying by 5."],
          strategy: "Estimate first",
        },
        {
          kind: "written",
          id: "number-bounds-p1-q09",
          question:
            "Arjun estimates {{49.6/0.81}} by working out {{50/0.8}} = 62.5.\n\nWithout working out the exact value, explain whether his estimate is an overestimate or an underestimate.",
          marks: 3,
          modelAnswer:
            "It is an overestimate. He rounded the numerator up (49.6 → 50), which makes the quotient bigger. He rounded the denominator down (0.81 → 0.8), and dividing by a smaller number also makes the answer bigger. Both changes increase the answer, so 62.5 is larger than the true value.",
          markScheme: [
            { point: "Numerator rounded up makes the answer larger", keywords: ["rounded up", "50", "bigger numerator", "larger"] },
            { point: "Denominator rounded down; dividing by a smaller number makes the answer larger", keywords: ["rounded down", "0.8", "smaller", "divide"] },
            { point: "Conclusion: overestimate", keywords: ["overestimate", "over-estimate", "too big", "too high"] },
          ],
          commonError: "Saying 'both numbers changed, so you can't tell' — here both changes push the answer the same way.",
          difficulty: "core",
          guideRef: "rounding-estimation",
          hints: ["Look at each rounding separately: did the number go up or down?", "What happens to a division when the bottom gets smaller?"],
          strategy: "Consider extremes",
        },
        {
          kind: "short",
          id: "number-bounds-p1-q10",
          question:
            "The number of visitors to Sentosa one day was 4700, correct to 2 significant figures. Write down the least possible number and the upper bound of the number of visitors, in that order.",
          answer: { type: "list", values: [4650, 4750], ordered: true, display: "4650 and 4750" },
          traps: [{ spec: { type: "list", values: [4695, 4705], ordered: true }, feedback: "2 s.f. here means the nearest 100, not the nearest 10. Half of 100 is 50." }],
          solution: ["2 s.f. of 4700 means the nearest 100.", "Half of 100 = 50.", "Least: 4650; upper bound: 4750 (4750 itself would round to 4800, but it is still the boundary)."],
          commonError: "Thinking 2 s.f. means 'to the nearest 10'.",
          difficulty: "core",
          guideRef: "error-intervals",
          hints: ["What place value is the 2nd significant figure of 4700?", "Half of a hundred either side."],
          strategy: "Half the unit either side",
        },
        {
          kind: "short",
          id: "number-bounds-p1-q11",
          question:
            "The sides of a triangle are 8.3 cm, 6.1 cm and 5.7 cm, each correct to 1 decimal place. Work out the upper bound for the perimeter of the triangle. Give your answer in cm.",
          answer: { type: "number", value: 20.25 },
          traps: [{ spec: { type: "number", value: 20.15 }, feedback: "You added 0.05 once to the total. Each of the three sides can be up to 0.05 cm longer." }],
          solution: ["Upper bounds: 8.35, 6.15, 5.75.", "8.35 + 6.15 + 5.75 = 20.25 cm."],
          difficulty: "core",
          guideRef: "bounds-calculations",
          hints: ["To make a sum as big as possible, use the upper bound of every part.", "Each side can be up to 0.05 cm more."],
          strategy: "Consider extremes",
        },
        {
          kind: "short",
          id: "number-bounds-p1-q12",
          question:
            "A small block of metal has a mass of 450 g, correct to the nearest 10 g, and a volume of 60 cm³, correct to the nearest 5 cm³. Work out the upper bound for its density. Give your answer in g/cm³ correct to 3 significant figures.",
          answer: { type: "number", value: 7.91 },
          traps: [
            { spec: { type: "number", value: 7.28, tolerance: 0.005 }, feedback: "455 ÷ 62.5 uses the upper bound of the volume. Dividing by a bigger number makes the density smaller — use the lower bound, 57.5 cm³." },
            { spec: { type: "number", value: 7.5 }, feedback: "450 ÷ 60 uses the rounded values. Use bounds: largest mass, smallest volume." },
          ],
          solution: [
            "Mass bounds: 445 g to 455 g. Volume bounds: 57.5 cm³ to 62.5 cm³.",
            "Upper bound of density = upper mass ÷ lower volume.",
            "455 ÷ 57.5 = 7.913… = 7.91 g/cm³ (3 s.f.).",
          ],
          commonError: "Using ±0.5 for the volume when it is given to the nearest 5 cm³ (the half-unit is 2.5).",
          difficulty: "core",
          guideRef: "bounds-calculations",
          hints: ["Density = mass ÷ volume. Which bound of each makes the density biggest?", "To the nearest 5 means ±2.5.", "455 ÷ 57.5."],
          strategy: "Consider extremes",
        },
        {
          kind: "short",
          id: "number-bounds-p1-q13",
          question:
            "a = 8.6 and b = 3.2, each correct to 1 decimal place.\n\nWork out the upper bound of {{(a + b)/(a - b)}}. Give your answer correct to 3 significant figures.",
          answer: { type: "number", value: 2.23 },
          traps: [
            { spec: { type: "number", value: 2.15, tolerance: 0.005 }, feedback: "That's a = 8.65, b = 3.15 — making a big feels natural, but a is also in the denominator, where a smaller a − b helps more. Try a = 8.55, b = 3.25." },
            { spec: { type: "number", value: 2.19, tolerance: 0.005 }, feedback: "That's the value from the rounded numbers. Test each combination of bounds for a and b." },
          ],
          solution: [
            "Rewrite: {{(a + b)/(a - b) = 1 + (2b)/(a - b)}}.",
            "This is biggest when b is as large as possible and a − b as small as possible: a = 8.55, b = 3.25.",
            "{{(8.55 + 3.25)/(8.55 - 3.25) = 11.8/5.3}} = 2.2264… = 2.23 (3 s.f.).",
          ],
          solutions: [
            { label: "Test the four combinations", steps: ["(8.65, 3.25): 11.9 ÷ 5.4 = 2.204", "(8.65, 3.15): 11.8 ÷ 5.5 = 2.145", "(8.55, 3.15): 11.7 ÷ 5.4 = 2.167", "(8.55, 3.25): 11.8 ÷ 5.3 = 2.226 — the largest."] },
          ],
          commonError: "Using the upper bound of a 'because it is in the numerator' — a is in the denominator too, and there it matters more.",
          difficulty: "challenge",
          guideRef: "bounds-calculations",
          hints: [
            "a appears on the top *and* the bottom. Each letter can take only one value at a time.",
            "Try all four combinations of upper/lower bounds — which is largest?",
            "Or rewrite {{(a+b)/(a-b)}} as {{1 + (2b)/(a-b)}}: what makes that big?",
          ],
          strategy: "Consider extremes",
        },
        {
          kind: "written",
          id: "number-bounds-p1-q14",
          question:
            "Zara runs 400 m, correct to the nearest metre, in a time of 51.8 seconds, correct to 1 decimal place.\n\nBy considering bounds, work out her average speed to a suitable degree of accuracy. You must show all your working and give a reason for your answer.",
          marks: 4,
          modelAnswer:
            "Distance: 399.5 ≤ d < 400.5. Time: 51.75 ≤ t < 51.85.\n\nUpper bound of speed = 400.5 ÷ 51.75 = 7.739… m/s.\nLower bound of speed = 399.5 ÷ 51.85 = 7.704… m/s.\n\nBoth bounds round to 7.7 to 2 significant figures (but they differ at 3 s.f.: 7.74 and 7.70), so the speed is 7.7 m/s to a suitable degree of accuracy.",
          markScheme: [
            { point: "Correct bounds used: 399.5, 400.5, 51.75, 51.85", keywords: ["399.5", "400.5", "51.75", "51.85"] },
            { point: "Upper bound of speed = 400.5 ÷ 51.75 = 7.739…", keywords: ["7.739", "7.74", "400.5 ÷ 51.75"] },
            { point: "Lower bound of speed = 399.5 ÷ 51.85 = 7.704…", keywords: ["7.704", "7.70", "399.5 ÷ 51.85"] },
            { point: "7.7 m/s because both bounds round to 7.7 (2 s.f.)", keywords: ["7.7", "both round", "same", "2 s.f", "2 significant"] },
          ],
          commonError: "Giving 7.72 (the value from the rounded data) without checking whether the bounds agree to that accuracy.",
          difficulty: "challenge",
          guideRef: "bounds-calculations",
          hints: [
            "Find the upper and lower bounds of the speed first.",
            "Upper speed = upper distance ÷ lower time; lower speed = lower distance ÷ upper time.",
            "Round both bounds to 3 s.f., then 2 s.f. — to how many figures do they agree?",
          ],
          strategy: "Consider extremes",
        },
        {
          kind: "written",
          id: "number-bounds-p1-q15",
          question:
            "p and q are two different prime numbers, both greater than 2.\n\nProve that {{p^2 - q^2}} is always a multiple of 8.",
          marks: 4,
          modelAnswer:
            "Primes greater than 2 are odd, so p and q are both odd.\n\n{{p^2 - q^2 = (p - q)(p + q)}}. The sum and difference of two odd numbers are both even.\n\nAlso (p + q) + (p − q) = 2p, and 2p is 2 × odd, which is not a multiple of 4. Two even numbers that are both multiples of 4 would add to a multiple of 4, so they can't both be multiples of 4; and if neither were a multiple of 4 (each 2 more than a multiple of 4) they would add to a multiple of 4 as well. So exactly one of p − q and p + q is a multiple of 4 and the other is even.\n\nHence {{(p - q)(p + q)}} = (multiple of 4) × (multiple of 2), which is a multiple of 8.",
          markScheme: [
            { point: "States p and q are odd (primes greater than 2)", keywords: ["odd"] },
            { point: "Factorises as difference of two squares (p − q)(p + q)", keywords: ["(p − q)(p + q)", "(p-q)(p+q)", "difference of two squares"] },
            { point: "Both factors are even", keywords: ["even", "both even"] },
            { point: "Shows one factor is a multiple of 4 (e.g. via sum 2p), so product is a multiple of 8", keywords: ["multiple of 4", "2p", "4 × 2", "multiple of 8"] },
          ],
          solutions: [
            { label: "Write odd numbers algebraically", steps: ["Let p = 2m + 1, q = 2n + 1.", "{{p^2 - q^2 = 4m^2 + 4m - 4n^2 - 4n = 4(m(m+1) - n(n+1))}}.", "m(m + 1) and n(n + 1) are products of consecutive integers, so both are even; their difference is even.", "So {{p^2 - q^2 = 4 * (even)}} = multiple of 8."] },
          ],
          commonError: "Testing a few examples (5² − 3² = 16) and calling it a proof. Examples are a good start, not a proof.",
          difficulty: "challenge",
          guideRef: "number-problems",
          hints: [
            "Try a few: 5² − 3², 7² − 3², 11² − 7². What do you notice?",
            "What do all primes greater than 2 have in common?",
            "Factorise {{p^2 - q^2}}. Are the two factors odd or even?",
            "Look at the sum of the two factors, 2p. Can both be multiples of 4?",
          ],
          strategy: "Try small cases, then prove",
        },
      ],
    },
    {
      id: "number-bounds-p2",
      title: "Practice Paper 2",
      questions: [
        {
          kind: "short",
          id: "number-bounds-p2-q01",
          question: "A number is written as {{2^3 * 3 * 5^2}}. Work out the number.",
          answer: { type: "number", value: 600 },
          traps: [{ spec: { type: "number", value: 240 }, feedback: "Check the powers: {{2^3 = 8}} and {{5^2 = 25}} — so 8 × 3 × 25." }],
          solution: ["{{2^3 = 8}}, {{5^2 = 25}}.", "8 × 3 × 25 = 24 × 25 = 600."],
          difficulty: "warmup",
          guideRef: "prime-factors-hcf-lcm",
          hints: ["Evaluate each power first, then multiply."],
        },
        {
          kind: "short",
          id: "number-bounds-p2-q02",
          question: "Round 0.07096 to 2 significant figures. Give your answer as a decimal.",
          answer: { type: "number", value: 0.071, allowFraction: false },
          traps: [
            { spec: { type: "number", value: 0.07 }, feedback: "0.07 is only 1 significant figure. After the 7, the next significant figure is the 0 — then look at the 9 to decide." },
          ],
          solution: ["First significant figure: 7. Second: 0.", "The next digit is 9, so round the 0 up to 1.", "0.07096 ≈ 0.071 (2 s.f.)."],
          difficulty: "warmup",
          guideRef: "rounding-estimation",
          hints: ["Leading zeros don't count — but zeros *after* the first non-zero digit do."],
        },
        {
          kind: "short",
          id: "number-bounds-p2-q03",
          question:
            "A number y is **truncated** to 1 decimal place. The result is 6.2. Write down the lower bound and the upper bound of y, in that order.",
          answer: { type: "list", values: [6.2, 6.3], ordered: true, display: "6.2 ≤ y < 6.3" },
          traps: [{ spec: { type: "list", values: [6.15, 6.25], ordered: true }, feedback: "Those are the bounds for *rounding*. Truncation just chops digits off: anything from 6.2 up to (not including) 6.3 truncates to 6.2." }],
          solution: ["Truncating chops off later digits, so 6.2, 6.21, …, 6.2999… all truncate to 6.2.", "Error interval: 6.2 ≤ y < 6.3."],
          difficulty: "warmup",
          guideRef: "error-intervals",
          hints: ["What does 6.29 truncate to? And 6.3?"],
        },
        {
          kind: "short",
          id: "number-bounds-p2-q04",
          question: "By rounding each number to 1 significant figure, work out an estimate for {{3.94^2 * 0.0486}}.",
          answer: { type: "number", value: 0.8 },
          traps: [{ spec: { type: "number", value: 0.4 }, feedback: "Square first: {{4^2 = 16}}, then 16 × 0.05 = 0.8. Did you do 4 × 2 × 0.05?" }],
          solution: ["3.94 ≈ 4 and 0.0486 ≈ 0.05.", "{{4^2 = 16}}.", "16 × 0.05 = 0.8."],
          difficulty: "warmup",
          guideRef: "rounding-estimation",
          hints: ["0.0486 to 1 s.f. is 0.05. Multiplying by 0.05 is the same as dividing by 20."],
          strategy: "Estimate first",
        },
        {
          kind: "short",
          id: "number-bounds-p2-q05",
          question:
            "The Venn diagram shows the prime factors of two numbers, A and B.\n\nWork out the HCF and the LCM of A and B. Give the HCF first.",
          diagram: primeVenn,
          answer: { type: "list", values: [12, 118800], ordered: true, display: "HCF = 12, LCM = 118 800" },
          traps: [
            { spec: { type: "list", values: [12, 1425600], ordered: true }, feedback: "1 425 600 = A × B counts the overlap twice. The LCM multiplies each number in the diagram exactly once." },
          ],
          solution: [
            "HCF = product of the overlap = 2 × 2 × 3 = 12.",
            "LCM = product of every number in the diagram = 2 × 2 × 5 × 5 × 2 × 2 × 3 × 3 × 3 × 11.",
            "{{= 2^4 * 3^3 * 5^2 * 11 = 16 * 27 * 25 * 11}} = 118 800.",
          ],
          difficulty: "core",
          guideRef: "prime-factors-hcf-lcm",
          hints: ["Which region holds the factors A and B share?", "The LCM uses every number in the diagram once."],
          strategy: "Prime-factor Venn diagram",
        },
        {
          kind: "short",
          id: "number-bounds-p2-q06",
          question: "Find the smallest positive integer k such that 540k is a square number.",
          answer: { type: "number", value: 15 },
          traps: [
            { spec: { type: "number", value: 540 }, feedback: "540 × 540 is square, but not the *smallest* choice. Look at which prime powers in 540 are odd." },
            { spec: { type: "number", value: 5 }, feedback: "{{540 * 5 = 2^2 * 3^3 * 5^2}}: the power of 3 is still odd. You also need another 3." },
          ],
          solution: ["{{540 = 2^2 * 3^3 * 5}}.", "A square needs every prime power even.", "Need one more 3 and one more 5: k = 3 × 5 = 15.", "Check: {{540 * 15 = 8100 = 90^2}}."],
          difficulty: "core",
          guideRef: "prime-factors-hcf-lcm",
          hints: ["Write 540 as a product of prime factors in index form.", "In a square number, every prime appears an even number of times."],
          strategy: "Prime factors reveal structure",
        },
        {
          kind: "short",
          id: "number-bounds-p2-q07",
          question: "The HCF of two numbers is 6 and their LCM is 180. One of the numbers is 36. Find the other number.",
          answer: { type: "number", value: 30 },
          traps: [{ spec: { type: "number", value: 5 }, feedback: "180 ÷ 36 = 5 — but then HCF(36, 5) = 1, not 6. Use HCF × LCM = product of the two numbers." }],
          solution: ["For two numbers, HCF × LCM = product of the numbers.", "6 × 180 = 1080.", "1080 ÷ 36 = 30.", "Check: HCF(36, 30) = 6 and LCM(36, 30) = 180. ✓"],
          solutions: [
            { label: "Prime factors", steps: ["{{36 = 2^2 * 3^2}}, {{6 = 2 * 3}}, {{180 = 2^2 * 3^2 * 5}}.", "The other number must contain 5 (from the LCM), and exactly one 2 and one 3 (so the HCF is 6 and not more).", "{{2 * 3 * 5}} = 30."] },
          ],
          difficulty: "core",
          guideRef: "prime-factors-hcf-lcm",
          hints: ["Try it with 4 and 6: HCF = 2, LCM = 12. Compare HCF × LCM with 4 × 6.", "HCF × LCM = A × B for any two numbers."],
          strategy: "Try small cases",
        },
        {
          kind: "short",
          id: "number-bounds-p2-q08",
          question: "Use your calculator to work out {{(5.2^3 - sqrt(40))/(1.8 * 6.25)}}. Give your answer correct to 3 significant figures.",
          answer: { type: "number", value: 11.9 },
          traps: [{ spec: { type: "number", value: 11.94, tolerance: 0.005 }, feedback: "Right value, but give it to 3 significant figures: 11.9." }],
          solution: ["{{5.2^3}} = 140.608; {{sqrt(40)}} = 6.3245…", "Numerator: 134.2834…", "Denominator: 1.8 × 6.25 = 11.25.", "134.2834… ÷ 11.25 = 11.936… = 11.9 (3 s.f.)."],
          difficulty: "core",
          guideRef: "rounding-estimation",
          hints: ["Work out the numerator and denominator separately, keeping full calculator accuracy.", "Round only at the very end."],
        },
        {
          kind: "short",
          id: "number-bounds-p2-q09",
          question: "A bag of rice has a mass of 245 g, correct to the nearest 5 g. Write down the lower bound and the upper bound of its mass, in that order, in grams.",
          answer: { type: "list", values: [242.5, 247.5], ordered: true, display: "242.5 g and 247.5 g" },
          traps: [{ spec: { type: "list", values: [244.5, 245.5], ordered: true }, feedback: "That would be 'to the nearest gram'. To the nearest 5 g means half of 5 g, 2.5 g, either side." }],
          solution: ["The unit of accuracy is 5 g; half of it is 2.5 g.", "245 − 2.5 = 242.5 g and 245 + 2.5 = 247.5 g."],
          difficulty: "core",
          guideRef: "error-intervals",
          hints: ["What is the unit of accuracy here? Halve it.", "245 ± 2.5."],
          strategy: "Half the unit either side",
        },
        {
          kind: "short",
          id: "number-bounds-p2-q10",
          question: "a = 6.4 and b = 2.8, each correct to 1 decimal place. Work out the lower bound of a − b.",
          answer: { type: "number", value: 3.5 },
          traps: [
            { spec: { type: "number", value: 3.6 }, feedback: "6.35 − 2.75 = 3.6 uses lower − lower. To make a difference small, subtract as *much* as you can: 6.35 − 2.85." },
            { spec: { type: "number", value: 3.7 }, feedback: "This is the upper bound (6.45 − 2.75). The lower bound is lower a − upper b." },
          ],
          solution: ["Lower bound of a − b = lower a − upper b.", "6.35 − 2.85 = 3.5."],
          difficulty: "core",
          guideRef: "bounds-calculations",
          hints: ["To make a subtraction as small as possible, start small and take away a lot.", "Which bound of b takes away the most?"],
          strategy: "Consider extremes",
        },
        {
          kind: "short",
          id: "number-bounds-p2-q11",
          question:
            "The radius of a circular hawker-centre table is 4.7 dm, correct to 1 decimal place. Work out the lower bound for the area of the table top. Give your answer in dm² correct to 3 significant figures.",
          answer: { type: "number", value: 67.9 },
          traps: [{ spec: { type: "number", value: 69.4, tolerance: 0.05 }, feedback: "That's {{pi * 4.7^2}} with the rounded radius. Use the lower bound of the radius, 4.65 dm." }],
          solution: ["Lower bound of radius = 4.65 dm.", "{{pi * 4.65^2}} = 67.929… = 67.9 dm² (3 s.f.)."],
          difficulty: "core",
          guideRef: "bounds-calculations",
          hints: ["Which value of the radius gives the smallest area?", "Square 4.65, then multiply by π."],
          strategy: "Consider extremes",
        },
        {
          kind: "written",
          id: "number-bounds-p2-q12",
          question:
            "Marcus measures a length x as 5.3 cm, correct to 1 decimal place. He writes the error interval as\n\n    5.25 ≤ x ≤ 5.35\n\nExplain what is wrong with Marcus's error interval and write the correct one.",
          marks: 2,
          modelAnswer:
            "The upper end should use a strict inequality: 5.35 would round up to 5.4, so x cannot equal 5.35. The correct error interval is 5.25 ≤ x < 5.35.",
          markScheme: [
            { point: "Explains 5.35 rounds to 5.4 (so it is not included / should be <)", keywords: ["5.4", "rounds up", "not included", "strict", "less than"] },
            { point: "Correct interval 5.25 ≤ x < 5.35", keywords: ["5.25 ≤ x < 5.35", "< 5.35", "5.25"] },
          ],
          commonError: "Thinking the lower bound should also be strict — 5.25 does round to 5.3, so ≤ is right there.",
          difficulty: "core",
          guideRef: "error-intervals",
          hints: ["Round 5.35 to 1 d.p. — what do you get?", "Which end of the interval is included, and which isn't?"],
        },
        {
          kind: "written",
          id: "number-bounds-p2-q13",
          question:
            "A lift in an HDB block has a maximum safe load of 630 kg, correct to the nearest 10 kg. Eight people get in. Each has a mass of 78 kg, correct to the nearest kilogram.\n\nCan you be sure the lift is safe? You must show your working.",
          marks: 3,
          modelAnswer:
            "The heaviest the eight people could be is 8 × 78.5 = 628 kg (upper bound).\n\nThe smallest the maximum load could be is 625 kg (lower bound).\n\nSince 628 > 625, the total mass might exceed the safe load, so you cannot be sure the lift is safe.",
          markScheme: [
            { point: "Upper bound of total mass 8 × 78.5 = 628 kg", keywords: ["78.5", "628"] },
            { point: "Lower bound of safe load 625 kg", keywords: ["625"] },
            { point: "Compares (628 > 625) and concludes it cannot be guaranteed safe", keywords: ["not sure", "cannot", "can't", "might", "may", "not safe", "628 > 625"] },
          ],
          commonError: "Comparing 8 × 78 = 624 with 630 and saying it is safe — ignoring the bounds.",
          difficulty: "core",
          guideRef: "bounds-calculations",
          hints: ["Worst case: the people as heavy as possible and the limit as low as possible.", "Upper bound of one person = 78.5 kg. Lower bound of the limit = ?", "Compare 8 × 78.5 with 625."],
          strategy: "Consider extremes (worst case)",
        },
        {
          kind: "short",
          id: "number-bounds-p2-q14",
          question:
            "In the right-angled triangle shown, the side opposite θ is 5.4 cm and the side adjacent to θ is 8.2 cm, each correct to 1 decimal place.\n\nWork out the lower bound for the angle θ. Give your answer in degrees correct to 1 decimal place.",
          diagram: trigBounds,
          answer: { type: "number", value: 33.0, display: "33.0°" },
          traps: [
            { spec: { type: "number", value: 33.8 }, feedback: "That's the upper bound (5.45 over 8.15). For the smallest angle, make tan θ smallest: smallest opposite over largest adjacent." },
            { spec: { type: "number", value: 33.4 }, feedback: "That uses the rounded lengths. Use the bounds: 5.35 and 8.25." },
          ],
          solution: [
            "{{tan theta = opp/adj}}; θ is smallest when {{opp/adj}} is smallest.",
            "Use the lower bound of the opposite (5.35) and the upper bound of the adjacent (8.25).",
            "{{tan theta = 5.35/8.25}} = 0.64848…",
            "θ = {{tan^(-1)(0.64848)}} = 32.96… = 33.0° (1 d.p.).",
          ],
          commonError: "Using both lower bounds — dividing by a smaller adjacent makes tan θ bigger, not smaller.",
          difficulty: "challenge",
          guideRef: "bounds-calculations",
          hints: ["Which trig ratio links the opposite and adjacent sides?", "As tan θ gets smaller, does θ get smaller? So minimise the fraction.", "Smallest fraction = smallest top ÷ biggest bottom."],
          strategy: "Consider extremes",
        },
        {
          kind: "written",
          id: "number-bounds-p2-q15",
          question:
            "(a) Show that 1001 = 7 × 11 × 13.\n\n(b) Hence explain why every six-digit number of the form *abcabc* (for example 572 572) is divisible by 7, by 11 and by 13.",
          marks: 4,
          modelAnswer:
            "(a) 7 × 11 = 77 and 77 × 13 = 1001.\n\n(b) The number abcabc = abc × 1000 + abc = abc × 1001. For example 572 572 = 572 × 1001.\n\nSince 1001 = 7 × 11 × 13, abcabc = abc × 7 × 11 × 13, so 7, 11 and 13 are all factors of it.",
          markScheme: [
            { point: "Shows 7 × 11 × 13 = 1001 (e.g. 77 × 13)", keywords: ["77", "1001", "77 × 13", "91 × 11", "143 × 7"] },
            { point: "Writes abcabc as abc × 1000 + abc", keywords: ["1000", "× 1000", "abc000"] },
            { point: "So abcabc = abc × 1001", keywords: ["× 1001", "abc × 1001", "572 × 1001"] },
            { point: "Concludes 7, 11 and 13 are factors because they are factors of 1001", keywords: ["factor", "divisible", "7 × 11 × 13"] },
          ],
          commonError: "Checking one example (572 572 ÷ 7 = 81 796) — that shows it works once, not always.",
          difficulty: "challenge",
          guideRef: "number-problems",
          hints: ["For (b), split abcabc into abc000 + abc.", "abc000 = abc × 1000. Factorise abc × 1000 + abc.", "abc × 1001 — and you know the factors of 1001."],
          strategy: "Introduce a variable",
        },
      ],
    },
  ],

  // -------------------------------------------------------------- challenge
  challenge: [
    {
      kind: "short",
      id: "number-bounds-ch-q01",
      question: "How many positive factors does 720 have (including 1 and 720)?",
      answer: { type: "number", value: 30 },
      traps: [
        { spec: { type: "number", value: 15 }, feedback: "(4 + 1)(2 + 1) = 15 forgets the prime 5. It gives two choices too (use it or not): (4 + 1)(2 + 1)(1 + 1)." },
        { spec: { type: "number", value: 8 }, feedback: "4 × 2 × 1 multiplies the powers. But each power can be chosen from 0 up to k — that's k + 1 choices." },
      ],
      solution: [
        "{{720 = 2^4 * 3^2 * 5}}.",
        "A factor is {{2^a * 3^b * 5^c}} with a ∈ {0,…,4}, b ∈ {0,1,2}, c ∈ {0,1}.",
        "Number of choices: 5 × 3 × 2 = 30.",
      ],
      solutions: [
        { label: "Prime-power counting", steps: ["{{720 = 2^4 * 3^2 * 5}}.", "(4 + 1)(2 + 1)(1 + 1) = 30."] },
        { label: "Factor pairs (slower, but checks it)", steps: ["Pair factors: 1 × 720, 2 × 360, 3 × 240, 4 × 180, 5 × 144, 6 × 120, 8 × 90, 9 × 80, 10 × 72, 12 × 60, 15 × 48, 16 × 45, 18 × 40, 20 × 36, 24 × 30.", "15 pairs and 720 isn't square, so 30 factors. The prime-power method is far quicker and can't miss a pair."] },
      ],
      difficulty: "challenge",
      guideRef: "prime-factors-hcf-lcm",
      hints: [
        "Write 720 in prime-factor index form.",
        "Every factor is built by choosing how many 2s, 3s and 5s to use.",
        "How many choices for the power of 2? (Don't forget zero.)",
        "Multiply the number of choices: product rule.",
      ],
      strategy: "Product rule for counting",
    },
    {
      kind: "short",
      id: "number-bounds-ch-q02",
      question: "Find the smallest positive integer n such that 1512n is a cube number.",
      answer: { type: "number", value: 49 },
      traps: [
        { spec: { type: "number", value: 7 }, feedback: "{{1512 * 7 = 2^3 * 3^3 * 7^2}} — the power of 7 is 2, not a multiple of 3. You need two more 7s." },
      ],
      solution: [
        "{{1512 = 2^3 * 3^3 * 7}}.",
        "For a cube, every prime power must be a multiple of 3.",
        "2 and 3 are fine; 7 needs two more: n = {{7^2}} = 49.",
        "Check: {{1512 * 49 = 74088 = 42^3}}.",
      ],
      difficulty: "challenge",
      guideRef: "prime-factors-hcf-lcm",
      hints: ["Prime-factorise 1512.", "In a cube, each prime appears a multiple of 3 times.", "Which prime falls short, and by how much?"],
      strategy: "Prime factors reveal structure",
    },
    {
      kind: "short",
      id: "number-bounds-ch-q03",
      question:
        "x and y are positive integers with x < y. The HCF of x and y is 12, the LCM of x and y is 360, and x + y = 132. Find x and y. Give x first.",
      answer: { type: "list", values: [60, 72], ordered: true, display: "x = 60, y = 72" },
      traps: [
        { spec: { type: "list", values: [12, 360], ordered: true }, feedback: "12 and 360 have the right HCF and LCM, but they add to 372, not 132." },
      ],
      solution: [
        "Write x = 12a, y = 12b where a and b share no common factor.",
        "LCM = 12ab = 360, so ab = 30.",
        "x + y = 12(a + b) = 132, so a + b = 11.",
        "a and b multiply to 30 and add to 11: a = 5, b = 6.",
        "x = 60, y = 72. Check: HCF(60, 72) = 12, LCM = 360. ✓",
      ],
      difficulty: "challenge",
      guideRef: "prime-factors-hcf-lcm",
      hints: [
        "Both numbers are multiples of 12 — write them as 12a and 12b.",
        "Why must a and b have no common factor?",
        "Use the LCM to find ab, and the sum to find a + b.",
      ],
      strategy: "Introduce a variable",
    },
    {
      kind: "short",
      id: "number-bounds-ch-q04",
      question: "How many positive whole numbers round to 1000 when rounded to 1 significant figure?",
      answer: { type: "number", value: 550 },
      traps: [
        { spec: { type: "number", value: 1000 }, feedback: "You used 500 ≤ n < 1500. But 1 s.f. below 1000 means the nearest 100: 900-something numbers round to 900 unless they are 950 or more." },
        { spec: { type: "number", value: 100 }, feedback: "That's 950 to 1049 — as if it were 'to the nearest 100' on both sides. Above 1000, 1 s.f. means the nearest *thousand*, so up to 1499 round to 1000." },
      ],
      solution: [
        "Below 1000, numbers have 3 digits, so 1 s.f. means the nearest 100: 950 to 999 round up to 1000 (949 rounds to 900).",
        "From 1000 up, 1 s.f. means the nearest 1000: 1000 to 1499 round to 1000 (1500 rounds to 2000).",
        "So 950 ≤ n ≤ 1499: 1499 − 950 + 1 = 550 numbers.",
      ],
      commonError: "Assuming the interval is symmetric about 1000. The size of 'one significant figure' changes at the power of 10.",
      difficulty: "challenge",
      guideRef: "rounding-estimation",
      hints: [
        "What does 970 round to at 1 s.f.? And 1400?",
        "The unit of accuracy is different just below 1000 and just above it.",
        "Find the smallest and largest whole numbers that work, then count.",
      ],
      strategy: "Consider extremes",
    },
    {
      kind: "short",
      id: "number-bounds-ch-q05",
      question:
        "x rounded to 2 significant figures is 3.7. Also, when 10x is truncated to a whole number, the result is 36.\n\nFind the error interval for x. Give the lower bound and then the upper bound.",
      answer: { type: "list", values: [3.65, 3.7], ordered: true, display: "3.65 ≤ x < 3.7" },
      traps: [
        { spec: { type: "list", values: [3.65, 3.75], ordered: true }, feedback: "That's the rounding condition alone. The truncation condition cuts it down further." },
        { spec: { type: "list", values: [3.6, 3.7], ordered: true }, feedback: "That's the truncation condition alone (3.6 ≤ x < 3.7). x must satisfy both — take the overlap." },
      ],
      solution: [
        "Rounding: 3.65 ≤ x < 3.75.",
        "Truncation: 36 ≤ 10x < 37, so 3.6 ≤ x < 3.7.",
        "Both must hold — the overlap is 3.65 ≤ x < 3.7.",
      ],
      difficulty: "challenge",
      guideRef: "error-intervals",
      hints: ["Write an error interval for each fact separately.", "If 10x truncates to 36, what can 10x be? Then divide by 10.", "Draw both intervals on a number line and find where they overlap."],
      strategy: "Draw a diagram (number line)",
    },
    {
      kind: "short",
      id: "number-bounds-ch-q06",
      question:
        "For a lens, {{f = (uv)/(u + v)}}. u = 12 cm and v = 20 cm, both correct to the nearest centimetre.\n\nWork out the upper bound of f. Give your answer correct to 3 significant figures.",
      answer: { type: "number", value: 7.77 },
      traps: [
        { spec: { type: "number", value: 8.27, tolerance: 0.005 }, feedback: "You used upper bounds on top and lower bounds below — but u and v can't be 12.5 and 11.5 at the same time. Each letter takes ONE value." },
        { spec: { type: "number", value: 7.5 }, feedback: "That's the value from the rounded measurements, not the upper bound." },
      ],
      solution: [
        "Rewrite: {{1/f = 1/u + 1/v}}, so {{f = 1/(1/u + 1/v)}}.",
        "Larger u and v make {{1/u + 1/v}} smaller, so f larger. So f is greatest when u and v are both at their upper bounds.",
        "{{f = (12.5 * 20.5)/(12.5 + 20.5) = 256.25/33}} = 7.765… = 7.77 (3 s.f.).",
      ],
      solutions: [
        { label: "Reciprocal form", steps: ["{{1/f = 1/u + 1/v}} — f increases as u and v increase.", "Use u = 12.5, v = 20.5: f = 7.77."] },
        { label: "Test the extremes", steps: ["(12.5, 20.5): 7.765", "(11.5, 19.5): 7.234", "(12.5, 19.5): 7.617; (11.5, 20.5): 7.367", "Largest is 7.765 → 7.77."] },
      ],
      commonError: "Mixing bounds for the same letter: u = 12.5 on top but u = 11.5 underneath.",
      difficulty: "challenge",
      guideRef: "bounds-calculations",
      hints: [
        "u and v both appear on the top and the bottom. Can you use different bounds for the same letter?",
        "Divide top and bottom by uv. What does f look like now?",
        "{{f = 1/(1/u + 1/v)}}. What happens to f as u grows?",
      ],
      strategy: "Change the form",
    },
    {
      kind: "short",
      id: "number-bounds-ch-q07",
      question:
        "The period of a pendulum is {{T = 2 pi sqrt(L/g)}}. L = 0.80 m, correct to 2 significant figures, and g = 9.8 m/s², correct to 1 decimal place.\n\nWork out the lower bound for T. Give your answer in seconds correct to 3 significant figures.",
      answer: { type: "number", value: 1.79 },
      traps: [
        { spec: { type: "number", value: 1.80, tolerance: 0.004 }, feedback: "Check your bounds: L to 2 s.f. means ±0.005 (so 0.795), and for the smallest T divide by the *largest* g, 9.85." },
      ],
      solution: [
        "Bounds: 0.795 ≤ L < 0.805 and 9.75 ≤ g < 9.85.",
        "T is smallest when L/g is smallest: lower L, upper g.",
        "{{T = 2 pi sqrt(0.795/9.85)}} = 2π × 0.28409… = 1.785… = 1.79 s (3 s.f.).",
      ],
      commonError: "Taking L = 0.80 to mean the nearest 0.1 (bounds 0.75 and 0.85). The trailing zero is significant: 0.80 is to the nearest 0.01.",
      difficulty: "challenge",
      guideRef: "bounds-calculations",
      hints: [
        "0.80 to 2 s.f. — what is the unit of accuracy? (The zero matters.)",
        "T increases when L/g increases. So which bounds minimise T?",
        "Lower L, upper g.",
      ],
      strategy: "Consider extremes",
    },
    {
      kind: "short",
      id: "number-bounds-ch-q08",
      question:
        "Siti has a tank holding 20 litres of iced bandung, correct to the nearest litre. She fills cups that each hold 250 ml, correct to the nearest 10 ml.\n\nWhat is the greatest number of full cups she can be **certain** of filling?",
      answer: { type: "number", value: 76 },
      traps: [
        { spec: { type: "number", value: 80 }, feedback: "20 000 ÷ 250 = 80 ignores the bounds. To be certain, assume the least drink and the biggest cups." },
        { spec: { type: "number", value: 83 }, feedback: "That's the most she *might* fill (most drink, smallest cups). To be certain, use the worst case: 19.5 L and 255 ml cups." },
        { spec: { type: "number", value: 77 }, feedback: "19 500 ÷ 255 = 76.47…, and the 77th cup can't be completely filled. Round *down* for full cups." },
      ],
      solution: [
        "Worst case: least drink, biggest cups.",
        "Lower bound of drink: 19.5 L = 19 500 ml. Upper bound of a cup: 255 ml.",
        "19 500 ÷ 255 = 76.47…",
        "She can be certain of 76 full cups.",
      ],
      commonError: "Rounding 76.47 to the nearest whole number and then not checking: here it happens to round down, but you must always round *down* for 'full cups'.",
      difficulty: "challenge",
      guideRef: "bounds-calculations",
      hints: ["'Certain' means the worst case. What is the worst case for the drink? For the cup size?", "Convert to the same units.", "Can a part-filled cup count?"],
      strategy: "Consider extremes (worst case)",
    },
    {
      kind: "short",
      id: "number-bounds-ch-q09",
      question: "How many four-digit **even** numbers have all four digits different?",
      answer: { type: "number", value: 2296 },
      traps: [
        { spec: { type: "number", value: 2520 }, feedback: "9 × 8 × 7 × 5 picks the first digit before knowing whether 0 has been used as the last digit. Split into cases: last digit 0, or last digit 2/4/6/8." },
        { spec: { type: "number", value: 2240 }, feedback: "You've treated every even last digit like 2/4/6/8. When the last digit is 0, the first digit has 9 choices, not 8." },
      ],
      solution: [
        "Fill the most restricted places first and split into cases.",
        "Case 1: last digit 0. First digit: 9 choices, then 8, then 7: 9 × 8 × 7 = 504.",
        "Case 2: last digit 2, 4, 6 or 8 (4 choices). First digit: not 0 and not the last digit: 8 choices. Then 8, then 7: 4 × 8 × 8 × 7 = 1792.",
        "Total: 504 + 1792 = 2296.",
      ],
      solutions: [
        { label: "Complement", steps: ["Four-digit numbers with distinct digits: 9 × 9 × 8 × 7 = 4536.", "Odd ones (last digit 1, 3, 5, 7, 9): last 5 choices, first 8 (not 0, not last), then 8, 7: 5 × 8 × 8 × 7 = 2240.", "Even = 4536 − 2240 = 2296."] },
      ],
      difficulty: "challenge",
      guideRef: "number-problems",
      hints: [
        "Which positions have restrictions? Fill those first.",
        "The first digit can't be 0, and the last must be even — but 0 is even. Does that cause a clash?",
        "Split into two cases: last digit 0, and last digit 2, 4, 6 or 8.",
      ],
      strategy: "Split into cases",
    },
    {
      kind: "short",
      id: "number-bounds-ch-q10",
      question: "How many digits does the number {{2^20 * 5^17}} have when written out in full?",
      answer: { type: "number", value: 18 },
      traps: [
        { spec: { type: "number", value: 17 }, feedback: "{{10^17}} has 18 digits (a 1 followed by 17 zeros). And here it's {{8 * 10^17}}." },
        { spec: { type: "number", value: 37 }, feedback: "You added the powers. Pair each 5 with a 2 to make 10s." },
      ],
      solution: [
        "Pair up 2s and 5s: {{2^20 * 5^17 = 2^3 * (2 * 5)^17 = 8 * 10^17}}.",
        "{{8 * 10^17}} is an 8 followed by 17 zeros.",
        "That is 18 digits.",
      ],
      difficulty: "challenge",
      guideRef: "number-problems",
      hints: ["What is 2 × 5?", "How many 2–5 pairs can you make? What's left over?", "How many digits does {{8 * 10^3}} have? Generalise."],
      strategy: "Make it simpler",
    },
  ],
};
