import type { TopicPractice } from "../../types.ts";

// Diagram plotted exactly from y = x² − x + 3 and its tangent y = 3x − 1 at (2, 5) (generated, then pasted).
const tangentThroughPoints = `__TANSVG__`;

export const practice: TopicPractice = {
  // =========================================================================
  // Quick-check quiz — 10 questions (3 mcq, 7 short) across the main sections
  // =========================================================================
  quiz: [
    {
      kind: "short",
      id: "calculus-quiz-q01",
      question: "Find {{dy/dx}} when y = 4x³ − 5x² + 7x − 2.",
      answer: { type: "expression", expr: "12x^2-10x+7", display: "{{dy/dx = 12x^2 - 10x + 7}}" },
      solution: [
        "Differentiate term by term: multiply by the power, then reduce the power by one.",
        "4x³ → 12x², −5x² → −10x, 7x → 7, −2 → 0.",
        "{{dy/dx = 12x^2 - 10x + 7}}.",
      ],
      traps: [
        { spec: { type: "expression", expr: "12x^2-10x+7x" }, feedback: "7x differentiates to 7 (its power 1 drops to 0, and {{x^0 = 1}}). The x disappears." },
        { spec: { type: "expression", expr: "12x^2-10x+5" }, feedback: "A constant term has gradient 0, so −2 vanishes — it doesn't combine with the 7." },
      ],
      commonError: "Leaving an x on the 7, or keeping the constant −2.",
      difficulty: "warmup",
      guideRef: "differentiating-powers",
      hints: ["For {{ax^n}}, the derivative is {{nax^(n-1)}}. Do one term at a time.", "What happens to a term with no x at all?"],
      strategy: "Make it simpler",
    },
    {
      kind: "mcq",
      id: "calculus-quiz-q02",
      question:
        "Points P(3, 9) and Q(3.1, 9.61) lie on the curve y = x². The chord PQ has gradient 6.1. Q is now moved along the curve closer and closer to P. What value does the gradient of PQ get closer and closer to?",
      options: ["6", "6.1", "9", "3"],
      answerIndex: 0,
      explanation:
        "As Q slides towards P, the chord turns into the tangent at P, and the chord gradient approaches the gradient of the curve at x = 3. For y = x², {{dy/dx = 2x}}, so the limit is 2 × 3 = 6. (Try Q at x = 3.01: {{(9.0601 - 9)/0.01 = 6.01}}.) 6.1 is just this particular chord. 9 is the y-coordinate of P, not a gradient. 3 is the x-coordinate.",
      difficulty: "warmup",
      guideRef: "gradient-of-a-curve",
      hints: ["Try Q at x = 3.01 and work out the chord gradient. Then x = 3.001.", "What line does the chord become when Q reaches P?"],
      strategy: "Try small cases",
    },
    {
      kind: "short",
      id: "calculus-quiz-q03",
      question: "y = (2x + 1)(x − 3). Find {{dy/dx}}.",
      answer: { type: "expression", expr: "4x-5", display: "{{dy/dx = 4x - 5}}" },
      solution: [
        "Expand first: (2x + 1)(x − 3) = 2x² − 6x + x − 3 = 2x² − 5x − 3.",
        "Differentiate: {{dy/dx = 4x - 5}}.",
      ],
      traps: [
        { spec: { type: "expression", expr: "2" }, feedback: "You can't differentiate each bracket and multiply (2 × 1 = 2). Expand the brackets first, then differentiate term by term." },
        { spec: { type: "expression", expr: "4x-7" }, feedback: "Check the expansion: the x-terms are −6x + x = −5x, so the derivative has −5." },
      ],
      commonError: "Differentiating each bracket separately and multiplying the results.",
      difficulty: "core",
      guideRef: "differentiating-powers",
      hints: ["The rule works on single powers of x. Can you turn the product into a sum of powers?", "Expand the brackets, collect like terms, then differentiate."],
      strategy: "Make it simpler",
    },
    {
      kind: "short",
      id: "calculus-quiz-q04",
      question: "Work out the gradient of the curve y = x³ − 4x at the point where x = 2.",
      answer: { type: "number", value: 8 },
      solution: ["{{dy/dx = 3x^2 - 4}}.", "At x = 2: 3 × 4 − 4 = 8."],
      traps: [
        { spec: { type: "number", value: 0 }, feedback: "0 is the **y-coordinate** at x = 2 (8 − 8). The gradient comes from substituting into {{dy/dx}}, not into y." },
        { spec: { type: "number", value: 2 }, feedback: "Check the derivative: x³ → 3x², so at x = 2 you get 3 × 4 = 12, then subtract 4." },
      ],
      commonError: "Substituting into the equation of the curve instead of into dy/dx.",
      difficulty: "core",
      guideRef: "tangents",
      hints: ["The gradient at a point comes from the gradient function. Find it first.", "Substitute x = 2 into {{dy/dx}}, not into y."],
    },
    {
      kind: "short",
      id: "calculus-quiz-q05",
      question: "Find the equation of the tangent to the curve y = x² − 3x + 1 at the point where x = 4. Give your answer in the form y = mx + c.",
      answer: { type: "equation", eq: "y=5x-15", display: "y = 5x − 15" },
      solution: [
        "Point: y = 16 − 12 + 1 = 5, so (4, 5).",
        "Gradient: {{dy/dx = 2x - 3}} = 8 − 3 = 5.",
        "y − 5 = 5(x − 4), so y = 5x − 15.",
      ],
      traps: [
        { spec: { type: "equation", eq: "y=5x-20" }, feedback: "Nearly: y − 5 = 5(x − 4) gives y = 5x − 20 **+ 5**. Don't forget to add the 5 back." },
        { spec: { type: "equation", eq: "y=5x+5" }, feedback: "The line must pass through (4, 5). Check: 5 × 4 + 5 = 25, not 5. Use y − 5 = 5(x − 4)." },
      ],
      commonError: "Using the gradient function 2x − 3 as the gradient of the line instead of its value at x = 4.",
      difficulty: "core",
      guideRef: "tangents",
      hints: ["A line needs a point and a gradient. What is the y-coordinate when x = 4?", "Find the gradient by substituting x = 4 into {{dy/dx}}.", "Use y − y₁ = m(x − x₁)."],
      strategy: "Break it into steps",
    },
    {
      kind: "short",
      id: "calculus-quiz-q06",
      question: "Find the coordinates of the turning point of the curve y = x² − 6x + 11. Give your answer as (x, y).",
      answer: { type: "list", values: [3, 2], ordered: true, display: "(3, 2)" },
      solution: [
        "At a turning point {{dy/dx = 0}}: 2x − 6 = 0, so x = 3.",
        "y = 9 − 18 + 11 = 2.",
        "Turning point (3, 2).",
      ],
      solutions: [
        { label: "Complete the square", steps: ["x² − 6x + 11 = {{(x - 3)^2 + 2}}.", "Minimum when x = 3, giving y = 2: (3, 2). Same answer — a good check."] },
      ],
      traps: [{ spec: { type: "list", values: [3, 0], ordered: true }, feedback: "{{dy/dx}} is 0 at the turning point, but the **y-coordinate** comes from putting x = 3 into the curve's equation." }],
      commonError: "Giving the gradient (0) as the y-coordinate.",
      difficulty: "core",
      guideRef: "turning-points",
      hints: ["What is the gradient at the bottom of a U-shaped curve?", "Solve {{dy/dx = 0}}, then substitute x back into y."],
      strategy: "Check by substituting",
    },
    {
      kind: "mcq",
      id: "calculus-quiz-q07",
      question: "The curve y = x³ − 12x has a turning point at x = 2. Which statement is correct?",
      options: [
        "It is a maximum, because {{(d^2y)/(dx^2) = 12}} is positive",
        "It is a maximum, because {{dy/dx = 0}} there",
        "It is a minimum, because y = −16 is negative",
        "It is a minimum, because {{(d^2y)/(dx^2) = 12}} is positive",
      ],
      answerIndex: 3,
      explanation:
        "{{dy/dx = 3x^2 - 12}} and {{(d^2y)/(dx^2) = 6x}}, which is 12 at x = 2. Positive second derivative means the gradient is increasing through zero (− then +), so the curve is U-shaped there: a **minimum**. The 'maximum because 12 is positive' option has the rule backwards. {{dy/dx = 0}} only says it is a turning point, not which kind. The sign of y tells you nothing about the type of turning point.",
      difficulty: "core",
      guideRef: "turning-points",
      hints: ["Find {{(d^2y)/(dx^2)}} and evaluate it at x = 2.", "Positive second derivative: is the gradient increasing or decreasing as you pass through x = 2?"],
      strategy: "Eliminate options",
    },
    {
      kind: "short",
      id: "calculus-quiz-q08",
      question: "A particle moves along a straight line. Its displacement s metres from O after t seconds is s = t³ − 6t² + 9t. Work out its velocity when t = 4. Give your answer in m/s.",
      answer: { type: "number", value: 9 },
      solution: ["{{v = (ds)/(dt) = 3t^2 - 12t + 9}}.", "At t = 4: 48 − 48 + 9 = 9 m/s."],
      traps: [{ spec: { type: "number", value: 4 }, feedback: "4 m is the **displacement** at t = 4. Velocity is the rate of change of displacement: differentiate s first." }],
      commonError: "Substituting into s instead of into ds/dt.",
      difficulty: "core",
      guideRef: "kinematics",
      hints: ["Velocity is the rate of change of displacement. What does that mean you should do to s?", "Find {{(ds)/(dt)}}, then put t = 4."],
    },
    {
      kind: "short",
      id: "calculus-quiz-q09",
      question: "For the same particle, s = t³ − 6t² + 9t. Find the two times when the particle is instantaneously at rest. Give your answers in seconds.",
      answer: { type: "list", values: [1, 3], display: "t = 1 and t = 3" },
      solution: ["At rest means v = 0.", "3t² − 12t + 9 = 0 → t² − 4t + 3 = 0 → (t − 1)(t − 3) = 0.", "t = 1 s and t = 3 s."],
      traps: [{ spec: { type: "list", values: [0, 3] }, feedback: "Those are the times when s = 0 (the particle is **at O**). 'At rest' means the **velocity** is zero." }],
      commonError: "Solving s = 0 (at the origin) instead of v = 0 (at rest).",
      difficulty: "core",
      guideRef: "kinematics",
      hints: ["What is the velocity of a particle that is at rest?", "Set {{(ds)/(dt) = 0}} and divide through by 3.", "Factorise t² − 4t + 3."],
    },
    {
      kind: "mcq",
      id: "calculus-quiz-q10",
      question: "What is the gradient of the **normal** to the curve y = x² + 1 at the point where x = 2?",
      options: ["4", "{{-1/4}}", "{{1/4}}", "−4"],
      answerIndex: 1,
      explanation:
        "The tangent gradient is {{dy/dx = 2x = 4}}. The normal is perpendicular to the tangent, so its gradient is the negative reciprocal: {{-1/4}}. 4 is the tangent's gradient; −4 only changes the sign; {{1/4}} only flips. You need both: flip **and** change sign (product −1).",
      difficulty: "core",
      guideRef: "normals",
      hints: ["First find the gradient of the tangent at x = 2.", "Perpendicular gradients multiply to −1."],
      strategy: "Use the inverse",
    },
  ],

  // =========================================================================
  // Practice papers
  // =========================================================================
  papers: [
    {
      id: "calculus-p1",
      title: "Practice Paper 1",
      questions: [
        {
          kind: "short",
          id: "calculus-p1-q01",
          question: "y = 5x⁴. Find {{dy/dx}}.",
          answer: { type: "expression", expr: "20x^3", display: "{{dy/dx = 20x^3}}" },
          solution: ["Multiply by the power and reduce the power by one: 5 × 4 = 20, and 4 − 1 = 3.", "{{dy/dx = 20x^3}}."],
          traps: [
            { spec: { type: "expression", expr: "20x^4" }, feedback: "Bring the 4 down **and** reduce the power by one: {{20x^3}}." },
            { spec: { type: "expression", expr: "5x^3" }, feedback: "You reduced the power but forgot to multiply by it: 5 × 4 = 20." },
          ],
          difficulty: "warmup",
          guideRef: "differentiating-powers",
          hints: ["For {{ax^n}}, the derivative is {{nax^(n-1)}}."],
        },
        {
          kind: "short",
          id: "calculus-p1-q02",
          question: "y = 3x² − 8x + 6. Find {{dy/dx}}.",
          answer: { type: "expression", expr: "6x-8", display: "{{dy/dx = 6x - 8}}" },
          solution: ["3x² → 6x, −8x → −8, 6 → 0.", "{{dy/dx = 6x - 8}}."],
          traps: [{ spec: { type: "expression", expr: "6x-8+6" }, feedback: "The constant 6 is a horizontal shift up — it has gradient 0, so it disappears." }],
          difficulty: "warmup",
          guideRef: "differentiating-powers",
          hints: ["Differentiate one term at a time.", "A constant differentiates to 0."],
        },
        {
          kind: "short",
          id: "calculus-p1-q03",
          question:
            "Points A and B lie on the curve y = x³ with x-coordinates 2 and 2.1. Work out the gradient of the chord AB. Give your answer as an exact decimal.",
          answer: { type: "number", value: 12.61, allowFraction: false },
          solution: [
            "A = (2, 8) and B = (2.1, 9.261).",
            "Gradient = {{(9.261 - 8)/(2.1 - 2) = 1.261/0.1 = 12.61}}.",
            "Compare: the gradient of the curve at x = 2 is 3 × 2² = 12. The chord is a slight overestimate because the curve is getting steeper.",
          ],
          traps: [{ spec: { type: "number", value: 12 }, feedback: "12 is the gradient of the **tangent** at x = 2. The question asks for the chord between the two points: rise ÷ run." }],
          commonError: "Dividing by 2.1 instead of by the change in x, 0.1.",
          difficulty: "warmup",
          guideRef: "gradient-of-a-curve",
          hints: ["Find the y-coordinates of A and B first.", "Gradient = change in y ÷ change in x."],
        },
        {
          kind: "short",
          id: "calculus-p1-q04",
          question: "The point (1, 5) lies on the curve y = 2x² + 3x. Work out the gradient of the curve at this point.",
          answer: { type: "number", value: 7 },
          solution: ["{{dy/dx = 4x + 3}}.", "At x = 1: 4 + 3 = 7."],
          traps: [{ spec: { type: "number", value: 5 }, feedback: "5 is the y-coordinate. Substitute x = 1 into {{dy/dx}} to get the gradient." }],
          difficulty: "warmup",
          guideRef: "tangents",
          hints: ["Differentiate, then substitute the x-coordinate."],
        },
        {
          kind: "short",
          id: "calculus-p1-q05",
          question: "{{y = (x^4 + 6)/(x^2)}}. Find {{dy/dx}}.",
          answer: { type: "expression", expr: "2x-12/x^3", display: "{{dy/dx = 2x - 12/(x^3)}}" },
          solution: [
            "Split the fraction: {{y = x^4/x^2 + 6/x^2 = x^2 + 6x^(-2)}}.",
            "Differentiate: {{2x + 6 * (-2)x^(-3) = 2x - 12x^(-3)}}.",
            "{{dy/dx = 2x - 12/(x^3)}}.",
          ],
          traps: [
            { spec: { type: "expression", expr: "2x^2" }, feedback: "You can't differentiate the top and bottom separately ({{4x^3/(2x) = 2x^2}}). Split into separate powers of x first." },
            { spec: { type: "expression", expr: "2x-12/x" }, feedback: "{{6x^(-2)}} → {{-12x^(-3)}}: the power goes **down** by one, from −2 to −3." },
          ],
          commonError: "Reducing −2 to −1 instead of −3 (going 'down' means more negative).",
          difficulty: "core",
          guideRef: "differentiating-powers",
          hints: ["The rule only works on sums of powers of x. Can you split the fraction?", "{{6/(x^2) = 6x^(-2)}}.", "Reduce the power −2 by one: what do you get?"],
          strategy: "Make it simpler",
        },
        {
          kind: "short",
          id: "calculus-p1-q06",
          question: "y = (3x − 2)². Find {{dy/dx}}. Give your answer in the form ax + b.",
          answer: { type: "expression", expr: "18x-12", display: "{{dy/dx = 18x - 12}}" },
          solution: ["Expand: (3x − 2)² = 9x² − 12x + 4.", "Differentiate: {{dy/dx = 18x - 12}}."],
          traps: [
            { spec: { type: "expression", expr: "2(3x-2)" }, feedback: "Close, but the inside of the bracket has its own gradient (3). Expand first: 9x² − 12x + 4 → 18x − 12." },
            { spec: { type: "expression", expr: "18x" }, feedback: "(3x − 2)² is not 9x² + 4: you've lost the middle term. Expand as (3x − 2)(3x − 2)." },
          ],
          commonError: "Squaring each term: (3x − 2)² ≠ 9x² + 4.",
          difficulty: "core",
          guideRef: "differentiating-powers",
          hints: ["Write the square out as two brackets.", "Expand to get three terms, then differentiate each."],
          strategy: "Make it simpler",
        },
        {
          kind: "short",
          id: "calculus-p1-q07",
          question: "The curve C has equation y = x³ − 6x² + 5. Find the x-coordinates of the two points on C where the gradient is −9.",
          answer: { type: "list", values: [1, 3], display: "x = 1 and x = 3" },
          solution: [
            "{{dy/dx = 3x^2 - 12x}}.",
            "Set it equal to −9: 3x² − 12x + 9 = 0 → x² − 4x + 3 = 0.",
            "(x − 1)(x − 3) = 0, so x = 1 or x = 3.",
          ],
          traps: [{ spec: { type: "list", values: [-1, -3] }, feedback: "Sign check on the factorising: (x − 1)(x − 3) = 0 gives x = +1 and x = +3." }],
          commonError: "Setting y = −9 instead of dy/dx = −9.",
          difficulty: "core",
          guideRef: "tangents",
          hints: ["Which expression tells you the gradient at any x?", "Set {{dy/dx = -9}} and rearrange to '= 0'.", "Divide by 3 and factorise."],
          strategy: "Work backwards",
        },
        {
          kind: "short",
          id: "calculus-p1-q08",
          question: "Find the equation of the tangent to the curve y = x³ − 2x + 1 at the point where x = 2. Give your answer in the form y = mx + c.",
          answer: { type: "equation", eq: "y=10x-15", display: "y = 10x − 15" },
          solution: [
            "Point: y = 8 − 4 + 1 = 5, so (2, 5).",
            "Gradient: {{dy/dx = 3x^2 - 2}} = 12 − 2 = 10.",
            "y − 5 = 10(x − 2) → y = 10x − 15.",
          ],
          traps: [
            { spec: { type: "equation", eq: "y=12x-19" }, feedback: "Check the gradient: 3 × 2² = 12, then **subtract 2** to get 10." },
            { spec: { type: "equation", eq: "y=10x-20" }, feedback: "Expand y − 5 = 10(x − 2) carefully: y = 10x − 20 + 5." },
          ],
          difficulty: "core",
          guideRef: "tangents",
          hints: ["You need a point and a gradient.", "y-coordinate from the curve; gradient from {{dy/dx}} at x = 2.", "Then y − y₁ = m(x − x₁)."],
          strategy: "Break it into steps",
        },
        {
          kind: "short",
          id: "calculus-p1-q09",
          question: "The curve y = 2x³ − 3x² − 12x + 4 has two turning points. Find the coordinates of the **minimum** point. Give your answer as (x, y).",
          answer: { type: "list", values: [2, -16], ordered: true, display: "(2, −16)" },
          solution: [
            "{{dy/dx = 6x^2 - 6x - 12 = 6(x - 2)(x + 1)}}, so turning points at x = 2 and x = −1.",
            "{{(d^2y)/(dx^2) = 12x - 6}}: at x = 2 it is 18 > 0 → minimum; at x = −1 it is −18 < 0 → maximum.",
            "At x = 2: y = 16 − 12 − 24 + 4 = −16. Minimum (2, −16).",
          ],
          solutions: [
            { label: "Shape of a cubic", steps: ["A positive x³ cubic goes up, down, up: maximum first, then minimum.", "So the minimum is at the larger x, x = 2, with y = −16."] },
          ],
          traps: [{ spec: { type: "list", values: [-1, 11], ordered: true }, feedback: "(−1, 11) is the other turning point — the **maximum**. Test each with {{(d^2y)/(dx^2)}}: positive means minimum." }],
          commonError: "Choosing the point with the smaller x-value as the minimum.",
          difficulty: "core",
          guideRef: "turning-points",
          hints: ["Solve {{dy/dx = 0}}. Take out the common factor 6 first.", "Which of the two x-values gives a minimum? Use {{(d^2y)/(dx^2)}} or the shape of the cubic.", "Substitute that x into the curve's equation."],
          strategy: "Split into cases",
        },
        {
          kind: "written",
          id: "calculus-p1-q10",
          question: "Show that the curve y = x³ + 3x − 7 has no turning points.",
          marks: 3,
          modelAnswer:
            "{{dy/dx = 3x^2 + 3}}. At a turning point {{dy/dx = 0}}, so 3x² + 3 = 0, giving x² = −1. But x² ≥ 0 for every real x, so this has no real solutions. In fact {{dy/dx = 3x^2 + 3 >= 3}} for all x, so the gradient is always positive and the curve never turns.",
          markScheme: [
            { point: "Differentiates correctly: dy/dx = 3x² + 3", keywords: ["3x^2 + 3", "3x² + 3", "3x^2+3", "dy/dx"] },
            { point: "Sets dy/dx = 0 (or considers its sign), reaching x² = −1", keywords: ["= 0", "x^2 = -1", "x² = −1", "-1"] },
            { point: "Concludes: x² cannot be negative, so no real solutions / gradient always positive, so no turning points", keywords: ["no real", "cannot", "never", "always positive", "x² ≥ 0", "no solutions", "no turning points"] },
          ],
          commonError: "Stopping at dy/dx = 3x² + 3 without explaining why it can never equal 0.",
          difficulty: "core",
          guideRef: "turning-points",
          hints: ["What is true about {{dy/dx}} at a turning point?", "Can 3x² + 3 ever equal 0? What is the smallest value x² can take?"],
          strategy: "Consider extremes",
        },
        {
          kind: "short",
          id: "calculus-p1-q11",
          question: "A particle moves in a straight line so that its displacement from O after t seconds is s = 2t³ − 15t² + 36t metres. Work out its acceleration when t = 3. Give your answer in m/s².",
          answer: { type: "number", value: 6 },
          solution: [
            "{{v = (ds)/(dt) = 6t^2 - 30t + 36}}.",
            "{{a = (dv)/(dt) = 12t - 30}}.",
            "At t = 3: a = 36 − 30 = 6 m/s².",
          ],
          traps: [
            { spec: { type: "number", value: 0 }, feedback: "That's the **velocity** at t = 3 (54 − 90 + 36 = 0). Acceleration needs a second differentiation." },
            { spec: { type: "number", value: 27 }, feedback: "That's the displacement at t = 3. Differentiate twice for acceleration." },
          ],
          commonError: "Stopping at velocity — differentiating only once.",
          difficulty: "core",
          guideRef: "kinematics",
          hints: ["Acceleration is the rate of change of velocity.", "Differentiate s to get v, then differentiate v to get a.", "Substitute t = 3 into a."],
        },
        {
          kind: "written",
          id: "calculus-p1-q12",
          question:
            "A particle moves along a straight line. Its displacement from O after t seconds is s = t³ − 9t² + 24t metres.\n\n(a) Show that the particle is instantaneously at rest when t = 2 and when t = 4.\n\n(b) Explain whether the particle is moving towards O or away from O between t = 2 and t = 4.",
          marks: 4,
          modelAnswer:
            "(a) {{v = (ds)/(dt) = 3t^2 - 18t + 24 = 3(t^2 - 6t + 8) = 3(t - 2)(t - 4)}}. So v = 0 when t = 2 and when t = 4: the particle is at rest at both times.\n\n(b) For 2 < t < 4, (t − 2) > 0 and (t − 4) < 0, so v < 0: the particle moves in the negative direction. Its displacement is positive throughout (s = 20 at t = 2 and s = 16 at t = 4), so moving in the negative direction means it is moving **towards** O.",
          markScheme: [
            { point: "Differentiates: v = 3t² − 18t + 24", keywords: ["3t^2 - 18t + 24", "3t² − 18t + 24", "ds/dt", "v ="] },
            { point: "Shows v = 0 at t = 2 and t = 4 (factorising or substituting)", keywords: ["(t - 2)(t - 4)", "(t−2)(t−4)", "= 0", "12 - 36 + 24", "48 - 72 + 24"] },
            { point: "v < 0 between t = 2 and t = 4 (e.g. v(3) = −3)", keywords: ["v < 0", "negative", "-3", "−3", "v(3)"] },
            { point: "s positive in this interval (s(2) = 20, s(4) = 16), so the particle moves towards O", keywords: ["towards o", "towards", "s = 20", "16", "positive", "decreasing"] },
          ],
          commonError: "Saying 'negative velocity means moving towards O' without checking which side of O the particle is on.",
          difficulty: "core",
          guideRef: "kinematics",
          hints: ["'At rest' means v = 0. Differentiate s.", "For (b), test a value such as t = 3 in v. What does the sign tell you?", "Is the particle on the positive or negative side of O? Find s at t = 2 and t = 4."],
          strategy: "Split into cases",
        },
        {
          kind: "short",
          id: "calculus-p1-q13",
          question:
            "For a CCA craft project, Wei Ling cuts a square of side x cm from each corner of a square sheet of card 24 cm by 24 cm, then folds up the sides to make an open box. The volume of the box is V = x(24 − 2x)² cm³. Find the maximum possible volume of the box. Give your answer in cm³.",
          answer: { type: "number", value: 1024 },
          solution: [
            "Expand: V = x(576 − 96x + 4x²) = 4x³ − 96x² + 576x.",
            "{{(dV)/(dx) = 12x^2 - 192x + 576 = 12(x^2 - 16x + 48) = 12(x - 4)(x - 12)}}.",
            "x = 12 makes the base 0 cm wide (V = 0), so x = 4.",
            "{{(d^2V)/(dx^2) = 24x - 192}} = −96 < 0 at x = 4: a maximum.",
            "V = 4 × 16² = 1024 cm³.",
          ],
          traps: [
            { spec: { type: "number", value: 4 }, feedback: "x = 4 cm is the size of the cut-out squares. The question asks for the maximum **volume**: substitute x = 4 into V." },
            { spec: { type: "number", value: 0 }, feedback: "x = 12 also gives {{(dV)/(dx) = 0}}, but there the box is flat (base 0 cm). It's the minimum — reject it." },
          ],
          commonError: "Keeping x = 12 without checking it is physically sensible.",
          difficulty: "challenge",
          guideRef: "turning-points",
          hints: ["Expand V into powers of x so you can differentiate.", "Solve {{(dV)/(dx) = 0}}: take out a factor of 12 first.", "One root makes the box impossible. Which one, and why?", "Check it is a maximum, then work out V."],
          strategy: "Consider extremes",
        },
        {
          kind: "short",
          id: "calculus-p1-q14",
          question:
            "The normal to the curve y = x² − 4x + 5 at the point P(3, 2) meets the curve again at the point Q. Find the coordinates of Q. Give your answer as (x, y), using decimals where needed.",
          answer: { type: "list", values: [0.5, 3.25], ordered: true, display: "(0.5, 3.25)" },
          solution: [
            "{{dy/dx = 2x - 4}} = 2 at x = 3, so the normal gradient is {{-1/2}}.",
            "Normal: {{y - 2 = -1/2 (x - 3)}}, i.e. {{y = (7 - x)/2}}.",
            "Meet the curve: {{x^2 - 4x + 5 = (7 - x)/2}} → 2x² − 8x + 10 = 7 − x → 2x² − 7x + 3 = 0.",
            "(2x − 1)(x − 3) = 0. x = 3 is P, so x = {{1/2}}.",
            "y = 0.25 − 2 + 5 = 3.25. Q = (0.5, 3.25).",
          ],
          traps: [
            { spec: { type: "list", values: [3, 2], ordered: true }, feedback: "That's P itself. The quadratic has two roots: one is x = 3 (P) — the other is Q." },
            { spec: { type: "list", values: [0.5, 2.75], ordered: true }, feedback: "Recheck the y-coordinate in the curve: 0.25 − 2 + 5 = 3.25. (It also lies on the normal: (7 − 0.5) ÷ 2 = 3.25.)" },
          ],
          commonError: "Using the tangent gradient 2 instead of the normal gradient −½.",
          difficulty: "challenge",
          guideRef: "normals",
          hints: ["Find the gradient of the tangent at P, then the normal.", "Write the equation of the normal.", "Set the normal equal to the curve. You already know one root — P — so factorising is easier."],
          strategy: "Use a known root",
        },
        {
          kind: "written",
          id: "calculus-p1-q15",
          question: "Prove that, for x > 0, the minimum value of {{x^2 + 16/x}} is 12.",
          marks: 4,
          modelAnswer:
            "Let {{y = x^2 + 16x^(-1)}}. Then {{dy/dx = 2x - 16x^(-2) = 2x - 16/(x^2)}}.\n\nAt a turning point {{2x = 16/(x^2)}}, so x³ = 8 and x = 2.\n\n{{(d^2y)/(dx^2) = 2 + 32/(x^3)}}, which is 2 + 4 = 6 > 0 at x = 2, so this is a minimum. (It is the only turning point for x > 0, so it is the least value.)\n\nAt x = 2, y = 4 + 8 = 12. So the minimum value is 12.",
          markScheme: [
            { point: "Writes 16/x as 16x⁻¹ and differentiates: 2x − 16x⁻²", keywords: ["16x^-1", "-16x^-2", "2x - 16/x^2", "−16/x²", "dy/dx"] },
            { point: "Sets dy/dx = 0 and solves x³ = 8, x = 2", keywords: ["x^3 = 8", "x³ = 8", "x = 2"] },
            { point: "Justifies minimum (second derivative 6 > 0, or sign change − to +)", keywords: ["second derivative", "d2y", "> 0", "positive", "6", "minimum"] },
            { point: "Substitutes x = 2: 4 + 8 = 12", keywords: ["4 + 8", "= 12", "12"] },
          ],
          commonError: "Differentiating 16/x as 16 or as 16/x² (wrong sign and power).",
          difficulty: "challenge",
          guideRef: "turning-points",
          hints: ["Rewrite {{16/x}} as a power of x.", "Set {{dy/dx = 0}} and solve for x (x > 0).", "Prove it's a minimum — then find the value of the expression there."],
          strategy: "Make it simpler",
        },
      ],
    },
    {
      id: "calculus-p2",
      title: "Practice Paper 2",
      questions: [
        {
          kind: "short",
          id: "calculus-p2-q01",
          question: "y = 7 − 2x³ + x. Find {{dy/dx}}.",
          answer: { type: "expression", expr: "1-6x^2", display: "{{dy/dx = 1 - 6x^2}}" },
          solution: ["7 → 0, −2x³ → −6x², x → 1.", "{{dy/dx = 1 - 6x^2}}."],
          traps: [{ spec: { type: "expression", expr: "7-6x^2+1" }, feedback: "The constant 7 differentiates to 0 — constants have no gradient." }],
          difficulty: "warmup",
          guideRef: "differentiating-powers",
          hints: ["The terms are in an unusual order. Differentiate each one separately — order doesn't matter."],
        },
        {
          kind: "short",
          id: "calculus-p2-q02",
          question:
            "The diagram shows a curve and the tangent to the curve at a point T. The tangent passes through the points (1, 2) and (4, 11). Write down the gradient of the curve at T.",
          diagram: tangentThroughPoints,
          answer: { type: "number", value: 3 },
          solution: [
            "The gradient of a curve at a point **is** the gradient of the tangent there.",
            "Tangent gradient = {{(11 - 2)/(4 - 1) = 9/3 = 3}}.",
          ],
          traps: [{ spec: { type: "number", value: 0.333333333, }, feedback: "That's run ÷ rise. Gradient = change in y ÷ change in x = 9 ÷ 3." }],
          difficulty: "warmup",
          guideRef: "gradient-of-a-curve",
          hints: ["The curve and its tangent share the same gradient at T.", "Use the two marked points: rise ÷ run."],
          strategy: "Draw a diagram",
        },
        {
          kind: "short",
          id: "calculus-p2-q03",
          question: "y = x²(x + 5). Find {{dy/dx}}.",
          answer: { type: "expression", expr: "3x^2+10x", display: "{{dy/dx = 3x^2 + 10x}}" },
          solution: ["Expand: y = x³ + 5x².", "{{dy/dx = 3x^2 + 10x}}."],
          traps: [{ spec: { type: "expression", expr: "2x" }, feedback: "You can't differentiate each factor and multiply (2x × 1). Expand first: x³ + 5x²." }],
          difficulty: "warmup",
          guideRef: "differentiating-powers",
          hints: ["Multiply out the bracket first so you have separate powers of x."],
          strategy: "Make it simpler",
        },
        {
          kind: "short",
          id: "calculus-p2-q04",
          question: "A lift moves upwards from the ground floor of an HDB block. Its height above the ground after t seconds is s = 0.5t² + 2t metres (for the first few seconds). Find an expression for its velocity v in terms of t.",
          answer: { type: "expression", expr: "t+2", display: "v = t + 2" },
          solution: ["{{v = (ds)/(dt)}}.", "0.5t² → t, 2t → 2. So v = t + 2 (m/s)."],
          traps: [{ spec: { type: "expression", expr: "0.5t+2" }, feedback: "0.5t² → 2 × 0.5t = t. Multiply the coefficient by the power." }],
          difficulty: "warmup",
          guideRef: "kinematics",
          hints: ["Velocity is the rate of change of displacement — differentiate s with respect to t."],
        },
        {
          kind: "short",
          id: "calculus-p2-q05",
          question: "{{y = 8/(x^2) - 3/x}}. Find {{dy/dx}}.",
          answer: { type: "expression", expr: "-16/x^3+3/x^2", display: "{{dy/dx = -16/(x^3) + 3/(x^2)}}" },
          solution: [
            "Rewrite with negative powers: {{y = 8x^(-2) - 3x^(-1)}}.",
            "Differentiate: {{-16x^(-3) + 3x^(-2)}}.",
            "{{dy/dx = -16/(x^3) + 3/(x^2)}}.",
          ],
          traps: [
            { spec: { type: "expression", expr: "-16/x^3-3/x^2" }, feedback: "Watch the double negative: −3 × (−1) = **+3**." },
            { spec: { type: "expression", expr: "-16/x-3" }, feedback: "Powers go **down** by one: −2 → −3 and −1 → −2." },
          ],
          commonError: "Sign errors with negative powers: −3x⁻¹ → +3x⁻².",
          difficulty: "core",
          guideRef: "differentiating-powers",
          hints: ["Write each fraction as a power of x with a negative index.", "Multiply by the power, then subtract 1 from it — the new power is *more* negative.", "Be careful: −3 × −1 = ?"],
        },
        {
          kind: "short",
          id: "calculus-p2-q06",
          question: "The curve y = ax² + 3x has gradient 15 at the point where x = 2. Find the value of the constant a.",
          answer: { type: "number", value: 3 },
          solution: ["{{dy/dx = 2ax + 3}}.", "At x = 2: 4a + 3 = 15, so 4a = 12 and a = 3."],
          traps: [{ spec: { type: "number", value: 2.25 }, feedback: "You set the **y-value** equal to 15 (4a + 6 = 15). The gradient comes from {{dy/dx}}." }],
          commonError: "Setting y = 15 instead of dy/dx = 15.",
          difficulty: "core",
          guideRef: "tangents",
          hints: ["Treat a like a number when you differentiate.", "Substitute x = 2 into {{dy/dx}} and set it equal to 15."],
          strategy: "Work backwards",
        },
        {
          kind: "short",
          id: "calculus-p2-q07",
          question: "Find the coordinates of the point on the curve y = x² − 5x + 2 where the gradient is 3. Give your answer as (x, y).",
          answer: { type: "list", values: [4, -2], ordered: true, display: "(4, −2)" },
          solution: ["{{dy/dx = 2x - 5}} = 3 → x = 4.", "y = 16 − 20 + 2 = −2. Point (4, −2)."],
          traps: [{ spec: { type: "list", values: [4, 3], ordered: true }, feedback: "3 is the gradient there, not the y-coordinate. Substitute x = 4 into the curve." }],
          difficulty: "core",
          guideRef: "tangents",
          hints: ["Set {{dy/dx = 3}} to find x.", "Then substitute into the equation of the curve for y."],
        },
        {
          kind: "short",
          id: "calculus-p2-q08",
          question: "Find the equation of the tangent to the curve {{y = 2/x}} at the point where x = 2. Give your answer in the form ax + by + c = 0, where a, b and c are integers.",
          answer: { type: "equation", eq: "x+2y-4=0", form: "general", display: "x + 2y − 4 = 0" },
          solution: [
            "Point: y = {{2/2}} = 1, so (2, 1).",
            "{{y = 2x^(-1)}}, so {{dy/dx = -2x^(-2) = -2/(x^2)}} = {{-2/4 = -1/2}} at x = 2.",
            "{{y - 1 = -1/2 (x - 2)}} → 2y − 2 = −x + 2 → x + 2y − 4 = 0.",
          ],
          traps: [{ spec: { type: "equation", eq: "x-2y=0" }, feedback: "The gradient of {{2/x}} is **negative** ({{-2/(x^2)}}): the curve slopes down. Recheck the sign." }],
          commonError: "Differentiating 2/x as 2 or as −2/x.",
          difficulty: "core",
          guideRef: "tangents",
          hints: ["Write {{2/x}} as a power of x before differentiating.", "Find the point and the gradient at x = 2.", "Use y − y₁ = m(x − x₁), then clear the fraction."],
          strategy: "Break it into steps",
        },
        {
          kind: "short",
          id: "calculus-p2-q09",
          question: "Find the coordinates of the maximum point on the curve y = 12x − x³. Give your answer as (x, y).",
          answer: { type: "list", values: [2, 16], ordered: true, display: "(2, 16)" },
          solution: [
            "{{dy/dx = 12 - 3x^2 = 0}} → x² = 4 → x = ±2.",
            "{{(d^2y)/(dx^2) = -6x}}: at x = 2 it is −12 < 0 → maximum.",
            "y = 24 − 8 = 16. Maximum (2, 16).",
          ],
          traps: [{ spec: { type: "list", values: [-2, -16], ordered: true }, feedback: "(−2, −16) is the **minimum**: there {{(d^2y)/(dx^2) = +12}}." }],
          commonError: "Forgetting x² = 4 has two solutions, or picking the wrong one.",
          difficulty: "core",
          guideRef: "turning-points",
          hints: ["Solve {{dy/dx = 0}} — remember a square root gives ±.", "Use the second derivative to decide which is the maximum."],
          strategy: "Split into cases",
        },
        {
          kind: "written",
          id: "calculus-p2-q10",
          question: "The curve C has equation y = x³ − 6x² + 9x + 1. Show that C has a turning point at (1, 5) and determine whether it is a maximum or a minimum.",
          marks: 3,
          modelAnswer:
            "{{dy/dx = 3x^2 - 12x + 9}}. At x = 1: 3 − 12 + 9 = 0, so there is a turning point at x = 1. y = 1 − 6 + 9 + 1 = 5, so the point is (1, 5).\n\n{{(d^2y)/(dx^2) = 6x - 12}} = −6 at x = 1. This is negative, so (1, 5) is a **maximum**.",
          markScheme: [
            { point: "Differentiates: dy/dx = 3x² − 12x + 9", keywords: ["3x^2 - 12x + 9", "3x² − 12x + 9", "dy/dx"] },
            { point: "Shows dy/dx = 0 at x = 1 and y = 5", keywords: ["3 - 12 + 9", "= 0", "1 - 6 + 9 + 1", "= 5"] },
            { point: "Second derivative 6x − 12 = −6 < 0 (or sign change + to −), so maximum", keywords: ["6x - 12", "-6", "−6", "negative", "< 0", "maximum"] },
          ],
          commonError: "Checking only that y = 5 at x = 1 — that shows the point is on the curve, not that it is a turning point.",
          difficulty: "core",
          guideRef: "turning-points",
          hints: ["Two things to show: the point is on the curve, and the gradient there is 0.", "Then use {{(d^2y)/(dx^2)}} at x = 1."],
        },
        {
          kind: "short",
          id: "calculus-p2-q11",
          question: "A particle moves along a straight line with velocity v = t² − 8t + 15 m/s at time t seconds. Find its acceleration at the **first** moment it is at rest. Give your answer in m/s².",
          answer: { type: "number", value: -2 },
          solution: [
            "At rest: t² − 8t + 15 = 0 → (t − 3)(t − 5) = 0 → t = 3 (first).",
            "{{a = (dv)/(dt) = 2t - 8}}.",
            "At t = 3: a = 6 − 8 = −2 m/s².",
          ],
          traps: [{ spec: { type: "number", value: 2 }, feedback: "That's the acceleration at t = 5, the **second** time it is at rest. The first time is t = 3." }],
          commonError: "Using t = 5 instead of the first time, t = 3.",
          difficulty: "core",
          guideRef: "kinematics",
          hints: ["When is v = 0? Which of the two times is first?", "Acceleration is {{(dv)/(dt)}}.", "Substitute the first time into a."],
        },
        {
          kind: "written",
          id: "calculus-p2-q12",
          question: "Zara throws a ball vertically upwards on Sentosa beach. Its height above her hand after t seconds is h = 20t − 5t² metres. Show that the greatest height the ball reaches above her hand is 20 m.",
          marks: 3,
          modelAnswer:
            "{{(dh)/(dt) = 20 - 10t}}. At the greatest height the ball stops rising, so {{(dh)/(dt) = 0}}: 20 − 10t = 0, t = 2.\n\n{{(d^2h)/(dt^2) = -10 < 0}}, so this is a maximum.\n\nh = 20 × 2 − 5 × 4 = 40 − 20 = 20 m.",
          markScheme: [
            { point: "Differentiates: dh/dt = 20 − 10t", keywords: ["20 - 10t", "20 − 10t", "dh/dt"] },
            { point: "Sets dh/dt = 0 to get t = 2", keywords: ["= 0", "t = 2"] },
            { point: "Substitutes t = 2: h = 40 − 20 = 20", keywords: ["40 - 20", "40 − 20", "= 20", "20 m"] },
          ],
          commonError: "Substituting the given 20 m into h and solving, which assumes the answer.",
          difficulty: "core",
          guideRef: "kinematics",
          hints: ["At the top, what is the ball's vertical velocity?", "Solve {{(dh)/(dt) = 0}}, then find h at that time."],
          strategy: "Consider extremes",
        },
        {
          kind: "short",
          id: "calculus-p2-q13",
          question:
            "A company designs a closed cylindrical tin with volume 128π cm³. With radius r cm, its surface area is {{A = 2pi r^2 + (256pi)/r}} cm². Find the minimum surface area. Give your answer in terms of π.",
          answer: { type: "expression", expr: "96pi", display: "96π cm²" },
          solution: [
            "{{A = 2pi r^2 + 256pi r^(-1)}}.",
            "{{(dA)/(dr) = 4pi r - 256pi r^(-2) = 0}} → 4r³ = 256 → r³ = 64 → r = 4.",
            "{{(d^2A)/(dr^2) = 4pi + (512pi)/(r^3) > 0}}, so it is a minimum.",
            "A = 2π(16) + {{(256pi)/4}} = 32π + 64π = 96π cm².",
          ],
          solutions: [
            {
              label: "Where the formula comes from",
              steps: [
                "Volume: πr²h = 128π, so {{h = 128/(r^2)}}.",
                "A = 2πr² + 2πrh = 2πr² + {{2pi r * 128/(r^2) = 2pi r^2 + (256pi)/r}}.",
                "At r = 4, h = 8 = 2r: the cheapest closed can is exactly as tall as it is wide.",
              ],
            },
          ],
          traps: [
            { spec: { type: "number", value: 4 }, feedback: "r = 4 cm gives the minimum — but the question asks for the minimum **area**. Substitute r = 4 into A." },
            { spec: { type: "expression", expr: "32pi" }, feedback: "That's only the 2πr² part. Add {{(256pi)/4 = 64pi}}." },
          ],
          commonError: "Differentiating 256π/r as 256π instead of −256π/r².",
          difficulty: "challenge",
          guideRef: "turning-points",
          hints: ["Write {{(256pi)/r}} as {{256pi r^(-1)}} — π is just a constant.", "Set {{(dA)/(dr) = 0}}. You can divide through by 4π.", "Solve r³ = 64, check it's a minimum, then substitute into A."],
          strategy: "Make it simpler",
        },
        {
          kind: "written",
          id: "calculus-p2-q14",
          question:
            "P is the point (2, 4) on the curve y = x². The tangent at P meets the y-axis at A. The normal at P meets the y-axis at B. Show that the area of triangle PAB is 8.5 square units.",
          marks: 4,
          modelAnswer:
            "{{dy/dx = 2x = 4}} at P.\n\nTangent: y − 4 = 4(x − 2), so y = 4x − 4. At x = 0, y = −4: A = (0, −4).\n\nNormal gradient {{-1/4}}: {{y - 4 = -1/4 (x - 2)}}. At x = 0, {{y = 4 + 1/2 = 4.5}}: B = (0, 4.5).\n\nAB lies on the y-axis with length 4.5 − (−4) = 8.5. The perpendicular height from P to the y-axis is the x-coordinate of P, 2.\n\nArea = {{1/2 * 8.5 * 2 = 8.5}} square units.",
          markScheme: [
            { point: "Tangent y = 4x − 4, giving A(0, −4)", keywords: ["4x - 4", "4x − 4", "(0, -4)", "-4", "−4"] },
            { point: "Normal gradient −1/4", keywords: ["-1/4", "−1/4", "-0.25", "negative reciprocal"] },
            { point: "Normal meets y-axis at B(0, 4.5)", keywords: ["4.5", "(0, 4.5)", "9/2"] },
            { point: "Area = ½ × 8.5 × 2 = 8.5", keywords: ["8.5", "1/2 × 8.5 × 2", "base", "height 2"] },
          ],
          commonError: "Using 4 (the y-coordinate of P) as the height instead of the horizontal distance 2.",
          difficulty: "challenge",
          guideRef: "normals",
          hints: ["Find the gradient at P, then the tangent and normal equations.", "Put x = 0 into each equation to find A and B.", "Take AB as the base (it's on the y-axis). What is the perpendicular height from P to that base?"],
          strategy: "Draw a diagram",
        },
        {
          kind: "short",
          id: "calculus-p2-q15",
          question: "The curve y = x³ + ax² + bx has a turning point at (1, −4). Find the values of the constants a and b. Give your answer as a, b in that order.",
          answer: { type: "list", values: [2, -7], ordered: true, display: "a = 2, b = −7" },
          solution: [
            "The point is on the curve: 1 + a + b = −4, so a + b = −5.",
            "Turning point: {{dy/dx = 3x^2 + 2ax + b}} = 0 at x = 1, so 3 + 2a + b = 0, i.e. 2a + b = −3.",
            "Subtract: a = 2. Then b = −7.",
            "Check: y = x³ + 2x² − 7x: y(1) = −4 ✓, {{dy/dx}} = 3 + 4 − 7 = 0 ✓.",
          ],
          traps: [{ spec: { type: "list", values: [-7, 2], ordered: true }, feedback: "Right values, wrong order: give a first, then b." }],
          commonError: "Using only one of the two conditions (on the curve AND gradient 0).",
          difficulty: "challenge",
          guideRef: "turning-points",
          hints: ["You have two unknowns, so you need two equations. What two facts do you know about the point (1, −4)?", "It lies on the curve — substitute it in.", "The gradient there is 0 — substitute x = 1 into {{dy/dx}}.", "Solve the simultaneous equations."],
          strategy: "Introduce a variable",
        },
      ],
    },
  ],

  // =========================================================================
  // Challenge — AoPS-hard, grade 9 / H+ flavour
  // =========================================================================
  challenge: [
    {
      kind: "short",
      id: "calculus-ch-q01",
      question:
        "The chord of y = x² joining the points with x-coordinates 1 and k (k > 1) is parallel to the tangent to y = x² at x = 4. Find k.",
      answer: { type: "number", value: 7 },
      solution: [
        "Chord gradient = {{(k^2 - 1)/(k - 1) = ((k - 1)(k + 1))/(k - 1) = k + 1}}.",
        "Tangent gradient at x = 4: 2 × 4 = 8.",
        "Parallel: k + 1 = 8, so k = 7.",
      ],
      solutions: [
        {
          label: "Midpoint property of a parabola",
          steps: [
            "For y = x², the chord from x = a to x = b has gradient a + b = 2 × {{(a + b)/2}}: the tangent gradient at the **midpoint** x-value.",
            "So the tangent at x = 4 is parallel to any chord whose x-values average 4.",
            "{{(1 + k)/2 = 4}} → k = 7. Quicker once you've spotted it — and it explains why the answer is so neat.",
          ],
        },
      ],
      traps: [{ spec: { type: "number", value: 4 }, feedback: "That chord would run from x = 1 to x = 4, gradient 5 — not 8. Find the chord gradient in terms of k." }],
      difficulty: "challenge",
      guideRef: "gradient-of-a-curve",
      hints: [
        "Write the chord gradient in terms of k: {{(k^2 - 1)/(k - 1)}}.",
        "Factorise the top — difference of two squares.",
        "Parallel lines have equal gradients. What is the tangent gradient at x = 4?",
        "Can you see a pattern: chord from a to b has gradient a + b?",
      ],
      strategy: "Find a pattern",
    },
    {
      kind: "short",
      id: "calculus-ch-q02",
      question: "{{y = (x + 1/x)^2}}, x ≠ 0. Find all the values of x for which {{dy/dx = 0}}.",
      answer: { type: "list", values: [1, -1], display: "x = 1 or x = −1" },
      solution: [
        "Expand: {{y = x^2 + 2 + 1/(x^2) = x^2 + 2 + x^(-2)}}.",
        "{{dy/dx = 2x - 2x^(-3) = 2x - 2/(x^3)}}.",
        "{{2x = 2/(x^3)}} → x⁴ = 1 → x = 1 or x = −1 (x² = −1 has no real solutions).",
      ],
      solutions: [
        {
          label: "Think, don't differentiate",
          steps: [
            "y is a square, so y ≥ 0 — but more usefully {{x + 1/x}} has magnitude at least 2 (AM–GM, or {{(x - 1)^2 >= 0}}).",
            "So y ≥ 4, with equality exactly when {{x + 1/x = +- 2}}, i.e. x = ±1.",
            "Those minimum points are where the gradient is 0 — and the derivative shows there are no others.",
          ],
        },
      ],
      traps: [{ spec: { type: "list", values: [1] }, feedback: "x⁴ = 1 has **two** real solutions. Try x = −1 too: the curve is symmetric about the y-axis." }],
      commonError: "Writing the square as x² + 1/x² (forgetting the middle term 2·x·(1/x) = 2), or missing x = −1.",
      difficulty: "challenge",
      guideRef: "differentiating-powers",
      hints: [
        "Expand the square. What is the middle term {{2 * x * 1/x}}?",
        "Write every term as a power of x, then differentiate.",
        "Multiply the equation {{dy/dx = 0}} by x³.",
        "How many real solutions does x⁴ = 1 have?",
      ],
      strategy: "Make it simpler",
    },
    {
      kind: "short",
      id: "calculus-ch-q03",
      question:
        "Two different tangents to the curve y = x² pass through the point (1, −3), which is below the curve. Find the gradients of the two tangents.",
      answer: { type: "list", values: [6, -2], display: "6 and −2" },
      solution: [
        "Let a tangent touch at (a, a²). Its gradient is 2a, so its equation is y − a² = 2a(x − a), i.e. y = 2ax − a².",
        "It passes through (1, −3): −3 = 2a − a² → a² − 2a − 3 = 0 → (a − 3)(a + 1) = 0.",
        "a = 3 or a = −1, giving gradients 2a = 6 and −2.",
        "Check: y = 6x − 9 and y = −2x − 1 both pass through (1, −3) ✓.",
      ],
      traps: [
        { spec: { type: "list", values: [2] }, feedback: "2 is the gradient of the curve at x = 1, but (1, −3) is **not on the curve**. Let the tangent touch at an unknown point (a, a²)." },
        { spec: { type: "list", values: [3, -1] }, feedback: "Those are the x-coordinates of the points of contact. The gradients are 2a." },
      ],
      commonError: "Differentiating and substituting x = 1, as if the point were on the curve.",
      difficulty: "challenge",
      guideRef: "tangents",
      hints: [
        "Is (1, −3) on the curve? If not, you don't know where the tangents touch.",
        "Introduce a variable: let the tangent touch at (a, a²).",
        "Write the tangent's equation in terms of a, then make it pass through (1, −3).",
        "Solve the quadratic in a. The gradients are 2a.",
      ],
      strategy: "Introduce a variable",
    },
    {
      kind: "written",
      id: "calculus-ch-q04",
      question: "P is the point (p, p³) on the curve y = x³, where p ≠ 0. Prove that the tangent at P meets the curve again at the point (−2p, −8p³).",
      marks: 4,
      modelAnswer:
        "{{dy/dx = 3x^2}}, so the gradient at P is 3p².\n\nTangent: y − p³ = 3p²(x − p), so y = 3p²x − 2p³.\n\nWhere it meets the curve: x³ = 3p²x − 2p³, i.e. x³ − 3p²x + 2p³ = 0.\n\nThe tangent touches at x = p, so (x − p)² is a factor: x³ − 3p²x + 2p³ = (x − p)²(x + 2p). [Check: (x² − 2px + p²)(x + 2p) = x³ − 3p²x + 2p³ ✓]\n\nSo the other intersection is at x = −2p, where y = (−2p)³ = −8p³. Since p ≠ 0, −2p ≠ p, so this is a different point: (−2p, −8p³).",
      markScheme: [
        { point: "Tangent at P: y = 3p²x − 2p³", keywords: ["3p^2", "3p²", "3p^2x - 2p^3", "2p³", "2p^3"] },
        { point: "Forms the cubic x³ − 3p²x + 2p³ = 0", keywords: ["x^3 - 3p^2x + 2p^3", "x³ − 3p²x + 2p³", "= 0"] },
        { point: "Uses the repeated root x = p: factor (x − p)²", keywords: ["(x - p)^2", "(x − p)²", "repeated", "double root", "factor"] },
        { point: "Other root x = −2p, y = −8p³", keywords: ["x + 2p", "-2p", "−2p", "-8p^3", "−8p³"] },
      ],
      solutions: [
        {
          label: "Sum of the roots",
          steps: [
            "x³ + 0x² − 3p²x + 2p³ = 0 has roots p, p (tangent: a double root) and r.",
            "The sum of the roots of x³ + bx² + … = 0 is −b = 0, so p + p + r = 0 and r = −2p.",
            "Faster — no factorising needed, once you know that fact.",
          ],
        },
      ],
      commonError: "Forgetting that a tangent gives a repeated root, and trying to solve the cubic from scratch.",
      difficulty: "challenge",
      guideRef: "tangents",
      hints: [
        "Find the tangent's equation in terms of p.",
        "Set it equal to x³ and rearrange to a cubic equal to 0.",
        "A tangent touches the curve at P — so x = p is a repeated root. What factor does that give?",
        "Divide out (x − p)² to find the third root.",
      ],
      strategy: "Use a known root",
    },
    {
      kind: "short",
      id: "calculus-ch-q05",
      question:
        "Priya is designing an open-topped box with a square base for a hawker-centre takeaway. It must hold 32 cm³. Find the smallest possible total surface area of card she can use. Give your answer in cm².",
      answer: { type: "number", value: 48 },
      solution: [
        "Base x by x, height h: x²h = 32, so {{h = 32/(x^2)}}.",
        "Area (no lid): S = x² + 4xh = {{x^2 + 4x * 32/(x^2) = x^2 + 128/x}}.",
        "{{(dS)/(dx) = 2x - 128/(x^2) = 0}} → x³ = 64 → x = 4.",
        "{{(d^2S)/(dx^2) = 2 + 256/(x^3) > 0}}: a minimum.",
        "S = 16 + 32 = 48 cm² (the box is 4 × 4 × 2).",
      ],
      traps: [
        { spec: { type: "number", value: 64 }, feedback: "That includes a lid (2x² + 4xh). The box is open-topped: only one square face." },
        { spec: { type: "number", value: 4 }, feedback: "x = 4 cm is the base edge. Substitute into S for the area." },
      ],
      commonError: "Including a lid, or leaving S in terms of two variables.",
      difficulty: "challenge",
      guideRef: "turning-points",
      hints: [
        "Introduce two variables: base x, height h. Write the volume condition.",
        "Write the surface area — remember there's no lid.",
        "Use the volume equation to eliminate h, so S depends on x only.",
        "Differentiate, set to 0, solve, and check it's a minimum.",
      ],
      strategy: "Introduce a variable",
    },
    {
      kind: "short",
      id: "calculus-ch-q06",
      question:
        "The curve y = x³ − 3x² + kx has no **stationary points** (points where {{dy/dx = 0}}). Find the smallest integer value k can take.",
      answer: { type: "number", value: 4 },
      solution: [
        "{{dy/dx = 3x^2 - 6x + k}}. No stationary points means 3x² − 6x + k = 0 has no real roots.",
        "Discriminant < 0: 36 − 12k < 0 → k > 3.",
        "The smallest integer is k = 4.",
        "At k = 3, {{dy/dx = 3(x - 1)^2}} = 0 at x = 1: a stationary point (a point of inflection — not a turning point, but still stationary). So 3 is excluded.",
      ],
      solutions: [
        {
          label: "Complete the square",
          steps: [
            "{{dy/dx = 3(x - 1)^2 + (k - 3)}}.",
            "The smallest value of dy/dx is k − 3 (at x = 1). For it never to be zero we need k − 3 > 0.",
            "So k > 3, smallest integer 4. This view also shows the gradient is then always positive.",
          ],
        },
      ],
      traps: [{ spec: { type: "number", value: 3 }, feedback: "At k = 3, {{dy/dx = 3(x - 1)^2}}, which equals 0 at x = 1 — a stationary point. The inequality is strict: k > 3." }],
      commonError: "Using ≤ 0 or ≥ in the discriminant condition, so k = 3 is wrongly included.",
      difficulty: "challenge",
      guideRef: "turning-points",
      hints: [
        "Write down {{dy/dx}}. It's a quadratic in x.",
        "'No stationary points' means this quadratic is never 0. What does that say about its discriminant?",
        "Solve 36 − 12k < 0.",
        "Test the boundary value: what happens when k = 3?",
      ],
      strategy: "Consider extremes",
    },
    {
      kind: "short",
      id: "calculus-ch-q07",
      question:
        "A particle starts at O and moves along a straight line. Its displacement from O after t seconds is s = t³ − 6t² + 9t metres. Find the **total distance** it travels in the first 4 seconds. Give your answer in metres.",
      answer: { type: "number", value: 12 },
      solution: [
        "{{v = 3t^2 - 12t + 9 = 3(t - 1)(t - 3)}}: the particle changes direction at t = 1 and t = 3.",
        "s(0) = 0, s(1) = 1 − 6 + 9 = 4, s(3) = 27 − 54 + 27 = 0, s(4) = 64 − 96 + 36 = 4.",
        "Distances: 0 → 4 (4 m out), 4 → 0 (4 m back), 0 → 4 (4 m out).",
        "Total distance = 4 + 4 + 4 = 12 m.",
      ],
      traps: [
        { spec: { type: "number", value: 4 }, feedback: "4 m is the final **displacement** s(4). The particle turned round twice — add up each leg separately." },
        { spec: { type: "number", value: 8 }, feedback: "You've found two of the legs. Did you check both turning times, t = 1 and t = 3?" },
      ],
      commonError: "Giving the displacement s(4) instead of the total distance.",
      difficulty: "challenge",
      guideRef: "kinematics",
      hints: [
        "Distance and displacement differ when the particle turns round. When does that happen?",
        "Find when v = 0.",
        "Work out s at t = 0, each turning time, and t = 4.",
        "Add the sizes of the changes in s between consecutive times.",
      ],
      strategy: "Split into cases",
    },
    {
      kind: "short",
      id: "calculus-ch-q08",
      question:
        "A particle moves along a straight line with displacement s = t³ − 9t² + 24t metres at time t seconds (t ≥ 0). Find the **least** value of its velocity. Give your answer in m/s.",
      answer: { type: "number", value: -3 },
      solution: [
        "{{v = 3t^2 - 18t + 24}}.",
        "v is least when {{(dv)/(dt) = 0}}: a = 6t − 18 = 0 → t = 3.",
        "{{(d^2v)/(dt^2) = 6 > 0}}, so a minimum. v(3) = 27 − 54 + 24 = −3 m/s.",
        "Meaning: at t = 3 the particle is moving in the negative direction at its fastest, 3 m/s.",
      ],
      solutions: [
        {
          label: "Complete the square",
          steps: ["v = 3(t² − 6t) + 24 = 3(t − 3)² − 27 + 24 = 3(t − 3)² − 3.", "Least value −3 when t = 3 — no second derivative needed."],
        },
      ],
      traps: [
        { spec: { type: "number", value: 0 }, feedback: "v = 0 when the particle is at rest (t = 2 and t = 4). Between those times v is negative, so its least value is below 0." },
        { spec: { type: "number", value: 18 }, feedback: "That's the displacement at t = 3. Substitute t = 3 into v, not s." },
      ],
      commonError: "Setting v = 0 instead of dv/dt = 0 to find the extreme value of v.",
      difficulty: "challenge",
      guideRef: "kinematics",
      hints: [
        "You want the minimum of v — the same method as the minimum of y.",
        "So differentiate v and set the result to 0. What quantity is {{(dv)/(dt)}}?",
        "Acceleration is zero at t = 3. Find v there.",
      ],
      strategy: "Consider extremes",
    },
    {
      kind: "short",
      id: "calculus-ch-q09",
      question:
        "P is the point (p, p²) on the curve y = x², where p > 0. The normal to the curve at P passes through the point (0, 5). Find the exact value of p. Give your answer in the form {{(a sqrt(b))/c}}.",
      answer: { type: "expression", expr: "3sqrt(2)/2", form: "surd", display: "{{(3sqrt(2))/2}}" },
      solution: [
        "Tangent gradient at P is 2p, so the normal gradient is {{-1/(2p)}}.",
        "Normal: {{y - p^2 = -1/(2p) (x - p)}}.",
        "At x = 0: {{y = p^2 + p/(2p) = p^2 + 1/2}}.",
        "{{p^2 + 1/2 = 5}} → {{p^2 = 9/2}} → {{p = 3/sqrt(2) = (3sqrt(2))/2}}.",
      ],
      solutions: [
        {
          label: "Perpendicular vectors",
          steps: [
            "The line from (0, 5) to P must be perpendicular to the tangent direction (1, 2p).",
            "Vector (p, p² − 5) · (1, 2p) = 0 → p + 2p(p² − 5) = 0 → 1 + 2p² − 10 = 0 (p ≠ 0).",
            "{{p^2 = 9/2}}, same answer.",
          ],
        },
      ],
      traps: [{ spec: { type: "expression", expr: "sqrt(5)" }, feedback: "{{p = sqrt(5)}} makes P level with (0, 5) — but the normal isn't horizontal. Write the normal's equation and put x = 0." }],
      commonError: "Using the tangent gradient 2p instead of the normal gradient −1/(2p).",
      difficulty: "challenge",
      guideRef: "normals",
      hints: [
        "What is the gradient of the tangent at P? And of the normal?",
        "Write the equation of the normal in terms of p.",
        "Put x = 0 and y = 5. Notice how neatly the p's cancel.",
        "Rationalise the denominator at the end.",
      ],
      strategy: "Introduce a variable",
    },
    {
      kind: "short",
      id: "calculus-ch-q10",
      question:
        "Find the shortest distance from the point (0, 3) to the curve y = x². Give your answer in the form {{sqrt(a)/b}}.",
      answer: { type: "expression", expr: "sqrt(11)/2", form: "surd", display: "{{sqrt(11)/2}}" },
      solution: [
        "A point on the curve is (x, x²). Its distance squared from (0, 3) is D = x² + (x² − 3)² = x⁴ − 5x² + 9.",
        "Minimise D (the distance is smallest when its square is): {{(dD)/(dx) = 4x^3 - 10x = 2x(2x^2 - 5) = 0}}.",
        "x = 0 gives D = 9 (distance 3, a local maximum of D). {{x^2 = 5/2}} gives {{D = 25/4 - 25/2 + 9 = 11/4}}.",
        "Shortest distance = {{sqrt(11/4) = sqrt(11)/2}} ≈ 1.66.",
      ],
      solutions: [
        {
          label: "The shortest line is a normal",
          steps: [
            "At the closest point, the line to (0, 3) must be perpendicular to the curve — it lies along the **normal**.",
            "Normal at (p, p²) meets the y-axis at {{y = p^2 + 1/2}} (as in the previous challenge). Set {{p^2 + 1/2 = 3}}: {{p^2 = 5/2}}.",
            "Distance² = {{p^2 + (p^2 - 3)^2 = 5/2 + 1/4 = 11/4}}. Same answer, and it explains *why* the calculus works.",
          ],
        },
      ],
      traps: [{ spec: { type: "number", value: 3 }, feedback: "3 is the distance to the vertex (0, 0) — but x = 0 is a local **maximum** of the distance. Points either side are closer." }],
      commonError: "Assuming the nearest point is the vertex (0, 0).",
      difficulty: "challenge",
      guideRef: "normals",
      hints: [
        "Is the closest point necessarily the bottom of the curve? Try x = 1: how far is (1, 1) from (0, 3)?",
        "Write the squared distance from (0, 3) to a general point (x, x²) — avoiding the square root makes the algebra easier.",
        "Differentiate D and set it to 0. Which root gives the minimum?",
        "Square-root at the end.",
      ],
      strategy: "Consider extremes",
    },
  ],
};
