// Fractions, decimals & percentages — MCQ papers (3 × 15). Options are shuffled at display time.
import type { Paper } from "../../types.ts";

export const mcqPapers: Paper[] = [
  // ===========================================================================
  // MCQ Paper 1
  // ===========================================================================
  {
    id: "fractions-percentages-m1",
    title: "MCQ Paper 1",
    questions: [
      {
        kind: "mcq",
        id: "fractions-percentages-m1-q01",
        question: "Work out {{2/3 + 1/4}}.",
        options: ["{{3/7}}", "{{3/12}}", "{{11/12}}", "{{2/12}}"],
        answerIndex: 2,
        explanation:
          "Twelfths are the common size: {{2/3 + 1/4 = 8/12 + 3/12 = 11/12}}. {{3/7}} comes from adding tops and adding bottoms. {{3/12}} adds the numerators but multiplies the denominators without converting. {{2/12}} is {{2/3 * 1/4}} — you multiplied instead of adding.",
        difficulty: "warmup",
        guideRef: "fraction-operations",
        hints: ["You can only add pieces of the same size. What is the LCM of 3 and 4?", "Rewrite both fractions as twelfths, then add the numerators."],
        strategy: "Find a common denominator",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m1-q02",
        question: "Which of these fractions can be written as a **terminating** decimal?",
        options: ["{{7/40}}", "{{5/12}}", "{{3/14}}", "{{4/15}}"],
        answerIndex: 0,
        explanation:
          "A fraction in its simplest form terminates exactly when its denominator has no prime factors other than 2 and 5. {{40 = 2^3 * 5}}, so {{7/40 = 0.175}}. {{5/12}} and {{3/14}} have even denominators, but 12 = 2² × 3 and 14 = 2 × 7 contain a 3 and a 7, so they recur. {{4/15}} has a 5 in the denominator, but 15 = 3 × 5 also contains a 3.",
        difficulty: "warmup",
        guideRef: "recurring-decimals",
        hints: ["Write each denominator as a product of primes.", "Only 2s and 5s allowed — because 10 = 2 × 5."],
        strategy: "Eliminate options",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m1-q03",
        question: "Prices in Singapore include 9% GST. Which single multiplier adds 9% GST to a price?",
        options: ["0.09", "1.9", "0.91", "1.09"],
        answerIndex: 3,
        explanation:
          "100% + 9% = 109% = 1.09. Multiplying by 0.09 gives just the GST, not the new price. 1.9 is a 90% increase (writing 9% as 0.9). 0.91 is a 9% **decrease**.",
        difficulty: "warmup",
        guideRef: "percentage-change",
        hints: ["The new price is (100 + 9)% of the old price. Write that percentage as a decimal."],
        strategy: "Use a multiplier",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m1-q04",
        question: "The price of a bicycle falls from $250 to $210. Work out the percentage decrease.",
        options: ["19.0%", "16%", "40%", "84%"],
        answerIndex: 1,
        explanation:
          "Change ÷ **original** × 100: {{40/250 * 100 = 16}}%. 19.0% divides by the new price, $210. 40% is the change in dollars, not a percentage. 84% is {{210/250}} — the new price as a percentage of the old, not the decrease.",
        difficulty: "warmup",
        guideRef: "percentage-change",
        hints: ["First find the actual change in dollars.", "Divide the change by the ORIGINAL price, then × 100."],
        strategy: "Change over original",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m1-q05",
        question: "Work out {{2 1/4 * 1 1/3}}.",
        options: ["{{2 1/12}}", "3", "{{3 7/12}}", "{{1 11/16}}"],
        answerIndex: 1,
        explanation:
          "Convert to improper fractions first: {{9/4 * 4/3 = 36/12 = 3}}. {{2 1/12}} multiplies the whole numbers (2 × 1) and the fractions ({{1/4 * 1/3}}) separately — that misses the cross terms. {{3 7/12}} is the sum, not the product. {{1 11/16}} is {{9/4 * 3/4}}: the second fraction was flipped, which belongs to division.",
        difficulty: "core",
        guideRef: "fraction-operations",
        hints: ["Can you multiply mixed numbers part by part? Try it with {{1 1/2 * 1 1/2}} — is the answer really {{1 1/4}}?", "Write {{2 1/4}} and {{1 1/3}} as improper fractions.", "Cancel the 4s before multiplying."],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m1-q06",
        question: "Write 0.2̇7̇ (= 0.272727…) as a fraction in its simplest form.",
        options: ["{{27/100}}", "{{1/37}}", "{{3/10}}", "{{3/11}}"],
        answerIndex: 3,
        explanation:
          "Let x = 0.2727…. Two digits repeat, so use 100x = 27.2727…. Subtract: 99x = 27, so {{x = 27/99 = 3/11}}. {{27/100}} = 0.27 treats the decimal as if it stopped. {{1/37}} = {{27/999}} uses three nines for a two-digit cycle. {{3/10}} = {{27/90}} wrongly treats the 2 as a non-recurring digit.",
        difficulty: "core",
        guideRef: "recurring-decimals",
        hints: ["How many digits are in the repeating block?", "Multiply x by 100 so the repeating parts line up, then subtract x.", "99x = 27 — now simplify."],
        strategy: "Line up the repeats",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m1-q07",
        question: "In a sale, a jacket is reduced by 20%. The sale price is $68. What was the price before the sale?",
        options: ["$85", "$81.60", "$56.67", "$54.40"],
        answerIndex: 0,
        explanation:
          "$68 is 80% of the original, so original = 68 ÷ 0.8 = $85. Check: 20% of $85 is $17, and 85 − 17 = 68. $81.60 adds 20% of the **sale** price ({{68 * 1.2}}) — but the 20% was of the original. $56.67 is 68 ÷ 1.2 and $54.40 is 68 × 0.8; both go the wrong direction.",
        difficulty: "core",
        guideRef: "reverse-percentages",
        hints: ["What percentage of the original price is $68?", "Original × 0.8 = 68. Use the inverse.", "Divide 68 by 0.8 — and check your answer by reducing it by 20%."],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m1-q08",
        question: "Aisha invests $5000 at 3% per year **compound** interest. Work out the value of the investment after 4 years, to the nearest cent.",
        options: ["$5600.00", "$627.54", "$5627.54", "$5463.64"],
        answerIndex: 2,
        explanation:
          "{{5000 * 1.03^4 = 5627.544…}}, so $5627.54. $5600.00 is simple interest (3% of $5000 = $150, four times). $627.54 is only the interest earned, not the value. $5463.64 is {{5000 * 1.03^3}} — one year short.",
        difficulty: "core",
        guideRef: "compound-growth",
        hints: ["Each year the amount is multiplied by the same number. What is it?", "Value = 5000 × (multiplier)ⁿ with n = 4."],
        strategy: "Use a multiplier",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m1-q09",
        question: "Simplify fully {{(x^2 - 9)/(x^2 + 5x + 6)}}.",
        options: ["{{(x+3)/(x+2)}}", "{{-9/(5x+6)}}", "{{(x+3)/(x-2)}}", "{{(x-3)/(x+2)}}"],
        answerIndex: 3,
        explanation:
          "Factorise both: {{((x-3)(x+3))/((x+2)(x+3)) = (x-3)/(x+2)}}. {{-9/(5x+6)}} 'cancels' the {{x^2}} terms — you can only cancel **factors**, never terms. {{(x+3)/(x+2)}} comes from factorising {{x^2 - 9}} as {{(x+3)(x+3)}}. {{(x+3)/(x-2)}} comes from writing the denominator as {{(x-2)(x-3)}} — check the signs: that expands to {{x^2 - 5x + 6}}.",
        difficulty: "core",
        guideRef: "algebraic-fractions",
        hints: ["Can you cancel the {{x^2}} on top with the {{x^2}} underneath? (Try x = 1 before deciding.)", "Factorise the numerator — it's a difference of two squares.", "Factorise the denominator, then cancel the common bracket."],
        strategy: "Factorise first",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m1-q10",
        question: "Work out {{3 1/3 ÷ 1 1/4}}.",
        options: ["{{2 2/3}}", "{{4 1/6}}", "{{4 1/3}}", "{{3/8}}"],
        answerIndex: 0,
        explanation:
          "{{10/3 ÷ 5/4 = 10/3 * 4/5 = 40/15 = 8/3 = 2 2/3}}. {{4 1/6}} multiplies by {{5/4}} without flipping it. {{4 1/3}} divides the parts separately (3 ÷ 1 = 3 and {{1/3 ÷ 1/4 = 4/3}}). {{3/8}} flips the **first** fraction instead of the second.",
        difficulty: "core",
        guideRef: "fraction-operations",
        hints: ["Should the answer be more or less than 3? Estimate: about 3.3 ÷ 1.25.", "Change both to improper fractions.", "Keep the first, change ÷ to ×, flip the second."],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m1-q11",
        question: "A car is bought for $90 000. It depreciates by 12% each year. Work out its value after 3 years, to the nearest dollar.",
        options: ["$57 600", "$28 668", "$61 332", "$126 444"],
        answerIndex: 2,
        explanation:
          "Each year the value is multiplied by 0.88: {{90000 * 0.88^3 = 61332.48}}, so $61 332. $57 600 takes 36% off in one go (simple depreciation) — but each year's 12% is of a smaller value. $28 668 is the total loss, not the value. $126 444 uses 1.12 — that is growth, not depreciation.",
        difficulty: "core",
        guideRef: "compound-growth",
        hints: ["Is 12% of the value the same amount every year?", "A 12% decrease means multiplying by 0.88 each year.", "Value = 90 000 × 0.88³."],
        strategy: "Use a multiplier",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m1-q12",
        question: "Write {{3/(x+2) + 2/(x-1)}} as a single fraction in its simplest form.",
        options: ["{{5/(2x+1)}}", "{{(5x+1)/((x+2)(x-1))}}", "{{(5x-1)/((x+2)(x-1))}}", "{{5/((x+2)(x-1))}}"],
        answerIndex: 1,
        explanation:
          "Common denominator {{(x+2)(x-1)}}: numerator {{3(x-1) + 2(x+2) = 3x - 3 + 2x + 4 = 5x + 1}}. {{5/(2x+1)}} adds tops and adds bottoms. {{(5x-1)/((x+2)(x-1))}} multiplies out {{2(x+2)}} as 2x + 2. {{5/((x+2)(x-1))}} puts both over the common denominator but forgets to multiply the numerators.",
        difficulty: "core",
        guideRef: "algebraic-fractions",
        hints: ["Treat it like {{3/5 + 2/7}}: what's the common denominator?", "Use {{(x+2)(x-1)}}. What must you multiply each numerator by?", "Expand {{3(x-1) + 2(x+2)}} carefully — both terms in each bracket."],
        strategy: "Find a common denominator",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m1-q13",
        question: "A shop increases all its prices by 25%. Later, in a sale, it reduces the new prices by 20%. A coat now costs $150. What did it cost before both changes?",
        options: ["$150", "$142.86", "$157.50", "$187.50"],
        answerIndex: 0,
        explanation:
          "Overall multiplier: 1.25 × 0.8 = 1, so the price is back where it started: $150. $142.86 assumes the changes net to +5% and divides by 1.05 — but percentages of different amounts don't add. $157.50 makes the same +5% assumption, applied forwards. $187.50 only undoes the 20% sale (150 ÷ 0.8).",
        difficulty: "challenge",
        guideRef: "reverse-percentages",
        hints: ["Does +25% then −20% really make +5%? Try it on $100.", "Combine the two changes into one multiplier.", "Original × 1.25 × 0.8 = 150."],
        strategy: "Try small cases",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m1-q14",
        question: "Which fraction is equal to 0.12̇7̇ (= 0.1272727…)?",
        options: ["{{127/990}}", "{{127/999}}", "{{14/111}}", "{{7/55}}"],
        answerIndex: 3,
        explanation:
          "Let x = 0.12727…. Then 1000x = 127.2727… and 10x = 1.2727…. Subtract: 990x = 126, so {{x = 126/990 = 7/55}}. {{127/990}} forgets to subtract the non-recurring 1. {{127/999}} treats all three digits as recurring. {{14/111}} = {{126/999}} subtracts correctly but uses the wrong power of 10.",
        difficulty: "challenge",
        guideRef: "recurring-decimals",
        hints: ["Only the 27 repeats — the 1 doesn't. You need two multiples of x with the same tail.", "Try 1000x and 10x: both end in .2727….", "1000x − 10x = 990x = 127.2727… − 1.2727… — now simplify."],
        strategy: "Line up the repeats",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m1-q15",
        question: "Simplify fully {{(2x^2 + 5x - 3)/(4x^2 - 1) ÷ (x+3)/(x-2)}}.",
        options: ["{{((x+3)^2)/((2x+1)(x-2))}}", "{{(x-2)/(2x+1)}}", "{{(x-2)/(2x-1)}}", "{{(x+3)/(2x+1)}}"],
        answerIndex: 1,
        explanation:
          "{{2x^2 + 5x - 3 = (2x-1)(x+3)}} and {{4x^2 - 1 = (2x-1)(2x+1)}}, so the first fraction is {{(x+3)/(2x+1)}}. Then multiply by the reciprocal: {{(x+3)/(2x+1) * (x-2)/(x+3) = (x-2)/(2x+1)}}. {{((x+3)^2)/((2x+1)(x-2))}} multiplies without flipping. {{(x-2)/(2x-1)}} treats {{4x^2 - 1}} as {{(2x-1)^2}}. {{(x+3)/(2x+1)}} simplifies the first fraction but never divides.",
        difficulty: "challenge",
        guideRef: "algebraic-fractions",
        hints: ["Dividing by a fraction means multiplying by its reciprocal.", "{{4x^2 - 1}} is a difference of two squares.", "Factorise {{2x^2 + 5x - 3}}: look for a factor that matches one in {{4x^2 - 1}}."],
        strategy: "Factorise first",
      },
    ],
  },

  // ===========================================================================
  // MCQ Paper 2
  // ===========================================================================
  {
    id: "fractions-percentages-m2",
    title: "MCQ Paper 2",
    questions: [
      {
        kind: "mcq",
        id: "fractions-percentages-m2-q01",
        question: "Work out {{5/6 - 3/8}}.",
        options: ["{{1/24}}", "{{11/24}}", "{{29/24}}", "−1"],
        answerIndex: 1,
        explanation:
          "LCM of 6 and 8 is 24: {{20/24 - 9/24 = 11/24}}. {{1/24}} is {{2/48}} — numerators subtracted but denominators multiplied without converting. {{29/24}} adds instead of subtracting. −1 subtracts tops and bottoms: {{2/(-2)}}.",
        difficulty: "warmup",
        guideRef: "fraction-operations",
        hints: ["What is the smallest number that both 6 and 8 divide into?", "Write both fractions in 24ths, then subtract the numerators."],
        strategy: "Find a common denominator",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m2-q02",
        question: "Write {{5/8}} as a decimal.",
        options: ["0.58", "1.6", "0.625625…", "0.625"],
        answerIndex: 3,
        explanation:
          "5 ÷ 8 = 0.625 (8 = 2³, so it terminates). 0.58 just glues the digits together. 1.6 is 8 ÷ 5 — the division is the wrong way round. 0.625625… pretends it recurs, but the division stops with remainder 0.",
        difficulty: "warmup",
        guideRef: "recurring-decimals",
        hints: ["A fraction means numerator ÷ denominator. Which number goes inside the bus stop?"],
        strategy: "Use short division",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m2-q03",
        question: "Decrease $240 by 35%.",
        options: ["$156", "$84", "$205", "$324"],
        answerIndex: 0,
        explanation:
          "Multiplier 1 − 0.35 = 0.65: 240 × 0.65 = $156. $84 is the decrease itself (35% of 240), not the new amount. $205 subtracts 35 dollars, not 35 percent. $324 is an increase.",
        difficulty: "warmup",
        guideRef: "percentage-change",
        hints: ["After a 35% decrease, what percentage is left?", "Multiply 240 by 0.65."],
        strategy: "Use a multiplier",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m2-q04",
        question: "A pair of headphones costs $109 including 9% GST. What was the price before GST was added?",
        options: ["$99.19", "$118.81", "$100", "$9"],
        answerIndex: 2,
        explanation:
          "$109 is 109% of the pre-GST price: 109 ÷ 1.09 = $100. $99.19 takes 9% off $109 — but the GST was 9% of the smaller, original price. $118.81 adds GST again. $9 is the GST, not the price.",
        difficulty: "warmup",
        guideRef: "reverse-percentages",
        hints: ["$109 is what percentage of the original price?", "Divide by the multiplier 1.09."],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m2-q05",
        question: "Arjun has {{3 1/2}} m of ribbon. He cuts it into pieces that are each {{3/8}} m long. How many **complete** pieces can he cut?",
        options: ["9", "{{9 1/3}}", "10", "{{1 5/16}}"],
        answerIndex: 0,
        explanation:
          "{{7/2 ÷ 3/8 = 7/2 * 8/3 = 56/6 = 9 1/3}}, so 9 complete pieces (the {{1/3}} of a piece is left over). {{9 1/3}} is the exact division but you can't have a third of a piece. 10 rounds up — there isn't enough ribbon. {{1 5/16}} multiplies {{7/2 * 3/8}} instead of dividing.",
        difficulty: "core",
        guideRef: "fraction-operations",
        hints: ["'How many {{3/8}}s fit into {{3 1/2}}?' is a division.", "{{3 1/2 = 7/2}}. Now flip {{3/8}} and multiply.", "Read the question again: complete pieces only."],
        strategy: "Read the question twice",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m2-q06",
        question: "Exactly one of these fractions gives a **recurring** decimal. Which one?",
        options: ["{{21/35}}", "{{7/56}}", "{{11/30}}", "{{9/48}}"],
        answerIndex: 2,
        explanation:
          "Simplify first, then look at the denominator's primes. {{11/30}}: 30 = 2 × 3 × 5 and the 3 can't cancel, so it recurs (0.3666…). {{21/35 = 3/5}} (the 7 cancels), {{7/56 = 1/8}} and {{9/48 = 3/16}} (the 3 cancels) all terminate. Judging by the unsimplified denominators 35 or 48 is the trap.",
        difficulty: "core",
        guideRef: "recurring-decimals",
        hints: ["The 2-and-5 test only works on fractions in their simplest form.", "Cancel each fraction fully, then factorise its denominator."],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m2-q07",
        question: "Mei buys a phone for $640 and sells it for $720. Work out her percentage profit.",
        options: ["11.1%", "80%", "112.5%", "12.5%"],
        answerIndex: 3,
        explanation:
          "Profit = $80. Percentage profit = profit ÷ **cost price** × 100 = {{80/640 * 100 = 12.5}}%. 11.1% divides by the selling price. 80% confuses dollars with percent. 112.5% is the selling price as a percentage of the cost, not the profit.",
        difficulty: "core",
        guideRef: "percentage-change",
        hints: ["Percentage profit is a percentage change. What's the 'original' amount here?", "Divide the $80 profit by the $640 she paid."],
        strategy: "Change over original",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m2-q08",
        question: "Siti's monthly salary increases by 4% to $3380. What was her salary before the increase?",
        options: ["$3244.80", "$3250", "$3515.20", "$3520.83"],
        answerIndex: 1,
        explanation:
          "$3380 is 104% of the old salary: 3380 ÷ 1.04 = $3250. Check: 3250 × 1.04 = 3380. $3244.80 subtracts 4% of the **new** salary (3380 × 0.96). $3515.20 adds another 4%. $3520.83 divides by 0.96, mixing up increase and decrease.",
        difficulty: "core",
        guideRef: "reverse-percentages",
        hints: ["Is the 4% a percentage of $3380 or of the old salary?", "Old salary × 1.04 = 3380.", "Divide by 1.04 and check by multiplying back."],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m2-q09",
        question: "A town's population is 40 000. It grows by 3% each year. After how many complete years will the population first be more than 50 000?",
        options: ["7", "8", "9", "1"],
        answerIndex: 1,
        explanation:
          "You need {{1.03^n > 1.25}}. {{1.03^7 = 1.2298…}} (49 195 — not yet) and {{1.03^8 = 1.2667…}} (50 671), so 8 years. 7 stops a year early. 9 treats the growth as simple: 25% ÷ 3% ≈ 8.3, rounded up — but compound growth gets there sooner. 1 uses the multiplier 1.3 instead of 1.03.",
        difficulty: "core",
        guideRef: "compound-growth",
        hints: ["What does the population get multiplied by each year?", "Keep multiplying 40 000 by 1.03 (or try powers of 1.03) until you pass 50 000.", "Compare {{1.03^7}} and {{1.03^8}} with 1.25."],
        strategy: "Trial and improvement",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m2-q10",
        question: "Simplify fully {{(x^2 - 4)/(3x) * (6x^2)/(x + 2)}}.",
        options: ["{{2x(x-2)}}", "{{2x(x+2)}}", "{{(x-2)/(2x)}}", "{{2x(x^2 - 4)}}"],
        answerIndex: 0,
        explanation:
          "{{x^2 - 4 = (x-2)(x+2)}}. Cancel {{(x+2)}}, and {{(6x^2)/(3x) = 2x}}, leaving {{2x(x-2)}}. {{2x(x+2)}} cancels the wrong bracket. {{(x-2)/(2x)}} turns {{(6x^2)/(3x)}} upside down. {{2x(x^2 - 4)}} drops the {{(x+2)}} denominator without cancelling it.",
        difficulty: "core",
        guideRef: "algebraic-fractions",
        hints: ["Factorise anything you can before multiplying.", "{{x^2 - 4}} is a difference of two squares.", "Cancel common factors across the two fractions."],
        strategy: "Factorise first",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m2-q11",
        question: "Work out {{2 3/4 - 1 5/6}}.",
        options: ["{{13/12}}", "{{4 7/12}}", "{{-1/12}}", "{{11/12}}"],
        answerIndex: 3,
        explanation:
          "{{11/4 - 11/6 = 33/12 - 22/12 = 11/12}}. (Or: wholes give 1, fractions give {{3/4 - 5/6 = -1/12}}, and {{1 - 1/12 = 11/12}}.) {{13/12}} (= {{1 1/12}}) does {{5/6 - 3/4}} to avoid the negative — subtracting the wrong way round. {{4 7/12}} adds. {{-1/12}} works out the fraction parts and forgets the whole numbers.",
        difficulty: "core",
        guideRef: "fraction-operations",
        hints: ["Estimate: about 2.75 − 1.83. Is the answer more or less than 1?", "Convert to improper fractions to avoid the 'borrowing' problem.", "{{11/4}} and {{11/6}} — use 12ths."],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m2-q12",
        question: "A laptop bought for $2000 depreciates by 8% per year. Which calculation gives its value after 5 years?",
        options: ["{{2000 * 0.08^5}}", "{{2000 * (1 - 0.08 * 5)}}", "{{2000 * 0.92^5}}", "{{2000 * 1.08^5}}"],
        answerIndex: 2,
        explanation:
          "Each year the value is 92% of the year before, so multiply by 0.92 five times: {{2000 * 0.92^5}}. {{2000 * 0.08^5}} uses the percentage lost as the multiplier. {{2000 * (1 - 0.08 * 5)}} is simple depreciation — 8% of the original every year. {{2000 * 1.08^5}} is growth.",
        difficulty: "core",
        guideRef: "compound-growth",
        hints: ["After one year, what fraction of the value is left?", "Repeat that multiplier for each of the 5 years."],
        strategy: "Use a multiplier",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m2-q13",
        question: "Work out 0.1̇ × 0.2̇7̇ (that is, 0.111… × 0.272727…). Give your answer as a fraction.",
        options: ["0.027", "{{1/37}}", "{{1/33}}", "{{38/99}}"],
        answerIndex: 2,
        explanation:
          "Convert first: {{0.111… = 1/9}} and {{0.2727… = 27/99 = 3/11}}. So the product is {{1/9 * 3/11 = 3/99 = 1/33}} (= 0.0303…). 0.027 treats both decimals as terminating (0.1 × 0.27). {{1/37}} = 0.027027… just multiplies the digits and keeps them recurring. {{38/99}} adds the two fractions instead of multiplying.",
        difficulty: "challenge",
        guideRef: "recurring-decimals",
        hints: ["Recurring decimals are awkward to multiply. What form are they easy to multiply in?", "0.111… = {{1/9}}. What is 0.2727… as a fraction?", "Multiply the fractions, cancelling first."],
        strategy: "Change the representation",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m2-q14",
        question: "In a sale, all prices are reduced by 15%. On Sundays there is a further 10% off the sale price. Kenji pays $45.90 for a jacket on a Sunday. What was the original price?",
        options: ["$61.20", "$60", "$57.38", "$58.06"],
        answerIndex: 1,
        explanation:
          "Overall multiplier 0.85 × 0.9 = 0.765. Original = 45.90 ÷ 0.765 = $60. $61.20 adds the discounts to 25% and divides by 0.75. $57.38 adds 25% on to $45.90. $58.06 multiplies by 1.15 and 1.10 — reversing a decrease is not the same as increasing by the same percentage.",
        difficulty: "challenge",
        guideRef: "reverse-percentages",
        hints: ["Successive percentage changes multiply — they don't add.", "Write one multiplier for both reductions.", "Original × 0.765 = 45.90."],
        strategy: "Work backwards",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m2-q15",
        question: "Simplify fully {{2/(x^2 - 1) - 1/(x - 1)}}.",
        options: ["{{-1/(x+1)}}", "{{(3-x)/(x^2 - 1)}}", "{{1/(x+1)}}", "{{1/(x^2 - x)}}"],
        answerIndex: 0,
        explanation:
          "{{x^2 - 1 = (x-1)(x+1)}} is already a common denominator. Numerator: {{2 - (x+1) = 1 - x = -(x-1)}}. Cancelling {{(x-1)}} leaves {{-1/(x+1)}}. {{(3-x)/(x^2 - 1)}} expands {{-(x+1)}} as {{-x + 1}}. {{1/(x+1)}} cancels {{(1-x)}} with {{(x-1)}} as if they were equal — they differ by a factor of −1. {{1/(x^2 - x)}} subtracts tops and bottoms.",
        difficulty: "challenge",
        guideRef: "algebraic-fractions",
        hints: ["Factorise {{x^2 - 1}} — what do you notice about the other denominator?", "Write {{1/(x-1)}} over {{(x-1)(x+1)}}.", "Your numerator is {{1 - x}}. How does that compare with {{x - 1}}?"],
        strategy: "Look for a hidden factor",
      },
    ],
  },

  // ===========================================================================
  // MCQ Paper 3 — Exam style
  // ===========================================================================
  {
    id: "fractions-percentages-m3",
    title: "MCQ Paper 3 — Exam style",
    questions: [
      {
        kind: "mcq",
        id: "fractions-percentages-m3-q01",
        question: "Hana is asked to show that {{1 2/3 * 2 1/10 = 3 1/2}}. Which is a correct first line of working?",
        options: ["{{5/3 * 12/10}}", "{{3/3 * 3/10}}", "{{2/3 * 21/10}}", "{{5/3 * 21/10}}"],
        answerIndex: 3,
        explanation:
          "{{1 2/3 = (3 + 2)/3 = 5/3}} and {{2 1/10 = (20 + 1)/10 = 21/10}}. Then {{5/3 * 21/10 = 105/30 = 7/2 = 3 1/2}}. {{12/10}} uses whole × numerator + denominator (2 × 1 + 10) — the wrong way round. {{3/3}} and {{3/10}} add the whole number to the numerator. {{2/3 * 21/10}} drops the whole number 1.",
        difficulty: "warmup",
        guideRef: "fraction-operations",
        hints: ["How many thirds are in {{1 2/3}}? How many tenths in {{2 1/10}}?", "Whole number × denominator, then add the numerator."],
        strategy: "Show every step",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m3-q02",
        question: "The price of a durian rises from $24 to $30. Work out the percentage increase.",
        options: ["20%", "25%", "6%", "125%"],
        answerIndex: 1,
        explanation:
          "Increase $6. {{6/24 * 100 = 25}}%. 20% divides by the new price, $30. 6% treats the $6 as a percentage. 125% is the new price as a percentage of the old, not the increase.",
        difficulty: "warmup",
        guideRef: "percentage-change",
        hints: ["Find the actual increase, then divide by the original price."],
        strategy: "Change over original",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m3-q03",
        question: "Olivia invests $2000 at 4% per year **simple** interest. How much interest does she earn in 3 years?",
        options: ["$249.73", "$2240", "$240", "$80"],
        answerIndex: 2,
        explanation:
          "Simple interest is the same every year: 4% of $2000 = $80, and 3 × $80 = $240. $249.73 is the compound interest ({{2000 * 1.04^3 - 2000}}). $2240 is the total value, not the interest. $80 is only one year.",
        difficulty: "warmup",
        guideRef: "compound-growth",
        hints: ["With simple interest, is the interest calculated on the original amount or the growing amount?", "Find one year's interest, then multiply by 3."],
        strategy: "Read the question twice",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m3-q04",
        question: "Write {{7/11}} as a decimal.",
        options: ["0.636363…", "0.63", "1.571428…", "0.0636363…"],
        answerIndex: 0,
        explanation:
          "7 ÷ 11: the remainders go 4, 7, 4, 7, … so the digits 6, 3 repeat for ever: 0.636363… = 0.6̇3̇. 0.63 stops the division too early. 1.571428… is 11 ÷ 7 — the wrong way round. 0.0636363… puts the decimal point in the wrong place.",
        difficulty: "warmup",
        guideRef: "recurring-decimals",
        hints: ["Work out 7.0000 ÷ 11 by short division and watch the remainders.", "When a remainder repeats, the digits repeat."],
        strategy: "Find a pattern",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m3-q05",
        question: "At a restaurant, a 10% service charge is added to the bill. Then 9% GST is added to that total. The food costs $60. How much is the final bill?",
        options: ["$71.40", "$11.94", "$71.94", "$66.00"],
        answerIndex: 2,
        explanation:
          "Multiply by both multipliers: 60 × 1.1 × 1.09 = $71.94. $71.40 adds the percentages (19%) — but the GST is charged on the service charge too. $11.94 is just the extra charges. $66.00 forgets the GST.",
        difficulty: "core",
        guideRef: "percentage-change",
        hints: ["The GST is 9% of which amount?", "Apply one multiplier, then the other.", "60 × 1.1 × 1.09."],
        strategy: "Use a multiplier",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m3-q06",
        question: "In a sale, normal prices are reduced by 18%. The sale price of a laptop is $1066. Work out the normal price of the laptop.",
        options: ["$1257.88", "$903.39", "$874.12", "$1300"],
        answerIndex: 3,
        explanation:
          "$1066 is 82% of the normal price: 1066 ÷ 0.82 = $1300. $1257.88 adds 18% to the sale price — the 18% was of the normal price. $903.39 divides by 1.18. $874.12 takes another 18% off.",
        difficulty: "core",
        guideRef: "reverse-percentages",
        hints: ["$1066 is what percentage of the normal price?", "Normal price × 0.82 = 1066.", "Divide — then check by taking 18% off your answer."],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m3-q07",
        question: "Marcus buys a car for $40 000. Its value depreciates by 15% each year. After how many complete years will its value first be less than half of what he paid?",
        options: ["4", "5", "3", "6"],
        answerIndex: 1,
        explanation:
          "You need {{0.85^n < 0.5}}. {{0.85^4 = 0.522…}} ($20 880 — still more than half) and {{0.85^5 = 0.443…}} ($17 748), so 5 years. 4 stops one year early (it also comes from simple depreciation, 50 ÷ 15 ≈ 3.3, rounded up). 3 rounds that down. 6 counts one year too many.",
        difficulty: "core",
        guideRef: "compound-growth",
        hints: ["What is the value multiplied by each year?", "Find the first n with {{0.85^n}} below 0.5.", "Work out {{0.85^4}} and {{0.85^5}}."],
        strategy: "Trial and improvement",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m3-q08",
        question: "Simplify fully {{(x^2 - 25)/(x^2 + 2x) ÷ (x - 5)/x}}.",
        options: ["{{(x+5)/(x+2)}}", "{{((x-5)^2(x+5))/(x^2(x+2))}}", "{{(x-5)/(x+2)}}", "{{-25/(2(x-5))}}"],
        answerIndex: 0,
        explanation:
          "{{((x-5)(x+5))/(x(x+2)) * x/(x-5)}}: cancel {{(x-5)}} and x to get {{(x+5)/(x+2)}}. {{((x-5)^2(x+5))/(x^2(x+2))}} multiplies without flipping. {{(x-5)/(x+2)}} factorises {{x^2 - 25}} as {{(x-5)^2}}. {{-25/(2(x-5))}} 'cancels' {{x^2}} terms in the first fraction.",
        difficulty: "core",
        guideRef: "algebraic-fractions",
        hints: ["Turn the division into a multiplication first.", "Factorise {{x^2 - 25}} and {{x^2 + 2x}}.", "Cancel factors that appear on the top and the bottom."],
        strategy: "Factorise first",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m3-q09",
        question: "Work out {{(2 1/3 - 1 1/2) ÷ 1 1/4}}. Give your answer in its simplest form.",
        options: ["{{25/24}}", "{{14/15}}", "{{1 1/2}}", "{{2/3}}"],
        answerIndex: 3,
        explanation:
          "Bracket first: {{14/6 - 9/6 = 5/6}}. Then {{5/6 ÷ 5/4 = 5/6 * 4/5 = 4/6 = 2/3}}. {{25/24}} multiplies by {{5/4}} instead of dividing. {{14/15}} does {{1/2 - 1/3}} in the bracket (subtracting the wrong way round) to get {{1 1/6}}. {{1 1/2}} flips {{5/6}} instead of {{5/4}}.",
        difficulty: "core",
        guideRef: "fraction-operations",
        hints: ["Which part do you do first?", "Write the mixed numbers as improper fractions in sixths.", "Dividing by {{5/4}} is multiplying by {{4/5}}."],
        strategy: "Show every step",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m3-q10",
        question: "Siti wants to prove that 0.25̇ (= 0.2555…) is equal to {{23/90}}. She writes x = 0.2555…, so 100x = 25.555… and 10x = 2.555…. What does she get when she subtracts the second equation from the first?",
        options: ["{{99x = 23}}", "{{9x = 23}}", "{{90x = 23}}", "{{90x = 25.3}}"],
        answerIndex: 2,
        explanation:
          "100x − 10x = 90x and 25.555… − 2.555… = 23, so 90x = 23 and {{x = 23/90}}. The recurring tails cancel exactly — that is the whole point of choosing 100x and 10x. 99x comes from 100x − x. 9x comes from 10x − x. 90x = 25.3 uses the right coefficient but subtracts x's value (0.2555…) instead of 10x's.",
        difficulty: "core",
        guideRef: "recurring-decimals",
        hints: ["Subtract the left-hand sides and the right-hand sides separately.", "100x − 10x = ?", "25.555… − 2.555… — what happens to the 5s?"],
        strategy: "Line up the repeats",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m3-q11",
        question: "A share price rises by 20% in January and then falls by 20% in February. What is the overall percentage change?",
        options: ["4% decrease", "No change", "4% increase", "0.4% decrease"],
        answerIndex: 0,
        explanation:
          "1.2 × 0.8 = 0.96, which is 96% of the starting price — a 4% decrease. 'No change' assumes +20% and −20% cancel, but the 20% fall is of a bigger amount. A 4% increase gets the direction wrong. 0.4% misreads 0.96 as 99.6%.",
        difficulty: "core",
        guideRef: "compound-growth",
        hints: ["Try it with a starting price of $100.", "Multiply the two multipliers together.", "Compare the result with 1."],
        strategy: "Try small cases",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m3-q12",
        question: "Zara's savings increased by 6.5% during one year. At the end of the year she had $2769. How much did she have at the start of the year?",
        options: ["$2589.02", "$2600", "$2948.99", "$1678.18"],
        answerIndex: 1,
        explanation:
          "$2769 is 106.5% of the starting amount: 2769 ÷ 1.065 = $2600. $2589.02 takes 6.5% off $2769 — but the 6.5% was of the starting amount. $2948.99 adds 6.5% again. $1678.18 uses 1.65 as the multiplier for 6.5%.",
        difficulty: "core",
        guideRef: "reverse-percentages",
        hints: ["Which amount is 100%?", "What is the multiplier for a 6.5% increase?", "Start × 1.065 = 2769."],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m3-q13",
        question: "Ravi invests $8000 in an account paying r% compound interest per year. After 2 years the account is worth $8988.80. Find r.",
        options: ["6.18", "12.36", "5.66", "6"],
        answerIndex: 3,
        explanation:
          "{{8000 * m^2 = 8988.80}} gives {{m^2 = 1.1236}}, so {{m = sqrt(1.1236) = 1.06}} and r = 6. 12.36 is the total growth over 2 years. 6.18 halves that total — simple-interest thinking. 5.66 comes from {{1 - sqrt(8000/8988.80)}}, measuring the change from the final amount.",
        difficulty: "challenge",
        guideRef: "compound-growth",
        hints: ["Call the yearly multiplier m. Write an equation for 2 years.", "Divide both sides by 8000.", "{{m^2 = 1.1236}} — undo the square."],
        strategy: "Work backwards",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m3-q14",
        question: "Simplify fully {{x/(x-2) - 8/(x^2 - 4)}}.",
        options: ["{{(x-8)/(x^2 - 4)}}", "{{(x-4)/(x-2)}}", "{{(x+4)/(x+2)}}", "{{(x+4)/(x-2)}}"],
        answerIndex: 2,
        explanation:
          "Common denominator {{(x-2)(x+2)}}: numerator {{x(x+2) - 8 = x^2 + 2x - 8 = (x+4)(x-2)}}. Cancel {{(x-2)}}: {{(x+4)/(x+2)}}. {{(x-8)/(x^2 - 4)}} forgets to multiply x by {{(x+2)}}. {{(x-4)/(x-2)}} factorises {{x^2 + 2x - 8}} as {{(x-4)(x+2)}}. {{(x+4)/(x-2)}} treats {{x^2 - 4}} as {{(x-2)^2}}.",
        difficulty: "challenge",
        guideRef: "algebraic-fractions",
        hints: ["Factorise {{x^2 - 4}} — it contains the other denominator.", "Rewrite {{x/(x-2)}} over {{(x-2)(x+2)}}.", "The new numerator factorises — and one factor cancels."],
        strategy: "Factorise first",
      },
      {
        kind: "mcq",
        id: "fractions-percentages-m3-q15",
        question: "Work out {{1/2 + 1/6 + 1/12 + 1/20 + 1/30 + 1/42 + 1/56 + 1/72 + 1/90}}.",
        options: ["{{10/11}}", "{{9/10}}", "1", "{{8/9}}"],
        answerIndex: 1,
        explanation:
          "Each term is {{1/(n(n+1)) = 1/n - 1/(n+1)}}: {{1/2 = 1 - 1/2}}, {{1/6 = 1/2 - 1/3}}, …, {{1/90 = 1/9 - 1/10}}. Almost everything cancels (it telescopes), leaving {{1 - 1/10 = 9/10}}. {{10/11}} and {{8/9}} miscount the 9 terms (10 or 8). 1 assumes the sum reaches a whole — it gets close but never arrives.",
        difficulty: "challenge",
        guideRef: "fraction-operations",
        hints: ["Look at the denominators: 2 = 1 × 2, 6 = 2 × 3, 12 = 3 × 4 … What's the pattern?", "Check that {{1/2 - 1/3 = 1/6}} and {{1/3 - 1/4 = 1/12}}.", "Write every term as a difference — what cancels when you add them?"],
        strategy: "Find a pattern",
      },
    ],
  },
];
