import type { TopicPractice } from "../../types.ts";

export const practice: TopicPractice = {
  // ------------------------------------------------------------------ quiz
  quiz: [
    {
      kind: "short",
      id: "fractions-percentages-quiz-q01",
      question: "Work out {{2 1/3 + 1 3/4}}. Give your answer as a mixed number in its simplest form.",
      answer: { type: "fraction", n: 49, d: 12, simplest: true, form: "mixed", display: "{{4 1/12}}" },
      traps: [
        { spec: { type: "fraction", n: 25, d: 7 }, feedback: "{{3 4/7}} comes from adding tops and bottoms of the fraction parts ({{1/3 + 3/4}} is not {{4/7}}). Make the denominators equal first: twelfths." },
      ],
      solution: [
        "Improper fractions: {{2 1/3 = 7/3}} and {{1 3/4 = 7/4}}.",
        "Common denominator 12: {{7/3 = 28/12}} and {{7/4 = 21/12}}.",
        "{{28/12 + 21/12 = 49/12}}.",
        "{{49/12 = 4 1/12}} (12 × 4 = 48, remainder 1).",
      ],
      solutions: [
        { label: "Wholes and parts separately", steps: ["Wholes: 2 + 1 = 3.", "Parts: {{1/3 + 3/4 = 4/12 + 9/12 = 13/12 = 1 1/12}}.", "Total: {{3 + 1 1/12 = 4 1/12}}."] },
      ],
      commonError: "Forgetting that the fraction parts add to more than 1, and writing {{3 13/12}}.",
      difficulty: "warmup",
      guideRef: "fraction-operations",
      hints: ["Either convert to improper fractions, or add the wholes and the fractions separately.", "The LCM of 3 and 4 is 12."],
      strategy: "Find a common denominator",
    },
    {
      kind: "mcq",
      id: "fractions-percentages-quiz-q02",
      question: "Which of these fractions is equal to a **terminating** decimal?",
      options: ["{{7/40}}", "{{5/12}}", "{{3/14}}", "{{4/15}}"],
      answerIndex: 0,
      explanation:
        "A fraction in simplest form terminates exactly when its denominator has no prime factors other than 2 and 5. 40 = {{2^3 * 5}}, so {{7/40}} = 0.175. {{5/12}} recurs because 12 = {{2^2 * 3}} contains a 3; {{3/14}} recurs because 14 contains a 7; {{4/15}} recurs because 15 contains a 3.",
      difficulty: "warmup",
      guideRef: "recurring-decimals",
      hints: ["Write each denominator as a product of primes.", "Which primes are allowed in the denominator of a terminating decimal?"],
      strategy: "Eliminate options",
    },
    {
      kind: "short",
      id: "fractions-percentages-quiz-q03",
      question: "Increase $240 by 15%. Give your answer in dollars.",
      answer: { type: "number", value: 276, display: "$276" },
      traps: [{ spec: { type: "number", value: 36 }, feedback: "$36 is the increase. Add it on to the original $240." }],
      solution: ["Multiplier for a 15% increase: 1 + 0.15 = 1.15.", "240 × 1.15 = 276.", "New amount: $276."],
      commonError: "Stopping at the increase ($36) instead of the new amount.",
      difficulty: "warmup",
      guideRef: "percentage-change",
      hints: ["What single number do you multiply by to increase by 15%?", "100% + 15% = 115% = 1.15."],
      strategy: "Use a multiplier",
    },
    {
      kind: "short",
      id: "fractions-percentages-quiz-q04",
      question: "The price of a bicycle **including** 9% GST is $1199. Work out the price before GST was added. Give your answer in dollars.",
      answer: { type: "number", value: 1100, display: "$1100" },
      traps: [
        { spec: { type: "number", value: 1091.09 }, feedback: "You took 9% of $1199 off. But the 9% was 9% of the *original* price, not of $1199. Divide by 1.09 instead." },
      ],
      solution: ["Price with GST = original × 1.09.", "So original = 1199 ÷ 1.09.", "= $1100."],
      commonError: "Subtracting 9% of $1199 (giving $1091.09) instead of dividing by 1.09.",
      difficulty: "core",
      guideRef: "reverse-percentages",
      hints: ["$1199 is what percentage of the original price?", "$1199 is 109% of the original.", "Divide by the multiplier 1.09."],
      strategy: "Use the inverse",
    },
    {
      kind: "mcq",
      id: "fractions-percentages-quiz-q05",
      question: "Arjun invests $5000 at 3% per year **compound** interest. Which calculation gives the value of his investment after 4 years?",
      options: ["5000 × 1.03 × 4", "{{5000 * 1.03^4}}", "5000 × 1.12", "{{5000 * 0.03^4}}"],
      answerIndex: 1,
      explanation:
        "Each year the amount is multiplied by 1.03, so after 4 years it is {{5000 * 1.03^4}} (= $5627.54). 5000 × 1.12 is simple interest (4 × 3% = 12%), which ignores interest on the interest. 5000 × 1.03 × 4 multiplies by 4 instead of raising to the power 4, and {{0.03^4}} uses the rate instead of the multiplier.",
      difficulty: "core",
      guideRef: "compound-growth",
      hints: ["What happens to the money in one year?", "Year 1: × 1.03. Year 2: × 1.03 again …"],
      strategy: "Find a pattern",
    },
    {
      kind: "short",
      id: "fractions-percentages-quiz-q06",
      question: "Simplify fully {{(x^2 - 9)/(x^2 + 5x + 6)}}.",
      answer: { type: "expression", expr: "(x-3)/(x+2)", display: "{{(x-3)/(x+2)}}" },
      solution: [
        "Numerator (difference of two squares): {{x^2 - 9 = (x + 3)(x - 3)}}.",
        "Denominator: {{x^2 + 5x + 6 = (x + 2)(x + 3)}}.",
        "Cancel the common factor {{(x + 3)}}: {{(x - 3)/(x + 2)}}.",
      ],
      commonError: "Cancelling the {{x^2}} terms directly — you can only cancel common *factors*, never terms.",
      difficulty: "core",
      guideRef: "algebraic-fractions",
      hints: ["You can only cancel factors. So factorise first.", "The top is a difference of two squares.", "Both top and bottom contain the factor (x + 3)."],
      strategy: "Factorise first",
    },
    {
      kind: "short",
      id: "fractions-percentages-quiz-q07",
      question: "The recurring decimal 0.454545… has the digits 45 repeating for ever. Write it as a fraction in its simplest form.",
      answer: { type: "fraction", n: 5, d: 11, simplest: true },
      traps: [{ spec: { type: "fraction", n: 45, d: 100 }, feedback: "{{45/100}} = 0.45 exactly, which stops. The digits keep repeating, so subtract to remove the tail." }],
      solution: [
        "Let x = 0.454545…",
        "The repeat is 2 digits long, so multiply by 100: 100x = 45.454545…",
        "Subtract: 99x = 45.",
        "{{x = 45/99 = 5/11}}.",
      ],
      commonError: "Writing {{45/100}}, which is the terminating decimal 0.45.",
      difficulty: "core",
      guideRef: "recurring-decimals",
      hints: ["Call the decimal x. How long is the repeating block?", "Multiply by 100 so the repeating tails line up.", "Subtract x from 100x to kill the tail."],
      strategy: "Introduce a variable",
    },
    {
      kind: "short",
      id: "fractions-percentages-quiz-q08",
      question: "The price of a school calculator falls from $80 to $68. Work out the percentage decrease.",
      answer: { type: "number", value: 15, display: "15%" },
      traps: [{ spec: { type: "number", value: 17.6470588 }, feedback: "You divided by the new price. Percentage change always compares with the *original* value, $80." }],
      solution: ["Decrease = 80 − 68 = $12.", "Percentage decrease = {{12/80 * 100}}.", "= 15%."],
      commonError: "Dividing by the new value (68) instead of the original (80).",
      difficulty: "core",
      guideRef: "percentage-change",
      hints: ["Find the actual change first.", "Percentage change = change ÷ original × 100."],
      strategy: "Use a formula",
    },
    {
      kind: "mcq",
      id: "fractions-percentages-quiz-q09",
      question: "Work out {{1 3/4 * 2 2/3}}.",
      options: ["{{2 1/2}}", "{{21/32}}", "{{4 2/3}}", "{{4 5/12}}"],
      answerIndex: 2,
      explanation:
        "Convert to improper fractions: {{7/4 * 8/3 = 56/12 = 14/3 = 4 2/3}}. {{2 1/2}} comes from multiplying wholes (1 × 2) and fractions ({{3/4 * 2/3}}) separately — but (1 + {{3/4}})(2 + {{2/3}}) has four products, not two. {{21/32}} flips the second fraction as if dividing, and {{4 5/12}} is the sum, not the product.",
      difficulty: "core",
      guideRef: "fraction-operations",
      hints: ["Mixed numbers must become improper fractions before you multiply.", "{{1 3/4 = 7/4}} and {{2 2/3 = 8/3}}."],
      strategy: "Change the form",
    },
    {
      kind: "short",
      id: "fractions-percentages-quiz-q10",
      question: "Zara's car cost $48 000. It depreciates by 12% each year. Work out its value after 3 years. Give your answer to the nearest dollar.",
      answer: { type: "number", value: 32711, display: "$32 711" },
      traps: [{ spec: { type: "number", value: 30720 }, feedback: "That is 36% off in one go (simple depreciation). Each year's 12% is taken from the *reduced* value: use {{0.88^3}}." }],
      solution: ["Multiplier for a 12% decrease: 0.88.", "Value = {{48000 * 0.88^3}}.", "= 32 710.656 …", "≈ $32 711."],
      commonError: "Taking 3 × 12% = 36% off the original price.",
      difficulty: "core",
      guideRef: "compound-growth",
      hints: ["What is the multiplier for a 12% decrease?", "Apply it once for each year: three times.", "{{48000 * 0.88^3}}"],
      strategy: "Use a multiplier",
    },
  ],

  // ---------------------------------------------------------------- papers
  papers: [
    {
      id: "fractions-percentages-p1",
      title: "Practice Paper 1",
      questions: [
        {
          kind: "short",
          id: "fractions-percentages-p1-q01",
          question: "Work out {{3/4 - 2/5}}. Give your answer in its simplest form.",
          answer: { type: "fraction", n: 7, d: 20, simplest: true },
          traps: [{ spec: { type: "number", value: -1 }, feedback: "Subtracting tops and bottoms gives {{1/(-1)}} = −1 — a negative answer from a bigger fraction minus a smaller one can't be right. Use a common denominator of 20." }],
          solution: ["LCM of 4 and 5 is 20.", "{{3/4 = 15/20}} and {{2/5 = 8/20}}.", "{{15/20 - 8/20 = 7/20}}."],
          commonError: "Subtracting the numerators and the denominators separately.",
          difficulty: "warmup",
          guideRef: "fraction-operations",
          hints: ["Make the pieces the same size: what is the LCM of 4 and 5?"],
          strategy: "Find a common denominator",
        },
        {
          kind: "short",
          id: "fractions-percentages-p1-q02",
          question: "A pair of trainers costs $65. In a sale the price is reduced by 20%. Work out the sale price in dollars.",
          answer: { type: "number", value: 52, display: "$52" },
          traps: [{ spec: { type: "number", value: 13 }, feedback: "$13 is the reduction. Subtract it from $65 — or multiply by 0.8 in one step." }],
          solution: ["Multiplier for a 20% decrease: 1 − 0.2 = 0.8.", "65 × 0.8 = 52.", "Sale price: $52."],
          difficulty: "warmup",
          guideRef: "percentage-change",
          hints: ["If 20% is taken off, what percentage is left?"],
          strategy: "Use a multiplier",
        },
        {
          kind: "short",
          id: "fractions-percentages-p1-q03",
          question: "Without a calculator, write {{3/8}} as a decimal.",
          answer: { type: "number", value: 0.375, allowFraction: false, display: "0.375" },
          solution: ["Divide 3 by 8 using short division: 3.000 ÷ 8.", "30 ÷ 8 = 3 r 6; 60 ÷ 8 = 7 r 4; 40 ÷ 8 = 5.", "{{3/8}} = 0.375."],
          solutions: [{ label: "Halving", steps: ["{{1/8}} is half of half of {{1/2}}: 0.5 → 0.25 → 0.125.", "{{3/8}} = 3 × 0.125 = 0.375."] }],
          difficulty: "warmup",
          guideRef: "recurring-decimals",
          hints: ["A fraction means a division: 3 ÷ 8."],
          strategy: "Use known facts",
        },
        {
          kind: "short",
          id: "fractions-percentages-p1-q04",
          question: "Priya invests $2000 at 4% per year **simple** interest. How much interest does she earn in total over 3 years? Give your answer in dollars.",
          answer: { type: "number", value: 240, display: "$240" },
          traps: [
            { spec: { type: "number", value: 2240 }, feedback: "That's the total amount in the account. The question asks for the interest only." },
            { spec: { type: "number", value: 249.728 }, feedback: "That's compound interest. Simple interest is the same amount every year: 4% of $2000." },
          ],
          solution: ["Simple interest is the same each year: 4% of 2000 = $80.", "Over 3 years: 3 × 80 = $240."],
          commonError: "Using compound interest when the question says simple.",
          difficulty: "warmup",
          guideRef: "compound-growth",
          hints: ["With simple interest, the interest is worked out on the original $2000 every year."],
          strategy: "Read the question carefully",
        },
        {
          kind: "written",
          id: "fractions-percentages-p1-q05",
          question: "Show that {{3 1/3 * 1 4/5 = 6}}. Show every step of your working — do not use a calculator.",
          marks: 3,
          modelAnswer:
            "{{3 1/3 = 10/3}} and {{1 4/5 = 9/5}}.\n\n{{10/3 * 9/5 = 90/15}}.\n\n{{90/15 = 6}}.\n\n(Or cancel first: {{10/3 * 9/5 = (2 * 3)/(1 * 1) = 6}}.)",
          markScheme: [
            { point: "Both mixed numbers written as improper fractions 10/3 and 9/5", keywords: ["10/3", "9/5", "improper"] },
            { point: "Correct multiplication (90/15) or correct cancelling (2 × 3)", keywords: ["90/15", "90", "cancel", "2 × 3", "2 x 3"] },
            { point: "Simplifies to 6 with all working shown", keywords: ["= 6", "6"] },
          ],
          commonError: "Multiplying the wholes and fractions separately: 3 × 1 = 3 and {{1/3 * 4/5 = 4/15}}, giving {{3 4/15}}.",
          difficulty: "core",
          guideRef: "fraction-operations",
          hints: ["Turn each mixed number into an improper fraction first.", "Look for cancelling: 10 and 5, 9 and 3."],
          strategy: "Change the form",
        },
        {
          kind: "written",
          id: "fractions-percentages-p1-q06",
          question: "The recurring decimal 0.3181818… has the digits 18 repeating for ever. Prove algebraically that 0.3181818… = {{7/22}}.",
          marks: 3,
          modelAnswer:
            "Let x = 0.3181818…\n\nThen 10x = 3.181818… and 1000x = 318.181818…\n\nSubtracting: 1000x − 10x = 990x = 318.1818… − 3.1818… = 315.\n\nSo {{x = 315/990}}. Dividing top and bottom by 45 gives {{x = 7/22}}.",
          markScheme: [
            { point: "Two multiples of x with the same recurring tail, e.g. 10x = 3.1818… and 1000x = 318.1818…", keywords: ["10x", "1000x", "3.18", "318.18"] },
            { point: "Subtracts to get 990x = 315", keywords: ["990x", "990", "315"] },
            { point: "Simplifies 315/990 to 7/22", keywords: ["315/990", "7/22"] },
          ],
          commonError: "Using 10x − x: the tails .81818… and .31818… don't match, so the recurring part doesn't cancel. Choose multiples whose decimal parts are identical.",
          difficulty: "core",
          guideRef: "recurring-decimals",
          hints: ["Let x = 0.3181818… The '3' does not repeat — only the 18 does.", "Find two multiples of x whose decimal parts are both .181818…", "Try 10x and 1000x, then subtract."],
          strategy: "Introduce a variable",
        },
        {
          kind: "short",
          id: "fractions-percentages-p1-q07",
          question: "Wei Ling buys a second-hand phone for $450 and sells it for $567. Work out her percentage profit.",
          answer: { type: "number", value: 26, display: "26%" },
          traps: [{ spec: { type: "number", value: 20.6349206 }, feedback: "You divided by the selling price. Profit is a percentage of what she *paid* ($450)." }],
          solution: ["Profit = 567 − 450 = $117.", "Percentage profit = {{117/450 * 100}}.", "= 26%."],
          solutions: [{ label: "Multiplier", steps: ["{{567/450}} = 1.26.", "A multiplier of 1.26 means a 26% increase."] }],
          commonError: "Dividing the profit by the selling price.",
          difficulty: "core",
          guideRef: "percentage-change",
          hints: ["Work out the actual profit.", "Divide by the original (cost) price, then × 100."],
          strategy: "Use a formula",
        },
        {
          kind: "short",
          id: "fractions-percentages-p1-q08",
          question: "In a sale all prices are reduced by 35%. The sale price of a jacket is $78.65. Work out the original price of the jacket in dollars.",
          answer: { type: "number", value: 121, display: "$121" },
          traps: [
            { spec: { type: "number", value: 106.1775 }, feedback: "You added 35% of the *sale* price. The 35% was of the original price — divide by 0.65." },
            { spec: { type: "number", value: 51.1225 }, feedback: "You took 35% off again. The sale price is 65% of the original, so divide by 0.65." },
          ],
          solution: ["Sale price = 65% of the original = original × 0.65.", "Original = 78.65 ÷ 0.65.", "= $121."],
          commonError: "Adding 35% of $78.65 back on.",
          difficulty: "core",
          guideRef: "reverse-percentages",
          hints: ["After a 35% reduction, what percentage of the original is left?", "$78.65 represents 65%.", "Divide by 0.65."],
          strategy: "Use the inverse",
        },
        {
          kind: "short",
          id: "fractions-percentages-p1-q09",
          question: "Kenji invests $8000 in a savings account paying 2.5% per year compound interest. Work out the value of the investment after 6 years. Give your answer to the nearest cent.",
          answer: { type: "number", value: 9277.55, tolerance: 0.006, display: "$9277.55" },
          traps: [{ spec: { type: "number", value: 9200 }, feedback: "That's simple interest (6 × 2.5% = 15%). Compound interest earns interest on the interest — use {{1.025^6}}." }],
          solution: ["Multiplier: 1.025.", "Value = {{8000 * 1.025^6}}.", "= 9277.547 …", "≈ $9277.55."],
          commonError: "Using simple interest: 8000 × 1.15 = $9200.",
          difficulty: "core",
          guideRef: "compound-growth",
          hints: ["What is the multiplier for a 2.5% increase?", "Use it 6 times: a power."],
          strategy: "Use a multiplier",
        },
        {
          kind: "short",
          id: "fractions-percentages-p1-q10",
          question: "Simplify fully {{(3x + 6)/(x^2 - 4)}}.",
          answer: { type: "expression", expr: "3/(x-2)", display: "{{3/(x-2)}}" },
          solution: [
            "Numerator: {{3x + 6 = 3(x + 2)}}.",
            "Denominator: {{x^2 - 4 = (x + 2)(x - 2)}}.",
            "Cancel {{(x + 2)}}: {{3/(x - 2)}}.",
          ],
          commonError: "Cancelling the 6 with the 4, or the x with the {{x^2}} — those are terms, not factors.",
          difficulty: "core",
          guideRef: "algebraic-fractions",
          hints: ["Factorise the top and the bottom separately.", "The bottom is a difference of two squares."],
          strategy: "Factorise first",
        },
        {
          kind: "short",
          id: "fractions-percentages-p1-q11",
          question: "Write {{2/(x + 1) + 3/(x - 2)}} as a single fraction in its simplest form.",
          answer: { type: "expression", expr: "(5x-1)/((x+1)(x-2))", display: "{{(5x - 1)/((x + 1)(x - 2))}}" },
          traps: [{ spec: { type: "expression", expr: "5/(2x-1)" }, feedback: "You added tops and bottoms. Use the common denominator (x + 1)(x − 2), just as with number fractions." }],
          solution: [
            "Common denominator: {{(x + 1)(x - 2)}}.",
            "{{(2(x - 2))/((x + 1)(x - 2)) + (3(x + 1))/((x + 1)(x - 2))}}.",
            "Numerator: {{2x - 4 + 3x + 3 = 5x - 1}}.",
            "Answer: {{(5x - 1)/((x + 1)(x - 2))}}.",
          ],
          commonError: "Adding numerators and denominators: {{5/(2x - 1)}}.",
          difficulty: "core",
          guideRef: "algebraic-fractions",
          hints: ["Treat it exactly like {{2/3 + 3/5}}.", "Multiply the denominators to get a common denominator.", "Each numerator gets multiplied by the *other* denominator."],
          strategy: "Find a common denominator",
        },
        {
          kind: "written",
          id: "fractions-percentages-p1-q12",
          question:
            "After a 20% price rise, a ticket to the Sentosa aquarium costs $96.\n\nRavi says: \"The old price was $96 − 20% of $96 = $76.80.\"\n\nExplain Ravi's mistake and work out the correct old price.",
          marks: 3,
          modelAnswer:
            "Ravi has taken 20% of the **new** price. The 20% rise was 20% of the **old** price, so $96 is 120% of the old price, not 100%.\n\nOld price = 96 ÷ 1.2 = $80.\n\nCheck: 80 × 1.2 = 96 ✓ (whereas 76.80 × 1.2 = 92.16 ✗).",
          markScheme: [
            { point: "Explains the 20% is of the original (old) price, not the new price", keywords: ["original", "old price", "not of 96", "new price", "of the old"] },
            { point: "States $96 = 120% (or uses multiplier 1.2)", keywords: ["120%", "1.2", "120"] },
            { point: "Correct old price $80", keywords: ["80"] },
          ],
          commonError: "Just saying \"he should divide\" without explaining which amount the 20% belongs to.",
          difficulty: "core",
          guideRef: "reverse-percentages",
          hints: ["20% of *which* amount was added on?", "Test Ravi's answer: increase $76.80 by 20%. Do you get $96?", "$96 is 120% of the old price."],
          strategy: "Check by substituting",
        },
        {
          kind: "short",
          id: "fractions-percentages-p1-q13",
          question:
            "A car is bought for $12 000. Its value depreciates by 15% each year. After how many whole years will its value **first** be less than $5000?",
          answer: { type: "number", value: 6, display: "6 years" },
          traps: [{ spec: { type: "number", value: 5 }, feedback: "After 5 years it is worth $5324.46 — still above $5000. Check one more year." }],
          solution: [
            "Value after n years = {{12000 * 0.85^n}}.",
            "n = 5: {{12000 * 0.85^5}} = $5324.46 (not yet below $5000).",
            "n = 6: {{12000 * 0.85^6}} = $4525.79 (below $5000).",
            "So 6 years.",
          ],
          solutions: [
            { label: "Year-by-year table", steps: ["12 000 → 10 200 → 8670 → 7369.50 → 6264.08 → 5324.46 → 4525.79.", "The sixth value is the first below 5000."] },
          ],
          commonError: "Stopping at 5 years because the value is 'close to' $5000, or using simple depreciation (12 000 ÷ 1800 ≈ 3.9 years).",
          difficulty: "challenge",
          guideRef: "compound-growth",
          hints: ["Write a formula for the value after n years.", "Try values of n — trial and improvement is fine here.", "Compare {{12000 * 0.85^5}} and {{12000 * 0.85^6}} with 5000."],
          strategy: "Trial and improvement",
        },
        {
          kind: "short",
          id: "fractions-percentages-p1-q14",
          question: "Simplify fully {{(2x^2 + 5x - 3)/(4x^2 - 1) ÷ (x^2 + 3x)/(2x + 1)}}.",
          answer: { type: "expression", expr: "1/x", display: "{{1/x}}" },
          traps: [{ spec: { type: "expression", expr: "(x+3)^2*x/(2x+1)^2" }, feedback: "You multiplied instead of dividing. Flip the second fraction first." }],
          solution: [
            "Factorise everything: {{2x^2 + 5x - 3 = (2x - 1)(x + 3)}}, {{4x^2 - 1 = (2x - 1)(2x + 1)}}, {{x^2 + 3x = x(x + 3)}}.",
            "Flip and multiply: {{((2x - 1)(x + 3))/((2x - 1)(2x + 1)) * (2x + 1)/(x(x + 3))}}.",
            "Cancel {{(2x - 1)}}, {{(x + 3)}} and {{(2x + 1)}}.",
            "Left with {{1/x}}.",
          ],
          commonError: "Cancelling before flipping the second fraction — cancelling across a ÷ sign is not allowed.",
          difficulty: "challenge",
          guideRef: "algebraic-fractions",
          hints: ["Turn the division into a multiplication first.", "Factorise all four expressions. One is a difference of two squares.", "{{2x^2 + 5x - 3}} has a factor (x + 3)."],
          strategy: "Factorise first",
        },
        {
          kind: "short",
          id: "fractions-percentages-p1-q15",
          question:
            "The price of a pair of headphones is increased by 20%. The new price is then reduced by 15%. The headphones now cost $102. Work out the original price in dollars.",
          answer: { type: "number", value: 100, display: "$100" },
          traps: [{ spec: { type: "number", value: 97.14285714 }, feedback: "+20% then −15% is not +5%. Combine the multipliers: 1.2 × 0.85 = 1.02." }],
          solution: ["Overall multiplier: 1.2 × 0.85 = 1.02.", "Original × 1.02 = 102.", "Original = 102 ÷ 1.02 = $100."],
          solutions: [{ label: "Undo each step", steps: ["Before the 15% cut: 102 ÷ 0.85 = $120.", "Before the 20% rise: 120 ÷ 1.2 = $100."] }],
          commonError: "Treating the changes as a single 5% increase (102 ÷ 1.05 = $97.14).",
          difficulty: "challenge",
          guideRef: "reverse-percentages",
          hints: ["Write the two changes as multipliers.", "What single multiplier has the same effect?", "Divide $102 by that combined multiplier."],
          strategy: "Work backwards",
        },
      ],
    },
    {
      id: "fractions-percentages-p2",
      title: "Practice Paper 2",
      questions: [
        {
          kind: "short",
          id: "fractions-percentages-p2-q01",
          question: "Work out {{3 1/5 - 1 3/4}}. Give your answer as a mixed number in its simplest form.",
          answer: { type: "fraction", n: 29, d: 20, simplest: true, form: "mixed", display: "{{1 9/20}}" },
          traps: [{ spec: { type: "fraction", n: 51, d: 20 }, feedback: "You did 3 − 1 = 2 and then {{3/4 - 1/5}} — the wrong way round. Since {{1/5}} is less than {{3/4}}, convert to improper fractions." }],
          solution: [
            "Improper fractions: {{16/5 - 7/4}}.",
            "Common denominator 20: {{64/20 - 35/20 = 29/20}}.",
            "{{29/20 = 1 9/20}}.",
          ],
          commonError: "Subtracting {{1/5 - 3/4}} the wrong way round to avoid a negative.",
          difficulty: "warmup",
          guideRef: "fraction-operations",
          hints: ["{{1/5}} is smaller than {{3/4}}, so improper fractions are safest.", "The LCM of 5 and 4 is 20."],
          strategy: "Change the form",
        },
        {
          kind: "short",
          id: "fractions-percentages-p2-q02",
          question: "The recurring decimal 0.777… has the digit 7 repeating for ever. Write it as a fraction.",
          answer: { type: "fraction", n: 7, d: 9 },
          traps: [{ spec: { type: "fraction", n: 7, d: 10 }, feedback: "{{7/10}} = 0.7 exactly. A single repeating digit gives ninths." }],
          solution: ["Let x = 0.777…", "10x = 7.777…", "Subtract: 9x = 7, so {{x = 7/9}}."],
          difficulty: "warmup",
          guideRef: "recurring-decimals",
          hints: ["Let x = 0.777… and multiply by 10, then subtract."],
          strategy: "Introduce a variable",
        },
        {
          kind: "short",
          id: "fractions-percentages-p2-q03",
          question: "A sofa costs $1350 before GST. GST of 9% is added. Work out the price including GST, in dollars.",
          answer: { type: "number", value: 1471.5, display: "$1471.50" },
          traps: [{ spec: { type: "number", value: 121.5 }, feedback: "$121.50 is the GST. Add it on to get the total price." }],
          solution: ["Multiplier: 1.09.", "1350 × 1.09 = 1471.50.", "Price including GST: $1471.50."],
          difficulty: "warmup",
          guideRef: "percentage-change",
          hints: ["100% + 9% = 109%. What multiplier is that?"],
          strategy: "Use a multiplier",
        },
        {
          kind: "short",
          id: "fractions-percentages-p2-q04",
          question: "The number of members of a school CCA increased by 25%. There are now 35 members. How many members were there before the increase?",
          answer: { type: "number", value: 28 },
          traps: [{ spec: { type: "number", value: 26.25 }, feedback: "You took 25% of 35 off. 35 is 125% of the old number — divide by 1.25." }],
          solution: ["35 = 125% of the original.", "Original = 35 ÷ 1.25 = 28."],
          difficulty: "warmup",
          guideRef: "reverse-percentages",
          hints: ["35 members is what percentage of the original number?"],
          strategy: "Use the inverse",
        },
        {
          kind: "written",
          id: "fractions-percentages-p2-q05",
          question: "Show that {{2 3/4 ÷ 1 5/6 = 1 1/2}}. Show every step of your working — do not use a calculator.",
          marks: 3,
          modelAnswer:
            "{{2 3/4 = 11/4}} and {{1 5/6 = 11/6}}.\n\n{{11/4 ÷ 11/6 = 11/4 * 6/11}}.\n\n{{= 66/44 = 3/2 = 1 1/2}}.",
          markScheme: [
            { point: "Both mixed numbers written as improper fractions 11/4 and 11/6", keywords: ["11/4", "11/6"] },
            { point: "Division turned into multiplication by the reciprocal 6/11", keywords: ["6/11", "reciprocal", "flip", "× 6/11", "x 6/11"] },
            { point: "Simplifies correctly to 3/2 = 1 1/2", keywords: ["66/44", "6/4", "3/2", "1 1/2"] },
          ],
          commonError: "Flipping the first fraction instead of the second.",
          difficulty: "core",
          guideRef: "fraction-operations",
          hints: ["Improper fractions first.", "Dividing by a fraction = multiplying by its reciprocal.", "Notice both numerators are 11."],
          strategy: "Use the inverse",
        },
        {
          kind: "written",
          id: "fractions-percentages-p2-q06",
          question: "The recurring decimal 0.1272727… has the digits 27 repeating for ever. Prove algebraically that 0.1272727… = {{7/55}}.",
          marks: 3,
          modelAnswer:
            "Let x = 0.1272727…\n\nThen 10x = 1.272727… and 1000x = 127.272727…\n\nSubtracting: 990x = 127.2727… − 1.2727… = 126.\n\nSo {{x = 126/990}}. Dividing top and bottom by 18 gives {{x = 7/55}}.",
          markScheme: [
            { point: "Two multiples of x with identical recurring parts, e.g. 10x = 1.2727… and 1000x = 127.2727…", keywords: ["10x", "1000x", "1.27", "127.27"] },
            { point: "Subtracts to get 990x = 126", keywords: ["990x", "990", "126"] },
            { point: "Simplifies 126/990 to 7/55", keywords: ["126/990", "7/55"] },
          ],
          commonError: "Writing 100x − x = 12.6, which leaves a non-recurring decimal behind and doesn't finish the proof cleanly.",
          difficulty: "core",
          guideRef: "recurring-decimals",
          hints: ["Only the 27 repeats — the 1 does not.", "Find two multiples of x that both end .272727…", "10x and 1000x work. Subtract."],
          strategy: "Introduce a variable",
        },
        {
          kind: "short",
          id: "fractions-percentages-p2-q07",
          question: "At a hawker centre the price of a plate of vegetarian bee hoon rises from $3.20 to $3.60. Work out the percentage increase.",
          answer: { type: "number", value: 12.5, display: "12.5%" },
          traps: [{ spec: { type: "number", value: 11.1111111 }, feedback: "You divided by the new price. Compare with the original $3.20." }],
          solution: ["Increase = 3.60 − 3.20 = $0.40.", "Percentage increase = {{0.40/3.20 * 100}} = 12.5%."],
          difficulty: "core",
          guideRef: "percentage-change",
          hints: ["Find the increase in dollars first.", "Divide by the original price, then × 100."],
          strategy: "Use a formula",
        },
        {
          kind: "short",
          id: "fractions-percentages-p2-q08",
          question: "Siti's monthly salary increases by 4%. Her new salary is $4524 per month. Work out her salary before the increase, in dollars.",
          answer: { type: "number", value: 4350, display: "$4350" },
          traps: [{ spec: { type: "number", value: 4343.04 }, feedback: "You subtracted 4% of the *new* salary. $4524 is 104% of the old salary — divide by 1.04." }],
          solution: ["$4524 = 104% of the old salary.", "Old salary = 4524 ÷ 1.04 = $4350."],
          commonError: "Subtracting 4% of $4524.",
          difficulty: "core",
          guideRef: "reverse-percentages",
          hints: ["Which amount is 100%: the old salary or the new one?", "$4524 is 104%.", "Divide by 1.04."],
          strategy: "Use the inverse",
        },
        {
          kind: "short",
          id: "fractions-percentages-p2-q09",
          question:
            "A laptop bought for $2400 depreciates by the same percentage each year. After 2 years it is worth $1536. Work out the annual percentage rate of depreciation.",
          answer: { type: "number", value: 20, display: "20%" },
          traps: [
            { spec: { type: "number", value: 18 }, feedback: "Splitting the 36% total loss equally between the years ignores compounding. Find the multiplier m with {{m^2 = 0.64}}." },
            { spec: { type: "number", value: 80 }, feedback: "0.8 is the multiplier — it means 80% is *kept* each year. What percentage is lost?" },
          ],
          solution: ["{{2400 * m^2 = 1536}}, so {{m^2 = 1536/2400 = 0.64}}.", "m = {{sqrt(0.64)}} = 0.8.", "A multiplier of 0.8 means a 20% decrease each year."],
          commonError: "Halving the total 36% loss to get 18%.",
          difficulty: "core",
          guideRef: "compound-growth",
          hints: ["Call the yearly multiplier m. What is the value after 2 years?", "{{2400 m^2 = 1536}}.", "Square-root to find m, then turn it into a percentage decrease."],
          strategy: "Introduce a variable",
        },
        {
          kind: "short",
          id: "fractions-percentages-p2-q10",
          question: "Simplify fully {{(x^2 + 3x - 10)/(2x^2 - 8x + 8)}}.",
          answer: { type: "expression", expr: "(x+5)/(2(x-2))", display: "{{(x + 5)/(2(x - 2))}}" },
          solution: [
            "Numerator: {{x^2 + 3x - 10 = (x + 5)(x - 2)}}.",
            "Denominator: {{2x^2 - 8x + 8 = 2(x^2 - 4x + 4) = 2(x - 2)^2}}.",
            "Cancel one factor of {{(x - 2)}}: {{(x + 5)/(2(x - 2))}}.",
          ],
          commonError: "Forgetting to take out the common factor 2 before factorising the denominator.",
          difficulty: "core",
          guideRef: "algebraic-fractions",
          hints: ["Look for a common factor in the denominator first.", "{{x^2 - 4x + 4}} is a perfect square.", "Cancel one (x − 2), not both."],
          strategy: "Factorise first",
        },
        {
          kind: "short",
          id: "fractions-percentages-p2-q11",
          question: "Simplify fully {{(x^2 - 16)/(3x) * (6x^2)/(x + 4)}}. Give your answer in the form ax(x + b).",
          answer: { type: "expression", expr: "2x(x-4)", display: "{{2x(x - 4)}}" },
          solution: [
            "Factorise: {{x^2 - 16 = (x + 4)(x - 4)}}.",
            "{{((x + 4)(x - 4))/(3x) * (6x^2)/(x + 4)}}.",
            "Cancel {{(x + 4)}}, and {{(6x^2)/(3x) = 2x}}.",
            "Answer: {{2x(x - 4)}}.",
          ],
          commonError: "Multiplying out everything first, which makes the cancelling much harder to see.",
          difficulty: "core",
          guideRef: "algebraic-fractions",
          hints: ["Factorise before you multiply.", "{{x^2 - 16}} is a difference of two squares.", "{{6x^2}} ÷ 3x = 2x."],
          strategy: "Factorise first",
        },
        {
          kind: "written",
          id: "fractions-percentages-p2-q12",
          question:
            "Aisha invests $5000 at 4% per year **simple** interest.\nMarcus invests $5000 at 3.8% per year **compound** interest.\n\nShow that after 5 years Marcus has more money than Aisha.",
          marks: 3,
          modelAnswer:
            "Aisha: interest each year = 4% of 5000 = $200, so after 5 years she has 5000 + 5 × 200 = $6000.\n\nMarcus: {{5000 * 1.038^5}} = $6025.00 (to the nearest cent).\n\n$6025.00 > $6000, so Marcus has more (by about $25).",
          markScheme: [
            { point: "Aisha's total $6000 (or interest $1000)", keywords: ["6000", "1000", "200"] },
            { point: "Marcus's total using 5000 × 1.038^5 ≈ $6025", keywords: ["1.038", "6025", "6024.99", "6024.996"] },
            { point: "Correct comparison and conclusion", keywords: ["more", "greater", "6025 > 6000", "marcus"] },
          ],
          commonError: "Rounding Marcus's multiplier too early (e.g. 1.038^5 ≈ 1.2 gives exactly 6000 and hides the difference).",
          difficulty: "core",
          guideRef: "compound-growth",
          hints: ["Simple interest: the same amount every year.", "Compound interest: multiply by 1.038 five times.", "Keep full calculator accuracy until the end."],
          strategy: "Compare like with like",
        },
        {
          kind: "short",
          id: "fractions-percentages-p2-q13",
          question:
            "The value of a painting increases by 8% in the first year and by 6% in the second year, then decreases by 5% in the third year. Work out the overall percentage change over the 3 years. Give your answer to 3 significant figures.",
          answer: { type: "number", value: 8.76, tolerance: 0.005, display: "8.76% increase" },
          traps: [{ spec: { type: "number", value: 9 }, feedback: "8 + 6 − 5 = 9 ignores that each change acts on a different amount. Multiply the multipliers." }],
          solution: ["Multipliers: 1.08, 1.06, 0.95.", "Overall: 1.08 × 1.06 × 0.95 = 1.08756.", "That is an increase of 8.756% ≈ 8.76%."],
          solutions: [{ label: "Pick a starting value", steps: ["Start with $100.", "100 → 108 → 114.48 → 108.756.", "Increase of $8.756 on $100 = 8.76%."] }],
          commonError: "Adding the percentages: 8 + 6 − 5 = 9%.",
          difficulty: "challenge",
          guideRef: "compound-growth",
          hints: ["Each change is a multiplier.", "Multiply the three multipliers together.", "Turn the combined multiplier back into a percentage change."],
          strategy: "Make it simpler",
        },
        {
          kind: "short",
          id: "fractions-percentages-p2-q14",
          question: "Write {{1/(x - 2) - 4/(x^2 - 4)}} as a single fraction in its simplest form.",
          answer: { type: "expression", expr: "1/(x+2)", display: "{{1/(x + 2)}}" },
          traps: [{ spec: { type: "expression", expr: "-3/(x^2-4)" }, feedback: "You changed the denominator of {{1/(x - 2)}} to {{x^2 - 4}} but left its numerator as 1. Multiply top and bottom by (x + 2)." }],
          solution: [
            "{{x^2 - 4 = (x - 2)(x + 2)}}, so that is the common denominator.",
            "{{1/(x - 2) = (x + 2)/((x - 2)(x + 2))}}.",
            "{{(x + 2 - 4)/((x - 2)(x + 2)) = (x - 2)/((x - 2)(x + 2))}}.",
            "Cancel {{(x - 2)}}: {{1/(x + 2)}}.",
          ],
          commonError: "Using {{(x - 2)(x^2 - 4)}} as the denominator, which makes the algebra much harder, or not cancelling at the end.",
          difficulty: "challenge",
          guideRef: "algebraic-fractions",
          hints: ["Factorise {{x^2 - 4}} — it already contains (x − 2).", "So the lowest common denominator is just (x − 2)(x + 2).", "After subtracting, check whether the numerator cancels with the denominator."],
          strategy: "Factorise first",
        },
        {
          kind: "short",
          id: "fractions-percentages-p2-q15",
          question:
            "x = 0.8333… (the 3 repeats for ever) and y = 0.272727… (the 27 repeats for ever). Without a calculator, work out x ÷ y. Give your answer as a mixed number in its simplest form.",
          answer: { type: "fraction", n: 55, d: 18, simplest: true, form: "mixed", display: "{{3 1/18}}" },
          traps: [{ spec: { type: "fraction", n: 18, d: 55 }, feedback: "That's y ÷ x. Divide x by y." }],
          solution: [
            "x: 10x = 8.333…, 100x = 83.333…, so 90x = 75 and {{x = 75/90 = 5/6}}.",
            "y: 100y = 27.2727…, so 99y = 27 and {{y = 27/99 = 3/11}}.",
            "{{x ÷ y = 5/6 * 11/3 = 55/18}}.",
            "{{55/18 = 3 1/18}}.",
          ],
          commonError: "Treating all of 0.8333… as repeating and writing x = {{8/9}} or {{83/99}} — only the 3 repeats.",
          difficulty: "challenge",
          guideRef: "recurring-decimals",
          hints: ["Turn each recurring decimal into a fraction first.", "For x, only the 3 repeats: use 100x − 10x.", "Then divide fractions: multiply by the reciprocal."],
          strategy: "Change the form",
        },
      ],
    },
  ],

  // ------------------------------------------------------------- challenge
  challenge: [
    {
      kind: "short",
      id: "fractions-percentages-ch-q01",
      question: "For how many integers n with 1 ≤ n ≤ 100 is {{n/120}} a **terminating** decimal?",
      answer: { type: "number", value: 33 },
      traps: [
        { spec: { type: "number", value: 0 }, feedback: "120 contains a factor 3 — but the fraction may simplify. When does the 3 cancel?" },
        { spec: { type: "number", value: 34 }, feedback: "Count the multiples of 3 between 1 and 100 carefully: 3, 6, …, 99." },
      ],
      solution: [
        "120 = {{2^3 * 3 * 5}}.",
        "In simplest form, {{n/120}} terminates exactly when the factor 3 in the denominator cancels — i.e. when 3 divides n.",
        "(Any factors of 2 or 5 left in the denominator are fine.)",
        "Multiples of 3 from 1 to 100: 3, 6, …, 99 — that is 33 of them.",
      ],
      solutions: [
        { label: "Multiply to clear the 2s and 5s", steps: ["{{n/120 * 1000 = (25n)/3}}.", "A decimal terminates exactly when multiplying by a big enough power of 10 makes it a whole number — and multiplying by more 10s only adds more factors of 2 and 5, never 3.", "So {{n/120}} terminates exactly when {{(25n)/3}} is whole, i.e. when 3 divides n: 33 values."] },
      ],
      difficulty: "challenge",
      guideRef: "recurring-decimals",
      hints: [
        "Write 120 as a product of primes.",
        "Which prime in the denominator causes a recurring decimal?",
        "The fraction must be in its simplest form before you judge. When does that prime cancel?",
        "Count the multiples of 3 up to 100.",
      ],
      strategy: "Split into cases",
    },
    {
      kind: "short",
      id: "fractions-percentages-ch-q02",
      question:
        "{{1/7}} = 0.142857142857… (the block 142857 repeats). What is the 100th digit after the decimal point in the decimal for {{3/7}}?",
      answer: { type: "number", value: 5 },
      traps: [
        { spec: { type: "number", value: 8 }, feedback: "That's the 100th digit of {{1/7}}. The block for {{3/7}} starts differently — work out 3 ÷ 7 first." },
        { spec: { type: "number", value: 4 }, feedback: "100 is not a multiple of 6. Find the remainder when 100 is divided by 6." },
      ],
      solution: [
        "{{3/7}} = 0.428571428571… — the block 428571 has length 6.",
        "100 = 6 × 16 + 4, so the 100th digit is the 4th digit of the block.",
        "The 4th digit of 428571 is 5.",
      ],
      solutions: [
        { label: "Use the cycle of 1/7", steps: ["{{3/7 = 3 * 0.142857…}} — and the digits of 3/7 are the same cycle 142857 started at a different point: 428571.", "Position 100 ≡ 4 (mod 6) → 5."] },
      ],
      difficulty: "challenge",
      guideRef: "recurring-decimals",
      hints: ["Write out the decimal for {{3/7}} using division.", "How long is the repeating block?", "Which position in the block is digit number 100? Use the remainder on dividing by 6."],
      strategy: "Find a pattern",
    },
    {
      kind: "short",
      id: "fractions-percentages-ch-q03",
      question: "Without a calculator, work out {{(1 + 1/2)(1 + 1/3)(1 + 1/4) * ... * (1 + 1/99)}}.",
      answer: { type: "number", value: 50 },
      traps: [{ spec: { type: "number", value: 100 }, feedback: "Close — check the first numerator and the last denominator that survive the cancelling." }],
      solution: [
        "Each bracket is {{(n + 1)/n}}: {{3/2 * 4/3 * 5/4 * ... * 100/99}}.",
        "Every numerator cancels with the next denominator (telescoping).",
        "Only the first denominator, 2, and the last numerator, 100, survive.",
        "{{100/2 = 50}}.",
      ],
      solutions: [
        { label: "Try small cases", steps: ["Up to {{1 + 1/3}}: {{3/2 * 4/3 = 2}}.", "Up to {{1 + 1/4}}: {{5/2}}. Up to {{1 + 1/5}}: 3.", "Pattern: up to {{1 + 1/n}} gives {{(n + 1)/2}}. With n = 99: 50."] },
      ],
      difficulty: "challenge",
      guideRef: "fraction-operations",
      hints: ["Write each bracket as a single fraction.", "Write out the first three or four fractions side by side. What do you notice?", "Almost everything cancels. What is left?"],
      strategy: "Try small cases",
    },
    {
      kind: "short",
      id: "fractions-percentages-ch-q04",
      question:
        "Positive integers a and b, with a < b, satisfy {{1/a + 1/b = 1/6}}. How many such pairs (a, b) are there?",
      answer: { type: "number", value: 4 },
      traps: [{ spec: { type: "number", value: 5 }, feedback: "a = b = 12 is a solution, but the question needs a < b." }],
      solution: [
        "Multiply by 6ab: 6b + 6a = ab, so ab − 6a − 6b = 0.",
        "Add 36 to both sides: ab − 6a − 6b + 36 = 36, i.e. (a − 6)(b − 6) = 36.",
        "Both a and b exceed 6 (each fraction is less than {{1/6}}), so a − 6 and b − 6 are positive factor pairs of 36 with the first smaller: 1 × 36, 2 × 18, 3 × 12, 4 × 9 (6 × 6 gives a = b).",
        "Pairs: (7, 42), (8, 24), (9, 18), (10, 15) — 4 pairs.",
      ],
      solutions: [
        { label: "Bound and check", steps: ["a < b means {{1/a > 1/12}}, so a < 12; and {{1/a < 1/6}}, so a > 6.", "Try a = 7, 8, 9, 10, 11: {{1/b = 1/6 - 1/a}} gives b = 42, 24, 18, 15, and for a = 11, {{1/b = 5/66}} — not a unit fraction.", "4 pairs."] },
      ],
      difficulty: "challenge",
      guideRef: "fraction-operations",
      hints: [
        "Which is bigger, a or 6? Why?",
        "Clear the fractions: multiply through by 6ab.",
        "Rearrange ab − 6a − 6b = 0 so it factorises — add 36 to both sides.",
        "Now count factor pairs of 36.",
      ],
      strategy: "Consider extremes",
    },
    {
      kind: "written",
      id: "fractions-percentages-ch-q05",
      question:
        "A shop increases all its prices by x%. Later it reduces the new prices by x%.\n\n(a) Prove that the final prices are always lower than the original prices (for any x > 0), and find the overall percentage decrease in terms of x.\n\n(b) The overall decrease is 4%. Find x.",
      marks: 4,
      modelAnswer:
        "(a) The multipliers are {{1 + x/100}} and {{1 - x/100}}. Combined: {{(1 + x/100)(1 - x/100) = 1 - x^2/10000}} (difference of two squares).\n\nSince {{x^2/10000 > 0}} for x > 0, the combined multiplier is less than 1, so prices always end lower. The decrease is {{x^2/10000}} as a fraction, i.e. {{x^2/100}} %.\n\n(b) {{x^2/100 = 4}}, so {{x^2 = 400}} and x = 20 (x > 0).\n\nCheck: 1.2 × 0.8 = 0.96, a 4% decrease ✓.",
      markScheme: [
        { point: "Writes the two multipliers and multiplies them", keywords: ["1 + x/100", "1 - x/100", "1 − x/100", "multiplier"] },
        { point: "Obtains 1 − x²/10000 (difference of two squares)", keywords: ["x^2/10000", "x²/10000", "10000", "difference of two squares"] },
        { point: "Argues it is less than 1 so always a decrease, of x²/100 %", keywords: ["less than 1", "always", "x^2/100", "x²/100", "decrease"] },
        { point: "Solves x²/100 = 4 to get x = 20", keywords: ["x = 20", "20", "400"] },
      ],
      solutions: [
        { label: "Area model", steps: ["Picture a square of side 1 changed to a rectangle with sides {{1 + x/100}} and {{1 - x/100}}.", "The strip added on one side is exactly matched by the strip removed — except for a small corner square of side {{x/100}} that is lost.", "So the area falls by {{(x/100)^2}}."] },
      ],
      commonError: "Assuming +x% then −x% cancels out, because the second x% is taken from a bigger amount.",
      difficulty: "challenge",
      guideRef: "percentage-change",
      hints: [
        "Try x = 10 first: what happens to $100?",
        "Write each change as a multiplier in terms of x.",
        "Multiply the multipliers — do you recognise a difference of two squares?",
        "Set the decrease equal to 4% and solve.",
      ],
      strategy: "Try small cases, then generalise",
    },
    {
      kind: "short",
      id: "fractions-percentages-ch-q06",
      question:
        "At a restaurant, Mei's bill is worked out like this: the menu total is reduced by 20% with a voucher, then a 10% service charge is added, then 9% GST is added to that. She pays $95.92. Work out the menu total before any changes, in dollars.",
      answer: { type: "number", value: 100, display: "$100" },
      traps: [
        { spec: { type: "number", value: 96.88888889 }, feedback: "−20% + 10% + 9% = −1% only works if all percentages were of the same amount. Multiply the three multipliers." },
        { spec: { type: "number", value: 80 }, feedback: "$80 is the price after the voucher. Undo the 20% discount too." },
      ],
      solution: [
        "Multipliers: 0.8 (voucher), 1.1 (service), 1.09 (GST).",
        "Combined: 0.8 × 1.1 × 1.09 = 0.9592.",
        "Menu total = 95.92 ÷ 0.9592 = $100.",
      ],
      solutions: [
        { label: "Undo one step at a time", steps: ["Before GST: 95.92 ÷ 1.09 = 88.", "Before service charge: 88 ÷ 1.1 = 80.", "Before voucher: 80 ÷ 0.8 = $100."] },
      ],
      commonError: "Adding and subtracting the percentages (−20 + 10 + 9 = −1%) instead of combining multipliers.",
      difficulty: "challenge",
      guideRef: "reverse-percentages",
      hints: ["Write each of the three changes as a multiplier.", "One combined multiplier takes the menu total to $95.92.", "Divide by the combined multiplier (or undo the steps in reverse order)."],
      strategy: "Work backwards",
    },
    {
      kind: "short",
      id: "fractions-percentages-ch-q07",
      question:
        "An investment earns r% per year compound interest. It exactly doubles in value in 9 years. Work out r. Give your answer to 3 significant figures.",
      answer: { type: "number", value: 8.01, tolerance: 0.005, display: "8.01" },
      traps: [
        { spec: { type: "number", value: 11.1 }, feedback: "100 ÷ 9 = 11.1 is the simple-interest rate. With compounding, the rate needed is smaller." },
        { spec: { type: "number", value: 1.08 }, feedback: "1.08 is the multiplier. Convert it into a percentage rate." },
      ],
      solution: [
        "Let the multiplier be m = {{1 + r/100}}. Then {{m^9 = 2}}.",
        "m = {{2^(1/9)}} = 1.080059…",
        "r = 8.0059… ≈ 8.01.",
      ],
      solutions: [
        { label: "Rule of 72 (estimate first)", steps: ["Bankers' rule: doubling time ≈ 72 ÷ rate, so rate ≈ 72 ÷ 9 = 8%.", "Check: {{1.08^9}} = 1.999 — just under 2, so r is a touch above 8: 8.01."] },
      ],
      difficulty: "challenge",
      guideRef: "compound-growth",
      hints: ["Let the starting amount be P. Write an equation for the amount after 9 years.", "The P cancels: {{m^9 = 2}}.", "Take the ninth root of 2."],
      strategy: "Introduce a variable",
    },
    {
      kind: "short",
      id: "fractions-percentages-ch-q08",
      question:
        "A new car loses 20% of its value in its first year. After that it loses 10% of its value each year. After how many whole years is it **first** worth less than half of its original value?",
      answer: { type: "number", value: 6, display: "6 years" },
      traps: [
        { spec: { type: "number", value: 4 }, feedback: "20% + 10% + 10% + 10% = 50% adds percentages of different amounts. Use multipliers." },
        { spec: { type: "number", value: 5 }, feedback: "After 5 years the value is 0.8 × {{0.9^4}} ≈ 0.525 of the original — still more than half." },
      ],
      solution: [
        "After n years (n ≥ 1) the value is {{0.8 * 0.9^(n-1)}} of the original.",
        "n = 5: {{0.8 * 0.9^4}} = 0.52488 > 0.5.",
        "n = 6: {{0.8 * 0.9^5}} = 0.47239 < 0.5.",
        "So 6 years.",
      ],
      commonError: "Adding the percentage losses: 20 + 10 + 10 + 10 = 50 → 4 years.",
      difficulty: "challenge",
      guideRef: "compound-growth",
      hints: ["Use a start value of 1 (or $100).", "What multiplier applies in year 1? In each later year?", "Find the first n with {{0.8 * 0.9^(n-1) < 0.5}}."],
      strategy: "Make it simpler",
    },
    {
      kind: "short",
      id: "fractions-percentages-ch-q09",
      question:
        "Write {{1/(x(x + 1)) + 1/((x + 1)(x + 2)) + 1/((x + 2)(x + 3))}} as a single fraction in its simplest form.",
      answer: { type: "expression", expr: "3/(x(x+3))", display: "{{3/(x(x + 3))}}" },
      solution: [
        "Notice {{1/(k(k + 1)) = 1/k - 1/(k + 1)}} (check: {{((k + 1) - k)/(k(k + 1))}}).",
        "So the sum is {{(1/x - 1/(x + 1)) + (1/(x + 1) - 1/(x + 2)) + (1/(x + 2) - 1/(x + 3))}}.",
        "The middle terms cancel: {{1/x - 1/(x + 3)}}.",
        "{{((x + 3) - x)/(x(x + 3)) = 3/(x(x + 3))}}.",
      ],
      solutions: [
        { label: "Brute force common denominator", steps: ["Common denominator {{x(x + 1)(x + 2)(x + 3)}}.", "Numerator: {{(x + 2)(x + 3) + x(x + 3) + x(x + 1) = 3x^2 + 9x + 6 = 3(x + 1)(x + 2)}}.", "Cancel {{(x + 1)(x + 2)}}: {{3/(x(x + 3))}}. It works — but the telescoping method is much quicker."] },
      ],
      difficulty: "challenge",
      guideRef: "algebraic-fractions",
      hints: [
        "Work out {{1/x - 1/(x + 1)}} as a single fraction. What do you notice?",
        "Split each term into a difference of two simpler fractions.",
        "Most of the terms now cancel in pairs.",
      ],
      strategy: "Find a pattern",
    },
    {
      kind: "short",
      id: "fractions-percentages-ch-q10",
      question:
        "Find the constants A and B such that {{(5x + 1)/((x + 1)(x - 1)) = A/(x + 1) + B/(x - 1)}} for all x ≠ ±1. Give A first, then B.",
      answer: { type: "list", values: [2, 3], ordered: true, display: "A = 2, B = 3" },
      traps: [{ spec: { type: "list", values: [3, 2], ordered: true }, feedback: "Right values, wrong order — A goes with (x + 1)." }],
      solution: [
        "Combine the right-hand side: {{(A(x - 1) + B(x + 1))/((x + 1)(x - 1))}}.",
        "So 5x + 1 = A(x − 1) + B(x + 1) for all x.",
        "x = 1: 6 = 2B, so B = 3.",
        "x = −1: −4 = −2A, so A = 2.",
      ],
      solutions: [
        { label: "Compare coefficients", steps: ["A(x − 1) + B(x + 1) = (A + B)x + (B − A).", "A + B = 5 and B − A = 1.", "Adding: 2B = 6, B = 3; then A = 2."] },
      ],
      difficulty: "challenge",
      guideRef: "algebraic-fractions",
      hints: [
        "Add the two fractions on the right, just as you would normally.",
        "The numerators must then be equal for every x.",
        "Choose clever values of x that make one bracket zero.",
      ],
      strategy: "Work backwards",
    },
  ],
};
