// Ratio, rates & proportion — MCQ papers (3 × 15). Options are shuffled at display time.
import type { Paper } from "../../types.ts";

export const mcqPapers: Paper[] = [
  // ===========================================================================
  // MCQ Paper 1
  // ===========================================================================
  {
    id: "ratio-proportion-m1",
    title: "MCQ Paper 1",
    questions: [
      {
        kind: "mcq",
        id: "ratio-proportion-m1-q01",
        question: "Write the ratio 2.4 kg : 600 g in its simplest form.",
        options: ["4 : 1", "1 : 4", "1 : 250", "2 : 5"],
        answerIndex: 0,
        explanation:
          "Same units first: 2.4 kg = 2400 g, so 2400 : 600 = 4 : 1 (divide both by 600). 1 : 250 comes from ignoring the units and simplifying 2.4 : 600. 2 : 5 comes from converting 2.4 kg to 240 g instead of 2400 g. 1 : 4 has the parts the wrong way round — the order of a ratio matters.",
        difficulty: "warmup",
        guideRef: "ratio-basics",
        hints: ["Can you compare kilograms with grams directly? Convert both to grams first.", "2.4 kg = 2400 g. Now divide both parts by their HCF."],
        strategy: "Make the units match",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m1-q02",
        question: "Siti, Ethan and Mei share $360 in the ratio 2 : 3 : 4. How much is the largest share?",
        options: ["$120", "$160", "$40", "$90"],
        answerIndex: 1,
        explanation:
          "There are 2 + 3 + 4 = 9 parts, so one part is 360 ÷ 9 = $40 and the largest share is 4 × 40 = $160. $120 splits the money equally between the three people. $40 is only one part. $90 is 360 ÷ 4 — dividing by the ratio number instead of the total number of parts.",
        difficulty: "warmup",
        guideRef: "ratio-basics",
        hints: ["How many parts are there altogether?", "Find the value of one part, then multiply by 4."],
        strategy: "Use a bar model",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m1-q03",
        question: "A car travels 135 km in 1 hour 30 minutes. Work out its average speed.",
        options: ["103.8 km/h", "202.5 km/h", "90 km/h", "1.5 km/h"],
        answerIndex: 2,
        explanation:
          "1 hour 30 minutes = 1.5 hours, so speed = {{135/1.5}} = 90 km/h. 103.8 km/h treats 1 h 30 min as 1.3 hours. 202.5 km/h multiplies distance by time. 1.5 km/h is 135 ÷ 90 minutes — that is 1.5 km per **minute**, not per hour.",
        difficulty: "warmup",
        guideRef: "compound-measures",
        hints: ["Speed = distance ÷ time — but write the time in hours as a decimal first. Is 30 minutes 0.3 of an hour?"],
        strategy: "Check the units",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m1-q04",
        question: "y is directly proportional to x. When x = 4, y = 12. Work out the value of y when x = 10.",
        options: ["18", "4.8", "3", "30"],
        answerIndex: 3,
        explanation:
          "y = kx with 12 = 4k, so k = 3 and y = 3 × 10 = 30. 18 adds 6 to y because x went up by 6 — proportion is multiplicative, not additive. 4.8 = {{48/10}} treats the relationship as inverse. 3 is the constant k, not y.",
        difficulty: "warmup",
        guideRef: "direct-proportion",
        hints: ["Write y = kx and use the pair x = 4, y = 12 to find k.", "x is multiplied by 2.5 — so what happens to y?"],
        strategy: "Find the constant first",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m1-q05",
        question: "y is inversely proportional to x. When x = 4, y = 6. Work out the value of y when x = 3.",
        options: ["8", "4.5", "5", "72"],
        answerIndex: 0,
        explanation:
          "{{y = k/x}} with k = xy = 4 × 6 = 24, so {{y = 24/3}} = 8. Smaller x gives bigger y, as it should. 4.5 = {{6 * 3/4}} uses direct proportion. 5 lowers y by 1 because x fell by 1 (additive thinking). 72 multiplies k by x instead of dividing.",
        difficulty: "core",
        guideRef: "inverse-proportion",
        hints: ["For inverse proportion, what stays constant: {{y/x}} or xy?", "k = xy = 24. Now use {{y = k/x}}."],
        strategy: "Find the constant first",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m1-q06",
        question:
          "Four jugs of orange drink are made from concentrate and water. Which jug has the **highest** proportion of concentrate?\n\n- Jug A: concentrate : water = 1 : 6\n- Jug B: 150 ml of concentrate in 1 litre of drink\n- Jug C: concentrate : water = 2 : 13\n- Jug D: 120 ml of concentrate mixed with 730 ml of water",
        options: ["Jug A", "Jug B", "Jug C", "Jug D"],
        answerIndex: 1,
        explanation:
          "Write each as concentrate ÷ **total**: A = {{1/7}} ≈ 14.3%, B = {{150/1000}} = 15%, C = {{2/15}} ≈ 13.3%, D = {{120/850}} ≈ 14.1%. So Jug B is strongest. Jug A looks strongest if you read 1 : 6 as {{1/6}} ≈ 16.7% — but a part : part ratio of 1 : 6 means 1 part in 7. Jug D looks like {{120/730}} ≈ 16.4% for the same reason.",
        difficulty: "core",
        guideRef: "ratio-problems",
        hints: ["Turn each jug into the same kind of number — a fraction or percentage of the whole drink.", "1 : 6 concentrate : water means 1 part out of how many parts in total?", "Compare {{1/7}}, {{150/1000}}, {{2/15}} and {{120/850}} as percentages."],
        strategy: "Make them comparable",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m1-q07",
        question: "A map has scale 1 : 50 000. Two MRT stations are 3.7 cm apart on the map. What is the real distance between them?",
        options: ["18.5 km", "0.185 km", "1.85 km", "185 km"],
        answerIndex: 2,
        explanation:
          "Real distance = 3.7 × 50 000 = 185 000 cm. Divide by 100 for metres (1850 m) and by 1000 for km: 1.85 km. 18.5 km and 0.185 km come from slipping a power of ten in the conversion (there are 100 000 cm in a km). 185 km divides 185 000 by 1000 only, treating centimetres as metres.",
        difficulty: "core",
        guideRef: "ratio-problems",
        hints: ["1 cm on the map is 50 000 cm in real life.", "How many centimetres are there in 1 km? (100 cm in a metre, 1000 m in a km.)"],
        strategy: "Check the units",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m1-q08",
        question: "A brass ornament has a volume of 240 cm³. Brass has a density of 8.5 g/cm³. What is the mass of the ornament?",
        options: ["0.0282 kg", "2040 kg", "20.4 kg", "2.04 kg"],
        answerIndex: 3,
        explanation:
          "Mass = density × volume = 8.5 × 240 = 2040 g = 2.04 kg. 0.0282 kg comes from 240 ÷ 8.5 (volume ÷ density) — check the units: g/cm³ × cm³ = g. 2040 kg forgets that the answer is in grams. 20.4 kg divides by 100 instead of 1000.",
        difficulty: "core",
        guideRef: "compound-measures",
        hints: ["Density is mass per unit volume. Which calculation makes the units come out in grams?", "Mass = density × volume. Then convert grams to kilograms."],
        strategy: "Use the units",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m1-q09",
        question: "A train travels at 72 km/h. What is this speed in metres per second?",
        options: ["20 m/s", "259.2 m/s", "1.2 m/s", "1200 m/s"],
        answerIndex: 0,
        explanation:
          "72 km/h = 72 000 m per 3600 s = {{72000/3600}} = 20 m/s (i.e. divide by 3.6). 259.2 m/s multiplies by 3.6 — a train at 259 m/s would be faster than a jet. 1.2 m/s divides by 60 only once. 1200 m/s is the number of metres per **minute**.",
        difficulty: "core",
        guideRef: "compound-measures",
        hints: ["Change the kilometres to metres and the hours to seconds separately.", "72 000 m in 3600 seconds — how many metres in 1 second?"],
        strategy: "Convert top and bottom separately",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m1-q10",
        question: "P is directly proportional to the square of r. When r = 5, P = 50. Work out the value of P when r = 8.",
        options: ["80", "128", "64", "256"],
        answerIndex: 1,
        explanation:
          "{{P = kr^2}}: 50 = 25k, so k = 2 and P = 2 × 64 = 128. 80 uses P ∝ r (no square). 64 is {{8^2}} without multiplying by k. 256 is {{(2 * 8)^2}} — the k was squared along with r.",
        difficulty: "core",
        guideRef: "direct-proportion",
        hints: ["Write the relationship as an equation with a constant k.", "{{P = kr^2}}. Substitute r = 5, P = 50 to find k.", "Square r before multiplying by k."],
        strategy: "Find the constant first",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m1-q11",
        question: "8 volunteers take 12 days to pack food hampers at a community centre. Two volunteers drop out. How many days would the remaining 6 volunteers take, working at the same rate?",
        options: ["9", "14", "16", "10"],
        answerIndex: 2,
        explanation:
          "The total job is 8 × 12 = 96 volunteer-days, so 6 volunteers need {{96/6}} = 16 days. 9 uses direct proportion ({{12 * 6/8}}) — fewer people should take *more* time, not less. 14 adds 2 days because 2 people left, and 10 subtracts them; both are additive thinking.",
        difficulty: "core",
        guideRef: "inverse-proportion",
        hints: ["Should fewer volunteers take more time or less?", "Work out the total amount of work in volunteer-days.", "8 × 12 = 96 volunteer-days. Share that between 6 people."],
        strategy: "Find the invariant",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m1-q12",
        question:
          "The table shows some values of x and y.\n\n| x | 2 | 4 | 6 |\n|---|---|---|---|\n| y | 12 | 48 | 108 |\n\nWhich statement describes the relationship?",
        options: ["y ∝ x", "y ∝ x³", "y ∝ {{1/x}}", "y ∝ x²"],
        answerIndex: 3,
        explanation:
          "When x doubles (2 → 4), y multiplies by 4 (12 → 48) — that is {{2^2}}. When x triples (2 → 6), y multiplies by 9 = {{3^2}}. So y ∝ x² (in fact y = 3x²). y ∝ x would make y double, not quadruple; \"y goes up when x goes up\" is not enough. y ∝ x³ would multiply y by 8 when x doubles. y ∝ {{1/x}} would make y go **down**.",
        difficulty: "core",
        guideRef: "direct-proportion",
        hints: ["What happens to y when x is doubled?", "If y ∝ xⁿ, doubling x multiplies y by {{2^n}}. Which n gives × 4?"],
        strategy: "Test the scale factor",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m1-q13",
        question: "a : b = 4 : 5 and b : c = 3 : 2. Also b − c = 35. Work out the value of a.",
        options: ["84", "12", "105", "420"],
        answerIndex: 0,
        explanation:
          "Make b the same in both ratios: 4 : 5 = 12 : 15 and 3 : 2 = 15 : 10, so a : b : c = 12 : 15 : 10. b − c is 5 parts = 35, so 1 part = 7 and a = 12 × 7 = 84. 12 is the number of parts for a, not its value. 105 is b. 420 = 12 × 35 treats the difference of 35 as one part.",
        difficulty: "challenge",
        guideRef: "ratio-basics",
        hints: ["b appears in both ratios but with different numbers of parts. What is the LCM of 5 and 3?", "Rewrite both ratios so b is 15 parts, then write a : b : c.", "b − c is how many parts? Use it to find one part."],
        strategy: "Match the common part",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m1-q14",
        question:
          "Priya and Marcus have money in the ratio 9 : 5. Priya gives Marcus $28. Now they have equal amounts. How much did Priya have at the start?",
        options: ["$63", "$126", "$98", "$70"],
        answerIndex: 1,
        explanation:
          "Let them have 9k and 5k. After the transfer, 9k − 28 = 5k + 28, so 4k = 56 and k = 14. Priya started with 9 × 14 = $126 (check: 98 and 98). $63 assumes the 4-part gap equals $28 — but giving $28 closes the gap by $56. $98 is Priya's amount *after* giving. $70 is Marcus's starting amount.",
        difficulty: "challenge",
        guideRef: "ratio-problems",
        hints: ["Call Priya's amount 9k and Marcus's 5k. What are they after the $28 moves?", "Set the new amounts equal and solve for k.", "Transferring $28 changes the difference between them by how much?"],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m1-q15",
        question: "y is inversely proportional to the square of x. x is decreased by 50%. What is the percentage change in y?",
        options: ["50% increase", "100% increase", "300% increase", "400% increase"],
        answerIndex: 2,
        explanation:
          "{{y = k/x^2}}. x becomes 0.5x, so y is multiplied by {{1/0.5^2}} = {{1/0.25}} = 4. The new y is 400% of the old y — an increase of 300%. 50% assumes y changes by the same percentage as x. 100% uses {{1/0.5}} = 2 and forgets the square. 400% confuses \"multiplied by 4\" with \"increased by 400%\".",
        difficulty: "challenge",
        guideRef: "inverse-proportion",
        hints: ["Pick numbers: let x = 1 so y = k. What is y when x = 0.5?", "y is multiplied by {{1/0.5^2}}. Work that out.", "If y is multiplied by 4, by what percentage has it increased?"],
        strategy: "Use a multiplier",
      },
    ],
  },

  // ===========================================================================
  // MCQ Paper 2
  // ===========================================================================
  {
    id: "ratio-proportion-m2",
    title: "MCQ Paper 2",
    questions: [
      {
        kind: "mcq",
        id: "ratio-proportion-m2-q01",
        question: "Write the ratio 8 : 5 in the form 1 : n.",
        options: ["1 : 1.6", "1 : 3", "1 : 40", "1 : 0.625"],
        answerIndex: 3,
        explanation:
          "Divide **both** parts by 8: 8 : 5 = 1 : {{5/8}} = 1 : 0.625. 1 : 1.6 divides 8 by 5 — that would be the form n : 1 written backwards. 1 : 3 subtracts instead of dividing. 1 : 40 multiplies the parts.",
        difficulty: "warmup",
        guideRef: "ratio-basics",
        hints: ["To make the first part 1, what must you divide both parts by?"],
        strategy: "Scale both parts",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m2-q02",
        question: "Hana and Jun share some sweets in the ratio 4 : 7. Jun gets 42 sweets. How many sweets are there altogether?",
        options: ["24", "18", "66", "462"],
        answerIndex: 2,
        explanation:
          "Jun's 7 parts = 42, so 1 part = 6. There are 11 parts in total: 11 × 6 = 66. 24 is Hana's share only. 18 is the difference between their shares. 462 is 42 × 11 — treating 42 as one part instead of seven.",
        difficulty: "warmup",
        guideRef: "ratio-basics",
        hints: ["42 sweets is how many parts?", "Find one part, then multiply by the total number of parts (4 + 7)."],
        strategy: "Use a bar model",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m2-q03",
        question: "A force of 600 N acts on an area of 0.25 m². Work out the pressure.",
        options: ["150 N/m²", "2400 N/m²", "0.000417 N/m²", "24 N/m²"],
        answerIndex: 1,
        explanation:
          "Pressure = force ÷ area = {{600/0.25}} = 2400 N/m². Dividing by a number less than 1 makes it bigger — a small area gives a big pressure. 150 multiplies force by area. 0.000417 is area ÷ force. 24 divides by 25 instead of 0.25.",
        difficulty: "warmup",
        guideRef: "compound-measures",
        hints: ["The units N/m² tell you the calculation: newtons divided by square metres."],
        strategy: "Use the units",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m2-q04",
        question: "Which pair of quantities is **inversely** proportional?",
        options: [
          "The time taken to drive 100 km and the average speed",
          "The cost of petrol and the number of litres bought",
          "The area of a circle and its radius",
          "A teenager's height and their age",
        ],
        answerIndex: 0,
        explanation:
          "For a fixed 100 km, speed × time = 100, so doubling the speed halves the time — that is inverse proportion. Petrol cost is **directly** proportional to litres. Area ∝ r² is direct proportion to the square, and both go up together. Height and age are related but not proportional at all (a 30-year-old is not twice as tall as a 15-year-old).",
        difficulty: "warmup",
        guideRef: "inverse-proportion",
        hints: ["Inverse proportion: when one doubles, the other halves. Which product stays constant?"],
        strategy: "Test with doubling",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m2-q05",
        question: "a : b = 3 : 4 and b : c = 6 : 5. Find the ratio a : c in its simplest form.",
        options: ["3 : 5", "5 : 8", "10 : 9", "9 : 10"],
        answerIndex: 3,
        explanation:
          "Match b using LCM(4, 6) = 12: a : b = 9 : 12 and b : c = 12 : 10, so a : b : c = 9 : 12 : 10 and a : c = 9 : 10. 3 : 5 just takes the outside numbers without matching b. 5 : 8 divides the ratios ({{3/4}} ÷ {{6/5}}) instead of multiplying. 10 : 9 is the right numbers in the wrong order.",
        difficulty: "core",
        guideRef: "ratio-basics",
        hints: ["The 4 parts of b and the 6 parts of b are different-sized parts. How can you make them match?", "Scale both ratios so b is 12 parts.", "a : b : c = 9 : 12 : 10."],
        strategy: "Match the common part",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m2-q06",
        question: "A supermarket sells rice in four sizes. Which bag is the **best value** for money?",
        options: ["2 kg for $5.40", "3 kg for $8.25", "5 kg for $12.75", "10 kg for $26.00"],
        answerIndex: 2,
        explanation:
          "Price per kg: $2.70, $2.75, $2.55 and $2.60. The 5 kg bag is cheapest per kilogram. The 10 kg bag is tempting because bigger is often cheaper, but here it costs $2.60/kg. The 2 kg bag has the lowest *price*, not the lowest *unit price*.",
        difficulty: "core",
        guideRef: "ratio-problems",
        hints: ["Compare like with like — work out the cost of 1 kg for each bag.", "Divide each price by the number of kilograms."],
        strategy: "Find the unit rate",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m2-q07",
        question:
          "The exchange rate is S$1 = RM 3.40 (Malaysian ringgit). Mei changes S$250 into ringgit. On a trip she spends RM 595, then changes the rest back into Singapore dollars at the same rate. How many Singapore dollars does she get back?",
        options: ["S$75", "S$255", "S$867", "S$175"],
        answerIndex: 0,
        explanation:
          "S$250 × 3.40 = RM 850. She has RM 850 − 595 = RM 255 left, and RM 255 ÷ 3.40 = S$75. S$867 multiplies the ringgit by 3.40 again instead of dividing. S$255 forgets to convert back. S$175 is what she *spent*, in Singapore dollars.",
        difficulty: "core",
        guideRef: "ratio-problems",
        hints: ["Work in ringgit while she is in Malaysia.", "How many ringgit does she have left?", "To go from ringgit back to S$, multiply or divide by 3.40? Which gives a smaller number?"],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m2-q08",
        question:
          "Ravi cycles 12 km at an average speed of 16 km/h, then 20 km at an average speed of 40 km/h. What is his average speed for the whole journey?",
        options: ["28 km/h", "31 km/h", "64 km/h", "25.6 km/h"],
        answerIndex: 3,
        explanation:
          "Times: {{12/16}} = 0.75 h and {{20/40}} = 0.5 h. Average speed = total distance ÷ total time = {{32/1.25}} = 25.6 km/h. 28 km/h is the mean of the two speeds — but he spends longer at the slower speed. 31 km/h weights the speeds by distance instead of time. 64 km/h divides the total distance by the second time only.",
        difficulty: "core",
        guideRef: "compound-measures",
        hints: ["Can you average the two speeds? Which part of the journey takes longer?", "Find the time for each part.", "Average speed = total distance ÷ total time."],
        strategy: "Go back to the definition",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m2-q09",
        question: "Aluminium has a density of 2.7 g/cm³. What is this density in kg/m³?",
        options: ["2700 kg/m³", "0.0027 kg/m³", "27 kg/m³", "2 700 000 kg/m³"],
        answerIndex: 0,
        explanation:
          "1 m³ = 1 000 000 cm³, so 1 m³ has mass 2.7 × 1 000 000 = 2 700 000 g = 2700 kg. 2 700 000 forgets to turn grams into kilograms. 0.0027 divides by 1000 but ignores the volume change. 27 uses 1 m³ = 100 cm³ × 100 — the volume factor is 100³, not 100².",
        difficulty: "core",
        guideRef: "compound-measures",
        hints: ["Work out the mass of 1 m³ of aluminium.", "1 m = 100 cm, so 1 m³ = {{100^3}} cm³.", "Then convert grams to kilograms."],
        strategy: "Convert top and bottom separately",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m2-q10",
        question: "The graph shows that y is directly proportional to x. Work out the value of y when x = 14.",
        diagram: `<svg viewBox="0 0 320 240" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Straight-line graph through the origin and the point (4, 10), x from 0 to 8, y from 0 to 20"><rect x="0" y="0" width="320" height="240" fill="#ffffff"/><g stroke="#e2e8f0" stroke-width="1"><line x1="100" y1="40" x2="100" y2="200"/><line x1="160" y1="40" x2="160" y2="200"/><line x1="220" y1="40" x2="220" y2="200"/><line x1="280" y1="40" x2="280" y2="200"/><line x1="40" y1="160" x2="280" y2="160"/><line x1="40" y1="120" x2="280" y2="120"/><line x1="40" y1="80" x2="280" y2="80"/><line x1="40" y1="40" x2="280" y2="40"/></g><line x1="40" y1="200" x2="295" y2="200" stroke="#1f2937" stroke-width="1.5"/><line x1="40" y1="200" x2="40" y2="25" stroke="#1f2937" stroke-width="1.5"/><text x="302" y="204" font-size="13" font-family="sans-serif" fill="#1f2937">x</text><text x="36" y="20" font-size="13" font-family="sans-serif" fill="#1f2937">y</text><g font-size="11" font-family="sans-serif" fill="#334155" text-anchor="middle"><text x="40" y="216">0</text><text x="100" y="216">2</text><text x="160" y="216">4</text><text x="220" y="216">6</text><text x="280" y="216">8</text></g><g font-size="11" font-family="sans-serif" fill="#334155" text-anchor="end"><text x="34" y="164">5</text><text x="34" y="124">10</text><text x="34" y="84">15</text><text x="34" y="44">20</text></g><line x1="40" y1="200" x2="280" y2="40" stroke="#4f46e5" stroke-width="2"/><line x1="160" y1="200" x2="160" y2="120" stroke="#334155" stroke-dasharray="4 3"/><line x1="40" y1="120" x2="160" y2="120" stroke="#334155" stroke-dasharray="4 3"/><circle cx="160" cy="120" r="4" fill="#1f2937"/><text x="168" y="116" font-size="12" font-family="sans-serif" fill="#1f2937">(4, 10)</text></svg>`,
        options: ["20", "35", "5.6", "2.5"],
        answerIndex: 1,
        explanation:
          "From the point (4, 10): k = {{10/4}} = 2.5, so y = 2.5 × 14 = 35. 20 adds 10 to y because x went up by 10 — direct proportion multiplies, it doesn't add. 5.6 = {{4 * 14/10}} uses the pair upside down. 2.5 is the gradient k, not y.",
        difficulty: "core",
        guideRef: "direct-proportion",
        hints: ["Read an exact point off the line.", "The line passes through (4, 10). What is {{y/x}}?", "y = 2.5x. Substitute x = 14."],
        strategy: "Read the graph",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m2-q11",
        question: "d is directly proportional to the square root of h. When h = 9, d = 18. Work out the value of h when d = 30.",
        options: ["15", "25", "5", "150"],
        answerIndex: 1,
        explanation:
          "{{d = k sqrt(h)}}: 18 = 3k, so k = 6. Then 30 = {{6 sqrt(h)}}, so {{sqrt(h)}} = 5 and h = 25. 15 treats d as directly proportional to h. 5 is {{sqrt(h)}} — the last step (squaring) was missed. 150 = {{30^2/6}} squares d but not k.",
        difficulty: "core",
        guideRef: "direct-proportion",
        hints: ["Write {{d = k sqrt(h)}} and find k.", "Substitute d = 30 to find {{sqrt(h)}}.", "You want h, not {{sqrt(h)}}."],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m2-q12",
        question: "The light intensity I from a lamp is inversely proportional to the square of the distance d from the lamp. I = 36 when d = 2. Work out I when d = 6.",
        options: ["12", "108", "4", "324"],
        answerIndex: 2,
        explanation:
          "{{I = k/d^2}}: 36 = {{k/4}}, so k = 144 and I = {{144/36}} = 4. Tripling d divides I by {{3^2}} = 9. 12 forgets the square ({{I = k/d}}). 108 and 324 use direct proportion — moving further from a lamp makes it dimmer, not brighter.",
        difficulty: "core",
        guideRef: "inverse-proportion",
        hints: ["Write the equation with k. Where does {{d^2}} go?", "{{k = I d^2}} = 36 × 4.", "d is multiplied by 3. What happens to {{d^2}}, and so to I?"],
        strategy: "Find the constant first",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m2-q13",
        question: "y is directly proportional to the cube of x. x is decreased by 20%. What is the percentage decrease in y?",
        options: ["48.8%", "51.2%", "60%", "20%"],
        answerIndex: 0,
        explanation:
          "{{y = kx^3}}. The new x is 0.8x, so y is multiplied by {{0.8^3}} = 0.512 — y is 51.2% of what it was, a decrease of 48.8%. 51.2% is the new *value* as a percentage, not the decrease. 60% multiplies the 20% by 3. 20% ignores the cube.",
        difficulty: "challenge",
        guideRef: "direct-proportion",
        hints: ["A 20% decrease is the same as multiplying by what?", "If x is multiplied by 0.8, y is multiplied by {{0.8^3}}.", "Is 0.512 the new amount or the decrease?"],
        strategy: "Use a multiplier",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m2-q14",
        question:
          "Solution A is 20% salt by mass. Solution B is 50% salt by mass. In what ratio A : B must they be mixed to make a solution that is 30% salt?",
        options: ["1 : 2", "2 : 1", "2 : 5", "3 : 5"],
        answerIndex: 1,
        explanation:
          "Mix a kg of A and b kg of B: 0.2a + 0.5b = 0.3(a + b), so 0.2b = 0.1a and a : b = 2 : 1. Check: 2 kg of A + 1 kg of B has 0.4 + 0.5 = 0.9 kg salt in 3 kg = 30%. 1 : 2 is the right numbers reversed — that gives 40%. 2 : 5 and 3 : 5 just compare the percentages instead of balancing them.",
        difficulty: "challenge",
        guideRef: "ratio-problems",
        hints: ["30% is closer to 20% than to 50%. So which solution do you need more of?", "Use a kg of A and b kg of B. Write the mass of salt two ways.", "0.2a + 0.5b = 0.3(a + b). Simplify."],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m2-q15",
        question:
          "Kenji drives from Singapore to a town at an average speed of 60 km/h and drives back along the same road at 40 km/h. What is his average speed for the whole round trip?",
        options: ["50 km/h", "24 km/h", "48 km/h", "100 km/h"],
        answerIndex: 2,
        explanation:
          "Let each leg be 120 km (any distance works). Times: 2 h and 3 h. Average speed = {{240/5}} = 48 km/h. 50 km/h is the mean of the speeds — but he spends longer at 40 km/h, so the answer is below 50. 24 km/h is 1 ÷ ({{1/60 + 1/40}}), using one leg's distance for the whole trip. 100 km/h adds the speeds.",
        difficulty: "challenge",
        guideRef: "compound-measures",
        hints: ["The distance isn't given. Does it matter? Try choosing a convenient one.", "Pick a distance that 60 and 40 both divide into, e.g. 120 km.", "Average speed = total distance ÷ total time."],
        strategy: "Make it simpler",
      },
    ],
  },

  // ===========================================================================
  // MCQ Paper 3 — Exam style
  // ===========================================================================
  {
    id: "ratio-proportion-m3",
    title: "MCQ Paper 3 — Exam style",
    questions: [
      {
        kind: "mcq",
        id: "ratio-proportion-m3-q01",
        question: "In a school CCA the ratio of boys to girls is 3 : 5. What fraction of the members are girls?",
        options: ["{{5/3}}", "{{5/8}}", "{{3/5}}", "{{3/8}}"],
        answerIndex: 1,
        explanation:
          "There are 3 + 5 = 8 parts and girls are 5 of them, so {{5/8}}. {{3/5}} and {{5/3}} compare one group with the other (part : part), not with the whole. {{3/8}} is the fraction who are boys.",
        difficulty: "warmup",
        guideRef: "ratio-basics",
        hints: ["A fraction compares a part with the whole. How many parts make the whole?"],
        strategy: "Part : part vs part : whole",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m3-q02",
        question: "A pancake recipe for 4 people uses 300 g of flour. How much flour is needed for 10 people?",
        options: ["306 g", "120 g", "3000 g", "750 g"],
        answerIndex: 3,
        explanation:
          "For 1 person: 300 ÷ 4 = 75 g, so for 10 people: 75 × 10 = 750 g (or × 2.5). 306 g adds 6 g because there are 6 more people — scaling is multiplying. 120 g = {{300 * 4/10}}, scaling the wrong way. 3000 g multiplies the whole recipe by 10.",
        difficulty: "warmup",
        guideRef: "ratio-problems",
        hints: ["How much flour is needed for one person?", "Then multiply by 10 — or notice 10 people is 2.5 × 4 people."],
        strategy: "Find the unit rate",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m3-q03",
        question: "A block of wood has mass 600 g. The density of the wood is 0.8 g/cm³. Work out the volume of the block.",
        options: ["750 cm³", "480 cm³", "0.0013 cm³", "75 cm³"],
        answerIndex: 0,
        explanation:
          "Volume = mass ÷ density = {{600/0.8}} = 750 cm³. Check: 750 × 0.8 = 600 g. 480 multiplies mass by density. 0.0013 is density ÷ mass. 75 is a place-value slip in dividing by 0.8.",
        difficulty: "warmup",
        guideRef: "compound-measures",
        hints: ["Density = mass ÷ volume. Rearrange for volume — or ask which calculation leaves cm³ as the unit."],
        strategy: "Use the units",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m3-q04",
        question: "The cost of concert tickets is directly proportional to the number of tickets bought. 5 tickets cost $42.50. How much do 8 tickets cost?",
        options: ["$45.50", "$26.56", "$68.00", "$340.00"],
        answerIndex: 2,
        explanation:
          "One ticket costs 42.50 ÷ 5 = $8.50, so 8 tickets cost 8 × 8.50 = $68.00. $45.50 adds $3 for 3 more tickets. $26.56 = {{42.50 * 5/8}} scales the wrong way (more tickets must cost more). $340 multiplies the cost of 5 tickets by 8.",
        difficulty: "warmup",
        guideRef: "direct-proportion",
        hints: ["What does one ticket cost?"],
        strategy: "Find the unit rate",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m3-q05",
        question: "Aisha and Zara share some money in the ratio 7 : 4. Aisha gets $45 more than Zara. How much money do they share altogether?",
        options: ["$105", "$165", "$495", "$60"],
        answerIndex: 1,
        explanation:
          "The difference is 7 − 4 = 3 parts = $45, so 1 part = $15. Total = 11 parts = $165. $105 is Aisha's share and $60 is Zara's. $495 = 45 × 11 treats the $45 difference as one part.",
        difficulty: "core",
        guideRef: "ratio-basics",
        hints: ["Draw a bar model — how many parts is the $45 difference?", "3 parts = $45. Find 1 part, then the 11-part total."],
        strategy: "Use a bar model",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m3-q06",
        question:
          "A plan of an HDB flat is drawn to a scale of 1 : 50. The bedroom has an area of 48 cm² on the plan. What is the real area of the bedroom?",
        options: ["0.24 m²", "2400 m²", "1200 m²", "12 m²"],
        answerIndex: 3,
        explanation:
          "Lengths scale by 50, so areas scale by {{50^2}} = 2500: 48 × 2500 = 120 000 cm². Since 1 m² = 10 000 cm², that is 12 m². 0.24 m² scales the area by 50 instead of 2500. 2400 m² does the same and forgets to convert. 1200 m² uses 1 m² = 100 cm² — but 1 m² = 100 × 100 cm².",
        difficulty: "core",
        guideRef: "ratio-problems",
        hints: ["If every length is 50 times bigger, how many times bigger is an area?", "Area scale factor = {{50^2}}.", "Convert cm² to m²: divide by {{100^2}}, not 100."],
        strategy: "Lengths, then areas",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m3-q07",
        question: "A box with weight 360 N rests on a face measuring 30 cm by 40 cm. Work out the pressure on the floor in N/m².",
        options: ["0.3 N/m²", "3000 N/m²", "30 N/m²", "43.2 N/m²"],
        answerIndex: 1,
        explanation:
          "Area = 0.3 m × 0.4 m = 0.12 m², so pressure = {{360/0.12}} = 3000 N/m². 0.3 is 360 ÷ 1200 — that is N/cm², not N/m². 30 uses 1200 cm² = 12 m². 43.2 multiplies force by area.",
        difficulty: "core",
        guideRef: "compound-measures",
        hints: ["The answer must be in N/m², so convert the lengths to metres before finding the area.", "Area = 0.3 × 0.4 m². Then pressure = force ÷ area."],
        strategy: "Check the units",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m3-q08",
        question: "Olivia walks 7.2 km at an average speed of 4.8 km/h. How long does the walk take?",
        options: ["1 hour 50 minutes", "40 minutes", "1 hour 30 minutes", "34 hours 34 minutes"],
        answerIndex: 2,
        explanation:
          "Time = distance ÷ speed = {{7.2/4.8}} = 1.5 hours = 1 hour 30 minutes. 1 hour 50 minutes misreads 1.5 hours as 1 h 50 min — 0.5 h is 30 minutes. 40 minutes is {{4.8/7.2}} h (speed ÷ distance). 34 h 34 min multiplies distance by speed.",
        difficulty: "core",
        guideRef: "compound-measures",
        hints: ["Which calculation leaves hours as the unit: km ÷ km/h or km × km/h?", "Convert the decimal part of the hours to minutes by × 60."],
        strategy: "Use the units",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m3-q09",
        question:
          "The time, T seconds, for one swing of a pendulum is directly proportional to the square root of its length, L cm. When L = 36, T = 1.2. Work out T when L = 100.",
        options: ["3.33", "0.72", "10", "2"],
        answerIndex: 3,
        explanation:
          "{{T = k sqrt(L)}}: 1.2 = 6k, so k = 0.2 and T = 0.2 × {{sqrt(100)}} = 0.2 × 10 = 2. 3.33 uses T ∝ L (no square root). 0.72 = {{1.2 * 6/10}} uses inverse proportion. 10 is {{sqrt(100)}} without multiplying by k.",
        difficulty: "core",
        guideRef: "direct-proportion",
        hints: ["Write the formula with a constant: {{T = k sqrt(L)}}.", "Use L = 36, T = 1.2 to find k.", "Now substitute L = 100."],
        strategy: "Find the constant first",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m3-q10",
        question: "y is inversely proportional to x². When x = 4, y = 5. Find a formula for y in terms of x.",
        options: ["{{y = 80/x^2}}", "{{y = 20/x}}", "{{y = 5/16 x^2}}", "{{y = 5/(16x^2)}}"],
        answerIndex: 0,
        explanation:
          "{{y = k/x^2}}, so {{k = y x^2}} = 5 × 16 = 80, giving {{y = 80/x^2}}. {{y = 20/x}} forgets the square. {{y = 5/16 x^2}} is direct proportion to x². {{y = 5/(16x^2)}} found k by dividing ({{5/16}}) when it should multiply.",
        difficulty: "core",
        guideRef: "inverse-proportion",
        hints: ["Start from {{y = k/x^2}}.", "Substitute x = 4, y = 5 and solve for k: multiply both sides by 16."],
        strategy: "Find the constant first",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m3-q11",
        question:
          "The time taken to fill a pool is inversely proportional to the number of hoses used. With 4 hoses the pool fills in 9 hours. After 3 hours, 2 more hoses are switched on. How long does it take to fill the pool altogether?",
        options: ["6 hours", "4 hours", "9 hours", "7 hours"],
        answerIndex: 3,
        explanation:
          "The job is 4 × 9 = 36 hose-hours. After 3 hours, 4 × 3 = 12 hose-hours are done, leaving 24. Six hoses do that in {{24/6}} = 4 hours, so the total is 3 + 4 = 7 hours. 6 hours is the time for the whole job with 6 hoses. 4 hours is only the second stage. 9 hours adds 3 hours to the full 6-hose time — forgetting that a third of the pool was already filled.",
        difficulty: "core",
        guideRef: "inverse-proportion",
        hints: ["Measure the whole job in hose-hours.", "How many hose-hours are done in the first 3 hours?", "Share the remaining hose-hours between 6 hoses, then add the first 3 hours."],
        strategy: "Find the invariant",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m3-q12",
        question:
          "In a box, the ratio of red pens to blue pens is 3 : 5. Six more red pens are put in the box. The ratio of red pens to blue pens is now 3 : 4. How many blue pens are in the box?",
        options: ["24", "8", "40", "32"],
        answerIndex: 2,
        explanation:
          "Let red = 3k and blue = 5k. Then (3k + 6) : 5k = 3 : 4, so 4(3k + 6) = 15k, giving 12k + 24 = 15k and k = 8. Blue = 5 × 8 = 40 (check: 30 : 40 = 3 : 4). 24 is the original number of red pens. 8 is k. 32 uses the new ratio's 4 parts with k = 8 — but the 4 in 3 : 4 is not 4k.",
        difficulty: "core",
        guideRef: "ratio-problems",
        hints: ["Blue pens don't change. Call the numbers 3k and 5k.", "Write (3k + 6) : 5k = 3 : 4 as an equation by cross-multiplying.", "4(3k + 6) = 3 × 5k."],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m3-q13",
        question: "x : y = 3 : 4. Find the ratio (2x + y) : (x + 3y) in its simplest form.",
        options: ["3 : 4", "2 : 3", "11 : 13", "2 : 5"],
        answerIndex: 1,
        explanation:
          "Let x = 3k, y = 4k. Then 2x + y = 10k and x + 3y = 15k, so the ratio is 10 : 15 = 2 : 3. 3 : 4 assumes combining x and y leaves the ratio unchanged. 11 : 13 swaps the values (x = 4, y = 3). 2 : 5 drops the y from the first bracket (6 : 15).",
        difficulty: "challenge",
        guideRef: "ratio-basics",
        hints: ["A ratio fixes x and y only up to a multiple. Write x = 3k and y = 4k.", "Substitute into both brackets — the k should cancel.", "10k : 15k."],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m3-q14",
        question:
          "The mass of a solid metal sphere is directly proportional to the cube of its radius. A sphere of radius 3 cm has mass 108 g. What is the radius of a sphere of the same metal with mass 500 g?",
        options: ["13.9 cm", "11.2 cm", "41.7 cm", "5 cm"],
        answerIndex: 3,
        explanation:
          "{{m = kr^3}}: 108 = 27k, so k = 4. Then 500 = {{4r^3}}, {{r^3}} = 125 and r = {{cbrt(125)}} = 5 cm. 13.9 cm assumes m ∝ r. 11.2 cm takes the square root of 125 instead of the cube root. 41.7 cm divides 125 by 3 instead of cube-rooting.",
        difficulty: "challenge",
        guideRef: "direct-proportion",
        hints: ["Write {{m = kr^3}} and find k from the first sphere.", "Substitute m = 500 to find {{r^3}}.", "Undo a cube with a cube root."],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "ratio-proportion-m3-q15",
        question: "y is inversely proportional to the square root of x. When x = 16, y = 3. Work out the value of x when y = 2.",
        options: ["36", "24", "6", "7.11"],
        answerIndex: 0,
        explanation:
          "{{y = k/sqrt(x)}}: 3 = {{k/4}}, so k = 12. Then 2 = {{12/sqrt(x)}}, so {{sqrt(x)}} = 6 and x = 36. 24 uses {{y = k/x}} (no root). 6 stops at {{sqrt(x)}}. 7.11 uses {{y = k sqrt(x)}} — direct, not inverse; a smaller y should need a *bigger* x.",
        difficulty: "challenge",
        guideRef: "inverse-proportion",
        hints: ["Write {{y = k/sqrt(x)}} and find k.", "Rearrange 2 = {{12/sqrt(x)}} to find {{sqrt(x)}}.", "Square to get x. Sanity check: y went down, so x should go up."],
        strategy: "Check by substituting",
      },
    ],
  },
];
