import type { TopicPractice } from "../../types.ts";

// Plotted exactly: origin (50, 250), 25 px per unit on both axes; line y = (2/3)·x² through (9, 6) and (12, 8).
const ySquaredGraph = `<svg viewBox="0 0 400 300" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Graph of y against x squared: a straight line through the origin passing through the point (9, 6)"><rect x="0" y="0" width="400" height="300" fill="#ffffff"/><line x1="75" y1="250" x2="75" y2="50" stroke="#e2e8f0" stroke-width="1"/><line x1="100" y1="250" x2="100" y2="50" stroke="#e2e8f0" stroke-width="1"/><line x1="125" y1="250" x2="125" y2="50" stroke="#e2e8f0" stroke-width="1"/><line x1="150" y1="250" x2="150" y2="50" stroke="#e2e8f0" stroke-width="1"/><line x1="175" y1="250" x2="175" y2="50" stroke="#e2e8f0" stroke-width="1"/><line x1="200" y1="250" x2="200" y2="50" stroke="#e2e8f0" stroke-width="1"/><line x1="225" y1="250" x2="225" y2="50" stroke="#e2e8f0" stroke-width="1"/><line x1="250" y1="250" x2="250" y2="50" stroke="#e2e8f0" stroke-width="1"/><line x1="275" y1="250" x2="275" y2="50" stroke="#e2e8f0" stroke-width="1"/><line x1="300" y1="250" x2="300" y2="50" stroke="#e2e8f0" stroke-width="1"/><line x1="325" y1="250" x2="325" y2="50" stroke="#e2e8f0" stroke-width="1"/><line x1="350" y1="250" x2="350" y2="50" stroke="#e2e8f0" stroke-width="1"/><line x1="50" y1="225" x2="350" y2="225" stroke="#e2e8f0" stroke-width="1"/><line x1="50" y1="200" x2="350" y2="200" stroke="#e2e8f0" stroke-width="1"/><line x1="50" y1="175" x2="350" y2="175" stroke="#e2e8f0" stroke-width="1"/><line x1="50" y1="150" x2="350" y2="150" stroke="#e2e8f0" stroke-width="1"/><line x1="50" y1="125" x2="350" y2="125" stroke="#e2e8f0" stroke-width="1"/><line x1="50" y1="100" x2="350" y2="100" stroke="#e2e8f0" stroke-width="1"/><line x1="50" y1="75" x2="350" y2="75" stroke="#e2e8f0" stroke-width="1"/><line x1="50" y1="50" x2="350" y2="50" stroke="#e2e8f0" stroke-width="1"/><line x1="50" y1="250" x2="360" y2="250" stroke="#334155" stroke-width="1.5"/><line x1="50" y1="250" x2="50" y2="40" stroke="#334155" stroke-width="1.5"/><text x="50" y="266" font-size="11" font-family="sans-serif" fill="#334155" text-anchor="middle">0</text><text x="125" y="266" font-size="11" font-family="sans-serif" fill="#334155" text-anchor="middle">3</text><text x="200" y="266" font-size="11" font-family="sans-serif" fill="#334155" text-anchor="middle">6</text><text x="275" y="266" font-size="11" font-family="sans-serif" fill="#334155" text-anchor="middle">9</text><text x="350" y="266" font-size="11" font-family="sans-serif" fill="#334155" text-anchor="middle">12</text><text x="44" y="204" font-size="11" font-family="sans-serif" fill="#334155" text-anchor="end">2</text><text x="44" y="154" font-size="11" font-family="sans-serif" fill="#334155" text-anchor="end">4</text><text x="44" y="104" font-size="11" font-family="sans-serif" fill="#334155" text-anchor="end">6</text><text x="44" y="54" font-size="11" font-family="sans-serif" fill="#334155" text-anchor="end">8</text><text x="364" y="254" font-size="13" font-family="sans-serif" fill="#1f2937">x²</text><text x="46" y="36" font-size="13" font-family="sans-serif" fill="#1f2937">y</text><line x1="50" y1="250" x2="350" y2="50" stroke="#1f2937" stroke-width="2.5"/><circle cx="275" cy="100" r="4.5" fill="#fde68a" stroke="#1f2937" stroke-width="1.5"/><text x="283" y="116" font-size="12" font-family="sans-serif" fill="#1f2937">(9, 6)</text></svg>`;

export const practice: TopicPractice = {
  // ------------------------------------------------------------------ quiz
  quiz: [
    {
      kind: "short",
      id: "ratio-proportion-quiz-q01",
      question: "Write the ratio 1.2 kg : 450 g in its simplest form.",
      answer: { type: "ratio", parts: [8, 3], simplest: true, display: "8 : 3" },
      traps: [
        { spec: { type: "ratio", parts: [2, 75] }, feedback: "You simplified 12 : 450 — but 1.2 kg is 1200 g, not 12 g. Put both quantities in the same unit first." },
      ],
      solution: ["Same units first: 1.2 kg = 1200 g.", "1200 : 450.", "Divide both by 150 (the HCF): 8 : 3."],
      commonError: "Simplifying 1.2 : 450 without converting kg to g.",
      difficulty: "warmup",
      guideRef: "ratio-basics",
      hints: ["A ratio only compares like with like. Are the units the same?", "1.2 kg = 1200 g. Now find the HCF of 1200 and 450."],
      strategy: "Change the form",
    },
    {
      kind: "short",
      id: "ratio-proportion-quiz-q02",
      question: "Arjun, Mei and Ravi share $540 in the ratio 2 : 3 : 4. How much does Ravi get? Give your answer in dollars.",
      answer: { type: "number", value: 240, display: "$240" },
      traps: [{ spec: { type: "number", value: 135 }, feedback: "You divided $540 by 4. Divide by the *total* number of parts, 2 + 3 + 4 = 9, then take 4 of them." }],
      solution: ["Total parts: 2 + 3 + 4 = 9.", "One part: 540 ÷ 9 = $60.", "Ravi gets 4 parts: 4 × 60 = $240."],
      commonError: "Dividing the total by Ravi's number of parts instead of by the total number of parts.",
      difficulty: "warmup",
      guideRef: "ratio-basics",
      hints: ["How many equal parts is the $540 split into?", "Find the value of one part, then take Ravi's 4 parts."],
      strategy: "Find one part first",
    },
    {
      kind: "mcq",
      id: "ratio-proportion-quiz-q03",
      question: "Write the ratio {{2/3}} : {{5/6}} in its simplest form, using whole numbers.",
      options: ["2 : 5", "1 : 2", "4 : 5", "5 : 4"],
      answerIndex: 2,
      explanation:
        "Multiply both parts by 6, the LCM of the denominators: {{2/3}} × 6 = 4 and {{5/6}} × 6 = 5, so the ratio is 4 : 5. 2 : 5 compares only the numerators — but thirds and sixths are different-sized pieces. 1 : 2 compares the denominators (3 : 6). 5 : 4 has the order reversed.",
      difficulty: "core",
      guideRef: "ratio-basics",
      hints: ["Multiplying both parts by the same number doesn't change a ratio. Which number clears both fractions?", "Multiply both parts by 6, the LCM of 3 and 6."],
      strategy: "Find a common multiple",
    },
    {
      kind: "short",
      id: "ratio-proportion-quiz-q04",
      question: "The exchange rate is S$1 = €0.74. Hana changes S$650 into euros. How many euros does she get?",
      answer: { type: "number", value: 481, display: "€481" },
      traps: [{ spec: { type: "number", value: 878.38, tolerance: 0.01 }, feedback: "You divided by 0.74. Each Singapore dollar is worth *less* than one euro, so she should get fewer euros than dollars — multiply." }],
      solution: ["Each S$1 buys €0.74.", "650 × 0.74 = 481.", "Hana gets €481."],
      commonError: "Dividing by the rate instead of multiplying.",
      difficulty: "warmup",
      guideRef: "ratio-problems",
      hints: ["How many euros does one Singapore dollar buy?", "Should the number of euros be bigger or smaller than 650?"],
      strategy: "Estimate first",
    },
    {
      kind: "short",
      id: "ratio-proportion-quiz-q05",
      question: "A car travels 150 km in 1 hour 40 minutes. Work out its average speed in km/h.",
      answer: { type: "number", value: 90, display: "90 km/h" },
      traps: [{ spec: { type: "number", value: 107.14, tolerance: 0.01 }, feedback: "1 hour 40 minutes is not 1.4 hours — 40 minutes is {{40/60 = 2/3}} of an hour, so the time is {{5/3}} hours." }],
      solution: ["Time = 1 h 40 min = {{1 2/3}} h = {{5/3}} h.", "Speed = distance ÷ time = 150 ÷ {{5/3}}.", "= 150 × {{3/5}} = 90 km/h."],
      commonError: "Writing 1 h 40 min as 1.4 h.",
      difficulty: "core",
      guideRef: "compound-measures",
      hints: ["Write the time in hours. How many hours is 40 minutes?", "40 min = {{2/3}} h, so the time is {{5/3}} h.", "Speed = distance ÷ time."],
      strategy: "Change the form",
    },
    {
      kind: "mcq",
      id: "ratio-proportion-quiz-q06",
      question: "A sprinter runs at an average speed of 9.5 m/s. What is this speed in kilometres per hour?",
      options: ["34.2 km/h", "2.64 km/h", "570 km/h", "0.57 km/h"],
      answerIndex: 0,
      explanation:
        "9.5 m every second is 9.5 × 3600 = 34 200 m every hour, which is 34.2 km/h (or simply × 3.6). 2.64 comes from dividing by 3.6 — the wrong direction, since km/h numbers are bigger than m/s numbers. 570 is the number of metres per **minute** (× 60), and 0.57 is the number of kilometres per minute.",
      difficulty: "core",
      guideRef: "compound-measures",
      hints: ["How many metres does the sprinter cover in one hour (3600 seconds)?", "9.5 × 3600 metres per hour. Now convert metres to kilometres."],
      strategy: "Change the form",
    },
    {
      kind: "short",
      id: "ratio-proportion-quiz-q07",
      question: "y is directly proportional to {{x^2}}. When x = 6, y = 72. Find the value of y when x = 5.",
      answer: { type: "number", value: 50 },
      traps: [{ spec: { type: "number", value: 60 }, feedback: "That treats y as proportional to x. Here y ∝ {{x^2}}, so {{y = kx^2}}." }],
      solution: ["{{y = kx^2}}.", "72 = k × 36, so k = 2.", "{{y = 2x^2}}. When x = 5: y = 2 × 25 = 50."],
      commonError: "Using y = kx instead of {{y = kx^2}}.",
      difficulty: "core",
      guideRef: "direct-proportion",
      hints: ["Write the relationship as an equation with a constant k.", "{{y = kx^2}}. Substitute x = 6, y = 72 to find k.", "k = 2. Now substitute x = 5."],
      strategy: "Introduce a variable",
    },
    {
      kind: "short",
      id: "ratio-proportion-quiz-q08",
      question: "y is inversely proportional to {{x^2}}. When x = 3, y = 8. Find the value of y when x = 6.",
      answer: { type: "number", value: 2 },
      traps: [{ spec: { type: "number", value: 4 }, feedback: "That would be true for y ∝ {{1/x}}. Here it is {{1/x^2}}: doubling x divides y by {{2^2 = 4}}." }],
      solution: ["{{y = k/x^2}}.", "8 = {{k/9}}, so k = 72.", "When x = 6: y = {{72/36}} = 2."],
      commonError: "Forgetting the square, so doubling x only halves y.",
      difficulty: "core",
      guideRef: "inverse-proportion",
      hints: ["Inverse proportion to {{x^2}} means {{y = k/x^2}}.", "Use x = 3, y = 8 to find k.", "k = 72. Substitute x = 6."],
      strategy: "Introduce a variable",
    },
    {
      kind: "mcq",
      id: "ratio-proportion-quiz-q09",
      question: "p is inversely proportional to {{q^2}}. The value of q is doubled. What happens to the value of p?",
      options: ["p is halved", "p is multiplied by 4", "p decreases by 25%", "p is divided by 4"],
      answerIndex: 3,
      explanation:
        "{{p = k/q^2}}. Replace q with 2q: {{k/(2q)^2 = k/(4q^2)}}, so p is divided by 4. 'Halved' forgets the square (that is p ∝ {{1/q}}). 'Multiplied by 4' is direct proportion to {{q^2}}. 'Decreases by 25%' confuses 'a quarter of the original' with 'a quarter less' — dividing by 4 is a 75% decrease.",
      difficulty: "core",
      guideRef: "inverse-proportion",
      hints: ["Write p as {{k/q^2}}.", "Replace q by 2q. What is {{(2q)^2}}?"],
      strategy: "Try small cases",
    },
    {
      kind: "short",
      id: "ratio-proportion-quiz-q10",
      question: "A map has a scale of 1 : 40 000. The distance between two hawker centres on the map is 4.5 cm. Work out the real distance between the hawker centres in kilometres.",
      answer: { type: "number", value: 1.8, display: "1.8 km" },
      traps: [
        { spec: { type: "number", value: 18 }, feedback: "Check the conversion: there are 100 000 cm in 1 km (100 cm in a metre, 1000 m in a km)." },
        { spec: { type: "number", value: 180000 }, feedback: "180 000 is the distance in centimetres. Convert to kilometres." },
      ],
      solution: ["Real distance = 4.5 × 40 000 = 180 000 cm.", "180 000 cm ÷ 100 = 1800 m.", "1800 m ÷ 1000 = 1.8 km."],
      commonError: "Dividing by 10 000 or 1000 instead of 100 000 when converting cm to km.",
      difficulty: "core",
      guideRef: "ratio-problems",
      hints: ["1 cm on the map is 40 000 cm in real life.", "Multiply, then convert cm → m → km.", "1 km = 100 000 cm."],
      strategy: "Change the form",
    },
  ],

  // ---------------------------------------------------------------- papers
  papers: [
    {
      id: "ratio-proportion-p1",
      title: "Practice Paper 1",
      questions: [
        {
          kind: "short",
          id: "ratio-proportion-p1-q01",
          question: "Write the ratio 2.4 : 3.6 in its simplest form, using whole numbers.",
          answer: { type: "ratio", parts: [2, 3], simplest: true, display: "2 : 3" },
          solution: ["Multiply by 10 to clear the decimals: 24 : 36.", "Divide both by 12: 2 : 3."],
          commonError: "Stopping at 24 : 36 or 12 : 18 — the HCF of 24 and 36 is 12.",
          difficulty: "warmup",
          guideRef: "ratio-basics",
          hints: ["Multiply both parts by 10 to get whole numbers, then divide by the HCF."],
          strategy: "Change the form",
        },
        {
          kind: "short",
          id: "ratio-proportion-p1-q02",
          question: "Write the ratio 5 : 8 in the form 1 : n. Give the value of n as a decimal.",
          answer: { type: "number", value: 1.6, allowFraction: false },
          traps: [{ spec: { type: "number", value: 0.625 }, feedback: "0.625 = 5 ÷ 8, which gives the form n : 1. For 1 : n divide both parts by the *first* part, 5." }],
          solution: ["To make the first part 1, divide both parts by 5.", "5 ÷ 5 : 8 ÷ 5 = 1 : 1.6.", "n = 1.6."],
          commonError: "Dividing by 8 instead of 5.",
          difficulty: "warmup",
          guideRef: "ratio-basics",
          hints: ["What must you divide 5 by to get 1? Do the same to 8."],
          strategy: "Use the inverse",
        },
        {
          kind: "short",
          id: "ratio-proportion-p1-q03",
          question: "Marble has a density of 2.6 g/cm³. A marble paperweight has a volume of 45 cm³. Work out its mass in grams.",
          answer: { type: "number", value: 117, display: "117 g" },
          traps: [{ spec: { type: "number", value: 17.31, tolerance: 0.01 }, feedback: "You divided. Density = mass ÷ volume, so mass = density × volume." }],
          solution: ["Density = {{\"mass\"/\"volume\"}}, so mass = density × volume.", "Mass = 2.6 × 45 = 117 g."],
          commonError: "Dividing volume by density.",
          difficulty: "warmup",
          guideRef: "compound-measures",
          hints: ["The units g/cm³ tell you density = grams ÷ cm³. Rearrange for grams."],
          strategy: "Use the units",
        },
        {
          kind: "short",
          id: "ratio-proportion-p1-q04",
          question: "Priya's recipe for 12 pineapple tarts uses 180 g of butter. How much butter does she need to make 20 tarts? Give your answer in grams.",
          answer: { type: "number", value: 300, display: "300 g" },
          solution: ["Butter for one tart: 180 ÷ 12 = 15 g.", "For 20 tarts: 20 × 15 = 300 g."],
          solutions: [{ label: "Scale factor", steps: ["Scale factor {{20/12 = 5/3}}.", "180 × {{5/3}} = 300 g."] }],
          commonError: "Adding 8 g for 8 extra tarts instead of scaling.",
          difficulty: "warmup",
          guideRef: "ratio-problems",
          hints: ["Find how much butter one tart needs (the unitary method)."],
          strategy: "Find one part first",
        },
        {
          kind: "short",
          id: "ratio-proportion-p1-q05",
          question: "Aisha and Marcus share some money in the ratio 5 : 3. Aisha gets $84 more than Marcus. How much money do they share altogether? Give your answer in dollars.",
          answer: { type: "number", value: 336, display: "$336" },
          traps: [{ spec: { type: "number", value: 672 }, feedback: "$84 is the *difference*, which is 5 − 3 = 2 parts — not one part." }],
          solution: ["The difference is 5 − 3 = 2 parts.", "2 parts = $84, so 1 part = $42.", "Total = 5 + 3 = 8 parts = 8 × 42 = $336."],
          commonError: "Treating the $84 difference as one part.",
          difficulty: "core",
          guideRef: "ratio-basics",
          hints: ["How many parts more does Aisha have than Marcus?", "2 parts = $84. Find one part.", "The total is 8 parts."],
          strategy: "Use a bar model",
        },
        {
          kind: "short",
          id: "ratio-proportion-p1-q06",
          question: "a : b = 3 : 5 and b : c = 2 : 7. Find a : b : c in its simplest form.",
          answer: { type: "ratio", parts: [6, 10, 35], simplest: true, display: "6 : 10 : 35" },
          traps: [{ spec: { type: "ratio", parts: [3, 5, 7] }, feedback: "The b parts are 5 in one ratio and 2 in the other, so you can't just glue them together. Scale both so b is 10." }],
          solution: ["The b values are 5 and 2; LCM = 10.", "a : b = 3 : 5 = 6 : 10.", "b : c = 2 : 7 = 10 : 35.", "So a : b : c = 6 : 10 : 35 (no common factor)."],
          commonError: "Writing 3 : 5 : 7 or 3 : 2 : 7 without matching the b parts.",
          difficulty: "core",
          guideRef: "ratio-basics",
          hints: ["The two ratios share b. Is b the same number of parts in both?", "Make b equal to the LCM of 5 and 2.", "Multiply a : b by 2 and b : c by 5."],
          strategy: "Find a common multiple",
        },
        {
          kind: "short",
          id: "ratio-proportion-p1-q07",
          question: "A map has a scale of 1 : 50 000. The real distance between two villages is 3.2 km. Work out the distance between them on the map, in centimetres.",
          answer: { type: "number", value: 6.4, display: "6.4 cm" },
          traps: [{ spec: { type: "number", value: 0.064 }, feedback: "You converted 3.2 km to metres (3200 m) and then divided. The map ratio needs the *same* unit on both sides — convert to centimetres: 320 000 cm." }],
          solution: ["3.2 km = 3200 m = 320 000 cm.", "Map distance = 320 000 ÷ 50 000.", "= 6.4 cm."],
          commonError: "Converting km to m instead of to cm before dividing.",
          difficulty: "core",
          guideRef: "ratio-problems",
          hints: ["Map → real means × 50 000, so real → map means ÷ 50 000.", "Convert 3.2 km to cm before dividing.", "1 km = 100 000 cm."],
          strategy: "Use the inverse",
        },
        {
          kind: "written",
          id: "ratio-proportion-p1-q08",
          question:
            "At a supermarket in Tampines, jasmine rice is sold in two sizes.\n\n| Bag | Mass | Price |\n|---|---|---|\n| Large | 2 kg | $5.60 |\n| Small | 750 g | $2.25 |\n\nShow that the large bag is better value for money.",
          marks: 3,
          modelAnswer:
            "Compare the cost of the same mass.\n\nLarge: 2 kg = 2000 g, so 100 g costs 5.60 ÷ 20 = $0.28.\n\nSmall: 750 g, so 100 g costs 2.25 ÷ 7.5 = $0.30.\n\n$0.28 < $0.30, so the large bag is cheaper per 100 g and is better value.",
          markScheme: [
            { point: "Converts to the same units (2 kg = 2000 g) and finds a comparable unit rate for one bag, e.g. 0.28 per 100 g or 357 g per $", keywords: ["2000", "0.28", "28", "357", "0.0028"] },
            { point: "Correct comparable unit rate for the other bag, e.g. 0.30 per 100 g or 333 g per $", keywords: ["0.30", "0.3", "30", "333", "0.003"] },
            { point: "Correct conclusion stated from the comparison", keywords: ["large", "better value", "cheaper", "less per"] },
          ],
          commonError: "Comparing prices without making the masses the same, or forgetting to convert 2 kg into grams.",
          difficulty: "core",
          guideRef: "ratio-problems",
          hints: ["You need to compare like with like — the same mass, or the same money.", "Work out the cost of 100 g for each bag.", "Remember 2 kg = 2000 g."],
          strategy: "Find one part first",
        },
        {
          kind: "short",
          id: "ratio-proportion-p1-q09",
          question: "Kenji cycles 18 km at an average speed of 24 km/h. He then cycles a further 20 km at an average speed of 16 km/h. Work out his average speed for the whole 38 km, in km/h.",
          answer: { type: "number", value: 19, display: "19 km/h" },
          traps: [{ spec: { type: "number", value: 20 }, feedback: "20 is the mean of 24 and 16. Average speed is *total distance ÷ total time* — and he spends longer at 16 km/h, so the two speeds aren't equally weighted." }],
          solution: ["Time 1 = 18 ÷ 24 = 0.75 h.", "Time 2 = 20 ÷ 16 = 1.25 h.", "Total time = 2 h; total distance = 38 km.", "Average speed = 38 ÷ 2 = 19 km/h."],
          commonError: "Averaging the two speeds.",
          difficulty: "core",
          guideRef: "compound-measures",
          hints: ["Average speed = total distance ÷ total time.", "Find the time for each part of the journey.", "Times are 0.75 h and 1.25 h."],
          strategy: "Split into cases",
        },
        {
          kind: "short",
          id: "ratio-proportion-p1-q10",
          question: "A box of textbooks has a weight of 960 N. Its base is a rectangle 40 cm by 60 cm. Work out the pressure it exerts on the floor, in N/m².",
          answer: { type: "number", value: 4000, display: "4000 N/m²" },
          traps: [{ spec: { type: "number", value: 0.4 }, feedback: "0.4 is the pressure in N/cm² (960 ÷ 2400). The question asks for N/m², so convert the area to m² first: 0.4 m × 0.6 m." }],
          solution: ["Area in m²: 0.4 × 0.6 = 0.24 m².", "Pressure = {{force/area}} = 960 ÷ 0.24.", "= 4000 N/m²."],
          commonError: "Leaving the area in cm², or converting 2400 cm² to m² by dividing by 100 instead of 10 000.",
          difficulty: "core",
          guideRef: "compound-measures",
          hints: ["Pressure = force ÷ area. What units must the area be in?", "Convert each length to metres before multiplying.", "Area = 0.4 × 0.6 m²."],
          strategy: "Use the units",
        },
        {
          kind: "short",
          id: "ratio-proportion-p1-q11",
          question: "The cost, $C, of a circular rug is directly proportional to the square of its radius, r metres. A rug of radius 0.8 m costs $96. Work out the cost of a rug of radius 1.2 m. Give your answer in dollars.",
          answer: { type: "number", value: 216, display: "$216" },
          traps: [{ spec: { type: "number", value: 144 }, feedback: "That scales the cost by 1.5, as if C ∝ r. The cost depends on {{r^2}}, so the multiplier is {{1.5^2 = 2.25}}." }],
          solution: ["{{C = kr^2}}.", "96 = k × 0.64, so k = 150.", "{{C = 150r^2}}. When r = 1.2: C = 150 × 1.44 = $216."],
          solutions: [{ label: "Scale factor", steps: ["r is multiplied by {{1.2/0.8}} = 1.5.", "So C is multiplied by {{1.5^2}} = 2.25.", "96 × 2.25 = $216."] }],
          commonError: "Treating C as proportional to r instead of {{r^2}}.",
          difficulty: "core",
          guideRef: "direct-proportion",
          hints: ["Write the relationship with a constant: C = k × ?", "{{C = kr^2}}. Substitute r = 0.8, C = 96.", "k = 150."],
          strategy: "Introduce a variable",
        },
        {
          kind: "written",
          id: "ratio-proportion-p1-q12",
          question:
            "y is inversely proportional to x.\n\nRavi says: \"If x increases by 50%, then y decreases by 50%.\"\n\nExplain why Ravi is wrong, and find the actual percentage decrease in y.",
          marks: 3,
          modelAnswer:
            "{{y = k/x}}. If x increases by 50%, the new x is 1.5x.\n\nNew y = {{k/(1.5x) = 1/1.5 * k/x = 2/3 y}}.\n\nSo y is multiplied by {{2/3}}, not by 0.5. That is a decrease of {{1/3}}, i.e. 33{{1/3}}% (33.3%). Ravi is wrong because y is *divided* by 1.5, which is not the same as taking 50% off.",
          markScheme: [
            { point: "Uses y = k/x and replaces x with 1.5x", keywords: ["k/x", "1.5x", "1.5"] },
            { point: "Shows new y = 2/3 of the original (or y ÷ 1.5)", keywords: ["2/3", "0.667", "÷ 1.5", "divided by 1.5"] },
            { point: "States the decrease is 33.3% (one third) so Ravi is wrong", keywords: ["33.3", "33", "1/3", "one third"] },
          ],
          commonError: "Assuming inverse proportion means 'the same percentage the other way'.",
          difficulty: "core",
          guideRef: "inverse-proportion",
          hints: ["Write y = {{k/x}}. What does 'x increases by 50%' do to x?", "Replace x with 1.5x and simplify.", "Is dividing by 1.5 the same as multiplying by 0.5?"],
          strategy: "Try small cases",
        },
        {
          kind: "short",
          id: "ratio-proportion-p1-q13",
          question: "Mei and Siti have money in the ratio 5 : 3. Mei gives Siti $24. The ratio of Mei's money to Siti's money is now 7 : 9. How much money did Mei have at the start? Give your answer in dollars.",
          answer: { type: "number", value: 80, display: "$80" },
          traps: [{ spec: { type: "number", value: 48 }, feedback: "That's Siti's starting amount. The question asks for Mei's." }],
          solution: [
            "Let Mei have 5x and Siti 3x.",
            "After the gift: {{(5x - 24)/(3x + 24) = 7/9}}.",
            "9(5x − 24) = 7(3x + 24), so 45x − 216 = 21x + 168.",
            "24x = 384, so x = 16.",
            "Mei had 5 × 16 = $80. (Check: 56 : 72 = 7 : 9.)",
          ],
          solutions: [
            {
              label: "The total doesn't change",
              steps: [
                "The total is fixed. Before: 8 parts. After: 16 parts. Use 16 parts for both.",
                "Before: 5 : 3 = 10 : 6. After: 7 : 9.",
                "Mei goes from 10 parts to 7 parts — she loses 3 parts, which is the $24.",
                "1 part = $8, so Mei had 10 × 8 = $80.",
              ],
            },
          ],
          commonError: "Subtracting 24 from both people (it moves from one to the other, so Siti gains 24).",
          difficulty: "challenge",
          guideRef: "ratio-problems",
          hints: ["What stays the same when Mei gives Siti money?", "The total stays the same. Write both ratios with the same total number of parts.", "5 : 3 = 10 : 6 and 7 : 9 both have 16 parts. How many parts did Mei lose?"],
          strategy: "Look for an invariant",
        },
        {
          kind: "short",
          id: "ratio-proportion-p1-q14",
          question: "The mass, M, of a solid ball bearing is directly proportional to the cube of its radius, r. The radius is increased by 20%. Work out the percentage increase in M.",
          answer: { type: "number", value: 72.8, display: "72.8%" },
          traps: [
            { spec: { type: "number", value: 60 }, feedback: "3 × 20% assumes percentages add up. They multiply: the scale factor is {{1.2^3}}." },
            { spec: { type: "number", value: 172.8 }, feedback: "172.8% is the new mass as a percentage of the old. The *increase* is 72.8%." },
          ],
          solution: ["{{M = kr^3}}.", "New radius = 1.2r, so new M = {{k(1.2r)^3 = 1.728kr^3}}.", "M is multiplied by 1.728: an increase of 72.8%."],
          commonError: "Multiplying 20% by 3 to get 60%.",
          difficulty: "challenge",
          guideRef: "direct-proportion",
          hints: ["Write M = {{kr^3}}. What is the multiplier for a 20% increase?", "Replace r with 1.2r.", "Work out {{1.2^3}} and turn it back into a percentage change."],
          strategy: "Use a multiplier",
        },
        {
          kind: "written",
          id: "ratio-proportion-p1-q15",
          question:
            "Zara runs up a hill path at an average speed of 8 km/h. She then runs back down the same path at an average speed of 12 km/h.\n\nShow that her average speed for the whole run is 9.6 km/h.",
          marks: 3,
          modelAnswer:
            "Let the path be d km long.\n\nTime up = {{d/8}} h; time down = {{d/12}} h.\n\nTotal time = {{d/8 + d/12 = 3d/24 + 2d/24 = 5d/24}} h.\n\nTotal distance = 2d km.\n\nAverage speed = 2d ÷ {{5d/24}} = {{2d * 24/(5d) = 48/5}} = 9.6 km/h. The d cancels, so this is true for any length of path.",
          markScheme: [
            { point: "Introduces a distance (or picks a value such as 24 km) and writes both times, d/8 and d/12", keywords: ["d/8", "d/12", "24", "3 hours", "2 hours"] },
            { point: "Total time 5d/24 (or 5 h for 24 km) with total distance 2d (or 48 km)", keywords: ["5d/24", "2d", "48", "5 hours", "5"] },
            { point: "Divides total distance by total time to get 9.6 km/h", keywords: ["9.6", "48/5"] },
          ],
          commonError: "Averaging the speeds: (8 + 12) ÷ 2 = 10 km/h. She spends longer going up, so the slower speed counts for more.",
          difficulty: "challenge",
          guideRef: "compound-measures",
          hints: ["You don't know the length of the path. Call it d (or pick a convenient number like 24 km).", "Find the time for each half in terms of d.", "Average speed = total distance ÷ total time — the d should cancel."],
          strategy: "Introduce a variable",
        },
      ],
    },
    {
      id: "ratio-proportion-p2",
      title: "Practice Paper 2",
      questions: [
        {
          kind: "short",
          id: "ratio-proportion-p2-q01",
          question: "Siti and Ethan share $360 in the ratio 7 : 5. How much does Ethan get? Give your answer in dollars.",
          answer: { type: "number", value: 150, display: "$150" },
          traps: [{ spec: { type: "number", value: 210 }, feedback: "$210 is Siti's share (7 parts). Ethan gets 5 parts." }],
          solution: ["Total parts: 7 + 5 = 12.", "One part: 360 ÷ 12 = $30.", "Ethan: 5 × 30 = $150."],
          commonError: "Giving the larger share by mistake.",
          difficulty: "warmup",
          guideRef: "ratio-basics",
          hints: ["Find the value of one part: divide by 7 + 5."],
          strategy: "Find one part first",
        },
        {
          kind: "short",
          id: "ratio-proportion-p2-q02",
          question: "For a fruit punch, Jun mixes 350 ml of lime juice, 2 litres of soda water and 1.25 litres of orange juice. Write the ratio lime : soda : orange in its simplest form.",
          answer: { type: "ratio", parts: [7, 40, 25], simplest: true, display: "7 : 40 : 25" },
          traps: [{ spec: { type: "ratio", parts: [350, 2, 1.25] }, feedback: "The units are mixed (ml and litres). Convert everything to ml first: 350 : 2000 : 1250." }],
          solution: ["Same units: 350 ml : 2000 ml : 1250 ml.", "Divide all three by 50 (the HCF).", "7 : 40 : 25."],
          commonError: "Mixing ml and litres in the same ratio.",
          difficulty: "warmup",
          guideRef: "ratio-basics",
          hints: ["Write every quantity in millilitres, then divide by the HCF."],
          strategy: "Change the form",
        },
        {
          kind: "short",
          id: "ratio-proportion-p2-q03",
          question: "An MRT train travels 4.2 km between two stations in 6 minutes. Work out its average speed in km/h.",
          answer: { type: "number", value: 42, display: "42 km/h" },
          traps: [{ spec: { type: "number", value: 0.7 }, feedback: "0.7 is in km per *minute*. Multiply by 60 to get km per hour." }],
          solution: ["6 minutes = {{6/60}} = 0.1 h.", "Speed = 4.2 ÷ 0.1 = 42 km/h."],
          commonError: "Dividing by 6 and leaving the answer in km per minute.",
          difficulty: "warmup",
          guideRef: "compound-measures",
          hints: ["Convert 6 minutes into hours, then use speed = distance ÷ time."],
          strategy: "Use the units",
        },
        {
          kind: "short",
          id: "ratio-proportion-p2-q04",
          question: "y is directly proportional to x. When x = 4, y = 28. Find the value of y when x = 11.",
          answer: { type: "number", value: 77 },
          solution: ["y = kx.", "28 = 4k, so k = 7.", "When x = 11: y = 7 × 11 = 77."],
          commonError: "Adding 7 (the change in x) to 28 instead of multiplying by the constant.",
          difficulty: "warmup",
          guideRef: "direct-proportion",
          hints: ["Write y = kx and use x = 4, y = 28 to find k."],
          strategy: "Introduce a variable",
        },
        {
          kind: "short",
          id: "ratio-proportion-p2-q05",
          question: "In a school robotics CCA, the ratio of boys to girls is 4 : 7. There are 28 boys. Then 5 more girls join the CCA. Write the new ratio of boys to girls in its simplest form.",
          answer: { type: "ratio", parts: [14, 27], simplest: true, display: "14 : 27" },
          traps: [{ spec: { type: "ratio", parts: [4, 12] }, feedback: "You added 5 to the 7 *parts*. The 5 new girls are 5 people, not 5 parts — work out the actual numbers first." }],
          solution: ["Boys = 4 parts = 28, so 1 part = 7.", "Girls at the start = 7 × 7 = 49.", "After 5 join: 49 + 5 = 54 girls.", "Boys : girls = 28 : 54 = 14 : 27 (÷ 2)."],
          commonError: "Adding the 5 new girls to the ratio number 7 instead of to the actual number of girls.",
          difficulty: "core",
          guideRef: "ratio-basics",
          hints: ["28 boys is how many parts?", "Find one part, then the number of girls at the start.", "Add 5 girls, then simplify 28 : (new number of girls)."],
          strategy: "Find one part first",
        },
        {
          kind: "short",
          id: "ratio-proportion-p2-q06",
          question: "Headphones cost £85 in London. The same headphones cost S$159 in Singapore. The exchange rate is S$1 = £0.58. How much cheaper, in Singapore dollars, are the headphones in London? Give your answer to the nearest cent.",
          answer: { type: "number", value: 12.45, tolerance: 0.006, display: "S$12.45" },
          traps: [{ spec: { type: "number", value: 109.7, tolerance: 0.01 }, feedback: "You multiplied £85 by 0.58. Pounds are worth *more* than Singapore dollars, so £85 is more than S$85 — divide by 0.58." }],
          solution: ["£85 in S$: 85 ÷ 0.58 = 146.55… ≈ S$146.55.", "Difference: 159 − 146.55 = S$12.45."],
          commonError: "Multiplying by the rate when converting from pounds into dollars.",
          difficulty: "core",
          guideRef: "ratio-problems",
          hints: ["First put both prices into the same currency.", "S$1 = £0.58 means £1 is worth more than S$1. Multiply or divide?", "£85 ÷ 0.58 gives the price in S$."],
          strategy: "Estimate first",
        },
        {
          kind: "short",
          id: "ratio-proportion-p2-q07",
          question:
            "Drink A is a 250 ml bottle containing 40 ml of mango concentrate; the rest is water. Drink B is mango concentrate and water mixed in the ratio 3 : 17.\n\nOlivia pours 250 ml of drink A and 400 ml of drink B into a jug. What fraction of the drink in the jug is concentrate? Give your answer as a fraction in its simplest form.",
          answer: { type: "fraction", n: 2, d: 13, simplest: true },
          traps: [{ spec: { type: "fraction", n: 31, d: 200 }, feedback: "You averaged the two concentrations (16% and 15%). The jug holds different amounts of each drink, so add the actual millilitres of concentrate." }],
          solution: [
            "Concentrate from A: 40 ml.",
            "B is {{3/20}} concentrate: {{3/20}} × 400 = 60 ml.",
            "Total concentrate = 100 ml in 650 ml.",
            "{{100/650 = 2/13}}.",
          ],
          commonError: "Treating 3 : 17 as 3 out of 17 instead of 3 out of 20.",
          difficulty: "core",
          guideRef: "ratio-problems",
          hints: ["Work out the millilitres of concentrate from each drink.", "In B, 3 : 17 means 3 parts out of 3 + 17 = 20.", "Fraction = total concentrate ÷ total volume."],
          strategy: "Find one part first",
        },
        {
          kind: "written",
          id: "ratio-proportion-p2-q08",
          question:
            "A scale drawing of a school hall uses the scale 1 : 200. On the drawing the hall is a rectangle 9 cm by 6 cm.\n\nMei says: \"The area on the drawing is 54 cm², so the real area is 54 × 200 = 10 800 cm², which is 1.08 m².\"\n\nExplain Mei's mistake and work out the correct real area of the hall in m².",
          marks: 3,
          modelAnswer:
            "Mei used the length scale factor (200) on an area. Every length is multiplied by 200, so area is multiplied by {{200^2}} = 40 000.\n\nReal lengths: 9 × 200 = 1800 cm = 18 m and 6 × 200 = 1200 cm = 12 m.\n\nReal area = 18 × 12 = 216 m². (Check: 54 × 40 000 = 2 160 000 cm² = 216 m².)",
          markScheme: [
            { point: "Explains that the area scale factor is 200² = 40 000, not 200", keywords: ["200²", "200^2", "squared", "40000", "40 000", "area scale factor"] },
            { point: "Finds the real lengths 18 m and 12 m (or 54 × 40 000 = 2 160 000 cm²)", keywords: ["18", "12", "1800", "1200", "2160000", "2 160 000"] },
            { point: "Correct area 216 m²", keywords: ["216"] },
          ],
          commonError: "Multiplying an area by the length scale factor.",
          difficulty: "core",
          guideRef: "ratio-problems",
          hints: ["The scale 1 : 200 is a *length* ratio. What happens to area when both length and width are multiplied by 200?", "Find the real length and width in metres first.", "18 m × 12 m."],
          strategy: "Draw a diagram",
        },
        {
          kind: "short",
          id: "ratio-proportion-p2-q09",
          question: "A jeweller melts 15 cm³ of gold (density 19.3 g/cm³) together with 5 cm³ of silver (density 10.5 g/cm³) to make an alloy. Assuming no volume is lost, work out the density of the alloy in g/cm³.",
          answer: { type: "number", value: 17.1, display: "17.1 g/cm³" },
          traps: [{ spec: { type: "number", value: 14.9 }, feedback: "14.9 is the mean of the two densities. There's three times as much gold as silver, so you must use total mass ÷ total volume." }],
          solution: ["Mass of gold = 15 × 19.3 = 289.5 g.", "Mass of silver = 5 × 10.5 = 52.5 g.", "Total mass = 342 g; total volume = 20 cm³.", "Density = 342 ÷ 20 = 17.1 g/cm³."],
          commonError: "Averaging the two densities.",
          difficulty: "core",
          guideRef: "compound-measures",
          hints: ["Density = total mass ÷ total volume. What do you need to find first?", "Find each mass using mass = density × volume.", "Total mass 342 g, total volume 20 cm³."],
          strategy: "Use the units",
        },
        {
          kind: "short",
          id: "ratio-proportion-p2-q10",
          question: "Steel has a density of 7800 kg/m³. Convert this density into g/cm³.",
          answer: { type: "number", value: 7.8, display: "7.8 g/cm³" },
          traps: [{ spec: { type: "number", value: 78 }, feedback: "1 m³ is not 100 cm³ — it is 100 × 100 × 100 = 1 000 000 cm³." }],
          solution: ["7800 kg = 7 800 000 g.", "1 m³ = 100 × 100 × 100 = 1 000 000 cm³.", "7 800 000 ÷ 1 000 000 = 7.8 g/cm³."],
          commonError: "Using 1 m³ = 100 cm³ (or 1000 cm³) instead of 1 000 000 cm³.",
          difficulty: "core",
          guideRef: "compound-measures",
          hints: ["Convert the kilograms to grams and the m³ to cm³ separately.", "A 1 m cube is 100 cm × 100 cm × 100 cm.", "Grams ÷ cm³."],
          strategy: "Use the units",
        },
        {
          kind: "short",
          id: "ratio-proportion-p2-q11",
          question: "y is directly proportional to the square root of x. When x = 36, y = 15. Find the value of x when y = 20.",
          answer: { type: "number", value: 64 },
          traps: [{ spec: { type: "number", value: 8 }, feedback: "8 is the value of {{sqrt(x)}}. Square it to find x." }],
          solution: ["{{y = k sqrt(x)}}.", "15 = k × 6, so k = 2.5.", "20 = 2.5{{sqrt(x)}}, so {{sqrt(x)}} = 8.", "x = 64."],
          commonError: "Stopping at {{sqrt(x)}} = 8.",
          difficulty: "core",
          guideRef: "direct-proportion",
          hints: ["Write y = k{{sqrt(x)}} and find k.", "k = 2.5. Substitute y = 20.", "You'll get {{sqrt(x)}} — don't stop there."],
          strategy: "Use the inverse",
        },
        {
          kind: "short",
          id: "ratio-proportion-p2-q12",
          question: "6 decorators take 15 days to paint the corridors of an HDB block. After 5 days, 4 more decorators join them. All decorators work at the same rate. How many more days does it take to finish the job?",
          answer: { type: "number", value: 6 },
          traps: [{ spec: { type: "number", value: 9 }, feedback: "9 days is how long 10 decorators would take for the *whole* job. Some of the work was done in the first 5 days." }],
          solution: [
            "Whole job = 6 × 15 = 90 decorator-days.",
            "First 5 days: 6 × 5 = 30 decorator-days done.",
            "Remaining: 60 decorator-days, shared by 10 decorators.",
            "60 ÷ 10 = 6 more days.",
          ],
          commonError: "Forgetting the work already done in the first 5 days.",
          difficulty: "core",
          guideRef: "inverse-proportion",
          hints: ["Measure the job in 'decorator-days'.", "How many decorator-days are done in the first 5 days?", "Share what's left between 10 decorators."],
          strategy: "Introduce a variable",
        },
        {
          kind: "written",
          id: "ratio-proportion-p2-q13",
          question:
            "The intensity of light, I, from a lamp is inversely proportional to the square of the distance, d, from the lamp.\n\nShow that, to halve the intensity of the light on her page, Aisha must increase the distance from the lamp by about 41%.",
          marks: 3,
          modelAnswer:
            "{{I = k/d^2}}. Let the distance be multiplied by m.\n\nNew I = {{k/(md)^2 = 1/m^2 * k/d^2}}, so I is multiplied by {{1/m^2}}.\n\nTo halve I: {{1/m^2 = 1/2}}, so {{m^2 = 2}} and {{m = sqrt(2)}} = 1.414…\n\nSo d must be multiplied by 1.414…, an increase of 41.4…% ≈ 41%. (Not 50% and not 100% — doubling d would make I a quarter.)",
          markScheme: [
            { point: "Writes I = k/d² and replaces d with md (or uses numbers, e.g. d = 1, k = 1)", keywords: ["k/d", "md", "1/m"] },
            { point: "Sets the multiplier 1/m² = 1/2 so m² = 2", keywords: ["1/2", "0.5", "m^2 = 2", "m² = 2", "= 2"] },
            { point: "m = √2 = 1.414…, so an increase of about 41%", keywords: ["√2", "sqrt(2)", "1.414", "1.41", "41"] },
          ],
          commonError: "Saying the distance must double (that gives a quarter of the intensity) or increase by 50%.",
          difficulty: "challenge",
          guideRef: "inverse-proportion",
          hints: ["Write I in terms of k and d.", "If d is multiplied by m, what is I multiplied by?", "Solve {{1/m^2 = 1/2}} and turn m into a percentage increase."],
          strategy: "Use a multiplier",
        },
        {
          kind: "short",
          id: "ratio-proportion-p2-q14",
          question: "A bag holds red, blue and green beads. red : blue = 2 : 5 and blue : green = 3 : 4. There are 42 more green beads than red beads. How many beads are in the bag altogether?",
          answer: { type: "number", value: 123 },
          traps: [{ spec: { type: "number", value: 45 }, feedback: "45 is the number of blue beads. The question asks for the total." }],
          solution: [
            "Match the blue parts: LCM of 5 and 3 is 15.",
            "red : blue = 6 : 15 and blue : green = 15 : 20, so red : blue : green = 6 : 15 : 20.",
            "green − red = 14 parts = 42, so 1 part = 3.",
            "Total = 6 + 15 + 20 = 41 parts = 123 beads.",
          ],
          commonError: "Combining as 2 : 5 : 4 without matching the blue parts.",
          difficulty: "challenge",
          guideRef: "ratio-basics",
          hints: ["Blue appears in both ratios. Make it the same number of parts.", "Scale to red : blue : green = 6 : 15 : 20.", "The difference green − red is 14 parts."],
          strategy: "Find a common multiple",
        },
        {
          kind: "written",
          id: "ratio-proportion-p2-q15",
          question:
            "The time, T seconds, for one swing of a pendulum is directly proportional to the square root of its length, L cm.\n\n(a) Show that to double the time of a swing, the length must be multiplied by 4.\n\n(b) Find the percentage increase in L needed to increase T by 10%.",
          marks: 4,
          modelAnswer:
            "(a) {{T = k sqrt(L)}}. If the length becomes mL, the time becomes {{k sqrt(mL) = sqrt(m) * k sqrt(L) = sqrt(m) T}}. To double T we need {{sqrt(m)}} = 2, so m = 4.\n\n(b) Now we need {{sqrt(m)}} = 1.1, so m = {{1.1^2}} = 1.21. L must increase by 21%.",
          markScheme: [
            { point: "Writes T = k√L and shows multiplying L by m multiplies T by √m", keywords: ["k√l", "ksqrt", "√m", "sqrt(m)", "k sqrt"] },
            { point: "√m = 2 so m = 4 (or shows T for 4L is 2T)", keywords: ["√4", "sqrt(4)", "= 2", "4l", "2t"] },
            { point: "Sets √m = 1.1 and squares to get 1.21", keywords: ["1.1", "1.21", "1.1²", "1.1^2"] },
            { point: "Correct percentage increase 21%", keywords: ["21"] },
          ],
          commonError: "Saying a 10% increase in T needs a 10% (or 20%) increase in L. Percentages multiply: {{1.1^2}} = 1.21.",
          difficulty: "challenge",
          guideRef: "direct-proportion",
          hints: ["Write T = k{{sqrt(L)}}. Replace L with mL.", "The new T is {{sqrt(m)}} times the old T.", "For (b), solve {{sqrt(m)}} = 1.1."],
          strategy: "Use a multiplier",
        },
      ],
    },
  ],

  // ------------------------------------------------------------- challenge
  challenge: [
    {
      kind: "short",
      id: "ratio-proportion-ch-q01",
      question: "(3x − y) : (x + 2y) = 4 : 5, where x and y are positive. Find the ratio x : y in its simplest form.",
      answer: { type: "ratio", parts: [13, 11], simplest: true, display: "13 : 11" },
      traps: [{ spec: { type: "ratio", parts: [11, 13] }, feedback: "Close — but that's y : x. If 11x = 13y, x must be the bigger number (x = 13, y = 11 works)." }],
      solution: [
        "Write the ratio as an equation: {{(3x - y)/(x + 2y) = 4/5}}.",
        "Cross-multiply: 5(3x − y) = 4(x + 2y).",
        "15x − 5y = 4x + 8y, so 11x = 13y.",
        "{{x/y = 13/11}}, so x : y = 13 : 11.",
      ],
      solutions: [
        { label: "Set y = 1", steps: ["Only the ratio matters, so let y = 1.", "{{(3x - 1)/(x + 2) = 4/5}} gives 15x − 5 = 4x + 8, so 11x = 13.", "x = {{13/11}}, so x : y = {{13/11}} : 1 = 13 : 11."] },
      ],
      commonError: "Reading 11x = 13y as x : y = 11 : 13. If 11x = 13y then x must be the bigger number.",
      difficulty: "challenge",
      guideRef: "ratio-basics",
      hints: [
        "A ratio a : b = 4 : 5 can be written as a fraction equation {{a/b = 4/5}}.",
        "Cross-multiply and collect the x terms on one side, y terms on the other.",
        "You should reach 11x = 13y.",
        "If 11x = 13y, which is bigger, x or y? Write x : y so that it matches.",
      ],
      strategy: "Work backwards",
    },
    {
      kind: "short",
      id: "ratio-proportion-ch-q02",
      question:
        "A rectangle has short side 1 and long side r. A 1 by 1 square is cut off one end. The rectangle that is left has its sides in the *same ratio* (long : short) as the original. Find r exactly, giving your answer in the form {{(a + sqrt(b))/c}}.",
      answer: { type: "expression", expr: "(1+sqrt(5))/2", form: "surd", display: "{{(1 + sqrt(5))/2}}" },
      traps: [{ spec: { type: "expression", expr: "(1-sqrt(5))/2" }, feedback: "That root is negative, and a length can't be negative. Take the positive root." }],
      solution: [
        "The leftover rectangle is 1 by (r − 1). Its long side is 1 (since r < 2) and its short side is r − 1.",
        "Same ratio: {{r/1 = 1/(r - 1)}}.",
        "r(r − 1) = 1, so {{r^2 - r - 1 = 0}}.",
        "{{r = (1 +- sqrt(1 + 4))/2 = (1 +- sqrt(5))/2}}.",
        "r > 0, so {{r = (1 + sqrt(5))/2}} ≈ 1.618 (the golden ratio).",
      ],
      commonError: "Writing the leftover ratio the wrong way round, (r − 1) : 1, which gives r − 1 = r, with no solution.",
      difficulty: "challenge",
      guideRef: "ratio-basics",
      hints: [
        "Draw it. What are the side lengths of the rectangle that's left?",
        "The leftover rectangle is 1 by (r − 1). Which side is longer?",
        "Set long : short equal for both: r : 1 = 1 : (r − 1).",
        "Cross-multiply to get a quadratic, then use the formula.",
      ],
      strategy: "Draw a diagram",
    },
    {
      kind: "short",
      id: "ratio-proportion-ch-q03",
      question:
        "Jug P contains syrup and water in the ratio 2 : 3. Jug Q contains syrup and water in the ratio 1 : 4. Wei Ling mixes some of P with some of Q to make exactly 1 litre of drink with syrup and water in the ratio 1 : 3. How many millilitres of P does she use?",
      answer: { type: "number", value: 250, display: "250 ml" },
      traps: [{ spec: { type: "number", value: 750 }, feedback: "750 ml is the amount of Q. Check: P is the stronger drink and the target 25% is much closer to Q's 20% than to P's 40%, so you need less P." }],
      solution: [
        "Syrup fractions: P = {{2/5}} = 0.4, Q = {{1/5}} = 0.2, target {{1/4}} = 0.25.",
        "Let p ml of P; then 1000 − p ml of Q.",
        "0.4p + 0.2(1000 − p) = 0.25 × 1000.",
        "0.2p + 200 = 250, so p = 250 ml.",
      ],
      solutions: [
        {
          label: "Balance the distances (alligation)",
          steps: [
            "The target 0.25 is 0.15 below P (0.4) and 0.05 above Q (0.2).",
            "The amounts are in the *inverse* ratio of these distances: P : Q = 0.05 : 0.15 = 1 : 3.",
            "P is {{1/4}} of 1000 ml = 250 ml.",
          ],
        },
      ],
      commonError: "Treating 2 : 3 as {{2/3}} syrup instead of {{2/5}}.",
      difficulty: "challenge",
      guideRef: "ratio-problems",
      hints: [
        "Turn each ratio into the fraction of the drink that is syrup.",
        "P is {{2/5}} syrup, Q is {{1/5}}, the target is {{1/4}}.",
        "Let p ml of P be used. Write an equation for the total syrup in 1000 ml.",
        "0.4p + 0.2(1000 − p) = 250.",
      ],
      strategy: "Introduce a variable",
    },
    {
      kind: "short",
      id: "ratio-proportion-ch-q04",
      question: "A map has a scale of 1 : n. A reservoir with a real area of 0.54 km² is shown on the map with an area of 6 cm². Work out the value of n.",
      answer: { type: "number", value: 30000, display: "n = 30 000" },
      traps: [
        { spec: { type: "number", value: 900000000 }, feedback: "900 000 000 is the *area* scale factor, {{n^2}}. The map scale 1 : n is a length scale, so take the square root." },
        { spec: { type: "number", value: 3000 }, feedback: "Check the conversion: 1 km² = 100 000 cm × 100 000 cm = {{10^10}} cm², not {{10^8}}." },
      ],
      solution: [
        "1 km² = 100 000 cm × 100 000 cm = {{10^10}} cm², so 0.54 km² = 5 400 000 000 cm².",
        "Area scale factor = 5 400 000 000 ÷ 6 = 900 000 000.",
        "Areas scale by {{n^2}}, so {{n^2}} = 900 000 000.",
        "n = {{sqrt(900000000)}} = 30 000.",
      ],
      solutions: [
        { label: "Work in km", steps: ["1 cm² on the map represents 0.54 ÷ 6 = 0.09 km².", "So 1 cm on the map represents {{sqrt(0.09)}} = 0.3 km.", "0.3 km = 30 000 cm, so the scale is 1 : 30 000."] },
      ],
      commonError: "Forgetting that the area scale factor is {{n^2}}, or converting km² to cm² with {{10^5}} or {{10^8}}.",
      difficulty: "challenge",
      guideRef: "ratio-problems",
      hints: [
        "Is 1 : n a length scale or an area scale? How do areas scale?",
        "Put both areas in the same unit: how many cm² are in 1 km²?",
        "Real area ÷ map area = {{n^2}}.",
        "Or: what real area does 1 cm² of map represent? Square-root it to find what 1 cm represents.",
      ],
      strategy: "Make it simpler",
    },
    {
      kind: "short",
      id: "ratio-proportion-ch-q05",
      question:
        "Arjun cycles from his home to Sentosa at an average speed of 20 km/h. He wants his average speed for the round trip (there and back on the same route) to be 24 km/h. What must his average speed be on the way back, in km/h?",
      answer: { type: "number", value: 30, display: "30 km/h" },
      traps: [{ spec: { type: "number", value: 28 }, feedback: "28 makes the *mean of the speeds* 24, but average speed is total distance ÷ total time. He spends longer on the slow leg, so he needs to go faster than 28." }],
      solution: [
        "Let the one-way distance be d km.",
        "Time there = {{d/20}}. Total time needed = {{(2d)/24 = d/12}}.",
        "Time back = {{d/12 - d/20 = (5d - 3d)/60 = d/30}}.",
        "Speed back = d ÷ {{d/30}} = 30 km/h.",
      ],
      solutions: [
        { label: "Pick a distance", steps: ["Let the distance be 60 km (a multiple of 20 and 24).", "Out: 60 ÷ 20 = 3 h. Whole trip: 120 ÷ 24 = 5 h.", "Back: 60 km in 2 h = 30 km/h."] },
      ],
      commonError: "Assuming the two speeds average to 24, giving 28 km/h.",
      difficulty: "challenge",
      guideRef: "compound-measures",
      hints: [
        "Average speed is not the mean of the speeds. What is it?",
        "Choose a convenient distance (or call it d).",
        "Find the time for the whole trip at 24 km/h, and the time already used going out.",
        "The time left is the time for the return leg.",
      ],
      strategy: "Introduce a variable",
    },
    {
      kind: "short",
      id: "ratio-proportion-ch-q06",
      question: "A train 180 m long travels at a constant speed. From the moment the front of the train enters a tunnel 1.02 km long to the moment the back of the train leaves it takes 48 seconds. Work out the speed of the train in km/h.",
      answer: { type: "number", value: 90, display: "90 km/h" },
      traps: [
        { spec: { type: "number", value: 76.5 }, feedback: "That uses only the tunnel's length. The back of the train must also get through, so the front travels 1020 + 180 m." },
        { spec: { type: "number", value: 25 }, feedback: "25 m/s is right — now convert to km/h (× 3.6)." },
      ],
      solution: [
        "The front travels the tunnel length plus the train length: 1020 + 180 = 1200 m.",
        "Speed = 1200 ÷ 48 = 25 m/s.",
        "In km/h: 25 × 3.6 = 90 km/h.",
      ],
      commonError: "Forgetting that the train's own length must also clear the tunnel.",
      difficulty: "challenge",
      guideRef: "compound-measures",
      hints: [
        "Track one point on the train — say the front. How far does it move during the 48 seconds?",
        "When the back leaves the tunnel, the front is 180 m past the far end.",
        "Distance = 1200 m. Find the speed in m/s, then convert.",
      ],
      strategy: "Draw a diagram",
    },
    {
      kind: "short",
      id: "ratio-proportion-ch-q07",
      question: "y is directly proportional to {{x^2}}, and x is inversely proportional to z. When z = 2, x = 6 and y = 27. Find the value of y when z = 3.",
      answer: { type: "number", value: 12 },
      traps: [{ spec: { type: "number", value: 18 }, feedback: "That assumes y ∝ {{1/z}}. Since x ∝ {{1/z}}, y ∝ {{x^2}} ∝ {{1/z^2}}." }],
      solution: [
        "x = {{c/z}}: 6 = {{c/2}}, so c = 12. When z = 3, x = 4.",
        "{{y = kx^2}}: 27 = 36k, so k = {{3/4}}.",
        "When x = 4: y = {{3/4}} × 16 = 12.",
      ],
      solutions: [
        { label: "Chain the proportions", steps: ["y ∝ {{x^2}} and x ∝ {{1/z}}, so y ∝ {{1/z^2}}: y = {{K/z^2}}.", "27 = {{K/4}}, so K = 108.", "When z = 3: y = {{108/9}} = 12."] },
      ],
      commonError: "Combining the relationships as y ∝ {{1/z}} and forgetting to square.",
      difficulty: "challenge",
      guideRef: "direct-proportion",
      hints: [
        "There are two links in the chain: z → x → y.",
        "Find x when z = 3 first.",
        "Or: if x ∝ {{1/z}}, what is {{x^2}} proportional to?",
      ],
      strategy: "Work backwards",
    },
    {
      kind: "short",
      id: "ratio-proportion-ch-q08",
      question: "The graph shows y plotted against {{x^2}}. It is a straight line through the origin, passing through the point (9, 6). Work out the value of y when x = 6.",
      diagram: ySquaredGraph,
      answer: { type: "number", value: 24 },
      traps: [
        { spec: { type: "number", value: 4 }, feedback: "You read off the graph at 6 on the horizontal axis — but that axis is {{x^2}}, not x. When x = 6, {{x^2}} = 36." },
        { spec: { type: "number", value: 12 }, feedback: "That doubles y because x doubled (x = 3 → 6). But y ∝ {{x^2}}, so doubling x multiplies y by 4." },
      ],
      solution: [
        "A straight line through the origin on a y–{{x^2}} graph means {{y = kx^2}}.",
        "The point has {{x^2}} = 9 and y = 6, so k = {{6/9 = 2/3}}.",
        "When x = 6, {{x^2}} = 36, so y = {{2/3}} × 36 = 24.",
      ],
      solutions: [
        { label: "Scale factor", steps: ["{{x^2}} = 9 means x = 3. Going to x = 6 doubles x.", "y ∝ {{x^2}}, so y is multiplied by {{2^2}} = 4.", "6 × 4 = 24."] },
      ],
      commonError: "Reading the horizontal axis as x rather than {{x^2}}.",
      difficulty: "challenge",
      guideRef: "direct-proportion",
      hints: [
        "Look at the label on the horizontal axis carefully.",
        "A straight line through (0, 0) means y is directly proportional to whatever is on the horizontal axis.",
        "So {{y = kx^2}}. Use the point (9, 6) to find k.",
        "When x = 6, what is {{x^2}}? (It's off the graph — use algebra.)",
      ],
      strategy: "Use the units",
    },
    {
      kind: "short",
      id: "ratio-proportion-ch-q09",
      question: "y is inversely proportional to the square root of x. When x increases by p%, y decreases by 20%. Find the value of p.",
      answer: { type: "number", value: 56.25, display: "56.25" },
      traps: [
        { spec: { type: "number", value: 25 }, feedback: "25% would be right for y ∝ {{1/x}}. Here y ∝ {{1/sqrt(x)}}, so you need to square 1.25." },
        { spec: { type: "number", value: 40 }, feedback: "Doubling 20% doesn't undo a square root. Use multipliers: 0.8 = {{1/sqrt(m)}}." },
      ],
      solution: [
        "{{y = k/sqrt(x)}}. Let x be multiplied by m; then y is multiplied by {{1/sqrt(m)}}.",
        "A 20% decrease means y is multiplied by 0.8: {{1/sqrt(m)}} = 0.8.",
        "{{sqrt(m) = 1/0.8}} = 1.25, so m = {{1.25^2}} = 1.5625.",
        "x increases by 56.25%, so p = 56.25.",
      ],
      commonError: "Working with percentages additively instead of with multipliers.",
      difficulty: "challenge",
      guideRef: "inverse-proportion",
      hints: [
        "Use multipliers, not percentages. What multiplier gives a 20% decrease?",
        "If x is multiplied by m, y is multiplied by {{1/sqrt(m)}}.",
        "Solve {{1/sqrt(m)}} = 0.8.",
        "{{sqrt(m)}} = 1.25. Square it and convert back to a percentage increase.",
      ],
      strategy: "Use a multiplier",
    },
    {
      kind: "short",
      id: "ratio-proportion-ch-q10",
      question:
        "A water tank at a hawker centre has two inlet pipes and one drain. Inlet A alone fills the empty tank in 6 hours. Inlet B alone fills it in 4 hours. The drain alone empties a full tank in 12 hours. The tank is empty and all three are opened at the same time. How many hours does it take to fill the tank?",
      answer: { type: "number", value: 3, display: "3 hours" },
      traps: [
        { spec: { type: "number", value: 2.4 }, feedback: "2.4 hours ignores the drain. The drain removes {{1/12}} of the tank every hour." },
        { spec: { type: "number", value: -2 }, feedback: "Times can't simply be added and subtracted (6 + 4 − 12). Add the *rates* (fractions of the tank per hour) instead." },
      ],
      solution: [
        "Time is inversely proportional to rate, so work with rates (tanks per hour).",
        "A: {{1/6}}, B: {{1/4}}, drain: −{{1/12}}.",
        "Combined: {{1/6 + 1/4 - 1/12 = 2/12 + 3/12 - 1/12 = 4/12 = 1/3}} tank per hour.",
        "Time = 1 ÷ {{1/3}} = 3 hours.",
      ],
      solutions: [
        { label: "Pick a tank size", steps: ["Let the tank hold 12 units (LCM of 6, 4, 12).", "A adds 2 units/h, B adds 3 units/h, the drain removes 1 unit/h.", "Net 4 units/h, so 12 ÷ 4 = 3 hours."] },
      ],
      commonError: "Adding or averaging the times instead of the rates.",
      difficulty: "challenge",
      guideRef: "inverse-proportion",
      hints: [
        "Times don't add, but rates do. What fraction of the tank does each pipe fill in one hour?",
        "A fills {{1/6}} per hour, B fills {{1/4}}, the drain empties {{1/12}}.",
        "Find the net fraction filled per hour.",
        "Or pretend the tank holds 12 litres and count litres per hour.",
      ],
      strategy: "Make it simpler",
    },
  ],
};
