import type { TopicPractice } from "../../types.ts";

export const practice: TopicPractice = {
  // =========================================================================
  // Quick-check quiz — 10 questions (3 mcq, 7 short) across the main sections
  // =========================================================================
  quiz: [
    {
      kind: "short",
      id: "inequalities-quiz-q01",
      question: "Solve 3x − 7 > 11.",
      answer: { type: "text", accept: ["x>6", "6<x", "x>6.0"], display: "x > 6" },
      solution: [
        "Add 7 to both sides: 3x > 18.",
        "Divide both sides by 3 (positive, so the sign stays): x > 6.",
        "Check with x = 7: 21 − 7 = 14 > 11 ✓.",
      ],
      traps: [
        { spec: { type: "text", accept: ["x>4/3", "x>1.33", "x>1.3"] }, feedback: "Undo the −7 by **adding** 7, not subtracting: 3x > 11 + 7 = 18." },
        { spec: { type: "text", accept: ["x=6", "6"] }, feedback: "Right boundary — but the answer is an inequality, not a single value. Every number bigger than 6 works: x > 6." },
      ],
      commonError: "Writing the answer as x = 6: an inequality has a whole set of solutions.",
      difficulty: "warmup",
      guideRef: "linear-inequalities",
      hints: ["Treat it like an equation: undo the −7 first, then the ×3.", "3x > 18. Dividing by a positive number keeps the sign the same way round."],
      strategy: "Use the inverse",
    },
    {
      kind: "mcq",
      id: "inequalities-quiz-q02",
      question: "Solve −2x ≥ 10.",
      options: ["x ≥ −5", "x ≤ 5", "x ≤ −5", "x ≥ 5"],
      answerIndex: 2,
      explanation:
        "Divide both sides by −2. Dividing by a **negative** reverses the inequality, so x ≤ −5. Check: x = −6 gives −2 × (−6) = 12 ≥ 10 ✓, while x = 0 gives 0 ≥ 10 ✗. The answer x ≥ −5 comes from dividing by −2 but forgetting to flip the sign; x ≤ 5 and x ≥ 5 lose the minus sign altogether.",
      difficulty: "warmup",
      guideRef: "linear-inequalities",
      hints: ["What do you divide both sides by?", "You are dividing by a negative number. What happens to the inequality sign?"],
      strategy: "Check by substituting",
    },
    {
      kind: "short",
      id: "inequalities-quiz-q03",
      question: "n is an integer and −3 < 2n + 1 ≤ 9.\n\nWrite down all the possible values of n.",
      answer: { type: "list", values: [-1, 0, 1, 2, 3, 4], display: "−1, 0, 1, 2, 3, 4" },
      solution: [
        "Subtract 1 from all three parts: −4 < 2n ≤ 8.",
        "Divide all three parts by 2: −2 < n ≤ 4.",
        "−2 is **not** included (strict <), 4 **is** included (≤).",
        "Integers: −1, 0, 1, 2, 3, 4.",
      ],
      traps: [
        { spec: { type: "list", values: [-2, -1, 0, 1, 2, 3, 4] }, feedback: "−2 < n means n is strictly greater than −2, so −2 itself is not allowed." },
        { spec: { type: "list", values: [-1, 0, 1, 2, 3] }, feedback: "n ≤ 4 includes 4 itself — check: 2(4) + 1 = 9 ≤ 9 ✓." },
      ],
      commonError: "Including the end value of a strict inequality (−2) or leaving out the end value of a ≤ (4).",
      difficulty: "warmup",
      guideRef: "linear-inequalities",
      hints: ["Do the same thing to all three parts.", "Subtract 1 everywhere, then divide everywhere by 2.", "−2 < n ≤ 4. Which end is included?"],
      strategy: "Use the inverse",
    },
    {
      kind: "short",
      id: "inequalities-quiz-q04",
      question: "Write down the inequality shown on the number line, using x.",
      diagram: `__SVG_QUIZ04__`,
      answer: {
        type: "text",
        accept: ["-2<x<=3", "3>=x>-2", "x>-2andx<=3", "x<=3andx>-2", "-2<x≤3", "{x:-2<x<=3}"],
        display: "−2 < x ≤ 3",
      },
      solution: [
        "Open circle at −2: −2 is **not** included, so x > −2.",
        "Filled circle at 3: 3 **is** included, so x ≤ 3.",
        "Together: −2 < x ≤ 3.",
      ],
      traps: [
        { spec: { type: "text", accept: ["-2<=x<3", "3>x>=-2"] }, feedback: "The circles are the other way round: the **open** circle (not included) is at −2 and the **filled** circle (included) is at 3." },
        { spec: { type: "text", accept: ["-2<=x<=3", "-2<x<3"] }, feedback: "Look closely at the circles: one end is open (strict <) and one is filled (≤)." },
      ],
      commonError: "Swapping the meanings of open and filled circles.",
      difficulty: "core",
      guideRef: "linear-inequalities",
      hints: ["What does an open circle mean? What does a filled circle mean?", "Open = not included (< or >). Filled = included (≤ or ≥).", "Write it as one double inequality with the smaller number on the left."],
      strategy: "Read the diagram",
    },
    {
      kind: "mcq",
      id: "inequalities-quiz-q05",
      question: "Which inequality describes the shaded region?",
      diagram: `__SVG_QUIZ05__`,
      options: ["y > 2x + 1", "y < 2x + 1", "y ≤ 2x + 1", "y ≥ 2x + 1"],
      answerIndex: 1,
      explanation:
        "The line is **dashed**, so points on it are not included: the sign is strict. Test the origin, which is shaded: is 0 < 2(0) + 1? Yes, 0 < 1, so the region is y < 2x + 1. y > 2x + 1 describes the unshaded side; y ≤ 2x + 1 would need a solid line.",
      difficulty: "core",
      guideRef: "graphical-regions",
      hints: ["Is the boundary line solid or dashed? What does that tell you about the sign?", "Pick a point clearly in the shaded region, such as (0, 0). Substitute it."],
      strategy: "Test a point",
    },
    {
      kind: "short",
      id: "inequalities-quiz-q06",
      question:
        "The region R is defined by the inequalities\n\n    x ≥ 1,   y ≥ x,   x + y ≤ 6\n\nHow many points with **integer** coordinates lie in R (including on its boundary)?",
      answer: { type: "number", value: 9 },
      solution: [
        "Go column by column (fix x, find the allowed y).",
        "x = 1: need 1 ≤ y ≤ 5 → 5 points.",
        "x = 2: need 2 ≤ y ≤ 4 → 3 points.",
        "x = 3: need 3 ≤ y ≤ 3 → 1 point.",
        "x = 4: need 4 ≤ y ≤ 2 → impossible.",
        "Total 5 + 3 + 1 = 9.",
      ],
      traps: [
        { spec: { type: "number", value: 4 }, feedback: "All three inequalities include their boundary (≥ and ≤), so points on the lines count too." },
      ],
      commonError: "Leaving out points that sit on a solid boundary line.",
      difficulty: "core",
      guideRef: "graphical-regions",
      hints: ["Sketch the three lines x = 1, y = x and x + y = 6.", "Work one column at a time: for x = 1, what values can y take?", "For each x, y runs from x up to 6 − x."],
      strategy: "Be systematic",
    },
    {
      kind: "short",
      id: "inequalities-quiz-q07",
      question: "Solve {{x^2 - 5x - 14 < 0}}.",
      answer: {
        type: "text",
        accept: ["-2<x<7", "7>x>-2", "x>-2andx<7", "x<7andx>-2", "{x:-2<x<7}"],
        display: "−2 < x < 7",
      },
      solution: [
        "Critical values: {{x^2 - 5x - 14 = 0}} → (x − 7)(x + 2) = 0 → x = −2 or x = 7.",
        "The graph of {{y = x^2 - 5x - 14}} is a ∪-shaped parabola crossing the x-axis at −2 and 7.",
        "We want y < 0: the part of the curve **below** the axis, between the roots.",
        "So −2 < x < 7.",
      ],
      traps: [
        { spec: { type: "text", accept: ["x<-2orx>7", "x>7orx<-2"] }, feedback: "That's where the expression is **positive**. The ∪-shaped curve is below the x-axis between the roots." },
        { spec: { type: "text", accept: ["-7<x<2", "2>x>-7"] }, feedback: "Sign slip in the critical values: (x − 7)(x + 2) = 0 gives x = 7 and x = −2." },
      ],
      commonError: "Writing x < 7 and x < −2 by treating each bracket like a linear equation.",
      difficulty: "core",
      guideRef: "quadratic-inequalities",
      hints: ["Start by solving {{x^2 - 5x - 14 = 0}} to get the critical values.", "Sketch the ∪-shaped curve through the critical values.", "'< 0' means below the x-axis. Which part of the curve is below it?"],
      strategy: "Draw a diagram",
    },
    {
      kind: "mcq",
      id: "inequalities-quiz-q08",
      question: "Solve {{x^2 >= 9}}.",
      options: ["x ≥ 3", "x ≥ ±3", "−3 ≤ x ≤ 3", "x ≤ −3 or x ≥ 3"],
      answerIndex: 3,
      explanation:
        "Critical values ±3. {{y = x^2 - 9}} is ∪-shaped, at or above the axis outside the roots, so x ≤ −3 or x ≥ 3. Check x = −4: 16 ≥ 9 ✓. x ≥ 3 forgets the negative side; 'x ≥ ±3' is meaningless (it would say x ≥ −3, which includes x = 0 and 0 ≥ 9 is false); −3 ≤ x ≤ 3 is where {{x^2 <= 9}}.",
      difficulty: "core",
      guideRef: "quadratic-inequalities",
      hints: ["Does x = −5 satisfy {{x^2 >= 9}}?", "Sketch {{y = x^2 - 9}}. Where is it on or above the x-axis?"],
      strategy: "Check by substituting",
    },
    {
      kind: "short",
      id: "inequalities-quiz-q09",
      question: "Solve {{x^2 + 2x - 15 > 0}}.",
      answer: {
        type: "text",
        accept: ["x<-5orx>3", "x>3orx<-5", "x<-5,x>3", "x>3,x<-5", "{x:x<-5}u{x:x>3}"],
        display: "x < −5 or x > 3",
      },
      solution: [
        "Critical values: (x + 5)(x − 3) = 0 → x = −5 or x = 3.",
        "∪-shaped parabola: positive (above the axis) **outside** the roots.",
        "So x < −5 or x > 3.",
      ],
      traps: [
        { spec: { type: "text", accept: ["-5<x<3", "3>x>-5"] }, feedback: "That's where the expression is negative. '> 0' means above the axis — the two outer pieces." },
        { spec: { type: "text", accept: ["x<-3orx>5", "x>5orx<-3"] }, feedback: "Check the critical values: (x + 5)(x − 3) = 0 gives x = −5 and x = 3." },
      ],
      commonError: "Writing −5 > x > 3, which no number satisfies. Two separate pieces need 'or'.",
      difficulty: "core",
      guideRef: "quadratic-inequalities",
      hints: ["Factorise: which two numbers multiply to −15 and add to 2?", "Sketch the curve through −5 and 3. Where is it above the axis?"],
      strategy: "Draw a diagram",
    },
    {
      kind: "short",
      id: "inequalities-quiz-q10",
      question: "How many integers x satisfy {{x^2 < 20}}?",
      answer: { type: "number", value: 9 },
      solution: [
        "{{x^2 < 20}} means {{-sqrt(20) < x < sqrt(20)}}, and {{sqrt(20) = 4.47...}}",
        "So −4.47… < x < 4.47….",
        "Integers: −4, −3, −2, −1, 0, 1, 2, 3, 4 — that is 9 integers.",
      ],
      traps: [
        { spec: { type: "number", value: 4 }, feedback: "Don't forget the negative integers (and 0): (−4)² = 16 < 20 too." },
        { spec: { type: "number", value: 5 }, feedback: "You've counted 0 to 4. Negative integers work too: (−3)² = 9 < 20." },
      ],
      commonError: "Only counting positive solutions — squaring hides the sign.",
      difficulty: "core",
      guideRef: "quadratic-inequalities",
      hints: ["Which positive integers have squares less than 20?", "Does a negative integer like −4 also work?"],
      strategy: "Use symmetry",
    },
  ],

  // =========================================================================
  // Practice papers
  // =========================================================================
  papers: [
    {
      id: "inequalities-p1",
      title: "Practice Paper 1",
      questions: [
        {
          kind: "short",
          id: "inequalities-p1-q01",
          question: "Solve 5x + 3 ≤ 2x + 18.",
          answer: { type: "text", accept: ["x<=5", "5>=x"], display: "x ≤ 5" },
          solution: ["Subtract 2x from both sides: 3x + 3 ≤ 18.", "Subtract 3: 3x ≤ 15.", "Divide by 3: x ≤ 5."],
          traps: [
            { spec: { type: "text", accept: ["x>=5", "5<=x"] }, feedback: "You only reverse the sign when multiplying or dividing by a **negative**. Here you divide by +3." },
            { spec: { type: "text", accept: ["x<=3", "3>=x"] }, feedback: "Check the collecting: 5x − 2x = 3x and 18 − 3 = 15, so 3x ≤ 15." },
          ],
          commonError: "Flipping the inequality sign when nothing negative was involved.",
          difficulty: "warmup",
          guideRef: "linear-inequalities",
          hints: ["Collect the x terms on the side with more x's.", "3x + 3 ≤ 18. Now finish it like an equation."],
          strategy: "Use the inverse",
        },
        {
          kind: "short",
          id: "inequalities-p1-q02",
          question: "Solve {{(x - 4)/3 > 2}}.",
          answer: { type: "text", accept: ["x>10", "10<x"], display: "x > 10" },
          solution: ["Multiply both sides by 3: x − 4 > 6.", "Add 4: x > 10."],
          traps: [
            { spec: { type: "text", accept: ["x>6", "6<x"] }, feedback: "Nearly: after multiplying by 3 you have x − 4 > 6, so add 4 to get x > 10." },
            { spec: { type: "text", accept: ["x>2/3+4", "x>14/3", "x>4.67"] }, feedback: "Multiply both sides by 3 to clear the fraction — don't divide the 2 by 3." },
          ],
          difficulty: "warmup",
          guideRef: "linear-inequalities",
          hints: ["Clear the fraction first: multiply both sides by 3."],
          strategy: "Use the inverse",
        },
        {
          kind: "short",
          id: "inequalities-p1-q03",
          question: "n is an integer. List all the values of n such that −6 ≤ 3n < 9.",
          answer: { type: "list", values: [-2, -1, 0, 1, 2], display: "−2, −1, 0, 1, 2" },
          solution: ["Divide all three parts by 3: −2 ≤ n < 3.", "−2 is included (≤); 3 is not (<).", "n = −2, −1, 0, 1, 2."],
          traps: [
            { spec: { type: "list", values: [-2, -1, 0, 1, 2, 3] }, feedback: "n < 3 means 3 itself is not allowed: 3 × 3 = 9, and 9 < 9 is false." },
            { spec: { type: "list", values: [-1, 0, 1, 2] }, feedback: "n ≥ −2 includes −2: 3 × (−2) = −6, and −6 ≤ −6 is true." },
          ],
          difficulty: "warmup",
          guideRef: "linear-inequalities",
          hints: ["Divide all three parts by 3.", "Look at each end: is it < or ≤?"],
          strategy: "Check the end points",
        },
        {
          kind: "short",
          id: "inequalities-p1-q04",
          question:
            "The region R is defined by\n\n    x < 2,   y ≥ −1,   y ≤ x + 3\n\nHere are five points: A(1, 0), B(2, 1), C(−1, 2), D(0, −1), E(−3, 1).\n\nHow many of these five points lie in R?",
          answer: { type: "number", value: 3 },
          solution: [
            "Test each point in all three inequalities.",
            "A(1, 0): 1 < 2 ✓, 0 ≥ −1 ✓, 0 ≤ 4 ✓ → in R.",
            "B(2, 1): 2 < 2 ✗ (strict) → not in R.",
            "C(−1, 2): −1 < 2 ✓, 2 ≥ −1 ✓, 2 ≤ 2 ✓ (on a solid line) → in R.",
            "D(0, −1): 0 < 2 ✓, −1 ≥ −1 ✓ (on a solid line), −1 ≤ 3 ✓ → in R.",
            "E(−3, 1): 1 ≤ −3 + 3 = 0 ✗ → not in R.",
            "So 3 points: A, C and D.",
          ],
          traps: [
            { spec: { type: "number", value: 4 }, feedback: "Check B(2, 1) carefully: x < 2 is strict, and 2 < 2 is false — B is on the dashed boundary, so not in R." },
            { spec: { type: "number", value: 1 }, feedback: "Points on a **solid** boundary (≤ or ≥) are in the region. C is on y = x + 3 and D is on y = −1 — both count." },
          ],
          commonError: "Treating a point on a boundary the wrong way: on a solid line (≤, ≥) it counts; on a dashed line (<, >) it does not.",
          difficulty: "warmup",
          guideRef: "graphical-regions",
          hints: ["A point is in R only if it satisfies **all three** inequalities.", "Watch the points that sit exactly on a boundary — is that boundary strict or not?"],
          strategy: "Test a point",
        },
        {
          kind: "short",
          id: "inequalities-p1-q05",
          question: "Solve 7 − 3x < 19.",
          answer: { type: "text", accept: ["x>-4", "-4<x"], display: "x > −4" },
          solution: [
            "Subtract 7: −3x < 12.",
            "Divide by −3 and **reverse** the sign: x > −4.",
            "Check with x = 0: 7 < 19 ✓ (0 is bigger than −4, so it should work — it does).",
          ],
          solutions: [
            { label: "Keep x positive", steps: ["Add 3x to both sides: 7 < 19 + 3x.", "Subtract 19: −12 < 3x.", "Divide by +3: −4 < x. No sign-flipping needed."] },
          ],
          traps: [
            { spec: { type: "text", accept: ["x<-4", "-4>x"] }, feedback: "Dividing by −3 reverses the inequality. Test x = −5: 7 + 15 = 22, which is not less than 19." },
            { spec: { type: "text", accept: ["x>4", "4<x", "x<4"] }, feedback: "12 ÷ (−3) = −4, not 4." },
          ],
          commonError: "Dividing by −3 without reversing the inequality sign.",
          difficulty: "core",
          guideRef: "linear-inequalities",
          hints: ["Get the x term on its own first.", "−3x < 12. You must divide by a negative — what does that do to the sign?", "Or avoid the issue: add 3x to both sides first."],
          strategy: "Check by substituting",
        },
        {
          kind: "short",
          id: "inequalities-p1-q06",
          question: "Solve −5 < 3 − 2x ≤ 11.\n\nWrite your answer as a single double inequality with the smaller number on the left.",
          answer: {
            type: "text",
            accept: ["-4<=x<4", "x>=-4andx<4", "x<4andx>=-4", "4>x>=-4", "{x:-4<=x<4}"],
            display: "−4 ≤ x < 4",
          },
          solution: [
            "Subtract 3 from all three parts: −8 < −2x ≤ 8.",
            "Divide all three parts by −2 and reverse **both** signs: 4 > x ≥ −4.",
            "Rewrite with the smaller number first: −4 ≤ x < 4.",
            "Check x = 0: 3 lies between −5 and 11 ✓. Check x = 4: 3 − 8 = −5, and −5 < −5 is false, so 4 is excluded ✓.",
          ],
          traps: [
            { spec: { type: "text", accept: ["-4<x<=4", "4>=x>-4"] }, feedback: "When you divide by −2 the signs flip, so the ≤ ends up at the −4 end: 4 > x ≥ −4, i.e. −4 ≤ x < 4." },
            { spec: { type: "text", accept: ["4<x<=-4", "-4>=x>4"] }, feedback: "No number can be bigger than 4 and less than −4. Reverse the signs when dividing by −2." },
          ],
          commonError: "Reversing only one of the two signs, or keeping the strict/inclusive ends in their original places.",
          difficulty: "core",
          guideRef: "linear-inequalities",
          hints: ["Do the same to all three parts. First, remove the 3.", "−8 < −2x ≤ 8. Divide every part by −2 — what happens to the signs?", "You get 4 > x ≥ −4. Now read it from left to right the other way."],
          strategy: "Check the end points",
        },
        {
          kind: "written",
          id: "inequalities-p1-q07",
          question:
            "Marcus solves the inequality 4 − 3x > 16 like this:\n\n    −3x > 12\n    x > −4\n\n(a) Explain the mistake Marcus has made.\n(b) Use a test value to show that his answer is wrong, and give the correct solution.",
          marks: 3,
          modelAnswer:
            "(a) In the second line he divided both sides by −3 but did not reverse the inequality sign. Multiplying or dividing an inequality by a negative number reverses it.\n\n(b) Take x = 0, which satisfies x > −4. Then 4 − 3(0) = 4, and 4 > 16 is false, so his answer includes values that don't work. Correct solution: −3x > 12 gives x < −4. (Check x = −5: 4 + 15 = 19 > 16 ✓.)",
          markScheme: [
            { point: "Identifies dividing by a negative (−3) without reversing the inequality sign", keywords: ["negative", "reverse", "flip", "-3", "sign"] },
            { point: "Uses a test value from his answer (e.g. x = 0) to show it fails", keywords: ["x = 0", "0", "4 > 16", "false", "doesn't work", "not true"] },
            { point: "Correct solution x < −4", keywords: ["x < -4", "x<-4", "-4 > x", "less than -4"] },
          ],
          commonError: "Just saying 'the sign is wrong' without saying why (dividing by a negative).",
          difficulty: "core",
          guideRef: "linear-inequalities",
          hints: ["Look at the step from −3x > 12 to x > −4. What did he divide by?", "Try x = 0 in the original inequality. Does it work? Is 0 > −4?"],
          strategy: "Spot the error",
        },
        {
          kind: "short",
          id: "inequalities-p1-q08",
          question:
            "The shaded region R is defined by\n\n    y ≥ 1,   x + y ≤ 6,   y ≤ 2x\n\nWork out the area of R. Give your answer as a decimal.",
          diagram: `__SVG_P1Q08__`,
          answer: { type: "number", value: 6.75, allowFraction: false, display: "6.75 square units" },
          solution: [
            "Find the vertices by solving pairs of boundary equations.",
            "y = 1 and y = 2x: x = 0.5 → (0.5, 1).",
            "y = 1 and x + y = 6: x = 5 → (5, 1).",
            "y = 2x and x + y = 6: 3x = 6 → (2, 4).",
            "Base along y = 1: 5 − 0.5 = 4.5. Height: 4 − 1 = 3.",
            "Area = {{1/2}} × 4.5 × 3 = 6.75.",
          ],
          traps: [
            { spec: { type: "number", value: 7.5 }, feedback: "Check the left vertex: y = 2x meets y = 1 at x = 0.5, not x = 0. So the base is 4.5, not 5." },
            { spec: { type: "number", value: 13.5 }, feedback: "A triangle's area is **half** of base × height." },
          ],
          commonError: "Reading the left-hand corner as (0, 1) or (1, 1) instead of solving y = 2x with y = 1.",
          difficulty: "core",
          guideRef: "graphical-regions",
          hints: ["R is a triangle. Find its three corners.", "Each corner is where two boundary lines meet — solve them simultaneously.", "The base lies along y = 1. How long is it, and how high is the top vertex above it?"],
          strategy: "Draw a diagram",
        },
        {
          kind: "short",
          id: "inequalities-p1-q09",
          question:
            "The diagram shows a dashed straight line through (0, 3) and (4, 0). The shaded region is below the line.\n\nWrite down the inequality that describes the shaded region. Give it in the form ax + by < c, where a, b and c are positive integers.",
          diagram: `__SVG_P1Q09__`,
          answer: {
            type: "text",
            accept: ["3x+4y<12", "4y+3x<12", "12>3x+4y", "12>4y+3x"],
            display: "3x + 4y < 12",
          },
          solution: [
            "Gradient = {{(0 - 3)/(4 - 0) = -3/4}}, y-intercept 3, so the line is {{y = -3/4 x + 3}}.",
            "Multiply by 4: 4y = −3x + 12, i.e. 3x + 4y = 12.",
            "Test the origin (shaded): 3(0) + 4(0) = 0 < 12 ✓, so the shaded side is 3x + 4y < 12.",
            "The line is dashed, so the inequality is strict (<, not ≤).",
          ],
          traps: [
            { spec: { type: "text", accept: ["3x+4y<=12", "4y+3x<=12"] }, feedback: "Right line, right side — but the boundary is **dashed**, so points on it are excluded. Use <, not ≤." },
            { spec: { type: "text", accept: ["3x+4y>12", "4y+3x>12"] }, feedback: "Test the origin, which is shaded: 0 < 12, so the region is 3x + 4y **<** 12." },
            { spec: { type: "text", accept: ["4x+3y<12", "3y+4x<12"] }, feedback: "Check with (4, 0): 4(4) + 3(0) = 16, not 12. The line is 3x + 4y = 12." },
          ],
          commonError: "Using ≤ for a dashed line, or getting the x and y coefficients the wrong way round.",
          difficulty: "core",
          guideRef: "graphical-regions",
          hints: ["Find the equation of the line first — gradient and intercept.", "{{y = -3/4 x + 3}}. Clear the fraction.", "Which side is shaded? Test (0, 0). Is the line solid or dashed?"],
          strategy: "Test a point",
        },
        {
          kind: "short",
          id: "inequalities-p1-q10",
          question: "Solve {{x^2 - 3x - 10 <= 0}}.",
          answer: {
            type: "text",
            accept: ["-2<=x<=5", "5>=x>=-2", "x>=-2andx<=5", "x<=5andx>=-2", "{x:-2<=x<=5}"],
            display: "−2 ≤ x ≤ 5",
          },
          solution: [
            "Critical values: (x − 5)(x + 2) = 0 → x = −2 or x = 5.",
            "{{y = x^2 - 3x - 10}} is ∪-shaped and is on or below the x-axis between the roots.",
            "The inequality is ≤, so the critical values are included: −2 ≤ x ≤ 5.",
          ],
          traps: [
            { spec: { type: "text", accept: ["-2<x<5", "5>x>-2"] }, feedback: "The inequality is ≤ 0, so x = −2 and x = 5 (where the expression equals 0) are included." },
            { spec: { type: "text", accept: ["x<=-2orx>=5", "x>=5orx<=-2"] }, feedback: "That's where the expression is ≥ 0. A ∪-shaped curve is below the axis **between** its roots." },
          ],
          difficulty: "core",
          guideRef: "quadratic-inequalities",
          hints: ["Find the critical values by solving {{x^2 - 3x - 10 = 0}}.", "Sketch the parabola. Where is it on or below the x-axis?"],
          strategy: "Draw a diagram",
        },
        {
          kind: "short",
          id: "inequalities-p1-q11",
          question: "Solve {{2x^2 + x - 6 > 0}}.",
          answer: {
            type: "text",
            accept: [
              "x<-2orx>1.5", "x>1.5orx<-2", "x<-2orx>3/2", "x>3/2orx<-2",
              "x<-2,x>1.5", "x<-2,x>3/2", "x>1.5,x<-2", "x>3/2,x<-2",
            ],
            display: "x < −2 or x > {{3/2}}",
          },
          solution: [
            "Factorise: a × c = −12; 4 and −3 multiply to −12 and add to 1.",
            "{{2x^2 + 4x - 3x - 6 = 2x(x + 2) - 3(x + 2) = (2x - 3)(x + 2)}}.",
            "Critical values: {{x = 3/2}} and x = −2.",
            "∪-shaped (positive {{x^2}} coefficient), so it is above the axis outside the roots.",
            "x < −2 or {{x > 3/2}}.",
          ],
          traps: [
            { spec: { type: "text", accept: ["-2<x<1.5", "-2<x<3/2"] }, feedback: "'> 0' means above the x-axis. For a ∪-shaped curve that's the two outside pieces." },
            { spec: { type: "text", accept: ["x<-2orx>3", "x>3orx<-2"] }, feedback: "2x − 3 = 0 gives {{x = 3/2}}, not 3." },
          ],
          commonError: "Solving 2x − 3 = 0 as x = 3 instead of {{x = 3/2}}.",
          difficulty: "core",
          guideRef: "quadratic-inequalities",
          hints: ["Factorise first. Try a × c = −12.", "(2x − 3)(x + 2). What are the critical values?", "Sketch it. '> 0' — which parts of the curve are above the axis?"],
          strategy: "Draw a diagram",
        },
        {
          kind: "written",
          id: "inequalities-p1-q12",
          question:
            "Wei Ling solves {{x^2 < 4x}} by dividing both sides by x to get x < 4.\n\n(a) Explain why dividing by x is not a valid step.\n(b) Solve {{x^2 < 4x}} correctly, showing your method.",
          marks: 4,
          modelAnswer:
            "(a) x might be negative (or zero). Dividing by a negative number reverses the inequality, and we can't divide by zero, so we don't know which way the sign should go. For example, x = −1 satisfies x < 4 but (−1)² = 1 is not less than 4(−1) = −4.\n\n(b) Rearrange: {{x^2 - 4x < 0}}, so x(x − 4) < 0. Critical values x = 0 and x = 4. The graph of y = x(x − 4) is ∪-shaped and below the x-axis between its roots, so 0 < x < 4.",
          markScheme: [
            { point: "x could be negative or zero, so dividing by x might reverse the inequality / is undefined", keywords: ["negative", "zero", "reverse", "flip", "don't know the sign"] },
            { point: "Rearranges to x² − 4x < 0 and factorises x(x − 4)", keywords: ["x^2 - 4x", "x(x - 4)", "x(x-4)", "rearrange"] },
            { point: "Critical values 0 and 4", keywords: ["0", "4", "critical"] },
            { point: "Correct solution 0 < x < 4", keywords: ["0 < x < 4", "0<x<4", "between 0 and 4"] },
          ],
          commonError: "Cancelling x from both sides, which loses the condition x > 0.",
          difficulty: "core",
          guideRef: "quadratic-inequalities",
          hints: ["Try x = −1 in Wei Ling's answer and in the original inequality.", "Bring everything to one side: {{x^2 - 4x < 0}}, then factorise.", "Sketch y = x(x − 4). Where is it below the axis?"],
          strategy: "Spot the error",
        },
        {
          kind: "short",
          id: "inequalities-p1-q13",
          question:
            "Siti bakes x trays of pineapple tarts and y trays of kaya puffs for a CCA fundraiser. Her constraints are\n\n    x ≥ 0,   y ≥ 0,   x + 2y ≤ 10,   3x + y ≤ 15\n\nShe makes a profit of $2 per tray of tarts and $3 per tray of puffs, so her profit is P = 2x + 3y dollars.\n\nFind the maximum possible profit, in dollars.",
          answer: { type: "number", value: 17, display: "$17" },
          solution: [
            "The feasible region is a quadrilateral. Its corners are (0, 0), (5, 0), (0, 5) and the point where x + 2y = 10 meets 3x + y = 15.",
            "From the first, x = 10 − 2y. Substitute: 3(10 − 2y) + y = 15 → 30 − 5y = 15 → y = 3, x = 4. Corner (4, 3).",
            "Evaluate P = 2x + 3y at each corner: (0, 0) → 0; (5, 0) → 10; (0, 5) → 15; (4, 3) → 8 + 9 = 17.",
            "The maximum profit is $17, with 4 trays of tarts and 3 trays of puffs.",
          ],
          traps: [
            { spec: { type: "number", value: 15 }, feedback: "(0, 5) gives 15, but check the corner where the two slanted lines cross: (4, 3) gives more." },
          ],
          commonError: "Only testing the corners on the axes and missing the corner where the two constraint lines cross.",
          difficulty: "challenge",
          guideRef: "graphical-regions",
          hints: [
            "Sketch the region. Where would a maximum of a straight-line expression like 2x + 3y happen?",
            "The maximum is at a corner of the region. List the corners.",
            "One corner needs simultaneous equations: x + 2y = 10 and 3x + y = 15.",
            "Evaluate 2x + 3y at all four corners and pick the biggest.",
          ],
          strategy: "Consider extremes",
        },
        {
          kind: "short",
          id: "inequalities-p1-q14",
          question:
            "The equation {{x^2 + kx + 9 = 0}} has **no real roots**.\n\nFind the set of possible values of k. Give your answer as an inequality in k.",
          answer: {
            type: "text",
            accept: ["-6<k<6", "6>k>-6", "k>-6andk<6", "k<6andk>-6", "{k:-6<k<6}"],
            display: "−6 < k < 6",
          },
          solution: [
            "No real roots means the discriminant is negative: {{b^2 - 4ac < 0}}.",
            "{{k^2 - 4(1)(9) < 0}}, so {{k^2 - 36 < 0}}.",
            "(k − 6)(k + 6) < 0: critical values ±6.",
            "The ∪-shaped graph of {{k^2 - 36}} is below the axis between the roots: −6 < k < 6.",
          ],
          traps: [
            { spec: { type: "text", accept: ["k<6", "6>k"] }, feedback: "{{k^2 < 36}} has negative solutions too: k = −7 gives 49, which is not less than 36, but k = −5 works. The answer is −6 < k < 6." },
            { spec: { type: "text", accept: ["k<-6ork>6", "k>6ork<-6"] }, feedback: "That's when there are two distinct real roots (discriminant > 0). No real roots needs the discriminant < 0." },
          ],
          commonError: "Writing k < ±6 or k < 6 — square-rooting an inequality loses the negative side.",
          difficulty: "challenge",
          guideRef: "quadratic-inequalities",
          hints: ["Which part of the quadratic formula tells you how many roots there are?", "No real roots: {{b^2 - 4ac < 0}}. Here a = 1, b = k, c = 9.", "{{k^2 < 36}} is a quadratic inequality in k. Solve it like any other."],
          strategy: "Use the discriminant",
        },
        {
          kind: "written",
          id: "inequalities-p1-q15",
          question: "Prove that {{x^2 - 6x + 10 > 0}} for all values of x.",
          marks: 3,
          modelAnswer:
            "Complete the square: {{x^2 - 6x + 10 = (x - 3)^2 - 9 + 10 = (x - 3)^2 + 1}}.\n\nA square is never negative, so {{(x - 3)^2 >= 0}} for every x.\n\nTherefore {{(x - 3)^2 + 1 >= 1 > 0}} for all x. (The minimum value is 1, when x = 3.)",
          markScheme: [
            { point: "Completes the square: (x − 3)² + 1", keywords: ["(x - 3)^2 + 1", "(x-3)^2+1", "(x-3)²+1", "complete the square"] },
            { point: "States that a square is always ≥ 0", keywords: ["square", ">= 0", "≥ 0", "never negative", "non-negative", "at least 0"] },
            { point: "Concludes the expression is ≥ 1, so always > 0", keywords: ["at least 1", ">= 1", "≥ 1", "minimum", "always positive", "> 0"] },
          ],
          solutions: [
            { label: "Discriminant", steps: ["{{b^2 - 4ac = 36 - 40 = -4 < 0}}, so the graph never meets the x-axis.", "The {{x^2}} coefficient is positive, so the ∪-shaped graph lies entirely above the axis: the expression is always positive."] },
          ],
          commonError: "Trying a few values of x and saying 'it works' — examples are not a proof.",
          difficulty: "challenge",
          guideRef: "quadratic-inequalities",
          hints: ["Testing values isn't proof. Can you rewrite the expression so its sign is obvious?", "Complete the square: {{x^2 - 6x = (x - 3)^2 - 9}}.", "What is the smallest a square can ever be?"],
          strategy: "Complete the square",
        },
      ],
    },
    {
      id: "inequalities-p2",
      title: "Practice Paper 2",
      questions: [
        {
          kind: "short",
          id: "inequalities-p2-q01",
          question: "Solve 4(x + 2) ≥ 2x − 6.",
          answer: { type: "text", accept: ["x>=-7", "-7<=x"], display: "x ≥ −7" },
          solution: ["Expand: 4x + 8 ≥ 2x − 6.", "Subtract 2x: 2x + 8 ≥ −6.", "Subtract 8: 2x ≥ −14.", "Divide by 2: x ≥ −7."],
          traps: [
            { spec: { type: "text", accept: ["x<=-7", "-7>=x"] }, feedback: "The answer is negative, but you divided by +2 — the sign stays the same way round." },
            { spec: { type: "text", accept: ["x>=-4", "-4<=x"] }, feedback: "Expand the bracket fully: 4(x + 2) = 4x + **8**." },
          ],
          commonError: "Reversing the sign because the answer is negative — only dividing by a negative reverses it.",
          difficulty: "warmup",
          guideRef: "linear-inequalities",
          hints: ["Expand the bracket first.", "Then collect x terms on the left and numbers on the right."],
          strategy: "Use the inverse",
        },
        {
          kind: "short",
          id: "inequalities-p2-q02",
          question: "Find the smallest integer n such that 3n > 14.",
          answer: { type: "number", value: 5 },
          solution: ["Divide by 3: {{n > 14/3 = 4 2/3}}.", "The smallest integer bigger than {{4 2/3}} is 5.", "Check: 3 × 5 = 15 > 14 ✓, and 3 × 4 = 12, which is not."],
          traps: [
            { spec: { type: "number", value: 4 }, feedback: "3 × 4 = 12, which is not greater than 14. n must be bigger than {{4 2/3}}." },
            { spec: { type: "number", value: 4.67, tolerance: 0.01 }, feedback: "n has to be an **integer**. Which whole number comes first after {{4 2/3}}?" },
          ],
          difficulty: "warmup",
          guideRef: "linear-inequalities",
          hints: ["Solve 3n > 14 first.", "{{n > 4 2/3}}. Which is the first integer above that?"],
          strategy: "Check by substituting",
        },
        {
          kind: "short",
          id: "inequalities-p2-q03",
          question: "Write down the inequality that describes the shaded region, using x.",
          diagram: `__SVG_P2Q03__`,
          answer: {
            type: "text",
            accept: ["-1<=x<3", "3>x>=-1", "x>=-1andx<3", "x<3andx>=-1", "{x:-1<=x<3}"],
            display: "−1 ≤ x < 3",
          },
          solution: [
            "The region is a vertical strip between the lines x = −1 and x = 3.",
            "x = −1 is solid, so −1 is included: x ≥ −1.",
            "x = 3 is dashed, so 3 is not included: x < 3.",
            "Together: −1 ≤ x < 3.",
          ],
          traps: [
            { spec: { type: "text", accept: ["-1<x<=3", "3>=x>-1"] }, feedback: "Solid line = included (≤), dashed line = not included (<). The solid line is at x = −1." },
            { spec: { type: "text", accept: ["-1<=y<3", "-1<y<3"] }, feedback: "These are vertical lines, so they have equations x = …. The inequality is about x." },
          ],
          commonError: "Mixing up x = … (vertical lines) with y = … (horizontal lines).",
          difficulty: "warmup",
          guideRef: "graphical-regions",
          hints: ["Vertical lines have equations x = a number.", "Which boundary is solid (≤) and which is dashed (<)?"],
          strategy: "Read the diagram",
        },
        {
          kind: "short",
          id: "inequalities-p2-q04",
          question: "Solve {{x^2 < 49}}.",
          answer: {
            type: "text",
            accept: ["-7<x<7", "7>x>-7", "x>-7andx<7", "x<7andx>-7", "{x:-7<x<7}"],
            display: "−7 < x < 7",
          },
          solution: [
            "Critical values: {{x^2 = 49}} → x = ±7.",
            "{{y = x^2 - 49}} is ∪-shaped, below the axis between −7 and 7.",
            "So −7 < x < 7.",
          ],
          traps: [
            { spec: { type: "text", accept: ["x<7", "7>x"] }, feedback: "Square-rooting loses the negative side. x = −10 gives 100, which is not less than 49 — so x < 7 can't be the whole story." },
            { spec: { type: "text", accept: ["x<-7orx>7", "x>7orx<-7"] }, feedback: "That's where {{x^2 > 49}}. Squares less than 49 come from numbers between −7 and 7." },
          ],
          commonError: "Writing x < ±7 or x < 7.",
          difficulty: "warmup",
          guideRef: "quadratic-inequalities",
          hints: ["Which numbers square to exactly 49?", "Try x = −8 and x = −6. Which works?"],
          strategy: "Check by substituting",
        },
        {
          kind: "short",
          id: "inequalities-p2-q05",
          question: "Solve {{(2x + 1)/3 - (x - 2)/2 <= 1}}.",
          answer: { type: "text", accept: ["x<=-2", "-2>=x"], display: "x ≤ −2" },
          solution: [
            "Multiply every term by 6 (the LCM of 3 and 2): 2(2x + 1) − 3(x − 2) ≤ 6.",
            "Expand carefully: 4x + 2 − 3x + 6 ≤ 6.",
            "Simplify: x + 8 ≤ 6.",
            "x ≤ −2.",
          ],
          traps: [
            { spec: { type: "text", accept: ["x<=10", "10>=x"] }, feedback: "Sign slip: −3(x − 2) = −3x **+ 6**, not −3x − 6." },
            { spec: { type: "text", accept: ["x<=3", "3>=x"] }, feedback: "When you multiply by 6, the right-hand side 1 must become 6 too." },
          ],
          commonError: "Expanding −3(x − 2) as −3x − 6.",
          difficulty: "core",
          guideRef: "linear-inequalities",
          hints: ["Clear the fractions: multiply every term by 6 — including the 1.", "2(2x + 1) − 3(x − 2) ≤ 6. Careful: minus times minus.", "x + 8 ≤ 6."],
          strategy: "Clear the fractions",
        },
        {
          kind: "short",
          id: "inequalities-p2-q06",
          question:
            "Priya has $50. She buys a book costing $12.80 and then spends the rest on notebooks costing $3.40 each.\n\nWhat is the greatest number of notebooks she can buy?",
          answer: { type: "number", value: 10 },
          solution: [
            "Let n be the number of notebooks: 12.80 + 3.40n ≤ 50.",
            "3.40n ≤ 37.20.",
            "n ≤ 37.20 ÷ 3.40 = 10.94….",
            "n must be a whole number, so the greatest is 10. Check: 12.80 + 34.00 = $46.80 ≤ $50 ✓; 11 notebooks would cost $50.20 in total ✗.",
          ],
          traps: [
            { spec: { type: "number", value: 11 }, feedback: "11 notebooks: 12.80 + 37.40 = $50.20 — more than $50. You must round **down** here." },
            { spec: { type: "number", value: 14 }, feedback: "Don't forget the book: she only has 50 − 12.80 = $37.20 left for notebooks." },
          ],
          commonError: "Rounding 10.94 up to 11 — with a spending limit you always round down.",
          difficulty: "core",
          guideRef: "linear-inequalities",
          hints: ["Write an inequality for the total cost with n notebooks.", "12.80 + 3.40n ≤ 50. Solve for n.", "n ≤ 10.94…. Should you round up or down?"],
          strategy: "Introduce a variable",
        },
        {
          kind: "written",
          id: "inequalities-p2-q07",
          question:
            "Hana says: \"If a > b, then {{a^2 > b^2}}.\"\n\n(a) Show that Hana is wrong.\n(b) State a condition on a and b that would make her statement true, and explain why.",
          marks: 3,
          modelAnswer:
            "(a) Counter-example: a = 1, b = −3. Then a > b, but {{a^2 = 1}} and {{b^2 = 9}}, so {{a^2 < b^2}}. One counter-example is enough to show the statement is false.\n\n(b) It is true when a and b are both positive (more precisely, a > b ≥ 0). Multiply a > b by the positive number a: {{a^2 > ab}}. Multiply a > b by b ≥ 0: {{ab >= b^2}}. So {{a^2 > ab >= b^2}}. Multiplying by a positive number keeps the inequality the same way round; with negatives this breaks down.",
          markScheme: [
            { point: "A valid counter-example with a > b but a² ≤ b² (e.g. a = 1, b = −3)", keywords: ["counter", "-3", "negative", "a = 1", "1 < 9", "example"] },
            { point: "Condition: both non-negative / both positive (a > b ≥ 0)", keywords: ["positive", "both positive", ">= 0", "≥ 0", "non-negative"] },
            { point: "Reason: multiplying an inequality by a positive number keeps the sign (a² > ab ≥ b²) or equivalent", keywords: ["multiply", "a^2 > ab", "positive number", "keeps", "same way"] },
          ],
          commonError: "Giving examples where it works (e.g. a = 5, b = 2) — that can't prove the statement wrong.",
          difficulty: "core",
          guideRef: "linear-inequalities",
          hints: ["To show a statement is false you need just one example where it fails.", "Try making b negative.", "Why does it work for positive numbers? Multiply a > b by a."],
          strategy: "Look for a counter-example",
        },
        {
          kind: "short",
          id: "inequalities-p2-q08",
          question:
            "The shaded region R is defined by\n\n    y ≥ 1,   y < x,   x + 2y ≤ 10\n\nHow many points with integer coordinates lie in R? Points on a solid boundary count; points on the dashed boundary do not.",
          diagram: `__SVG_P2Q08__`,
          answer: { type: "number", value: 12 },
          solution: [
            "Work row by row (fix y, find the allowed x).",
            "y = 1: need x > 1 and x ≤ 10 − 2 = 8 → x = 2, 3, …, 8 → 7 points.",
            "y = 2: need x > 2 and x ≤ 6 → x = 3, 4, 5, 6 → 4 points.",
            "y = 3: need x > 3 and x ≤ 4 → x = 4 → 1 point.",
            "y = 4: need x > 4 and x ≤ 2 → none.",
            "Total 7 + 4 + 1 = 12.",
          ],
          traps: [
            { spec: { type: "number", value: 15 }, feedback: "y = x is dashed (y < x), so points like (1, 1), (2, 2) and (3, 3) on it are not in R." },
          ],
          commonError: "Counting points on the dashed line y = x.",
          difficulty: "core",
          guideRef: "graphical-regions",
          hints: ["Go one row at a time: for y = 1, which integer x values are allowed?", "For each y you need x > y and x ≤ 10 − 2y.", "Stop when there are no x values left."],
          strategy: "Be systematic",
        },
        {
          kind: "written",
          id: "inequalities-p2-q09",
          question:
            "The region S is defined by y < 2x − 4 and x + y ≥ 5.\n\nRavi says the point (3, 2) lies in S. Is he correct? Show your working and explain your answer.",
          marks: 3,
          modelAnswer:
            "Test (3, 2) in both inequalities.\n\ny < 2x − 4: 2x − 4 = 6 − 4 = 2, and 2 < 2 is **false**.\n\nx + y ≥ 5: 3 + 2 = 5, and 5 ≥ 5 is true.\n\nThe point satisfies the second inequality but not the first. It lies exactly on the line y = 2x − 4, which is a dashed (strict) boundary, so it is **not** in S. Ravi is wrong.",
          markScheme: [
            { point: "Tests the first inequality: 2 < 2 is false", keywords: ["2 < 2", "2<2", "false", "not less than", "6 - 4"] },
            { point: "Tests the second inequality: 5 ≥ 5 is true", keywords: ["5 >= 5", "5 ≥ 5", "3 + 2", "true"] },
            { point: "Concludes not in S because it is on the strict (dashed) boundary y = 2x − 4", keywords: ["not", "wrong", "dashed", "strict", "on the line", "boundary"] },
          ],
          commonError: "Treating < as ≤ and concluding the point is in S because it is 'on the line'.",
          difficulty: "core",
          guideRef: "graphical-regions",
          hints: ["Substitute x = 3, y = 2 into each inequality in turn.", "A point must satisfy **both** inequalities to be in S.", "What happens when the two sides are equal and the sign is strict?"],
          strategy: "Test a point",
        },
        {
          kind: "short",
          id: "inequalities-p2-q10",
          question: "Solve {{x^2 + 4x > 12}}.",
          answer: {
            type: "text",
            accept: ["x<-6orx>2", "x>2orx<-6", "x<-6,x>2", "x>2,x<-6", "{x:x<-6}u{x:x>2}"],
            display: "x < −6 or x > 2",
          },
          solution: [
            "Rearrange so one side is 0: {{x^2 + 4x - 12 > 0}}.",
            "Factorise: (x + 6)(x − 2) > 0. Critical values −6 and 2.",
            "∪-shaped, above the axis outside the roots: x < −6 or x > 2.",
          ],
          traps: [
            { spec: { type: "text", accept: ["-6<x<2", "2>x>-6"] }, feedback: "'> 0' means above the axis. For a ∪-shaped curve that's outside the roots, not between them." },
            { spec: { type: "text", accept: ["x<-2orx>6", "x>6orx<-2"] }, feedback: "Check the factorisation: (x + 6)(x − 2) = {{x^2 + 4x - 12}} ✓, so the critical values are −6 and 2." },
          ],
          commonError: "Trying to factorise x(x + 4) > 12 — you need 0 on one side before the factors tell you anything.",
          difficulty: "core",
          guideRef: "quadratic-inequalities",
          hints: ["Get 0 on one side first.", "{{x^2 + 4x - 12 > 0}}. Factorise.", "Sketch the curve through the critical values. Where is it above the axis?"],
          strategy: "Rearrange to = 0 first",
        },
        {
          kind: "short",
          id: "inequalities-p2-q11",
          question: "Solve {{3x^2 - 10x + 3 <= 0}}.",
          answer: {
            type: "text",
            accept: ["1/3<=x<=3", "3>=x>=1/3", "x>=1/3andx<=3", "x<=3andx>=1/3", "{x:1/3<=x<=3}"],
            display: "{{1/3}} ≤ x ≤ 3",
          },
          solution: [
            "a × c = 9; −9 and −1 multiply to 9 and add to −10.",
            "{{3x^2 - 9x - x + 3 = 3x(x - 3) - (x - 3) = (3x - 1)(x - 3)}}.",
            "Critical values {{x = 1/3}} and x = 3.",
            "∪-shaped, on or below the axis between the roots: {{1/3 <= x <= 3}}.",
          ],
          traps: [
            { spec: { type: "text", accept: ["1<=x<=3", "3>=x>=1"] }, feedback: "3x − 1 = 0 gives {{x = 1/3}}, not 1." },
            { spec: { type: "text", accept: ["x<=1/3orx>=3", "x>=3orx<=1/3"] }, feedback: "That's where the expression is ≥ 0. '≤ 0' is the part between the roots." },
          ],
          difficulty: "core",
          guideRef: "quadratic-inequalities",
          hints: ["Factorise: a × c = 9. Which pair adds to −10?", "(3x − 1)(x − 3). Critical values?", "'≤ 0' — between or outside the roots?"],
          strategy: "Draw a diagram",
        },
        {
          kind: "short",
          id: "inequalities-p2-q12",
          question: "Solve {{12 + x - x^2 > 0}}.",
          answer: {
            type: "text",
            accept: ["-3<x<4", "4>x>-3", "x>-3andx<4", "x<4andx>-3", "{x:-3<x<4}"],
            display: "−3 < x < 4",
          },
          solution: [
            "Multiply by −1 to make the {{x^2}} term positive — and **reverse the sign**: {{x^2 - x - 12 < 0}}.",
            "Factorise: (x − 4)(x + 3) < 0. Critical values −3 and 4.",
            "∪-shaped, below the axis between the roots: −3 < x < 4.",
          ],
          solutions: [
            { label: "Sketch the ∩ directly", steps: ["{{y = 12 + x - x^2}} has a negative {{x^2}} term, so it is ∩-shaped.", "It crosses the axis where (4 − x)(3 + x) = 0: x = −3 and x = 4.", "A ∩ is above the axis **between** its roots, so −3 < x < 4."] },
          ],
          traps: [
            { spec: { type: "text", accept: ["x<-3orx>4", "x>4orx<-3"] }, feedback: "This curve is ∩-shaped (negative {{x^2}}), so it is positive **between** the roots. Or: if you multiplied by −1, did you reverse the sign?" },
          ],
          commonError: "Assuming every quadratic is ∪-shaped, or multiplying by −1 without reversing the inequality.",
          difficulty: "core",
          guideRef: "quadratic-inequalities",
          hints: ["What shape is the graph when the {{x^2}} term is negative?", "Either sketch the ∩ directly, or multiply through by −1 (and reverse the sign).", "Critical values: solve {{x^2 - x - 12 = 0}}."],
          strategy: "Draw a diagram",
        },
        {
          kind: "short",
          id: "inequalities-p2-q13",
          question:
            "Find all the integers x that satisfy **both** {{x^2 < 3x + 18}} and 2x + 5 > 8.",
          answer: { type: "list", values: [2, 3, 4, 5], display: "2, 3, 4, 5" },
          solution: [
            "First: {{x^2 - 3x - 18 < 0}} → (x − 6)(x + 3) < 0 → −3 < x < 6.",
            "Second: 2x > 3 → x > 1.5.",
            "Both: 1.5 < x < 6.",
            "Integers: 2, 3, 4, 5.",
          ],
          traps: [
            { spec: { type: "list", values: [2, 3, 4, 5, 6] }, feedback: "x = 6 gives 36 < 36, which is false. The quadratic inequality is strict." },
            { spec: { type: "list", values: [-2, -1, 0, 1, 2, 3, 4, 5] }, feedback: "That's just the quadratic inequality. x must satisfy 2x + 5 > 8 as well, so x > 1.5." },
          ],
          commonError: "Solving each inequality but not combining them — the answer is the overlap.",
          difficulty: "challenge",
          guideRef: "quadratic-inequalities",
          hints: ["Solve each inequality separately.", "Rearrange the first to {{x^2 - 3x - 18 < 0}} and factorise.", "Draw both solution sets on one number line. Where do they overlap?"],
          strategy: "Draw a number line",
        },
        {
          kind: "written",
          id: "inequalities-p2-q14",
          question:
            "Zara solves {{1/x < 2}} by multiplying both sides by x to get 1 < 2x, so {{x > 1/2}}.\n\n(a) Explain why her method has lost some solutions.\n(b) Find the complete solution of {{1/x < 2}}.",
          marks: 4,
          modelAnswer:
            "(a) Multiplying by x is only safe if x is positive. If x is negative the inequality must be reversed. For example x = −1: {{1/(-1) = -1 < 2}} ✓, but −1 is not greater than {{1/2}} — so her answer misses it.\n\n(b) Case 1, x > 0: multiply by x (sign unchanged): 1 < 2x, so {{x > 1/2}}.\nCase 2, x < 0: multiply by x (reverse): 1 > 2x, so {{x < 1/2}} — which is true for every negative x.\n(x = 0 is impossible: {{1/0}} is undefined.)\n\nComplete solution: x < 0 or {{x > 1/2}}.",
          markScheme: [
            { point: "Multiplying by x is not safe because x could be negative (sign would reverse)", keywords: ["negative", "reverse", "flip", "sign of x"] },
            { point: "Shows a negative value such as x = −1 works in the original", keywords: ["-1", "negative", "works", "1/x is negative"] },
            { point: "Splits into cases x > 0 and x < 0 (or uses a sketch of y = 1/x)", keywords: ["case", "x > 0", "x < 0", "graph", "sketch"] },
            { point: "Complete solution x < 0 or x > 1/2", keywords: ["x < 0", "x<0", "x > 1/2", "x>1/2", "0.5"] },
          ],
          solutions: [
            { label: "Multiply by x² (always positive)", steps: ["{{x^2 > 0}} for x ≠ 0, so multiplying by {{x^2}} keeps the sign: {{x < 2x^2}}.", "{{2x^2 - x > 0}} → x(2x − 1) > 0.", "Critical values 0 and {{1/2}}; ∪-shaped, positive outside: x < 0 or {{x > 1/2}}."] },
          ],
          commonError: "Multiplying an inequality by an unknown without knowing its sign.",
          difficulty: "challenge",
          guideRef: "linear-inequalities",
          hints: ["Is {{1/x < 2}} true when x = −1?", "What happens to an inequality when you multiply by a negative number?", "Split into two cases, x > 0 and x < 0. Or multiply both sides by {{x^2}}, which is always positive."],
          strategy: "Split into cases",
        },
        {
          kind: "short",
          id: "inequalities-p2-q15",
          question:
            "k is a positive constant. The region defined by\n\n    y ≥ 0,   y ≤ x,   x + y ≤ k\n\nhas area 16 square units. Find k.",
          answer: { type: "number", value: 8 },
          solution: [
            "The region is a triangle. Corners: (0, 0); where x + y = k meets y = 0: (k, 0); where it meets y = x: {{(k/2, k/2)}}.",
            "Base along the x-axis = k; height = {{k/2}}.",
            "Area = {{1/2 * k * k/2 = k^2/4}}.",
            "{{k^2/4 = 16}} → {{k^2 = 64}} → k = 8 (k is positive).",
          ],
          traps: [
            { spec: { type: "number", value: 4 }, feedback: "Check the height: the top corner is at {{(k/2, k/2)}}, so the area is {{k^2/4}}, not {{k^2}}." },
            { spec: { type: "number", value: 5.66, tolerance: 0.01 }, feedback: "The height is {{k/2}}, not k: area = {{1/2 * k * k/2 = k^2/4}}." },
          ],
          commonError: "Taking the height of the triangle as k instead of {{k/2}}.",
          difficulty: "challenge",
          guideRef: "graphical-regions",
          hints: ["Sketch the three boundary lines for, say, k = 4.", "Find the three corners in terms of k.", "The top corner is where y = x meets x + y = k. Then area = {{1/2}} × base × height."],
          strategy: "Introduce a variable",
        },
      ],
    },
  ],

  // =========================================================================
  // Challenge problems — grade 9 / H+ / olympiad flavour
  // =========================================================================
  challenge: [
    {
      kind: "short",
      id: "inequalities-ch-q01",
      question:
        "a and b are real numbers with −3 ≤ a ≤ 2 and −4 ≤ b ≤ 1.\n\nFind the least possible value of ab and the greatest possible value of ab. Give the least value first.",
      answer: { type: "list", values: [-8, 12], ordered: true, display: "least −8, greatest 12" },
      solution: [
        "For a fixed b, ab is a straight-line function of a, so its extreme values happen at the ends a = −3 or a = 2. The same goes for b. So check the four corner products.",
        "(−3)(−4) = 12, (−3)(1) = −3, (2)(−4) = −8, (2)(1) = 2.",
        "Least −8, greatest 12.",
      ],
      traps: [
        { spec: { type: "list", values: [-6, 2], ordered: true }, feedback: "You may have multiplied the lower limits and the upper limits only (or similar). Try all four corner combinations — two negatives make a large positive." },
        { spec: { type: "list", values: [-8, 2], ordered: true }, feedback: "The least value is right. For the greatest, remember (−3) × (−4) is positive." },
      ],
      commonError: "Assuming the greatest product comes from the two largest values (2 × 1 = 2).",
      difficulty: "challenge",
      guideRef: "linear-inequalities",
      hints: [
        "Inequalities can't just be multiplied together when negatives are involved. Think about extremes instead.",
        "If b is fixed, where is ab largest — in the middle of the range of a, or at an end?",
        "Only the four 'corner' combinations of end values matter.",
        "Work out all four products.",
      ],
      strategy: "Consider extremes",
    },
    {
      kind: "short",
      id: "inequalities-ch-q02",
      question: "The solution of the inequality ax + 7 > 2x − 5 is x < 4.\n\nFind the value of the constant a.",
      answer: { type: "number", value: -1 },
      solution: [
        "Rearrange: ax − 2x > −12, i.e. (a − 2)x > −12.",
        "The answer is x < 4 — the sign has reversed, so we must have divided by a **negative** number: a − 2 < 0.",
        "Then {{x < -12/(a - 2)}}, so {{-12/(a - 2) = 4}}.",
        "a − 2 = −3, so a = −1.",
        "Check: −x + 7 > 2x − 5 → 12 > 3x → x < 4 ✓.",
      ],
      traps: [
        { spec: { type: "number", value: -5 }, feedback: "Check your answer: with a = −5, −5x + 7 > 2x − 5 gives 12 > 7x, so {{x < 12/7}}. Set {{-12/(a - 2) = 4}} carefully." },
        { spec: { type: "number", value: 5 }, feedback: "With a = 5, (a − 2) = 3 is positive, which would give x > −4. The sign reversed, so a − 2 must be negative." },
      ],
      commonError: "Ignoring the fact that the direction of the answer (x < 4) tells you the coefficient was negative.",
      difficulty: "challenge",
      guideRef: "linear-inequalities",
      hints: [
        "Collect the x terms: what is the coefficient of x?",
        "(a − 2)x > −12. The answer has '<'. What must be true about a − 2?",
        "a − 2 is negative, and dividing gives {{x < -12/(a - 2)}}. Set that boundary equal to 4.",
      ],
      strategy: "Work backwards",
    },
    {
      kind: "short",
      id: "inequalities-ch-q03",
      question:
        "The sum of three consecutive **odd** integers is greater than 100 but less than 120.\n\nFind all the possible values of the **smallest** of the three integers.",
      answer: { type: "list", values: [33, 35, 37], display: "33, 35, 37" },
      solution: [
        "Let the middle one be m (odd). The three are m − 2, m, m + 2, with sum 3m.",
        "100 < 3m < 120 → 33.3… < m < 40.",
        "Odd values of m: 35, 37, 39.",
        "Smallest of the three = m − 2: 33, 35, 37.",
        "Check: 33 + 35 + 37 = 105 ✓; 37 + 39 + 41 = 117 ✓; 31 + 33 + 35 = 99 ✗; 39 + 41 + 43 = 123 ✗.",
      ],
      solutions: [
        { label: "Smallest as the variable", steps: ["Let the smallest be s: s + (s + 2) + (s + 4) = 3s + 6.", "100 < 3s + 6 < 120 → 94 < 3s < 114 → 31.3… < s < 38.", "Odd s: 33, 35, 37."] },
      ],
      traps: [
        { spec: { type: "list", values: [35, 37, 39] }, feedback: "Those are the possible **middle** numbers. The question asks for the smallest of the three." },
      ],
      commonError: "Forgetting that the integers must be odd, or answering with the middle value.",
      difficulty: "challenge",
      guideRef: "linear-inequalities",
      hints: [
        "Introduce a variable. Choosing the middle number makes the algebra neat.",
        "m − 2, m, m + 2 add up to 3m. Write a double inequality.",
        "33.3… < m < 40 and m is odd. Then subtract 2.",
      ],
      strategy: "Introduce a variable",
    },
    {
      kind: "short",
      id: "inequalities-ch-q04",
      question:
        "Ethan runs a hawker stall. Each day he makes x trays of kueh and y trays of vegetable curry puffs, where x and y are whole numbers and\n\n    2x + y ≤ 10   (oven hours)\n    x + 3y ≤ 12   (preparation hours)\n\nHis profit is $30 per tray of kueh and $40 per tray of curry puffs.\n\nFind his maximum possible daily profit, in dollars.",
      answer: { type: "number", value: 210, display: "$210" },
      solution: [
        "Profit P = 30x + 40y. Corners of the region: (0, 0), (5, 0), (0, 4) and where 2x + y = 10 meets x + 3y = 12.",
        "Solve: y = 10 − 2x → x + 30 − 6x = 12 → x = 3.6, y = 2.8. At this corner P = 108 + 112 = 220 — but x and y must be whole numbers!",
        "Check whole-number points near (3.6, 2.8): (3, 3): 2(3) + 3 = 9 ≤ 10 ✓, 3 + 9 = 12 ≤ 12 ✓ → P = 90 + 120 = 210.",
        "(4, 2): 10 ≤ 10 ✓, 10 ≤ 12 ✓ → P = 120 + 80 = 200. (4, 3) and (3, 4) break a constraint.",
        "Other corners: (5, 0) → 150; (0, 4) → 160.",
        "Any point with P > 210 needs 3x + 4y ≥ 22, and checking the few candidates shows none is feasible. Maximum profit $210 at (3, 3).",
      ],
      traps: [
        { spec: { type: "number", value: 220 }, feedback: "$220 happens at (3.6, 2.8) — but Ethan can't make 3.6 trays. Search the whole-number points near that corner." },
        { spec: { type: "number", value: 200 }, feedback: "(4, 2) is allowed, but there is a better whole-number point nearby. Try (3, 3)." },
      ],
      commonError: "Rounding the corner (3.6, 2.8) to (4, 3), which breaks the oven constraint (2 × 4 + 3 = 11 > 10).",
      difficulty: "challenge",
      guideRef: "graphical-regions",
      hints: [
        "Sketch the region. Where does a linear profit like 30x + 40y reach its maximum?",
        "Find the corner where the two slanted lines meet.",
        "That corner isn't a whole-number point. You can't just round it — check the constraints.",
        "Test the whole-number points closest to (3.6, 2.8): (3, 2), (3, 3), (4, 2), (4, 3)…",
      ],
      strategy: "Consider extremes",
    },
    {
      kind: "short",
      id: "inequalities-ch-q05",
      question:
        "The region R is defined by {{y >= x^2}} and y ≤ x + 2.\n\nHow many points with integer coordinates lie in R (including its boundary)?",
      answer: { type: "number", value: 8 },
      solution: [
        "The curve and the line meet where {{x^2 = x + 2}}: (x − 2)(x + 1) = 0, so x = −1 or x = 2.",
        "So the region only exists for −1 ≤ x ≤ 2 (that's the quadratic inequality {{x^2 <= x + 2}}).",
        "x = −1: 1 ≤ y ≤ 1 → 1 point.",
        "x = 0: 0 ≤ y ≤ 2 → 3 points.",
        "x = 1: 1 ≤ y ≤ 3 → 3 points.",
        "x = 2: 4 ≤ y ≤ 4 → 1 point.",
        "Total 1 + 3 + 3 + 1 = 8.",
      ],
      traps: [
        { spec: { type: "number", value: 6 }, feedback: "Both boundaries are included (≥ and ≤). Don't forget the two points where the curve meets the line: (−1, 1) and (2, 4)." },
      ],
      commonError: "Missing the corner points (−1, 1) and (2, 4) where the curve and line cross.",
      difficulty: "challenge",
      guideRef: "graphical-regions",
      hints: [
        "Sketch {{y = x^2}} and y = x + 2. Where do they meet?",
        "Between which x values is the line above the curve?",
        "For each integer x in that range, y runs from {{x^2}} up to x + 2. Count.",
      ],
      strategy: "Draw a diagram",
    },
    {
      kind: "short",
      id: "inequalities-ch-q06",
      question:
        "The line y = kx − 1 does **not** meet the curve {{y = x^2 + 3}}.\n\nFind the set of possible values of k. Give your answer as an inequality in k.",
      answer: {
        type: "text",
        accept: ["-4<k<4", "4>k>-4", "k>-4andk<4", "k<4andk>-4", "{k:-4<k<4}"],
        display: "−4 < k < 4",
      },
      solution: [
        "Where they meet: {{x^2 + 3 = kx - 1}}, i.e. {{x^2 - kx + 4 = 0}}.",
        "No intersection means no real roots: discriminant < 0.",
        "{{(-k)^2 - 4(1)(4) < 0}} → {{k^2 < 16}}.",
        "−4 < k < 4.",
      ],
      traps: [
        { spec: { type: "text", accept: ["k<4", "4>k"] }, feedback: "{{k^2 < 16}} has negative solutions too: e.g. k = −2 gives 4 < 16. The answer is −4 < k < 4." },
        { spec: { type: "text", accept: ["k<-4ork>4", "k>4ork<-4"] }, feedback: "That's when the line crosses the curve twice. 'Does not meet' means the discriminant is negative." },
      ],
      commonError: "Writing k < 4 (forgetting the negative side) or using the wrong sign of the discriminant.",
      difficulty: "challenge",
      guideRef: "quadratic-inequalities",
      hints: [
        "Set the two expressions for y equal to each other.",
        "You get a quadratic in x. What does 'no intersection' say about its roots?",
        "Discriminant < 0 gives a quadratic inequality in k.",
      ],
      strategy: "Use the discriminant",
    },
    {
      kind: "short",
      id: "inequalities-ch-q07",
      question: "Solve {{x^3 > 4x}}.",
      answer: {
        type: "text",
        accept: [
          "-2<x<0orx>2", "x>2or-2<x<0", "-2<x<0,x>2", "x>2,-2<x<0",
          "{x:-2<x<0}u{x:x>2}",
        ],
        display: "−2 < x < 0 or x > 2",
      },
      solution: [
        "Don't divide by x (its sign is unknown). Rearrange: {{x^3 - 4x > 0}}.",
        "Factorise: x(x − 2)(x + 2) > 0. Critical values −2, 0, 2.",
        "Sign table: for x < −2 all three factors are negative → product negative. For −2 < x < 0: two negatives → positive. For 0 < x < 2: one negative → negative. For x > 2: all positive → positive.",
        "So −2 < x < 0 or x > 2.",
      ],
      solutions: [
        { label: "Sketch the cubic", steps: ["{{y = x^3 - 4x}} is a positive cubic crossing the axis at −2, 0 and 2.", "It rises from below, crosses at −2 (goes above), crosses at 0 (goes below), crosses at 2 (goes above for good).", "Above the axis: −2 < x < 0 or x > 2."] },
      ],
      traps: [
        { spec: { type: "text", accept: ["x<-2orx>2", "x>2orx<-2"] }, feedback: "That's the answer to {{x^2 > 4}} — you divided by x. If x is negative, dividing reverses the sign. Test x = −1: −1 > −4 ✓, so −1 is a solution." },
        { spec: { type: "text", accept: ["x>2", "2<x"] }, feedback: "Test x = −1: (−1)³ = −1 and 4(−1) = −4, and −1 > −4 ✓. There are negative solutions too." },
      ],
      commonError: "Dividing both sides by x — that throws away (or mangles) the negative solutions.",
      difficulty: "challenge",
      guideRef: "quadratic-inequalities",
      hints: [
        "Is x = −1 a solution? So can you safely divide by x?",
        "Bring everything to one side and factorise completely.",
        "x(x − 2)(x + 2): three critical values split the number line into four intervals. What is the sign of the product in each?",
      ],
      strategy: "Split into cases",
    },
    {
      kind: "short",
      id: "inequalities-ch-q08",
      question:
        "A rectangle has length (x + 3) cm and width (x − 1) cm. Its area is at most 32 cm² and its perimeter is at least 12 cm.\n\nFind the range of possible values of x. Give your answer as a double inequality.",
      answer: {
        type: "text",
        accept: ["2<=x<=5", "5>=x>=2", "x>=2andx<=5", "x<=5andx>=2", "{x:2<=x<=5}"],
        display: "2 ≤ x ≤ 5",
      },
      solution: [
        "Area: (x + 3)(x − 1) ≤ 32 → {{x^2 + 2x - 3 <= 32}} → {{x^2 + 2x - 35 <= 0}} → (x + 7)(x − 5) ≤ 0 → −7 ≤ x ≤ 5.",
        "Perimeter: 2(x + 3) + 2(x − 1) = 4x + 4 ≥ 12 → x ≥ 2.",
        "Width must be positive: x − 1 > 0 → x > 1 (already covered by x ≥ 2).",
        "Combine: 2 ≤ x ≤ 5.",
      ],
      traps: [
        { spec: { type: "text", accept: ["-7<=x<=5", "5>=x>=-7"] }, feedback: "That's only the area condition. A length can't be negative, and the perimeter condition gives x ≥ 2." },
        { spec: { type: "text", accept: ["1<x<=5", "5>=x>1"] }, feedback: "Don't forget the perimeter condition: 4x + 4 ≥ 12 gives x ≥ 2." },
      ],
      commonError: "Solving the quadratic inequality and forgetting the real-world restrictions (positive lengths, the perimeter).",
      difficulty: "challenge",
      guideRef: "quadratic-inequalities",
      hints: [
        "Write one inequality for the area and one for the perimeter.",
        "The area gives a quadratic inequality: rearrange and factorise.",
        "Don't forget that a width must be positive. Then combine everything on a number line.",
      ],
      strategy: "Draw a number line",
    },
    {
      kind: "short",
      id: "inequalities-ch-q09",
      question:
        "Find the sum of all the integers x that satisfy both {{x^2 - 10x + 16 <= 0}} and {{x^2 > 20}}.",
      answer: { type: "number", value: 26 },
      solution: [
        "First: (x − 2)(x − 8) ≤ 0 → 2 ≤ x ≤ 8.",
        "Second: {{x^2 > 20}} → {{x < -sqrt(20)}} or {{x > sqrt(20)}}, where {{sqrt(20) = 4.47...}}",
        "Overlap: 4.47… < x ≤ 8, so the integers are 5, 6, 7, 8.",
        "Sum = 5 + 6 + 7 + 8 = 26.",
      ],
      traps: [
        { spec: { type: "number", value: 35 }, feedback: "2 + 3 + … + 8 = 35 uses only the first inequality. {{x^2 > 20}} rules out 2, 3 and 4 (4² = 16)." },
        { spec: { type: "number", value: 30 }, feedback: "4² = 16, which is not greater than 20, so 4 is not allowed." },
      ],
      commonError: "Including 4 (16 > 20 is false) or only using one of the two inequalities.",
      difficulty: "challenge",
      guideRef: "quadratic-inequalities",
      hints: [
        "Solve each inequality separately.",
        "The first gives a closed interval. The second removes the integers whose square is 20 or less.",
        "Which integers from 2 to 8 have squares bigger than 20?",
      ],
      strategy: "Draw a number line",
    },
    {
      kind: "short",
      id: "inequalities-ch-q10",
      question: "x is a positive real number. Find the minimum possible value of {{x + 9/x}}.",
      answer: { type: "number", value: 6 },
      solution: [
        "Claim: {{x + 9/x >= 6}} for all x > 0.",
        "Multiply by x (positive, so the sign stays): {{x^2 + 9 >= 6x}}, i.e. {{x^2 - 6x + 9 >= 0}}.",
        "That is {{(x - 3)^2 >= 0}}, which is always true.",
        "Equality when x = 3: {{3 + 9/3 = 6}}. So the minimum is 6.",
      ],
      solutions: [
        { label: "Perfect square of roots", steps: ["{{x + 9/x - 6 = (sqrt(x) - 3/sqrt(x))^2}} — expand to check: {{x - 6 + 9/x}}.", "A square is ≥ 0, so {{x + 9/x >= 6}}, with equality when {{sqrt(x) = 3/sqrt(x)}}, i.e. x = 3."] },
        { label: "Discriminant", steps: ["Suppose {{x + 9/x = m}}. Then {{x^2 - mx + 9 = 0}} must have a real root.", "Discriminant {{m^2 - 36 >= 0}}, so m ≥ 6 (m is positive). Smallest m = 6."] },
      ],
      traps: [
        { spec: { type: "number", value: 10 }, feedback: "x = 1 gives 10, but try x = 2 (6.5) and x = 3 (6). Can you go lower than 6? Prove it can't." },
      ],
      commonError: "Trying x = 1 (or a few values) and guessing — the minimum needs an argument.",
      difficulty: "challenge",
      guideRef: "quadratic-inequalities",
      hints: [
        "Try x = 1, 2, 3, 4, 5. Which gives the smallest value?",
        "It looks like 6 at x = 3. To prove nothing is smaller, show {{x + 9/x >= 6}}.",
        "Multiply by x (positive) and move everything to one side.",
        "You get {{x^2 - 6x + 9 >= 0}}. Recognise it?",
      ],
      strategy: "Try small cases, then prove",
    },
  ],
};
