import type { TopicPractice } from "../../types.ts";

// ---------------------------------------------------------------------------
// Diagrams (drawn to scale from the data in the questions)
// ---------------------------------------------------------------------------

// p1-q06: AB = 8 cm vertical, right angle at B; D and C on the line through B.
// Scale 22 px per cm: BD = 6.25 cm, BC = 13.31 cm.
const SHARED_SIDE = `<svg viewBox="0 0 460 300" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Triangle ABC with a right angle at B. AB is vertical and 8 cm long. D lies on CB between C and B. Angle ACB is 31 degrees and angle ADB is 52 degrees."><rect x="0" y="0" width="460" height="300" fill="#ffffff"/><polygon points="107,260 400,260 400,84" fill="#e0e7ff" stroke="none"/><line x1="107" y1="260" x2="400" y2="260" stroke="#1f2937" stroke-width="2"/><line x1="400" y1="260" x2="400" y2="84" stroke="#1f2937" stroke-width="2"/><line x1="107" y1="260" x2="400" y2="84" stroke="#1f2937" stroke-width="2"/><line x1="262.5" y1="260" x2="400" y2="84" stroke="#1f2937" stroke-width="2"/><polyline points="386,260 386,246 400,246" fill="none" stroke="#1f2937" stroke-width="1.5"/><path d="M 147 260 A 40 40 0 0 0 141.3 239.4" fill="none" stroke="#334155" stroke-width="1.5"/><text x="152" y="252" font-size="13" font-family="sans-serif" fill="#1f2937">31°</text><path d="M 290.5 260 A 28 28 0 0 0 279.7 237.9" fill="none" stroke="#334155" stroke-width="1.5"/><text x="294" y="250" font-size="13" font-family="sans-serif" fill="#1f2937">52°</text><text x="94" y="278" font-size="14" font-family="sans-serif" fill="#1f2937">C</text><text x="256" y="278" font-size="14" font-family="sans-serif" fill="#1f2937">D</text><text x="404" y="278" font-size="14" font-family="sans-serif" fill="#1f2937">B</text><text x="404" y="80" font-size="14" font-family="sans-serif" fill="#1f2937">A</text><text x="408" y="176" font-size="13" font-family="sans-serif" fill="#1f2937">8 cm</text></svg>`;

// p1-q09: cuboid 8 × 6 × 5 in oblique projection; AG and AC highlighted.
const CUBOID = `<svg viewBox="0 0 440 310" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Cuboid ABCDEFGH. The base ABCD has AB = 8 cm and BC = 6 cm. The vertical edges AE, BF, CG and DH are 5 cm. The diagonal AG and the base diagonal AC are drawn."><rect x="0" y="0" width="440" height="310" fill="#ffffff"/><polygon points="60,280 378,235 378,85" fill="#fde68a" fill-opacity="0.55" stroke="none"/><line x1="60" y1="280" x2="300" y2="280" stroke="#1f2937" stroke-width="2"/><line x1="300" y1="280" x2="378" y2="235" stroke="#1f2937" stroke-width="2"/><line x1="60" y1="130" x2="300" y2="130" stroke="#1f2937" stroke-width="2"/><line x1="300" y1="130" x2="378" y2="85" stroke="#1f2937" stroke-width="2"/><line x1="138" y1="85" x2="378" y2="85" stroke="#1f2937" stroke-width="2"/><line x1="60" y1="130" x2="138" y2="85" stroke="#1f2937" stroke-width="2"/><line x1="60" y1="280" x2="60" y2="130" stroke="#1f2937" stroke-width="2"/><line x1="300" y1="280" x2="300" y2="130" stroke="#1f2937" stroke-width="2"/><line x1="378" y1="235" x2="378" y2="85" stroke="#1f2937" stroke-width="2"/><line x1="60" y1="280" x2="138" y2="235" stroke="#64748b" stroke-width="1.5" stroke-dasharray="5 4"/><line x1="138" y1="235" x2="378" y2="235" stroke="#64748b" stroke-width="1.5" stroke-dasharray="5 4"/><line x1="138" y1="235" x2="138" y2="85" stroke="#64748b" stroke-width="1.5" stroke-dasharray="5 4"/><line x1="60" y1="280" x2="378" y2="235" stroke="#b45309" stroke-width="2" stroke-dasharray="7 4"/><line x1="60" y1="280" x2="378" y2="85" stroke="#b91c1c" stroke-width="2.5"/><text x="44" y="296" font-size="14" font-family="sans-serif" fill="#1f2937">A</text><text x="298" y="298" font-size="14" font-family="sans-serif" fill="#1f2937">B</text><text x="384" y="244" font-size="14" font-family="sans-serif" fill="#1f2937">C</text><text x="124" y="232" font-size="14" font-family="sans-serif" fill="#1f2937">D</text><text x="44" y="128" font-size="14" font-family="sans-serif" fill="#1f2937">E</text><text x="296" y="122" font-size="14" font-family="sans-serif" fill="#1f2937">F</text><text x="384" y="82" font-size="14" font-family="sans-serif" fill="#1f2937">G</text><text x="124" y="78" font-size="14" font-family="sans-serif" fill="#1f2937">H</text><text x="166" y="300" font-size="13" font-family="sans-serif" fill="#1f2937">8 cm</text><text x="346" y="276" font-size="13" font-family="sans-serif" fill="#1f2937">6 cm</text><text x="20" y="210" font-size="13" font-family="sans-serif" fill="#1f2937">5 cm</text></svg>`;

// p1-q13: right square-based pyramid, base 10 cm, slant edges 13 cm.
const PYRAMID = `<svg viewBox="0 0 440 300" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Right square-based pyramid VABCD. The base ABCD is a square of side 10 cm. Each sloping edge such as VA is 13 cm. M is the centre of the base, directly below V."><rect x="0" y="0" width="440" height="300" fill="#ffffff"/><line x1="80" y1="260" x2="280" y2="260" stroke="#1f2937" stroke-width="2"/><line x1="280" y1="260" x2="360" y2="200" stroke="#1f2937" stroke-width="2"/><line x1="80" y1="260" x2="160" y2="200" stroke="#64748b" stroke-width="1.5" stroke-dasharray="5 4"/><line x1="160" y1="200" x2="360" y2="200" stroke="#64748b" stroke-width="1.5" stroke-dasharray="5 4"/><line x1="220" y1="40" x2="80" y2="260" stroke="#1f2937" stroke-width="2"/><line x1="220" y1="40" x2="280" y2="260" stroke="#1f2937" stroke-width="2"/><line x1="220" y1="40" x2="360" y2="200" stroke="#1f2937" stroke-width="2"/><line x1="220" y1="40" x2="160" y2="200" stroke="#64748b" stroke-width="1.5" stroke-dasharray="5 4"/><line x1="220" y1="40" x2="220" y2="230" stroke="#b91c1c" stroke-width="1.5" stroke-dasharray="4 3"/><line x1="80" y1="260" x2="220" y2="230" stroke="#b91c1c" stroke-width="1.5" stroke-dasharray="4 3"/><circle cx="220" cy="230" r="3" fill="#b91c1c"/><text x="226" y="244" font-size="13" font-family="sans-serif" fill="#1f2937">M</text><text x="214" y="32" font-size="14" font-family="sans-serif" fill="#1f2937">V</text><text x="64" y="276" font-size="14" font-family="sans-serif" fill="#1f2937">A</text><text x="280" y="278" font-size="14" font-family="sans-serif" fill="#1f2937">B</text><text x="366" y="204" font-size="14" font-family="sans-serif" fill="#1f2937">C</text><text x="146" y="196" font-size="14" font-family="sans-serif" fill="#1f2937">D</text><text x="160" y="280" font-size="13" font-family="sans-serif" fill="#1f2937">10 cm</text><text x="258" y="150" font-size="13" font-family="sans-serif" fill="#1f2937">13 cm</text></svg>`;

export const practice: TopicPractice = {
  // =========================================================================
  // QUICK-CHECK QUIZ
  // =========================================================================
  quiz: [
    {
      kind: "short",
      id: "pythagoras-trigonometry-quiz-q01",
      question:
        "A right-angled triangle has shorter sides 7 cm and 10 cm. Work out the length of the hypotenuse. Give your answer correct to 3 significant figures.",
      answer: { type: "number", value: 12.2, display: "12.2 cm" },
      solution: ["{{c^2 = 7^2 + 10^2 = 49 + 100 = 149}}", "{{c = sqrt(149) = 12.206...}}", "c = 12.2 cm (3 s.f.)."],
      commonError: "Forgetting the square root and giving 149.",
      traps: [
        { spec: { type: "number", value: 149 }, feedback: "149 is {{c^2}}. Take the square root to get c." },
        { spec: { type: "number", value: 7.14, tolerance: 0.01 }, feedback: "You subtracted. The hypotenuse is the longest side, so add the squares." },
      ],
      difficulty: "warmup",
      guideRef: "pythagoras",
      hints: ["Square both shorter sides and add.", "{{c^2 = 7^2 + 10^2}}, then square-root."],
      strategy: "Use a formula",
    },
    {
      kind: "short",
      id: "pythagoras-trigonometry-quiz-q02",
      question:
        "A right-angled triangle has hypotenuse 13.5 cm and one of the shorter sides 8.1 cm. Work out the length of the third side in cm.",
      answer: { type: "number", value: 10.8, display: "10.8 cm" },
      solution: ["The missing side is a shorter side, so subtract: {{a^2 = 13.5^2 - 8.1^2}}.", "{{a^2 = 182.25 - 65.61 = 116.64}}", "{{a = sqrt(116.64) = 10.8}} cm (exactly)."],
      commonError: "Adding the squares and getting {{sqrt(247.86) = 15.7}} — longer than the hypotenuse, which is impossible.",
      traps: [{ spec: { type: "number", value: 15.7, tolerance: 0.05 }, feedback: "That's longer than the hypotenuse! For a shorter side, subtract the squares." }],
      difficulty: "warmup",
      guideRef: "pythagoras",
      hints: ["Is the missing side the hypotenuse or a shorter side?", "Shorter side: hypotenuse² minus the other side²."],
      strategy: "Estimate first",
    },
    {
      kind: "mcq",
      id: "pythagoras-trigonometry-quiz-q03",
      question:
        "In a right-angled triangle, one angle is 35°. The side **opposite** the 35° angle is 8 cm. You want the hypotenuse, h cm. Which equation should you use?",
      options: ["{{cos 35° = 8/h}}", "{{tan 35° = 8/h}}", "{{sin 35° = 8/h}}", "{{sin 35° = h/8}}"],
      answerIndex: 2,
      explanation:
        "Opposite and hypotenuse means **SOH**: {{sin 35° = O/H = 8/h}}, so {{h = 8/(sin 35°) = 13.9}} cm. {{tan 35° = 8/h}} treats h as the adjacent side; {{sin 35° = h/8}} has the fraction upside down.",
      difficulty: "warmup",
      guideRef: "sohcahtoa",
      hints: ["Label the sides O, A, H from the 35° angle.", "You have O and want H. Which of SOH, CAH, TOA uses O and H?"],
      strategy: "Label then choose",
    },
    {
      kind: "short",
      id: "pythagoras-trigonometry-quiz-q04",
      question:
        "Triangle ABC has a right angle at B. AB = 12 cm and angle BAC = 40°. Work out the length of BC. Give your answer correct to 3 significant figures.",
      answer: { type: "number", value: 10.1, display: "10.1 cm" },
      solution: [
        "From angle A: BC is opposite, AB is adjacent. Use TOA.",
        "{{tan 40° = (BC)/12}}",
        "{{BC = 12 tan 40° = 10.069...}} = 10.1 cm.",
      ],
      commonError: "Using sin 40° (treating AB as the hypotenuse) and getting 7.71 cm.",
      traps: [
        { spec: { type: "number", value: 7.71, tolerance: 0.01 }, feedback: "AB is not the hypotenuse — the hypotenuse is AC, opposite the right angle. Use tan." },
        { spec: { type: "number", value: 14.3, tolerance: 0.05 }, feedback: "You divided by tan 40°. Rearrange {{tan 40° = (BC)/12}} carefully: multiply both sides by 12." },
      ],
      difficulty: "core",
      guideRef: "sohcahtoa",
      hints: ["Sketch it. Which side is opposite the right angle?", "From A: BC is opposite, AB is adjacent.", "{{tan 40° = (BC)/12}}"],
      strategy: "Draw a diagram",
    },
    {
      kind: "short",
      id: "pythagoras-trigonometry-quiz-q05",
      question:
        "In a right-angled triangle, the side adjacent to angle θ is 7 cm and the hypotenuse is 11 cm. Work out θ. Give your answer correct to 1 decimal place.",
      answer: { type: "number", value: 50.5, display: "50.5°" },
      solution: ["Adjacent and hypotenuse: CAH.", "{{cos θ = 7/11}}", "{{θ = cos^(-1)(7/11) = 50.478...°}} = 50.5°."],
      commonError: "Using {{sin^(-1)}} and getting 39.5° — that is the *other* acute angle.",
      traps: [{ spec: { type: "number", value: 39.5 }, feedback: "That's the other acute angle. With adjacent and hypotenuse, use cos." }],
      difficulty: "core",
      guideRef: "sohcahtoa",
      hints: ["Which two sides do you know, relative to θ?", "A and H → cos.", "Use the inverse: {{θ = cos^(-1)(7/11)}}."],
      strategy: "Use the inverse",
    },
    {
      kind: "mcq",
      id: "pythagoras-trigonometry-quiz-q06",
      question: "The bearing of B from A is 065°. What is the bearing of A from B?",
      options: ["115°", "245°", "295°", "155°"],
      answerIndex: 1,
      explanation:
        "A back bearing differs by 180°: 065° + 180° = 245°. 115° is 180° − 65°, and 295° is 360° − 65° — neither turns you round to face the way you came.",
      difficulty: "core",
      guideRef: "bearings-elevation",
      hints: ["Draw a north line at A and at B. They are parallel.", "Facing back the way you came is a half-turn.", "Add 180° (or subtract it if the bearing is over 180°)."],
      strategy: "Draw a diagram",
    },
    {
      kind: "short",
      id: "pythagoras-trigonometry-quiz-q07",
      question:
        "Arjun stands on level ground 40 m from the foot of a vertical rain tree. The angle of elevation of the top of the tree from the ground where he stands is 28°. Work out the height of the tree. Give your answer correct to 3 significant figures.",
      answer: { type: "number", value: 21.3, display: "21.3 m" },
      solution: ["Height is opposite the 28° angle; 40 m is adjacent.", "{{h = 40 tan 28° = 21.268...}}", "h = 21.3 m."],
      commonError: "Using 40 sin 28° = 18.8 m — 40 m is along the ground (adjacent), not the hypotenuse.",
      traps: [{ spec: { type: "number", value: 18.8, tolerance: 0.05 }, feedback: "The 40 m is along the ground — the adjacent side, not the hypotenuse. Use tan." }],
      difficulty: "core",
      guideRef: "bearings-elevation",
      hints: ["Draw the right-angled triangle: ground, tree, line of sight.", "Height is opposite 28°, ground distance is adjacent.", "{{tan 28° = h/40}}"],
      strategy: "Draw a diagram",
    },
    {
      kind: "short",
      id: "pythagoras-trigonometry-quiz-q08",
      question: "A cuboid measures 3 cm by 4 cm by 12 cm. Work out the length of the diagonal from one corner to the opposite corner (the space diagonal), in cm.",
      answer: { type: "number", value: 13, display: "13 cm" },
      solution: ["Base diagonal: {{sqrt(3^2 + 4^2) = 5}} cm.", "Space diagonal: {{sqrt(5^2 + 12^2) = sqrt(169) = 13}} cm.", "In one step: {{d = sqrt(3^2 + 4^2 + 12^2) = sqrt(169) = 13}}."],
      commonError: "Stopping at the base diagonal (5 cm).",
      traps: [{ spec: { type: "number", value: 5 }, feedback: "That's only the diagonal of the 3 × 4 face. Now use it with the 12 cm edge." }],
      difficulty: "core",
      guideRef: "three-d",
      hints: ["Find the diagonal of the base first.", "The base diagonal, the 12 cm edge and the space diagonal make a right-angled triangle.", "Or use {{d^2 = a^2 + b^2 + c^2}}."],
      strategy: "Find the right right-angled triangle",
    },
    {
      kind: "mcq",
      id: "pythagoras-trigonometry-quiz-q09",
      question: "What is the exact value of cos 30°?",
      options: ["{{1/2}}", "{{1/sqrt(2)}}", "{{sqrt(3)}}", "{{sqrt(3)/2}}"],
      answerIndex: 3,
      explanation:
        "Halve an equilateral triangle of side 2: the sides are 1, {{sqrt(3)}}, 2. From the 30° angle the adjacent side is {{sqrt(3)}}, so {{cos 30° = sqrt(3)/2}}. {{1/2}} is cos 60° (or sin 30°); {{sqrt(3)}} is tan 60°.",
      difficulty: "core",
      guideRef: "exact-values",
      hints: ["Picture half of an equilateral triangle with side 2.", "Its sides are 1, {{sqrt(3)}} and 2. Which is adjacent to 30°?"],
      strategy: "Draw a diagram",
    },
    {
      kind: "short",
      id: "pythagoras-trigonometry-quiz-q10",
      question:
        "Without a calculator: a right-angled triangle has shorter sides 20 cm and 48 cm. Work out the length of the hypotenuse in cm.",
      answer: { type: "number", value: 52, display: "52 cm" },
      solution: ["Notice 20 = 4 × 5 and 48 = 4 × 12.", "5, 12, 13 is a Pythagorean triple, so the hypotenuse is 4 × 13 = 52 cm.", "Check: {{20^2 + 48^2 = 400 + 2304 = 2704 = 52^2}}."],
      commonError: "Adding the sides (68) instead of their squares.",
      traps: [{ spec: { type: "number", value: 68 }, feedback: "Pythagoras adds the *squares*, not the lengths." }],
      difficulty: "core",
      guideRef: "pythagorean-triples",
      hints: ["Is there a common factor of 20 and 48?", "Divide by 4: 5 and 12. Recognise the triple?"],
      strategy: "Spot a triple",
    },
  ],

  // =========================================================================
  // PRACTICE PAPERS
  // =========================================================================
  papers: [
    {
      id: "pythagoras-trigonometry-p1",
      title: "Practice Paper 1",
      questions: [
        {
          kind: "short",
          id: "pythagoras-trigonometry-p1-q01",
          question:
            "A 5.5 m ladder leans against a vertical wall. The foot of the ladder is on level ground, 1.8 m from the wall. How far up the wall does the ladder reach? Give your answer correct to 3 significant figures.",
          answer: { type: "number", value: 5.2, display: "5.20 m" },
          solution: ["The ladder is the hypotenuse.", "{{h^2 = 5.5^2 - 1.8^2 = 30.25 - 3.24 = 27.01}}", "{{h = sqrt(27.01) = 5.197...}} = 5.20 m."],
          commonError: "Adding the squares: {{sqrt(33.49) = 5.79}} m — more than the ladder's length.",
          traps: [{ spec: { type: "number", value: 5.79, tolerance: 0.01 }, feedback: "The ladder is the hypotenuse, so the height must be less than 5.5 m. Subtract the squares." }],
          difficulty: "warmup",
          guideRef: "pythagoras",
          hints: ["Which side of the triangle is the ladder?", "Height² = 5.5² − 1.8²."],
          strategy: "Draw a diagram",
        },
        {
          kind: "short",
          id: "pythagoras-trigonometry-p1-q02",
          question:
            "A right-angled triangle has shorter sides 4 cm and 6 cm. Find the exact length of the hypotenuse. Give your answer as a surd in its simplest form.",
          answer: { type: "expression", expr: "2sqrt(13)", form: "surd", display: "{{2sqrt(13)}} cm" },
          solution: ["{{c^2 = 4^2 + 6^2 = 16 + 36 = 52}}", "{{c = sqrt(52) = sqrt(4 * 13) = 2sqrt(13)}} cm."],
          commonError: "Leaving the answer as {{sqrt(52)}}, which is not simplified.",
          difficulty: "warmup",
          guideRef: "pythagoras",
          hints: ["Find {{c^2}} first.", "{{52 = 4 * 13}} — take out the square factor."],
          strategy: "Find a square factor",
        },
        {
          kind: "short",
          id: "pythagoras-trigonometry-p1-q03",
          question:
            "A wheelchair ramp rises 5 m over a horizontal distance of 9 m. Work out the angle the ramp makes with the horizontal. Give your answer correct to 1 decimal place.",
          answer: { type: "number", value: 29.1, display: "29.1°" },
          solution: ["Opposite = 5, adjacent = 9: TOA.", "{{tan θ = 5/9}}", "{{θ = tan^(-1)(5/9) = 29.05...°}} = 29.1°."],
          commonError: "Using {{sin^(-1)(5/9)}} = 33.7° — 9 m is horizontal (adjacent), not the slope.",
          traps: [{ spec: { type: "number", value: 33.7 }, feedback: "9 m is the horizontal distance — adjacent, not hypotenuse. Use tan." }],
          difficulty: "warmup",
          guideRef: "sohcahtoa",
          hints: ["Label opposite and adjacent from the angle at the bottom of the ramp.", "{{tan θ = 5/9}}"],
          strategy: "Label then choose",
        },
        {
          kind: "short",
          id: "pythagoras-trigonometry-p1-q04",
          question: "The bearing of P from Q is 312°. Work out the bearing of Q from P.",
          answer: { type: "number", value: 132, display: "132°" },
          solution: ["Back bearing = bearing ± 180°.", "312° is more than 180°, so subtract: 312° − 180° = 132°."],
          commonError: "Adding 180° to get 492°, which is not a bearing.",
          traps: [{ spec: { type: "number", value: 48 }, feedback: "360° − 312° = 48° is the angle anticlockwise from north, not the back bearing. Subtract 180° instead." }],
          difficulty: "warmup",
          guideRef: "bearings-elevation",
          hints: ["A back bearing differs by 180°.", "Bearings must be between 000° and 360°."],
          strategy: "Draw a diagram",
        },
        {
          kind: "written",
          id: "pythagoras-trigonometry-p1-q05",
          question:
            "A triangle has sides 6 cm, 9 cm and 11 cm.\n\nIs the triangle right-angled? Show your working and explain your conclusion.",
          marks: 3,
          modelAnswer:
            "If it were right-angled, the longest side (11 cm) would be the hypotenuse, so {{6^2 + 9^2}} would equal {{11^2}}.\n\n{{6^2 + 9^2 = 36 + 81 = 117}} and {{11^2 = 121}}.\n\nSince 117 ≠ 121, the triangle is **not** right-angled. (In fact {{11^2 > 6^2 + 9^2}}, so the angle opposite the 11 cm side is slightly more than 90° — it is obtuse.)",
          markScheme: [
            { point: "Tests the longest side as the hypotenuse: compares 6² + 9² with 11²", keywords: ["11^2", "11²", "longest", "hypotenuse", "6^2 + 9^2", "6² + 9²"] },
            { point: "Correct values 117 and 121", keywords: ["117", "121"] },
            { point: "Concludes not right-angled because they are not equal", keywords: ["not right", "not equal", "≠", "not a right", "obtuse"] },
          ],
          commonError: "Checking {{6^2 + 11^2}} against {{9^2}} — the hypotenuse must be the longest side.",
          difficulty: "core",
          guideRef: "pythagoras",
          hints: ["Which side would have to be the hypotenuse?", "If it is right-angled, {{a^2 + b^2 = c^2}} must hold exactly.", "Compare {{6^2 + 9^2}} with {{11^2}}."],
          strategy: "Use the converse",
        },
        {
          kind: "short",
          id: "pythagoras-trigonometry-p1-q06",
          question:
            "In the diagram, ABC is a right-angled triangle with the right angle at B. D is a point on CB. AB = 8 cm, angle ADB = 52° and angle ACB = 31°.\n\nWork out the length of CD. Give your answer correct to 3 significant figures.",
          diagram: SHARED_SIDE,
          answer: { type: "number", value: 7.06, tolerance: 0.01, display: "7.06 cm" },
          solution: [
            "Triangle ABD: {{tan 52° = 8/(BD)}}, so {{BD = 8/(tan 52°) = 6.2503...}} cm.",
            "Triangle ABC: {{tan 31° = 8/(BC)}}, so {{BC = 8/(tan 31°) = 13.3142...}} cm.",
            "CD = BC − BD = 13.3142 − 6.2503 = 7.0639... = 7.06 cm.",
          ],
          commonError: "Rounding BD and BC to 3 s.f. too early, or calculating 8 tan 52° (putting BD on top).",
          traps: [{ spec: { type: "number", value: 3.07, tolerance: 0.01 }, feedback: "Check your rearrangement for BD: {{tan 52° = 8/(BD)}} gives {{BD = 8/(tan 52°)}}, not {{8 tan 52°}}." }],
          difficulty: "core",
          guideRef: "sohcahtoa",
          hints: [
            "CD isn't in any right-angled triangle by itself. What is CD in terms of BC and BD?",
            "AB is shared by both right-angled triangles — it is the opposite side in each.",
            "{{BD = 8/(tan 52°)}} and {{BC = 8/(tan 31°)}}. Subtract.",
          ],
          strategy: "Work through a shared side",
        },
        {
          kind: "short",
          id: "pythagoras-trigonometry-p1-q07",
          question:
            "A ferry leaves harbour H and sails 15 km on a bearing of 040°. How far east of H is the ferry now? Give your answer correct to 3 significant figures.",
          answer: { type: "number", value: 9.64, tolerance: 0.01, display: "9.64 km" },
          solution: [
            "The bearing 040° is measured from north, so the 40° angle is between the north line and the path.",
            "The eastward distance is opposite the 40° angle; the path (15 km) is the hypotenuse.",
            "{{E = 15 sin 40° = 9.641...}} = 9.64 km.",
          ],
          commonError: "Using 15 cos 40° = 11.5 km, which is the distance **north**.",
          traps: [{ spec: { type: "number", value: 11.5, tolerance: 0.05 }, feedback: "That's the distance north. East is opposite the 40° angle (measured from north) — use sin." }],
          difficulty: "core",
          guideRef: "bearings-elevation",
          hints: ["Draw north at H and mark the 40° angle clockwise from it.", "Drop a line from the ferry to the north line — the east distance is opposite 40°.", "East = 15 sin 40°."],
          strategy: "Draw a diagram",
        },
        {
          kind: "short",
          id: "pythagoras-trigonometry-p1-q08",
          question:
            "Without a calculator: a right-angled triangle has hypotenuse 10 cm and one angle of 60°. Find the exact length of the side opposite the 60° angle. Give your answer as a surd in its simplest form.",
          answer: { type: "expression", expr: "5sqrt(3)", form: "surd", display: "{{5sqrt(3)}} cm" },
          solution: ["Opposite = hypotenuse × sin 60°.", "{{sin 60° = sqrt(3)/2}}", "{{10 * sqrt(3)/2 = 5sqrt(3)}} cm."],
          commonError: "Using {{cos 60° = 1/2}} and getting 5 cm — that is the side adjacent to 60°.",
          traps: [{ spec: { type: "number", value: 5 }, feedback: "5 cm is adjacent to the 60° angle. You need the opposite side: use sin 60°." }],
          difficulty: "core",
          guideRef: "exact-values",
          hints: ["O and H → sin.", "Recall {{sin 60°}} from the half-equilateral triangle with sides 1, {{sqrt(3)}}, 2.", "{{sin 60° = sqrt(3)/2}}."],
          strategy: "Use exact values",
        },
        {
          kind: "short",
          id: "pythagoras-trigonometry-p1-q09",
          question:
            "The diagram shows a cuboid ABCDEFGH with AB = 8 cm, BC = 6 cm and CG = 5 cm.\n\nWork out the angle between the diagonal AG and the base ABCD. Give your answer correct to 1 decimal place.",
          diagram: CUBOID,
          answer: { type: "number", value: 26.6, display: "26.6°" },
          solution: [
            "The angle is GAC, because C is directly below G.",
            "{{AC = sqrt(8^2 + 6^2) = 10}} cm.",
            "Triangle ACG has a right angle at C: {{tan(GAC) = 5/10}}.",
            "{{GAC = tan^(-1)(0.5) = 26.565...°}} = 26.6°.",
          ],
          commonError: "Using the edge AB instead of the base diagonal AC: {{tan^(-1)(5/8) = 32.0°}}.",
          traps: [{ spec: { type: "number", value: 32 }, feedback: "G is not above B — it is above C. The triangle you need is ACG, with AC = 10 cm." }],
          difficulty: "core",
          guideRef: "three-d",
          hints: [
            "Which point on the base is directly below G?",
            "The angle you want is between AG and AC. Find AC first.",
            "Triangle ACG is right-angled at C, with AC = 10 and CG = 5.",
          ],
          strategy: "Find the right right-angled triangle",
        },
        {
          kind: "written",
          id: "pythagoras-trigonometry-p1-q10",
          question:
            "In a right-angled triangle, the side opposite angle x is 7 cm and the hypotenuse is 25 cm.\n\nPriya writes: \"{{x = tan^(-1)(7/25) = 15.6°}}\".\n\nExplain Priya's mistake and work out the correct value of x, correct to 1 decimal place.",
          marks: 3,
          modelAnswer:
            "Tan is opposite ÷ **adjacent**, but 25 cm is the hypotenuse, not the adjacent side. With opposite and hypotenuse, Priya should use sin (SOH).\n\n{{sin x = 7/25}}, so {{x = sin^(-1)(7/25) = 16.26...°}} = **16.3°**.\n\n(Check with Pythagoras: the adjacent side is {{sqrt(625 - 49) = 24}}, and {{tan^(-1)(7/24) = 16.3°}} too.)",
          markScheme: [
            { point: "Identifies that 25 cm is the hypotenuse, not the adjacent side (tan needs adjacent)", keywords: ["hypotenuse", "not adjacent", "adjacent", "should use sin", "sin"] },
            { point: "Correct method sin x = 7/25", keywords: ["sin x = 7/25", "sin^-1", "sin⁻¹", "7/25", "soh"] },
            { point: "Correct answer 16.3°", keywords: ["16.3", "16.26"] },
          ],
          commonError: "Saying 'she used the wrong button' without explaining which sides tan needs.",
          difficulty: "core",
          guideRef: "sohcahtoa",
          hints: ["Label the sides O, A, H from x.", "Which ratio uses O and H?", "Tan uses O and A. Which side is 25 cm?"],
          strategy: "Spot the error",
        },
        {
          kind: "short",
          id: "pythagoras-trigonometry-p1-q11",
          question:
            "Marcus stands at the top of a vertical cliff, 60 m above sea level. He sees a boat at an angle of depression of 18°. How far is the boat from the foot of the cliff? Give your answer correct to 3 significant figures.",
          answer: { type: "number", value: 185, display: "185 m" },
          solution: [
            "The angle of depression (18°) equals the angle of elevation from the boat to Marcus (alternate angles).",
            "From the boat: opposite = 60 m, adjacent = d. {{tan 18° = 60/d}}.",
            "{{d = 60/(tan 18°) = 184.66...}} = 185 m.",
          ],
          commonError: "Putting the 18° at the top of the cliff and calculating 60 tan 18° = 19.5 m.",
          traps: [{ spec: { type: "number", value: 19.5, tolerance: 0.05 }, feedback: "The angle of depression is measured *down from the horizontal*, not from the cliff face. Move the 18° to the boat (alternate angles)." }],
          difficulty: "core",
          guideRef: "bearings-elevation",
          hints: [
            "Draw the horizontal at Marcus's eye. The 18° is between that and the line of sight.",
            "Alternate angles: the angle at the boat is also 18°.",
            "From the boat, 60 m is opposite and d is adjacent.",
          ],
          strategy: "Use alternate angles",
        },
        {
          kind: "short",
          id: "pythagoras-trigonometry-p1-q12",
          question:
            "A right-angled triangle has integer sides. One of the shorter sides is 33 cm and the hypotenuse is 65 cm. Work out the length of the third side in cm.",
          answer: { type: "number", value: 56, display: "56 cm" },
          solution: [
            "{{b^2 = 65^2 - 33^2}}",
            "Difference of two squares: {{(65 - 33)(65 + 33) = 32 * 98 = 3136}}.",
            "{{b = sqrt(3136) = 56}} cm. (33, 56, 65 is a Pythagorean triple.)",
          ],
          solutions: [
            { label: "Square and subtract", steps: ["{{65^2 = 4225}}, {{33^2 = 1089}}.", "4225 − 1089 = 3136; {{sqrt(3136) = 56}}."] },
            { label: "Difference of two squares", steps: ["{{65^2 - 33^2 = (65 - 33)(65 + 33) = 32 * 98}}.", "{{32 * 98 = 64 * 49}}, so {{b = 8 * 7 = 56}}. Quicker without a calculator."] },
          ],
          commonError: "Adding the squares instead of subtracting.",
          traps: [{ spec: { type: "number", value: 73 }, feedback: "73 would be the hypotenuse if 33 and 65 were the shorter sides. Here 65 *is* the hypotenuse — subtract." }],
          difficulty: "core",
          guideRef: "pythagorean-triples",
          hints: ["Hypotenuse² − side² = other side².", "Try writing {{65^2 - 33^2}} as a difference of two squares.", "{{(65 - 33)(65 + 33) = 32 * 98}}."],
          strategy: "Factorise a difference of two squares",
        },
        {
          kind: "short",
          id: "pythagoras-trigonometry-p1-q13",
          question:
            "The diagram shows a right square-based pyramid VABCD. The base is a square of side 10 cm and each sloping edge is 13 cm. M is the centre of the base, directly below V.\n\nWork out (a) the vertical height VM and (b) the angle between the edge VA and the base. Give the height correct to 3 significant figures and the angle correct to 1 decimal place, height first.",
          diagram: PYRAMID,
          answer: { type: "list", values: [10.9, 57.0], ordered: true, tolerance: 0.05, display: "10.9 cm, 57.0°" },
          solution: [
            "AC is a diagonal of the base: {{AC = sqrt(10^2 + 10^2) = 10sqrt(2)}}, so {{AM = 5sqrt(2) = 7.071...}} cm.",
            "Triangle VMA is right-angled at M: {{VM = sqrt(13^2 - (5sqrt(2))^2) = sqrt(169 - 50) = sqrt(119) = 10.908...}} = 10.9 cm.",
            "The angle between VA and the base is angle VAM: {{cos(VAM) = (5sqrt(2))/13}}.",
            "{{VAM = cos^(-1)(7.071/13) = 57.05...°}} = 57.0°.",
          ],
          commonError: "Using half the side (5 cm) instead of half the diagonal for AM.",
          traps: [{ spec: { type: "list", values: [12, 67.4], ordered: true, tolerance: 0.05 }, feedback: "M is the centre of the square, so AM is half the **diagonal** ({{5sqrt(2)}}), not half a side (5)." }],
          difficulty: "challenge",
          guideRef: "three-d",
          hints: [
            "Which right-angled triangle contains VA, VM and the base? Its third side is AM.",
            "AM is half the diagonal of the square base.",
            "{{AM = 5sqrt(2)}}; then {{VM^2 = 13^2 - AM^2}} and {{cos(VAM) = (AM)/13}}.",
          ],
          strategy: "Find the right right-angled triangle",
        },
        {
          kind: "written",
          id: "pythagoras-trigonometry-p1-q14",
          question:
            "A hiker walks 6 km from A to B on a bearing of 050°. She then walks 8 km from B to C on a bearing of 140°.\n\n(a) Show that angle ABC = 90°.\n(b) Show that AC = 10 km and that the bearing of C from A is 103°, correct to the nearest degree.",
          marks: 4,
          modelAnswer:
            "(a) The bearing of A from B is 050° + 180° = 230°. The bearing of C from B is 140°. So angle ABC = 230° − 140° = **90°**.\n\n(b) Triangle ABC is right-angled at B, so {{AC = sqrt(6^2 + 8^2) = sqrt(100) = 10}} km.\n\nAngle BAC: {{tan(BAC) = 8/6}}, so angle BAC = 53.13°.\n\nC is clockwise from B as seen from A, so the bearing of C from A is 050° + 53.13° = 103.13° = **103°** to the nearest degree.",
          markScheme: [
            { point: "Back bearing of A from B is 230°", keywords: ["230"] },
            { point: "Angle ABC = 230° − 140° = 90°", keywords: ["230 - 140", "230 − 140", "90"] },
            { point: "AC = √(6² + 8²) = 10", keywords: ["100", "6^2 + 8^2", "6² + 8²", "10 km", "sqrt(100)"] },
            { point: "Angle BAC = tan⁻¹(8/6) = 53.1° and bearing 50 + 53.1 = 103°", keywords: ["53.1", "53.13", "8/6", "103"] },
          ],
          commonError: "Adding the bearings (50° + 140°) or using the angle 140° − 50° = 90° without justifying it with the back bearing.",
          difficulty: "challenge",
          guideRef: "bearings-elevation",
          hints: [
            "Draw a north line at B. What is the bearing of A from B?",
            "Angle ABC is the gap between the back bearing 230° and the bearing 140°.",
            "Once ABC = 90°, use Pythagoras for AC and tan for angle BAC — then add it to 050°.",
          ],
          strategy: "Draw a diagram",
        },
        {
          kind: "short",
          id: "pythagoras-trigonometry-p1-q15",
          question:
            "T is the top of a vertical tower TB standing on level ground. C and D are points on the ground in a straight line with B, with D between C and B, and CD = 20 m.\n\nThe angle of elevation of T from C is 30° and from D is 45°. Find the exact height of the tower. Give your answer in the form {{a + b sqrt(3)}}, where a and b are integers.",
          answer: { type: "expression", expr: "10+10sqrt(3)", form: "surd", display: "{{10 + 10sqrt(3)}} m" },
          solution: [
            "Let the height be h. From D (45°): {{DB = h/(tan 45°) = h}}.",
            "From C (30°): {{CB = h/(tan 30°) = h sqrt(3)}}, since {{tan 30° = 1/sqrt(3)}}.",
            "CB − DB = 20: {{h sqrt(3) - h = 20}}, so {{h = 20/(sqrt(3) - 1)}}.",
            "Rationalise: {{h = (20(sqrt(3) + 1))/((sqrt(3) - 1)(sqrt(3) + 1)) = (20(sqrt(3) + 1))/2 = 10 + 10sqrt(3)}} m (≈ 27.3 m).",
          ],
          commonError: "Leaving the surd in the denominator, or using decimals for tan 30° so the answer is not exact.",
          traps: [{ spec: { type: "number", value: 27.3, tolerance: 0.05 }, feedback: "Right value — but the question wants it exactly, in the form {{a + b sqrt(3)}}. Use {{tan 30° = 1/sqrt(3)}} and rationalise." }],
          difficulty: "challenge",
          guideRef: "exact-values",
          hints: [
            "Call the height h and write both ground distances CB and DB in terms of h.",
            "{{tan 45° = 1}} and {{tan 30° = 1/sqrt(3)}}, so DB = h and {{CB = h sqrt(3)}}.",
            "{{h sqrt(3) - h = 20}}. Factorise, divide, then rationalise the denominator.",
          ],
          strategy: "Introduce a variable",
        },
      ],
    },
    {
      id: "pythagoras-trigonometry-p2",
      title: "Practice Paper 2",
      questions: [
        {
          kind: "short",
          id: "pythagoras-trigonometry-p2-q01",
          question: "Work out the distance between the points (−2, 3) and (4, 11).",
          answer: { type: "number", value: 10, display: "10 units" },
          solution: ["Horizontal change: 4 − (−2) = 6. Vertical change: 11 − 3 = 8.", "{{d = sqrt(6^2 + 8^2) = sqrt(100) = 10}}."],
          commonError: "Working out 4 − 2 = 2 instead of 4 − (−2) = 6.",
          traps: [{ spec: { type: "number", value: 8.25, tolerance: 0.01 }, feedback: "Check the horizontal change: 4 − (−2) = 6, not 2." }],
          difficulty: "warmup",
          guideRef: "pythagoras",
          hints: ["Sketch the two points and draw the right-angled triangle between them.", "The shorter sides are the changes in x and in y."],
          strategy: "Draw a diagram",
        },
        {
          kind: "short",
          id: "pythagoras-trigonometry-p2-q02",
          question:
            "In a right-angled triangle, angle θ = 34° and the side adjacent to θ is 9 cm. Work out the length of the hypotenuse. Give your answer correct to 3 significant figures.",
          answer: { type: "number", value: 10.9, display: "10.9 cm" },
          solution: ["A and H: CAH. {{cos 34° = 9/h}}.", "{{h = 9/(cos 34°) = 10.855...}} = 10.9 cm."],
          commonError: "Multiplying: 9 cos 34° = 7.46 cm — shorter than the adjacent side, so it can't be the hypotenuse.",
          traps: [{ spec: { type: "number", value: 7.46, tolerance: 0.01 }, feedback: "The hypotenuse must be longer than 9 cm. When the unknown is on the bottom, divide: {{h = 9/(cos 34°)}}." }],
          difficulty: "warmup",
          guideRef: "sohcahtoa",
          hints: ["Adjacent and hypotenuse → cos.", "{{cos 34° = 9/h}} — h is on the bottom, so {{h = 9/(cos 34°)}}."],
          strategy: "Check by estimating",
        },
        {
          kind: "short",
          id: "pythagoras-trigonometry-p2-q03",
          question:
            "A vertical lamp post is 12 m tall. Mei stands on level ground 20 m from its base. Work out the angle of elevation of the top of the lamp post from where Mei's feet are. Give your answer correct to 1 decimal place.",
          answer: { type: "number", value: 31, display: "31.0°" },
          solution: ["Opposite 12, adjacent 20: {{tan θ = 12/20}}.", "{{θ = tan^(-1)(0.6) = 30.96...°}} = 31.0°."],
          commonError: "Using {{tan^(-1)(20/12)}} = 59.0° — that's the angle at the top of the post.",
          traps: [{ spec: { type: "number", value: 59 }, feedback: "That's the angle at the top of the lamp post. Elevation is measured at the ground: {{tan θ = 12/20}}." }],
          difficulty: "warmup",
          guideRef: "bearings-elevation",
          hints: ["The angle of elevation is at Mei's position, up from the horizontal.", "{{tan θ = 12/20}}"],
          strategy: "Draw a diagram",
        },
        {
          kind: "mcq",
          id: "pythagoras-trigonometry-p2-q04",
          question: "Which set of lengths forms a right-angled triangle?",
          options: ["9 cm, 12 cm, 15 cm", "5 cm, 12 cm, 14 cm", "7 cm, 24 cm, 26 cm", "4 cm, 5 cm, 6 cm"],
          answerIndex: 0,
          explanation:
            "{{9^2 + 12^2 = 81 + 144 = 225 = 15^2}} — it is 3 × (3, 4, 5). For 5, 12, 14: {{25 + 144 = 169 = 13^2}}, not {{14^2}}. For 7, 24, 26: {{49 + 576 = 625 = 25^2}}, not {{26^2}}. 4, 5, 6 is a classic trap: consecutive numbers, but {{16 + 25 = 41 != 36}}.",
          difficulty: "warmup",
          guideRef: "pythagorean-triples",
          hints: ["Test each: does (shorter)² + (shorter)² = (longest)²?", "Look for a multiple of a triple you know: 3-4-5, 5-12-13, 7-24-25."],
          strategy: "Spot a triple",
        },
        {
          kind: "short",
          id: "pythagoras-trigonometry-p2-q05",
          question: "An isosceles triangle has two sides of 13 cm and a base of 10 cm. Work out its area in cm².",
          answer: { type: "number", value: 60, display: "60 cm²" },
          solution: [
            "The line of symmetry splits the base into two halves of 5 cm and meets it at right angles.",
            "Height: {{h = sqrt(13^2 - 5^2) = sqrt(144) = 12}} cm.",
            "Area = {{1/2 * 10 * 12 = 60}} cm².",
          ],
          commonError: "Using 13 as the height (area 65 cm²) — the sloping side is not perpendicular to the base.",
          traps: [{ spec: { type: "number", value: 65 }, feedback: "13 cm is a sloping side, not the perpendicular height. Find the height with Pythagoras first." }],
          difficulty: "core",
          guideRef: "pythagoras",
          hints: ["You need the perpendicular height.", "Split the isosceles triangle down its line of symmetry into two right-angled triangles.", "Each has hypotenuse 13 and base 5."],
          strategy: "Use symmetry",
        },
        {
          kind: "written",
          id: "pythagoras-trigonometry-p2-q06",
          question: "A is the point (1, 2), B is the point (5, 5) and C is the point (2, 9).\n\nShow that triangle ABC is right-angled, and state which vertex has the right angle.",
          marks: 3,
          modelAnswer:
            "{{AB^2 = (5 - 1)^2 + (5 - 2)^2 = 16 + 9 = 25}}\n\n{{BC^2 = (2 - 5)^2 + (9 - 5)^2 = 9 + 16 = 25}}\n\n{{AC^2 = (2 - 1)^2 + (9 - 2)^2 = 1 + 49 = 50}}\n\nSince {{AB^2 + BC^2 = 25 + 25 = 50 = AC^2}}, the converse of Pythagoras shows the triangle is right-angled. The right angle is opposite the longest side AC, so it is at **B**. (It is also isosceles: AB = BC = 5.)",
          markScheme: [
            { point: "Finds AB² = 25 and BC² = 25 (or AB = BC = 5)", keywords: ["25", "ab = 5", "bc = 5"] },
            { point: "Finds AC² = 50", keywords: ["50", "sqrt(50)", "√50", "5√2"] },
            { point: "Uses AB² + BC² = AC² to conclude right angle at B", keywords: ["25 + 25", "right angle at b", "angle b", "at b", "converse"] },
          ],
          commonError: "Finding the three lengths but not stating the converse of Pythagoras, or naming the wrong vertex.",
          difficulty: "core",
          guideRef: "pythagoras",
          hints: ["Find the square of each side's length using the coordinates.", "If two squared lengths add to the third, the triangle is right-angled.", "The right angle is opposite the longest side."],
          strategy: "Use the converse",
        },
        {
          kind: "short",
          id: "pythagoras-trigonometry-p2-q07",
          question:
            "An isosceles triangle has two equal sides of 9 cm and a base of 14 cm. Work out the size of one of its base angles. Give your answer correct to 1 decimal place.",
          answer: { type: "number", value: 38.9, display: "38.9°" },
          solution: ["Split down the line of symmetry: a right-angled triangle with hypotenuse 9 and base 7.", "{{cos θ = 7/9}}", "{{θ = cos^(-1)(7/9) = 38.94...°}} = 38.9°."],
          commonError: "Using the full base: {{cos^(-1)(14/9)}} gives a calculator error — 14 can't be adjacent to a hypotenuse of 9.",
          traps: [{ spec: { type: "number", value: 51.1 }, feedback: "That's the angle at the top of the half-triangle. The base angle is next to the 7 cm side: {{cos θ = 7/9}}." }],
          difficulty: "core",
          guideRef: "sohcahtoa",
          hints: ["Trig needs a right angle. Where can you make one?", "Halve the triangle: the base becomes 7 cm.", "Adjacent 7, hypotenuse 9 → cos."],
          strategy: "Use symmetry",
        },
        {
          kind: "short",
          id: "pythagoras-trigonometry-p2-q08",
          question:
            "Wei Ling cycles 9 km due north from her home H, then 14 km due west to point P. Work out the bearing of P from H. Give your answer correct to the nearest degree.",
          answer: { type: "number", value: 303, display: "303°" },
          solution: [
            "At H, the angle between north and HP is {{tan^(-1)(14/9) = 57.26...°}}, measured anticlockwise (towards west).",
            "Bearings are clockwise from north, so the bearing is 360° − 57.26° = 302.7° = 303°.",
          ],
          commonError: "Giving 057° (forgetting that west of north is measured round clockwise) or using {{tan^(-1)(9/14)}}.",
          traps: [
            { spec: { type: "number", value: 57 }, feedback: "57° is the angle *anticlockwise* from north. Bearings go clockwise: subtract from 360°." },
            { spec: { type: "number", value: 327 }, feedback: "Check which side is opposite the angle at H: the 14 km west leg is opposite, 9 km north is adjacent." },
          ],
          difficulty: "core",
          guideRef: "bearings-elevation",
          hints: ["Sketch it: north then west. P is north-west of H.", "Find the angle at H between north and HP with tan.", "Bearings are clockwise from north — so subtract from 360°."],
          strategy: "Draw a diagram",
        },
        {
          kind: "short",
          id: "pythagoras-trigonometry-p2-q09",
          question: "A storage box is a cuboid measuring 12 cm by 9 cm by 20 cm. What is the length of the longest straight rod that fits inside the box? Give your answer in cm.",
          answer: { type: "number", value: 25, display: "25 cm" },
          solution: ["The longest rod lies along the space diagonal.", "{{d = sqrt(12^2 + 9^2 + 20^2) = sqrt(144 + 81 + 400) = sqrt(625) = 25}} cm."],
          commonError: "Using only a face diagonal, e.g. {{sqrt(12^2 + 20^2) = 23.3}} cm.",
          traps: [{ spec: { type: "number", value: 23.3, tolerance: 0.05 }, feedback: "That's a face diagonal. The longest rod goes corner to opposite corner through the box." }],
          difficulty: "core",
          guideRef: "three-d",
          hints: ["Where does the longest rod go?", "Corner to opposite corner: {{d^2 = a^2 + b^2 + c^2}}."],
          strategy: "Consider extremes",
        },
        {
          kind: "short",
          id: "pythagoras-trigonometry-p2-q10",
          question:
            "A vertical flagpole stands at one corner of a horizontal rectangular field measuring 40 m by 30 m. From the diagonally opposite corner, the angle of elevation of the top of the flagpole is 12°. Work out the height of the flagpole. Give your answer correct to 3 significant figures.",
          answer: { type: "number", value: 10.6, display: "10.6 m" },
          solution: [
            "The diagonal of the field: {{sqrt(40^2 + 30^2) = 50}} m.",
            "The diagonal, the flagpole and the line of sight form a right-angled triangle.",
            "{{h = 50 tan 12° = 10.627...}} = 10.6 m.",
          ],
          commonError: "Using 40 m (a side of the field) instead of the 50 m diagonal: 8.50 m.",
          traps: [{ spec: { type: "number", value: 8.5, tolerance: 0.01 }, feedback: "The opposite corner is along the diagonal, not a side. Find the 50 m diagonal first." }],
          difficulty: "core",
          guideRef: "three-d",
          hints: ["How far is the opposite corner from the foot of the flagpole?", "Diagonal = {{sqrt(40^2 + 30^2)}}.", "Then height = diagonal × tan 12°."],
          strategy: "Find the right right-angled triangle",
        },
        {
          kind: "short",
          id: "pythagoras-trigonometry-p2-q11",
          question:
            "Without a calculator: a right-angled isosceles triangle has hypotenuse 12 cm. Find the exact length of each of the shorter sides. Give your answer as a surd in its simplest form.",
          answer: { type: "expression", expr: "6sqrt(2)", form: "surd", display: "{{6sqrt(2)}} cm" },
          solution: [
            "The angles are 45°, 45°, 90°. Side = {{12 sin 45° = 12 * 1/sqrt(2) = 12/sqrt(2)}}.",
            "Rationalise: {{12/sqrt(2) = (12sqrt(2))/2 = 6sqrt(2)}} cm.",
          ],
          solutions: [
            { label: "Pythagoras", steps: ["{{x^2 + x^2 = 12^2}}, so {{2x^2 = 144}}, {{x^2 = 72}}.", "{{x = sqrt(72) = 6sqrt(2)}}."] },
          ],
          commonError: "Halving the hypotenuse to get 6 cm.",
          traps: [{ spec: { type: "number", value: 6 }, feedback: "Halving doesn't work — check: {{6^2 + 6^2 = 72 != 144}}. Use {{sin 45° = 1/sqrt(2)}}." }],
          difficulty: "core",
          guideRef: "exact-values",
          hints: ["What are the angles in a right-angled isosceles triangle?", "{{sin 45° = 1/sqrt(2)}}, or call each side x and use Pythagoras.", "Simplify {{12/sqrt(2)}} by rationalising."],
          strategy: "Use exact values",
        },
        {
          kind: "written",
          id: "pythagoras-trigonometry-p2-q12",
          question:
            "Ethan says: \"In a right-angled triangle with a fixed hypotenuse, if you double an angle, the side opposite it doubles too.\"\n\nUse a triangle with hypotenuse 10 cm and angles of 30° and 60° to show that Ethan is wrong. Explain why his idea fails.",
          marks: 3,
          modelAnswer:
            "Opposite 30°: {{10 sin 30° = 10 * 1/2 = 5}} cm.\n\nOpposite 60°: {{10 sin 60° = 10 * sqrt(3)/2 = 5sqrt(3) ≈ 8.66}} cm.\n\nIf Ethan were right, the side opposite 60° would be 10 cm. It is 8.66 cm, so he is wrong.\n\nThe side opposite is {{10 sin θ}}, and sin θ is **not proportional** to θ: {{sin 60° != 2 sin 30°}}. (Doubling 60° to 120° would not even fit in a right-angled triangle — and the opposite side can never exceed the 10 cm hypotenuse.)",
          markScheme: [
            { point: "Side opposite 30° is 5 cm", keywords: ["5 cm", "10 sin 30", "= 5", "sin 30 = 1/2"] },
            { point: "Side opposite 60° is 5√3 ≈ 8.66 cm, not 10 cm", keywords: ["8.66", "5√3", "5sqrt(3)", "10 sin 60", "not 10"] },
            { point: "Explains sin is not proportional to the angle (sin 60° ≠ 2 sin 30°)", keywords: ["not proportional", "sin 60 ≠ 2 sin 30", "not double", "doesn't double", "does not double", "not linear"] },
          ],
          commonError: "Just saying 'he's wrong' after one calculation, without comparing to 10 cm or explaining why.",
          difficulty: "core",
          guideRef: "sohcahtoa",
          hints: ["Work out the side opposite 30° and the side opposite 60°.", "Is the second one double the first?", "Opposite = 10 sin θ. Does sin double when θ doubles?"],
          strategy: "Test a counterexample",
        },
        {
          kind: "short",
          id: "pythagoras-trigonometry-p2-q13",
          question:
            "A right-angled triangle has a perimeter of 30 cm and a hypotenuse of 13 cm. Work out the area of the triangle in cm².",
          answer: { type: "number", value: 30, display: "30 cm²" },
          solution: [
            "Let the shorter sides be a and b. Then a + b = 30 − 13 = 17 and {{a^2 + b^2 = 169}}.",
            "Square the first: {{(a + b)^2 = a^2 + 2ab + b^2 = 289}}.",
            "Subtract: {{2ab = 289 - 169 = 120}}, so ab = 60.",
            "Area = {{1/2 ab = 30}} cm².",
          ],
          solutions: [
            { label: "Spot the triple", steps: ["A hypotenuse of 13 suggests 5, 12, 13. Check: 5 + 12 + 13 = 30 ✓.", "Area = {{1/2 * 5 * 12 = 30}} cm². Quick — but only works because the sides happen to be whole numbers."] },
            { label: "Use (a + b)² without finding a or b", steps: ["{{2ab = (a + b)^2 - (a^2 + b^2) = 17^2 - 13^2 = 120}}.", "Area = {{(ab)/2 = 30}}. This works for *any* values, whole or not."] },
          ],
          commonError: "Trying to solve for a and b separately and getting lost in a quadratic, when the area only needs ab.",
          traps: [{ spec: { type: "number", value: 60 }, feedback: "60 is ab. The area of a right-angled triangle is half of that." }],
          difficulty: "challenge",
          guideRef: "pythagoras",
          hints: [
            "Call the shorter sides a and b. Write two equations.",
            "a + b = 17 and {{a^2 + b^2 = 169}}. The area is {{1/2 ab}} — you only need the product.",
            "What happens if you square a + b = 17?",
          ],
          strategy: "Work backwards from what you need",
        },
        {
          kind: "short",
          id: "pythagoras-trigonometry-p2-q14",
          question:
            "Two boats leave port O at the same time. Boat P sails 20 km on a bearing of 035°. Boat Q sails 15 km on a bearing of 125°.\n\nWork out the bearing of Q from P. Give your answer correct to the nearest degree.",
          answer: { type: "number", value: 178, display: "178°" },
          solution: [
            "Angle POQ = 125° − 35° = 90°, so triangle POQ is right-angled at O (and PQ = {{sqrt(20^2 + 15^2) = 25}} km).",
            "Angle OPQ: {{tan(OPQ) = 15/20}}, so OPQ = 36.87°.",
            "The bearing of O from P is 035° + 180° = 215°.",
            "Q is anticlockwise from O as seen from P (Q lies east of the line PO), so the bearing of Q from P is 215° − 36.87° = 178.13° = 178°.",
          ],
          commonError: "Adding 36.9° to 215° instead of subtracting (giving 252°) — sketch to see which side of PO the point Q lies.",
          traps: [{ spec: { type: "number", value: 252 }, feedback: "Sketch it: from P, the port O is at 215°, and Q is round to the east of that line — so turn *anticlockwise* from 215°." }],
          difficulty: "challenge",
          guideRef: "bearings-elevation",
          hints: [
            "Find angle POQ first. What do you notice?",
            "With a right angle at O, find angle OPQ using tan.",
            "From P, the bearing back to O is 215°. Does Q lie clockwise or anticlockwise from that direction?",
          ],
          strategy: "Draw a diagram",
        },
        {
          kind: "written",
          id: "pythagoras-trigonometry-p2-q15",
          question:
            "A cube has edges of length a cm.\n\nShow that the angle between a space diagonal of the cube and its base is the same for every cube, and find this angle correct to 1 decimal place.",
          marks: 3,
          modelAnswer:
            "Let the base be ABCD with G directly above C, and take the space diagonal AG.\n\nBase diagonal: {{AC = sqrt(a^2 + a^2) = a sqrt(2)}}.\n\nTriangle ACG is right-angled at C with CG = a, so {{tan(GAC) = a/(a sqrt(2)) = 1/sqrt(2)}}.\n\nThe a cancels, so the angle does not depend on the size of the cube: {{GAC = tan^(-1)(1/sqrt(2)) = 35.3°}} for every cube.",
          markScheme: [
            { point: "Base diagonal = a√2", keywords: ["a√2", "asqrt(2)", "a sqrt(2)", "2a^2", "2a²"] },
            { point: "tan θ = a/(a√2) = 1/√2, with a cancelling", keywords: ["1/√2", "1/sqrt(2)", "cancel", "a/a√2", "independent"] },
            { point: "Angle = 35.3°", keywords: ["35.3", "35.26"] },
          ],
          commonError: "Choosing a particular cube (e.g. a = 1) — that finds the angle but doesn't show it is the same for *every* cube.",
          difficulty: "challenge",
          guideRef: "three-d",
          hints: ["Which point on the base lies directly below the top end of the diagonal?", "Write the base diagonal in terms of a.", "Form tan θ — what happens to a?"],
          strategy: "Introduce a variable",
        },
      ],
    },
  ],

  // =========================================================================
  // CHALLENGE SET
  // =========================================================================
  challenge: [
    {
      kind: "short",
      id: "pythagoras-trigonometry-ch-q01",
      question:
        "The *spiral of Theodorus* is built from right-angled triangles. Triangle 1 has shorter sides 1 and 1. Each new triangle uses the hypotenuse of the previous triangle as one shorter side and a new side of length 1 as the other.\n\nHow many of the first 100 triangles have a hypotenuse whose length is a whole number?",
      answer: { type: "number", value: 9 },
      solution: [
        "Triangle 1: {{sqrt(1 + 1) = sqrt(2)}}. Triangle 2: {{sqrt(2 + 1) = sqrt(3)}}. Triangle 3: {{sqrt(3 + 1) = sqrt(4) = 2}}.",
        "Pattern: triangle n has hypotenuse {{sqrt(n + 1)}} (each step adds 1 to the square).",
        "For n = 1 to 100, n + 1 runs from 2 to 101. The perfect squares in that range are 4, 9, 16, …, 100, i.e. {{2^2}} to {{10^2}}.",
        "That's 9 triangles.",
      ],
      solutions: [
        { label: "Induction-style argument", steps: ["If triangle n has hypotenuse {{sqrt(n + 1)}}, triangle n + 1 has hypotenuse {{sqrt((sqrt(n + 1))^2 + 1^2) = sqrt(n + 2)}}.", "So the formula holds for every n; count the squares between 2 and 101: 9."] },
        { label: "Track the squares", steps: ["Hypotenuse² goes 2, 3, 4, 5, …, 101 (adds 1 each time).", "Whole-number hypotenuse ⇔ hypotenuse² is a perfect square: 4, 9, …, 100 → 9 of them."] },
      ],
      commonError: "Counting 10 by including 1 = {{1^2}} — but the first hypotenuse² is 2, so 1 never appears.",
      traps: [{ spec: { type: "number", value: 10 }, feedback: "Is {{1^2}} ever a hypotenuse²? The smallest is 2. Count squares from 4 up to 101 only." }],
      difficulty: "challenge",
      guideRef: "pythagoras",
      hints: [
        "Work out the first three or four hypotenuses. Keep them as surds.",
        "Look at the hypotenuse *squared* each time. What's the pattern?",
        "Triangle n has hypotenuse {{sqrt(n + 1)}}. When is that a whole number?",
        "Count the perfect squares between 2 and 101.",
      ],
      strategy: "Try small cases, then find a pattern",
    },
    {
      kind: "short",
      id: "pythagoras-trigonometry-ch-q02",
      question:
        "A right-angled triangle has whole-number sides, and one of its shorter sides is 15. Find **every** possible length of the hypotenuse. (Give all values, in any order.)",
      answer: { type: "list", values: [17, 25, 39, 113], ordered: false, display: "17, 25, 39, 113" },
      solution: [
        "Let the other shorter side be b and the hypotenuse c: {{c^2 - b^2 = 225}}, so {{(c - b)(c + b) = 225}}.",
        "c − b and c + b are positive whole numbers with product 225, c − b < c + b, and both odd (since 225 is odd).",
        "Factor pairs: 1 × 225, 3 × 75, 5 × 45, 9 × 25. (15 × 15 gives b = 0.)",
        "c = average of the pair: 113, 39, 25, 17 (with b = 112, 36, 20, 8).",
        "So the hypotenuse can be 17, 25, 39 or 113.",
      ],
      solutions: [
        { label: "Difference of two squares", steps: ["{{(c - b)(c + b) = 225}}. List factor pairs, solve each pair of simultaneous equations.", "Gets *every* answer and proves there are no others."] },
        { label: "Scale known triples (incomplete!)", steps: ["Scale (3, 4, 5) by 5 → (15, 20, 25). Scale (5, 12, 13) by 3 → (15, 36, 39). (8, 15, 17) is a primitive triple you may know. (Careful: in (9, 12, 15) the 15 is the hypotenuse, so it doesn't count.)", "Scaling finds 17, 25, 39 but easily misses (15, 112, 113) — which is why the algebraic method is better."] },
      ],
      commonError: "Stopping after spotting (15, 20, 25) and (8, 15, 17) and missing the large triple (15, 112, 113).",
      traps: [{ spec: { type: "list", values: [17, 25, 39], ordered: false }, feedback: "Close — there's one more. Have you used the factor pair 1 × 225?" }],
      difficulty: "challenge",
      guideRef: "pythagorean-triples",
      hints: [
        "Write {{c^2 - 15^2 = b^2}}, i.e. {{c^2 - b^2 = 225}}.",
        "Factorise the left side as a difference of two squares.",
        "{{(c - b)(c + b) = 225}}. List the factor pairs of 225.",
        "For each pair, c is the mean of the two factors. Discard any pair giving b = 0.",
      ],
      strategy: "Factorise a difference of two squares",
    },
    {
      kind: "short",
      id: "pythagoras-trigonometry-ch-q03",
      question:
        "A regular pentagon has sides of length 10 cm. Work out its area. Give your answer correct to 3 significant figures.",
      answer: { type: "number", value: 172, display: "172 cm²" },
      solution: [
        "Join the centre O to every vertex: 5 congruent isosceles triangles, each with angle {{360° ÷ 5 = 72°}} at O.",
        "Split one in half: a right-angled triangle with angle 36° at O and opposite side 5 cm.",
        "Height (apothem): {{h = 5/(tan 36°) = 6.8819...}} cm.",
        "One isosceles triangle: {{1/2 * 10 * 6.8819 = 34.409...}} cm². Five of them: 172.05... = 172 cm².",
      ],
      commonError: "Using 72° (the whole angle at the centre) in the right-angled triangle instead of half of it.",
      traps: [{ spec: { type: "number", value: 40.6, tolerance: 0.05 }, feedback: "You used 72° in the right-angled triangle. Halving the isosceles triangle also halves the angle at the centre: 36°." }],
      difficulty: "challenge",
      guideRef: "sohcahtoa",
      hints: [
        "Split the pentagon into triangles from the centre. How many, and what angle at the centre?",
        "Each is isosceles. Cut it in half to get a right angle.",
        "In the half-triangle: angle 36° at the centre, opposite side 5 cm. Find the height with tan.",
      ],
      strategy: "Make it simpler",
    },
    {
      kind: "short",
      id: "pythagoras-trigonometry-ch-q04",
      question:
        "From the top of a 50 m tall HDB block, Siti measures the angle of elevation of the top of a taller condominium as 20° and the angle of depression of its base as 35°. Both buildings stand on the same level ground.\n\nWork out the height of the condominium. Give your answer correct to 3 significant figures.",
      answer: { type: "number", value: 76, display: "76.0 m" },
      solution: [
        "Let d be the horizontal distance between the buildings.",
        "Lower triangle (depression 35°): {{tan 35° = 50/d}}, so {{d = 50/(tan 35°) = 71.407...}} m.",
        "Upper triangle (elevation 20°): extra height {{= d tan 20° = 71.407 * tan 20° = 25.990...}} m.",
        "Height = 50 + 25.990 = 75.990... = 76.0 m.",
      ],
      solutions: [
        { label: "Find the gap first", steps: ["{{d = 50/(tan 35°)}}, then height {{= 50 + d tan 20°}}."] },
        { label: "One formula", steps: ["Height {{= 50 + 50 * (tan 20°)/(tan 35°) = 50(1 + (tan 20°)/(tan 35°))}}.", "= 50 × 1.5198 = 76.0 m. Doing it in one go avoids any early rounding."] },
      ],
      commonError: "Forgetting to add the 50 m (giving 26.0 m), or putting the 35° at the base of the condominium wrongly.",
      traps: [{ spec: { type: "number", value: 26, tolerance: 0.05 }, feedback: "That's only the part of the condominium *above* Siti's eye level. Add the 50 m below it." }],
      difficulty: "challenge",
      guideRef: "bearings-elevation",
      hints: [
        "Draw a horizontal line from Siti across to the condominium. It splits the problem into two right-angled triangles.",
        "Both triangles share the horizontal distance d. Find d from the lower one.",
        "Use d to find the height above Siti's level, then add 50 m.",
      ],
      strategy: "Work through a shared side",
    },
    {
      kind: "short",
      id: "pythagoras-trigonometry-ch-q05",
      question:
        "Hana walks 5 km on a bearing of 030°, then 8 km on a bearing of 100°. She wants to walk straight back to her start.\n\nWork out (a) how far she must walk and (b) the bearing she must walk on. Give the distance correct to 3 significant figures and the bearing to the nearest degree, distance first.",
      answer: { type: "list", values: [10.8, 254], ordered: true, tolerance: 0.05, display: "10.8 km, 254°" },
      solution: [
        "Split each leg into east and north parts using right-angled triangles.",
        "Leg 1: east {{5 sin 30° = 2.5}}, north {{5 cos 30° = 4.330}}.",
        "Leg 2: the bearing 100° is 10° south of east. East {{8 cos 10° = 7.878}}, south {{8 sin 10° = 1.389}}.",
        "Total: east 10.378 km, north 4.330 − 1.389 = 2.941 km.",
        "Distance back: {{sqrt(10.378^2 + 2.941^2) = 10.787...}} = 10.8 km.",
        "From the end point, start is west and a little south. Angle below west: {{tan^(-1)(2.941/10.378) = 15.82°}}. Bearing = 270° − 15.82° = 254.18° = 254°.",
      ],
      commonError: "Adding the distances (13 km) or treating the two legs as perpendicular — the angle between them is 110°, not 90°.",
      traps: [{ spec: { type: "list", values: [9.43, 238], ordered: true, tolerance: 0.05 }, feedback: "The legs are not at right angles (100° − 30° = 70° change of direction). Break each leg into east and north parts instead." }],
      difficulty: "challenge",
      guideRef: "bearings-elevation",
      hints: [
        "The two legs don't make a right angle, so split each into an east part and a north part.",
        "For a bearing θ (from north), east = distance × sin θ and north = distance × cos θ.",
        "Add the east parts and the north parts. Now one right-angled triangle gives the distance back.",
        "To head back you face the opposite direction: work out the angle from west, then convert to a bearing.",
      ],
      strategy: "Make it simpler",
    },
    {
      kind: "short",
      id: "pythagoras-trigonometry-ch-q06",
      question:
        "ABCDEFGH is a cube of side 2 cm. ABCD is the base and E, F, G, H lie directly above A, B, C, D respectively. M is the midpoint of the top edge GH.\n\nWork out the angle between the line AM and the base ABCD. Give your answer correct to 1 decimal place.",
      answer: { type: "number", value: 41.8, display: "41.8°" },
      solution: [
        "The point of the base directly below M is N, the midpoint of CD.",
        "AN: along AD 2 cm, across DN 1 cm, so {{AN = sqrt(2^2 + 1^2) = sqrt(5)}} cm.",
        "Triangle ANM is right-angled at N with MN = 2 cm: {{tan(MAN) = 2/sqrt(5)}}.",
        "{{MAN = tan^(-1)(2/sqrt(5)) = 41.81...°}} = 41.8°.",
      ],
      solutions: [
        { label: "Projection onto the base", steps: ["Drop M straight down to N; the angle is MAN with {{tan(MAN) = 2/sqrt(5)}}."] },
        { label: "Coordinates", steps: ["A = (0, 0, 0), M = (1, 2, 2). Horizontal distance {{sqrt(1^2 + 2^2) = sqrt(5)}}, vertical rise 2.", "Angle = {{tan^(-1)(2/sqrt(5)) = 41.8°}}. AM itself is {{sqrt(1 + 4 + 4) = 3}} cm, so also {{sin^(-1)(2/3) = 41.8°}} ✓."] },
      ],
      commonError: "Using AD (2 cm) as the horizontal side instead of AN, giving 45°.",
      traps: [{ spec: { type: "number", value: 45 }, feedback: "M is not above D — it's above the midpoint of CD. The horizontal distance is {{sqrt(5)}}, not 2." }],
      difficulty: "challenge",
      guideRef: "three-d",
      hints: [
        "Which point of the base is directly below M?",
        "It's N, the midpoint of CD. The angle you want is MAN.",
        "Find AN with Pythagoras on the base, then use tan with MN = 2.",
      ],
      strategy: "Find the right right-angled triangle",
    },
    {
      kind: "short",
      id: "pythagoras-trigonometry-ch-q07",
      question:
        "An ant is at one corner of a closed cuboid box measuring 6 cm by 4 cm by 3 cm. It wants to reach the diagonally opposite corner, walking only on the outside surface of the box.\n\nFind the length of the shortest possible path. Give your answer as an exact surd.",
      answer: { type: "expression", expr: "sqrt(85)", form: "surd", display: "{{sqrt(85)}} cm (≈ 9.22 cm)" },
      solution: [
        "Unfold (net) two adjacent faces so they lie flat; the shortest path is then a straight line.",
        "There are three ways to pair the edges: {{sqrt((4 + 3)^2 + 6^2) = sqrt(85)}}, {{sqrt((6 + 3)^2 + 4^2) = sqrt(97)}}, {{sqrt((6 + 4)^2 + 3^2) = sqrt(109)}}.",
        "The smallest is {{sqrt(85) ≈ 9.22}} cm — fold the two *shorter* edges together and keep the longest edge on its own.",
      ],
      solutions: [
        { label: "Check all three nets", steps: ["Each unfolding makes a rectangle whose diagonal is the path: {{sqrt(85)}}, {{sqrt(97)}}, {{sqrt(109)}}.", "Choose the minimum: {{sqrt(85)}}."] },
        { label: "Algebra shortcut", steps: ["With edges a ≥ b ≥ c, the options are {{a^2 + (b + c)^2}}, etc. Each expands to {{a^2 + b^2 + c^2 + 2 * (product of the paired edges)}}.", "Minimised by pairing the two smallest: {{2bc = 24}}, so {{36 + 16 + 9 + 24 = 85}}."] },
      ],
      commonError: "Giving the space diagonal {{sqrt(61)}} — the ant can't go through the box.",
      traps: [{ spec: { type: "expression", expr: "sqrt(61)" }, feedback: "That's the space diagonal — straight *through* the box. The ant must stay on the surface: unfold the faces." }],
      difficulty: "challenge",
      guideRef: "three-d",
      hints: [
        "The ant must cross two faces. What happens if you unfold them flat?",
        "On the flat net the shortest path is a straight line — the diagonal of a rectangle.",
        "There are three different ways to unfold. Compare {{(4 + 3)^2 + 6^2}}, {{(6 + 3)^2 + 4^2}} and {{(6 + 4)^2 + 3^2}}.",
      ],
      strategy: "Draw a diagram (unfold the net)",
    },
    {
      kind: "short",
      id: "pythagoras-trigonometry-ch-q08",
      question:
        "Triangle ABC has a right angle at C, angle BAC = 30° and BC = 1. The side CA is extended beyond A to a point D so that AD = AB.\n\nUse triangle BCD to find the exact value of tan 15°. Give your answer in the form {{a - sqrt(b)}}.",
      answer: { type: "expression", expr: "2-sqrt(3)", form: "surd", display: "{{2 - sqrt(3)}}" },
      solution: [
        "In the 30-60-90 triangle ABC with BC = 1: AB = 2 and {{AC = sqrt(3)}}.",
        "AD = AB = 2, so triangle ABD is isosceles and angle ADB = angle ABD.",
        "Exterior angle of triangle ABD at A: angle BAC = angle ADB + angle ABD, so 30° = 2 × angle ADB, giving angle ADB = 15°.",
        "Triangle BCD is right-angled at C with {{CD = 2 + sqrt(3)}} and BC = 1: {{tan 15° = 1/(2 + sqrt(3))}}.",
        "Rationalise: {{1/(2 + sqrt(3)) * (2 - sqrt(3))/(2 - sqrt(3)) = (2 - sqrt(3))/(4 - 3) = 2 - sqrt(3)}}.",
      ],
      solutions: [
        { label: "Isosceles construction", steps: ["As above: exterior angle gives 15°, then {{tan 15° = 1/(2 + sqrt(3)) = 2 - sqrt(3)}}."] },
        { label: "Check with a calculator", steps: ["{{2 - sqrt(3) = 0.26794...}} and tan 15° = 0.26794... ✓", "Bonus: in the same triangle, {{BD^2 = 1 + (2 + sqrt(3))^2 = 8 + 4sqrt(3)}}, which leads to exact values for sin 15° and cos 15° too."] },
      ],
      commonError: "Thinking angle ADB is 30° or 60°; the isosceles triangle halves the exterior 30° angle.",
      traps: [{ spec: { type: "expression", expr: "2+sqrt(3)" }, feedback: "{{2 + sqrt(3) ≈ 3.73}} is tan 75° — the angle at B in triangle BCD. You want the angle at D: opposite over adjacent is {{1/(2 + sqrt(3))}}." }],
      difficulty: "challenge",
      guideRef: "exact-values",
      hints: [
        "Find AB and AC exactly using the 30-60-90 triangle.",
        "Triangle ABD is isosceles. Use the exterior angle at A to find angle ADB.",
        "Angle ADB = 15°. In triangle BCD, CD = AC + AD = {{sqrt(3) + 2}}.",
        "{{tan 15° = 1/(2 + sqrt(3))}} — now rationalise the denominator.",
      ],
      strategy: "Construct a helpful triangle",
    },
    {
      kind: "short",
      id: "pythagoras-trigonometry-ch-q09",
      question:
        "ABCD is a square of side 6 cm. An equilateral triangle ABE is drawn inside the square on side AB.\n\nFind the exact length of CE. Give your answer in the form {{p sqrt(6) - q sqrt(2)}}, where p and q are integers.",
      answer: { type: "expression", expr: "3sqrt(6)-3sqrt(2)", form: "surd", display: "{{3sqrt(6) - 3sqrt(2)}} cm" },
      solution: [
        "Put A = (0, 0), B = (6, 0), C = (6, 6), D = (0, 6). E is above the midpoint of AB at height {{6 sin 60° = 3sqrt(3)}}: E = {{(3, 3sqrt(3))}}.",
        "From E to C: across 6 − 3 = 3, up {{6 - 3sqrt(3)}}.",
        "{{CE^2 = 3^2 + (6 - 3sqrt(3))^2 = 9 + 36 - 36sqrt(3) + 27 = 72 - 36sqrt(3)}}.",
        "Try {{(p sqrt(6) - q sqrt(2))^2 = 6p^2 + 2q^2 - 4pq sqrt(3)}}. Match: 4pq = 36 and {{6p^2 + 2q^2 = 72}} → p = q = 3.",
        "So {{CE = 3sqrt(6) - 3sqrt(2)}} cm (≈ 3.11 cm).",
      ],
      solutions: [
        { label: "Coordinates then match the form", steps: ["{{CE^2 = 72 - 36sqrt(3)}}; compare with {{(p sqrt(6) - q sqrt(2))^2}} to get p = q = 3."] },
        { label: "Angles and exact 15° values", steps: ["BE = BC = 6 and angle EBC = 90° − 60° = 30°, so triangle EBC is isosceles with apex angle 30°.", "Drop the perpendicular from B: {{CE = 2 * 6 sin 15°}}. With {{sin 15° = (sqrt(6) - sqrt(2))/4}}, {{CE = 3(sqrt(6) - sqrt(2))}}."] },
      ],
      commonError: "Taking the height of E as 3 (half the side) instead of {{3sqrt(3)}}.",
      traps: [{ spec: { type: "expression", expr: "3sqrt(2)" }, feedback: "That puts E at height 3 — half the side. E is the apex of an *equilateral* triangle, so its height is {{6 sin 60° = 3sqrt(3)}}." }],
      difficulty: "challenge",
      guideRef: "exact-values",
      hints: [
        "Use coordinates with A at the origin. Where exactly is E?",
        "E is at height {{3sqrt(3)}} above the midpoint of AB.",
        "Find {{CE^2}} — you should get {{72 - 36sqrt(3)}}.",
        "Expand {{(p sqrt(6) - q sqrt(2))^2}} and match the rational and {{sqrt(3)}} parts.",
      ],
      strategy: "Introduce coordinates",
    },
    {
      kind: "written",
      id: "pythagoras-trigonometry-ch-q10",
      question:
        "(a) Prove that for every whole number n > 1, the numbers {{n^2 - 1}}, 2n and {{n^2 + 1}} form a Pythagorean triple.\n\n(b) Use this to find a right-angled triangle with whole-number sides and hypotenuse 401.",
      marks: 3,
      modelAnswer:
        "(a) {{(n^2 - 1)^2 + (2n)^2 = n^4 - 2n^2 + 1 + 4n^2 = n^4 + 2n^2 + 1 = (n^2 + 1)^2}}.\n\nSo the squares of the two shorter numbers add to the square of the largest, and for n > 1 all three are positive whole numbers — a Pythagorean triple.\n\n(b) {{n^2 + 1 = 401}} gives {{n^2 = 400}}, n = 20. The triple is {{20^2 - 1 = 399}}, {{2 * 20 = 40}}, 401.\n\nCheck: {{399^2 + 40^2 = 159201 + 1600 = 160801 = 401^2}} ✓.",
      markScheme: [
        { point: "Expands (n² − 1)² + (2n)² = n⁴ + 2n² + 1", keywords: ["n^4 + 2n^2 + 1", "n⁴ + 2n² + 1", "n^4 - 2n^2 + 1", "4n^2", "4n²"] },
        { point: "Shows this equals (n² + 1)²", keywords: ["(n^2 + 1)^2", "(n² + 1)²", "= (n^2+1)^2"] },
        { point: "n = 20 giving 399, 40, 401", keywords: ["399", "40", "n = 20"] },
      ],
      commonError: "Checking a few values of n instead of proving it for all n — examples are not a proof.",
      difficulty: "challenge",
      guideRef: "pythagorean-triples",
      hints: [
        "You need to show (shorter)² + (shorter)² = (longest)² for every n — use algebra, not examples.",
        "Expand {{(n^2 - 1)^2}} and add {{(2n)^2}}.",
        "Does {{n^4 + 2n^2 + 1}} factorise as a perfect square?",
        "For (b), solve {{n^2 + 1 = 401}}.",
      ],
      strategy: "Prove it with algebra",
    },
  ],
};
