// Expanding, Factorising & Substitution — MCQ papers (3 × 15). Options are shuffled at display time.
import type { Paper } from "../../types.ts";

export const mcqPapers: Paper[] = [
  {
    id: "expand-factorise-m1",
    title: "MCQ Paper 1",
    questions: [
      {
        kind: "mcq",
        id: "expand-factorise-m1-q01",
        question: "Expand and simplify {{(x + 5)(x - 3)}}.",
        options: [
          "{{x^2 + 2x - 15}}",
          "{{x^2 - 15}}",
          "{{x^2 + 2x + 15}}",
          "{{x^2 - 2x - 15}}",
        ],
        answerIndex: 0,
        explanation:
          "Four products: {{x * x = x^2}}, {{x * (-3) = -3x}}, {{5 * x = 5x}}, {{5 * (-3) = -15}}. Collect: {{x^2 + 2x - 15}}. {{x^2 - 15}} multiplies only the firsts and the lasts and loses both middle terms; {{x^2 - 2x - 15}} gets the sign of {{-3x + 5x}} wrong.",
        difficulty: "warmup",
        guideRef: "expanding-brackets",
        hints: [
          "Every term in the first bracket multiplies every term in the second — that is four products.",
          "The two middle products are {{-3x}} and {{+5x}}.",
        ],
        strategy: "Use a grid",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m1-q02",
        question: "Factorise {{x^2 + 7x + 12}}.",
        options: [
          "{{(x + 2)(x + 6)}}",
          "{{(x + 3)(x + 4)}}",
          "{{(x + 1)(x + 12)}}",
          "{{(x - 3)(x - 4)}}",
        ],
        answerIndex: 1,
        explanation:
          "You need two numbers that **multiply** to 12 and **add** to 7: 3 and 4. {{(x + 2)(x + 6)}} multiplies to 12 but its middle term is {{8x}}; {{(x - 3)(x - 4)}} gives {{-7x}}, not {{+7x}}.",
        difficulty: "warmup",
        guideRef: "factorising-quadratics",
        hints: [
          "Find two numbers with product 12 and sum 7.",
          "List the factor pairs of 12: 1 × 12, 2 × 6, 3 × 4.",
        ],
        strategy: "Check by expanding",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m1-q03",
        question: "Work out the value of {{2a^2 - b}} when {{a = -3}} and {{b = 4}}.",
        options: [
          "−22",
          "32",
          "14",
          "−16",
        ],
        answerIndex: 2,
        explanation:
          "Square first: {{(-3)^2 = 9}}, so {{2 * 9 - 4 = 14}}. −22 comes from treating {{a^2}} as {{-3^2 = -9}}; 32 squares {{2a}} instead of just {{a}}, {{(-6)^2 - 4}}; −16 treats squaring as doubling.",
        difficulty: "warmup",
        guideRef: "substitution-formulae",
        hints: [
          "Indices come before multiplication — square {{a}} first.",
          "{{(-3)^2}} is positive: a negative times a negative.",
        ],
        strategy: "Use brackets when you substitute",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m1-q04",
        question: "{{f(x) = 3x - 7}}. Work out {{f(-2)}}.",
        options: [
          "−1",
          "1",
          "−27",
          "−13",
        ],
        answerIndex: 3,
        explanation:
          "Replace every {{x}} with {{(-2)}}: {{3 * (-2) - 7 = -6 - 7 = -13}}. −1 drops the negative sign ({{6 - 7}}); −27 treats the rule as {{3(x - 7)}}.",
        difficulty: "warmup",
        guideRef: "function-notation-basics",
        hints: [
          "{{f(-2)}} means: put −2 in wherever you see {{x}}.",
        ],
      },
      {
        kind: "mcq",
        id: "expand-factorise-m1-q05",
        question: "Expand and simplify {{(2x - 3)^2}}.",
        options: [
          "{{4x^2 - 12x + 9}}",
          "{{4x^2 + 9}}",
          "{{4x^2 - 6x + 9}}",
          "{{2x^2 - 12x + 9}}",
        ],
        answerIndex: 0,
        explanation:
          "{{(2x - 3)^2 = (2x - 3)(2x - 3) = 4x^2 - 6x - 6x + 9 = 4x^2 - 12x + 9}}. {{4x^2 + 9}} squares each term separately — the classic error; {{4x^2 - 6x + 9}} counts the middle product once instead of twice; {{2x^2}} forgets to square the 2.",
        difficulty: "core",
        guideRef: "expanding-brackets",
        hints: [
          "Write the square out as two brackets.",
          "There are two identical middle products, each {{-6x}}.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m1-q06",
        question: "Factorise fully {{6x^2 y - 9xy^2}}.",
        options: [
          "{{3x(2xy - 3y^2)}}",
          "{{3xy(2x - 3y)}}",
          "{{xy(6x - 9y)}}",
          "{{3xy(2x - 9y)}}",
        ],
        answerIndex: 1,
        explanation:
          "The HCF of the terms is {{3xy}} (HCF of 6 and 9 is 3; both terms contain {{x}} and {{y}}). Dividing out leaves {{2x - 3y}}. {{3x(2xy - 3y^2)}} and {{xy(6x - 9y)}} are correct but not *fully* factorised — the brackets still have a common factor. {{3xy(2x - 9y)}} forgets to divide 9 by 3.",
        difficulty: "core",
        guideRef: "factorising-quadratics",
        hints: [
          "Find the HCF of the numbers, then of each letter.",
          "Check the bracket left behind has no common factor.",
        ],
        strategy: "Check by expanding",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m1-q07",
        question: "Factorise {{2x^2 + 7x + 3}}.",
        options: [
          "{{(2x + 3)(x + 1)}}",
          "{{(x + 6)(x + 1)}}",
          "{{(2x + 1)(x + 3)}}",
          "{{(2x - 1)(x - 3)}}",
        ],
        answerIndex: 2,
        explanation:
          "{{ac = 6}}; numbers with product 6 and sum 7 are 6 and 1. Split: {{2x^2 + 6x + x + 3 = 2x(x + 3) + 1(x + 3) = (2x + 1)(x + 3)}}. {{(2x + 3)(x + 1)}} expands to {{2x^2 + 5x + 3}}; {{(x + 6)(x + 1)}} uses the split numbers directly and forgets the {{2x^2}}; {{(2x - 1)(x - 3)}} gives {{-7x}}.",
        difficulty: "core",
        guideRef: "factorising-quadratics",
        hints: [
          "Multiply {{a}} and {{c}}: what is {{2 * 3}}?",
          "Find two numbers with product 6 and sum 7, then split {{7x}}.",
          "Factorise in pairs: {{2x^2 + 6x}} and {{x + 3}}.",
        ],
        strategy: "Split the middle term",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m1-q08",
        question: "Write {{x^2 + 6x + 2}} in the form {{(x + p)^2 + q}}.",
        options: [
          "{{(x + 6)^2 - 34}}",
          "{{(x + 3)^2 + 11}}",
          "{{(x + 3)^2 + 2}}",
          "{{(x + 3)^2 - 7}}",
        ],
        answerIndex: 3,
        explanation:
          "Halve 6 to get 3: {{(x + 3)^2 = x^2 + 6x + 9}}, which is 9 too many, so {{x^2 + 6x + 2 = (x + 3)^2 - 9 + 2 = (x + 3)^2 - 7}}. {{(x + 6)^2 - 34}} does not halve the coefficient; {{(x + 3)^2 + 11}} adds the 9 instead of subtracting it; {{(x + 3)^2 + 2}} forgets to take the 9 away at all.",
        difficulty: "core",
        guideRef: "completing-the-square",
        hints: [
          "Halve the coefficient of {{x}}.",
          "Expand {{(x + 3)^2}} — what extra number appears that you didn't want?",
          "Take that extra 9 off, then add the 2.",
        ],
        strategy: "Check by expanding",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m1-q09",
        question: "Use {{v^2 = u^2 + 2as}} to work out {{v}} when {{u = 5}}, {{a = -3}} and {{s = 2.5}}. Take {{v}} to be positive and give your answer correct to 3 significant figures.",
        options: [
          "3.16",
          "6.32",
          "10",
          "4.18",
        ],
        answerIndex: 0,
        explanation:
          "{{v^2 = 25 + 2 * (-3) * 2.5 = 25 - 15 = 10}}, so {{v = sqrt(10) = 3.16}} (3 s.f.). 6.32 is {{sqrt(40)}} — the sign of {{a}} was ignored; 10 is {{v^2}}, not {{v}}; 4.18 is {{sqrt(17.5)}} from leaving out the 2 in {{2as}}.",
        difficulty: "core",
        guideRef: "substitution-formulae",
        hints: [
          "Substitute carefully: {{2as = 2 * (-3) * 2.5}}.",
          "You get {{v^2}} first — what do you still need to do?",
        ],
        strategy: "Use brackets when you substitute",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m1-q10",
        question: "{{f(x) = x^2 - 4x}}. Find the values of {{x}} for which {{f(x) = 12}}.",
        options: [
          "{{x = -6}} or {{x = 2}}",
          "{{x = 6}} or {{x = -2}}",
          "96",
          "{{x = 0}} or {{x = 4}}",
        ],
        answerIndex: 1,
        explanation:
          "Set {{x^2 - 4x = 12}}, so {{x^2 - 4x - 12 = 0}}, i.e. {{(x - 6)(x + 2) = 0}}: {{x = 6}} or {{x = -2}}. Check: {{f(6) = 36 - 24 = 12}}. 96 is {{f(12)}} — that treats 12 as the input rather than the output; {{x = 0}} or {{x = 4}} solves {{f(x) = 0}}; {{x = -6}} or {{x = 2}} has the signs swapped.",
        difficulty: "core",
        guideRef: "function-notation-basics",
        hints: [
          "{{f(x) = 12}} gives you the *output*. Write an equation.",
          "Rearrange to {{x^2 - 4x - 12 = 0}} and factorise.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m1-q11",
        question: "Expand and simplify {{(x + 1)(x - 2)(x + 3)}}.",
        options: [
          "{{x^3 - 6}}",
          "{{x^3 + 2x^2 - x - 6}}",
          "{{x^3 + 2x^2 - 5x - 6}}",
          "{{x^3 + 2x^2 + 5x - 6}}",
        ],
        answerIndex: 2,
        explanation:
          "First pair: {{(x + 1)(x - 2) = x^2 - x - 2}}. Then {{(x^2 - x - 2)(x + 3) = x^3 + 3x^2 - x^2 - 3x - 2x - 6 = x^3 + 2x^2 - 5x - 6}}. Check with {{x = 1}}: {{2 * (-1) * 4 = -8}} and {{1 + 2 - 5 - 6 = -8}}. {{x^3 - 6}} only multiplies firsts and lasts; {{x^3 + 2x^2 - x - 6}} loses one of the two {{x}} terms.",
        difficulty: "core",
        guideRef: "expanding-brackets",
        hints: [
          "Expand two of the brackets first.",
          "Multiply each of the three terms of {{x^2 - x - 2}} by {{x}} and then by 3 — six products.",
          "Collect: {{-3x - 2x}}.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m1-q12",
        question: "The kinetic energy of an object is {{E = 1/2 mv^2}}. Work out {{E}} when {{m = 0.4}} and {{v = -3}}.",
        options: [
          "−1.8",
          "3.6",
          "0.36",
          "1.8",
        ],
        answerIndex: 3,
        explanation:
          "{{v^2 = (-3)^2 = 9}}, so {{E = 0.5 * 0.4 * 9 = 1.8}}. −1.8 forgets that a negative squared is positive; 3.6 leaves out the {{1/2}}; 0.36 squares {{1/2 mv}} instead of just {{v}}.",
        difficulty: "core",
        guideRef: "substitution-formulae",
        hints: [
          "Which letter is squared — only {{v}}, or {{mv}}?",
          "{{(-3)^2 = 9}}. Now multiply by {{0.5 * 0.4}}.",
        ],
        strategy: "Use brackets when you substitute",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m1-q13",
        question: "Write {{2x^2 - 12x + 5}} in the form {{a(x + b)^2 + c}}.",
        options: [
          "{{2(x - 3)^2 - 13}}",
          "{{2(x - 3)^2 - 4}}",
          "{{2(x - 6)^2 - 67}}",
          "{{2(x - 3)^2 + 23}}",
        ],
        answerIndex: 0,
        explanation:
          "Take out the 2 from the {{x}} terms: {{2(x^2 - 6x) + 5 = 2[(x - 3)^2 - 9] + 5 = 2(x - 3)^2 - 18 + 5 = 2(x - 3)^2 - 13}}. {{2(x - 3)^2 - 4}} subtracts 9 instead of {{2 * 9 = 18}} — the 9 is inside the bracket that is multiplied by 2; {{2(x - 6)^2 - 67}} does not halve the 6; {{+23}} adds the 18.",
        difficulty: "challenge",
        guideRef: "completing-the-square",
        hints: [
          "Factor 2 out of {{2x^2 - 12x}} only.",
          "Complete the square inside: {{x^2 - 6x = (x - 3)^2 - 9}}.",
          "The {{-9}} is inside a bracket multiplied by 2 — multiply it out before adding 5.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m1-q14",
        question: "Factorise fully {{x^4 - 16}}.",
        options: [
          "{{(x^2 + 4)(x^2 - 4)}}",
          "{{(x^2 + 4)(x + 2)(x - 2)}}",
          "{{(x^2 - 4)^2}}",
          "{{(x - 2)^4}}",
        ],
        answerIndex: 1,
        explanation:
          "{{x^4 - 16 = (x^2)^2 - 4^2 = (x^2 + 4)(x^2 - 4)}}, and {{x^2 - 4}} is *again* a difference of two squares: {{(x + 2)(x - 2)}}. {{(x^2 + 4)(x^2 - 4)}} is correct but not fully factorised. {{(x^2 - 4)^2 = x^4 - 8x^2 + 16}} and {{(x - 2)^4}} also has middle terms — powers do not distribute over subtraction. ({{x^2 + 4}} cannot be factorised with real numbers.)",
        difficulty: "challenge",
        guideRef: "harder-algebra",
        hints: [
          "Write {{x^4}} as {{(x^2)^2}} and 16 as {{4^2}}.",
          "Use {{A^2 - B^2 = (A + B)(A - B)}}.",
          "Look at each bracket you get — can any be factorised again?",
        ],
        strategy: "Spot a difference of two squares",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m1-q15",
        question: "{{n}} is an integer. Which expression is **always** a multiple of 8?",
        options: [
          "{{n^2 + n}}",
          "{{(2n + 1)^2 + 1}}",
          "{{(n + 3)^2 - (n - 1)^2}}",
          "{{(n + 1)^2 - n^2}}",
        ],
        answerIndex: 2,
        explanation:
          "Difference of two squares: {{(n + 3)^2 - (n - 1)^2 = [(n + 3) - (n - 1)][(n + 3) + (n - 1)] = 4(2n + 2) = 8(n + 1)}} — always a multiple of 8. {{n^2 + n = n(n + 1)}} is always even but {{n = 1}} gives 2; {{(2n + 1)^2 + 1 = 4n^2 + 4n + 2}} is always 2 more than a multiple of 4; {{(n + 1)^2 - n^2 = 2n + 1}} is always odd.",
        difficulty: "challenge",
        guideRef: "harder-algebra",
        hints: [
          "Try {{n = 1}} and {{n = 2}} in each — which survive?",
          "For the survivor, simplify algebraically; don't trust a few cases.",
          "{{A^2 - B^2 = (A - B)(A + B)}} with {{A = n + 3}}, {{B = n - 1}}.",
        ],
        strategy: "Try small cases, then prove",
      },
    ],
  },
  {
    id: "expand-factorise-m2",
    title: "MCQ Paper 2",
    questions: [
      {
        kind: "mcq",
        id: "expand-factorise-m2-q01",
        question: "Expand and simplify {{3(2x - 1) - 2(x - 4)}}.",
        options: [
          "{{4x - 11}}",
          "{{4x + 5}}",
          "{{4x - 7}}",
          "{{8x + 5}}",
        ],
        answerIndex: 1,
        explanation:
          "{{6x - 3 - 2x + 8 = 4x + 5}}: the {{-2}} multiplies the {{-4}} to give {{+8}}. {{4x - 11}} writes {{-2 * -4}} as {{-8}}; {{4x - 7}} only multiplies the first term ({{-2x - 4}}); {{8x + 5}} turns {{-2x}} into {{+2x}}.",
        difficulty: "warmup",
        guideRef: "expanding-brackets",
        hints: [
          "The {{-2}} multiplies *both* terms in its bracket, sign included.",
        ],
      },
      {
        kind: "mcq",
        id: "expand-factorise-m2-q02",
        question: "Factorise {{x^2 - 49}}.",
        options: [
          "{{(x - 7)^2}}",
          "{{(x + 7)^2}}",
          "{{(x + 7)(x - 7)}}",
          "{{(x + 49)(x - 49)}}",
        ],
        answerIndex: 2,
        explanation:
          "Difference of two squares: {{x^2 - 7^2 = (x + 7)(x - 7)}}; the {{+7x}} and {{-7x}} cancel. {{(x - 7)^2 = x^2 - 14x + 49}} has a middle term; {{(x + 49)(x - 49) = x^2 - 2401}} forgets to square-root 49.",
        difficulty: "warmup",
        guideRef: "factorising-quadratics",
        hints: [
          "49 is a square number. What pattern is {{A^2 - B^2}}?",
        ],
        strategy: "Spot a difference of two squares",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m2-q03",
        question: "Work out the value of {{6ab + a^2}} when {{a = 1/2}} and {{b = -1/3}}.",
        options: [
          "{{5/4}}",
          "0",
          "{{-5/4}}",
          "{{-3/4}}",
        ],
        answerIndex: 3,
        explanation:
          "{{6 * 1/2 * (-1/3) = -1}} and {{(1/2)^2 = 1/4}}, so the total is {{-1 + 1/4 = -3/4}}. {{5/4}} ignores the negative {{b}}; 0 treats {{a^2}} as {{2a = 1}}; {{-5/4}} subtracts {{a^2}} instead of adding it.",
        difficulty: "warmup",
        guideRef: "substitution-formulae",
        hints: [
          "Do the two parts separately: {{6ab}}, then {{a^2}}.",
          "{{(1/2)^2 = 1/4}}, not 1.",
        ],
        strategy: "Use brackets when you substitute",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m2-q04",
        question: "{{f(x) = x^2 + 1}}. Work out {{f(-3)}}.",
        options: [
          "10",
          "−8",
          "−5",
          "4",
        ],
        answerIndex: 0,
        explanation:
          "{{f(-3) = (-3)^2 + 1 = 9 + 1 = 10}}. −8 comes from {{-3^2 = -9}} (squaring without the bracket); −5 doubles instead of squaring; 4 works out {{(-3 + 1)^2}}.",
        difficulty: "warmup",
        guideRef: "function-notation-basics",
        hints: [
          "Put {{(-3)}} in a bracket before squaring.",
        ],
        strategy: "Use brackets when you substitute",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m2-q05",
        question: "Factorise {{x^2 - 3x - 28}}.",
        options: [
          "{{(x + 7)(x - 4)}}",
          "{{(x - 7)(x + 4)}}",
          "{{(x - 14)(x + 2)}}",
          "{{(x - 7)(x - 4)}}",
        ],
        answerIndex: 1,
        explanation:
          "Product −28 and sum −3: −7 and 4. Check: {{-7x + 4x = -3x}}. {{(x + 7)(x - 4)}} gives {{+3x}}; {{(x - 14)(x + 2)}} gives {{-12x}}; {{(x - 7)(x - 4)}} gives {{+28}}.",
        difficulty: "core",
        guideRef: "factorising-quadratics",
        hints: [
          "The product is negative, so one number is negative and one positive.",
          "The sum is −3, so the bigger number is the negative one.",
        ],
        strategy: "Check by expanding",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m2-q06",
        question: "Factorise {{6x^2 - x - 2}}.",
        options: [
          "{{(3x + 2)(2x - 1)}}",
          "{{(6x + 1)(x - 2)}}",
          "{{(3x - 2)(2x + 1)}}",
          "{{(x - 4)(x + 3)}}",
        ],
        answerIndex: 2,
        explanation:
          "{{ac = -12}}; −4 and 3 have product −12 and sum −1. Split: {{6x^2 - 4x + 3x - 2 = 2x(3x - 2) + 1(3x - 2) = (3x - 2)(2x + 1)}}. {{(3x + 2)(2x - 1)}} gives {{+x}}; {{(6x + 1)(x - 2)}} gives {{-11x}}; {{(x - 4)(x + 3)}} uses the split numbers and forgets the 6.",
        difficulty: "core",
        guideRef: "factorising-quadratics",
        hints: [
          "Work out {{ac = 6 * (-2)}}.",
          "Find two numbers with product −12 and sum −1.",
          "Split {{-x}} as {{-4x + 3x}} and factorise in pairs.",
        ],
        strategy: "Split the middle term",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m2-q07",
        question: "By completing the square, find the coordinates of the turning point of {{y = x^2 - 10x + 30}}.",
        options: [
          "(−5, 5)",
          "(5, 30)",
          "(5, −5)",
          "(5, 5)",
        ],
        answerIndex: 3,
        explanation:
          "{{x^2 - 10x + 30 = (x - 5)^2 - 25 + 30 = (x - 5)^2 + 5}}. The square is never negative and is 0 when {{x = 5}}, so the minimum point is (5, 5). (−5, 5) reads the sign in the bracket wrongly; (5, 30) uses the original constant; (5, −5) works out {{25 - 30}} instead of {{-25 + 30}}.",
        difficulty: "core",
        guideRef: "completing-the-square",
        hints: [
          "Write it as {{(x - 5)^2 + q}}.",
          "What value of {{x}} makes {{(x - 5)^2}} as small as possible?",
        ],
        strategy: "Complete the square",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m2-q08",
        question: "Expand and simplify {{(2x + 1)(x - 3)(x + 2)}}.",
        options: [
          "{{2x^3 - x^2 - 13x - 6}}",
          "{{2x^3 - 6}}",
          "{{2x^3 - x^2 - 10x - 6}}",
          "{{2x^3 + 9x^2 + 7x - 6}}",
        ],
        answerIndex: 0,
        explanation:
          "{{(2x + 1)(x - 3) = 2x^2 - 5x - 3}}. Then {{(2x^2 - 5x - 3)(x + 2) = 2x^3 + 4x^2 - 5x^2 - 10x - 3x - 6 = 2x^3 - x^2 - 13x - 6}}. Check {{x = 1}}: {{3 * (-2) * 3 = -18}} and {{2 - 1 - 13 - 6 = -18}}. {{2x^3 - x^2 - 10x - 6}} drops the {{-3x}}; {{2x^3 + 9x^2 + 7x - 6}} comes from a sign slip giving {{2x^2 + 5x - 3}} for the first pair.",
        difficulty: "core",
        guideRef: "expanding-brackets",
        hints: [
          "Expand any two brackets first.",
          "Multiply each term of the quadratic by {{x}}, then by 2.",
          "Check your answer by putting {{x = 1}} into both forms.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m2-q09",
        question: "A ball is thrown upwards. Its displacement is {{s = ut + 1/2 at^2}}. Work out {{s}} when {{u = 12}}, {{t = 3}} and {{a = -9.8}}.",
        options: [
          "80.1",
          "−8.1",
          "21.3",
          "252.1",
        ],
        answerIndex: 1,
        explanation:
          "{{ut = 36}} and {{1/2 at^2 = 0.5 * (-9.8) * 9 = -44.1}}, so {{s = 36 - 44.1 = -8.1}} (the ball is below its starting point). 80.1 ignores the minus sign on {{a}}; 21.3 forgets to square {{t}}; 252.1 squares {{1/2 at}} instead of only {{t}}.",
        difficulty: "core",
        guideRef: "substitution-formulae",
        hints: [
          "Work out the two terms separately.",
          "Only {{t}} is squared: {{t^2 = 9}}.",
        ],
        strategy: "Use brackets when you substitute",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m2-q10",
        question: "{{f(x) = 2x + 3}}. Find and simplify an expression for {{f(a + 1)}}.",
        options: [
          "{{2a + 4}}",
          "{{2a^2 + 5a + 3}}",
          "{{2a + 5}}",
          "{{a + 4}}",
        ],
        answerIndex: 2,
        explanation:
          "Replace {{x}} with {{(a + 1)}}: {{2(a + 1) + 3 = 2a + 2 + 3 = 2a + 5}}. {{2a + 4}} comes either from {{2a + 1 + 3}} (forgetting the bracket) or from {{f(a) + 1}}; {{2a^2 + 5a + 3}} multiplies {{f(a)}} by {{a + 1}}; {{a + 4}} forgets the coefficient 2.",
        difficulty: "core",
        guideRef: "function-notation-basics",
        hints: [
          "Every {{x}} becomes {{(a + 1)}} — in a bracket.",
          "Expand {{2(a + 1)}}.",
        ],
      },
      {
        kind: "mcq",
        id: "expand-factorise-m2-q11",
        question: "{{g(x) = 3/(x - 2)}}. Find {{x}} when {{g(x) = 6}}.",
        options: [
          "0.5",
          "0.75",
          "20",
          "2.5",
        ],
        answerIndex: 3,
        explanation:
          "{{3/(x - 2) = 6}} gives {{x - 2 = 3/6 = 0.5}}, so {{x = 2.5}}. Check: {{3/0.5 = 6}}. 0.5 stops at {{x - 2}}; 0.75 is {{g(6)}}, using 6 as the input; 20 comes from {{x - 2 = 3 * 6}}.",
        difficulty: "core",
        guideRef: "function-notation-basics",
        hints: [
          "6 is the output. Write the equation {{3/(x - 2) = 6}}.",
          "Multiply both sides by {{(x - 2)}}, then divide by 6.",
        ],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m2-q12",
        question: "Write {{x^2 + 5x + 1}} in the form {{(x + p)^2 + q}}.",
        options: [
          "{{(x + 5/2)^2 - 21/4}}",
          "{{(x + 5/2)^2 + 29/4}}",
          "{{(x + 5)^2 - 24}}",
          "{{(x + 5/2)^2 - 3/2}}",
        ],
        answerIndex: 0,
        explanation:
          "Halve 5: {{(x + 5/2)^2 = x^2 + 5x + 25/4}}, so subtract {{25/4}}: {{1 - 25/4 = -21/4}}. {{+29/4}} adds the {{25/4}}; {{(x + 5)^2 - 24}} does not halve; {{-3/2}} subtracts {{5/2}} instead of its square.",
        difficulty: "core",
        guideRef: "completing-the-square",
        hints: [
          "Half of 5 is {{5/2}} — fractions are fine.",
          "What constant appears when you expand {{(x + 5/2)^2}}?",
          "Write 1 as {{4/4}} before subtracting {{25/4}}.",
        ],
        strategy: "Check by expanding",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m2-q13",
        question: "Factorise fully {{(x + 3)^2 - (x - 1)^2}}.",
        options: [
          "{{4(2x + 2)}}",
          "{{8(x + 1)}}",
          "{{2(2x + 5)}}",
          "{{8(x + 2)}}",
        ],
        answerIndex: 1,
        explanation:
          "Treat it as {{P^2 - Q^2}} with {{P = x + 3}}, {{Q = x - 1}}: {{(P - Q)(P + Q) = 4(2x + 2) = 8(x + 1)}}. {{4(2x + 2)}} is right but not fully factorised; {{2(2x + 5)}} comes from expanding and subtracting {{x^2 - 2x + 1}} without changing all its signs ({{4x + 10}}); {{8(x + 2)}} adds the brackets as {{2x + 4}}.",
        difficulty: "challenge",
        guideRef: "harder-algebra",
        hints: [
          "This is {{A^2 - B^2}} with brackets for {{A}} and {{B}}.",
          "{{A - B = (x + 3) - (x - 1)}} — careful with the minus.",
          "Look for a common factor in what's left.",
        ],
        strategy: "Spot a difference of two squares",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m2-q14",
        question: "Factorise fully {{x^4 - 5x^2 + 4}}.",
        options: [
          "{{(x^2 - 1)(x^2 - 4)}}",
          "{{(x^2 + 1)(x^2 + 4)}}",
          "{{(x - 1)(x + 1)(x - 2)(x + 2)}}",
          "{{(x - 1)(x - 4)}}",
        ],
        answerIndex: 2,
        explanation:
          "It is a quadratic in {{x^2}}: with {{y = x^2}}, {{y^2 - 5y + 4 = (y - 1)(y - 4)}}, so {{(x^2 - 1)(x^2 - 4)}}. Both brackets are differences of two squares, giving {{(x - 1)(x + 1)(x - 2)(x + 2)}}. {{(x^2 - 1)(x^2 - 4)}} stops too early; {{(x^2 + 1)(x^2 + 4)}} expands to {{x^4 + 5x^2 + 4}}; {{(x - 1)(x - 4)}} forgets that the variable is {{x^2}}.",
        difficulty: "challenge",
        guideRef: "harder-algebra",
        hints: [
          "Let {{y = x^2}}. What does the expression become?",
          "Factorise {{y^2 - 5y + 4}}, then put {{x^2}} back.",
          "Can either bracket be factorised again?",
        ],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m2-q15",
        question: "{{y = 5 + 4x - x^2}}. By completing the square, which statement is true?",
        options: [
          "The minimum value of {{y}} is 9, when {{x = 2}}.",
          "The maximum value of {{y}} is 1, when {{x = 2}}.",
          "The maximum value of {{y}} is 9, when {{x = -2}}.",
          "The maximum value of {{y}} is 9, when {{x = 2}}.",
        ],
        answerIndex: 3,
        explanation:
          "{{5 + 4x - x^2 = 5 - (x^2 - 4x) = 5 - [(x - 2)^2 - 4] = 9 - (x - 2)^2}}. Since {{(x - 2)^2 >= 0}}, {{y}} is at most 9, reached at {{x = 2}}. The {{-x^2}} makes it a maximum, not a minimum; 1 comes from {{5 - 4}} — forgetting that the minus outside the bracket flips {{-4}} to {{+4}}; {{x = -2}} misreads the bracket.",
        difficulty: "challenge",
        guideRef: "completing-the-square",
        hints: [
          "Take out −1 from the {{x}} terms: {{-(x^2 - 4x)}}.",
          "Complete the square inside, then distribute the minus sign carefully.",
          "Something minus a square — is that a maximum or a minimum?",
        ],
        strategy: "Complete the square",
      },
    ],
  },
  {
    id: "expand-factorise-m3",
    title: "MCQ Paper 3 — Exam style",
    questions: [
      {
        kind: "mcq",
        id: "expand-factorise-m3-q01",
        question: "Expand and simplify {{(3x + 2)(x - 5)}}.",
        options: [
          "{{3x^2 - 10}}",
          "{{3x^2 - 17x - 10}}",
          "{{3x^2 - 13x - 10}}",
          "{{3x^2 + 13x - 10}}",
        ],
        answerIndex: 2,
        explanation:
          "{{3x^2 - 15x + 2x - 10 = 3x^2 - 13x - 10}}. {{3x^2 - 10}} misses the middle products; {{-17x}} treats {{+2x}} as {{-2x}}; {{+13x}} flips the sign of the total.",
        difficulty: "warmup",
        guideRef: "expanding-brackets",
        hints: [
          "Four products: {{3x * x}}, {{3x * (-5)}}, {{2 * x}}, {{2 * (-5)}}.",
        ],
        strategy: "Use a grid",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m3-q02",
        question: "Use {{c = sqrt(a^2 + b^2)}} to work out {{c}} when {{a = 2.4}} and {{b = 1.8}}.",
        options: [
          "4.2",
          "9",
          "2.05",
          "3",
        ],
        answerIndex: 3,
        explanation:
          "{{a^2 + b^2 = 5.76 + 3.24 = 9}}, so {{c = sqrt(9) = 3}}. 4.2 just adds {{a + b}} — a square root does not undo squares term by term; 9 forgets the square root; 2.05 is {{sqrt(2.4 + 1.8)}}, forgetting to square.",
        difficulty: "warmup",
        guideRef: "substitution-formulae",
        hints: [
          "Square each value, add, then square-root the total.",
        ],
      },
      {
        kind: "mcq",
        id: "expand-factorise-m3-q03",
        question: "Factorise {{x^2 + x - 20}}.",
        options: [
          "{{(x + 5)(x - 4)}}",
          "{{(x - 5)(x + 4)}}",
          "{{(x + 10)(x - 2)}}",
          "{{(x + 5)(x + 4)}}",
        ],
        answerIndex: 0,
        explanation:
          "Product −20 and sum +1: 5 and −4. {{(x - 5)(x + 4)}} gives {{-x}}; {{(x + 10)(x - 2)}} gives {{+8x}}; {{(x + 5)(x + 4)}} gives {{+20}}.",
        difficulty: "warmup",
        guideRef: "factorising-quadratics",
        hints: [
          "Find two numbers with product −20 and sum +1.",
        ],
        strategy: "Check by expanding",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m3-q04",
        question: "{{f(x) = 4 - 3x}}. Find {{x}} when {{f(x) = 19}}.",
        options: [
          "5",
          "−5",
          "−53",
          "{{-23/3}}",
        ],
        answerIndex: 1,
        explanation:
          "{{4 - 3x = 19}}, so {{-3x = 15}} and {{x = -5}}. Check: {{4 - 3 * (-5) = 19}}. −53 is {{f(19)}}, using 19 as the input; 5 loses the sign when dividing by −3; {{-23/3}} adds 4 to 19 instead of subtracting it ({{-3x = 23}}).",
        difficulty: "warmup",
        guideRef: "function-notation-basics",
        hints: [
          "19 is the output, so solve {{4 - 3x = 19}}.",
          "Divide by −3 carefully.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m3-q05",
        question: "{{(x - 1)(x + 3)(2x - 1)}} can be written in the form {{ax^3 + bx^2 + cx + d}}. Which is the correct expansion?",
        options: [
          "{{2x^3 + 3x^2 - 4x + 3}}",
          "{{2x^3 + 3}}",
          "{{2x^3 + 3x^2 - 8x + 3}}",
          "{{2x^3 + 5x^2 - 8x + 3}}",
        ],
        answerIndex: 2,
        explanation:
          "{{(x - 1)(x + 3) = x^2 + 2x - 3}}. Then {{(x^2 + 2x - 3)(2x - 1) = 2x^3 - x^2 + 4x^2 - 2x - 6x + 3 = 2x^3 + 3x^2 - 8x + 3}}. Check {{x = 2}}: {{1 * 5 * 3 = 15}} and {{16 + 12 - 16 + 3 = 15}}. {{-4x}} comes from writing {{-2x}} as {{+2x}}; {{5x^2}} from writing {{-x^2}} as {{+x^2}}; {{2x^3 + 3}} only multiplies firsts and lasts.",
        difficulty: "core",
        guideRef: "expanding-brackets",
        hints: [
          "Expand two brackets first.",
          "You should have six products before collecting.",
          "Substitute {{x = 2}} to check.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m3-q06",
        question: "Factorise {{3x^2 - 14x + 8}}.",
        options: [
          "{{(3x - 4)(x - 2)}}",
          "{{(3x + 2)(x + 4)}}",
          "{{(x - 12)(x - 2)}}",
          "{{(3x - 2)(x - 4)}}",
        ],
        answerIndex: 3,
        explanation:
          "{{ac = 24}}; −12 and −2 have product 24 and sum −14. {{3x^2 - 12x - 2x + 8 = 3x(x - 4) - 2(x - 4) = (3x - 2)(x - 4)}}. {{(3x - 4)(x - 2)}} gives {{-10x}}; {{(3x + 2)(x + 4)}} gives {{+14x}}; {{(x - 12)(x - 2)}} uses the split numbers without the 3.",
        difficulty: "core",
        guideRef: "factorising-quadratics",
        hints: [
          "{{ac = 3 * 8 = 24}}. Product 24, sum −14?",
          "Split {{-14x}} as {{-12x - 2x}}.",
          "Factorise in pairs; the brackets must match.",
        ],
        strategy: "Split the middle term",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m3-q07",
        question: "For all values of {{x}}, {{x^2 - 8x + 21 = (x - a)^2 + b}}. Find the values of {{a}} and {{b}}.",
        options: [
          "{{a = 4}}, {{b = 5}}",
          "{{a = -4}}, {{b = 5}}",
          "{{a = 8}}, {{b = -43}}",
          "{{a = 4}}, {{b = 37}}",
        ],
        answerIndex: 0,
        explanation:
          "{{(x - 4)^2 = x^2 - 8x + 16}}, so {{x^2 - 8x + 21 = (x - 4)^2 + 5}}: {{a = 4}}, {{b = 5}}. The form already has a minus sign, so {{a = -4}} double-counts it; {{a = 8}} does not halve; {{b = 37}} adds 16 instead of subtracting it.",
        difficulty: "core",
        guideRef: "completing-the-square",
        hints: [
          "Halve −8.",
          "The bracket is {{(x - a)}} — so what is {{a}} itself?",
          "{{21 - 16 = ?}}",
        ],
        strategy: "Compare coefficients",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m3-q08",
        question: "The lens formula is {{1/f = 1/u + 1/v}}. Work out {{f}} when {{u = 12}} and {{v = 6}}.",
        options: [
          "18",
          "4",
          "{{1/4}}",
          "9",
        ],
        answerIndex: 1,
        explanation:
          "{{1/f = 1/12 + 1/6 = 1/12 + 2/12 = 3/12 = 1/4}}, so {{f = 4}}. {{1/4}} is {{1/f}} — you still have to flip it; 18 adds {{u + v}} as if reciprocals add like whole numbers; 9 is the mean of 12 and 6.",
        difficulty: "core",
        guideRef: "substitution-formulae",
        hints: [
          "Add the fractions with a common denominator.",
          "You have found {{1/f}}. What is {{f}}?",
        ],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m3-q09",
        question: "{{f(x) = 2x^2 - 3}}. Work out {{f(3) - f(-3)}}.",
        options: [
          "36",
          "−18",
          "0",
          "30",
        ],
        answerIndex: 2,
        explanation:
          "{{f(3) = 18 - 3 = 15}} and {{f(-3) = 2 * 9 - 3 = 15}}, so the difference is 0 — squaring hides the sign. 36 uses {{f(-3) = -21}} (squaring −3 to −9); −18 uses {{(2 * -3)^2 - 3 = 33}}; 30 adds instead of subtracting.",
        difficulty: "core",
        guideRef: "function-notation-basics",
        hints: [
          "Work out each value separately.",
          "{{2x^2}} means {{2 * x^2}}: square first, then double.",
        ],
        strategy: "Use symmetry",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m3-q10",
        question: "The garden bed is a rectangle measuring {{(2x + 3)}} m by {{(x - 1)}} m. Which expression gives its area in m²?",
        diagram: `<svg viewBox="0 0 300 170" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="A rectangular garden bed with length (2x + 3) metres along the bottom and width (x − 1) metres up the side"><rect x="0" y="0" width="300" height="170" fill="#ffffff"/><rect x="50" y="25" width="200" height="100" fill="#bbf7d0" stroke="#1f2937" stroke-width="2"/><polyline points="50,113 62,113 62,125" fill="none" stroke="#1f2937" stroke-width="1.5"/><text x="150" y="150" font-size="14" font-family="sans-serif" text-anchor="middle" fill="#1f2937">(2x + 3) m</text><text x="258" y="80" font-size="14" font-family="sans-serif" fill="#1f2937">(x − 1) m</text><text x="150" y="80" font-size="13" font-family="sans-serif" text-anchor="middle" fill="#334155">Garden bed</text></svg>`,
        options: [
          "{{2x^2 - 3}}",
          "{{6x + 4}}",
          "{{2x^2 + 5x - 3}}",
          "{{2x^2 + x - 3}}",
        ],
        answerIndex: 3,
        explanation:
          "Area = length × width = {{(2x + 3)(x - 1) = 2x^2 - 2x + 3x - 3 = 2x^2 + x - 3}}. {{6x + 4}} is the *perimeter*, {{2(3x + 2)}}; {{2x^2 - 3}} misses the middle products; {{+5x}} treats {{-2x}} as {{+2x}}.",
        difficulty: "core",
        guideRef: "expanding-brackets",
        hints: [
          "Area of a rectangle = length × width.",
          "Expand {{(2x + 3)(x - 1)}} — four products.",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m3-q11",
        question: "Temperatures convert using {{F = 9/5 C + 32}}. Work out {{F}} when {{C = -12.5}}.",
        options: [
          "9.5",
          "54.5",
          "35.1",
          "−22.5",
        ],
        answerIndex: 0,
        explanation:
          "{{9/5 * (-12.5) = -22.5}}, then {{-22.5 + 32 = 9.5}}. 54.5 loses the minus sign; 35.1 adds 32 first and then multiplies by {{9/5}} (wrong order of operations); −22.5 forgets to add 32.",
        difficulty: "core",
        guideRef: "substitution-formulae",
        hints: [
          "Multiply before you add.",
          "{{9/5 * (-12.5)}} is negative.",
        ],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m3-q12",
        question: "Which of these is a factor of {{4x^2 - 25}}?",
        options: [
          "{{4x - 5}}",
          "{{2x - 5}}",
          "{{x - 5}}",
          "{{2x - 25}}",
        ],
        answerIndex: 1,
        explanation:
          "{{4x^2 - 25 = (2x)^2 - 5^2 = (2x + 5)(2x - 5)}}. The square root of {{4x^2}} is {{2x}}, not {{4x}} or {{x}}; {{2x - 25}} forgets to square-root 25.",
        difficulty: "core",
        guideRef: "factorising-quadratics",
        hints: [
          "Both terms are perfect squares. What squares to give {{4x^2}}?",
          "Use {{A^2 - B^2 = (A + B)(A - B)}}.",
        ],
        strategy: "Spot a difference of two squares",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m3-q13",
        question: "{{n}} is an integer. Simplify {{(2n + 1)^2 - (2n - 1)^2}}. What does your answer show?",
        options: [
          "2, so the difference is always 2",
          "{{4n}}, so the difference is always a multiple of 4 but not always of 8",
          "{{8n}}, so the difference is always a multiple of 8",
          "{{8n + 2}}, so the difference is always even but never a multiple of 4",
        ],
        answerIndex: 2,
        explanation:
          "{{(4n^2 + 4n + 1) - (4n^2 - 4n + 1) = 8n}} (or by difference of two squares: {{2 * 4n = 8n}}). So the difference of the squares of two consecutive odd numbers is always a multiple of 8 — e.g. {{5^2 - 3^2 = 16}}. 2 comes from squaring each term separately; {{4n}} uses a middle term of {{2n}} instead of {{4n}}; {{8n + 2}} adds the 1s instead of subtracting.",
        difficulty: "challenge",
        guideRef: "harder-algebra",
        hints: [
          "Try {{n = 1}}: {{3^2 - 1^2}}. Try {{n = 2}}.",
          "Expand each square fully (three terms each).",
          "Or use {{A^2 - B^2 = (A - B)(A + B)}}.",
        ],
        strategy: "Try small cases, then prove",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m3-q14",
        question: "Factorise fully {{3x^3 - 12x}}.",
        options: [
          "{{3x(x^2 - 4)}}",
          "{{3x(x - 2)^2}}",
          "{{3(x + 2)(x - 2)}}",
          "{{3x(x + 2)(x - 2)}}",
        ],
        answerIndex: 3,
        explanation:
          "Common factor first: {{3x(x^2 - 4)}}, then difference of two squares: {{3x(x + 2)(x - 2)}}. {{3x(x^2 - 4)}} stops too early — an exam would give only partial credit; {{3x(x - 2)^2}} expands to {{3x^3 - 12x^2 + 12x}}; {{3(x + 2)(x - 2)}} loses the factor {{x}}.",
        difficulty: "challenge",
        guideRef: "harder-algebra",
        hints: [
          "Take out the highest common factor first.",
          "Look at what is left in the bracket — is it a special form?",
        ],
        strategy: "Common factor first",
      },
      {
        kind: "mcq",
        id: "expand-factorise-m3-q15",
        question: "The expression {{3x^2 + 12x + k}} has a minimum value of 5. Find the value of {{k}}.",
        options: [
          "17",
          "9",
          "−7",
          "5",
        ],
        answerIndex: 0,
        explanation:
          "{{3x^2 + 12x + k = 3(x^2 + 4x) + k = 3[(x + 2)^2 - 4] + k = 3(x + 2)^2 + k - 12}}. The minimum is {{k - 12 = 5}}, so {{k = 17}}. 9 subtracts 4 instead of {{3 * 4 = 12}}; −7 works out {{5 - 12}}; 5 confuses the constant term with the minimum value.",
        difficulty: "challenge",
        guideRef: "completing-the-square",
        hints: [
          "Complete the square in terms of {{k}}.",
          "Take 3 out of {{3x^2 + 12x}} first.",
          "The minimum value is the constant left after completing the square; set it equal to 5.",
        ],
        strategy: "Work backwards",
      },
    ],
  },
];
