import type { TopicPractice } from "../../types.ts";

export const practice: TopicPractice = {
  // =========================================================================
  // QUICK QUIZ — 10 questions: 3 mcq, 7 short
  // =========================================================================
  quiz: [
    {
      kind: "short",
      id: "expand-factorise-quiz-q01",
      question: "Expand and simplify (x + 5)(x − 3).",
      answer: { type: "expression", expr: "x^2+2x-15", form: "expanded", display: "{{x^2 + 2x - 15}}" },
      solution: [
        "Multiply every term in the first bracket by every term in the second:",
        "x × x = {{x^2}}, x × (−3) = −3x, 5 × x = 5x, 5 × (−3) = −15.",
        "Collect the x-terms: −3x + 5x = 2x.",
        "{{x^2 + 2x - 15}}",
      ],
      commonError: "Multiplying only the first terms and the last terms, giving {{x^2 - 15}} and losing the middle term.",
      traps: [
        { spec: { type: "expression", expr: "x^2-15" }, feedback: "You've multiplied firsts and lasts only. There are four products: the two 'outer' and 'inner' ones make the x-term." },
        { spec: { type: "expression", expr: "x^2-2x-15" }, feedback: "Check the sign of the x-term: −3x + 5x = +2x." },
      ],
      difficulty: "warmup",
      guideRef: "expanding-brackets",
      hints: ["Every term in the first bracket multiplies every term in the second — four products.", "The two x-terms are −3x and +5x. Combine them."],
      strategy: "Use a grid",
    },
    {
      kind: "mcq",
      id: "expand-factorise-quiz-q02",
      question: "Factorise {{x^2 - 11x + 18}}.",
      options: ["(x − 2)(x − 9)", "(x + 2)(x + 9)", "(x − 3)(x − 6)", "(x − 1)(x − 18)"],
      answerIndex: 0,
      explanation:
        "You need two numbers that **multiply to +18** and **add to −11**: −2 and −9. So {{x^2 - 11x + 18 = (x-2)(x-9)}}. (x + 2)(x + 9) has the right product but adds to +11, giving +11x. (x − 3)(x − 6) multiplies to 18 but adds to −9. (x − 1)(x − 18) multiplies to 18 but adds to −19.",
      difficulty: "warmup",
      guideRef: "factorising-quadratics",
      hints: ["Find two numbers that multiply to 18 and add to −11.", "A positive product with a negative sum means both numbers are negative."],
      strategy: "Check by expanding",
    },
    {
      kind: "short",
      id: "expand-factorise-quiz-q03",
      question: "Expand and simplify {{(2x - 3)^2}}.",
      answer: { type: "expression", expr: "4x^2-12x+9", form: "expanded", display: "{{4x^2 - 12x + 9}}" },
      solution: [
        "Write it as two brackets: (2x − 3)(2x − 3).",
        "2x × 2x = {{4x^2}}; 2x × (−3) = −6x; (−3) × 2x = −6x; (−3) × (−3) = +9.",
        "{{4x^2 - 12x + 9}}",
      ],
      commonError: "Squaring each term separately: {{(2x-3)^2}} is NOT {{4x^2 - 9}} (or {{4x^2 + 9}}).",
      traps: [
        { spec: { type: "expression", expr: "4x^2+9" }, feedback: "You squared each term on its own. {{(2x-3)^2}} means (2x − 3)(2x − 3) — there are two −6x terms in the middle." },
        { spec: { type: "expression", expr: "4x^2-9" }, feedback: "That's the difference of two squares, which comes from (2x − 3)(2x + 3). Here both brackets are (2x − 3)." },
        { spec: { type: "expression", expr: "2x^2-12x+9" }, feedback: "Square the 2 as well: 2x × 2x = {{4x^2}}." },
      ],
      difficulty: "core",
      guideRef: "expanding-brackets",
      hints: ["Squaring a bracket means multiplying it by itself. Write it out twice.", "You should get two middle terms, both −6x.", "Collect: {{4x^2}} − 6x − 6x + 9."],
      strategy: "Write it out in full",
    },
    {
      kind: "short",
      id: "expand-factorise-quiz-q04",
      question: "Factorise {{3x^2 - 11x - 4}}.",
      answer: { type: "expression", expr: "(3x+1)(x-4)", form: "factorised", display: "(3x + 1)(x − 4)" },
      solution: [
        "a × c = 3 × (−4) = −12. Find two numbers that multiply to −12 and add to −11: −12 and +1.",
        "Split the middle term: {{3x^2 - 12x + x - 4}}.",
        "Group: 3x(x − 4) + 1(x − 4).",
        "Common bracket: (3x + 1)(x − 4).",
      ],
      solutions: [
        { label: "Trial of brackets", steps: ["The brackets must start (3x …)(x …).", "The numbers multiply to −4: try +1 and −4.", "(3x + 1)(x − 4): outer −12x, inner +x, total −11x. ✓"] },
      ],
      commonError: "Getting the signs the wrong way round: (3x − 1)(x + 4) gives +11x.",
      traps: [
        { spec: { type: "expression", expr: "(3x-1)(x+4)" }, feedback: "Expand to check: that gives {{3x^2 + 11x - 4}}. Swap the signs." },
        { spec: { type: "expression", expr: "(3x-4)(x+1)" }, feedback: "Right numbers, wrong positions: (3x − 4)(x + 1) gives −x. The 4 must multiply the 3x." },
      ],
      difficulty: "core",
      guideRef: "factorising-quadratics",
      hints: ["When a ≠ 1, start with a × c = 3 × (−4).", "Two numbers multiplying to −12 and adding to −11.", "−12 and +1: split −11x into −12x + x and factorise in pairs."],
      strategy: "Split the middle term",
    },
    {
      kind: "short",
      id: "expand-factorise-quiz-q05",
      question: "Write {{x^2 + 8x + 5}} in the form {{(x + a)^2 + b}}. Give the values of a and b, a first.",
      answer: { type: "list", values: [4, -11], ordered: true, display: "a = 4, b = −11" },
      solution: [
        "Halve the coefficient of x: 8 ÷ 2 = 4, so start with {{(x+4)^2}}.",
        "{{(x+4)^2 = x^2 + 8x + 16}}, which is 16 too much compared with {{x^2 + 8x}}.",
        "{{x^2 + 8x + 5 = (x+4)^2 - 16 + 5 = (x+4)^2 - 11}}.",
      ],
      commonError: "Adding the 16 instead of subtracting it.",
      traps: [
        { spec: { type: "list", values: [4, 21], ordered: true }, feedback: "{{(x+4)^2}} already contains +16, so you must *take away* 16 to compensate: 5 − 16 = −11." },
        { spec: { type: "list", values: [8, 5], ordered: true }, feedback: "a is *half* the coefficient of x. Expand {{(x+8)^2}} — it gives 16x, not 8x." },
      ],
      difficulty: "core",
      guideRef: "completing-the-square",
      hints: ["What number goes in the bracket? Halve the x-coefficient.", "Expand {{(x+4)^2}}. How does it compare with {{x^2 + 8x}}?", "Subtract the extra 16, then add the 5."],
      strategy: "Compare with what you want",
    },
    {
      kind: "mcq",
      id: "expand-factorise-quiz-q06",
      question: "Kinetic energy is given by {{E = 1/2 m v^2}}. Work out E when m = 0.4 and v = −5.",
      options: ["−5", "1", "5", "−1"],
      answerIndex: 2,
      explanation:
        "Square v first: {{(-5)^2 = 25}}. Then {{E = 1/2 * 0.4 * 25 = 0.2 * 25 = 5}}. −5 comes from typing −5² into a calculator without brackets (giving −25). 1 comes from squaring the whole product {{(1/2 * 0.4 * (-5))^2}}. −1 comes from forgetting to square v at all.",
      difficulty: "core",
      guideRef: "substitution-formulae",
      hints: ["Which part of the formula is squared — just v, or more?", "Use brackets on the calculator: {{(-5)^2}}.", "Then multiply 25 by {{1/2}} and 0.4."],
      strategy: "Brackets round negatives",
    },
    {
      kind: "short",
      id: "expand-factorise-quiz-q07",
      question: "{{f(x) = 3x^2 - 2x}}. Find f(−2).",
      answer: { type: "number", value: 16 },
      solution: ["Replace every x with (−2): {{f(-2) = 3(-2)^2 - 2(-2)}}.", "{{(-2)^2 = 4}}, so 3 × 4 = 12.", "−2 × (−2) = +4.", "12 + 4 = 16."],
      commonError: "Writing 3 × (−2)² as −12, or −2 × (−2) as −4.",
      traps: [
        { spec: { type: "number", value: 8 }, feedback: "Check the second term: −2 × (−2) = **+4**, not −4." },
        { spec: { type: "number", value: -8 }, feedback: "{{(-2)^2}} is +4, so 3 × 4 = +12. A negative number squared is positive." },
        { spec: { type: "number", value: 40 }, feedback: "Only x is squared, not 3x. Square −2 first, then multiply by 3." },
      ],
      difficulty: "warmup",
      guideRef: "function-notation-basics",
      hints: ["f(−2) means: put −2 in place of every x.", "Use brackets: {{3(-2)^2 - 2(-2)}}."],
      strategy: "Brackets round negatives",
    },
    {
      kind: "short",
      id: "expand-factorise-quiz-q08",
      question: "{{g(x) = 5 - 2x}}. Find the value of x for which g(x) = 17.",
      answer: { type: "number", value: -6 },
      solution: ["Set up an equation: 5 − 2x = 17.", "Subtract 5: −2x = 12.", "Divide by −2: x = −6.", "Check: g(−6) = 5 − 2(−6) = 5 + 12 = 17. ✓"],
      commonError: "Working out g(17) instead of solving g(x) = 17.",
      traps: [
        { spec: { type: "number", value: -29 }, feedback: "That's g(17) — the output when the *input* is 17. Here 17 is the *output*: solve 5 − 2x = 17." },
        { spec: { type: "number", value: 6 }, feedback: "Watch the sign when you divide by −2: −2x = 12 gives x = −6." },
      ],
      difficulty: "core",
      guideRef: "function-notation-basics",
      hints: ["Is 17 the input or the output here?", "Write 5 − 2x = 17 and solve it.", "−2x = 12. Divide carefully by −2."],
      strategy: "Use the inverse",
    },
    {
      kind: "short",
      id: "expand-factorise-quiz-q09",
      question: "{{(x+3)^2 - (x-1)^2}} can be written as k(x + 1), where k is an integer. Find k.",
      answer: { type: "number", value: 8 },
      solution: [
        "Difference of two squares: {{A^2 - B^2 = (A - B)(A + B)}} with A = x + 3, B = x − 1.",
        "A − B = (x + 3) − (x − 1) = 4.",
        "A + B = (x + 3) + (x − 1) = 2x + 2 = 2(x + 1).",
        "So the expression is 4 × 2(x + 1) = 8(x + 1), and k = 8.",
      ],
      solutions: [
        { label: "Expand both squares", steps: ["{{(x+3)^2 = x^2 + 6x + 9}}; {{(x-1)^2 = x^2 - 2x + 1}}.", "Subtract: {{x^2 + 6x + 9 - x^2 + 2x - 1 = 8x + 8}}.", "8x + 8 = 8(x + 1), so k = 8."] },
      ],
      commonError: "Writing A − B = (x + 3) − x − 1 = 2: the bracket around (x − 1) changes −1 to +1.",
      traps: [{ spec: { type: "number", value: 4 }, feedback: "When subtracting (x − 1), both signs change: (x + 3) − (x − 1) = x + 3 − x + 1 = 4. Then multiply by A + B = 2(x + 1)." }],
      difficulty: "core",
      guideRef: "harder-algebra",
      hints: ["The expression is a difference of two squares, {{A^2 - B^2}}.", "{{A^2 - B^2 = (A - B)(A + B)}}. Work out A − B and A + B with A = x + 3, B = x − 1.", "A − B = 4 and A + B = 2x + 2."],
      strategy: "Spot the structure",
    },
    {
      kind: "mcq",
      id: "expand-factorise-quiz-q10",
      question: "Which is the factorised form of {{49x^2 - 4}}?",
      options: ["{{(7x - 2)^2}}", "(49x − 2)(49x + 2)", "(7x − 4)(7x + 1)", "(7x − 2)(7x + 2)"],
      answerIndex: 3,
      explanation:
        "{{49x^2 = (7x)^2}} and {{4 = 2^2}}, so it is a difference of two squares: (7x − 2)(7x + 2). The ±14x middle terms cancel. {{(7x-2)^2}} expands to {{49x^2 - 28x + 4}}, which has a middle term and +4. (49x − 2)(49x + 2) gives {{2401x^2 - 4}}: you need the square *root* of {{49x^2}}. (7x − 4)(7x + 1) gives {{49x^2 - 21x - 4}}.",
      difficulty: "core",
      guideRef: "factorising-quadratics",
      hints: ["Is each term a perfect square? What are their square roots?", "{{a^2 - b^2 = (a - b)(a + b)}} with a = 7x and b = 2."],
      strategy: "Spot the structure",
    },
  ],

  // =========================================================================
  // PRACTICE PAPERS
  // =========================================================================
  papers: [
    {
      id: "expand-factorise-p1",
      title: "Practice Paper 1",
      questions: [
        {
          kind: "short",
          id: "expand-factorise-p1-q01",
          question: "Expand and simplify 3(2x + 1) − 2(x − 4).",
          answer: { type: "expression", expr: "4x+11", form: "simplified", display: "4x + 11" },
          solution: ["3(2x + 1) = 6x + 3.", "−2(x − 4) = −2x + 8 (negative × negative is positive).", "6x + 3 − 2x + 8 = 4x + 11."],
          commonError: "Writing −2 × −4 as −8.",
          traps: [{ spec: { type: "expression", expr: "4x-5" }, feedback: "The −2 multiplies the −4 too: −2 × (−4) = **+8**." }],
          difficulty: "warmup",
          guideRef: "expanding-brackets",
          hints: ["Treat the second bracket as being multiplied by −2, not 2.", "−2 × (−4) = +8."],
          strategy: "Watch the signs",
        },
        {
          kind: "short",
          id: "expand-factorise-p1-q02",
          question: "Factorise fully {{6x^2 y - 15x y^2}}.",
          answer: { type: "expression", expr: "3xy(2x-5y)", form: "factorised", display: "3xy(2x − 5y)" },
          solution: ["HCF of 6 and 15 is 3.", "Both terms contain at least one x and one y, so the HCF is 3xy.", "{{6x^2 y ÷ 3xy = 2x}} and {{15x y^2 ÷ 3xy = 5y}}.", "3xy(2x − 5y)"],
          commonError: "Taking out only 3 or 3x, which leaves a common factor inside the bracket.",
          difficulty: "warmup",
          guideRef: "factorising-quadratics",
          hints: ["Find the HCF of the numbers, then of each letter.", "The HCF is 3xy. Divide each term by it."],
          strategy: "Check by expanding",
        },
        {
          kind: "short",
          id: "expand-factorise-p1-q03",
          question: "Factorise {{x^2 + 2x - 24}}.",
          answer: { type: "expression", expr: "(x+6)(x-4)", form: "factorised", display: "(x + 6)(x − 4)" },
          solution: ["Two numbers that multiply to −24 and add to +2: +6 and −4.", "(x + 6)(x − 4)", "Check: {{x^2 - 4x + 6x - 24 = x^2 + 2x - 24}}. ✓"],
          commonError: "Getting the signs swapped: (x − 6)(x + 4) gives −2x.",
          traps: [{ spec: { type: "expression", expr: "(x-6)(x+4)" }, feedback: "Expand to check: that gives {{x^2 - 2x - 24}}. The larger number needs to be positive to make +2x." }],
          difficulty: "warmup",
          guideRef: "factorising-quadratics",
          hints: ["Product −24, sum +2.", "One number is positive, one negative — the larger one is positive."],
          strategy: "Check by expanding",
        },
        {
          kind: "short",
          id: "expand-factorise-p1-q04",
          question: "Work out the value of {{5a - 3b^2}} when a = −2 and b = −3.",
          answer: { type: "number", value: -37 },
          solution: ["5a = 5 × (−2) = −10.", "{{b^2 = (-3)^2 = 9}}, so {{3b^2 = 27}}.", "−10 − 27 = −37."],
          commonError: "Squaring −3b (giving 81) instead of squaring b only, or treating (−3)² as −9.",
          traps: [
            { spec: { type: "number", value: 17 }, feedback: "{{(-3)^2}} is +9, not −9. So you subtract 27: −10 − 27." },
            { spec: { type: "number", value: -91 }, feedback: "Only b is squared, not 3b. Index first: {{b^2 = 9}}, then multiply by 3." },
          ],
          difficulty: "warmup",
          guideRef: "substitution-formulae",
          hints: ["Powers before multiplication (BIDMAS): square b first.", "Put negatives in brackets: {{3(-3)^2}}."],
          strategy: "Brackets round negatives",
        },
        {
          kind: "short",
          id: "expand-factorise-p1-q05",
          question: "Expand and simplify (x + 2)(x − 3)(2x + 1).",
          answer: { type: "expression", expr: "2x^3-x^2-13x-6", form: "expanded", display: "{{2x^3 - x^2 - 13x - 6}}" },
          solution: [
            "First two brackets: (x + 2)(x − 3) = {{x^2 - x - 6}}.",
            "Multiply by (2x + 1): {{2x(x^2 - x - 6) + 1(x^2 - x - 6)}}.",
            "{{= 2x^3 - 2x^2 - 12x + x^2 - x - 6}}.",
            "Collect: {{2x^3 - x^2 - 13x - 6}}.",
          ],
          commonError: "Losing a term when multiplying a three-term bracket — there should be 6 products before collecting.",
          traps: [{ spec: { type: "expression", expr: "2x^3-x^2-11x-6" }, feedback: "Recheck the x-terms: −12x − x = −13x." }],
          difficulty: "core",
          guideRef: "expanding-brackets",
          hints: ["Expand two of the brackets first.", "(x + 2)(x − 3) = {{x^2 - x - 6}}. Now multiply each of its three terms by 2x and by 1.", "You should have six terms before collecting like terms."],
          strategy: "Make it simpler",
        },
        {
          kind: "short",
          id: "expand-factorise-p1-q06",
          question: "Factorise {{6x^2 - 7x - 3}}.",
          answer: { type: "expression", expr: "(3x+1)(2x-3)", form: "factorised", display: "(3x + 1)(2x − 3)" },
          solution: [
            "a × c = 6 × (−3) = −18. Two numbers multiplying to −18 and adding to −7: −9 and +2.",
            "{{6x^2 - 9x + 2x - 3}}",
            "3x(2x − 3) + 1(2x − 3)",
            "(3x + 1)(2x − 3)",
          ],
          commonError: "Only trying (6x …)(x …): the 6 can also split as 3 × 2.",
          traps: [{ spec: { type: "expression", expr: "(3x-1)(2x+3)" }, feedback: "That expands to {{6x^2 + 7x - 3}} — the signs are swapped." }],
          difficulty: "core",
          guideRef: "factorising-quadratics",
          hints: ["Work out a × c.", "You need two numbers that multiply to −18 and add to −7.", "−9 and +2. Split −7x into −9x + 2x and group in pairs."],
          strategy: "Split the middle term",
        },
        {
          kind: "short",
          id: "expand-factorise-p1-q07",
          question: "Write {{2x^2 + 12x + 7}} in the form {{a(x + b)^2 + c}}. Give a, b and c in that order.",
          answer: { type: "list", values: [2, 3, -11], ordered: true, display: "a = 2, b = 3, c = −11" },
          solution: [
            "Take out the 2 from the x-terms: {{2(x^2 + 6x) + 7}}.",
            "Complete the square inside: {{x^2 + 6x = (x+3)^2 - 9}}.",
            "{{2[(x+3)^2 - 9] + 7 = 2(x+3)^2 - 18 + 7}}.",
            "{{= 2(x+3)^2 - 11}}.",
          ],
          commonError: "Forgetting to multiply the −9 by the 2 outside, which gives c = −2.",
          traps: [
            { spec: { type: "list", values: [2, 3, -2], ordered: true }, feedback: "The −9 is inside the 2( ) — it becomes −18 when you multiply out. 7 − 18 = −11." },
            { spec: { type: "list", values: [2, 6, -11], ordered: true }, feedback: "After factoring out 2 the bracket is {{x^2 + 6x}}, so b is half of 6." },
          ],
          difficulty: "core",
          guideRef: "completing-the-square",
          hints: ["Factor 2 out of the first two terms only.", "Complete the square on {{x^2 + 6x}}.", "Multiply out the outer 2 carefully: 2 × (−9) = −18."],
          strategy: "Make it simpler",
        },
        {
          kind: "short",
          id: "expand-factorise-p1-q08",
          question: "{{v^2 = u^2 + 2as}}. A car slows down with u = 12, a = −2.5 and s = 20. Work out the positive value of v. Give your answer correct to 3 significant figures.",
          answer: { type: "number", value: 6.63, tolerance: 0.005 },
          solution: ["{{v^2 = 12^2 + 2(-2.5)(20)}}", "{{= 144 - 100 = 44}}", "{{v = sqrt(44) = 6.6332...}}", "v = 6.63 (3 s.f.)"],
          commonError: "Forgetting the minus sign on a, giving {{v^2 = 244}}.",
          traps: [
            { spec: { type: "number", value: 15.6, tolerance: 0.05 }, feedback: "a is negative (the car slows down): 2 × (−2.5) × 20 = −100, not +100." },
            { spec: { type: "number", value: 44 }, feedback: "That's {{v^2}}. Square-root to find v." },
          ],
          difficulty: "core",
          guideRef: "substitution-formulae",
          hints: ["Substitute into the right-hand side first, with brackets round −2.5.", "{{v^2 = 144 - 100}}.", "Now square-root."],
          strategy: "Brackets round negatives",
        },
        {
          kind: "short",
          id: "expand-factorise-p1-q09",
          question: "{{T = (2a + b)/(a - b)}}. Work out the value of T when a = {{3/4}} and b = −{{1/2}}. Give your answer as a fraction in its simplest form.",
          answer: { type: "fraction", n: 4, d: 5, simplest: true, allowDecimal: true },
          solution: [
            "Numerator: {{2 * 3/4 + (-1/2) = 3/2 - 1/2 = 1}}.",
            "Denominator: {{3/4 - (-1/2) = 3/4 + 2/4 = 5/4}}.",
            "{{T = 1 ÷ 5/4 = 4/5}}.",
          ],
          commonError: "Treating a − b as {{3/4 - 1/2 = 1/4}}: subtracting a negative means adding.",
          traps: [{ spec: { type: "number", value: 4 }, feedback: "Check the denominator: {{3/4 - (-1/2)}} is {{3/4 + 1/2 = 5/4}}, not {{1/4}}." }],
          difficulty: "core",
          guideRef: "substitution-formulae",
          hints: ["Work out the top and the bottom separately.", "Subtracting −{{1/2}} is the same as adding {{1/2}}.", "Then divide: {{1 ÷ 5/4}}."],
          strategy: "Split into parts",
        },
        {
          kind: "short",
          id: "expand-factorise-p1-q10",
          question: "{{f(x) = x^2 - 4x}}. Find and simplify f(a + 1).",
          answer: { type: "expression", expr: "a^2-2a-3", form: "expanded", display: "{{a^2 - 2a - 3}}" },
          solution: [
            "Replace every x with (a + 1): {{f(a+1) = (a+1)^2 - 4(a+1)}}.",
            "{{= a^2 + 2a + 1 - 4a - 4}}.",
            "{{= a^2 - 2a - 3}}.",
          ],
          commonError: "Working out f(a) + 1 instead of f(a + 1).",
          traps: [
            { spec: { type: "expression", expr: "a^2-4a+1" }, feedback: "That's f(a) + 1. f(a + 1) means the *input* is a + 1: replace every x with (a + 1)." },
            { spec: { type: "expression", expr: "a^2-4a-3" }, feedback: "{{(a+1)^2 = a^2 + 2a + 1}} — you've lost the 2a." },
          ],
          difficulty: "core",
          guideRef: "function-notation-basics",
          hints: ["f(a + 1): what goes in place of each x?", "{{(a+1)^2 - 4(a+1)}}. Expand both parts.", "Collect: 2a − 4a = −2a and 1 − 4 = −3."],
          strategy: "Substitute a bracket",
        },
        {
          kind: "written",
          id: "expand-factorise-p1-q11",
          question: "n is an integer. Prove that {{(n+3)^2 - (n-3)^2}} is always a multiple of 12.",
          marks: 3,
          modelAnswer:
            "{{(n+3)^2 = n^2 + 6n + 9}} and {{(n-3)^2 = n^2 - 6n + 9}}.\n\nSubtracting: {{n^2 + 6n + 9 - n^2 + 6n - 9 = 12n}}.\n\n12n = 12 × n and n is an integer, so the expression is always a multiple of 12.",
          markScheme: [
            { point: "Expands both brackets correctly (or uses difference of two squares: (6)(2n))", keywords: ["n^2 + 6n + 9", "n^2 - 6n + 9", "6n", "(6)(2n)", "difference of two squares"] },
            { point: "Simplifies to 12n", keywords: ["12n"] },
            { point: "Concludes: 12 × an integer, so a multiple of 12", keywords: ["12 ×", "multiple of 12", "integer", "factor of 12"] },
          ],
          commonError: "Subtracting (n − 3)² without changing the sign of every term, giving 18 or 12n + 18.",
          solutions: [
            { label: "Difference of two squares", steps: ["{{A^2 - B^2 = (A - B)(A + B)}} with A = n + 3, B = n − 3.", "A − B = 6, A + B = 2n.", "Product = 12n, a multiple of 12."] },
          ],
          difficulty: "core",
          guideRef: "harder-algebra",
          hints: ["Expand both squares, or spot a difference of two squares.", "Be careful subtracting the whole of {{(n-3)^2}}.", "Show the answer is 12 × (something that is an integer)."],
          strategy: "Spot the structure",
        },
        {
          kind: "written",
          id: "expand-factorise-p1-q12",
          question: "Priya says that {{2x^2 - 5x - 3 = (2x - 1)(x + 3)}}.\n\nShow that Priya is wrong, explain her mistake and give the correct factorisation.",
          marks: 3,
          modelAnswer:
            "Expanding Priya's brackets: {{(2x-1)(x+3) = 2x^2 + 6x - x - 3 = 2x^2 + 5x - 3}}, which has +5x, not −5x, so she is wrong.\n\nHer numbers are right but the signs are swapped.\n\nCorrect: a × c = −6; −6 and +1 add to −5, so {{2x^2 - 6x + x - 3 = 2x(x - 3) + 1(x - 3) = (2x + 1)(x - 3)}}.",
          markScheme: [
            { point: "Expands (2x − 1)(x + 3) to show it gives 2x² + 5x − 3", keywords: ["2x^2 + 5x - 3", "+5x", "5x", "6x - x"] },
            { point: "Identifies the mistake: signs are the wrong way round", keywords: ["sign", "signs", "wrong way", "swapped", "opposite"] },
            { point: "Correct factorisation (2x + 1)(x − 3)", keywords: ["(2x + 1)(x - 3)", "(2x+1)(x-3)", "(x - 3)(2x + 1)"] },
          ],
          commonError: "Just stating the correct answer without showing why Priya's version is wrong.",
          difficulty: "core",
          guideRef: "factorising-quadratics",
          hints: ["Expand Priya's answer. What do you get?", "Which term is different from the original?", "Keep the numbers 1 and 3 but think about which one is negative."],
          strategy: "Check by expanding",
        },
        {
          kind: "written",
          id: "expand-factorise-p1-q13",
          question: "Show that {{x^2 - 8x + 19}} is positive for all values of x.",
          marks: 3,
          modelAnswer:
            "Completing the square: {{x^2 - 8x + 19 = (x-4)^2 - 16 + 19 = (x-4)^2 + 3}}.\n\nA square is never negative, so {{(x-4)^2 >= 0}} for every x.\n\nTherefore {{(x-4)^2 + 3 >= 3 > 0}}, so the expression is always positive (its minimum value is 3, when x = 4).",
          markScheme: [
            { point: "Completes the square: (x − 4)² + 3", keywords: ["(x - 4)^2 + 3", "(x-4)^2+3", "(x - 4)²", "+ 3"] },
            { point: "States that a square is always ≥ 0", keywords: ["≥ 0", ">= 0", "never negative", "square", "at least 0", "non-negative"] },
            { point: "Concludes the expression is ≥ 3, so always positive", keywords: ["≥ 3", ">= 3", "minimum", "at least 3", "always positive", "> 0"] },
          ],
          commonError: "Testing a few values of x — that cannot prove it for *all* x.",
          difficulty: "challenge",
          guideRef: "completing-the-square",
          hints: ["Trying numbers can't prove 'for all x'. What form reveals the smallest value?", "Complete the square.", "What is the smallest possible value of {{(x-4)^2}}?"],
          strategy: "Consider extremes",
        },
        {
          kind: "short",
          id: "expand-factorise-p1-q14",
          question: "{{x^4 - 13x^2 + 36}} can be written as (x − a)(x + a)(x − b)(x + b), where a and b are positive integers and a < b. Find a and b. Give a first.",
          answer: { type: "list", values: [2, 3], ordered: true, display: "a = 2, b = 3" },
          solution: [
            "Treat it as a quadratic in {{x^2}}: let {{y = x^2}}, so it is {{y^2 - 13y + 36}}.",
            "{{y^2 - 13y + 36 = (y - 4)(y - 9)}}.",
            "So {{x^4 - 13x^2 + 36 = (x^2 - 4)(x^2 - 9)}}.",
            "Each bracket is a difference of two squares: (x − 2)(x + 2)(x − 3)(x + 3).",
            "a = 2, b = 3.",
          ],
          commonError: "Stopping at {{(x^2 - 4)(x^2 - 9)}}: each bracket factorises again.",
          traps: [{ spec: { type: "list", values: [4, 9], ordered: true }, feedback: "Those are the values of {{x^2}}. The factors {{x^2 - 4}} and {{x^2 - 9}} split again: a and b are their square roots." }],
          difficulty: "challenge",
          guideRef: "harder-algebra",
          hints: ["Look at the powers: 4 and 2. This is a quadratic in disguise.", "Let {{y = x^2}}. Factorise {{y^2 - 13y + 36}}.", "You get {{(x^2 - 4)(x^2 - 9)}}. Can each of those factorise?"],
          strategy: "Introduce a variable",
        },
        {
          kind: "short",
          id: "expand-factorise-p1-q15",
          question: "{{x^2 + kx + 20}} can be factorised as (x + m)(x + n), where k, m and n are all integers. How many different values of k are possible?",
          answer: { type: "number", value: 6 },
          solution: [
            "Expanding: (x + m)(x + n) = {{x^2 + (m + n)x + mn}}, so mn = 20 and k = m + n.",
            "Factor pairs of 20: 1 × 20, 2 × 10, 4 × 5, giving k = 21, 12, 9.",
            "Both negative also works: (−1)(−20), (−2)(−10), (−4)(−5), giving k = −21, −12, −9.",
            "That is 6 values of k.",
          ],
          commonError: "Forgetting the negative factor pairs.",
          traps: [{ spec: { type: "number", value: 3 }, feedback: "Two negative numbers also multiply to +20 — e.g. (x − 4)(x − 5)." }],
          difficulty: "challenge",
          guideRef: "factorising-quadratics",
          hints: ["Expand (x + m)(x + n). How are m and n related to 20 and to k?", "mn = 20 and k = m + n. List the factor pairs of 20.", "Don't forget pairs of negative numbers."],
          strategy: "Split into cases",
        },
      ],
    },
    {
      id: "expand-factorise-p2",
      title: "Practice Paper 2",
      questions: [
        {
          kind: "short",
          id: "expand-factorise-p2-q01",
          question: "Expand and simplify (x − 7)(x + 2).",
          answer: { type: "expression", expr: "x^2-5x-14", form: "expanded", display: "{{x^2 - 5x - 14}}" },
          solution: ["{{x^2 + 2x - 7x - 14}}", "{{x^2 - 5x - 14}}"],
          commonError: "Writing −7 × 2 as +14.",
          traps: [{ spec: { type: "expression", expr: "x^2-5x+14" }, feedback: "(−7) × (+2) = −14." }],
          difficulty: "warmup",
          guideRef: "expanding-brackets",
          hints: ["Four products: x × x, x × 2, −7 × x, −7 × 2.", "Collect +2x − 7x."],
          strategy: "Use a grid",
        },
        {
          kind: "short",
          id: "expand-factorise-p2-q02",
          question: "Factorise {{x^2 - 9x + 20}}.",
          answer: { type: "expression", expr: "(x-4)(x-5)", form: "factorised", display: "(x − 4)(x − 5)" },
          solution: ["Two numbers multiplying to +20 and adding to −9: −4 and −5.", "(x − 4)(x − 5)"],
          commonError: "Choosing +4 and +5, which add to +9.",
          traps: [{ spec: { type: "expression", expr: "(x+4)(x+5)" }, feedback: "That expands to {{x^2 + 9x + 20}}. You need a sum of −9." }],
          difficulty: "warmup",
          guideRef: "factorising-quadratics",
          hints: ["Product +20, sum −9.", "Positive product and negative sum: both numbers are negative."],
        },
        {
          kind: "short",
          id: "expand-factorise-p2-q03",
          question: "Work out the value of {{(a^2 - b)/(2c)}} when a = −4, b = 6 and c = −5.",
          answer: { type: "number", value: -1 },
          solution: ["{{a^2 = (-4)^2 = 16}}.", "Numerator: 16 − 6 = 10.", "Denominator: 2 × (−5) = −10.", "10 ÷ (−10) = −1."],
          commonError: "Writing {{(-4)^2}} as −16.",
          traps: [
            { spec: { type: "number", value: 2.2 }, feedback: "{{(-4)^2 = +16}}: a negative number squared is positive." },
            { spec: { type: "number", value: 1 }, feedback: "Check the sign of the denominator: 2 × (−5) = −10." },
          ],
          difficulty: "warmup",
          guideRef: "substitution-formulae",
          hints: ["Work out the top and bottom separately.", "{{(-4)^2}} — use brackets on your calculator."],
          strategy: "Brackets round negatives",
        },
        {
          kind: "short",
          id: "expand-factorise-p2-q04",
          question: "{{f(x) = 2x^3 - 5}}. Find f(−2).",
          answer: { type: "number", value: -21 },
          solution: ["{{f(-2) = 2(-2)^3 - 5}}", "{{(-2)^3 = -8}}", "2 × (−8) − 5 = −16 − 5 = −21."],
          commonError: "Treating {{(-2)^3}} as +8: an odd power of a negative is negative.",
          traps: [
            { spec: { type: "number", value: 11 }, feedback: "{{(-2)^3 = (-2)(-2)(-2) = -8}}. An odd power keeps the minus sign." },
            { spec: { type: "number", value: -69 }, feedback: "Only x is cubed, not 2x: cube −2 first, then double." },
          ],
          difficulty: "warmup",
          guideRef: "function-notation-basics",
          hints: ["Replace x with (−2).", "What is (−2) × (−2) × (−2)?"],
        },
        {
          kind: "short",
          id: "expand-factorise-p2-q05",
          question: "Expand and simplify {{(2x + 3)(x - 4) - (x - 5)^2}}.",
          answer: { type: "expression", expr: "x^2+5x-37", form: "simplified", display: "{{x^2 + 5x - 37}}" },
          solution: [
            "{{(2x+3)(x-4) = 2x^2 - 8x + 3x - 12 = 2x^2 - 5x - 12}}.",
            "{{(x-5)^2 = x^2 - 10x + 25}}.",
            "Subtract the whole of it: {{2x^2 - 5x - 12 - x^2 + 10x - 25}}.",
            "{{= x^2 + 5x - 37}}.",
          ],
          commonError: "Only changing the sign of the first term when subtracting {{(x-5)^2}}.",
          traps: [
            { spec: { type: "expression", expr: "x^2-15x+13" }, feedback: "When you subtract {{x^2 - 10x + 25}}, *every* sign changes: −x² + 10x − 25." },
            { spec: { type: "expression", expr: "x^2-5x-37" }, feedback: "Check the x-terms: −5x − (−10x) = +5x." },
          ],
          difficulty: "core",
          guideRef: "expanding-brackets",
          hints: ["Expand each part separately first.", "Put the expansion of {{(x-5)^2}} in a bracket before subtracting it.", "−(x² − 10x + 25) = −x² + 10x − 25."],
          strategy: "Make it simpler",
        },
        {
          kind: "short",
          id: "expand-factorise-p2-q06",
          question: "Factorise {{10x^2 + 11x - 6}}.",
          answer: { type: "expression", expr: "(5x-2)(2x+3)", form: "factorised", display: "(5x − 2)(2x + 3)" },
          solution: [
            "a × c = 10 × (−6) = −60. Two numbers multiplying to −60 and adding to +11: +15 and −4.",
            "{{10x^2 + 15x - 4x - 6}}",
            "5x(2x + 3) − 2(2x + 3)",
            "(5x − 2)(2x + 3)",
          ],
          commonError: "Only trying (10x …)(x …) — 10 also splits as 5 × 2.",
          traps: [{ spec: { type: "expression", expr: "(5x+2)(2x-3)" }, feedback: "That expands to {{10x^2 - 11x - 6}}: swap the signs." }],
          difficulty: "core",
          guideRef: "factorising-quadratics",
          hints: ["a × c = −60.", "Which pair multiplies to −60 and adds to +11?", "+15 and −4. Split 11x into 15x − 4x and group."],
          strategy: "Split the middle term",
        },
        {
          kind: "short",
          id: "expand-factorise-p2-q07",
          question: "{{3x^2 - 12x - 36}} can be factorised fully as a(x + b)(x + c), where a, b and c are integers and b > c. Find a, b and c. Give them in that order.",
          answer: { type: "list", values: [3, 2, -6], ordered: true, display: "a = 3, b = 2, c = −6" },
          solution: [
            "Common factor first: {{3(x^2 - 4x - 12)}}.",
            "Two numbers multiplying to −12 and adding to −4: −6 and +2.",
            "{{3(x+2)(x-6)}}, so a = 3, b = 2, c = −6.",
          ],
          commonError: "Not taking out the common factor 3 first, then struggling with a ≠ 1.",
          traps: [{ spec: { type: "list", values: [3, 6, -2], ordered: true }, feedback: "Check: (x + 6)(x − 2) gives +4x. You need −4x, so it's (x + 2)(x − 6)." }],
          difficulty: "core",
          guideRef: "factorising-quadratics",
          hints: ["Is there a common factor in all three terms?", "Take out 3, then factorise {{x^2 - 4x - 12}}.", "Product −12, sum −4."],
          strategy: "Make it simpler",
        },
        {
          kind: "short",
          id: "expand-factorise-p2-q08",
          question: "Write {{x^2 - 5x + 2}} in the form {{(x + p)^2 + q}}. Give p and q, p first. (Fractions or decimals are fine.)",
          answer: { type: "list", values: [-2.5, -4.25], ordered: true, display: "p = −{{5/2}}, q = −{{17/4}}" },
          solution: [
            "Half of −5 is −{{5/2}}: start with {{(x - 5/2)^2 = x^2 - 5x + 25/4}}.",
            "{{x^2 - 5x + 2 = (x - 5/2)^2 - 25/4 + 2}}.",
            "{{-25/4 + 8/4 = -17/4}}.",
            "{{(x - 5/2)^2 - 17/4}}, so p = −{{5/2}}, q = −{{17/4}}.",
          ],
          commonError: "Subtracting {{5/2}} instead of {{(5/2)^2 = 25/4}}.",
          traps: [
            { spec: { type: "list", values: [-2.5, -0.5], ordered: true }, feedback: "You subtracted {{5/2}}; you need to subtract its *square*, {{25/4}}." },
            { spec: { type: "list", values: [2.5, -4.25], ordered: true }, feedback: "{{(x + p)^2}} must give −5x, so p is negative: p = −{{5/2}}." },
          ],
          difficulty: "core",
          guideRef: "completing-the-square",
          hints: ["Halve the coefficient of x — it's fine for it to be a fraction.", "{{(x - 5/2)^2}} contains +{{25/4}}. Take it away.", "{{2 - 25/4 = 8/4 - 25/4}}."],
        },
        {
          kind: "short",
          id: "expand-factorise-p2-q09",
          question: "For a lens, {{1/f = 1/u + 1/v}}. Work out f when u = {{2/3}} and v = −{{1/4}}. Give your answer as a fraction.",
          answer: { type: "fraction", n: -2, d: 5, allowDecimal: true, display: "−{{2/5}}" },
          solution: [
            "{{1/u = 1 ÷ 2/3 = 3/2}}.",
            "{{1/v = 1 ÷ (-1/4) = -4}}.",
            "{{1/f = 3/2 - 4 = -5/2}}.",
            "So {{f = -2/5}}.",
          ],
          commonError: "Stopping at {{1/f = -5/2}} and forgetting to take the reciprocal.",
          traps: [
            { spec: { type: "fraction", n: -5, d: 2 }, feedback: "That's {{1/f}}. Flip it to get f." },
            { spec: { type: "fraction", n: 5, d: 12 }, feedback: "{{1/f}} is not {{u + v}}. Find the reciprocals of u and v first." },
          ],
          difficulty: "core",
          guideRef: "substitution-formulae",
          hints: ["The reciprocal of a fraction: flip it.", "{{1/u = 3/2}} and {{1/v = -4}}.", "Add them to get {{1/f}}, then flip."],
          strategy: "Use the inverse",
        },
        {
          kind: "short",
          id: "expand-factorise-p2-q10",
          question: "f(x) = 3x − 7. Find and simplify f(2a) − f(a).",
          answer: { type: "expression", expr: "3a", form: "simplified", display: "3a" },
          solution: ["f(2a) = 3(2a) − 7 = 6a − 7.", "f(a) = 3a − 7.", "(6a − 7) − (3a − 7) = 6a − 7 − 3a + 7 = 3a."],
          commonError: "Not putting f(a) in a bracket, so −7 − 7 = −14 appears.",
          traps: [
            { spec: { type: "expression", expr: "3a-14" }, feedback: "Subtract the *whole* of f(a): −(3a − 7) = −3a **+ 7**." },
            { spec: { type: "expression", expr: "3a-7" }, feedback: "f(2a) means put 2a in place of x: 3(2a) − 7 = 6a − 7, not 2(3a − 7)." },
          ],
          difficulty: "core",
          guideRef: "function-notation-basics",
          hints: ["Work out f(2a) and f(a) separately.", "Put f(a) in a bracket before subtracting."],
          strategy: "Substitute a bracket",
        },
        {
          kind: "written",
          id: "expand-factorise-p2-q11",
          question: "Show that {{(x + 1)(x - 2)(2x + 5) = 2x^3 + 3x^2 - 9x - 10}}.",
          marks: 3,
          modelAnswer:
            "First two brackets: {{(x+1)(x-2) = x^2 - 2x + x - 2 = x^2 - x - 2}}.\n\nMultiply by (2x + 5): {{(x^2 - x - 2)(2x + 5) = 2x^3 + 5x^2 - 2x^2 - 5x - 4x - 10}}.\n\nCollect like terms: {{2x^3 + 3x^2 - 9x - 10}}, as required.",
          markScheme: [
            { point: "Expands one pair of brackets correctly, e.g. x² − x − 2", keywords: ["x^2 - x - 2", "x² - x - 2", "x^2 - x - 2"] },
            { point: "All six products correct when multiplying by the third bracket", keywords: ["2x^3", "5x^2", "-2x^2", "-5x", "-4x", "-10"] },
            { point: "Collects to 2x³ + 3x² − 9x − 10 with no errors", keywords: ["2x^3 + 3x^2 - 9x - 10", "3x^2", "-9x", "as required"] },
          ],
          commonError: "Missing one of the six products when multiplying the trinomial by (2x + 5).",
          difficulty: "core",
          guideRef: "expanding-brackets",
          hints: ["Expand any two brackets first.", "Multiply each of the three terms by 2x, then by 5.", "Collect the x² terms and the x terms."],
          strategy: "Make it simpler",
        },
        {
          kind: "written",
          id: "expand-factorise-p2-q12",
          question: "Marcus works out the value of {{4 - 2x^2}} when x = −3. He writes:\n\n    4 − 2x² = 4 − (−6)² = 4 − 36 = −32\n\nExplain his mistake and work out the correct value.",
          marks: 3,
          modelAnswer:
            "Marcus multiplied 2 by −3 first and then squared, so he squared 2x (= −6) instead of just x.\n\nIndices come before multiplication: {{x^2 = (-3)^2 = 9}}, then 2 × 9 = 18.\n\nCorrect value: 4 − 18 = −14.",
          markScheme: [
            { point: "Identifies that he squared 2x (or −6) instead of x", keywords: ["squared 2x", "squared -6", "squared −6", "(-6)", "2 × -3", "multiplied first"] },
            { point: "States the correct order: square x first (indices before multiplication)", keywords: ["indices", "powers", "bidmas", "square first", "x^2 = 9", "9"] },
            { point: "Correct value −14", keywords: ["-14", "−14"] },
          ],
          commonError: "Saying 'he did it wrong' without naming which operation came in the wrong order.",
          difficulty: "core",
          guideRef: "substitution-formulae",
          hints: ["In {{2x^2}}, what exactly is being squared?", "BIDMAS: indices before multiplication.", "Square −3 first, then multiply by 2."],
          strategy: "Spot the error",
        },
        {
          kind: "written",
          id: "expand-factorise-p2-q13",
          question: "Prove that the square of any odd number is always one more than a multiple of 8.",
          marks: 4,
          modelAnswer:
            "Let the odd number be 2n + 1, where n is an integer.\n\n{{(2n+1)^2 = 4n^2 + 4n + 1 = 4n(n+1) + 1}}.\n\nn and n + 1 are consecutive integers, so one of them is even. That makes n(n + 1) even: say n(n + 1) = 2k for an integer k.\n\nThen {{(2n+1)^2 = 4(2k) + 1 = 8k + 1}}, which is one more than a multiple of 8.",
          markScheme: [
            { point: "Writes the odd number as 2n + 1 (or 2n − 1) and expands to 4n² + 4n + 1", keywords: ["2n + 1", "2n+1", "4n^2 + 4n + 1", "4n² + 4n + 1"] },
            { point: "Factorises to 4n(n + 1) + 1", keywords: ["4n(n + 1)", "4n(n+1)", "n(n + 1)", "n(n+1)"] },
            { point: "Explains n(n + 1) is even because one of two consecutive integers is even", keywords: ["consecutive", "even", "one of them"] },
            { point: "Concludes 8k + 1, one more than a multiple of 8", keywords: ["8k + 1", "8k+1", "multiple of 8", "one more"] },
          ],
          commonError: "Stopping at 4n(n + 1) + 1 and claiming 'multiple of 8' without explaining why n(n + 1) is even.",
          solutions: [
            { label: "Split into cases", steps: ["If n is even, n = 2m: {{4n(n+1) = 8m(2m+1)}}, a multiple of 8.", "If n is odd, n + 1 = 2m: {{4n(n+1) = 8mn}}, a multiple of 8.", "Either way {{(2n+1)^2}} is a multiple of 8 plus 1."] },
          ],
          difficulty: "challenge",
          guideRef: "harder-algebra",
          hints: ["Write any odd number in algebra and square it.", "{{4n^2 + 4n = 4n(n+1)}}. That gives a factor of 4 — where can another factor of 2 come from?", "n and n + 1 are consecutive integers. What do you know about one of them?"],
          strategy: "Introduce a variable",
        },
        {
          kind: "short",
          id: "expand-factorise-p2-q14",
          question: "The expression {{2x^2 - 8x + c}} has a minimum value of 3. Find the value of c.",
          answer: { type: "number", value: 11 },
          solution: [
            "{{2x^2 - 8x + c = 2(x^2 - 4x) + c}}.",
            "{{= 2[(x-2)^2 - 4] + c = 2(x-2)^2 - 8 + c}}.",
            "The minimum value is c − 8 (when x = 2).",
            "c − 8 = 3, so c = 11.",
          ],
          solutions: [
            { label: "Find where the minimum is first", steps: ["The minimum is on the axis of symmetry, halfway between the roots of {{2x^2 - 8x = 0}}: x = 0 and x = 4, so x = 2.", "At x = 2: 2(4) − 16 + c = c − 8.", "c − 8 = 3, so c = 11."] },
          ],
          commonError: "Completing the square as {{(x-2)^2 - 4 + c}} without the factor 2, giving c = 7.",
          traps: [{ spec: { type: "number", value: 7 }, feedback: "Factor out the 2 first: {{2(x-2)^2 - 8 + c}}. The −4 is multiplied by 2." }],
          difficulty: "challenge",
          guideRef: "completing-the-square",
          hints: ["Complete the square on {{2x^2 - 8x}} — factor out the 2 first.", "You should get {{2(x-2)^2 - 8 + c}}.", "The minimum of that is c − 8. Set it equal to 3."],
          strategy: "Work backwards",
        },
        {
          kind: "short",
          id: "expand-factorise-p2-q15",
          question: "Factorise fully {{(2x + 1)^2 - (x - 3)^2}}.",
          answer: { type: "expression", expr: "(x+4)(3x-2)", form: "factorised", display: "(x + 4)(3x − 2)" },
          solution: [
            "Difference of two squares with A = 2x + 1, B = x − 3.",
            "A − B = 2x + 1 − x + 3 = x + 4.",
            "A + B = 2x + 1 + x − 3 = 3x − 2.",
            "(x + 4)(3x − 2)",
          ],
          solutions: [
            { label: "Expand, then factorise", steps: ["{{4x^2 + 4x + 1 - (x^2 - 6x + 9) = 3x^2 + 10x - 8}}.", "a × c = −24: use +12 and −2.", "{{3x^2 + 12x - 2x - 8 = 3x(x + 4) - 2(x + 4) = (3x - 2)(x + 4)}}.", "The difference-of-squares route is quicker: no quadratic to factorise."] },
          ],
          commonError: "Writing A − B as 2x + 1 − x − 3 = x − 2 (not distributing the minus over the bracket).",
          traps: [{ spec: { type: "expression", expr: "(x-2)(3x-2)" }, feedback: "A − B = (2x + 1) − (x − 3): subtracting −3 gives **+3**, so A − B = x + 4." }],
          difficulty: "challenge",
          guideRef: "harder-algebra",
          hints: ["It's {{A^2 - B^2}} — what are A and B?", "{{A^2 - B^2 = (A - B)(A + B)}}.", "Take care with A − B: (2x + 1) − (x − 3)."],
          strategy: "Spot the structure",
        },
      ],
    },
  ],

  // =========================================================================
  // CHALLENGE — 10 questions
  // =========================================================================
  challenge: [
    {
      kind: "short",
      id: "expand-factorise-ch-q01",
      question: "Find the coefficient of x in the expansion of (x + 1)(x + 2)(x + 3)(x + 4).",
      answer: { type: "number", value: 50 },
      solution: [
        "Pair the brackets cleverly: (x + 1)(x + 4) = {{x^2 + 5x + 4}} and (x + 2)(x + 3) = {{x^2 + 5x + 6}}.",
        "In {{(x^2 + 5x + 4)(x^2 + 5x + 6)}}, the x-terms come only from (5x × 6) and (4 × 5x).",
        "30x + 20x = 50x, so the coefficient is 50.",
      ],
      solutions: [
        {
          label: "Choose an x from one bracket",
          steps: [
            "An x-term comes from choosing x from exactly one bracket and the number from the other three.",
            "x from the first: 2 × 3 × 4 = 24. From the second: 1 × 3 × 4 = 12. From the third: 1 × 2 × 4 = 8. From the fourth: 1 × 2 × 3 = 6.",
            "24 + 12 + 8 + 6 = 50.",
          ],
        },
      ],
      commonError: "Adding 1 + 2 + 3 + 4 = 10 — that is the coefficient of {{x^3}}, not x.",
      traps: [
        { spec: { type: "number", value: 10 }, feedback: "1 + 2 + 3 + 4 gives the coefficient of {{x^3}} (choose x from three brackets). For x you choose x from just *one* bracket." },
        { spec: { type: "number", value: 24 }, feedback: "24 is the constant term (1 × 2 × 3 × 4). The x-term needs one x and three numbers." },
      ],
      difficulty: "challenge",
      guideRef: "expanding-brackets",
      hints: [
        "You don't need the full expansion. Which products give a single x?",
        "Each term in the expansion picks one thing from each bracket. For an x-term, you pick x from exactly one bracket.",
        "Or: pair (x + 1)(x + 4) and (x + 2)(x + 3) — both start {{x^2 + 5x}}.",
        "Add 2·3·4 + 1·3·4 + 1·2·4 + 1·2·3.",
      ],
      strategy: "Make it simpler",
    },
    {
      kind: "short",
      id: "expand-factorise-ch-q02",
      question: "By factorising {{x^3 - x^2 - 4x + 4}}, solve {{x^3 - x^2 - 4x + 4 = 0}}. Give all three solutions.",
      answer: { type: "list", values: [1, 2, -2], ordered: false, display: "x = 1, 2 or −2" },
      solution: [
        "Group in pairs: {{x^2(x - 1) - 4(x - 1)}}.",
        "Common bracket: {{(x - 1)(x^2 - 4)}}.",
        "Difference of two squares: (x − 1)(x − 2)(x + 2).",
        "So x = 1, x = 2 or x = −2.",
      ],
      solutions: [
        { label: "Spot a root", steps: ["Try x = 1: 1 − 1 − 4 + 4 = 0, so (x − 1) is a factor.", "Divide out: {{x^3 - x^2 - 4x + 4 = (x - 1)(x^2 - 4)}}.", "Then x = ±2 as well."] },
      ],
      commonError: "Taking −4 out of the second pair as −4(x + 1), so the brackets don't match.",
      traps: [{ spec: { type: "list", values: [1, 4] }, feedback: "{{x^2 - 4 = 0}} gives x = ±2, not 4." }],
      difficulty: "challenge",
      guideRef: "harder-algebra",
      hints: [
        "Four terms: try grouping them in pairs.",
        "Take {{x^2}} out of the first pair and −4 out of the second.",
        "You should get {{(x - 1)(x^2 - 4)}}. Can that factorise further?",
      ],
      strategy: "Group in pairs",
    },
    {
      kind: "short",
      id: "expand-factorise-ch-q03",
      question: "{{(ax + b)^2 = 9x^2 - 24x + c}} for all values of x, where a > 0. Find a, b and c. Give them in that order.",
      answer: { type: "list", values: [3, -4, 16], ordered: true, display: "a = 3, b = −4, c = 16" },
      solution: [
        "Expand: {{(ax + b)^2 = a^2 x^2 + 2abx + b^2}}.",
        "Compare {{x^2}} terms: {{a^2 = 9}}, and a > 0, so a = 3.",
        "Compare x terms: 2ab = −24, so 6b = −24, b = −4.",
        "Compare constants: {{c = b^2 = 16}}.",
      ],
      commonError: "Taking b = −24 ÷ 2 = −12, forgetting the a in the 2ab term.",
      traps: [{ spec: { type: "list", values: [3, -12, 144], ordered: true }, feedback: "The middle term is 2ab, not 2b. With a = 3, 6b = −24." }],
      difficulty: "challenge",
      guideRef: "expanding-brackets",
      hints: [
        "Expand {{(ax + b)^2}} in terms of a and b.",
        "'For all x' means you can compare coefficients.",
        "{{a^2 = 9}}, 2ab = −24, {{b^2 = c}}.",
      ],
      strategy: "Compare coefficients",
    },
    {
      kind: "short",
      id: "expand-factorise-ch-q04",
      question: "Find the maximum value of {{7 + 8x - 2x^2}}.",
      answer: { type: "number", value: 15 },
      solution: [
        "{{7 + 8x - 2x^2 = -2(x^2 - 4x) + 7}}.",
        "{{= -2[(x-2)^2 - 4] + 7 = -2(x-2)^2 + 8 + 7}}.",
        "{{= 15 - 2(x-2)^2}}.",
        "{{2(x-2)^2 >= 0}}, so the greatest value is 15 (when x = 2).",
      ],
      solutions: [
        { label: "Symmetry", steps: ["{{8x - 2x^2 = 2x(4 - x)}} is 0 at x = 0 and x = 4.", "The maximum is halfway, at x = 2.", "7 + 16 − 8 = 15."] },
      ],
      commonError: "Factoring out −2 and getting the sign of the +8 wrong, giving −1.",
      traps: [
        { spec: { type: "number", value: -1 }, feedback: "−2 × (−4) = **+8**, so you get 7 + 8 = 15." },
        { spec: { type: "number", value: 2 }, feedback: "That's the x-value where the maximum happens. The question asks for the maximum *value*." },
      ],
      difficulty: "challenge",
      guideRef: "completing-the-square",
      hints: [
        "The {{x^2}} coefficient is negative, so this has a maximum. Factor −2 out of the x-terms.",
        "Complete the square on {{x^2 - 4x}}.",
        "You should get 15 − {{2(x-2)^2}}. When is the subtracted part smallest?",
      ],
      strategy: "Consider extremes",
    },
    {
      kind: "short",
      id: "expand-factorise-ch-q05",
      question: "{{f(x) = x^2 - 2x}}. Find the value of a for which f(a + 2) = f(a) + 12.",
      answer: { type: "number", value: 3 },
      solution: [
        "{{f(a+2) = (a+2)^2 - 2(a+2) = a^2 + 4a + 4 - 2a - 4 = a^2 + 2a}}.",
        "{{f(a) + 12 = a^2 - 2a + 12}}.",
        "{{a^2 + 2a = a^2 - 2a + 12}}: the {{a^2}} terms cancel.",
        "4a = 12, so a = 3.",
        "Check: f(5) = 15 and f(3) + 12 = 3 + 12 = 15. ✓",
      ],
      commonError: "Writing f(a + 2) as f(a) + 2.",
      difficulty: "challenge",
      guideRef: "function-notation-basics",
      hints: [
        "Write f(a + 2) by replacing every x with (a + 2).",
        "Simplify both sides fully.",
        "The {{a^2}} terms cancel — it's a linear equation in a.",
      ],
      strategy: "Substitute a bracket",
    },
    {
      kind: "short",
      id: "expand-factorise-ch-q06",
      question: "Without a calculator, work out {{(2027^2 - 2023^2)/2025}}.",
      answer: { type: "number", value: 8 },
      solution: [
        "Difference of two squares: {{2027^2 - 2023^2 = (2027 - 2023)(2027 + 2023)}}.",
        "= 4 × 4050.",
        "4050 = 2 × 2025, so the fraction is {{(4 * 2 * 2025)/2025 = 8}}.",
      ],
      solutions: [
        { label: "Centre on 2025", steps: ["Let n = 2025. Then {{(n+2)^2 - (n-2)^2 = 8n}}.", "So the fraction is {{8n/n = 8}}."] },
      ],
      commonError: "Trying to square the four-digit numbers.",
      difficulty: "challenge",
      guideRef: "harder-algebra",
      hints: [
        "Squaring 2027 by hand is painful. What structure does the numerator have?",
        "{{a^2 - b^2 = (a - b)(a + b)}}.",
        "2027 + 2023 = 4050. How does 4050 relate to 2025?",
      ],
      strategy: "Spot the structure",
    },
    {
      kind: "short",
      id: "expand-factorise-ch-q07",
      question: "n is a positive integer and {{n^2 + 20}} is a perfect square. Find n.",
      answer: { type: "number", value: 4 },
      solution: [
        "Let {{n^2 + 20 = m^2}} with m a positive integer. Then {{m^2 - n^2 = 20}}.",
        "(m − n)(m + n) = 20.",
        "m − n and m + n have the same parity (they differ by 2n), and their product is even, so both are even.",
        "The only even factor pair of 20 is 2 × 10: m − n = 2, m + n = 10.",
        "So m = 6, n = 4. Check: 16 + 20 = 36 = {{6^2}}. ✓",
      ],
      commonError: "Testing n = 1, 2, 3, … and stopping without showing there are no other solutions.",
      traps: [{ spec: { type: "number", value: 6 }, feedback: "6 is m, where {{n^2 + 20 = m^2}}. The question asks for n." }],
      difficulty: "challenge",
      guideRef: "harder-algebra",
      hints: [
        "Call the perfect square {{m^2}}. Rearrange so the squares are on one side.",
        "{{m^2 - n^2 = 20}} — factorise the left-hand side.",
        "(m − n)(m + n) = 20. m − n and m + n are both odd or both even. Which factor pairs of 20 work?",
        "Only 2 × 10 works.",
      ],
      strategy: "Split into cases",
    },
    {
      kind: "short",
      id: "expand-factorise-ch-q08",
      question: "Work out the exact value of {{(a + b)/(1 - ab)}} when a = −{{1/2}} and b = {{2/3}}. Give your answer as a fraction.",
      answer: { type: "fraction", n: 1, d: 8, simplest: true, allowDecimal: true },
      solution: [
        "{{a + b = -1/2 + 2/3 = -3/6 + 4/6 = 1/6}}.",
        "{{ab = -1/2 * 2/3 = -1/3}}, so {{1 - ab = 1 + 1/3 = 4/3}}.",
        "{{1/6 ÷ 4/3 = 1/6 * 3/4 = 3/24 = 1/8}}.",
      ],
      solutions: [
        { label: "Clear the fractions first", steps: ["Multiply top and bottom by 6: {{(6a + 6b)/(6 - 6ab)}}.", "6a + 6b = −3 + 4 = 1; 6ab = −2, so 6 − 6ab = 8.", "{{1/8}}."] },
      ],
      commonError: "Writing 1 − ab as {{1 - 1/3 = 2/3}}: subtracting a negative means adding.",
      traps: [{ spec: { type: "fraction", n: 1, d: 4 }, feedback: "ab is negative, so 1 − ab = 1 + {{1/3}} = {{4/3}}, not {{2/3}}." }],
      difficulty: "challenge",
      guideRef: "substitution-formulae",
      hints: [
        "Work out a + b and ab separately.",
        "ab is negative — what does 1 − (negative) become?",
        "Divide: {{1/6 ÷ 4/3}}.",
      ],
      strategy: "Split into parts",
    },
    {
      kind: "written",
      id: "expand-factorise-ch-q09",
      question: "Prove that the difference between the squares of any two odd numbers is a multiple of 8.",
      marks: 4,
      modelAnswer:
        "Let the odd numbers be 2a + 1 and 2b + 1, where a and b are integers.\n\n{{(2a+1)^2 - (2b+1)^2 = 4a^2 + 4a + 1 - 4b^2 - 4b - 1 = 4(a^2 + a) - 4(b^2 + b)}}.\n\n{{= 4[a(a+1) - b(b+1)]}}.\n\na(a + 1) is the product of two consecutive integers, so one of them is even and a(a + 1) is even; likewise b(b + 1) is even. The difference of two even numbers is even, say 2k.\n\nSo the difference is 4 × 2k = 8k, a multiple of 8.",
      markScheme: [
        { point: "Uses two independent odd numbers, e.g. 2a + 1 and 2b + 1", keywords: ["2a + 1", "2b + 1", "2a+1", "2b+1", "2m + 1", "2n + 1"] },
        { point: "Expands and simplifies to 4(a² + a − b² − b) or 4[a(a + 1) − b(b + 1)]", keywords: ["4a^2 + 4a", "4(a^2 + a", "a(a + 1)", "4[", "4("] },
        { point: "Explains that a(a + 1) and b(b + 1) are even (product of consecutive integers)", keywords: ["consecutive", "even", "one of them is even", "a(a + 1)"] },
        { point: "Concludes 4 × even = multiple of 8", keywords: ["8k", "multiple of 8", "4 × 2", "8("] },
      ],
      commonError: "Using 2n + 1 and 2n + 3 (consecutive odd numbers only) — the statement is about *any* two odd numbers.",
      solutions: [
        { label: "Difference of two squares", steps: ["{{(2a+1)^2 - (2b+1)^2 = (2a - 2b)(2a + 2b + 2) = 4(a - b)(a + b + 1)}}.", "If a and b have the same parity, a − b is even; if not, a + b + 1 is even.", "Either way (a − b)(a + b + 1) is even, so the difference is a multiple of 8."] },
      ],
      difficulty: "challenge",
      guideRef: "harder-algebra",
      hints: [
        "'Any two odd numbers' — they need separate letters, not 2n + 1 and 2n + 3.",
        "Expand {{(2a+1)^2 - (2b+1)^2}} and take out the 4.",
        "Getting a factor 4 is easy. Where does the extra factor of 2 come from?",
        "Look at {{a^2 + a = a(a+1)}}: a product of two consecutive integers.",
      ],
      strategy: "Introduce a variable",
    },
    {
      kind: "short",
      id: "expand-factorise-ch-q10",
      question: "x and y can be any real numbers. Find the smallest possible value of {{x^2 + y^2 - 6x + 4y + 20}}.",
      answer: { type: "number", value: 7 },
      solution: [
        "Complete the square in x and in y separately.",
        "{{x^2 - 6x = (x-3)^2 - 9}} and {{y^2 + 4y = (y+2)^2 - 4}}.",
        "Expression {{= (x-3)^2 + (y+2)^2 - 9 - 4 + 20 = (x-3)^2 + (y+2)^2 + 7}}.",
        "Both squares are ≥ 0 and both equal 0 when x = 3, y = −2, so the minimum is 7.",
      ],
      commonError: "Adding the 9 and 4 instead of subtracting them, giving 33.",
      traps: [
        { spec: { type: "number", value: 33 }, feedback: "{{(x-3)^2}} contains an extra +9 and {{(y+2)^2}} an extra +4 — subtract them: 20 − 9 − 4 = 7." },
        { spec: { type: "number", value: 20 }, feedback: "20 is the value at x = 0, y = 0, but you can do better. Complete the square in each variable." },
      ],
      difficulty: "challenge",
      guideRef: "completing-the-square",
      hints: [
        "Group the x-terms together and the y-terms together.",
        "Complete the square on {{x^2 - 6x}} and on {{y^2 + 4y}} separately.",
        "You get {{(x-3)^2 + (y+2)^2 + k}}. What's the smallest value of a sum of two squares?",
      ],
      strategy: "Consider extremes",
    },
  ],
};
