// Sets & Venn diagrams — MCQ papers (3 × 15). Options are shuffled at display time.
// Venn diagrams are drawn with the region values used in each question.
import type { Paper } from "../../types.ts";

export const mcqPapers: Paper[] = [
  {
    id: "sets-venn-m1",
    title: "MCQ Paper 1",
    questions: [
      {
        kind: "mcq",
        id: "sets-venn-m1-q01",
        question: "ξ = {positive integers less than 20}\n\nE = {x : x is a prime number}\n\nWork out n(E).",
        options: ["9", "7", "8", "10"],
        answerIndex: 2,
        explanation: "The primes below 20 are 2, 3, 5, 7, 11, 13, 17, 19, so n(E) = 8. 9 comes from counting 1 as a prime (it is not — a prime has exactly two factors). 7 comes from leaving out 2, the only even prime. 10 is the number of odd numbers below 20, which is not the same thing as primes (9 and 15 are odd but not prime).",
        difficulty: "warmup",
        guideRef: "set-notation",
        hints: ["List the primes below 20 carefully. Is 1 prime? Is 2?", "n(E) means *how many* elements E has, not the elements themselves."],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "sets-venn-m1-q02",
        question: "ξ = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}\n\nE = {2, 4, 6, 8, 10}\n\nF = {1, 2, 3, 4, 5}\n\nList the members of E ∩ F.",
        options: ["{2, 4}", "{1, 2, 3, 4, 5, 6, 8, 10}", "{6, 8, 10}", "{1, 3, 5}"],
        answerIndex: 0,
        explanation: "∩ (intersection) means *in both* sets: 2 and 4 are the only numbers in E and in F, so E ∩ F = {2, 4}. {1, 2, 3, 4, 5, 6, 8, 10} is the union E ∪ F (in either set). {6, 8, 10} is in E but not F, i.e. E ∩ F′. {1, 3, 5} is in F but not E.",
        difficulty: "warmup",
        guideRef: "set-notation",
        hints: ["∩ looks like an upside-down U — think 'n' for 'and'. Which numbers are in E **and** F?"],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "sets-venn-m1-q03",
        question: "The Venn diagram shows the number of elements in each region.\n\nWork out n(A).",
        diagram: `<svg viewBox="0 0 320 210" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Two-set Venn diagram. A only 7, A and B 4, B only 9, outside both 5."><rect x="0" y="0" width="320" height="210" fill="#ffffff"/><rect x="10" y="10" width="300" height="190" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="125" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="195" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><text x="22" y="30" font-size="15" text-anchor="start" font-family="sans-serif" fill="#1f2937" font-style="italic">ξ</text><text x="68" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">A</text><text x="252" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">B</text><text x="98" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">7</text><text x="160" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">4</text><text x="222" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">9</text><text x="285" y="188" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">5</text></svg>`,
        options: ["7", "20", "14", "11"],
        answerIndex: 3,
        explanation: "To find n(A), count *everything* inside circle A, including the overlap: 7 + 4 = 11. 7 is only the 'A only' region (forgetting the overlap is part of A). 20 = 7 + 4 + 9 is the size of A ∪ B. 14 = 9 + 5 is the size of A′, everything outside A.",
        difficulty: "warmup",
        guideRef: "venn-diagrams",
        hints: ["Which regions lie inside circle A? There are two of them."],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "sets-venn-m1-q04",
        question: "The Venn diagram shows the prime factors of 60 and 72.\n\nWork out the **highest common factor** (HCF) of 60 and 72.",
        diagram: `<svg viewBox="0 0 320 210" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Venn diagram of prime factors. 60 only: 5. Both: 2, 2, 3. 72 only: 2, 3."><rect x="0" y="0" width="320" height="210" fill="#ffffff"/><rect x="10" y="10" width="300" height="190" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="125" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="195" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><text x="22" y="30" font-size="15" text-anchor="start" font-family="sans-serif" fill="#1f2937" font-style="italic">ξ</text><text x="68" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">60</text><text x="252" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">72</text><text x="98" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">5</text><text x="160" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">2, 2, 3</text><text x="222" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">2, 3</text></svg>`,
        options: ["360", "12", "6", "4320"],
        answerIndex: 1,
        explanation: "The HCF is the product of the primes in the **intersection**: 2 × 2 × 3 = 12. 360 is the LCM (the product of everything in the diagram: 5 × 2 × 2 × 3 × 2 × 3). 6 takes each common prime only once (2 × 3) but there are *two* 2s in the overlap. 4320 is 60 × 72, which is a common multiple but neither the HCF nor the LCM.",
        difficulty: "warmup",
        guideRef: "venn-hcf-lcm",
        hints: ["The overlap holds the prime factors the two numbers share. Multiply them together."],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "sets-venn-m1-q05",
        question: "The Venn diagram shows how many of 40 students study Art (R) and Music (M).\n\nA student is chosen at random. Work out the probability that the student studies **exactly one** of these subjects.",
        diagram: `<svg viewBox="0 0 320 210" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Two-set Venn diagram of 40 students. R only 12, R and M 8, M only 14, neither 6."><rect x="0" y="0" width="320" height="210" fill="#ffffff"/><rect x="10" y="10" width="300" height="190" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="125" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="195" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><text x="22" y="30" font-size="15" text-anchor="start" font-family="sans-serif" fill="#1f2937" font-style="italic">ξ</text><text x="68" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">R</text><text x="252" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">M</text><text x="98" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">12</text><text x="160" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">8</text><text x="222" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">14</text><text x="285" y="188" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">6</text></svg>`,
        options: ["{{17/20}}", "{{13/20}}", "{{1/5}}", "{{3/10}}"],
        answerIndex: 1,
        explanation: "Exactly one means R only or M only: 12 + 14 = 26 students, so the probability is {{26/40 = 13/20}}. {{17/20}} = {{34/40}} also includes the 8 who study both (that is P(R ∪ M), 'at least one'). {{1/5}} = {{8/40}} is the probability of both. {{3/10}} = {{12/40}} is Art only.",
        difficulty: "core",
        guideRef: "venn-probability",
        hints: ["'Exactly one' excludes the overlap. Which two regions do you need?", "Add those two regions, then divide by the total, 40.", "{{(12 + 14)/40}} — now simplify."],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "sets-venn-m1-q06",
        question: "Which set is represented by the shaded region of the Venn diagram?",
        diagram: `<svg viewBox="0 0 320 210" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Two-set Venn diagram with only the part of A outside B shaded."><rect x="0" y="0" width="320" height="210" fill="#ffffff"/><path d="M160 50.23 A65 65 0 1 0 160 159.77 A65 65 0 0 1 160 50.23 Z" fill="#fde68a"/><rect x="10" y="10" width="300" height="190" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="125" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="195" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><text x="22" y="30" font-size="15" text-anchor="start" font-family="sans-serif" fill="#1f2937" font-style="italic">ξ</text><text x="68" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">A</text><text x="252" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">B</text></svg>`,
        options: ["A", "A′ ∩ B", "A ∪ B′", "A ∩ B′"],
        answerIndex: 3,
        explanation: "The shaded region is inside A but outside B, so it is A ∩ B′ ('in A and not in B'). Just 'A' would include the overlap, which is not shaded. A′ ∩ B is the mirror image (in B but not A). A ∪ B′ is everything in A *or* outside B — that would also shade the region outside both circles.",
        difficulty: "core",
        guideRef: "venn-diagrams",
        hints: ["Describe the shaded region in words first: in which set, and not in which set?", "'Not in B' is written B′. Then join the two conditions with 'and' (∩)."],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "sets-venn-m1-q07",
        question: "ξ = {integers from 1 to 20}\n\nG = {factors of 18}\n\nH = {multiples of 3}\n\nList the members of G ∩ H.",
        options: ["{3, 6, 9, 18}", "{3, 6, 9}", "{3, 6, 9, 12, 15, 18}", "{1, 2, 3, 6, 9, 12, 15, 18}"],
        answerIndex: 0,
        explanation: "G = {1, 2, 3, 6, 9, 18} and H = {3, 6, 9, 12, 15, 18}. The numbers in both are 3, 6, 9 and 18. {3, 6, 9} forgets that 18 is a factor of itself. {3, 6, 9, 12, 15, 18} is all of H — 12 and 15 do not divide 18. {1, 2, 3, 6, 9, 12, 15, 18} is the union G ∪ H.",
        difficulty: "core",
        guideRef: "set-notation",
        hints: ["List G and H in full first.", "Factors of 18 come in pairs: 1 × 18, 2 × 9, 3 × 6.", "Now pick out the numbers that appear in both lists."],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "sets-venn-m1-q08",
        question: "In a class of 30 students, 18 like bubble tea, 15 like kopi and 4 like neither.\n\nHow many students like **both** bubble tea and kopi?",
        options: ["3", "26", "7", "33"],
        answerIndex: 2,
        explanation: "26 students like at least one drink (30 − 4). Adding 18 + 15 = 33 counts the 'both' group twice, so both = 33 − 26 = 7. 3 comes from 18 + 15 − 30, forgetting the 4 who like neither. 26 is the number who like at least one. 33 is the double-counted total.",
        difficulty: "core",
        guideRef: "venn-diagrams",
        hints: ["How many students are inside the circles altogether?", "If you add 18 and 15, which group have you counted twice?", "Both = (18 + 15) − (number inside the circles)."],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "sets-venn-m1-q09",
        question: "The Venn diagram shows the prime factors of 84 and 90.\n\nWork out the **lowest common multiple** (LCM) of 84 and 90.",
        diagram: `<svg viewBox="0 0 320 210" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Venn diagram of prime factors. 84 only: 2, 7. Both: 2, 3. 90 only: 3, 5."><rect x="0" y="0" width="320" height="210" fill="#ffffff"/><rect x="10" y="10" width="300" height="190" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="125" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="195" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><text x="22" y="30" font-size="15" text-anchor="start" font-family="sans-serif" fill="#1f2937" font-style="italic">ξ</text><text x="68" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">84</text><text x="252" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">90</text><text x="98" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">2, 7</text><text x="160" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">2, 3</text><text x="222" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">3, 5</text></svg>`,
        options: ["6", "7560", "630", "1260"],
        answerIndex: 3,
        explanation: "The LCM is the product of **every** prime in the diagram, each region once: 2 × 7 × 2 × 3 × 3 × 5 = 1260. 6 is the HCF (the overlap, 2 × 3). 7560 is 84 × 90, which counts the shared 2 and 3 twice. 630 leaves out the extra 2 in the '84 only' region.",
        difficulty: "core",
        guideRef: "venn-hcf-lcm",
        hints: ["HCF uses the overlap; LCM uses the whole diagram.", "Multiply all six primes in the diagram — once each.", "2 × 7 × 2 × 3 × 3 × 5"],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "sets-venn-m1-q10",
        question: "For two events X and Y,\n\nP(X) = 0.6, P(Y) = 0.5 and P(X ∩ Y) = 0.3\n\nWork out P(X ∪ Y).",
        options: ["0.8", "1.1", "0.2", "0.5"],
        answerIndex: 0,
        explanation: "P(X ∪ Y) = P(X) + P(Y) − P(X ∩ Y) = 0.6 + 0.5 − 0.3 = 0.8. Sketch it: X only 0.3, both 0.3, Y only 0.2, outside 0.2. 1.1 forgets to subtract the overlap — and a probability can never exceed 1. 0.2 is P(neither). 0.5 subtracts the overlap twice: that is P(exactly one).",
        difficulty: "core",
        guideRef: "venn-probability",
        hints: ["Put 0.3 in the overlap of a Venn diagram first.", "X only = 0.6 − 0.3; Y only = 0.5 − 0.3.", "Add the three regions inside the circles."],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "sets-venn-m1-q11",
        question: "The Venn diagram shows how many of 50 students study French (F), German (G) and Spanish (S).\n\nHow many students study **both** French and Spanish?",
        diagram: `<svg viewBox="0 0 320 240" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Three-set Venn diagram of 50 students. F only 10, G only 8, S only 12, F and G only 3, F and S only 4, G and S only 5, all three 2, none 6."><rect x="0" y="0" width="320" height="240" fill="#ffffff"/><rect x="10" y="10" width="300" height="220" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="130" cy="95" r="60" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="190" cy="95" r="60" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="160" cy="147" r="60" fill="none" stroke="#1f2937" stroke-width="1.5"/><text x="22" y="30" font-size="15" text-anchor="start" font-family="sans-serif" fill="#1f2937" font-style="italic">ξ</text><text x="72" y="40" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">F</text><text x="248" y="40" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">G</text><text x="232" y="205" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">S</text><text x="102" y="84" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">10</text><text x="218" y="84" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">8</text><text x="160" y="188" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">12</text><text x="160" y="70" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">3</text><text x="126" y="140" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">4</text><text x="194" y="140" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">5</text><text x="160" y="118" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">2</text><text x="288" y="220" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">6</text></svg>`,
        options: ["4", "2", "6", "36"],
        answerIndex: 2,
        explanation: "French and Spanish means anywhere in the overlap of F and S — including the centre, where students study all three: 4 + 2 = 6. 4 is only the 'F and S but not G' region. 2 is the centre (all three subjects). 36 is n(F ∪ S), French *or* Spanish.",
        difficulty: "core",
        guideRef: "venn-diagrams",
        hints: ["Shade the lens where circles F and S overlap. How many numbers sit inside it?", "The centre region is inside every circle — does it count?"],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "sets-venn-m1-q12",
        question: "ξ = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}\n\nP = {2, 3, 5, 7}\n\nQ = {1, 3, 5, 7, 9}\n\nWhich statement is true?",
        options: ["P ⊂ Q", "5 ∈ P ∩ Q", "n(P ∪ Q) = 9", "9 ∉ Q"],
        answerIndex: 1,
        explanation: "5 is in both P and Q, so 5 ∈ P ∩ Q is true. P ⊂ Q is false because 2 ∈ P but 2 ∉ Q. n(P ∪ Q) = 9 adds 4 + 5 without removing the shared 3, 5 and 7: P ∪ Q = {1, 2, 3, 5, 7, 9}, which has 6 members. 9 ∉ Q is false — 9 is in Q.",
        difficulty: "core",
        guideRef: "set-notation",
        hints: ["Read each symbol aloud: ∈ 'is a member of', ⊂ 'is a subset of', ∉ 'is not a member of'.", "Test each statement against the lists. One counter-example kills a statement."],
        strategy: "Eliminate options",
      },
      {
        kind: "mcq",
        id: "sets-venn-m1-q13",
        question: "45 students were asked about the sports they play: hockey (H), football (F) and cricket (K).\n\n- 3 play all three sports.\n- 7 play hockey and football.\n- 5 play football and cricket.\n- 6 play hockey and cricket.\n- 20 play hockey, 18 play football and 15 play cricket.\n\nHow many students play **exactly one** of the three sports?",
        options: ["26", "17", "38", "53"],
        answerIndex: 0,
        explanation: "Fill in from the centre outwards. Centre = 3. H and F only = 7 − 3 = 4; F and K only = 5 − 3 = 2; H and K only = 6 − 3 = 3. H only = 20 − 4 − 3 − 3 = 10; F only = 18 − 4 − 2 − 3 = 9; K only = 15 − 3 − 2 − 3 = 7. Exactly one = 10 + 9 + 7 = 26. 17 comes from treating '7 play hockey and football' as the 'two only' region, forgetting the 3 in the centre are inside it. 38 is everyone who plays at least one sport. 53 is 20 + 18 + 15, which counts many students more than once.",
        difficulty: "challenge",
        guideRef: "venn-diagrams",
        hints: ["Draw three overlapping circles and start in the very centre.", "'7 play hockey and football' includes the 3 who play all three. What goes in the 'H and F only' region?", "Each 'only one sport' region = circle total − the three other regions inside that circle.", "Add the three 'only' regions."],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "sets-venn-m1-q14",
        question: "For two events X and Y,\n\nP(X) = 0.45, P(Y) = 0.4 and P(X′ ∩ Y′) = 0.3\n\nWork out P(X | Y), the probability of X **given** Y.",
        options: ["0.15", "{{1/3}}", "0.18", "0.375"],
        answerIndex: 3,
        explanation: "P(X ∪ Y) = 1 − 0.3 = 0.7, so P(X ∩ Y) = 0.45 + 0.4 − 0.7 = 0.15. Given Y, the 'world' shrinks to circle Y: P(X | Y) = {{0.15/0.4}} = 0.375. 0.15 is P(X ∩ Y) — you have not divided by P(Y). {{1/3}} = {{0.15/0.45}} is P(Y | X), the wrong way round. 0.18 = 0.45 × 0.4 assumes X and Y are independent, which nothing says.",
        difficulty: "challenge",
        guideRef: "venn-probability",
        hints: ["P(X′ ∩ Y′) is the region outside both circles. What is P(X ∪ Y)?", "Use P(X ∪ Y) = P(X) + P(Y) − P(X ∩ Y) to find the overlap.", "'Given Y' means divide by P(Y), not by 1."],
        strategy: "Work backwards",
      },
      {
        kind: "mcq",
        id: "sets-venn-m1-q15",
        question: "The HCF of two numbers is 12 and their LCM is 180. One of the numbers is 36.\n\nWhat is the other number?",
        options: ["5", "15", "60", "2160"],
        answerIndex: 2,
        explanation: "In a prime-factor Venn diagram the HCF is the overlap and the LCM is the whole diagram, so HCF × LCM = (overlap) × (whole) = the product of the two numbers. Other number = {{(12 × 180)/36}} = 60. Check: 36 = 2² × 3² and 60 = 2² × 3 × 5 give HCF 2² × 3 = 12 and LCM 2² × 3² × 5 = 180. 5 = 180 ÷ 36 forgets the overlap. 15 = 180 ÷ 12. 2160 = 12 × 180 forgets to divide by 36.",
        difficulty: "challenge",
        guideRef: "venn-hcf-lcm",
        hints: ["Draw the prime-factor Venn diagram for 36. The overlap must multiply to 12.", "What extra prime must sit in the other number's 'only' region so that the whole diagram multiplies to 180?", "Or: the overlap appears in both numbers, so HCF × LCM = product of the two numbers."],
        strategy: "Draw a diagram",
      },
    ],
  },
  {
    id: "sets-venn-m2",
    title: "MCQ Paper 2",
    questions: [
      {
        kind: "mcq",
        id: "sets-venn-m2-q01",
        question: "ξ = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}\n\nT = {factors of 12}\n\nList the members of T′.",
        options: ["{1, 2, 3, 4, 6, 12}", "{5, 7, 8, 9, 10, 11}", "{5, 7, 9, 11}", "{0, 5, 7, 8, 9, 10, 11}"],
        answerIndex: 1,
        explanation: "T = {1, 2, 3, 4, 6, 12}, and T′ is everything in ξ that is **not** in T: {5, 7, 8, 9, 10, 11}. {1, 2, 3, 4, 6, 12} is T itself. {5, 7, 9, 11} misses the even non-factors 8 and 10. {0, 5, 7, 8, 9, 10, 11} includes 0, but 0 is not in the universal set — a complement only contains members of ξ.",
        difficulty: "warmup",
        guideRef: "set-notation",
        hints: ["T′ means 'not in T' — but only from the numbers in ξ."],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "sets-venn-m2-q02",
        question: "What does the statement n(M ∪ S) = 15 mean?",
        options: ["There are 15 elements that are in both M and S", "There are 15 elements in M and 15 elements in S", "The number 15 is an element of M or of S", "There are 15 elements that are in M or S or both"],
        answerIndex: 3,
        explanation: "n( ) counts elements, and ∪ (union) means 'in M or S or both'. So there are 15 elements altogether inside the two circles. 'In both' describes ∩, not ∪. n(M ∪ S) is a single count, not one for each set. '15 is an element' would be written 15 ∈ M ∪ S.",
        difficulty: "warmup",
        guideRef: "set-notation",
        hints: ["What does n( ) do to a set? What does ∪ mean?"],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "sets-venn-m2-q03",
        question: "The Venn diagram shows the prime factors of two numbers, X and Y.\n\nWhat is the value of Y?",
        diagram: `<svg viewBox="0 0 320 210" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Venn diagram of prime factors. X only: 2, 3. Both: 2, 5. Y only: 7."><rect x="0" y="0" width="320" height="210" fill="#ffffff"/><rect x="10" y="10" width="300" height="190" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="125" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="195" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><text x="22" y="30" font-size="15" text-anchor="start" font-family="sans-serif" fill="#1f2937" font-style="italic">ξ</text><text x="68" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">X</text><text x="252" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">Y</text><text x="98" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">2, 3</text><text x="160" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">2, 5</text><text x="222" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">7</text></svg>`,
        options: ["70", "7", "10", "420"],
        answerIndex: 0,
        explanation: "Y is the product of every prime **inside circle Y**, including the overlap: 2 × 5 × 7 = 70. 7 is only the 'Y only' region. 10 = 2 × 5 is the overlap, which is the HCF of X and Y. 420 multiplies everything in the diagram, which gives the LCM.",
        difficulty: "warmup",
        guideRef: "venn-hcf-lcm",
        hints: ["Which primes lie inside circle Y? Remember the overlap is inside Y too."],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "sets-venn-m2-q04",
        question: "The Venn diagram shows how many of 30 students play tennis (T) and chess (K).\n\nA student is chosen at random. Find P(T′).",
        diagram: `<svg viewBox="0 0 320 210" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Two-set Venn diagram of 30 students. T only 9, T and K 6, K only 11, neither 4."><rect x="0" y="0" width="320" height="210" fill="#ffffff"/><rect x="10" y="10" width="300" height="190" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="125" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="195" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><text x="22" y="30" font-size="15" text-anchor="start" font-family="sans-serif" fill="#1f2937" font-style="italic">ξ</text><text x="68" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">T</text><text x="252" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">K</text><text x="98" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">9</text><text x="160" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">6</text><text x="222" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">11</text><text x="285" y="188" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">4</text></svg>`,
        options: ["{{11/30}}", "{{2/15}}", "{{1/2}}", "{{13/15}}"],
        answerIndex: 2,
        explanation: "T′ is everything outside circle T: K only (11) plus neither (4) = 15 students, so P(T′) = {{15/30 = 1/2}}. {{11/30}} forgets the 4 students outside both circles — they are not in T either. {{2/15}} = {{4/30}} is only the 'neither' region. {{13/15}} = {{26/30}} is P(T ∪ K).",
        difficulty: "warmup",
        guideRef: "venn-probability",
        hints: ["T′ = 'not tennis'. Which regions are outside circle T? There are two."],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "sets-venn-m2-q05",
        question: "Which set is represented by the shaded region of the Venn diagram?",
        diagram: `<svg viewBox="0 0 320 210" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Two-set Venn diagram with everything outside circle A shaded, including the part of B outside A."><rect x="0" y="0" width="320" height="210" fill="#ffffff"/><path d="M10 10 H310 V200 H10 Z M190 105 A65 65 0 1 0 60 105 A65 65 0 1 0 190 105 Z" fill="#fde68a" fill-rule="evenodd"/><rect x="10" y="10" width="300" height="190" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="125" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="195" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><text x="22" y="30" font-size="15" text-anchor="start" font-family="sans-serif" fill="#1f2937" font-style="italic">ξ</text><text x="68" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">A</text><text x="252" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">B</text></svg>`,
        options: ["A′ ∩ B", "(A ∪ B)′", "B", "A′"],
        answerIndex: 3,
        explanation: "Everything outside circle A is shaded — the 'B only' part *and* the region outside both circles. That is A′. A′ ∩ B would shade only the 'B only' part. (A ∪ B)′ would shade only the region outside both circles. B would include the overlap, which is not shaded.",
        difficulty: "core",
        guideRef: "venn-diagrams",
        hints: ["Is any part of circle A shaded?", "List every shaded region. What do they have in common?"],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "sets-venn-m2-q06",
        question: "ξ = {integers from 1 to 40}\n\nE = {even numbers}\n\nS = {square numbers}\n\nList the members of E ∩ S.",
        options: ["{4, 16, 36}", "{4, 16}", "{2, 4, 6}", "{1, 4, 9, 16, 25, 36}"],
        answerIndex: 0,
        explanation: "The square numbers up to 40 are 1, 4, 9, 16, 25, 36; the even ones are 4, 16 and 36. {4, 16} stops too early — 36 = 6² is also at most 40. {2, 4, 6} lists the square *roots* of the even squares, not the squares. {1, 4, 9, 16, 25, 36} is all of S, ignoring the 'even' condition.",
        difficulty: "core",
        guideRef: "set-notation",
        hints: ["List S first: 1², 2², 3², … while the answer is at most 40.", "Now keep only the even ones."],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "sets-venn-m2-q07",
        question: "In a class of 32 students, 20 study Physics, 17 study Biology and 9 study both.\n\nHow many students study **neither** subject?",
        options: ["23", "4", "13", "28"],
        answerIndex: 1,
        explanation: "Physics only = 20 − 9 = 11; Biology only = 17 − 9 = 8; inside the circles = 11 + 9 + 8 = 28. Neither = 32 − 28 = 4. 23 = 32 − 9 subtracts only the overlap. 13 = 32 − 11 − 8 forgets the 9 who study both. 28 is the number who study at least one subject.",
        difficulty: "core",
        guideRef: "venn-diagrams",
        hints: ["Draw two circles and put 9 in the overlap first.", "Physics only = 20 − 9. Biology only = 17 − 9.", "Neither = 32 − (everything inside the circles)."],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "sets-venn-m2-q08",
        question: "The Venn diagram shows the prime factors of 12, 18 and 30.\n\nWork out the LCM of 12, 18 and 30.",
        diagram: `<svg viewBox="0 0 320 240" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Three-set Venn diagram of prime factors. 12 only: 2. 18 only: 3. 30 only: 5. All three: 2, 3. Other regions empty."><rect x="0" y="0" width="320" height="240" fill="#ffffff"/><rect x="10" y="10" width="300" height="220" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="130" cy="95" r="60" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="190" cy="95" r="60" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="160" cy="147" r="60" fill="none" stroke="#1f2937" stroke-width="1.5"/><text x="22" y="30" font-size="15" text-anchor="start" font-family="sans-serif" fill="#1f2937" font-style="italic">ξ</text><text x="72" y="40" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">12</text><text x="248" y="40" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">18</text><text x="232" y="205" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">30</text><text x="102" y="84" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">2</text><text x="218" y="84" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">3</text><text x="160" y="188" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">5</text><text x="160" y="118" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">2, 3</text></svg>`,
        options: ["6", "6480", "180", "90"],
        answerIndex: 2,
        explanation: "The LCM is the product of every prime in the diagram, each region once: 2 × 3 × 5 × 2 × 3 = 180. Check: 180 ÷ 12 = 15, 180 ÷ 18 = 10, 180 ÷ 30 = 6. 6 is the HCF (the centre, 2 × 3). 6480 = 12 × 18 × 30 counts shared factors many times. 90 misses the extra 2 that 12 needs (12 = 2² × 3, and 90 is not a multiple of 4).",
        difficulty: "core",
        guideRef: "venn-hcf-lcm",
        hints: ["HCF = centre only. LCM = the whole diagram.", "Multiply every prime you can see, once each."],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "sets-venn-m2-q09",
        question: "The Venn diagram shows how many of 80 students go to the gym (G) and go swimming (S).\n\nA student who goes swimming is chosen at random. What is the probability that this student also goes to the gym?",
        diagram: `<svg viewBox="0 0 320 210" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Two-set Venn diagram of 80 students. G only 22, G and S 18, S only 26, neither 14."><rect x="0" y="0" width="320" height="210" fill="#ffffff"/><rect x="10" y="10" width="300" height="190" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="125" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="195" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><text x="22" y="30" font-size="15" text-anchor="start" font-family="sans-serif" fill="#1f2937" font-style="italic">ξ</text><text x="68" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">G</text><text x="252" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">S</text><text x="98" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">22</text><text x="160" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">18</text><text x="222" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">26</text><text x="285" y="188" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">14</text></svg>`,
        options: ["{{9/22}}", "{{9/40}}", "{{9/20}}", "{{1/2}}"],
        answerIndex: 0,
        explanation: "We are told the student swims, so the sample space is circle S only: 18 + 26 = 44 students. 18 of them also go to the gym, so the probability is {{18/44 = 9/22}}. {{9/40}} = {{18/80}} divides by all 80 students — that is P(G ∩ S). {{9/20}} = {{18/40}} divides by the 40 in circle G, which is 'given gym'. {{1/2}} = {{40/80}} is P(G).",
        difficulty: "core",
        guideRef: "venn-probability",
        hints: ["'A student who goes swimming is chosen' — which circle do you now restrict to?", "How many students are in circle S altogether?", "Probability = (in both) ÷ (in S)."],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "sets-venn-m2-q10",
        question: "45 Year 11 students were asked how they travel to school. 20 sometimes take the MRT and 16 sometimes take the bus. The number who take **neither** is twice the number who take **both**.\n\nHow many students take neither?",
        options: ["9", "27", "6", "18"],
        answerIndex: 3,
        explanation: "Let x take both. MRT only = 20 − x, bus only = 16 − x, neither = 2x. Total: (20 − x) + x + (16 − x) + 2x = 45, so 36 + x = 45 and x = 9. Neither = 2 × 9 = 18. 9 is the number who take both — the question asks for neither. 27 = 36 − 9 is the number who take at least one. 6 comes from 36 + 3x = 45, adding x and 2x on top of 20 + 16 without removing the double count.",
        difficulty: "core",
        guideRef: "venn-diagrams",
        hints: ["Let x be the number who take both. What goes in each region?", "MRT only = 20 − x. Bus only = 16 − x. Neither = 2x.", "All four regions add up to 45."],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "sets-venn-m2-q11",
        question: "M and N are sets with M ⊂ N.\n\nWhich of these statements **must** be true?",
        options: ["M ∪ N = M", "M ∩ N = M", "M ∩ N = ∅", "n(M) > n(N)"],
        answerIndex: 1,
        explanation: "If every member of M is also in N, the elements in both are exactly the elements of M, so M ∩ N = M. M ∪ N is N, not M (N may have extra elements). M ∩ N = ∅ would mean they share nothing — the opposite of a subset. A subset cannot be bigger than the set it sits in, so n(M) > n(N) is false.",
        difficulty: "core",
        guideRef: "set-notation",
        hints: ["Draw it: where does circle M go if M ⊂ N?", "Try a small example, e.g. M = {1, 2} and N = {1, 2, 3}, and test each statement."],
        strategy: "Try small cases",
      },
      {
        kind: "mcq",
        id: "sets-venn-m2-q12",
        question: "The Venn diagram shows the number of elements in each region.\n\nWork out n(Y ∩ Z′).",
        diagram: `<svg viewBox="0 0 320 240" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Three-set Venn diagram. X only 6, Y only 9, Z only 7, X and Y only 4, X and Z only 3, Y and Z only 2, all three 5, none 8."><rect x="0" y="0" width="320" height="240" fill="#ffffff"/><rect x="10" y="10" width="300" height="220" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="130" cy="95" r="60" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="190" cy="95" r="60" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="160" cy="147" r="60" fill="none" stroke="#1f2937" stroke-width="1.5"/><text x="22" y="30" font-size="15" text-anchor="start" font-family="sans-serif" fill="#1f2937" font-style="italic">ξ</text><text x="72" y="40" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">X</text><text x="248" y="40" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">Y</text><text x="232" y="205" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">Z</text><text x="102" y="84" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">6</text><text x="218" y="84" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">9</text><text x="160" y="188" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">7</text><text x="160" y="70" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">4</text><text x="126" y="140" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">3</text><text x="194" y="140" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">2</text><text x="160" y="118" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">5</text><text x="288" y="220" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">8</text></svg>`,
        options: ["9", "20", "13", "18"],
        answerIndex: 2,
        explanation: "Y ∩ Z′ means inside Y but outside Z: the 'Y only' region (9) plus the 'X and Y only' region (4), giving 13. 9 forgets the part of Y that is also in X. 20 is all of Y (9 + 4 + 2 + 5). 18 includes the centre (5), but the centre is inside Z.",
        difficulty: "core",
        guideRef: "venn-diagrams",
        hints: ["Shade circle Y. Now remove anything that is also inside Z.", "Which regions are left? There are two."],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "sets-venn-m2-q13",
        question: "The Venn diagram shows the number of elements in each region, in terms of x. n(ξ) = 50.\n\nAn element is chosen at random from G. What is the probability that it is also in H?",
        diagram: `<svg viewBox="0 0 320 210" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Two-set Venn diagram with algebraic regions. G only 2x, G and H x + 1, H only 13, neither 3x."><rect x="0" y="0" width="320" height="210" fill="#ffffff"/><rect x="10" y="10" width="300" height="190" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="125" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="195" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><text x="22" y="30" font-size="15" text-anchor="start" font-family="sans-serif" fill="#1f2937" font-style="italic">ξ</text><text x="68" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">G</text><text x="252" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">H</text><text x="98" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">2x</text><text x="160" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">x + 1</text><text x="222" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">13</text><text x="285" y="188" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">3x</text></svg>`,
        options: ["{{7/50}}", "{{7/19}}", "{{7/20}}", "{{19/50}}"],
        answerIndex: 1,
        explanation: "2x + (x + 1) + 13 + 3x = 50, so 6x + 14 = 50 and x = 6. The regions are G only 12, both 7, H only 13, neither 18. Given G (12 + 7 = 19 elements), the probability of H is {{7/19}}. {{7/50}} is P(G ∩ H), dividing by everything. {{7/20}} divides by n(H) = 20 — that is 'given H'. {{19/50}} is P(G).",
        difficulty: "challenge",
        guideRef: "venn-probability",
        hints: ["All four regions add up to 50. Form an equation in x.", "Solve to find x, then work out every region.", "'Chosen from G' — so divide by n(G), not by 50."],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "sets-venn-m2-q14",
        question: "n(ξ) = 50, n(E) = 30 and n(F) = 35.\n\nWhat is the **smallest** possible value of n(E ∩ F)?",
        options: ["15", "0", "5", "30"],
        answerIndex: 0,
        explanation: "n(E ∪ F) = 30 + 35 − n(E ∩ F), and E ∪ F cannot have more than 50 elements. So 65 − n(E ∩ F) ≤ 50, giving n(E ∩ F) ≥ 15. It is possible: E only 15, both 15, F only 20, outside 0. 0 is impossible — 30 + 35 = 65 elements will not fit into 50 without overlapping. 5 = 35 − 30 has no meaning here. 30 is the **largest** possible overlap (when E ⊂ F).",
        difficulty: "challenge",
        guideRef: "venn-diagrams",
        hints: ["To make the overlap small, push the circles as far apart as possible. What stops you?", "Everything has to fit inside ξ: n(E ∪ F) ≤ 50.", "n(E ∪ F) = n(E) + n(F) − n(E ∩ F)."],
        strategy: "Consider extremes",
      },
      {
        kind: "mcq",
        id: "sets-venn-m2-q15",
        question: "Two numbers x and y have HCF 6 and LCM 72. Neither number is 6 or 72, and x > y.\n\nWork out x + y.",
        options: ["78", "30", "42", "48"],
        answerIndex: 2,
        explanation: "6 = 2 × 3 is the overlap of the prime-factor Venn diagram, and 72 = 2³ × 3², so the 'only' regions must hold the extra 2 × 2 and 3 between them. If any prime goes to both sides they would share more than 6, so the 2 × 2 goes to one number and the 3 to the other: x = 6 × 4 = 24 and y = 6 × 3 = 18 (check: HCF 6, LCM 72). x + y = 42. 78 = 6 + 72 uses the forbidden pair. 30 = 12 + 18, but 12 and 18 have LCM 36. 48 = 12 + 36, but 12 and 36 have HCF 12.",
        difficulty: "challenge",
        guideRef: "venn-hcf-lcm",
        hints: ["Put 2 × 3 in the overlap. Which primes are still needed to make the LCM 72?", "72 = 2³ × 3². What is 72 ÷ 6? Split that into two 'only' regions.", "If a 2 went to each side, what would the HCF become?"],
        strategy: "Draw a diagram",
      },
    ],
  },
  {
    id: "sets-venn-m3",
    title: "MCQ Paper 3 — Exam style",
    questions: [
      {
        kind: "mcq",
        id: "sets-venn-m3-q01",
        question: "ξ = {students in Year 11}\n\nF = {students in the football CCA}\n\nH = {students in the drama CCA}\n\nWhich description matches the set F ∩ H′?",
        options: ["Students in the drama CCA but not the football CCA", "Students in neither CCA", "Students in football or drama but not both", "Students in the football CCA but not the drama CCA"],
        answerIndex: 3,
        explanation: "F ∩ H′ means 'in F **and** not in H': football but not drama. 'Drama but not football' is F′ ∩ H. 'Neither' is F′ ∩ H′, or (F ∪ H)′. 'Football or drama but not both' would be two regions, (F ∩ H′) ∪ (F′ ∩ H).",
        difficulty: "warmup",
        guideRef: "set-notation",
        hints: ["Read ∩ as 'and' and the dash ′ as 'not'."],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "sets-venn-m3-q02",
        question: "The Venn diagram shows the prime factors of 42 and 126.\n\nWork out the HCF of 42 and 126.",
        diagram: `<svg viewBox="0 0 320 210" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Venn diagram of prime factors. 42 only: empty. Both: 2, 3, 7. 126 only: 3."><rect x="0" y="0" width="320" height="210" fill="#ffffff"/><rect x="10" y="10" width="300" height="190" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="125" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="195" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><text x="22" y="30" font-size="15" text-anchor="start" font-family="sans-serif" fill="#1f2937" font-style="italic">ξ</text><text x="68" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">42</text><text x="252" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">126</text><text x="160" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">2, 3, 7</text><text x="222" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">3</text></svg>`,
        options: ["3", "42", "126", "5292"],
        answerIndex: 1,
        explanation: "The HCF is the product of the overlap: 2 × 3 × 7 = 42. Every prime factor of 42 is in the overlap, so 42 divides 126 (126 = 3 × 42) and the HCF is 42 itself. 3 is the '126 only' region. 126 is the LCM. 5292 = 42 × 126.",
        difficulty: "warmup",
        guideRef: "venn-hcf-lcm",
        hints: ["Multiply the primes in the overlap.", "Notice the '42 only' region is empty. What does that tell you?"],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "sets-venn-m3-q03",
        question: "The Venn diagram shows the members of the sets P, Q and ξ.\n\nList the members of Q′.",
        diagram: `<svg viewBox="0 0 320 210" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Two-set Venn diagram listing elements. P only: 1, 9. P and Q: 3, 5. Q only: 2, 7. Outside both: 4, 6, 8."><rect x="0" y="0" width="320" height="210" fill="#ffffff"/><rect x="10" y="10" width="300" height="190" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="125" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="195" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><text x="22" y="30" font-size="15" text-anchor="start" font-family="sans-serif" fill="#1f2937" font-style="italic">ξ</text><text x="68" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">P</text><text x="252" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">Q</text><text x="98" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">1, 9</text><text x="160" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">3, 5</text><text x="222" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">2, 7</text><text x="285" y="188" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">4, 6, 8</text></svg>`,
        options: ["{4, 6, 8}", "{1, 9}", "{1, 4, 6, 8, 9}", "{1, 3, 5, 9}"],
        answerIndex: 2,
        explanation: "Q′ is everything outside circle Q: 1 and 9 (in P only) and 4, 6, 8 (outside both). {4, 6, 8} is (P ∪ Q)′ — it misses the numbers in P that are not in Q. {1, 9} is P ∩ Q′ — it misses the outside region. {1, 3, 5, 9} is the set P.",
        difficulty: "warmup",
        guideRef: "venn-diagrams",
        hints: ["Cover up circle Q with your hand. Which numbers can you still see?"],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "sets-venn-m3-q04",
        question: "60 people at a hawker centre were asked whether they like chendol (H) and kaya toast (K). The results are shown in the Venn diagram.\n\nOne of the 60 people is chosen at random. Find P(H ∩ K).",
        diagram: `<svg viewBox="0 0 320 210" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Two-set Venn diagram of 60 people. H only 18, H and K 12, K only 21, neither 9."><rect x="0" y="0" width="320" height="210" fill="#ffffff"/><rect x="10" y="10" width="300" height="190" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="125" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="195" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><text x="22" y="30" font-size="15" text-anchor="start" font-family="sans-serif" fill="#1f2937" font-style="italic">ξ</text><text x="68" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">H</text><text x="252" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">K</text><text x="98" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">18</text><text x="160" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">12</text><text x="222" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">21</text><text x="285" y="188" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">9</text></svg>`,
        options: ["{{1/5}}", "{{1/2}}", "{{17/20}}", "{{4/11}}"],
        answerIndex: 0,
        explanation: "H ∩ K is the overlap: 12 people out of 60, so P(H ∩ K) = {{12/60 = 1/5}}. {{1/2}} = {{30/60}} is P(H) (18 + 12). {{17/20}} = {{51/60}} is P(H ∪ K). {{4/11}} = {{12/33}} divides by the 33 people in circle K — that is a 'given K' probability, but nobody said the person likes kaya toast.",
        difficulty: "warmup",
        guideRef: "venn-probability",
        hints: ["∩ is the overlap. Divide by everyone, 60."],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "sets-venn-m3-q05",
        question: "ξ = {1, 2, 3, …, 15}\n\nM = {multiples of 3}\n\nN = {factors of 30}\n\nWork out n(M ∪ N).",
        options: ["12", "3", "9", "6"],
        answerIndex: 2,
        explanation: "M = {3, 6, 9, 12, 15} and N = {1, 2, 3, 5, 6, 10, 15}. They share 3, 6 and 15, so M ∪ N = {1, 2, 3, 5, 6, 9, 10, 12, 15}, which has 9 members (or 5 + 7 − 3 = 9). 12 = 5 + 7 counts 3, 6 and 15 twice. 3 is n(M ∩ N). 6 is n((M ∪ N)′), the numbers in neither set.",
        difficulty: "core",
        guideRef: "venn-diagrams",
        hints: ["List M and N. Which numbers appear in both lists?", "Put the shared numbers in the overlap of a Venn diagram first, then fill in the rest.", "n(M ∪ N) = n(M) + n(N) − n(M ∩ N)."],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "sets-venn-m3-q06",
        question: "Which set is represented by the shaded region of the Venn diagram?",
        diagram: `<svg viewBox="0 0 320 210" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Two-set Venn diagram with every region shaded except the overlap of A and B."><rect x="0" y="0" width="320" height="210" fill="#ffffff"/><path d="M10 10 H310 V200 H10 Z M160 50.23 A65 65 0 0 1 160 159.77 A65 65 0 0 1 160 50.23 Z" fill="#fde68a" fill-rule="evenodd"/><rect x="10" y="10" width="300" height="190" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="125" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="195" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><text x="22" y="30" font-size="15" text-anchor="start" font-family="sans-serif" fill="#1f2937" font-style="italic">ξ</text><text x="68" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">A</text><text x="252" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">B</text></svg>`,
        options: ["A′ ∩ B′", "(A ∩ B)′", "A ∪ B", "(A ∪ B)′"],
        answerIndex: 1,
        explanation: "Everything **except** the overlap is shaded, so the region is 'not (in A and B)' = (A ∩ B)′. A′ ∩ B′ and (A ∪ B)′ are the same set — only the region outside both circles. A ∪ B would shade the overlap and leave the outside blank.",
        difficulty: "core",
        guideRef: "venn-diagrams",
        hints: ["Which single region is NOT shaded?", "If one region is left out, the shaded set is the complement of that region."],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "sets-venn-m3-q07",
        question: "ξ = {integers from 1 to 12}\n\nG = {x : 3x − 2 > 13}\n\nH = {factors of 24}\n\nList the members of G ∩ H.",
        options: ["{4, 6, 8, 12}", "{1, 2, 3, 4}", "{6, 7, 8, 9, 10, 11, 12}", "{6, 8, 12}"],
        answerIndex: 3,
        explanation: "3x − 2 > 13 gives 3x > 15, so x > 5 and G = {6, 7, 8, 9, 10, 11, 12}. H = {1, 2, 3, 4, 6, 8, 12}. In both: {6, 8, 12}. {4, 6, 8, 12} comes from subtracting 2 instead of adding it (3x > 11, so x > 3.67). {1, 2, 3, 4} is G′ ∩ H. {6, 7, …, 12} is just G.",
        difficulty: "core",
        guideRef: "set-notation",
        hints: ["Solve the inequality to describe G as a list.", "3x − 2 > 13 → 3x > 15 → x > 5.", "Now list the factors of 24 and pick out the common members."],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "sets-venn-m3-q08",
        question: "Two buses leave Tampines interchange at 08:00. One route departs every 12 minutes and the other every 18 minutes.\n\nAt what time will both routes next depart together?",
        options: ["08:36", "08:06", "11:36", "08:30"],
        answerIndex: 0,
        explanation: "12 = 2² × 3 and 18 = 2 × 3², so the LCM is 2² × 3² = 36. They next leave together 36 minutes later, at 08:36. 08:06 uses the HCF (6), which is when neither bus is due. 11:36 uses 12 × 18 = 216 minutes, a common multiple but not the lowest. 08:30 adds 12 + 18.",
        difficulty: "core",
        guideRef: "venn-hcf-lcm",
        hints: ["Both buses leave together after a time that is a multiple of 12 *and* of 18.", "You want the **lowest** common multiple. Use prime factors or list the multiples."],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "sets-venn-m3-q09",
        question: "The Venn diagram shows how many of 60 students study French (F), Spanish (S) and Mandarin (M).\n\nA student who studies Mandarin is chosen at random. Find the probability that this student also studies French.",
        diagram: `<svg viewBox="0 0 320 240" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Three-set Venn diagram of 60 students. F only 14, S only 9, M only 11, F and S only 5, F and M only 6, S and M only 3, all three 2, none 10."><rect x="0" y="0" width="320" height="240" fill="#ffffff"/><rect x="10" y="10" width="300" height="220" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="130" cy="95" r="60" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="190" cy="95" r="60" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="160" cy="147" r="60" fill="none" stroke="#1f2937" stroke-width="1.5"/><text x="22" y="30" font-size="15" text-anchor="start" font-family="sans-serif" fill="#1f2937" font-style="italic">ξ</text><text x="72" y="40" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">F</text><text x="248" y="40" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">S</text><text x="232" y="205" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">M</text><text x="102" y="84" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">14</text><text x="218" y="84" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">9</text><text x="160" y="188" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">11</text><text x="160" y="70" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">5</text><text x="126" y="140" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">6</text><text x="194" y="140" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">3</text><text x="160" y="118" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">2</text><text x="288" y="220" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">10</text></svg>`,
        options: ["{{3/11}}", "{{4/11}}", "{{2/15}}", "{{8/27}}"],
        answerIndex: 1,
        explanation: "Circle M holds 11 + 6 + 3 + 2 = 22 students. Of these, 6 + 2 = 8 also study French, so the probability is {{8/22 = 4/11}}. {{3/11}} = {{6/22}} forgets the 2 students in the centre who study all three. {{2/15}} = {{8/60}} divides by all 60 students. {{8/27}} divides by the 27 in circle F — that is 'given French'.",
        difficulty: "core",
        guideRef: "venn-probability",
        hints: ["Restrict to circle M. How many students is that?", "Which parts of circle M are also inside circle F? Don't miss the centre.", "Probability = (in F and M) ÷ (in M)."],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "sets-venn-m3-q10",
        question: "The Venn diagram shows the number of elements in each region, in terms of x. n(ξ) = 32.\n\nWork out n(E).",
        diagram: `<svg viewBox="0 0 320 210" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Two-set Venn diagram with algebraic regions. E only 2x, E and F 5, F only x + 3, neither x."><rect x="0" y="0" width="320" height="210" fill="#ffffff"/><rect x="10" y="10" width="300" height="190" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="125" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="195" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><text x="22" y="30" font-size="15" text-anchor="start" font-family="sans-serif" fill="#1f2937" font-style="italic">ξ</text><text x="68" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">E</text><text x="252" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">F</text><text x="98" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">2x</text><text x="160" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">5</text><text x="222" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">x + 3</text><text x="285" y="188" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">x</text></svg>`,
        options: ["6", "12", "17", "26"],
        answerIndex: 2,
        explanation: "2x + 5 + (x + 3) + x = 32, so 4x + 8 = 32 and x = 6. E contains the 'E only' region (2x = 12) and the overlap (5): n(E) = 17. 6 is x itself. 12 is only the 'E only' region. 26 is n(E ∪ F) = 12 + 5 + 9.",
        difficulty: "core",
        guideRef: "venn-diagrams",
        hints: ["All four regions add up to n(ξ) = 32.", "Solve 4x + 8 = 32.", "n(E) includes the overlap."],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "sets-venn-m3-q11",
        question: "S = {letters in the word SINGAPORE}\n\nT = {letters in the word SENTOSA}\n\nWork out n(S ∩ T).",
        options: ["5", "6", "10", "7"],
        answerIndex: 0,
        explanation: "S = {S, I, N, G, A, P, O, R, E} and T = {S, E, N, T, O, A}. A set lists each member once, so the repeated S in SENTOSA counts only once. Common letters: S, N, A, O, E — 5 of them. 6 counts the S in SENTOSA twice. 10 is n(S ∪ T) = 9 + 6 − 5. 7 is the number of letters in SENTOSA, not the number of shared members.",
        difficulty: "core",
        guideRef: "set-notation",
        hints: ["Write each set as a list. Does a repeated letter appear twice in a set?", "Now tick the letters that appear in both lists."],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "sets-venn-m3-q12",
        question: "The Venn diagram shows the probabilities of events X and Y.\n\nWork out P(X′ ∪ Y).",
        diagram: `<svg viewBox="0 0 320 210" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Two-set Venn diagram of probabilities. X only 0.25, X and Y 0.15, Y only 0.3, outside both not given."><rect x="0" y="0" width="320" height="210" fill="#ffffff"/><rect x="10" y="10" width="300" height="190" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="125" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><circle cx="195" cy="105" r="65" fill="none" stroke="#1f2937" stroke-width="1.5"/><text x="22" y="30" font-size="15" text-anchor="start" font-family="sans-serif" fill="#1f2937" font-style="italic">ξ</text><text x="68" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">X</text><text x="252" y="46" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937" font-weight="bold">Y</text><text x="98" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">0.25</text><text x="160" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">0.15</text><text x="222" y="110" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">0.3</text></svg>`,
        options: ["0.6", "0.45", "0.3", "0.75"],
        answerIndex: 3,
        explanation: "The missing probability outside both circles is 1 − 0.25 − 0.15 − 0.3 = 0.3. X′ ∪ Y is everything that is outside X **or** inside Y — every region except 'X only'. So P(X′ ∪ Y) = 1 − 0.25 = 0.75. 0.6 is P(X′) alone (it leaves out the overlap, which is in Y). 0.45 is P(Y). 0.3 is P(X′ ∩ Y′), the region outside both.",
        difficulty: "core",
        guideRef: "venn-probability",
        hints: ["First find the missing probability outside both circles — the total is 1.", "Shade X′, then also shade Y. Which region is left unshaded?", "P(X′ ∪ Y) = 1 − P(that region)."],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "sets-venn-m3-q13",
        question: "Which statement is true for **all** sets A and B?",
        options: ["(A ∩ B)′ = A′ ∩ B′", "A ∩ B′ = (A ∩ B)′", "n(A ∪ B) = n(A) + n(B)", "(A ∪ B)′ = A′ ∩ B′"],
        answerIndex: 3,
        explanation: "Outside the union means outside both circles: 'not in A and not in B'. So (A ∪ B)′ = A′ ∩ B′ for any two sets — this is De Morgan's law. (A ∩ B)′ is everything except the overlap, but A′ ∩ B′ is only the region outside both circles; any element in A only shows they differ. A ∩ B′ is just one region, while (A ∩ B)′ is three regions. Adding the sizes of A and B to get the size of the union fails whenever the sets overlap, because the overlap is counted twice.",
        difficulty: "challenge",
        guideRef: "set-notation",
        hints: ["Shade both sides of each statement on its own Venn diagram.", "A statement that is true for all sets must survive every counter-example — try the 'A only' region.", "'Not (A or B)' — how would you say that in words using 'and'?"],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "sets-venn-m3-q14",
        question: "Three lights flash every 8 seconds, 12 seconds and 20 seconds. They all flash together at exactly 12:00 noon.\n\nHow many more times will they all flash together up to and including 1:00 p.m.?",
        options: ["31", "15", "30", "1"],
        answerIndex: 2,
        explanation: "8 = 2³, 12 = 2² × 3, 20 = 2² × 5, so the LCM is 2³ × 3 × 5 = 120 seconds. One hour is 3600 s, and 3600 ÷ 120 = 30 more flashes together (the last at exactly 1:00 p.m.). 31 also counts the flash at noon, which the question excludes ('more times'). 15 uses 240 s, putting 2⁴ in the LCM instead of the highest power 2³. 1 uses 8 × 12 × 20 = 1920 s, a common multiple but not the lowest.",
        difficulty: "challenge",
        guideRef: "venn-hcf-lcm",
        hints: ["How long between the times all three flash together?", "Find the LCM of 8, 12 and 20 using a three-set prime-factor Venn diagram.", "How many of those gaps fit into 3600 seconds? Is noon itself included?"],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "sets-venn-m3-q15",
        question: "X and Y are **independent** events. P(X) = 0.4 and P(X ∩ Y) = 0.12.\n\nWork out P(X′ ∩ Y′).",
        options: ["0.58", "0.42", "0.48", "0.18"],
        answerIndex: 1,
        explanation: "Independent means P(X ∩ Y) = P(X) × P(Y), so P(Y) = 0.12 ÷ 0.4 = 0.3. Regions: X only 0.28, both 0.12, Y only 0.18, so outside both = 1 − 0.58 = 0.42 (check: 0.6 × 0.7 = 0.42). 0.58 is P(X ∪ Y). 0.48 = 1 − 0.4 − 0.12 forgets the 'Y only' region. 0.18 is P(X′ ∩ Y), the 'Y only' region.",
        difficulty: "challenge",
        guideRef: "venn-probability",
        hints: ["What does independence tell you about P(X ∩ Y)?", "Find P(Y) first, then fill in all four regions of a Venn diagram.", "The four regions add to 1."],
        strategy: "Work backwards",
      },
    ],
  },
];
