// Quadratic equations — MCQ papers (3 × 15). Options are shuffled at display time.
import type { Paper } from "../../types.ts";

export const mcqPapers: Paper[] = [
  {
    id: "quadratic-equations-m1",
    title: "MCQ Paper 1",
    questions: [
      {
        kind: "mcq",
        id: "quadratic-equations-m1-q01",
        question: "Solve {{(x - 2)^2 = 25}}.",
        options: ["x = 7 or x = −3", "x = 7", "x = 27 or x = −23", "x = −7 or x = 3"],
        answerIndex: 0,
        explanation:
          "No expanding needed: square-root both sides, remembering **both** roots. {{x - 2 = 5}} or {{x - 2 = -5}}, so x = 7 or x = −3. Check: {{(-3 - 2)^2 = 25}} ✓. x = 7 alone forgets the negative square root. x = 27 or −23 uses {{x - 2 = +- 25}} — the square root was never taken. x = −7 or 3 solves {{(x + 2)^2 = 25}}, a sign slip.",
        difficulty: "warmup",
        guideRef: "solve-by-factorising",
        hints: ["What undoes a square? And how many numbers square to give 25?"],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m1-q02",
        question: "Solve {{x^2 - 5x - 14 = 0}}.",
        options: ["x = −7 or x = 2", "x = 14 or x = −1", "x = 7 or x = −2", "x = 7 or x = 2"],
        answerIndex: 2,
        explanation:
          "Find two numbers that multiply to −14 and add to −5: −7 and +2. So {{(x - 7)(x + 2) = 0}}, giving x = 7 or x = −2. x = −7 or 2 copies the numbers from the brackets without changing sign. x = 14 or −1 comes from (x − 14)(x + 1): the pair −14 and 1 multiplies to −14 but adds to −13, not −5. x = 7 or 2 would need a product of +14.",
        difficulty: "warmup",
        guideRef: "solve-by-factorising",
        hints: ["Which pair of numbers multiplies to −14 and adds to −5? Then set each bracket equal to zero."],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m1-q03",
        question: "Solve {{x^2 = 7x}}.",
        options: ["x = 7", "x = 0 or x = 7", "x = 0 or x = −7", "x = {{sqrt(7)}} or x = {{-sqrt(7)}}"],
        answerIndex: 1,
        explanation:
          "Rearrange to = 0 first: {{x^2 - 7x = 0}}, so {{x(x - 7) = 0}} and x = 0 or x = 7. Dividing both sides by x gives x = 7 only — it throws away x = 0, because you can't divide by something that might be zero. x = 0 or −7 is a sign slip in the bracket. ±{{sqrt(7)}} treats the equation as {{x^2 = 7}}.",
        difficulty: "warmup",
        guideRef: "solve-by-factorising",
        hints: ["Don't divide by x — it might be 0. Get everything on one side and factorise instead."],
        strategy: "Split into cases",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m1-q04",
        question: "What is the value of the discriminant {{b^2 - 4ac}} for {{2x^2 - 3x + 5 = 0}}?",
        options: ["49", "−49", "−11", "−31"],
        answerIndex: 3,
        explanation:
          "a = 2, b = −3, c = 5, so {{b^2 - 4ac = (-3)^2 - 4 * 2 * 5 = 9 - 40 = -31}}. It is negative, so the equation has no real roots. 49 comes from {{b^2 + 4ac}}. −49 squares −3 to get −9 (put −3 in brackets: {{(-3)^2 = 9}}). −11 leaves a out of 4ac.",
        difficulty: "warmup",
        guideRef: "quadratic-formula",
        hints: ["Write down a, b and c with their signs, then put b in brackets before squaring it."],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m1-q05",
        question: "Solve {{3x^2 + 10x - 8 = 0}}.",
        options: ["x = 2 or x = −4", "x = {{-2/3}} or x = 4", "x = {{2/3}} or x = −4", "x = {{3/2}} or x = −4"],
        answerIndex: 2,
        explanation:
          "ac = 3 × (−8) = −24; the pair 12 and −2 multiplies to −24 and adds to 10. Split: {{3x^2 + 12x - 2x - 8 = 3x(x + 4) - 2(x + 4) = (3x - 2)(x + 4)}}. So {{3x - 2 = 0}} gives x = {{2/3}}, and x = −4. x = 2 forgets to divide by the 3. {{3/2}} divides the wrong way round. {{-2/3}} or 4 has both signs flipped.",
        difficulty: "core",
        guideRef: "solve-by-factorising",
        hints: [
          "When a ≠ 1, find two numbers that multiply to ac = −24 and add to b = 10.",
          "12 and −2 work. Split 10x into 12x − 2x and factorise in pairs.",
          "For the bracket (3x − 2), solve 3x − 2 = 0 — don't just read off the 2.",
        ],
        strategy: "Find a pattern",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m1-q06",
        question: "The rectangle has length (x + 5) cm, width (x − 2) cm and area 60 cm². Find the **width** of the rectangle.",
        diagram: `<svg viewBox="0 0 320 200" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Rectangle with length labelled (x + 5) cm, width labelled (x − 2) cm and area 60 square centimetres"><rect x="0" y="0" width="320" height="200" fill="#ffffff"/><rect x="40" y="50" width="216" height="90" fill="#fde68a" stroke="#1f2937" stroke-width="2"/><text x="148" y="40" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">(x + 5) cm</text><text x="264" y="100" font-size="13" font-family="sans-serif" fill="#1f2937">(x − 2) cm</text><text x="148" y="100" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937">60 cm²</text></svg>`,
        options: ["5 cm", "7 cm", "12 cm", "−12 cm"],
        answerIndex: 0,
        explanation:
          "{{(x + 5)(x - 2) = 60}} gives {{x^2 + 3x - 10 = 60}}, so {{x^2 + 3x - 70 = 0}} and {{(x + 10)(x - 7) = 0}}. x = −10 would make the width −12 cm, so reject it: x = 7 and the width is 7 − 2 = 5 cm (check: 12 × 5 = 60 ✓). 7 cm is x, not the width. 12 cm is the length. −12 cm comes from keeping x = −10 — a length can't be negative.",
        difficulty: "core",
        guideRef: "solve-by-factorising",
        hints: [
          "Area = length × width. Write the equation, expand and make it = 0.",
          "You should get {{x^2 + 3x - 70 = 0}}. Which root makes sense for a length?",
          "Re-read the question: it asks for the width, not x.",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m1-q07",
        question: "By completing the square, solve {{x^2 + 8x + 5 = 0}}. Give your answers in surd form.",
        options: ["x = 4 ± {{sqrt(11)}}", "x = −4 ± {{sqrt(21)}}", "x = −8 ± {{sqrt(59)}}", "x = −4 ± {{sqrt(11)}}"],
        answerIndex: 3,
        explanation:
          "Halve 8 to get 4: {{x^2 + 8x = (x + 4)^2 - 16}}. So {{(x + 4)^2 - 16 + 5 = 0}}, i.e. {{(x + 4)^2 = 11}}, giving {{x + 4 = +- sqrt(11)}} and x = −4 ± {{sqrt(11)}}. 4 ± {{sqrt(11)}} forgets to subtract 4 at the end (sign slip). −4 ± {{sqrt(21)}} uses 16 + 5 instead of 16 − 5. −8 ± {{sqrt(59)}} uses {{(x + 8)^2}} — the 8 wasn't halved.",
        difficulty: "core",
        guideRef: "solve-completing-square",
        hints: [
          "Halve the coefficient of x to get the number in the bracket.",
          "{{(x + 4)^2}} expands to {{x^2 + 8x + 16}} — so you've added 16 too many. Take it away.",
          "Get {{(x + 4)^2}} on its own, then square-root both sides (±).",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m1-q08",
        question: "Solve {{2x^2 - 7x + 2 = 0}}. Give your answers correct to 3 significant figures.",
        options: ["x = 6.37 or x = 0.628", "x = 3.19 or x = 0.314", "x = −3.19 or x = −0.314", "x = 3.77 or x = −0.266"],
        answerIndex: 1,
        explanation:
          "a = 2, b = −7, c = 2: {{x = (7 +- sqrt(49 - 16))/4 = (7 +- sqrt(33))/4}}, so x = 3.186… or 0.3138… → 3.19 or 0.314. 6.37 and 0.628 divide by 2 instead of 2a = 4. −3.19 and −0.314 use −b = −7 (b is already −7, so −b = +7). 3.77 and −0.266 use {{b^2 + 4ac = 65}}.",
        difficulty: "core",
        guideRef: "quadratic-formula",
        hints: [
          "Write a, b and c with their signs before substituting.",
          "b = −7, so −b = +7. The discriminant is {{49 - 4 * 2 * 2}}.",
          "The whole of {{-b +- sqrt(b^2 - 4ac)}} is divided by 2a = 4.",
        ],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m1-q09",
        question: "Solve the simultaneous equations\n\n    {{y = x + 1}}\n    {{y = x^2 - 5}}",
        options: ["(3, −1) and (−2, 4)", "(3, 4) and (−2, −1)", "(−3, −2) and (2, 3)", "(6, 7) and (−1, 0)"],
        answerIndex: 1,
        explanation:
          "Set the two expressions for y equal: {{x^2 - 5 = x + 1}}, so {{x^2 - x - 6 = 0}} and {{(x - 3)(x + 2) = 0}}. Substitute each x into the **linear** equation: x = 3 → y = 4; x = −2 → y = −1. (3, −1) and (−2, 4) pair the y-values with the wrong x-values. (−3, −2) and (2, 3) come from factorising as (x + 3)(x − 2). (6, 7) and (−1, 0) come from (x − 6)(x + 1): the pair −6 and 1 multiplies to −6 but adds to −5, not −1.",
        difficulty: "core",
        guideRef: "linear-quadratic-simultaneous",
        hints: [
          "Both equations say what y is — so put the two right-hand sides equal.",
          "Rearrange to {{x^2 - x - 6 = 0}} and factorise.",
          "Find each y from y = x + 1 and keep each pair together.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m1-q10",
        question: "Solve {{6/x - 6/(x + 1) = 1}}.",
        options: ["x = 3 or x = −2", "There is no solution", "x = 2 or x = −3", "x = 2 only, because x = −3 must be rejected"],
        answerIndex: 2,
        explanation:
          "Multiply **every** term by x(x + 1): {{6(x + 1) - 6x = x(x + 1)}}, so {{6 = x^2 + x}} and {{x^2 + x - 6 = (x + 3)(x - 2) = 0}}. x = 2 or x = −3; neither makes a denominator zero, so both stand. \"No solution\" comes from forgetting to multiply the 1 on the right (giving 6 = 1). x = 3 or −2 is a sign slip in the factorising. Negative answers are only rejected if they make a denominator zero or make no sense in context — −3 does neither.",
        difficulty: "core",
        guideRef: "algebraic-fraction-equations",
        hints: [
          "What expression is a common denominator for both fractions?",
          "Multiply every term — including the 1 — by x(x + 1).",
          "The only values you must reject are those that make a denominator zero: here x = 0 and x = −1.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m1-q11",
        question: "By completing the square, solve {{2x^2 + 12x + 7 = 0}}. Give your answers in exact form.",
        options: ["x = −3 ± {{sqrt(22)/2}}", "x = −3 ± {{sqrt(11)}}", "x = −2 or x = −4", "x = 3 ± {{sqrt(22)/2}}"],
        answerIndex: 0,
        explanation:
          "Take out the 2 from the x terms: {{2(x^2 + 6x) + 7 = 2[(x + 3)^2 - 9] + 7 = 2(x + 3)^2 - 11}}. So {{(x + 3)^2 = 11/2}} and {{x = -3 +- sqrt(11/2) = -3 +- sqrt(22)/2}}. −3 ± {{sqrt(11)}} forgets to divide 11 by 2. x = −2 or −4 writes −9 instead of 2 × (−9) = −18 when expanding the square bracket. 3 ± … has the sign of 3 wrong.",
        difficulty: "core",
        guideRef: "solve-completing-square",
        hints: [
          "Factor the 2 out of the {{x^2}} and x terms first.",
          "Inside: {{x^2 + 6x = (x + 3)^2 - 9}}. Multiply the −9 by the 2 outside too.",
          "Rationalise: {{sqrt(11/2) = sqrt(11)/sqrt(2) = sqrt(22)/2}}.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m1-q12",
        question: "The equation {{x^2 + kx + 9 = 0}} has exactly one (repeated) root. Find the possible values of k.",
        options: ["k = 6 only", "k = 3 or k = −3", "k = 36", "k = 6 or k = −6"],
        answerIndex: 3,
        explanation:
          "One repeated root means the discriminant is 0: {{k^2 - 4 * 1 * 9 = 0}}, so {{k^2 = 36}} and k = ±6. Check: {{x^2 + 6x + 9 = (x + 3)^2}} and {{x^2 - 6x + 9 = (x - 3)^2}}. k = 6 only forgets the negative root of {{k^2 = 36}}. k = ±3 sets {{k^2 = 9}} (forgot the 4a). k = 36 doesn't square-root.",
        difficulty: "core",
        guideRef: "quadratic-formula",
        hints: [
          "What must {{b^2 - 4ac}} equal for a repeated root?",
          "Here a = 1, b = k, c = 9. Solve {{k^2 - 36 = 0}}.",
          "{{k^2 = 36}} has two solutions.",
        ],
        strategy: "Work backwards",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m1-q13",
        question: "The line {{y = 2x + c}} is a tangent to the curve {{y = x^2 + 3}} (it touches the curve at exactly one point). Find c.",
        options: ["c = −2", "c = 2", "c = 3", "c = −1"],
        answerIndex: 1,
        explanation:
          "Where they meet, {{x^2 + 3 = 2x + c}}, so {{x^2 - 2x + (3 - c) = 0}}. Exactly one meeting point means a repeated root: {{(-2)^2 - 4(3 - c) = 0}}, so {{4 - 12 + 4c = 0}} and c = 2. (The line touches at (1, 4).) c = −2 writes the constant as 3 + c. c = −1 drops the +3 altogether. c = 3 just matches the y-intercepts — the line and curve would then cross at x = 0 and x = 2.",
        difficulty: "challenge",
        guideRef: "linear-quadratic-simultaneous",
        hints: [
          "What does 'touches at exactly one point' mean for the quadratic you get by equating the two?",
          "Rearrange to {{x^2 - 2x + (3 - c) = 0}}.",
          "A single (repeated) solution means the discriminant is zero.",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m1-q14",
        question: "Solve {{x^4 - 10x^2 + 9 = 0}}.",
        options: ["x = 1 or x = 9", "x = 1 or x = 3", "x = ±1 or x = ±3", "x = ±1 or x = ±9"],
        answerIndex: 2,
        explanation:
          "Let {{u = x^2}}: {{u^2 - 10u + 9 = (u - 1)(u - 9) = 0}}, so u = 1 or u = 9. Now go back to x: {{x^2 = 1}} gives x = ±1 and {{x^2 = 9}} gives x = ±3 — four solutions. x = 1 or 9 stops at u. x = 1 or 3 forgets the negative square roots. ±1 or ±9 forgets to square-root the 9.",
        difficulty: "challenge",
        guideRef: "disguised-quadratics",
        hints: [
          "Notice {{x^4 = (x^2)^2}}. What substitution turns this into an ordinary quadratic?",
          "With {{u = x^2}} you get {{u^2 - 10u + 9 = 0}}. Solve for u.",
          "Don't stop at u — each value of {{x^2}} gives two values of x.",
        ],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m1-q15",
        question: "The right-angled triangle has sides x cm, (x + 7) cm and hypotenuse (x + 8) cm. Find x.",
        diagram: `<svg viewBox="0 0 320 280" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Right-angled triangle: vertical side x cm, horizontal side (x + 7) cm, hypotenuse (x + 8) cm"><rect x="0" y="0" width="320" height="280" fill="#ffffff"/><polygon points="60,230 276,230 60,140" fill="#bae6fd" stroke="#1f2937" stroke-width="2"/><polyline points="60,216 74,216 74,230" fill="none" stroke="#1f2937" stroke-width="1.5"/><text x="50" y="190" font-size="13" text-anchor="end" font-family="sans-serif" fill="#1f2937">x cm</text><text x="168" y="252" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">(x + 7) cm</text><text x="180" y="172" font-size="13" font-family="sans-serif" fill="#1f2937">(x + 8) cm</text></svg>`,
        options: ["x = 3", "x = 15", "x = −3 or x = 5", "x = 5"],
        answerIndex: 3,
        explanation:
          "Pythagoras: {{x^2 + (x + 7)^2 = (x + 8)^2}}, so {{x^2 + x^2 + 14x + 49 = x^2 + 16x + 64}}, giving {{x^2 - 2x - 15 = 0}} and {{(x - 5)(x + 3) = 0}}. x = −3 would make a side negative, so x = 5 (a 5, 12, 13 triangle ✓). Keeping x = −3 ignores the context. x = 3 is a sign slip in the factorising. x = 15 just reads off the constant term.",
        difficulty: "challenge",
        guideRef: "solve-by-factorising",
        hints: [
          "Which side is the hypotenuse? Write Pythagoras' theorem with the brackets.",
          "Expand {{(x + 7)^2}} and {{(x + 8)^2}} fully — they each have three terms.",
          "You should reach {{x^2 - 2x - 15 = 0}}. Which root is a sensible length?",
        ],
        strategy: "Draw a diagram",
      },
    ],
  },
  {
    id: "quadratic-equations-m2",
    title: "MCQ Paper 2",
    questions: [
      {
        kind: "mcq",
        id: "quadratic-equations-m2-q01",
        question: "Write {{x^2 - 10x + 3}} in the form {{(x + p)^2 + q}}.",
        options: ["{{(x - 5)^2 + 28}}", "{{(x - 10)^2 - 97}}", "{{(x + 5)^2 - 22}}", "{{(x - 5)^2 - 22}}"],
        answerIndex: 3,
        explanation:
          "Halve −10 to get −5: {{(x - 5)^2 = x^2 - 10x + 25}}, which is 25 too many, so {{x^2 - 10x + 3 = (x - 5)^2 - 25 + 3 = (x - 5)^2 - 22}}. +28 adds the 25 instead of subtracting it. {{(x - 10)^2}} forgets to halve. {{(x + 5)^2}} has the wrong sign inside the bracket.",
        difficulty: "warmup",
        guideRef: "solve-completing-square",
        hints: ["Halve the coefficient of x for the bracket, then subtract the square of that number."],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m2-q02",
        question: "Using the quadratic formula on {{x^2 + 4x - 1 = 0}}, which line is correct?",
        options: [
          "{{x = (4 +- sqrt(20))/2}}",
          "{{x = (-4 +- sqrt(20))/2}}",
          "{{x = (-4 +- sqrt(12))/2}}",
          "{{x = -4 +- sqrt(20)/2}}",
        ],
        answerIndex: 1,
        explanation:
          "a = 1, b = 4, c = −1: {{b^2 - 4ac = 16 - 4(1)(-1) = 20}}, so {{x = (-4 +- sqrt(20))/2}} (= −2 ± {{sqrt(5)}}). (4 ± …) forgets the minus in −b. {{sqrt(12)}} treats c as +1, so −4ac became −4. Writing −4 ± {{sqrt(20)/2}} divides only the square root by 2a — the whole numerator must be divided.",
        difficulty: "warmup",
        guideRef: "quadratic-formula",
        hints: ["c = −1, so −4ac = −4 × 1 × (−1) = +4. The fraction line goes under the whole of −b ± √…"],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m2-q03",
        question: "Solve {{3x^2 - 48 = 0}}.",
        options: ["x = 4 or x = −4", "x = 4", "x = 16 or x = −16", "x = 8 or x = −8"],
        answerIndex: 0,
        explanation:
          "No factorising needed: {{3x^2 = 48}}, so {{x^2 = 16}} and x = ±4. x = 4 alone misses the negative root ({{(-4)^2 = 16}} too). ±16 stops before square-rooting. ±8 halves 16 instead of square-rooting it.",
        difficulty: "warmup",
        guideRef: "solve-by-factorising",
        hints: ["Get {{x^2}} on its own, then square-root — and remember there are two roots."],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m2-q04",
        question: "Substituting {{y = 2x - 1}} into {{x^2 + y^2 = 10}} gives which equation?",
        options: ["{{5x^2 - 11 = 0}}", "{{x^2 + 2x - 11 = 0}}", "{{5x^2 - 4x - 9 = 0}}", "{{3x^2 - 4x - 9 = 0}}"],
        answerIndex: 2,
        explanation:
          "{{x^2 + (2x - 1)^2 = 10}}. Expand carefully: {{(2x - 1)^2 = 4x^2 - 4x + 1}}. So {{5x^2 - 4x + 1 = 10}}, i.e. {{5x^2 - 4x - 9 = 0}} (which factorises as (5x − 9)(x + 1)). {{5x^2 - 11 = 0}} squares the bracket as {{4x^2 - 1}}, losing the middle term. {{x^2 + 2x - 11 = 0}} forgets to square y. {{3x^2 - 4x - 9 = 0}} squares 2x as {{2x^2}} instead of {{4x^2}}.",
        difficulty: "warmup",
        guideRef: "linear-quadratic-simultaneous",
        hints: ["Replace y with (2x − 1) in brackets, then expand {{(2x - 1)^2}} as (2x − 1)(2x − 1)."],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m2-q05",
        question: "Solve {{6x^2 - x - 2 = 0}}.",
        options: ["x = {{2/3}} or x = {{-1/2}}", "x = 2 or x = −1", "x = {{-2/3}} or x = {{1/2}}", "x = {{3/2}} or x = −2"],
        answerIndex: 0,
        explanation:
          "ac = −12; −4 and 3 multiply to −12 and add to −1. {{6x^2 - 4x + 3x - 2 = 2x(3x - 2) + 1(3x - 2) = (3x - 2)(2x + 1)}}. So x = {{2/3}} or x = {{-1/2}}. x = 2 or −1 reads numbers off the brackets without dividing by the x-coefficients. {{-2/3}} and {{1/2}} flip both signs. {{3/2}} and −2 divide the wrong way round.",
        difficulty: "core",
        guideRef: "solve-by-factorising",
        hints: [
          "Multiply a × c. Which pair of factors of −12 add to −1?",
          "Split −x into −4x + 3x and factorise in pairs.",
          "Solve each bracket = 0 properly, e.g. 3x − 2 = 0.",
        ],
        strategy: "Find a pattern",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m2-q06",
        question: "A ball is thrown upwards. Its height, h metres, after t seconds is {{h = 20t - 5t^2}}. At what times is the ball exactly 15 m above the ground?",
        options: ["t = 1 only", "t = −1 and t = −3", "t = 3 only", "t = 1 and t = 3"],
        answerIndex: 3,
        explanation:
          "{{20t - 5t^2 = 15}} → {{5t^2 - 20t + 15 = 0}} → divide by 5: {{t^2 - 4t + 3 = (t - 1)(t - 3) = 0}}. So t = 1 (on the way up) and t = 3 (on the way down) — both make sense, so keep both. Choosing only one root ignores that the ball passes 15 m twice. −1 and −3 come from a sign slip; negative times would also be rejected here.",
        difficulty: "core",
        guideRef: "solve-by-factorising",
        hints: [
          "Set h = 15 and rearrange so one side is 0.",
          "Divide every term by 5 to make the numbers friendlier.",
          "Think about the flight of a ball: how many times does it pass a given height?",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m2-q07",
        question: "Wei Ling completes the square on {{x^2 - 6x + 14 = 0}}. What does she find?",
        options: [
          "x = 3 ± {{sqrt(5)}}",
          "x = −3 ± {{sqrt(5)}}",
          "There are no real solutions, because {{(x - 3)^2 = -5}}",
          "x = 3 ± {{sqrt(23)}}",
        ],
        answerIndex: 2,
        explanation:
          "{{x^2 - 6x + 14 = (x - 3)^2 - 9 + 14 = (x - 3)^2 + 5}}. Setting this to 0 gives {{(x - 3)^2 = -5}}, but a square is never negative — so no real solutions. (The minimum value of the expression is 5, at x = 3.) 3 ± {{sqrt(5)}} moves +5 across without changing its sign. −3 ± {{sqrt(5)}} adds a bracket-sign slip too. 3 ± {{sqrt(23)}} uses 9 + 14 instead of 9 − 14.",
        difficulty: "core",
        guideRef: "solve-completing-square",
        hints: [
          "Halve −6 for the bracket, then subtract 9.",
          "You should get {{(x - 3)^2 + 5 = 0}}. Move the 5 across.",
          "Can a squared number ever be negative?",
        ],
        strategy: "Consider extremes",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m2-q08",
        question: "Solve {{3x^2 + 5x - 1 = 0}}. Give your answers correct to 3 significant figures.",
        options: ["x = −0.232 or x = −1.43", "x = 0.180 or x = −1.85", "x = 0.361 or x = −3.69", "x = 1.85 or x = −0.180"],
        answerIndex: 1,
        explanation:
          "a = 3, b = 5, c = −1: {{x = (-5 +- sqrt(25 + 12))/6 = (-5 +- sqrt(37))/6}}, so x = 0.1804… or −1.847… → 0.180 or −1.85. −0.232 and −1.43 use {{25 - 12}} (treating c as +1). 0.361 and −3.69 divide by a = 3 instead of 2a = 6. 1.85 and −0.180 use +b instead of −b.",
        difficulty: "core",
        guideRef: "quadratic-formula",
        hints: [
          "Write a = 3, b = 5, c = −1.",
          "{{-4ac = -4 * 3 * (-1) = +12}}, so the discriminant is 37.",
          "Divide by 2a = 6, and give 0.180 to 3 s.f. (the zero counts).",
        ],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m2-q09",
        question: "The diagram shows the circle {{x^2 + y^2 = 25}} and the line {{y = x - 1}}, meeting at A and B. Find the coordinates of A and B.",
        diagram: `<svg viewBox="0 0 320 300" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Circle centre the origin radius 5 with the line y = x − 1 crossing it at two points A (upper right) and B (lower left)"><rect x="0" y="0" width="320" height="300" fill="#ffffff"/><line x1="10" y1="150" x2="310" y2="150" stroke="#334155" stroke-width="1.5"/><line x1="160" y1="290" x2="160" y2="10" stroke="#334155" stroke-width="1.5"/><text x="305" y="166" font-size="12" font-family="sans-serif" fill="#1f2937">x</text><text x="166" y="20" font-size="12" font-family="sans-serif" fill="#1f2937">y</text><text x="270" y="166" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#1f2937">5</text><text x="50" y="166" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#1f2937">−5</text><text x="152" y="44" font-size="11" text-anchor="end" font-family="sans-serif" fill="#1f2937">5</text><text x="152" y="264" font-size="11" text-anchor="end" font-family="sans-serif" fill="#1f2937">−5</text><circle cx="160" cy="150" r="110" fill="none" stroke="#1f2937" stroke-width="2"/><line x1="39" y1="293" x2="303" y2="29" stroke="#2563eb" stroke-width="2"/><circle cx="248" cy="84" r="4" fill="#1f2937"/><circle cx="94" cy="238" r="4" fill="#1f2937"/><text x="256" y="80" font-size="13" font-family="sans-serif" fill="#1f2937">A</text><text x="86" y="254" font-size="13" text-anchor="end" font-family="sans-serif" fill="#1f2937">B</text><text x="272" y="120" font-size="12" font-family="sans-serif" fill="#2563eb">y = x − 1</text></svg>`,
        options: ["(4, −4) and (−3, 3)", "(−4, −5) and (3, 2)", "(4, 3) and (3, 4)", "(4, 3) and (−3, −4)"],
        answerIndex: 3,
        explanation:
          "{{x^2 + (x - 1)^2 = 25}} → {{2x^2 - 2x + 1 = 25}} → {{x^2 - x - 12 = 0}} → {{(x - 4)(x + 3) = 0}}. Then y = x − 1: x = 4 → y = 3; x = −3 → y = −4. So A(4, 3), B(−3, −4) — matching the diagram. (4, −4) and (−3, 3) mix up the pairs. (−4, −5) and (3, 2) come from the sign slip (x + 4)(x − 3). (3, 4) is on the circle but not on the line (4 ≠ 3 − 1).",
        difficulty: "core",
        guideRef: "linear-quadratic-simultaneous",
        hints: [
          "Substitute y = x − 1 into the circle equation.",
          "Expand {{(x - 1)^2}}, simplify, then divide through by 2.",
          "Use the line, not the circle, to find each y — that pairs them correctly.",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m2-q10",
        question: "Solve {{3/(x - 1) - 2/(x + 1) = 1}}.",
        options: ["x = 3 or x = −2", "x = 2 or x = −1", "x = −4", "x = −3 or x = 2"],
        answerIndex: 0,
        explanation:
          "Multiply every term by (x − 1)(x + 1): {{3(x + 1) - 2(x - 1) = x^2 - 1}}, so {{x + 5 = x^2 - 1}} and {{x^2 - x - 6 = (x - 3)(x + 2) = 0}}. x = 3 or −2, neither of which makes a denominator zero. x = 2 or −1 comes from −2(x − 1) = −2x − 2 (should be +2) — and x = −1 isn't even allowed. x = −4 forgets to multiply the 1 on the right. −3 or 2 is a factorising sign slip.",
        difficulty: "core",
        guideRef: "algebraic-fraction-equations",
        hints: [
          "Multiply every term by (x − 1)(x + 1) — including the 1.",
          "Careful: −2(x − 1) = −2x + 2.",
          "Check your answers don't make x − 1 or x + 1 zero.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m2-q11",
        question: "Which statement about {{4x^2 - 12x + 9 = 0}} is true?",
        options: [
          "It has two distinct real roots",
          "It has one repeated real root, x = 1.5",
          "It has no real roots",
          "It has one repeated real root, x = −1.5",
        ],
        answerIndex: 1,
        explanation:
          "{{b^2 - 4ac = 144 - 4 * 4 * 9 = 144 - 144 = 0}}, so there is one repeated root. In fact {{4x^2 - 12x + 9 = (2x - 3)^2}}, so x = 1.5. 'Two distinct roots' would need a positive discriminant. 'No real roots' comes from {{-144 - 144}} (squaring −12 as −144). x = −1.5 is a sign slip: {{x = 12/8}}.",
        difficulty: "core",
        guideRef: "quadratic-formula",
        hints: [
          "Work out {{b^2 - 4ac}} with b = −12.",
          "A zero discriminant means the parabola just touches the x-axis. Where? Try {{x = -b/(2a)}}.",
        ],
        strategy: "Find a pattern",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m2-q12",
        question: "A photo frame measures x cm by (x + 4) cm and has area 96 cm². What is the value of x?",
        options: ["x = 8 or x = −12", "x = 12", "x = 8", "x = −12"],
        answerIndex: 2,
        explanation:
          "{{x(x + 4) = 96}} → {{x^2 + 4x - 96 = 0}} → {{(x + 12)(x - 8) = 0}}. x = −12 is impossible for a length, so x = 8 (frame 8 cm by 12 cm). Giving both roots ignores the context. x = 12 is a sign slip (it is the other side length, not x). −12 is the root you must reject.",
        difficulty: "core",
        guideRef: "solve-by-factorising",
        hints: [
          "Write area = length × width as an equation and make it equal 0.",
          "Find two numbers that multiply to −96 and add to 4.",
          "Can a length be negative?",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m2-q13",
        question: "Arjun solves {{x^2 + 6x + k = 0}} by completing the square and gets {{x = -3 +- sqrt(5)}}. What is the value of k?",
        options: ["k = 4", "k = 14", "k = −4", "k = 5"],
        answerIndex: 0,
        explanation:
          "{{x^2 + 6x + k = (x + 3)^2 - 9 + k}}, so {{(x + 3)^2 = 9 - k}}. The answer {{-3 +- sqrt(5)}} means {{9 - k = 5}}, so k = 4. Check with the product of roots: {{(-3 + sqrt(5))(-3 - sqrt(5)) = 9 - 5 = 4}} ✓. k = 14 uses 9 + 5. k = −4 is a sign slip. k = 5 assumes the number under the root is k.",
        difficulty: "challenge",
        guideRef: "solve-completing-square",
        hints: [
          "Complete the square with k still in it.",
          "You get {{(x + 3)^2 = 9 - k}}. What must 9 − k be to give ±{{sqrt(5)}}?",
          "Check: multiply the two roots together — for {{x^2 + bx + c}} the product of the roots is c.",
        ],
        strategy: "Work backwards",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m2-q14",
        question: "Solve {{x - 6 sqrt(x) + 8 = 0}}.",
        options: ["x = 2 or x = 4", "x = {{sqrt(2)}} or x = 2", "x = 16 or x = 256", "x = 4 or x = 16"],
        answerIndex: 3,
        explanation:
          "Let {{u = sqrt(x)}}, so {{x = u^2}}: {{u^2 - 6u + 8 = (u - 2)(u - 4) = 0}}, giving {{sqrt(x) = 2}} or {{sqrt(x) = 4}}. Square: x = 4 or x = 16. Check: 4 − 6(2) + 8 = 0 ✓, 16 − 6(4) + 8 = 0 ✓. x = 2 or 4 stops at u. {{sqrt(2)}} and 2 square-root instead of squaring. 16 or 256 squares twice.",
        difficulty: "challenge",
        guideRef: "disguised-quadratics",
        hints: [
          "x is the square of {{sqrt(x)}}. What substitution makes this a normal quadratic?",
          "With {{u = sqrt(x)}}: {{u^2 - 6u + 8 = 0}}.",
          "You've found {{sqrt(x)}}, not x. Undo the square root.",
        ],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m2-q15",
        question: "The line {{y = 3 - x}} meets the circle {{x^2 + y^2 = 5}} at the points A and B. Find the exact length of AB.",
        options: ["1", "{{sqrt(2)}}", "{{2 sqrt(5)}}", "2"],
        answerIndex: 1,
        explanation:
          "{{x^2 + (3 - x)^2 = 5}} → {{2x^2 - 6x + 9 = 5}} → {{x^2 - 3x + 2 = 0}} → x = 1 or 2. Using y = 3 − x: A(1, 2), B(2, 1). {{AB = sqrt((2 - 1)^2 + (1 - 2)^2) = sqrt(2)}}. 1 is only the horizontal change. 2 adds the horizontal and vertical changes instead of using Pythagoras. {{2 sqrt(5)}} is the diameter — AB is a chord, not necessarily a diameter.",
        difficulty: "challenge",
        guideRef: "linear-quadratic-simultaneous",
        hints: [
          "First find A and B by substituting the line into the circle.",
          "You should get x = 1 and x = 2. Find each y from the line.",
          "Use Pythagoras for the distance between the two points.",
        ],
        strategy: "Draw a diagram",
      },
    ],
  },
  {
    id: "quadratic-equations-m3",
    title: "MCQ Paper 3 — Exam style",
    questions: [
      {
        kind: "mcq",
        id: "quadratic-equations-m3-q01",
        question: "Solve {{(2x + 1)^2 = 9}}.",
        options: ["x = 1", "x = 4 or x = −5", "x = 1 or x = −2", "x = −1 or x = 2"],
        answerIndex: 2,
        explanation:
          "Square-root both sides: {{2x + 1 = +- 3}}. So 2x = 2 → x = 1, or 2x = −4 → x = −2. x = 1 alone misses the negative root. 4 or −5 uses {{2x + 1 = +- 9}} (no square root taken). −1 or 2 is a sign slip.",
        difficulty: "warmup",
        guideRef: "solve-by-factorising",
        hints: ["Square-root both sides first (±), then solve two linear equations."],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m3-q02",
        question: "The discriminant of {{5x^2 - 2x - 3 = 0}} is 64. What does this tell you about the roots?",
        options: [
          "Two distinct real roots, both rational — so the quadratic factorises",
          "No real roots",
          "One repeated real root",
          "Two distinct real roots, both irrational surds",
        ],
        answerIndex: 0,
        explanation:
          "64 > 0, so there are two distinct real roots, and because 64 is a perfect square, {{sqrt(64) = 8}} and the roots are rational: {{x = (2 +- 8)/10}}, i.e. x = 1 or x = {{-3/5}}. Indeed {{5x^2 - 2x - 3 = (5x + 3)(x - 1)}}. 'No real roots' needs a negative discriminant; 'one repeated root' needs zero. The roots would only be surds if the discriminant were positive but not a perfect square.",
        difficulty: "warmup",
        guideRef: "quadratic-formula",
        hints: ["Is 64 positive, zero or negative? Is it a perfect square?"],
        strategy: "Split into cases",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m3-q03",
        question: "Solve {{x + 8/x = 6}}.",
        options: ["x = 1.6", "x = 1 or x = 8", "x = −2 or x = −4", "x = 2 or x = 4"],
        answerIndex: 3,
        explanation:
          "Multiply every term by x: {{x^2 + 8 = 6x}}, so {{x^2 - 6x + 8 = (x - 2)(x - 4) = 0}} → x = 2 or 4 (x ≠ 0 is fine). Check: 2 + 4 = 6 ✓ and 4 + 2 = 6 ✓. x = 1.6 multiplies only the fraction by x (x + 8 = 6x). 1 and 8 multiply to 8 but add to 9, not 6. −2 or −4 is a sign slip.",
        difficulty: "warmup",
        guideRef: "algebraic-fraction-equations",
        hints: ["Multiply **every** term by x, then rearrange to = 0."],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m3-q04",
        question: "The graphs of {{y = x^2}} and {{y = x + 2}} intersect at two points. What are their x-coordinates?",
        options: ["x = −2 and x = 1", "x = 2 and x = −1", "x = {{sqrt(2)}} and x = {{-sqrt(2)}}", "x = 0 and x = 2"],
        answerIndex: 1,
        explanation:
          "At an intersection both equations hold: {{x^2 = x + 2}}, so {{x^2 - x - 2 = (x - 2)(x + 1) = 0}} → x = 2 or x = −1 (points (2, 4) and (−1, 1)). −2 and 1 is a sign slip. ±{{sqrt(2)}} drops the x term (solving {{x^2 = 2}}). x = 0 and 2 is a guess: at x = 0 the curve is at y = 0 but the line is at y = 2, so they don't meet there.",
        difficulty: "warmup",
        guideRef: "linear-quadratic-simultaneous",
        hints: ["Where graphs meet, their y-values are equal. Set {{x^2 = x + 2}} and solve."],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m3-q05",
        question: "Siti's rectangular herb garden is x m wide and (2x − 3) m long. Its area is 27 m². Work out the perimeter of the garden.",
        diagram: `<svg viewBox="0 0 300 220" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Rectangle, width x metres, length (2x − 3) metres, area 27 square metres"><rect x="0" y="0" width="300" height="220" fill="#ffffff"/><rect x="50" y="45" width="180" height="135" fill="#bbf7d0" stroke="#1f2937" stroke-width="2"/><text x="140" y="35" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">(2x − 3) m</text><text x="238" y="117" font-size="13" font-family="sans-serif" fill="#1f2937">x m</text><text x="140" y="117" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937">27 m²</text></svg>`,
        options: ["10.5 m", "21 m", "4.5 m", "12 m"],
        answerIndex: 1,
        explanation:
          "{{x(2x - 3) = 27}} → {{2x^2 - 3x - 27 = 0}}. ac = −54: −9 and 6 work, so {{2x^2 - 9x + 6x - 27 = x(2x - 9) + 3(2x - 9) = (2x - 9)(x + 3)}}. x = −3 is impossible, so x = 4.5: the garden is 4.5 m by 6 m (4.5 × 6 = 27 ✓) and the perimeter is 2(4.5 + 6) = 21 m. 10.5 m adds only one length and one width. 4.5 m is x. 12 m comes from the sign slip (2x + 9)(x − 3), giving x = 3.",
        difficulty: "core",
        guideRef: "solve-by-factorising",
        hints: [
          "Form the equation from area = width × length and make it = 0.",
          "a ≠ 1: find two numbers that multiply to 2 × (−27) = −54 and add to −3.",
          "Once you have x, find both side lengths — the question asks for the perimeter.",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m3-q06",
        question: "Solve {{3x^2 - 6x - 1 = 0}} by completing the square. Give your answers in the form {{a +- (b sqrt(3))/3}}.",
        options: [
          "x = 1 ± {{sqrt(6)/3}}",
          "x = 3 or x = −1",
          "x = 1 ± {{(2 sqrt(3))/3}}",
          "x = −1 ± {{(2 sqrt(3))/3}}",
        ],
        answerIndex: 2,
        explanation:
          "{{3(x^2 - 2x) - 1 = 3[(x - 1)^2 - 1] - 1 = 3(x - 1)^2 - 4}}. So {{(x - 1)^2 = 4/3}}, {{x - 1 = +- 2/sqrt(3) = +- (2 sqrt(3))/3}}. 1 ± {{sqrt(6)/3}} forgets to multiply the −1 inside the bracket by 3 (getting {{(x - 1)^2 = 2/3}}). x = 3 or −1 forgets to divide the 4 by 3. −1 ± … has the wrong sign inside the bracket.",
        difficulty: "core",
        guideRef: "solve-completing-square",
        hints: [
          "Take 3 out of the first two terms: {{3(x^2 - 2x) - 1}}.",
          "{{x^2 - 2x = (x - 1)^2 - 1}}. Multiply out the 3 carefully.",
          "Rationalise {{2/sqrt(3)}} by multiplying top and bottom by {{sqrt(3)}}.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m3-q07",
        question: "Solve {{x(x + 3) = 7}}. Give your answers correct to 3 significant figures.",
        options: ["x = 1.54 or x = −4.54", "x = 3.08 or x = −9.08", "There are no real solutions", "x = 4.54 or x = −1.54"],
        answerIndex: 0,
        explanation:
          "Expand and rearrange first: {{x^2 + 3x - 7 = 0}}. Then {{x = (-3 +- sqrt(9 + 28))/2 = (-3 +- sqrt(37))/2}} = 1.541… or −4.541… → 1.54 or −4.54. 3.08 and −9.08 forget to divide by 2a = 2. 'No real solutions' uses c = +7 (not rearranging), giving {{9 - 28 < 0}}. 4.54 and −1.54 use +b instead of −b.",
        difficulty: "core",
        guideRef: "quadratic-formula",
        hints: [
          "The formula only works for {{ax^2 + bx + c = 0}}. Get it into that form first.",
          "After rearranging, c = −7, so {{-4ac = +28}}.",
          "Divide the whole numerator by 2a = 2.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m3-q08",
        question: "Solve the simultaneous equations\n\n    {{y = 2x - 3}}\n    {{x^2 + xy = 6}}",
        options: [
          "x = 2, y = −5 and x = −1, y = 1",
          "x = −2, y = −7 and x = 1, y = −1",
          "x = 2, y = 1 only",
          "x = 2, y = 1 and x = −1, y = −5",
        ],
        answerIndex: 3,
        explanation:
          "Substitute: {{x^2 + x(2x - 3) = 6}} → {{3x^2 - 3x - 6 = 0}} → {{x^2 - x - 2 = (x - 2)(x + 1) = 0}}. x = 2 → y = 1; x = −1 → y = −5. Check the second pair: {{(-1)^2 + (-1)(-5) = 1 + 5 = 6}} ✓. Swapping the y-values mispairs the solutions. x = −2 and x = 1 is a factorising sign slip. 'Only' throws away a valid negative solution — there's no context here to reject it.",
        difficulty: "core",
        guideRef: "linear-quadratic-simultaneous",
        hints: [
          "Replace y in the second equation with (2x − 3).",
          "Collect terms to get {{3x^2 - 3x - 6 = 0}}, then divide by 3.",
          "Find each y from the linear equation and keep the pairs together.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m3-q09",
        question: "Solve {{2/(x - 1) + 3/(x + 3) = 1}}. Give your answers correct to 3 significant figures.",
        options: ["x = 4.70 or x = −1.70", "x = −0.4", "x = 4.37 or x = −1.37", "x = −4.37 or x = 1.37"],
        answerIndex: 2,
        explanation:
          "Multiply every term by (x − 1)(x + 3): {{2(x + 3) + 3(x - 1) = (x - 1)(x + 3)}}, so {{5x + 3 = x^2 + 2x - 3}} and {{x^2 - 3x - 6 = 0}}. Formula: {{x = (3 +- sqrt(9 + 24))/2 = (3 +- sqrt(33))/2}} = 4.372… or −1.372… → 4.37 or −1.37 (neither is 1 or −3, so both stand). 4.70 and −1.70 come from 3(x − 1) = 3x − 1. x = −0.4 forgets to multiply the 1 by the denominators. −4.37 and 1.37 use +b instead of −b.",
        difficulty: "core",
        guideRef: "algebraic-fraction-equations",
        hints: [
          "Multiply every term — including the 1 — by (x − 1)(x + 3).",
          "Expand both sides, then collect everything on one side: you should get {{x^2 - 3x - 6 = 0}}.",
          "It won't factorise, so use the formula with a = 1, b = −3, c = −6.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m3-q10",
        question: "Solve {{2^(2x) - 6 * 2^x + 8 = 0}}.",
        options: ["x = 2 or x = 4", "x = 1 or x = 2", "x = 4 or x = 16", "x = −1 or x = −2"],
        answerIndex: 1,
        explanation:
          "{{2^(2x) = (2^x)^2}}, so let {{u = 2^x}}: {{u^2 - 6u + 8 = (u - 2)(u - 4) = 0}}. Then {{2^x = 2}} → x = 1 and {{2^x = 4}} → x = 2. x = 2 or 4 stops at u. 4 or 16 squares u. −1 or −2 is a sign slip — and {{2^x}} can never be negative anyway.",
        difficulty: "core",
        guideRef: "disguised-quadratics",
        hints: [
          "Write {{2^(2x)}} as {{(2^x)^2}}.",
          "Let {{u = 2^x}} and solve {{u^2 - 6u + 8 = 0}}.",
          "You've found {{2^x}}. What power of 2 gives each value?",
        ],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m3-q11",
        question: "Solve {{(x - 3)(x + 2) = 6}}.",
        options: ["x = 9 or x = 4", "x = 3 or x = −2", "x = −4 or x = 3", "x = 4 or x = −3"],
        answerIndex: 3,
        explanation:
          "The 'set each bracket to zero' trick only works when the product is **zero**. Expand: {{x^2 - x - 6 = 6}}, so {{x^2 - x - 12 = (x - 4)(x + 3) = 0}} → x = 4 or −3. Check: (1)(6) = 6 ✓. x = 9 or 4 sets each bracket equal to 6. x = 3 or −2 solves (x − 3)(x + 2) = 0 instead. −4 or 3 is a sign slip.",
        difficulty: "core",
        guideRef: "solve-by-factorising",
        hints: [
          "If two numbers multiply to 6, do they each have to be 6? Why does the 'zero' rule work only for zero?",
          "Expand the left side and subtract 6 so the equation equals 0.",
          "Factorise {{x^2 - x - 12}}.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m3-q12",
        question: "k is a non-zero constant. For which values of k does {{kx^2 + 4x + 1 = 0}} have two distinct real roots?",
        options: ["k < 4", "k > 4", "k < 16", "k < 1"],
        answerIndex: 0,
        explanation:
          "Two distinct real roots need {{b^2 - 4ac > 0}}: {{16 - 4k > 0}}, so k < 4 (with k ≠ 0). Check: k = 3 gives {{16 - 12 = 4 > 0}} ✓; k = 5 gives −4 ✗. k > 4 has the inequality reversed. k < 16 forgets the 4 in 4ac. k < 1 uses b = 4 without squaring it.",
        difficulty: "core",
        guideRef: "quadratic-formula",
        hints: [
          "Which condition on the discriminant gives two distinct real roots?",
          "Here a = k, b = 4, c = 1. Write {{b^2 - 4ac > 0}} and solve for k.",
          "Test a value either side of your critical value to check the direction.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m3-q13",
        question: "How many times does the line {{y = 2x - 1}} meet the curve {{y = x^2 + 2}}?",
        options: ["Once — the line is a tangent", "Twice", "Never", "Twice, at x = 3 and x = −1"],
        answerIndex: 2,
        explanation:
          "Equate: {{x^2 + 2 = 2x - 1}}, so {{x^2 - 2x + 3 = 0}}. Discriminant {{= (-2)^2 - 4 * 1 * 3 = 4 - 12 = -8 < 0}}: no real solutions, so the line never meets the curve (it passes underneath — e.g. at x = 1 the line is at 1, the curve at 3). 'Once' comes from {{x^2 - 2x + 1 = 0}} (moving −1 across without changing sign). 'Twice at 3 and −1' comes from {{x^2 - 2x - 3 = 0}} (sign slip on the constant).",
        difficulty: "challenge",
        guideRef: "linear-quadratic-simultaneous",
        hints: [
          "Set the two expressions for y equal and rearrange to = 0.",
          "You don't need to solve it — what does the discriminant tell you?",
          "Number of intersections = number of real roots.",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m3-q14",
        question: "Find all the real solutions of {{x^4 - 3x^2 - 4 = 0}}.",
        options: ["x = 2 or x = −2", "x = ±2 or x = ±1", "x = 4 or x = −1", "x = 2 only"],
        answerIndex: 0,
        explanation:
          "Let {{u = x^2}}: {{u^2 - 3u - 4 = (u - 4)(u + 1) = 0}}, so {{x^2 = 4}} or {{x^2 = -1}}. A real square can't be −1, so reject it. {{x^2 = 4}} gives x = ±2. ±1 wrongly square-roots −1 as if it were +1. x = 4 or −1 stops at u. x = 2 only forgets the negative root.",
        difficulty: "challenge",
        guideRef: "disguised-quadratics",
        hints: [
          "Substitute {{u = x^2}}.",
          "Solve for u, then ask: which values of u can actually equal {{x^2}}?",
          "Each valid value of {{x^2}} gives two values of x.",
        ],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "quadratic-equations-m3-q15",
        question: "How many **distinct** real solutions does {{(x + 1/x)^2 - 5(x + 1/x) + 6 = 0}} have?",
        options: ["2", "3", "4", "1"],
        answerIndex: 1,
        explanation:
          "Let {{u = x + 1/x}}: {{u^2 - 5u + 6 = 0}} gives u = 2 or u = 3. Now {{x + 1/x = 2}} → {{x^2 - 2x + 1 = 0}} → {{(x - 1)^2 = 0}}, just x = 1 (a repeated root). And {{x + 1/x = 3}} → {{x^2 - 3x + 1 = 0}}, discriminant 5 > 0, giving two roots {{(3 +- sqrt(5))/2}}. Total: 3 distinct solutions. 2 stops at the values of u. 4 assumes each u gives two different x — but u = 2 gives a repeated root. 1 counts only x = 1.",
        difficulty: "challenge",
        guideRef: "disguised-quadratics",
        hints: [
          "The bracket (x + {{1/x}}) appears twice. Call it u.",
          "Solve for u, then turn each value of u back into a quadratic in x (multiply by x).",
          "Use the discriminant of each quadratic in x to count its distinct roots.",
        ],
        strategy: "Introduce a variable",
      },
    ],
  },
];
