// Vectors & Transformations — MCQ papers (3 × 15). Options are shuffled at display time.
// Column vectors are written (x, y) with x on top. Grid diagrams are drawn exactly from the stated coordinates.
import type { Paper } from "../../types.ts";

const D_M1_Q04 = `<svg viewBox="0 0 288 216" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Coordinate grid from x = −4 to 6 and y = −2 to 5. Triangle A has vertices (2, 1), (4, 1) and (2, 4). Triangle B has vertices (0, 1), (−2, 1) and (0, 4)."><rect x="0" y="0" width="288" height="216" fill="#ffffff"/><line x1="24" y1="192" x2="24" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="48" y1="192" x2="48" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="72" y1="192" x2="72" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="96" y1="192" x2="96" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="120" y1="192" x2="120" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="144" y1="192" x2="144" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="168" y1="192" x2="168" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="192" y1="192" x2="192" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="216" y1="192" x2="216" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="240" y1="192" x2="240" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="264" y1="192" x2="264" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="192" x2="264" y2="192" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="168" x2="264" y2="168" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="144" x2="264" y2="144" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="120" x2="264" y2="120" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="96" x2="264" y2="96" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="72" x2="264" y2="72" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="48" x2="264" y2="48" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="24" x2="264" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="144" x2="264" y2="144" stroke="#334155" stroke-width="1.5"/><line x1="120" y1="192" x2="120" y2="24" stroke="#334155" stroke-width="1.5"/><text x="270" y="148" font-size="12" font-style="italic" font-family="sans-serif" fill="#334155">x</text><text x="125" y="16" font-size="12" font-style="italic" font-family="sans-serif" fill="#334155">y</text><text x="24" y="157" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−4</text><text x="48" y="157" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−3</text><text x="72" y="157" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−2</text><text x="96" y="157" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−1</text><text x="144" y="157" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">1</text><text x="168" y="157" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">2</text><text x="192" y="157" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">3</text><text x="216" y="157" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">4</text><text x="240" y="157" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">5</text><text x="264" y="157" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">6</text><text x="116" y="196" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−2</text><text x="116" y="172" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−1</text><text x="116" y="124" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">1</text><text x="116" y="100" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">2</text><text x="116" y="76" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">3</text><text x="116" y="52" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">4</text><text x="116" y="28" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">5</text><text x="116" y="157" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155">0</text><polygon points="168,120 216,120 168,48" fill="#c7d2fe" fill-opacity="0.8" stroke="#1f2937" stroke-width="1.5"/><text x="183.60000000000002" y="101" font-size="14" font-weight="bold" text-anchor="middle" font-family="sans-serif" fill="#1f2937" stroke="#ffffff" stroke-width="3" paint-order="stroke">A</text><polygon points="120,120 72,120 120,48" fill="#fde68a" fill-opacity="0.8" stroke="#1f2937" stroke-width="1.5"/><text x="104.4" y="101" font-size="14" font-weight="bold" text-anchor="middle" font-family="sans-serif" fill="#1f2937" stroke="#ffffff" stroke-width="3" paint-order="stroke">B</text></svg>`;

const D_M1_Q13 = `<svg viewBox="0 0 440 290" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Triangle OAB. Vector OA is a and vector OB is b. P lies on AB, nearer to A, with AP : PB = 2 : 3."><rect x="0" y="0" width="440" height="290" fill="#ffffff"/><line x1="50.0" y1="250.0" x2="170.0" y2="50.0" stroke="#1f2937" stroke-width="1.8"/><polygon points="89.1,184.9 87.2,197.7 78.6,192.6" fill="#1f2937"/><line x1="50.0" y1="250.0" x2="400.0" y2="230.0" stroke="#1f2937" stroke-width="1.8"/><polygon points="161.0,243.7 149.3,249.3 148.7,239.4" fill="#1f2937"/><line x1="170.0" y1="50.0" x2="400.0" y2="230.0" stroke="#1f2937" stroke-width="1.8"/><text x="68.0" y="190.0" font-size="15" font-weight="bold" font-style="italic" text-anchor="middle" font-family="sans-serif" fill="#1d4ed8">a</text><text x="155.0" y="266.0" font-size="15" font-weight="bold" font-style="italic" text-anchor="middle" font-family="sans-serif" fill="#1d4ed8">b</text><circle cx="50.0" cy="250.0" r="3.5" fill="#1f2937"/><text x="42.0" y="266.0" font-size="14" text-anchor="end" font-family="sans-serif" fill="#1f2937">O</text><circle cx="170.0" cy="50.0" r="3.5" fill="#1f2937"/><text x="170.0" y="40.0" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937">A</text><circle cx="400.0" cy="230.0" r="3.5" fill="#1f2937"/><text x="410.0" y="235.0" font-size="14" text-anchor="start" font-family="sans-serif" fill="#1f2937">B</text><circle cx="262.0" cy="122.0" r="3.5" fill="#1f2937"/><text x="270.0" y="114.0" font-size="14" text-anchor="start" font-family="sans-serif" fill="#1f2937">P</text></svg>`;

const D_M2_Q04 = `<svg viewBox="0 0 440 290" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Parallelogram OABC. Vector OA is a and vector OC is c."><rect x="0" y="0" width="440" height="290" fill="#ffffff"/><line x1="50.0" y1="240.0" x2="290.0" y2="240.0" stroke="#1f2937" stroke-width="1.8"/><polygon points="176.0,240.0 164.0,245.0 164.0,235.0" fill="#1f2937"/><line x1="50.0" y1="240.0" x2="140.0" y2="70.0" stroke="#1f2937" stroke-width="1.8"/><polygon points="97.8,149.7 96.6,162.6 87.8,158.0" fill="#1f2937"/><line x1="290.0" y1="240.0" x2="380.0" y2="70.0" stroke="#1f2937" stroke-width="1.8"/><line x1="140.0" y1="70.0" x2="380.0" y2="70.0" stroke="#1f2937" stroke-width="1.8"/><text x="170.0" y="268.0" font-size="15" font-weight="bold" font-style="italic" text-anchor="middle" font-family="sans-serif" fill="#1d4ed8">a</text><text x="80.0" y="150.0" font-size="15" font-weight="bold" font-style="italic" text-anchor="middle" font-family="sans-serif" fill="#1d4ed8">c</text><circle cx="50.0" cy="240.0" r="3.5" fill="#1f2937"/><text x="42.0" y="256.0" font-size="14" text-anchor="end" font-family="sans-serif" fill="#1f2937">O</text><circle cx="290.0" cy="240.0" r="3.5" fill="#1f2937"/><text x="298.0" y="256.0" font-size="14" text-anchor="start" font-family="sans-serif" fill="#1f2937">A</text><circle cx="380.0" cy="70.0" r="3.5" fill="#1f2937"/><text x="388.0" y="64.0" font-size="14" text-anchor="start" font-family="sans-serif" fill="#1f2937">B</text><circle cx="140.0" cy="70.0" r="3.5" fill="#1f2937"/><text x="132.0" y="64.0" font-size="14" text-anchor="end" font-family="sans-serif" fill="#1f2937">C</text></svg>`;

const D_M2_Q06 = `<svg viewBox="0 0 240 168" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Coordinate grid from x = −3 to 5 and y = −1 to 4. Triangle A has vertices (2, 1), (4, 1) and (2, 2). Triangle B has vertices (0, 1), (0, 3) and (−1, 1)."><rect x="0" y="0" width="240" height="168" fill="#ffffff"/><line x1="24" y1="144" x2="24" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="48" y1="144" x2="48" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="72" y1="144" x2="72" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="96" y1="144" x2="96" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="120" y1="144" x2="120" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="144" y1="144" x2="144" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="168" y1="144" x2="168" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="192" y1="144" x2="192" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="216" y1="144" x2="216" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="144" x2="216" y2="144" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="120" x2="216" y2="120" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="96" x2="216" y2="96" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="72" x2="216" y2="72" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="48" x2="216" y2="48" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="24" x2="216" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="120" x2="216" y2="120" stroke="#334155" stroke-width="1.5"/><line x1="96" y1="144" x2="96" y2="24" stroke="#334155" stroke-width="1.5"/><text x="222" y="124" font-size="12" font-style="italic" font-family="sans-serif" fill="#334155">x</text><text x="101" y="16" font-size="12" font-style="italic" font-family="sans-serif" fill="#334155">y</text><text x="24" y="133" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−3</text><text x="48" y="133" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−2</text><text x="72" y="133" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−1</text><text x="120" y="133" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">1</text><text x="144" y="133" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">2</text><text x="168" y="133" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">3</text><text x="192" y="133" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">4</text><text x="216" y="133" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">5</text><text x="92" y="148" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−1</text><text x="92" y="100" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">1</text><text x="92" y="76" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">2</text><text x="92" y="52" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">3</text><text x="92" y="28" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">4</text><text x="92" y="133" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155">0</text><polygon points="144,96 192,96 144,72" fill="#c7d2fe" fill-opacity="0.8" stroke="#1f2937" stroke-width="1.5"/><text x="159.60000000000002" y="93.80000000000001" font-size="14" font-weight="bold" text-anchor="middle" font-family="sans-serif" fill="#1f2937" stroke="#ffffff" stroke-width="3" paint-order="stroke">A</text><polygon points="96,96 96,48 72,96" fill="#fde68a" fill-opacity="0.8" stroke="#1f2937" stroke-width="1.5"/><text x="87.6" y="86.6" font-size="14" font-weight="bold" text-anchor="middle" font-family="sans-serif" fill="#1f2937" stroke="#ffffff" stroke-width="3" paint-order="stroke">B</text></svg>`;

const D_M2_Q12 = `<svg viewBox="0 0 440 290" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Parallelogram OABC. Vector OA is a and vector OC is c. M is the midpoint of BC."><rect x="0" y="0" width="440" height="290" fill="#ffffff"/><line x1="50.0" y1="240.0" x2="290.0" y2="240.0" stroke="#1f2937" stroke-width="1.8"/><polygon points="176.0,240.0 164.0,245.0 164.0,235.0" fill="#1f2937"/><line x1="50.0" y1="240.0" x2="140.0" y2="70.0" stroke="#1f2937" stroke-width="1.8"/><polygon points="97.8,149.7 96.6,162.6 87.8,158.0" fill="#1f2937"/><line x1="290.0" y1="240.0" x2="380.0" y2="70.0" stroke="#1f2937" stroke-width="1.8"/><line x1="140.0" y1="70.0" x2="380.0" y2="70.0" stroke="#1f2937" stroke-width="1.8"/><text x="170.0" y="268.0" font-size="15" font-weight="bold" font-style="italic" text-anchor="middle" font-family="sans-serif" fill="#1d4ed8">a</text><text x="80.0" y="150.0" font-size="15" font-weight="bold" font-style="italic" text-anchor="middle" font-family="sans-serif" fill="#1d4ed8">c</text><circle cx="50.0" cy="240.0" r="3.5" fill="#1f2937"/><text x="42.0" y="256.0" font-size="14" text-anchor="end" font-family="sans-serif" fill="#1f2937">O</text><circle cx="290.0" cy="240.0" r="3.5" fill="#1f2937"/><text x="298.0" y="256.0" font-size="14" text-anchor="start" font-family="sans-serif" fill="#1f2937">A</text><circle cx="380.0" cy="70.0" r="3.5" fill="#1f2937"/><text x="388.0" y="64.0" font-size="14" text-anchor="start" font-family="sans-serif" fill="#1f2937">B</text><circle cx="140.0" cy="70.0" r="3.5" fill="#1f2937"/><text x="132.0" y="64.0" font-size="14" text-anchor="end" font-family="sans-serif" fill="#1f2937">C</text><circle cx="260.0" cy="70.0" r="3.5" fill="#1f2937"/><text x="260.0" y="60.0" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937">M</text></svg>`;

const D_M2_Q15 = `<svg viewBox="0 0 440 290" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Triangle OAB. Vector OA is a and vector OB is b. P lies on OA with OP : PA = 2 : 1. Q is the midpoint of AB. P and Q are joined."><rect x="0" y="0" width="440" height="290" fill="#ffffff"/><line x1="50.0" y1="250.0" x2="170.0" y2="50.0" stroke="#1f2937" stroke-width="1.8"/><polygon points="89.1,184.9 87.2,197.7 78.6,192.6" fill="#1f2937"/><line x1="50.0" y1="250.0" x2="400.0" y2="230.0" stroke="#1f2937" stroke-width="1.8"/><polygon points="161.0,243.7 149.3,249.3 148.7,239.4" fill="#1f2937"/><line x1="170.0" y1="50.0" x2="400.0" y2="230.0" stroke="#1f2937" stroke-width="1.8"/><text x="68.0" y="190.0" font-size="15" font-weight="bold" font-style="italic" text-anchor="middle" font-family="sans-serif" fill="#1d4ed8">a</text><text x="155.0" y="266.0" font-size="15" font-weight="bold" font-style="italic" text-anchor="middle" font-family="sans-serif" fill="#1d4ed8">b</text><circle cx="50.0" cy="250.0" r="3.5" fill="#1f2937"/><text x="42.0" y="266.0" font-size="14" text-anchor="end" font-family="sans-serif" fill="#1f2937">O</text><circle cx="170.0" cy="50.0" r="3.5" fill="#1f2937"/><text x="170.0" y="40.0" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937">A</text><circle cx="400.0" cy="230.0" r="3.5" fill="#1f2937"/><text x="410.0" y="235.0" font-size="14" text-anchor="start" font-family="sans-serif" fill="#1f2937">B</text><line x1="130.0" y1="116.7" x2="285.0" y2="140.0" stroke="#1f2937" stroke-width="1.8" stroke-dasharray="5 4"/><circle cx="130.0" cy="116.7" r="3.5" fill="#1f2937"/><text x="120.0" y="116.7" font-size="14" text-anchor="end" font-family="sans-serif" fill="#1f2937">P</text><circle cx="285.0" cy="140.0" r="3.5" fill="#1f2937"/><text x="293.0" y="132.0" font-size="14" text-anchor="start" font-family="sans-serif" fill="#1f2937">Q</text></svg>`;

const D_M3_Q01 = `<svg viewBox="0 0 216 240" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Coordinate grid from x = −2 to 5 and y = −5 to 3. Triangle A has vertices (1, 1), (3, 1) and (1, 2). Triangle B has vertices (1, −3), (3, −3) and (1, −4)."><rect x="0" y="0" width="216" height="240" fill="#ffffff"/><line x1="24" y1="216" x2="24" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="48" y1="216" x2="48" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="72" y1="216" x2="72" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="96" y1="216" x2="96" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="120" y1="216" x2="120" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="144" y1="216" x2="144" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="168" y1="216" x2="168" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="192" y1="216" x2="192" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="216" x2="192" y2="216" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="192" x2="192" y2="192" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="168" x2="192" y2="168" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="144" x2="192" y2="144" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="120" x2="192" y2="120" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="96" x2="192" y2="96" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="72" x2="192" y2="72" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="48" x2="192" y2="48" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="24" x2="192" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="96" x2="192" y2="96" stroke="#334155" stroke-width="1.5"/><line x1="72" y1="216" x2="72" y2="24" stroke="#334155" stroke-width="1.5"/><text x="198" y="100" font-size="12" font-style="italic" font-family="sans-serif" fill="#334155">x</text><text x="77" y="16" font-size="12" font-style="italic" font-family="sans-serif" fill="#334155">y</text><text x="24" y="109" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−2</text><text x="48" y="109" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−1</text><text x="96" y="109" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">1</text><text x="120" y="109" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">2</text><text x="144" y="109" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">3</text><text x="168" y="109" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">4</text><text x="192" y="109" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">5</text><text x="68" y="220" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−5</text><text x="68" y="196" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−4</text><text x="68" y="172" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−3</text><text x="68" y="148" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−2</text><text x="68" y="124" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−1</text><text x="68" y="76" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">1</text><text x="68" y="52" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">2</text><text x="68" y="28" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">3</text><text x="68" y="109" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155">0</text><polygon points="96,72 144,72 96,48" fill="#c7d2fe" fill-opacity="0.8" stroke="#1f2937" stroke-width="1.5"/><text x="110.4" y="69.8" font-size="14" font-weight="bold" text-anchor="middle" font-family="sans-serif" fill="#1f2937" stroke="#ffffff" stroke-width="3" paint-order="stroke">A</text><polygon points="96,168 144,168 96,192" fill="#fde68a" fill-opacity="0.8" stroke="#1f2937" stroke-width="1.5"/><text x="110.4" y="186.2" font-size="14" font-weight="bold" text-anchor="middle" font-family="sans-serif" fill="#1f2937" stroke="#ffffff" stroke-width="3" paint-order="stroke">B</text></svg>`;

const D_M3_Q04 = `<svg viewBox="0 0 380 290" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Triangle ABC. Vector AB is 2a and vector BC is b."><rect x="0" y="0" width="380" height="290" fill="#ffffff"/><line x1="60.0" y1="240.0" x2="300.0" y2="240.0" stroke="#1f2937" stroke-width="1.8"/><polygon points="186.0,240.0 174.0,245.0 174.0,235.0" fill="#1f2937"/><line x1="300.0" y1="240.0" x2="220.0" y2="60.0" stroke="#1f2937" stroke-width="1.8"/><polygon points="257.6,144.5 267.0,153.5 257.9,157.5" fill="#1f2937"/><line x1="220.0" y1="60.0" x2="60.0" y2="240.0" stroke="#1f2937" stroke-width="1.8"/><text x="180.0" y="268.0" font-size="15" font-weight="bold" font-style="italic" text-anchor="middle" font-family="sans-serif" fill="#1d4ed8">2a</text><text x="280.0" y="145.0" font-size="15" font-weight="bold" font-style="italic" text-anchor="middle" font-family="sans-serif" fill="#1d4ed8">b</text><circle cx="60.0" cy="240.0" r="3.5" fill="#1f2937"/><text x="52.0" y="256.0" font-size="14" text-anchor="end" font-family="sans-serif" fill="#1f2937">A</text><circle cx="300.0" cy="240.0" r="3.5" fill="#1f2937"/><text x="308.0" y="256.0" font-size="14" text-anchor="start" font-family="sans-serif" fill="#1f2937">B</text><circle cx="220.0" cy="60.0" r="3.5" fill="#1f2937"/><text x="220.0" y="50.0" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937">C</text></svg>`;

const D_M3_Q05 = `<svg viewBox="0 0 216 240" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Coordinate grid from x = −1 to 6 and y = −1 to 7. Triangle A has vertices (2, 1), (3, 1) and (2, 3). Triangle B has vertices (3, 2), (5, 2) and (3, 6)."><rect x="0" y="0" width="216" height="240" fill="#ffffff"/><line x1="24" y1="216" x2="24" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="48" y1="216" x2="48" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="72" y1="216" x2="72" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="96" y1="216" x2="96" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="120" y1="216" x2="120" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="144" y1="216" x2="144" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="168" y1="216" x2="168" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="192" y1="216" x2="192" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="216" x2="192" y2="216" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="192" x2="192" y2="192" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="168" x2="192" y2="168" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="144" x2="192" y2="144" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="120" x2="192" y2="120" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="96" x2="192" y2="96" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="72" x2="192" y2="72" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="48" x2="192" y2="48" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="24" x2="192" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="192" x2="192" y2="192" stroke="#334155" stroke-width="1.5"/><line x1="48" y1="216" x2="48" y2="24" stroke="#334155" stroke-width="1.5"/><text x="198" y="196" font-size="12" font-style="italic" font-family="sans-serif" fill="#334155">x</text><text x="53" y="16" font-size="12" font-style="italic" font-family="sans-serif" fill="#334155">y</text><text x="24" y="205" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−1</text><text x="72" y="205" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">1</text><text x="96" y="205" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">2</text><text x="120" y="205" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">3</text><text x="144" y="205" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">4</text><text x="168" y="205" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">5</text><text x="192" y="205" font-size="10" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">6</text><text x="44" y="220" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−1</text><text x="44" y="172" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">1</text><text x="44" y="148" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">2</text><text x="44" y="124" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">3</text><text x="44" y="100" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">4</text><text x="44" y="76" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">5</text><text x="44" y="52" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">6</text><text x="44" y="28" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">7</text><text x="44" y="205" font-size="10" text-anchor="end" font-family="sans-serif" fill="#334155">0</text><polygon points="96,168 120,168 96,120" fill="#c7d2fe" fill-opacity="0.8" stroke="#1f2937" stroke-width="1.5"/><text x="103.19999999999999" y="159.8" font-size="14" font-weight="bold" text-anchor="middle" font-family="sans-serif" fill="#1f2937" stroke="#ffffff" stroke-width="3" paint-order="stroke">A</text><polygon points="120,144 168,144 120,48" fill="#fde68a" fill-opacity="0.8" stroke="#1f2937" stroke-width="1.5"/><text x="134.39999999999998" y="125.0" font-size="14" font-weight="bold" text-anchor="middle" font-family="sans-serif" fill="#1f2937" stroke="#ffffff" stroke-width="3" paint-order="stroke">B</text></svg>`;

const D_M3_Q11 = `<svg viewBox="0 0 440 290" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Triangle OAB. Vector OA is a and vector OB is b. M is the midpoint of OA and N is the midpoint of OB. M and N are joined."><rect x="0" y="0" width="440" height="290" fill="#ffffff"/><line x1="50.0" y1="250.0" x2="170.0" y2="50.0" stroke="#1f2937" stroke-width="1.8"/><polygon points="89.1,184.9 87.2,197.7 78.6,192.6" fill="#1f2937"/><line x1="50.0" y1="250.0" x2="400.0" y2="230.0" stroke="#1f2937" stroke-width="1.8"/><polygon points="161.0,243.7 149.3,249.3 148.7,239.4" fill="#1f2937"/><line x1="170.0" y1="50.0" x2="400.0" y2="230.0" stroke="#1f2937" stroke-width="1.8"/><text x="68.0" y="190.0" font-size="15" font-weight="bold" font-style="italic" text-anchor="middle" font-family="sans-serif" fill="#1d4ed8">a</text><text x="155.0" y="266.0" font-size="15" font-weight="bold" font-style="italic" text-anchor="middle" font-family="sans-serif" fill="#1d4ed8">b</text><circle cx="50.0" cy="250.0" r="3.5" fill="#1f2937"/><text x="42.0" y="266.0" font-size="14" text-anchor="end" font-family="sans-serif" fill="#1f2937">O</text><circle cx="170.0" cy="50.0" r="3.5" fill="#1f2937"/><text x="170.0" y="40.0" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937">A</text><circle cx="400.0" cy="230.0" r="3.5" fill="#1f2937"/><text x="410.0" y="235.0" font-size="14" text-anchor="start" font-family="sans-serif" fill="#1f2937">B</text><line x1="110.0" y1="150.0" x2="225.0" y2="240.0" stroke="#1f2937" stroke-width="1.8" stroke-dasharray="5 4"/><circle cx="110.0" cy="150.0" r="3.5" fill="#1f2937"/><text x="100.0" y="150.0" font-size="14" text-anchor="end" font-family="sans-serif" fill="#1f2937">M</text><circle cx="225.0" cy="240.0" r="3.5" fill="#1f2937"/><text x="225.0" y="260.0" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937">N</text></svg>`;

const D_M3_Q12 = `<svg viewBox="0 0 440 300" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Regular hexagon ABCDEF with centre O. Vector OA is a and vector OB is b."><rect x="0" y="0" width="440" height="300" fill="#ffffff"/><polygon points="330.0,150.0 275.0,54.7 165.0,54.7 110.0,150.0 165.0,245.3 275.0,245.3" fill="#bae6fd" fill-opacity="0.5" stroke="#1f2937" stroke-width="1.8"/><line x1="220.0" y1="150.0" x2="330.0" y2="150.0" stroke="#1f2937" stroke-width="1.8"/><polygon points="281.0,150.0 269.0,155.0 269.0,145.0" fill="#1f2937"/><line x1="220.0" y1="150.0" x2="275.0" y2="54.7" stroke="#1f2937" stroke-width="1.8"/><polygon points="250.5,97.2 248.8,110.1 240.2,105.1" fill="#1f2937"/><text x="275.0" y="168.0" font-size="15" font-weight="bold" font-style="italic" text-anchor="middle" font-family="sans-serif" fill="#1d4ed8">a</text><text x="230.0" y="98.0" font-size="15" font-weight="bold" font-style="italic" text-anchor="middle" font-family="sans-serif" fill="#1d4ed8">b</text><circle cx="330.0" cy="150.0" r="3.5" fill="#1f2937"/><text x="342.0" y="155.0" font-size="14" text-anchor="start" font-family="sans-serif" fill="#1f2937">A</text><circle cx="275.0" cy="54.7" r="3.5" fill="#1f2937"/><text x="283.0" y="46.7" font-size="14" text-anchor="start" font-family="sans-serif" fill="#1f2937">B</text><circle cx="165.0" cy="54.7" r="3.5" fill="#1f2937"/><text x="157.0" y="46.7" font-size="14" text-anchor="end" font-family="sans-serif" fill="#1f2937">C</text><circle cx="110.0" cy="150.0" r="3.5" fill="#1f2937"/><text x="98.0" y="155.0" font-size="14" text-anchor="end" font-family="sans-serif" fill="#1f2937">D</text><circle cx="165.0" cy="245.3" r="3.5" fill="#1f2937"/><text x="157.0" y="263.3" font-size="14" text-anchor="end" font-family="sans-serif" fill="#1f2937">E</text><circle cx="275.0" cy="245.3" r="3.5" fill="#1f2937"/><text x="283.0" y="263.3" font-size="14" text-anchor="start" font-family="sans-serif" fill="#1f2937">F</text><circle cx="220.0" cy="150.0" r="3.5" fill="#1f2937"/><text x="214.0" y="168.0" font-size="14" text-anchor="end" font-family="sans-serif" fill="#1f2937">O</text></svg>`;

const D_M3_Q14 = `<svg viewBox="0 0 440 290" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Parallelogram OABC. Vector OA is a and vector OC is c. M is the midpoint of AB. The line OM is extended to meet the line CB extended at P."><rect x="0" y="0" width="440" height="290" fill="#ffffff"/><line x1="30.0" y1="250.0" x2="190.0" y2="250.0" stroke="#1f2937" stroke-width="1.8"/><polygon points="116.0,250.0 104.0,255.0 104.0,245.0" fill="#1f2937"/><line x1="30.0" y1="250.0" x2="80.0" y2="130.0" stroke="#1f2937" stroke-width="1.8"/><polygon points="57.3,184.5 57.3,197.5 48.1,193.6" fill="#1f2937"/><line x1="190.0" y1="250.0" x2="240.0" y2="130.0" stroke="#1f2937" stroke-width="1.8"/><line x1="80.0" y1="130.0" x2="240.0" y2="130.0" stroke="#1f2937" stroke-width="1.8"/><line x1="240.0" y1="130.0" x2="400.0" y2="130.0" stroke="#1f2937" stroke-width="1.8" stroke-dasharray="5 4"/><line x1="30.0" y1="250.0" x2="215.0" y2="190.0" stroke="#1f2937" stroke-width="1.8"/><line x1="215.0" y1="190.0" x2="400.0" y2="130.0" stroke="#1f2937" stroke-width="1.8" stroke-dasharray="5 4"/><text x="110.0" y="276.0" font-size="15" font-weight="bold" font-style="italic" text-anchor="middle" font-family="sans-serif" fill="#1d4ed8">a</text><text x="44.0" y="185.0" font-size="15" font-weight="bold" font-style="italic" text-anchor="middle" font-family="sans-serif" fill="#1d4ed8">c</text><circle cx="30.0" cy="250.0" r="3.5" fill="#1f2937"/><text x="22.0" y="266.0" font-size="14" text-anchor="end" font-family="sans-serif" fill="#1f2937">O</text><circle cx="190.0" cy="250.0" r="3.5" fill="#1f2937"/><text x="198.0" y="266.0" font-size="14" text-anchor="start" font-family="sans-serif" fill="#1f2937">A</text><circle cx="240.0" cy="130.0" r="3.5" fill="#1f2937"/><text x="238.0" y="120.0" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937">B</text><circle cx="80.0" cy="130.0" r="3.5" fill="#1f2937"/><text x="72.0" y="124.0" font-size="14" text-anchor="end" font-family="sans-serif" fill="#1f2937">C</text><circle cx="215.0" cy="190.0" r="3.5" fill="#1f2937"/><text x="225.0" y="200.0" font-size="14" text-anchor="start" font-family="sans-serif" fill="#1f2937">M</text><circle cx="400.0" cy="130.0" r="3.5" fill="#1f2937"/><text x="408.0" y="122.0" font-size="14" text-anchor="start" font-family="sans-serif" fill="#1f2937">P</text></svg>`;

const D_M3_Q15 = `<svg viewBox="0 0 440 290" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Triangle OAB. Vector OA is a and vector OB is b. M is the midpoint of OB and N is the midpoint of OA. Lines AM and BN cross at G."><rect x="0" y="0" width="440" height="290" fill="#ffffff"/><line x1="50.0" y1="250.0" x2="170.0" y2="50.0" stroke="#1f2937" stroke-width="1.8"/><polygon points="89.1,184.9 87.2,197.7 78.6,192.6" fill="#1f2937"/><line x1="50.0" y1="250.0" x2="400.0" y2="230.0" stroke="#1f2937" stroke-width="1.8"/><polygon points="161.0,243.7 149.3,249.3 148.7,239.4" fill="#1f2937"/><line x1="170.0" y1="50.0" x2="400.0" y2="230.0" stroke="#1f2937" stroke-width="1.8"/><text x="68.0" y="190.0" font-size="15" font-weight="bold" font-style="italic" text-anchor="middle" font-family="sans-serif" fill="#1d4ed8">a</text><text x="155.0" y="266.0" font-size="15" font-weight="bold" font-style="italic" text-anchor="middle" font-family="sans-serif" fill="#1d4ed8">b</text><circle cx="50.0" cy="250.0" r="3.5" fill="#1f2937"/><text x="42.0" y="266.0" font-size="14" text-anchor="end" font-family="sans-serif" fill="#1f2937">O</text><circle cx="170.0" cy="50.0" r="3.5" fill="#1f2937"/><text x="170.0" y="40.0" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937">A</text><circle cx="400.0" cy="230.0" r="3.5" fill="#1f2937"/><text x="410.0" y="235.0" font-size="14" text-anchor="start" font-family="sans-serif" fill="#1f2937">B</text><line x1="170.0" y1="50.0" x2="225.0" y2="240.0" stroke="#1f2937" stroke-width="1.8" stroke-dasharray="5 4"/><line x1="400.0" y1="230.0" x2="110.0" y2="150.0" stroke="#1f2937" stroke-width="1.8" stroke-dasharray="5 4"/><circle cx="225.0" cy="240.0" r="3.5" fill="#1f2937"/><text x="225.0" y="260.0" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937">M</text><circle cx="110.0" cy="150.0" r="3.5" fill="#1f2937"/><text x="100.0" y="150.0" font-size="14" text-anchor="end" font-family="sans-serif" fill="#1f2937">N</text><circle cx="206.7" cy="176.7" r="3.5" fill="#1f2937"/><text x="210.7" y="166.7" font-size="14" text-anchor="start" font-family="sans-serif" fill="#1f2937">G</text></svg>`;

export const mcqPapers: Paper[] = [
  {
    id: "vectors-transformations-m1",
    title: "MCQ Paper 1",
    questions: [
      {
        kind: "mcq",
        id: "vectors-transformations-m1-q01",
        question: "The point P(2, −1) is translated by the column vector (−3, 4) — that is, −3 in x and 4 in y. What are the coordinates of the image of P?",
        options: [
          "(5, −5)",
          "(−6, −4)",
          "(−1, 3)",
          "(1, 3)",
        ],
        answerIndex: 2,
        explanation: "A translation **adds** the vector to the coordinates: (2 + (−3), −1 + 4) = (−1, 3). (5, −5) subtracts the vector instead of adding it; (−6, −4) multiplies the coordinates by the components; (1, 3) slips on 2 − 3, getting +1.",
        difficulty: "warmup",
        guideRef: "transformations",
        hints: [
          "Top number = move in x (negative means left), bottom number = move in y. Add each one to the matching coordinate.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m1-q02",
        question: "Given the column vectors **a** = (3, −2) and **b** = (−1, 5), work out 2**a** − **b**.",
        options: [
          "(7, −9)",
          "(5, 1)",
          "(5, −9)",
          "(4, −7)",
        ],
        answerIndex: 0,
        explanation: "2**a** = (6, −4). Then 2**a** − **b** = (6 − (−1), −4 − 5) = (7, −9). (5, 1) is 2**a** + **b**; (5, −9) treats 6 − (−1) as 6 − 1; (4, −7) is **a** − **b**, forgetting to double **a**.",
        difficulty: "warmup",
        guideRef: "vector-basics",
        hints: [
          "Double each component of **a** first, then subtract **b** component by component — watch the double negative in the top row.",
        ],
        strategy: "Work component by component",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m1-q03",
        question: "Work out the magnitude of the vector (−5, 12).",
        options: [
          "7",
          "17",
          "{{sqrt(119)}}",
          "13",
        ],
        answerIndex: 3,
        explanation: "The magnitude is the length of the arrow, found by Pythagoras: {{sqrt((-5)^2 + 12^2) = sqrt(25 + 144) = sqrt(169) = 13}}. 7 just adds −5 + 12; 17 adds the sizes 5 + 12; {{sqrt(119)}} comes from {{12^2 - 5^2}} — a negative component still gives a positive square.",
        difficulty: "warmup",
        guideRef: "vector-basics",
        hints: [
          "Draw the vector as the hypotenuse of a right-angled triangle with sides 5 and 12.",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m1-q04",
        question: "Describe fully the single transformation that maps triangle A onto triangle B.",
        diagram: D_M1_Q04,
        options: [
          "Reflection in the line {{y = 1}}",
          "Reflection in the line {{x = 1}}",
          "Reflection in the y-axis",
          "Translation by the vector (−4, 0)",
        ],
        answerIndex: 1,
        explanation: "B is a mirror image of A (it is flipped), and each vertex is the same distance either side of the vertical line through x = 1: (2, 1) ↔ (0, 1), (4, 1) ↔ (−2, 1). So it is a reflection in {{x = 1}}. The line {{y = 1}} is horizontal — a classic mix-up, since vertical lines are x = …. The y-axis (x = 0) would send (2, 4) to (−2, 4), but the matching vertex of B is (0, 4). A translation never flips a shape, and (−4, 0) would move (2, 4) to (−2, 4), not (0, 4).",
        difficulty: "warmup",
        guideRef: "transformations",
        hints: [
          "Is B flipped or just slid? A flipped shape points the other way.",
          "Find the point halfway between a vertex of A and its matching vertex in B. Vertical lines have equations x = ….",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m1-q05",
        question: "The point (3, 1) is rotated 90° **clockwise** about the origin. What are the coordinates of its image?",
        options: [
          "(−1, 3)",
          "(1, −3)",
          "(−3, −1)",
          "(3, −1)",
        ],
        answerIndex: 1,
        explanation: "A quarter turn clockwise about O sends (x, y) to (y, −x): (3, 1) → (1, −3). Check with tracing paper: a point in the first quadrant turns clockwise into the fourth quadrant. (−1, 3) is the **anticlockwise** rotation; (−3, −1) is a half turn (180°); (3, −1) is a reflection in the x-axis.",
        difficulty: "core",
        guideRef: "transformations",
        hints: [
          "Which quadrant does a point in the top-right end up in after a quarter turn clockwise?",
          "Sketch the line from O to (3, 1), then turn it 90° clockwise — the 'across 3, up 1' becomes 'across 1, down 3'.",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m1-q06",
        question: "The point P(3, 2) is enlarged by scale factor −2 with centre (1, 1). What are the coordinates of the image of P?",
        options: [
          "(5, 3)",
          "(−6, −4)",
          "(−1, 0)",
          "(−3, −1)",
        ],
        answerIndex: 3,
        explanation: "Vector from the centre to P: (3 − 1, 2 − 1) = (2, 1). Multiply by −2: (−4, −2). Add to the centre: (1 − 4, 1 − 2) = (−3, −1). (5, 3) uses scale factor +2 (image on the same side as P); (−6, −4) multiplies P's coordinates by −2, which only works when the centre is the origin; (−1, 0) uses scale factor −1.",
        difficulty: "core",
        guideRef: "transformations",
        hints: [
          "Always work from the centre of enlargement, not the origin.",
          "Find the vector from (1, 1) to P, multiply it by −2, then add it back on to (1, 1).",
          "A negative scale factor puts the image on the **opposite** side of the centre.",
        ],
        strategy: "Work from the centre",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m1-q07",
        question: "A shape has area 36 cm². It is enlarged by scale factor {{-1/2}}. What is the area of the image?",
        options: [
          "9 cm²",
          "18 cm²",
          "−9 cm²",
          "4.5 cm²",
        ],
        answerIndex: 0,
        explanation: "Lengths are multiplied by {{1/2}} (the minus sign only turns the image upside down through the centre), so areas are multiplied by {{(1/2)^2 = 1/4}}: 36 × {{1/4}} = 9 cm². 18 cm² multiplies the area by the length factor; −9 cm² keeps the minus sign, but an area cannot be negative; 4.5 cm² uses the volume factor {{(1/2)^3}}.",
        difficulty: "core",
        guideRef: "transformations",
        hints: [
          "What does the negative sign do to the image — does it change the size?",
          "Area scale factor = (length scale factor)².",
        ],
        strategy: "Use scale factors for length, area and volume",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m1-q08",
        question: "A shape is reflected in the x-axis and then the image is reflected in the y-axis. Which **single** transformation has the same effect?",
        options: [
          "Reflection in the line {{y = x}}",
          "Rotation 90° clockwise about (0, 0)",
          "Rotation 180° about (0, 0)",
          "Reflection in the line {{y = -x}}",
        ],
        answerIndex: 2,
        explanation: "Track a point: (x, y) → (x, −y) → (−x, −y). That is a half turn about the origin. Two reflections never give a reflection — the second flip undoes the first, so the shape ends up the right way round, which rules out both reflections in y = x and y = −x. A 90° rotation would send (1, 0) to (0, −1), but the pair of reflections sends it to (−1, 0).",
        difficulty: "core",
        guideRef: "combined-transformations",
        hints: [
          "Pick a simple point such as (2, 1) and follow it through both reflections.",
          "Where does (x, y) end up? Which transformation sends (x, y) to (−x, −y)?",
          "Two flips put the shape back the right way round — so the answer cannot be a reflection.",
        ],
        strategy: "Try a specific case",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m1-q09",
        question: "A transformation consists of a reflection in the x-axis followed by a translation by the vector (4, 0). Which statement about invariant points is true?",
        options: [
          "(2, 0) is the only invariant point",
          "(4, 0) is the only invariant point",
          "Every point on the x-axis is invariant",
          "No point is invariant",
        ],
        answerIndex: 3,
        explanation: "Follow (x, y): reflect → (x, −y), translate → (x + 4, −y). For a point to stay put we need x + 4 = x, which is impossible. So nothing is fixed — the translation moves every point, including those on the mirror line. 'Every point on the x-axis' would be true for the reflection alone. (2, 0) and (4, 0) both still move 4 to the right.",
        difficulty: "core",
        guideRef: "combined-transformations",
        hints: [
          "An invariant point ends exactly where it started. Write the image of (x, y) after both steps.",
          "Set the image equal to (x, y). Can the x-coordinates ever match?",
        ],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m1-q10",
        question: "A is the point (2, −1) and B is the point (7, 3). Which column vector is →AB?",
        options: [
          "(−5, −4)",
          "(5, 4)",
          "(9, 2)",
          "(4.5, 1)",
        ],
        answerIndex: 1,
        explanation: "→AB = →OB − →OA (end minus start) = (7 − 2, 3 − (−1)) = (5, 4). (−5, −4) is →BA (start minus end); (9, 2) adds the position vectors; (4.5, 1) is the midpoint of AB, a point, not a journey.",
        difficulty: "core",
        guideRef: "vector-basics",
        hints: [
          "→AB is the journey **from** A **to** B.",
          "Journey = end position − start position. Be careful with 3 − (−1).",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m1-q11",
        question: "The vector (k, 3) is parallel to the vector (8, 12). What is the value of k?",
        options: [
          "−1",
          "32",
          "2",
          "4.5",
        ],
        answerIndex: 2,
        explanation: "Parallel vectors are scalar multiples of each other. (8, 12) = 4 × (2, 3), so (k, 3) must be (2, 3): k = 2. −1 comes from adding/subtracting (12 − 3 = 9, so 8 − 9) — parallel means multiply, not add. 32 uses the multiplier upside down (8 × 4 instead of 8 ÷ 4). 4.5 sets {{k/3 = 12/8}}, mixing up which components pair up.",
        difficulty: "core",
        guideRef: "vector-basics",
        hints: [
          "Parallel vectors: one is a number times the other.",
          "What do you multiply 3 by to get 12? Use the same multiplier on the top row.",
        ],
        strategy: "Use the scalar multiple",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m1-q12",
        question: "In triangle OAB, →OA = **a** and →OB = **b**. M is the midpoint of AB. Find →OM in terms of **a** and **b**.",
        options: [
          "{{1/2}}(**a** + **b**)",
          "{{1/2}}(**b** − **a**)",
          "**a** + **b**",
          "{{1/2}}**a** + **b**",
        ],
        answerIndex: 0,
        explanation: "→AB = −**a** + **b** = **b** − **a**. Then →OM = →OA + {{1/2}}→AB = **a** + {{1/2}}(**b** − **a**) = {{1/2}}**a** + {{1/2}}**b** = {{1/2}}(**a** + **b**). {{1/2}}(**b** − **a**) is →AM — it stops halfway without starting from O. **a** + **b** would be the fourth corner of a parallelogram, not a midpoint.",
        difficulty: "core",
        guideRef: "vector-geometry",
        hints: [
          "Find a route from O to M that only uses known vectors: O → A → M.",
          "First write →AB in terms of **a** and **b**. Then →AM is half of it.",
          "→OM = **a** + {{1/2}}(**b** − **a**). Simplify.",
        ],
        strategy: "Find a route",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m1-q13",
        question: "In triangle OAB, →OA = **a** and →OB = **b**. The point P lies on AB such that AP : PB = 2 : 3. Find →OP in terms of **a** and **b**.",
        diagram: D_M1_Q13,
        options: [
          "{{3/5}}**a** + {{2/5}}**b**",
          "{{2/5}}**a** + {{3/5}}**b**",
          "{{1/3}}**a** + {{2/3}}**b**",
          "{{7/5}}**a** − {{2/5}}**b**",
        ],
        answerIndex: 0,
        explanation: "AP is 2 parts out of 2 + 3 = 5, so →AP = {{2/5}}→AB = {{2/5}}(**b** − **a**). Then →OP = **a** + {{2/5}}(**b** − **a**) = {{3/5}}**a** + {{2/5}}**b**. Sense check: P is nearer A, so the coefficient of **a** should be bigger. {{2/5}}**a** + {{3/5}}**b** swaps the weights (P nearer B); {{1/3}}**a** + {{2/3}}**b** reads 2 : 3 as {{2/3}}; {{7/5}}**a** − {{2/5}}**b** uses →AB = **a** − **b**, the wrong way round.",
        difficulty: "challenge",
        guideRef: "vector-geometry",
        hints: [
          "How many equal parts is AB split into? What fraction of AB is AP?",
          "→AB = **b** − **a** (end minus start).",
          "→OP = **a** + {{2/5}}(**b** − **a**). Collect the **a** terms.",
        ],
        strategy: "Find a route",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m1-q14",
        question: "Shape S is rotated 90° clockwise about (0, 0), and then the image is reflected in the x-axis. Which single transformation maps S to the final image?",
        options: [
          "Reflection in the line {{y = -x}}",
          "Rotation 90° anticlockwise about (0, 0)",
          "Reflection in the line {{y = x}}",
          "Reflection in the y-axis",
        ],
        answerIndex: 2,
        explanation: "Track (x, y): rotate 90° clockwise → (y, −x); reflect in the x-axis → (y, x). Swapping the coordinates is reflection in {{y = x}}. Reflection in {{y = -x}} is what you get if you do the two steps in the **other order** — order matters. A rotation followed by a reflection is a single reflection (one flip in total), so a rotation cannot be the answer.",
        difficulty: "challenge",
        guideRef: "combined-transformations",
        hints: [
          "Follow a general point (x, y), or a test point like (3, 1), through each step in the given order.",
          "A 90° clockwise turn about O sends (x, y) to (y, −x).",
          "Which reflection swaps the x- and y-coordinates?",
        ],
        strategy: "Try a specific case",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m1-q15",
        question: "O is the origin, →OA = **a** and →OB = **b**. The point C has →OC = 3**b** − 2**a**. Which statement is true?",
        options: [
          "A, B and C lie on a straight line and AB : BC = 1 : 3",
          "A, B and C lie on a straight line and AB : BC = 1 : 2",
          "AC is parallel to AB, but A, B and C are not on a straight line",
          "A, B and C are not on a straight line, because →OC is not a multiple of **a** + **b**",
        ],
        answerIndex: 1,
        explanation: "→AB = **b** − **a**. →AC = →OC − →OA = 3**b** − 2**a** − **a** = 3**b** − 3**a** = 3(**b** − **a**) = 3→AB. So AC is parallel to AB **and** they share the point A, so A, B, C are collinear, with AC three times AB: AB : BC = 1 : 2. '1 : 3' confuses AB : AC with AB : BC. Parallel lines through a common point cannot be separate lines, so the 'not on a straight line' option is impossible. Comparing →OC with **a** + **b** tests nothing useful.",
        difficulty: "challenge",
        guideRef: "vector-geometry",
        hints: [
          "To test collinearity, compare two vectors that share a point, such as →AB and →AC.",
          "→AC = →OC − →OA. Factorise it.",
          "If →AC = k→AB, the lines are parallel AND share A. What does that tell you?",
        ],
        strategy: "Look for a scalar multiple",
      },
    ],
  },
  {
    id: "vectors-transformations-m2",
    title: "MCQ Paper 2",
    questions: [
      {
        kind: "mcq",
        id: "vectors-transformations-m2-q01",
        question: "The point (5, −2) is reflected in the line {{y = x}}. What are the coordinates of its image?",
        options: [
          "(5, 2)",
          "(−5, 2)",
          "(2, −5)",
          "(−2, 5)",
        ],
        answerIndex: 3,
        explanation: "Reflection in {{y = x}} swaps the coordinates: (x, y) → (y, x), so (5, −2) → (−2, 5). (5, 2) is a reflection in the x-axis; (−5, 2) is a rotation of 180° about O; (2, −5) is a reflection in {{y = -x}}, which swaps **and** changes both signs.",
        difficulty: "warmup",
        guideRef: "transformations",
        hints: [
          "Points on y = x have equal coordinates. What does reflecting in it do to x and y?",
        ],
        strategy: "Try a specific case",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m2-q02",
        question: "Which of these vectors is parallel to (2, −3)?",
        options: [
          "(3, −2)",
          "(−4, 6)",
          "(4, 6)",
          "(−2, −3)",
        ],
        answerIndex: 1,
        explanation: "(−4, 6) = −2 × (2, −3), a scalar multiple, so it is parallel (pointing the opposite way). (3, −2) swaps the components; (4, 6) and (−2, −3) only change one sign, so they are not multiples of (2, −3).",
        difficulty: "warmup",
        guideRef: "vector-basics",
        hints: [
          "Parallel vectors are scalar multiples: find a single number k with k × (2, −3) equal to the option.",
        ],
        strategy: "Use the scalar multiple",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m2-q03",
        question: "A translation maps the point A(1, −2) onto A′(−3, 1). Which column vector describes the translation?",
        options: [
          "(−4, 3)",
          "(4, −3)",
          "(−3, 1)",
          "(−2, −1)",
        ],
        answerIndex: 0,
        explanation: "Vector = image − object = (−3 − 1, 1 − (−2)) = (−4, 3): 4 left and 3 up. (4, −3) is the reverse journey, A′ back to A; (−3, 1) is just the coordinates of the image; (−2, −1) adds the two points.",
        difficulty: "warmup",
        guideRef: "transformations",
        hints: [
          "How far left or right, and how far up or down, do you go from A to A′? Image minus object.",
        ],
        strategy: "Work backwards",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m2-q04",
        question: "OABC is a parallelogram. →OA = **a** and →OC = **c**. Find →CA.",
        diagram: D_M2_Q04,
        options: [
          "**c** − **a**",
          "**a** + **c**",
          "**a** − **c**",
          "−**a** − **c**",
        ],
        answerIndex: 2,
        explanation: "Go from C to A via O: →CA = →CO + →OA = −**c** + **a** = **a** − **c**. **c** − **a** is →AC, the reverse direction; **a** + **c** is →OB, the other diagonal; −**a** − **c** is →BO.",
        difficulty: "warmup",
        guideRef: "vector-geometry",
        hints: [
          "Find a route from C to A using only known vectors. Going against an arrow makes it negative.",
        ],
        strategy: "Find a route",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m2-q05",
        question: "The point (5, 6) is enlarged by scale factor {{1/2}} with centre (−1, 2). What are the coordinates of the image?",
        options: [
          "(2.5, 3)",
          "(11, 10)",
          "(2, 4)",
          "(−4, 0)",
        ],
        answerIndex: 2,
        explanation: "Centre to point: (5 − (−1), 6 − 2) = (6, 4). Halve it: (3, 2). Add to the centre: (−1 + 3, 2 + 2) = (2, 4). (2.5, 3) halves the coordinates, as if the centre were the origin; (11, 10) uses scale factor 2 ('a half' does not mean doubling); (−4, 0) uses scale factor {{-1/2}}.",
        difficulty: "core",
        guideRef: "transformations",
        hints: [
          "A fractional scale factor brings the point **closer** to the centre.",
          "Find the vector from the centre to the point, halve it, and add it to the centre.",
        ],
        strategy: "Work from the centre",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m2-q06",
        question: "Describe fully the single transformation that maps triangle A onto triangle B.",
        diagram: D_M2_Q06,
        options: [
          "Rotation 90° clockwise about (1, 0)",
          "Rotation 90° anticlockwise about (0, 0)",
          "Reflection in the line {{x = 1}}",
          "Rotation 90° anticlockwise about (1, 0)",
        ],
        answerIndex: 3,
        explanation: "The long horizontal side of A (along y = 1) has become a vertical side in B, so it is a quarter turn. Check centre (1, 0): (2, 1) is 1 right and 1 up from it; turning that 90° anticlockwise gives 1 left and 1 up, i.e. (0, 1) ✓. (4, 1) → (0, 3) ✓ and (2, 2) → (−1, 1) ✓. Clockwise about (1, 0) would send (4, 1) to (2, −3). About (0, 0) it would send (2, 1) to (−1, 2). A reflection in x = 1 would keep the long side horizontal.",
        difficulty: "core",
        guideRef: "transformations",
        hints: [
          "Has the shape turned or flipped? Look at what happened to the long side.",
          "For a rotation you need three things: angle, direction and centre.",
          "Test a centre: does the vector from it to each vertex of A turn through 90° to reach the matching vertex of B?",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m2-q07",
        question: "Triangle T is enlarged by scale factor −3 to give triangle T′. Which statement is true?",
        options: [
          "T′ is one third of the size of T",
          "T′ is 3 times as long as T, on the opposite side of the centre and upside down",
          "T′ is 3 times as long as T, on the same side of the centre and the same way up",
          "T′ has 3 times the area of T",
        ],
        answerIndex: 1,
        explanation: "The size of the scale factor (3) multiplies every length by 3. The minus sign sends each point through the centre to the other side, which turns the image upside down (like a 180° rotation). One third would need a scale factor of ±{{1/3}}; 'same side' describes +3; the area is multiplied by {{3^2 = 9}}, not 3.",
        difficulty: "core",
        guideRef: "transformations",
        hints: [
          "Split the scale factor into its size and its sign. What does each part do?",
          "Area scale factor = (length scale factor)².",
        ],
        strategy: "Split into cases",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m2-q08",
        question: "The point (2, 5) is reflected in the y-axis. The image is then translated by the vector (3, −1). What are the coordinates of the final image?",
        options: [
          "(1, 4)",
          "(−5, 4)",
          "(5, −6)",
          "(−1, 6)",
        ],
        answerIndex: 0,
        explanation: "Reflect in the y-axis: (2, 5) → (−2, 5). Translate: (−2 + 3, 5 − 1) = (1, 4). (−5, 4) does the steps in the wrong order (translate first, then reflect); (5, −6) reflects in the x-axis instead; (−1, 6) subtracts the translation vector.",
        difficulty: "core",
        guideRef: "combined-transformations",
        hints: [
          "Do the transformations in the order given.",
          "Reflection in the y-axis changes the sign of the x-coordinate only.",
        ],
        strategy: "Do one step at a time",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m2-q09",
        question: "Which of these transformations has a whole **line** of invariant points?",
        options: [
          "Rotation 90° clockwise about (0, 0)",
          "Reflection in the line {{y = -x}}",
          "Enlargement, scale factor 2, centre (1, 1)",
          "Translation by the vector (3, 3)",
        ],
        answerIndex: 1,
        explanation: "Every point on a mirror line stays where it is, so a reflection fixes a whole line — here every point (t, −t). A rotation fixes only its centre; an enlargement (scale factor ≠ 1) fixes only its centre; a translation fixes nothing at all.",
        difficulty: "core",
        guideRef: "combined-transformations",
        hints: [
          "An invariant point is one that does not move. Which points stay put under each transformation?",
          "Think about where the 'pivot' of each transformation is — a point, a line or nowhere.",
        ],
        strategy: "Consider each case",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m2-q10",
        question: "**p** = (1, 3) and **q** = (−2, −1). Find the magnitude of 2**p** − **q**. Give your answer as a surd.",
        options: [
          "{{sqrt(65)}}",
          "5",
          "11",
          "7",
        ],
        answerIndex: 0,
        explanation: "2**p** − **q** = (2 − (−2), 6 − (−1)) = (4, 7). Magnitude = {{sqrt(4^2 + 7^2) = sqrt(16 + 49) = sqrt(65)}}. 5 is the length of 2**p** + **q** = (0, 5); 11 adds the components 4 + 7 instead of using Pythagoras; 7 comes from (0, 7), slipping on 2 − (−2).",
        difficulty: "core",
        guideRef: "vector-basics",
        hints: [
          "Find the vector first, then its length.",
          "Subtracting a negative: 2 − (−2) = 4 and 6 − (−1) = 7.",
          "Length of (x, y) = {{sqrt(x^2 + y^2)}}.",
        ],
        strategy: "Do one step at a time",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m2-q11",
        question: "O is the origin. →OA = (3, 1) and →AB = (−5, 4). What are the coordinates of B?",
        options: [
          "(−8, 3)",
          "(8, −3)",
          "(−5, 4)",
          "(−2, 5)",
        ],
        answerIndex: 3,
        explanation: "→OB = →OA + →AB = (3 + (−5), 1 + 4) = (−2, 5), and the position vector of B gives its coordinates. (−8, 3) is →AB − →OA; (8, −3) is →OA − →AB; (−5, 4) treats the journey A → B as if it started at O.",
        difficulty: "core",
        guideRef: "vector-basics",
        hints: [
          "Get from O to B by going O → A → B.",
          "Add the two vectors; the position vector →OB gives the coordinates of B.",
        ],
        strategy: "Find a route",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m2-q12",
        question: "OABC is a parallelogram. →OA = **a** and →OC = **c**. M is the midpoint of BC. Find →OM.",
        diagram: D_M2_Q12,
        options: [
          "**a** + {{1/2}}**c**",
          "{{1/2}}(**a** + **c**)",
          "**c** + {{1/2}}**a**",
          "**c** − {{1/2}}**a**",
        ],
        answerIndex: 2,
        explanation: "Route O → C → M. →CB is parallel and equal to →OA, so →CB = **a** and →CM = {{1/2}}**a**. →OM = **c** + {{1/2}}**a**. **a** + {{1/2}}**c** is the midpoint of AB; {{1/2}}(**a** + **c**) is the centre of the parallelogram; **c** − {{1/2}}**a** goes along CB the wrong way.",
        difficulty: "core",
        guideRef: "vector-geometry",
        hints: [
          "Opposite sides of a parallelogram are equal vectors. What is →CB?",
          "Route O → C → M: →OC + {{1/2}}→CB.",
        ],
        strategy: "Find a route",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m2-q13",
        question: "→PQ = 2**a** − 6**b** and →RS = k**a** + 9**b**, where **a** and **b** are not parallel. PQ is parallel to RS. Find k.",
        options: [
          "−3",
          "3",
          "17",
          "{{-4/3}}",
        ],
        answerIndex: 0,
        explanation: "Parallel means →RS = λ→PQ for some number λ. Matching the **b** terms: 9 = −6λ, so λ = {{-3/2}}. Then k = 2λ = −3. Check: {{-3/2}}(2**a** − 6**b**) = −3**a** + 9**b** ✓. 3 ignores the sign change; 17 uses adding (−6 + 15 = 9, so 2 + 15) instead of multiplying; {{-4/3}} uses the multiplier upside down.",
        difficulty: "challenge",
        guideRef: "vector-basics",
        hints: [
          "Parallel vectors are scalar multiples: →RS = λ→PQ.",
          "Both coefficients are known for **b**. What must λ be?",
          "Use the same λ on the **a** coefficient.",
        ],
        strategy: "Use the scalar multiple",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m2-q14",
        question: "A shape is enlarged by scale factor 2, centre (0, 0). The image is then enlarged by scale factor {{1/2}}, centre (4, 0). Which single transformation maps the original shape to the final image?",
        options: [
          "No change: every point maps to itself, because 2 × {{1/2}} = 1",
          "Translation by the vector (4, 0)",
          "Translation by the vector (−2, 0)",
          "Translation by the vector (2, 0)",
        ],
        answerIndex: 3,
        explanation: "Follow (x, y): first → (2x, 2y). Then the vector from (4, 0) is (2x − 4, 2y); halve it → (x − 2, y); add to (4, 0) → (x + 2, y). Every point moves 2 to the right: a translation by (2, 0). The scale factors do multiply to 1, so the shape is the same size — but the different centres mean it has moved. Test with the origin: (0, 0) → (0, 0) → (2, 0).",
        difficulty: "challenge",
        guideRef: "combined-transformations",
        hints: [
          "The combined scale factor is 1, so the size is unchanged. But does the shape stay in the same place?",
          "Follow the origin (0, 0) through both enlargements.",
          "Then follow a general point (x, y) to see whether every point moves the same way.",
        ],
        strategy: "Try a specific case",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m2-q15",
        question: "In triangle OAB, →OA = **a** and →OB = **b**. P lies on OA with OP : PA = 2 : 1, and Q is the midpoint of AB. Find →PQ.",
        diagram: D_M2_Q15,
        options: [
          "{{1/6}}**a** − {{1/2}}**b**",
          "{{1/6}}**a** + {{1/2}}**b**",
          "{{1/2}}**b** − {{1/6}}**a**",
          "{{1/2}}**b** − {{2/3}}**a**",
        ],
        answerIndex: 2,
        explanation: "→OP = {{2/3}}**a** and →OQ = **a** + {{1/2}}(**b** − **a**) = {{1/2}}**a** + {{1/2}}**b**. →PQ = →OQ − →OP = {{1/2}}**a** + {{1/2}}**b** − {{2/3}}**a** = {{1/2}}**b** − {{1/6}}**a**. {{1/6}}**a** − {{1/2}}**b** is →QP (wrong way round); {{1/6}}**a** + {{1/2}}**b** places P only {{1/3}} of the way along OA; {{1/2}}**b** − {{2/3}}**a** takes →OQ as just {{1/2}}**b**.",
        difficulty: "challenge",
        guideRef: "vector-geometry",
        hints: [
          "Write the position vectors →OP and →OQ first.",
          "OP is 2 parts out of 3, so →OP = {{2/3}}**a**. Q is the midpoint of AB, so →OQ = **a** + {{1/2}}→AB.",
          "→PQ = →OQ − →OP (end minus start).",
        ],
        strategy: "Use position vectors",
      },
    ],
  },
  {
    id: "vectors-transformations-m3",
    title: "MCQ Paper 3 — Exam style",
    questions: [
      {
        kind: "mcq",
        id: "vectors-transformations-m3-q01",
        question: "Describe fully the single transformation that maps triangle A onto triangle B.",
        diagram: D_M3_Q01,
        options: [
          "Reflection in the line {{x = -1}}",
          "Reflection in the line {{y = -1}}",
          "Reflection in the x-axis",
          "Rotation 180° about (2, −1)",
        ],
        answerIndex: 1,
        explanation: "B is a flipped copy of A, and each vertex of B is the same distance below y = −1 as its partner in A is above it: (1, 1) ↔ (1, −3), both 2 from y = −1. So it is a reflection in {{y = -1}}. x = −1 is a vertical line; the x-axis would send (1, 1) to (1, −1); a 180° rotation about (2, −1) would send (1, 1) to (3, −3), putting the right angle on the wrong side.",
        difficulty: "warmup",
        guideRef: "transformations",
        hints: [
          "Find the line exactly halfway between matching vertices, e.g. (1, 1) and (1, −3). Horizontal lines are y = ….",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m3-q02",
        question: "(2, y) + (x, −5) = (−1, 3), where each bracket is a column vector. Find x and y.",
        options: [
          "x = 1, y = −2",
          "x = −3, y = −2",
          "x = −3, y = 8",
          "x = 1, y = 8",
        ],
        answerIndex: 2,
        explanation: "Top row: 2 + x = −1, so x = −3. Bottom row: y − 5 = 3, so y = 8. 'x = 1, y = −2' just adds the numbers you can see instead of solving; the mixed options get one row right.",
        difficulty: "warmup",
        guideRef: "vector-basics",
        hints: [
          "Write one equation for the top row and one for the bottom row, then solve each.",
        ],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m3-q03",
        question: "The point (4, −3) is rotated 180° about the origin. What are the coordinates of its image?",
        options: [
          "(−4, −3)",
          "(4, 3)",
          "(3, 4)",
          "(−4, 3)",
        ],
        answerIndex: 3,
        explanation: "A half turn about O sends (x, y) to (−x, −y), so (4, −3) → (−4, 3). (−4, −3) is a reflection in the y-axis; (4, 3) is a reflection in the x-axis; (3, 4) is a 90° anticlockwise rotation.",
        difficulty: "warmup",
        guideRef: "transformations",
        hints: [
          "A half turn about the origin sends a point to the diagonally opposite quadrant — both signs change.",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m3-q04",
        question: "In triangle ABC, →AB = 2**a** and →BC = **b**. Find →CA.",
        diagram: D_M3_Q04,
        options: [
          "−2**a** − **b**",
          "2**a** + **b**",
          "**b** − 2**a**",
          "2**a** − **b**",
        ],
        answerIndex: 0,
        explanation: "Going round the triangle A → B → C → A gets you back where you started, so →AB + →BC + →CA = **0**. Hence →CA = −(2**a** + **b**) = −2**a** − **b**. 2**a** + **b** is →AC (wrong direction); the other two each reverse only one of the vectors.",
        difficulty: "warmup",
        guideRef: "vector-geometry",
        hints: [
          "Route from C to A: go C → B → A, reversing each arrow you travel against.",
        ],
        strategy: "Find a route",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m3-q05",
        question: "Triangle B is an enlargement of triangle A. What are the coordinates of the centre of enlargement?",
        diagram: D_M3_Q05,
        options: [
          "(0, 0)",
          "(1, 0)",
          "(2, 1)",
          "(3, 2)",
        ],
        answerIndex: 1,
        explanation: "Draw lines through matching vertices: (2, 1) → (3, 2), (3, 1) → (5, 2) and (2, 3) → (3, 6). Extended backwards, all three meet at (1, 0). Check: the vector from (1, 0) to (2, 1) is (1, 1); doubled it is (2, 2), giving (3, 2) ✓ — scale factor 2. The origin is a guess that only works when lines pass through it; (2, 1) and (3, 2) are vertices, not the centre.",
        difficulty: "core",
        guideRef: "transformations",
        hints: [
          "Join each vertex of A to the matching vertex of B with a straight line, and extend the lines.",
          "Where do all three lines meet?",
          "Check: is each vertex of B twice as far from your centre as the matching vertex of A?",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m3-q06",
        question: "An enlargement with centre (0, 0) maps the point (6, −4) onto the point (−3, 2). What is the scale factor?",
        options: [
          "{{1/2}}",
          "−2",
          "{{-1/2}}",
          "2",
        ],
        answerIndex: 2,
        explanation: "With centre O, image = k × object: (−3, 2) = k(6, −4) gives k = {{-1/2}}. The image is smaller (half the distance from O) and on the opposite side of the centre. {{1/2}} ignores the change of side; −2 and 2 divide the wrong way round (object ÷ image).",
        difficulty: "core",
        guideRef: "transformations",
        hints: [
          "Is the image nearer to or further from the centre? Is it on the same side?",
          "Scale factor = image distance ÷ object distance, with a minus sign if it crosses the centre.",
        ],
        strategy: "Work backwards",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m3-q07",
        question: "A shape is reflected in the line {{x = 1}}, and then the image is reflected in the line {{x = 4}}. Which single transformation has the same effect?",
        options: [
          "Translation by the vector (6, 0)",
          "Translation by the vector (3, 0)",
          "Reflection in the line {{x = 2.5}}",
          "Translation by the vector (−6, 0)",
        ],
        answerIndex: 0,
        explanation: "Track a point, e.g. (1, 0): it is on the first mirror so stays at (1, 0), then reflects in x = 4 to (7, 0) — a shift of 6. In general (x, y) → (2 − x, y) → (8 − (2 − x), y) = (x + 6, y). Two reflections in parallel mirrors give a translation of **twice** the gap between them, in the direction from the first mirror to the second. (3, 0) is just the gap; (−6, 0) is the reverse order; two flips cannot make a single reflection.",
        difficulty: "core",
        guideRef: "combined-transformations",
        hints: [
          "Pick a test point, e.g. (0, 0), and reflect it twice.",
          "Reflection in x = a sends x to 2a − x.",
          "Compare the gap between the mirrors with the distance moved.",
        ],
        strategy: "Try a specific case",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m3-q08",
        question: "Shape A is mapped onto shape B by a rotation of 90° clockwise about (1, 2). Which transformation maps B back onto A?",
        options: [
          "Rotation 90° clockwise about (1, 2)",
          "Rotation 90° anticlockwise about (−1, −2)",
          "Rotation 270° anticlockwise about (1, 2)",
          "Rotation 90° anticlockwise about (1, 2)",
        ],
        answerIndex: 3,
        explanation: "To undo a turn you turn back the same amount, the other way, about the same centre: 90° anticlockwise about (1, 2). Turning 90° clockwise again would make a half turn. The centre does not change sign when you reverse the turn. 270° anticlockwise is the same as 90° clockwise, so it goes the wrong way too.",
        difficulty: "core",
        guideRef: "combined-transformations",
        hints: [
          "What undoes a quarter turn clockwise?",
          "Does the centre of rotation move when you undo the turn?",
        ],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m3-q09",
        question: "A drone flies the displacement (12, −5) metres and then the displacement (−3, 17) metres. How far is it from its starting point at the end?",
        options: [
          "30.3 m",
          "21 m",
          "26.6 m",
          "15 m",
        ],
        answerIndex: 3,
        explanation: "Resultant displacement = (12 + (−3), −5 + 17) = (9, 12). Distance = {{sqrt(9^2 + 12^2) = sqrt(225) = 15}} m. 30.3 m adds the lengths of the two legs (13 + 17.3) — that is distance flown, not distance from the start; 21 m adds 9 + 12; 26.6 m uses (15, 22), adding the sizes of the components and ignoring the signs.",
        difficulty: "core",
        guideRef: "vector-basics",
        hints: [
          "Add the two displacement vectors first.",
          "Then find the length of the resultant with Pythagoras.",
        ],
        strategy: "Do one step at a time",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m3-q10",
        question: "A is the point (−1, 4) and B is the point (5, −2). M is the midpoint of AB. Which column vector is →OM?",
        options: [
          "(3, −3)",
          "(2, 1)",
          "(6, −6)",
          "(4, 2)",
        ],
        answerIndex: 1,
        explanation: "→OM = {{1/2}}(→OA + →OB) = {{1/2}}(4, 2) = (2, 1). Or →OM = →OA + {{1/2}}→AB = (−1, 4) + (3, −3) = (2, 1). (3, −3) is →AM, half of AB without starting from A; (6, −6) is →AB; (4, 2) is the sum of the position vectors before halving.",
        difficulty: "core",
        guideRef: "vector-basics",
        hints: [
          "The position vector of a midpoint is the average of the two position vectors.",
          "Add (−1, 4) and (5, −2), then halve.",
        ],
        strategy: "Use position vectors",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m3-q11",
        question: "In triangle OAB, →OA = **a** and →OB = **b**. M is the midpoint of OA and N is the midpoint of OB. Which statement is correct?",
        diagram: D_M3_Q11,
        options: [
          "→MN = {{1/2}}(**b** − **a**), so MN is parallel to AB and half its length",
          "→MN = {{1/2}}(**a** − **b**), so MN is parallel to AB and half its length",
          "→MN = {{1/2}}(**b** − **a**), so MN is perpendicular to AB",
          "→MN = **b** − **a**, so MN is equal in length to AB",
        ],
        answerIndex: 0,
        explanation: "→MN = →MO + →ON = −{{1/2}}**a** + {{1/2}}**b** = {{1/2}}(**b** − **a**) = {{1/2}}→AB. A scalar multiple means parallel, and the factor {{1/2}} gives half the length. {{1/2}}(**a** − **b**) is →NM, the reverse direction. Vectors that are multiples of each other are parallel, never perpendicular. **b** − **a** forgets that M and N are only halfway along.",
        difficulty: "core",
        guideRef: "vector-geometry",
        hints: [
          "Write →MN as a route: M → O → N.",
          "→MO = −{{1/2}}**a** and →ON = {{1/2}}**b**.",
          "Compare your answer with →AB = **b** − **a**.",
        ],
        strategy: "Find a route",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m3-q12",
        question: "ABCDEF is a regular hexagon with centre O. →OA = **a** and →OB = **b**. Find →AC.",
        diagram: D_M3_Q12,
        options: [
          "**b** − **a**",
          "**a** + **b**",
          "**b** − 2**a**",
          "2**a** − **b**",
        ],
        answerIndex: 2,
        explanation: "The hexagon is made of six equilateral triangles, so OABC is a rhombus and →OC = →AB = **b** − **a**. Then →AC = →AO + →OC = −**a** + **b** − **a** = **b** − 2**a**. **b** − **a** is →AB (or →OC), one side, not the diagonal; **a** + **b** points out between A and B, away from C; 2**a** − **b** is →CA.",
        difficulty: "core",
        guideRef: "vector-geometry",
        hints: [
          "Look for parallel sides: which side of the hexagon is parallel to OC?",
          "→OC = →AB = **b** − **a**, because OABC is a rhombus.",
          "Route A → O → C.",
        ],
        strategy: "Find a route",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m3-q13",
        question: "An enlargement with scale factor −2 maps the point P(1, 3) onto P′(7, −3). What are the coordinates of the centre of enlargement?",
        options: [
          "(4, 0)",
          "(3, 1)",
          "(−5, 9)",
          "(5, −1)",
        ],
        answerIndex: 1,
        explanation: "Let the centre be C(c, d). Then →CP′ = −2 →CP: 7 − c = −2(1 − c) gives c = 3, and −3 − d = −2(3 − d) gives d = 1. So C is (3, 1). Check: →CP = (−2, 2), × −2 = (4, −4), and (3, 1) + (4, −4) = (7, −3) ✓. Equivalently, C divides PP′ in the ratio 1 : 2. (4, 0) is the midpoint (scale factor −1); (−5, 9) solves with scale factor +2; (5, −1) divides PP′ in 2 : 1, the wrong way round.",
        difficulty: "challenge",
        guideRef: "transformations",
        hints: [
          "The centre lies on the line through P and P′, between them (negative scale factor).",
          "P′ is twice as far from the centre as P is. So how does the centre split PP′?",
          "Or let the centre be (c, d) and use: image − centre = −2 × (object − centre).",
        ],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m3-q14",
        question: "OABC is a parallelogram with →OA = **a** and →OC = **c**. M is the midpoint of AB. The line OM is extended to meet the line CB extended at P. Find →OP.",
        diagram: D_M3_Q14,
        options: [
          "**a** + {{1/2}}**c**",
          "2**a** + 2**c**",
          "**a** + **c**",
          "2**a** + **c**",
        ],
        answerIndex: 3,
        explanation: "P is on line OM, so →OP = λ→OM = λ(**a** + {{1/2}}**c**). P is also on line CB, so →OP = **c** + μ**a**. Compare **c** terms: {{1/2}}λ = 1, so λ = 2 and →OP = 2**a** + **c** (μ = 2, so BP = CB). **a** + {{1/2}}**c** is →OM itself, which stops at M; **a** + **c** is →OB; 2**a** + 2**c** doubles everything and isn't on line CB.",
        difficulty: "challenge",
        guideRef: "vector-geometry",
        hints: [
          "P lies on two lines. Write →OP in two ways, each with an unknown scalar.",
          "On line OM: →OP = λ(**a** + {{1/2}}**c**). On line CB: →OP = **c** + μ**a**.",
          "**a** and **c** aren't parallel, so the **c** coefficients must match.",
        ],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "vectors-transformations-m3-q15",
        question: "In triangle OAB, →OA = **a** and →OB = **b**. M is the midpoint of OB and N is the midpoint of OA. The lines AM and BN cross at G. Find →OG.",
        diagram: D_M3_Q15,
        options: [
          "{{1/3}}(**a** + **b**)",
          "{{1/2}}(**a** + **b**)",
          "{{1/4}}(**a** + **b**)",
          "{{2/3}}(**a** + **b**)",
        ],
        answerIndex: 0,
        explanation: "On AM: →OG = **a** + λ({{1/2}}**b** − **a**) = (1 − λ)**a** + {{1/2}}λ**b**. On BN: →OG = **b** + μ({{1/2}}**a** − **b**) = {{1/2}}μ**a** + (1 − μ)**b**. Matching: 1 − λ = {{1/2}}μ and {{1/2}}λ = 1 − μ. Solving gives λ = μ = {{2/3}}, so →OG = {{1/3}}**a** + {{1/3}}**b**. (G is the centroid: two thirds of the way along each median.) {{1/2}}(**a** + **b**) is the midpoint of AB; {{2/3}}(**a** + **b**) reverses the 2 : 1 ratio; {{1/4}}(**a** + **b**) is a guess from 'midpoint of a midpoint'.",
        difficulty: "challenge",
        guideRef: "vector-geometry",
        hints: [
          "Use symmetry: the set-up is the same if you swap **a** and **b**, so →OG = t(**a** + **b**) for some t.",
          "Write →OG as a route along AM: **a** + λ→AM, with →AM = {{1/2}}**b** − **a**.",
          "Match coefficients of **a** and **b** with t(**a** + **b**).",
        ],
        strategy: "Use symmetry",
      },
    ],
  },
];
