// Indices, Standard Form & Surds — MCQ papers (3 × 15). Options are shuffled at display time.
import type { Paper } from "../../types.ts";

export const mcqPapers: Paper[] = [
  // =========================================================================
  // MCQ Paper 1
  // =========================================================================
  {
    id: "indices-surds-m1",
    title: "MCQ Paper 1",
    questions: [
      {
        kind: "mcq",
        id: "indices-surds-m1-q01",
        question: "Simplify {{3a^4 * 5a^2}}.",
        options: ["{{15a^6}}", "{{8a^6}}", "{{15a^8}}", "{{8a^8}}"],
        answerIndex: 0,
        explanation:
          "Multiply the numbers and **add** the indices: {{3 * 5 = 15}} and {{a^4 * a^2 = a^(4+2) = a^6}}, giving {{15a^6}}. {{8a^6}} adds the coefficients instead of multiplying them; {{15a^8}} multiplies the indices (that is the rule for a power of a power, not a product).",
        difficulty: "warmup",
        guideRef: "index-laws",
        hints: ["Deal with the numbers and the powers of {{a}} separately — what happens to indices when you multiply the same base?"],
        strategy: "Split into parts",
      },
      {
        kind: "mcq",
        id: "indices-surds-m1-q02",
        question: "Work out the value of {{5^(-2)}}.",
        options: ["−25", "{{1/25}}", "−10", "{{1/10}}"],
        answerIndex: 1,
        explanation:
          "A negative index means *reciprocal*: {{5^(-2) = 1/5^2 = 1/25}}. −25 is the classic slip of thinking a negative power makes the answer negative; −10 and {{1/10}} come from multiplying 5 × 2 instead of squaring.",
        difficulty: "warmup",
        guideRef: "negative-fractional-indices",
        hints: ["A negative index never makes the number negative — it flips it. What is {{5^2}}?"],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "indices-surds-m1-q03",
        question: "Write 0.000 47 in standard form.",
        options: ["{{4.7 * 10^(-5)}}", "{{47 * 10^(-5)}}", "{{4.7 * 10^(-4)}}", "{{4.7 * 10^4}}"],
        answerIndex: 2,
        explanation:
          "The digits move 4 places to the left to make 4.7, so 0.000 47 = {{4.7 * 10^(-4)}}. {{4.7 * 10^(-5)}} miscounts the jumps — 5 places would give 47, not 4.7; {{47 * 10^(-5)}} has the right value but 47 is not between 1 and 10; {{10^4}} would make a large number.",
        difficulty: "warmup",
        guideRef: "standard-form",
        hints: ["How many places must the decimal point move to turn 0.000 47 into 4.7? Small number ⇒ negative power."],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "indices-surds-m1-q04",
        question: "Simplify {{sqrt(50)}}.",
        options: ["{{25 sqrt(2)}}", "{{2 sqrt(5)}}", "{{10 sqrt(5)}}", "{{5 sqrt(2)}}"],
        answerIndex: 3,
        explanation:
          "Split off the largest square factor: {{sqrt(50) = sqrt(25 * 2) = sqrt(25) * sqrt(2) = 5 sqrt(2)}}. {{25 sqrt(2)}} forgets to square-root the 25; {{2 sqrt(5)}} swaps which number is the square; {{10 sqrt(5)}} uses 50 = 10 × 5, but 10 is not a square number.",
        difficulty: "warmup",
        guideRef: "simplifying-surds",
        hints: ["Which square number (4, 9, 16, 25, …) is a factor of 50?"],
        strategy: "Find the largest square factor",
      },
      {
        kind: "mcq",
        id: "indices-surds-m1-q05",
        question: "Simplify fully {{(3x^2 y)^3 / (9xy)}}.",
        options: ["{{x^5 y^2}}", "{{3x^5 y^2}}", "{{3x^4 y^2}}", "{{27x^5 y^2}}"],
        answerIndex: 1,
        explanation:
          "Cube **everything** in the bracket: {{(3x^2 y)^3 = 27x^6 y^3}}. Then divide: {{27/9 = 3}}, {{x^6 / x = x^5}}, {{y^3 / y = y^2}}, so the answer is {{3x^5 y^2}}. {{x^5 y^2}} comes from cubing 3 to get 9; {{3x^4 y^2}} treats {{(x^2)^3}} as {{x^5}} (adding instead of multiplying); {{27x^5 y^2}} forgets to divide 27 by 9.",
        difficulty: "core",
        guideRef: "index-laws",
        hints: [
          "Start with the bracket — the power 3 applies to the 3, the {{x^2}} and the {{y}}.",
          "{{(x^2)^3}}: power of a power means multiply the indices.",
          "Now divide numbers by numbers, {{x}}'s by {{x}}'s and {{y}}'s by {{y}}'s.",
        ],
        strategy: "Split into parts",
      },
      {
        kind: "mcq",
        id: "indices-surds-m1-q06",
        question: "Without a calculator, work out the value of {{(8/27)^(-2/3)}}.",
        options: ["{{4/9}}", "{{3/2}}", "{{9/4}}", "{{-4/9}}"],
        answerIndex: 2,
        explanation:
          "Deal with the three parts of the index one at a time. Minus ⇒ flip: {{(27/8)^(2/3)}}. Denominator 3 ⇒ cube root: {{3/2}}. Numerator 2 ⇒ square: {{9/4}}. {{4/9}} ignores the minus sign; {{-4/9}} wrongly makes the answer negative; {{3/2}} stops after the cube root and forgets to square.",
        difficulty: "core",
        guideRef: "negative-fractional-indices",
        hints: [
          "There are three instructions hidden in {{-2/3}}. What does each part tell you to do?",
          "The minus sign means take the reciprocal: {{(27/8)^(2/3)}}.",
          "Cube root first ({{cbrt(27) = 3}}, {{cbrt(8) = 2}}), then square.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "indices-surds-m1-q07",
        question: "Work out {{(6 * 10^5) * (4 * 10^(-8))}}. Give your answer in standard form.",
        options: ["{{2.4 * 10^(-2)}}", "{{24 * 10^(-3)}}", "{{2.4 * 10^(-4)}}", "{{2.4 * 10^(-40)}}"],
        answerIndex: 0,
        explanation:
          "Multiply the numbers and add the powers: {{6 * 4 = 24}} and {{10^(5 + (-8)) = 10^(-3)}}, so {{24 * 10^(-3)}}. That is not standard form, so write {{24 = 2.4 * 10^1}}: {{2.4 * 10^(-2)}}. {{24 * 10^(-3)}} is the right value in the wrong form; {{2.4 * 10^(-4)}} adjusts the power the wrong way; {{10^(-40)}} multiplies the indices.",
        difficulty: "core",
        guideRef: "standard-form",
        hints: [
          "Group the ordinary numbers together and the powers of 10 together.",
          "{{6 * 4 = 24}} — is 24 allowed at the front of a standard-form number?",
          "Making the front number 10 times smaller means the power must go up by 1.",
        ],
        strategy: "Split into parts",
      },
      {
        kind: "mcq",
        id: "indices-surds-m1-q08",
        question: "Solve {{27^x = 1/9}}.",
        options: ["{{-3/2}}", "{{2/3}}", "−2", "{{-2/3}}"],
        answerIndex: 3,
        explanation:
          "Write both sides as powers of 3: {{27^x = 3^(3x)}} and {{1/9 = 3^(-2)}}. So {{3x = -2}} and {{x = -2/3}}. {{-3/2}} divides the wrong way round; {{2/3}} loses the minus from the reciprocal; −2 forgets that 27 is {{3^3}}, so the left side is {{3^(3x)}}, not {{3^x}}.",
        difficulty: "core",
        guideRef: "index-equations",
        hints: [
          "27 and 9 are both powers of the same prime. Which one?",
          "{{27 = 3^3}} and {{1/9 = 3^(-2)}}.",
          "Once the bases match, set the indices equal: {{3x = -2}}.",
        ],
        strategy: "Write with the same base",
      },
      {
        kind: "mcq",
        id: "indices-surds-m1-q09",
        question: "Simplify {{sqrt(72) + sqrt(18)}}.",
        options: ["{{sqrt(90)}}", "{{18 sqrt(2)}}", "{{9 sqrt(2)}}", "{{9 sqrt(4)}}"],
        answerIndex: 2,
        explanation:
          "Simplify each surd first: {{sqrt(72) = 6 sqrt(2)}} and {{sqrt(18) = 3 sqrt(2)}}. They are *like surds*, so collect them: {{6 sqrt(2) + 3 sqrt(2) = 9 sqrt(2)}}. {{sqrt(90)}} adds the numbers under the roots — but {{sqrt(a) + sqrt(b) != sqrt(a + b)}}; {{18 sqrt(2)}} multiplies 6 × 3; {{9 sqrt(4)}} adds the {{sqrt(2)}}'s as if {{sqrt(2) + sqrt(2) = sqrt(4)}}.",
        difficulty: "core",
        guideRef: "simplifying-surds",
        hints: [
          "You can only collect surds once they have the same number under the root.",
          "Find the largest square factor of 72, then of 18.",
          "{{sqrt(72) = sqrt(36) sqrt(2)}} and {{sqrt(18) = sqrt(9) sqrt(2)}}.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "indices-surds-m1-q10",
        question: "Expand and simplify {{(3 + sqrt(5))(2 - sqrt(5))}}.",
        options: ["{{1 - sqrt(5)}}", "{{11 - sqrt(5)}}", "{{1 + sqrt(5)}}", "{{-19 - sqrt(5)}}"],
        answerIndex: 0,
        explanation:
          "Four products: {{3 * 2 = 6}}, {{3 * (-sqrt(5)) = -3 sqrt(5)}}, {{sqrt(5) * 2 = 2 sqrt(5)}}, {{sqrt(5) * (-sqrt(5)) = -5}}. Total: {{6 - 5 - 3 sqrt(5) + 2 sqrt(5) = 1 - sqrt(5)}}. {{11 - sqrt(5)}} loses the minus on the last product; {{1 + sqrt(5)}} gets the sign of the surd terms wrong; {{-19 - sqrt(5)}} thinks {{sqrt(5) * sqrt(5) = 25}}.",
        difficulty: "core",
        guideRef: "surd-brackets",
        hints: [
          "Expand exactly like {{(3 + x)(2 - x)}} — four products.",
          "What is {{sqrt(5) * sqrt(5)}}? Watch the sign in front of it.",
          "Collect the whole numbers and the {{sqrt(5)}} terms separately.",
        ],
        strategy: "Grid method",
      },
      {
        kind: "mcq",
        id: "indices-surds-m1-q11",
        question: "Rationalise the denominator and simplify {{12/sqrt(3)}}.",
        options: ["{{12 sqrt(3)}}", "{{4 sqrt(3)}}", "4", "{{sqrt(3)/4}}"],
        answerIndex: 1,
        explanation:
          "Multiply top and bottom by {{sqrt(3)}}: {{(12 sqrt(3))/3 = 4 sqrt(3)}}. {{12 sqrt(3)}} multiplies the top but forgets the denominator became 3; 4 drops the root altogether; {{sqrt(3)/4}} is the reciprocal of the answer.",
        difficulty: "core",
        guideRef: "rationalising",
        hints: [
          "What can you multiply {{sqrt(3)}} by to get a whole number?",
          "Multiply the top **and** bottom by {{sqrt(3)}} — that is multiplying by 1.",
          "Then cancel {{12/3}}.",
        ],
        strategy: "Multiply by a clever form of 1",
      },
      {
        kind: "mcq",
        id: "indices-surds-m1-q12",
        question: "Solve {{x^(3/2) = 27}}.",
        options: ["18", "40.5", "140.3 (to 1 d.p.)", "9"],
        answerIndex: 3,
        explanation:
          "Undo the power {{3/2}} by raising both sides to its reciprocal, {{2/3}}: {{x = 27^(2/3) = (cbrt(27))^2 = 3^2 = 9}}. Check: {{9^(3/2) = (sqrt(9))^3 = 27}}. 18 multiplies 27 by {{2/3}}; 40.5 multiplies by {{3/2}} — powers are not undone by multiplying; 140.3 is {{27^(3/2)}}, applying the same power again instead of its inverse.",
        difficulty: "core",
        guideRef: "harder-index-equations",
        hints: [
          "What power undoes 'to the power {{3/2}}'? Think about {{(x^a)^b = x^(ab)}}.",
          "Raise both sides to the power {{2/3}}.",
          "{{27^(2/3)}}: cube root first, then square.",
        ],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "indices-surds-m1-q13",
        question: "Solve {{x - 5 sqrt(x) + 6 = 0}}.",
        options: ["{{x = 2}} or {{x = 3}}", "{{x = sqrt(2)}} or {{x = sqrt(3)}}", "{{x = 4}} or {{x = 9}}", "{{x = -2}} or {{x = -3}}"],
        answerIndex: 2,
        explanation:
          "It is a disguised quadratic: let {{y = sqrt(x)}}, so {{x = y^2}} and {{y^2 - 5y + 6 = 0}}. Then {{(y - 2)(y - 3) = 0}}, so {{sqrt(x) = 2}} or {{3}}, giving {{x = 4}} or {{x = 9}}. Check: {{4 - 10 + 6 = 0}} ✓. {{x = 2}} or {{3}} stops at {{sqrt(x)}}; {{sqrt(2)}}, {{sqrt(3)}} square-roots instead of squaring; −2, −3 is a sign slip in the factorising (and {{sqrt(x)}} can't be negative anyway).",
        difficulty: "challenge",
        guideRef: "harder-index-equations",
        hints: [
          "{{x}} is the square of {{sqrt(x)}}. Can you see a quadratic hiding here?",
          "Let {{y = sqrt(x)}}. Rewrite the equation in {{y}}.",
          "Solve {{y^2 - 5y + 6 = 0}}, then remember you found {{sqrt(x)}}, not {{x}}.",
        ],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "indices-surds-m1-q14",
        question: "Write {{(2 + sqrt(3))/(2 - sqrt(3))}} in the form {{a + b sqrt(3)}}.",
        options: ["{{7 + 4 sqrt(3)}}", "7", "{{7 + 2 sqrt(3)}}", "{{(7 + 4 sqrt(3))/7}}"],
        answerIndex: 0,
        explanation:
          "Multiply top and bottom by the conjugate {{2 + sqrt(3)}}. Bottom: {{(2 - sqrt(3))(2 + sqrt(3)) = 4 - 3 = 1}}. Top: {{(2 + sqrt(3))^2 = 4 + 4 sqrt(3) + 3 = 7 + 4 sqrt(3)}}. Over 1, the answer is {{7 + 4 sqrt(3)}}. 7 squares each term and loses the middle term; {{7 + 2 sqrt(3)}} counts the middle term only once; dividing by 7 comes from thinking the denominator is {{4 + 3}}.",
        difficulty: "challenge",
        guideRef: "rationalising",
        hints: [
          "What do you multiply {{2 - sqrt(3)}} by to get rid of the surd?",
          "Use the conjugate {{2 + sqrt(3)}} — difference of two squares on the bottom.",
          "{{(2 + sqrt(3))^2}} has **three** terms after expanding.",
        ],
        strategy: "Multiply by a clever form of 1",
      },
      {
        kind: "mcq",
        id: "indices-surds-m1-q15",
        question: "Given that {{sqrt(12) + sqrt(27) = sqrt(n)}}, find {{n}}.",
        options: ["39", "75", "324", "15"],
        answerIndex: 1,
        explanation:
          "{{sqrt(12) = 2 sqrt(3)}} and {{sqrt(27) = 3 sqrt(3)}}, so the sum is {{5 sqrt(3) = sqrt(25 * 3) = sqrt(75)}}. 39 adds under the root ({{sqrt(12) + sqrt(27) != sqrt(39)}}); 324 multiplies 12 × 27; 15 is 5 × 3, forgetting to square the 5 when moving it back inside the root.",
        difficulty: "challenge",
        guideRef: "simplifying-surds",
        hints: [
          "Simplify each surd so they share the same root.",
          "You should reach {{5 sqrt(3)}}. How do you write that as a single square root?",
          "To move 5 inside a square root it becomes {{5^2}}.",
        ],
        strategy: "Work backwards",
      },
    ],
  },

  // =========================================================================
  // MCQ Paper 2
  // =========================================================================
  {
    id: "indices-surds-m2",
    title: "MCQ Paper 2",
    questions: [
      {
        kind: "mcq",
        id: "indices-surds-m2-q01",
        question: "Simplify {{m^9 / m^3}}.",
        options: ["{{m^3}}", "{{m^12}}", "{{m^(-6)}}", "{{m^6}}"],
        answerIndex: 3,
        explanation:
          "Dividing powers of the same base: **subtract** the indices, {{9 - 3 = 6}}, so {{m^6}}. {{m^3}} divides the indices; {{m^12}} adds them (that is for multiplying); {{m^(-6)}} subtracts the wrong way round.",
        difficulty: "warmup",
        guideRef: "index-laws",
        hints: ["Write it out: nine {{m}}'s on top, three on the bottom. How many are left after cancelling?"],
        strategy: "Try small cases",
      },
      {
        kind: "mcq",
        id: "indices-surds-m2-q02",
        question: "Work out {{64^(1/3)}}.",
        options: ["4", "8", "{{64/3}}", "{{1/4}}"],
        answerIndex: 0,
        explanation:
          "A power of {{1/3}} means cube root: {{cbrt(64) = 4}} because {{4^3 = 64}}. 8 is the *square* root; {{64/3}} divides by 3 instead of rooting; {{1/4}} confuses a fractional index with a negative one.",
        difficulty: "warmup",
        guideRef: "negative-fractional-indices",
        hints: ["{{x^(1/3) * x^(1/3) * x^(1/3) = x^1}}. So {{x^(1/3)}} is which root?"],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "indices-surds-m2-q03",
        question: "Write {{3.06 * 10^5}} as an ordinary number.",
        options: ["3 060 000", "306 000", "30 600", "0.000 030 6"],
        answerIndex: 1,
        explanation:
          "Multiply 3.06 by 10 five times — the digits move 5 places left: 306 000. 3 060 000 counts 5 zeros to *add* rather than 5 places to move; 30 600 moves only 4 places; 0.000 030 6 treats the power as negative.",
        difficulty: "warmup",
        guideRef: "standard-form",
        hints: ["{{10^5}} = 100 000. What is 3.06 × 100 000?"],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "indices-surds-m2-q04",
        question: "Expand {{sqrt(3)(sqrt(3) + 2)}}.",
        options: ["{{9 + 2 sqrt(3)}}", "{{3 sqrt(3)}}", "{{3 + 2 sqrt(3)}}", "{{3 + sqrt(6)}}"],
        answerIndex: 2,
        explanation:
          "{{sqrt(3) * sqrt(3) = 3}} and {{sqrt(3) * 2 = 2 sqrt(3)}}, so {{3 + 2 sqrt(3)}}. {{9 + 2 sqrt(3)}} thinks {{sqrt(3) * sqrt(3) = 9}}; {{3 sqrt(3)}} treats {{sqrt(3) * sqrt(3)}} as {{sqrt(3)}}; {{3 + sqrt(6)}} puts the 2 under the root.",
        difficulty: "warmup",
        guideRef: "surd-brackets",
        hints: ["Multiply {{sqrt(3)}} by each term in the bracket. What is {{sqrt(3) * sqrt(3)}}?"],
        strategy: "Grid method",
      },
      {
        kind: "mcq",
        id: "indices-surds-m2-q05",
        question: "Without a calculator, work out the value of {{81^(-3/4)}}.",
        options: ["27", "−27", "{{-243/4}}", "{{1/27}}"],
        answerIndex: 3,
        explanation:
          "Fourth root first: 3, since {{3^4 = 81}}. Cube it: 27. Negative ⇒ reciprocal: {{1/27}}. 27 ignores the minus; −27 thinks a negative index makes the answer negative; {{-243/4}} multiplies 81 by {{-3/4}} as if the index were a multiplier.",
        difficulty: "core",
        guideRef: "negative-fractional-indices",
        hints: [
          "Split {{-3/4}} into its three jobs: reciprocal, 4th root, cube.",
          "What number to the power 4 makes 81?",
          "{{81^(3/4) = 3^3 = 27}}. Now apply the minus.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "indices-surds-m2-q06",
        question: "Simplify fully {{(4x^3 y^2)^2 / (2x^2 y)^3}}.",
        options: ["{{2y}}", "{{y}}", "{{8/3 y}}", "{{2xy}}"],
        answerIndex: 0,
        explanation:
          "Top: {{(4x^3 y^2)^2 = 16x^6 y^4}}. Bottom: {{(2x^2 y)^3 = 8x^6 y^3}}. Divide: {{16/8 = 2}}, {{x^6/x^6 = x^0 = 1}}, {{y^4/y^3 = y}}: answer {{2y}}. {{y}} squares 4 to get 8; {{8/3 y}} cubes 2 to get 6; {{2xy}} treats {{x^0}} as {{x}} instead of 1.",
        difficulty: "core",
        guideRef: "index-laws",
        hints: [
          "Expand each bracket first — every factor inside gets the power.",
          "Top is {{16x^6 y^4}}. What is the bottom?",
          "What is {{x^6 / x^6}}? Anything (non-zero) to the power 0 is 1.",
        ],
        strategy: "Split into parts",
      },
      {
        kind: "mcq",
        id: "indices-surds-m2-q07",
        question: "Without a calculator, work out {{(8 * 10^3) / (2 * 10^(-5))}}. Give your answer in standard form.",
        options: ["{{4 * 10^(-2)}}", "{{4 * 10^(-8)}}", "{{4 * 10^8}}", "{{6 * 10^8}}"],
        answerIndex: 2,
        explanation:
          "Divide the numbers, subtract the powers: {{8/2 = 4}} and {{10^(3 - (-5)) = 10^8}}, giving {{4 * 10^8}}. {{4 * 10^(-2)}} adds the indices (that's for multiplying); {{4 * 10^(-8)}} gets the double negative wrong; {{6 * 10^8}} subtracts 8 − 2 instead of dividing.",
        difficulty: "core",
        guideRef: "standard-form",
        hints: [
          "Divide the front numbers and deal with the powers of 10 separately.",
          "For division, subtract the indices: {{3 - (-5)}}.",
          "Subtracting a negative is adding.",
        ],
        strategy: "Split into parts",
      },
      {
        kind: "mcq",
        id: "indices-surds-m2-q08",
        question:
          "The mass of the Sun is {{1.99 * 10^30}} kg. The mass of the Earth is {{5.97 * 10^24}} kg. How many times heavier than the Earth is the Sun? Give your answer in standard form to 3 significant figures.",
        options: ["{{3.33 * 10^6}}", "{{3.33 * 10^5}}", "{{3.00 * 10^(-6)}}", "{{3.33 * 10^54}}"],
        answerIndex: 1,
        explanation:
          "{{(1.99 * 10^30)/(5.97 * 10^24) = (1.99/5.97) * 10^6 = 0.3333... * 10^6 = 3.33 * 10^5}}. {{3.33 * 10^6}} forgets to adjust the power after 0.333 becomes 3.33; {{3.00 * 10^(-6)}} divides the Earth by the Sun; {{10^54}} adds the indices instead of subtracting.",
        difficulty: "core",
        guideRef: "standard-form",
        hints: [
          "'How many times heavier' means divide — which mass goes on top?",
          "{{1.99/5.97}} is less than 1. What does that do to the power of 10?",
          "{{0.333 * 10^6 = 3.33 * 10^5}}.",
        ],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "indices-surds-m2-q09",
        question: "Solve {{4^x = 8^(x-1)}}.",
        options: ["{{x = 1}}", "{{x = 2}}", "{{x = -3}}", "{{x = 3}}"],
        answerIndex: 3,
        explanation:
          "Base 2: {{4^x = 2^(2x)}} and {{8^(x-1) = 2^(3(x-1)) = 2^(3x-3)}}. So {{2x = 3x - 3}}, giving {{x = 3}}. Check: {{4^3 = 64 = 8^2}} ✓. {{x = 1}} forgets to multiply the whole bracket by 3 ({{2x = 3x - 1}}); {{x = 2}} treats {{4^x}} and {{8^(x-1)}} as {{4x}} and {{8(x-1)}}; {{x = -3}} is a rearranging sign slip.",
        difficulty: "core",
        guideRef: "index-equations",
        hints: [
          "4 and 8 are both powers of 2.",
          "{{8^(x-1) = (2^3)^(x-1)}}. Multiply out the index carefully.",
          "Set the indices equal: {{2x = 3x - 3}}.",
        ],
        strategy: "Write with the same base",
      },
      {
        kind: "mcq",
        id: "indices-surds-m2-q10",
        question: "Simplify {{2 sqrt(6) * 5 sqrt(10)}}. Give your answer in the form {{a sqrt(b)}}, where {{b}} is as small as possible.",
        options: ["{{20 sqrt(15)}}", "40", "{{7 sqrt(60)}}", "{{10 sqrt(15)}}"],
        answerIndex: 0,
        explanation:
          "Numbers × numbers, roots × roots: {{2 * 5 = 10}}, {{sqrt(6) * sqrt(10) = sqrt(60) = sqrt(4 * 15) = 2 sqrt(15)}}. So {{10 * 2 sqrt(15) = 20 sqrt(15)}}. 40 adds 6 + 10 under the root to get {{sqrt(16)}}; {{7 sqrt(60)}} adds the coefficients; {{10 sqrt(15)}} simplifies {{sqrt(60)}} but drops the 2 that came out.",
        difficulty: "core",
        guideRef: "simplifying-surds",
        hints: [
          "Use {{sqrt(a) * sqrt(b) = sqrt(ab)}} and multiply the whole numbers separately.",
          "You should get {{10 sqrt(60)}}. Is 60 square-free?",
          "{{60 = 4 * 15}} — and the {{sqrt(4)}} comes out as 2.",
        ],
        strategy: "Find the largest square factor",
      },
      {
        kind: "mcq",
        id: "indices-surds-m2-q11",
        question: "Expand and simplify {{(sqrt(7) - sqrt(2))^2}}.",
        options: ["5", "{{9 - sqrt(14)}}", "{{9 - 2 sqrt(14)}}", "{{5 - 2 sqrt(14)}}"],
        answerIndex: 2,
        explanation:
          "{{(a - b)^2 = a^2 - 2ab + b^2}}: {{7 - 2 sqrt(14) + 2 = 9 - 2 sqrt(14)}}. 5 squares each term and subtracts — the classic 'forgot the middle term' slip; {{9 - sqrt(14)}} includes the middle term only once; {{5 - 2 sqrt(14)}} makes {{(-sqrt(2))^2}} negative.",
        difficulty: "core",
        guideRef: "surd-brackets",
        hints: [
          "Write it as {{(sqrt(7) - sqrt(2))(sqrt(7) - sqrt(2))}} — four products.",
          "{{(-sqrt(2)) * (-sqrt(2))}} is positive.",
          "The two middle products are both {{-sqrt(14)}}.",
        ],
        strategy: "Grid method",
      },
      {
        kind: "mcq",
        id: "indices-surds-m2-q12",
        question: "Write {{10/sqrt(5) + sqrt(20)}} in the form {{k sqrt(5)}}.",
        options: ["{{12 sqrt(5)}}", "{{4 sqrt(5)}}", "{{4 sqrt(10)}}", "{{2 + 2 sqrt(5)}}"],
        answerIndex: 1,
        explanation:
          "{{10/sqrt(5) = (10 sqrt(5))/5 = 2 sqrt(5)}} and {{sqrt(20) = 2 sqrt(5)}}, so the total is {{4 sqrt(5)}}. {{12 sqrt(5)}} forgets that the denominator becomes 5; {{4 sqrt(10)}} adds {{sqrt(5) + sqrt(5)}} as {{sqrt(10)}}; {{2 + 2 sqrt(5)}} cancels {{10/sqrt(5)}} as if it were {{10/5}}.",
        difficulty: "core",
        guideRef: "rationalising",
        hints: [
          "Get both terms as multiples of {{sqrt(5)}}.",
          "Rationalise {{10/sqrt(5)}} by multiplying top and bottom by {{sqrt(5)}}.",
          "{{sqrt(20) = sqrt(4) sqrt(5)}}.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "indices-surds-m2-q13",
        question: "Solve {{2^(2x) - 6 * 2^x + 8 = 0}}.",
        options: ["{{x = 2}} or {{x = 4}}", "{{x = -2}} or {{x = -4}}", "{{x = 4}} or {{x = 16}}", "{{x = 1}} or {{x = 2}}"],
        answerIndex: 3,
        explanation:
          "{{2^(2x) = (2^x)^2}}, so let {{y = 2^x}}: {{y^2 - 6y + 8 = 0}}, {{(y - 2)(y - 4) = 0}}. Then {{2^x = 2}} gives {{x = 1}} and {{2^x = 4}} gives {{x = 2}}. {{x = 2}} or 4 stops at {{y}}; −2 or −4 is a factorising sign slip (and {{2^x}} is never negative); 4 or 16 works out {{2^2}} and {{2^4}} — the substitution done backwards.",
        difficulty: "challenge",
        guideRef: "harder-index-equations",
        hints: [
          "How is {{2^(2x)}} related to {{2^x}}?",
          "Let {{y = 2^x}}. Then {{2^(2x) = y^2}} — rewrite the equation.",
          "Solve the quadratic in {{y}}, then solve {{2^x = y}} for each root.",
        ],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "indices-surds-m2-q14",
        question: "Solve {{3^(2x+1) - 10 * 3^x + 3 = 0}}.",
        options: ["{{x = -1}} or {{x = 1}}", "{{x = 1/3}} or {{x = 3}}", "{{x = 1}} only", "No real solutions — a power of 3 can't equal {{1/3}}"],
        answerIndex: 0,
        explanation:
          "{{3^(2x+1) = 3 * (3^x)^2}}. Let {{y = 3^x}}: {{3y^2 - 10y + 3 = 0}}, {{(3y - 1)(y - 3) = 0}}, so {{y = 1/3}} or {{y = 3}}. {{3^x = 1/3 = 3^(-1)}} gives {{x = -1}}; {{3^x = 3}} gives {{x = 1}}. {{1/3}} or 3 are the values of {{y}}, not {{x}}; '{{x = 1}} only' and 'no real solutions' both wrongly reject {{3^x = 1/3}} — a negative **index** is fine, only a negative *value* of {{3^x}} is impossible.",
        difficulty: "challenge",
        guideRef: "harder-index-equations",
        hints: [
          "Split {{3^(2x+1)}} using the index laws: {{3^(2x) * 3^1}}.",
          "Let {{y = 3^x}}. You should get {{3y^2 - 10y + 3 = 0}}.",
          "Factorise, then solve {{3^x = 1/3}} and {{3^x = 3}}.",
        ],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "indices-surds-m2-q15",
        question:
          "A rectangle has sides of length {{(3 + sqrt(2))}} cm and {{(3 - sqrt(2))}} cm. Find the exact length of its diagonal.",
        diagram: `<svg viewBox="0 0 320 150" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Rectangle with long side 3 plus root 2 centimetres and short side 3 minus root 2 centimetres, with a dashed diagonal marked d"><rect x="0" y="0" width="320" height="150" fill="#ffffff"/><rect x="50" y="30" width="220" height="79" fill="#c7d2fe" stroke="#334155" stroke-width="2"/><line x1="50" y1="109" x2="270" y2="30" stroke="#1f2937" stroke-width="2" stroke-dasharray="6 4"/><polyline points="50,99 60,99 60,109" fill="none" stroke="#334155" stroke-width="1.5"/><text x="160" y="130" font-size="13" font-family="sans-serif" text-anchor="middle" fill="#1f2937">(3 + √2) cm</text><text x="278" y="74" font-size="13" font-family="sans-serif" fill="#1f2937">(3 − √2) cm</text><text x="150" y="62" font-size="14" font-style="italic" font-family="sans-serif" fill="#1f2937">d</text></svg>`,
        options: ["22 cm", "{{3 sqrt(2)}} cm", "{{sqrt(22)}} cm", "6 cm"],
        answerIndex: 2,
        explanation:
          "Pythagoras: {{d^2 = (3 + sqrt(2))^2 + (3 - sqrt(2))^2 = (11 + 6 sqrt(2)) + (11 - 6 sqrt(2)) = 22}}, so {{d = sqrt(22)}} cm. The surd terms cancel. 22 forgets the final square root; {{3 sqrt(2) = sqrt(18)}} squares only the 3s and ignores the surds; 6 adds the two sides.",
        difficulty: "challenge",
        guideRef: "surd-brackets",
        hints: [
          "The diagonal is the hypotenuse of a right-angled triangle.",
          "Expand {{(3 + sqrt(2))^2}} and {{(3 - sqrt(2))^2}} — each has three terms.",
          "Add them: what happens to the {{6 sqrt(2)}} terms?",
        ],
        strategy: "Draw a diagram",
      },
    ],
  },

  // =========================================================================
  // MCQ Paper 3 — Exam style
  // =========================================================================
  {
    id: "indices-surds-m3",
    title: "MCQ Paper 3 — Exam style",
    questions: [
      {
        kind: "mcq",
        id: "indices-surds-m3-q01",
        question: "Write {{(5^3 * 5^4)/5^2}} as a single power of 5.",
        options: ["{{5^10}}", "{{5^6}}", "{{5^5}}", "{{5^9}}"],
        answerIndex: 2,
        explanation:
          "Top: {{5^(3+4) = 5^7}}. Divide: {{5^(7-2) = 5^5}}. {{5^10}} multiplies 3 × 4 then subtracts 2; {{5^6}} multiplies 3 × 4 then divides by 2; {{5^9}} adds all three indices.",
        difficulty: "warmup",
        guideRef: "index-laws",
        hints: ["Multiplying ⇒ add indices; dividing ⇒ subtract indices. Do the top first."],
        strategy: "Split into parts",
      },
      {
        kind: "mcq",
        id: "indices-surds-m3-q02",
        question: "Write {{1/x^3}} as a power of {{x}}.",
        options: ["{{x^(1/3)}}", "{{-x^3}}", "{{x^(-1/3)}}", "{{x^(-3)}}"],
        answerIndex: 3,
        explanation:
          "A reciprocal is a negative index: {{1/x^3 = x^(-3)}}. {{x^(1/3)}} is the cube root — a fractional index, not a reciprocal; {{-x^3}} makes the value negative; {{x^(-1/3)}} mixes up both ideas.",
        difficulty: "warmup",
        guideRef: "negative-fractional-indices",
        hints: ["Use {{x^3 / x^6 = x^(3-6)}}. What does that tell you {{1/x^3}} equals?"],
        strategy: "Find a pattern",
      },
      {
        kind: "mcq",
        id: "indices-surds-m3-q03",
        question: "Rationalise the denominator of {{5/sqrt(2)}}.",
        options: ["{{(5 sqrt(2))/2}}", "{{5 sqrt(2)}}", "{{(5 sqrt(2))/4}}", "{{sqrt(10)/2}}"],
        answerIndex: 0,
        explanation:
          "{{5/sqrt(2) * sqrt(2)/sqrt(2) = (5 sqrt(2))/2}}. {{5 sqrt(2)}} multiplies only the top; {{(5 sqrt(2))/4}} thinks {{sqrt(2) * sqrt(2) = 4}}; {{sqrt(10)/2}} would be the answer for {{sqrt(5)/sqrt(2)}} — the 5 is not under a root.",
        difficulty: "warmup",
        guideRef: "rationalising",
        hints: ["Multiply top and bottom by {{sqrt(2)}}. What is {{sqrt(2) * sqrt(2)}}?"],
        strategy: "Multiply by a clever form of 1",
      },
      {
        kind: "mcq",
        id: "indices-surds-m3-q04",
        question: "Which of these numbers is **not** written in standard form?",
        options: ["{{8 * 10^(-4)}}", "{{0.8 * 10^4}}", "{{1.0 * 10^9}}", "{{9.99 * 10^3}}"],
        answerIndex: 1,
        explanation:
          "Standard form is {{A * 10^n}} with {{1 <= A < 10}} and {{n}} an integer. In {{0.8 * 10^4}} the front number 0.8 is less than 1 (it should be {{8 * 10^3}}). A negative power is fine, 1.0 is allowed (1 ≤ A), and 9.99 is less than 10.",
        difficulty: "warmup",
        guideRef: "standard-form",
        hints: ["Check the front number in each: it must be at least 1 and less than 10."],
        strategy: "Eliminate options",
      },
      {
        kind: "mcq",
        id: "indices-surds-m3-q05",
        question:
          "A red blood cell has a diameter of {{8 * 10^(-6)}} m. How many red blood cells, laid end to end, would make a line 2 cm long?",
        options: ["{{2.5 * 10^5}}", "{{2.5 * 10^(-3)}}", "{{1.6 * 10^(-7)}}", "{{2.5 * 10^3}}"],
        answerIndex: 3,
        explanation:
          "Convert first: 2 cm = 0.02 m = {{2 * 10^(-2)}} m. Then {{(2 * 10^(-2))/(8 * 10^(-6)) = 0.25 * 10^4 = 2.5 * 10^3}} cells. {{2.5 * 10^5}} uses 2 m instead of 2 cm; {{2.5 * 10^(-3)}} gets the power the wrong sign; {{1.6 * 10^(-7)}} multiplies instead of dividing.",
        difficulty: "core",
        guideRef: "standard-form",
        hints: [
          "Units first — the cell is measured in metres.",
          "Number of cells = total length ÷ length of one cell.",
          "{{0.02/0.000 008}}: estimate — is it about a thousand, a million, or tiny?",
        ],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "indices-surds-m3-q06",
        question:
          "Light travels at {{3.0 * 10^8}} m/s. Sunlight takes 8 minutes 20 seconds to reach the Earth. Work out the distance from the Sun to the Earth. Give your answer in metres in standard form.",
        options: ["{{1.48 * 10^11}}", "{{2.46 * 10^9}}", "{{1.5 * 10^11}}", "{{6.0 * 10^5}}"],
        answerIndex: 2,
        explanation:
          "8 min 20 s = 8 × 60 + 20 = 500 s. Distance = speed × time = {{3.0 * 10^8 * 500 = 1.5 * 10^11}} m. {{1.48 * 10^11}} treats 8 min 20 s as 8.2 minutes (492 s); {{2.46 * 10^9}} uses 8.2 without converting to seconds; {{6.0 * 10^5}} divides speed by time.",
        difficulty: "core",
        guideRef: "standard-form",
        hints: [
          "The speed is per second, so the time must be in seconds.",
          "Careful: 20 seconds is not 0.2 minutes.",
          "Distance = speed × time.",
        ],
        strategy: "Check the units",
      },
      {
        kind: "mcq",
        id: "indices-surds-m3-q07",
        question: "Given that {{(x^a)^3 * x^5 = x^20}}, find the value of {{a}}.",
        options: ["12", "5", "15", "4"],
        answerIndex: 1,
        explanation:
          "{{(x^a)^3 = x^(3a)}}, so {{x^(3a) * x^5 = x^(3a+5)}}. Then {{3a + 5 = 20}}, so {{a = 5}}. 12 treats {{(x^a)^3}} as {{x^(a+3)}}; 15 forgets the power 3 and just does 20 − 5; 4 divides 20 by 5.",
        difficulty: "core",
        guideRef: "index-laws",
        hints: [
          "Simplify the left-hand side to a single power of {{x}}.",
          "Power of a power: multiply. Then multiplying: add.",
          "Set the indices equal: {{3a + 5 = 20}}.",
        ],
        strategy: "Work backwards",
      },
      {
        kind: "mcq",
        id: "indices-surds-m3-q08",
        question: "Simplify fully {{(27x^6)^(2/3)}}.",
        options: ["{{9x^4}}", "{{18x^4}}", "{{9x^9}}", "{{3x^4}}"],
        answerIndex: 0,
        explanation:
          "Apply the power to both factors. {{27^(2/3) = (cbrt(27))^2 = 9}} and {{(x^6)^(2/3) = x^(6 * 2/3) = x^4}}: {{9x^4}}. {{18x^4}} multiplies 27 by {{2/3}}; {{9x^9}} multiplies 6 by {{3/2}}; {{3x^4}} takes the cube root of 27 but forgets to square it.",
        difficulty: "core",
        guideRef: "negative-fractional-indices",
        hints: [
          "The power {{2/3}} applies to the 27 **and** to {{x^6}}.",
          "For 27: cube root, then square.",
          "For {{x^6}}: multiply the indices, {{6 * 2/3}}.",
        ],
        strategy: "Split into parts",
      },
      {
        kind: "mcq",
        id: "indices-surds-m3-q09",
        question: "Solve {{2^x * 4^(x+1) = 32}}.",
        options: ["{{x = 4/3}}", "{{x = 2}}", "{{x = 1/3}}", "{{x = 1}}"],
        answerIndex: 3,
        explanation:
          "Base 2 throughout: {{4^(x+1) = 2^(2x+2)}} and {{32 = 2^5}}. So {{2^(x + 2x + 2) = 2^5}}, {{3x + 2 = 5}}, {{x = 1}}. Check: {{2 * 4^2 = 32}} ✓. {{4/3}} writes {{4^(x+1)}} as {{2^(2x+1)}} (only doubling the {{x}}); 2 treats {{4^(x+1)}} as {{2^(x+1)}}; {{1/3}} multiplies the bases, {{2 * 4 = 8}}, which isn't allowed when the indices differ.",
        difficulty: "core",
        guideRef: "index-equations",
        hints: [
          "Write 4 and 32 as powers of 2.",
          "{{4^(x+1) = (2^2)^(x+1)}} — double the **whole** index.",
          "Add the indices on the left and set equal to 5.",
        ],
        strategy: "Write with the same base",
      },
      {
        kind: "mcq",
        id: "indices-surds-m3-q10",
        question: "A square has area 98 cm². Find the exact perimeter of the square.",
        options: ["{{7 sqrt(2)}} cm", "{{28 sqrt(2)}} cm", "{{196 sqrt(2)}} cm", "{{14 sqrt(2)}} cm"],
        answerIndex: 1,
        explanation:
          "Side = {{sqrt(98) = sqrt(49 * 2) = 7 sqrt(2)}} cm. Perimeter = 4 × side = {{28 sqrt(2)}} cm. {{7 sqrt(2)}} is just the side; {{196 sqrt(2)}} writes {{sqrt(98)}} as {{49 sqrt(2)}} (forgetting to root the 49); {{14 sqrt(2)}} uses 2 sides instead of 4.",
        difficulty: "core",
        guideRef: "simplifying-surds",
        hints: [
          "Side length = {{sqrt(area)}}.",
          "Simplify {{sqrt(98)}} using a square factor.",
          "A square has four equal sides.",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "indices-surds-m3-q11",
        question: "Expand and simplify {{(2 + sqrt(3))(2 - sqrt(3))}}.",
        options: ["7", "{{4 - sqrt(3)}}", "1", "−1"],
        answerIndex: 2,
        explanation:
          "Difference of two squares: {{2^2 - (sqrt(3))^2 = 4 - 3 = 1}}. The surd terms {{-2 sqrt(3) + 2 sqrt(3)}} cancel. 7 adds 4 + 3; {{4 - sqrt(3)}} forgets to square {{sqrt(3)}}; −1 subtracts the wrong way round.",
        difficulty: "core",
        guideRef: "surd-brackets",
        hints: [
          "This is {{(a + b)(a - b)}}. What does that always expand to?",
          "{{(sqrt(3))^2 = 3}}.",
        ],
        strategy: "Spot a pattern",
      },
      {
        kind: "mcq",
        id: "indices-surds-m3-q12",
        question: "Write {{(sqrt(3) + 1)/(sqrt(3) - 1)}} in the form {{a + sqrt(b)}}, where {{a}} and {{b}} are integers.",
        options: ["{{2 + sqrt(3)}}", "{{4 + 2 sqrt(3)}}", "{{1 + sqrt(3)/2}}", "{{2 + 2 sqrt(3)}}"],
        answerIndex: 0,
        explanation:
          "Multiply top and bottom by {{sqrt(3) + 1}}. Top: {{(sqrt(3) + 1)^2 = 4 + 2 sqrt(3)}}. Bottom: {{3 - 1 = 2}}. So {{(4 + 2 sqrt(3))/2 = 2 + sqrt(3)}}. {{4 + 2 sqrt(3)}} forgets to divide by 2; {{1 + sqrt(3)/2}} uses {{3 + 1 = 4}} on the bottom; {{2 + 2 sqrt(3)}} divides only the first term by 2.",
        difficulty: "core",
        guideRef: "rationalising",
        hints: [
          "Use the conjugate of the denominator.",
          "Bottom: {{(sqrt(3) - 1)(sqrt(3) + 1)}} — difference of two squares.",
          "Divide **every** term on the top by the denominator.",
        ],
        strategy: "Multiply by a clever form of 1",
      },
      {
        kind: "mcq",
        id: "indices-surds-m3-q13",
        question: "Solve {{2x^(-3/2) = 1/4}}.",
        options: ["{{1/4}}", "64", "2.52 (to 3 s.f.)", "4"],
        answerIndex: 3,
        explanation:
          "Divide by 2: {{x^(-3/2) = 1/8}}. Flip both sides: {{x^(3/2) = 8}}. Raise to the power {{2/3}}: {{x = 8^(2/3) = 2^2 = 4}}. Check: {{2 * 4^(-3/2) = 2 * 1/8 = 1/4}} ✓. {{1/4}} raises {{1/8}} to the power {{2/3}} without flipping; 64 squares 8 instead of using {{2/3}}; 2.52 ignores the 2 at the front ({{4^(2/3)}}).",
        difficulty: "challenge",
        guideRef: "harder-index-equations",
        hints: [
          "Get {{x^(-3/2)}} on its own first.",
          "A negative index: take the reciprocal of both sides to get {{x^(3/2) = 8}}.",
          "Undo the power {{3/2}} with the power {{2/3}}.",
        ],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "indices-surds-m3-q14",
        question: "Given that {{(p + sqrt(2))^2 = 27 + 10 sqrt(2)}}, where {{p}} is a positive integer, find {{p}}.",
        options: ["10", "5", "25", "{{5/2}}"],
        answerIndex: 1,
        explanation:
          "{{(p + sqrt(2))^2 = p^2 + 2p sqrt(2) + 2}}. Compare the surd parts: {{2p = 10}}, so {{p = 5}}. Check the whole-number part: {{25 + 2 = 27}} ✓. 10 forgets the 2 in the middle term {{2p sqrt(2)}}; 25 is {{p^2}}, not {{p}}; {{5/2}} uses {{4p}} for the middle term.",
        difficulty: "challenge",
        guideRef: "surd-brackets",
        hints: [
          "Expand the left-hand side in terms of {{p}}.",
          "The surd parts on both sides must be equal, and so must the whole-number parts.",
          "Middle term: {{2 * p * sqrt(2)}}. Then check with the whole-number part.",
        ],
        strategy: "Compare coefficients",
      },
      {
        kind: "mcq",
        id: "indices-surds-m3-q15",
        question: "Rationalise the denominator and simplify {{2/(sqrt(5) + sqrt(3))}}.",
        options: ["{{(sqrt(5) - sqrt(3))/4}}", "{{2 sqrt(5) - 2 sqrt(3)}}", "{{sqrt(5) - sqrt(3)}}", "{{sqrt(2)/2}}"],
        answerIndex: 2,
        explanation:
          "Multiply by {{(sqrt(5) - sqrt(3))/(sqrt(5) - sqrt(3))}}. Bottom: {{5 - 3 = 2}}. So {{(2(sqrt(5) - sqrt(3)))/2 = sqrt(5) - sqrt(3)}}. {{(sqrt(5) - sqrt(3))/4}} uses {{5 + 3 = 8}} on the bottom; {{2 sqrt(5) - 2 sqrt(3)}} forgets to divide by 2; {{sqrt(2)/2}} adds {{sqrt(5) + sqrt(3)}} as {{sqrt(8)}}.",
        difficulty: "challenge",
        guideRef: "rationalising",
        hints: [
          "What is the conjugate of {{sqrt(5) + sqrt(3)}}?",
          "{{(sqrt(5) + sqrt(3))(sqrt(5) - sqrt(3)) = 5 - 3}}.",
          "Cancel the 2 on top with the 2 on the bottom.",
        ],
        strategy: "Multiply by a clever form of 1",
      },
    ],
  },
];
