import type { TopicPractice } from "../../types.ts";

export const practice: TopicPractice = {
  // =========================================================================
  // QUICK-CHECK QUIZ — 10 questions across the main sections (3 mcq, 7 short)
  // =========================================================================
  quiz: [
    {
      kind: "short",
      id: "indices-surds-quiz-q01",
      question: "Simplify fully {{(2a^3 b)^4}}.",
      answer: { type: "expression", expr: "16a^12b^4", form: "simplified", display: "{{16a^12 b^4}}" },
      solution: [
        "Everything inside the bracket is raised to the power 4.",
        "{{2^4 = 16}}, {{(a^3)^4 = a^12}}, {{b^4 = b^4}}.",
        "So {{(2a^3 b)^4 = 16a^12 b^4}}.",
      ],
      commonError: "Writing {{2a^12 b^4}} (forgetting to raise the 2 to the power 4) or {{8a^12 b^4}} (multiplying 2 × 4).",
      traps: [
        { spec: { type: "expression", expr: "2a^12b^4" }, feedback: "The number 2 is inside the bracket too — it must be raised to the power 4: {{2^4 = 16}}." },
        { spec: { type: "expression", expr: "8a^12b^4" }, feedback: "{{2^4}} means 2 × 2 × 2 × 2, not 2 × 4." },
        { spec: { type: "expression", expr: "16a^7b^4" }, feedback: "Power of a power: *multiply* the indices, so {{(a^3)^4 = a^12}}, not {{a^7}}." },
      ],
      difficulty: "warmup",
      guideRef: "index-laws",
      hints: ["Every factor inside the bracket gets the power 4 — including the number.", "{{(a^3)^4}}: multiply the indices."],
      strategy: "Break it into parts",
    },
    {
      kind: "mcq",
      id: "indices-surds-quiz-q02",
      question: "Work out the value of {{16^(-1/2)}}.",
      options: ["{{1/4}}", "−4", "−8", "4"],
      answerIndex: 0,
      explanation:
        "The negative index means *reciprocal*, and the {{1/2}} means *square root*: {{16^(-1/2) = 1/sqrt(16) = 1/4}}. A negative index never makes the answer negative, so −4 is wrong; −8 comes from multiplying 16 by {{-1/2}}; 4 ignores the minus sign completely.",
      difficulty: "warmup",
      guideRef: "negative-fractional-indices",
      hints: ["Deal with the two parts of the index separately: the minus sign and the {{1/2}}.", "Negative index → reciprocal. Index {{1/2}} → square root."],
      strategy: "Break it into parts",
    },
    {
      kind: "short",
      id: "indices-surds-quiz-q03",
      question: "Without a calculator, work out {{(8/27)^(-2/3)}}. Give your answer as a fraction in its simplest form.",
      answer: { type: "fraction", n: 9, d: 4, simplest: true },
      solution: [
        "Negative index: flip the fraction. {{(8/27)^(-2/3) = (27/8)^(2/3)}}.",
        "Cube root first: {{(27/8)^(1/3) = 3/2}}.",
        "Then square: {{(3/2)^2 = 9/4}}.",
      ],
      solutions: [
        { label: "Root first (smaller numbers)", steps: ["Flip: {{(27/8)^(2/3)}}.", "Cube root: {{3/2}}.", "Square: {{9/4}}."] },
        { label: "Power first", steps: ["{{(27/8)^2 = 729/64}}.", "Cube root: {{cbrt(729)/cbrt(64) = 9/4}}.", "Same answer, but much bigger numbers — root first is quicker."] },
      ],
      commonError: "Forgetting to flip, giving {{4/9}}.",
      traps: [
        { spec: { type: "fraction", n: 4, d: 9 }, feedback: "That's {{(8/27)^(2/3)}}. The negative index means you must take the reciprocal too." },
        { spec: { type: "fraction", n: 3, d: 2 }, feedback: "You've done the cube root and the flip — now square it (the 2 on top of the index)." },
      ],
      difficulty: "core",
      guideRef: "negative-fractional-indices",
      hints: [
        "There are three jobs hidden in {{-2/3}}: a reciprocal, a cube root and a square. Which order is easiest?",
        "Do the reciprocal first: {{(27/8)^(2/3)}}.",
        "The cube root of {{27/8}} is {{3/2}}. Now square it.",
      ],
      strategy: "Break it into parts",
    },
    {
      kind: "short",
      id: "indices-surds-quiz-q04",
      question: "Write 0.000 307 in standard form.",
      answer: { type: "number", value: 0.000307, standardForm: true, display: "{{3.07 * 10^(-4)}}" },
      solution: [
        "Move the decimal point to get a number between 1 and 10: 3.07.",
        "The point moved 4 places to the right, so the power is −4.",
        "{{3.07 * 10^(-4)}}.",
      ],
      commonError: "Writing {{3.07 * 10^4}} — a small number needs a negative power.",
      traps: [
        { spec: { type: "number", value: 30700 }, feedback: "{{3.07 * 10^4}} is 30 700 — a big number. 0.000 307 is less than 1, so the power must be negative." },
        { spec: { type: "number", value: 0.0000307 }, feedback: "Count again: 0.000 307 → 3.07 needs the point to move 4 places, so {{10^(-4)}}." },
      ],
      difficulty: "warmup",
      guideRef: "standard-form",
      hints: ["Where must the decimal point go so the number is between 1 and 10?", "Count how many places it moves. Small number → negative power."],
      strategy: "Estimate first",
    },
    {
      kind: "short",
      id: "indices-surds-quiz-q05",
      question: "Work out {{(6 * 10^5) * (4 * 10^(-2))}}. Give your answer in standard form.",
      answer: { type: "number", value: 24000, standardForm: true, display: "{{2.4 * 10^4}}" },
      solution: [
        "Multiply the numbers: 6 × 4 = 24.",
        "Add the powers: {{10^5 * 10^(-2) = 10^3}}.",
        "{{24 * 10^3}} is not standard form: {{24 = 2.4 * 10}}, so the answer is {{2.4 * 10^4}}.",
      ],
      commonError: "Leaving {{24 * 10^3}}, which has the right value but is not in standard form.",
      traps: [
        { spec: { type: "number", value: 2400 }, feedback: "When you write 24 as {{2.4 * 10}}, the power goes *up* by one: {{2.4 * 10^4}}." },
        { spec: { type: "number", value: 2.4e8 }, feedback: "{{10^5 * 10^(-2)}} — add the indices: 5 + (−2) = 3, not 7." },
      ],
      difficulty: "core",
      guideRef: "standard-form",
      hints: ["Group the numbers together and the powers of 10 together.", "{{10^5 * 10^(-2)}}: add the indices.", "Is 24 between 1 and 10? Adjust it."],
      strategy: "Break it into parts",
    },
    {
      kind: "mcq",
      id: "indices-surds-quiz-q06",
      question: "Solve {{27^x = 1/9}}.",
      options: ["{{-3/2}}", "{{-2/3}}", "{{2/3}}", "{{-1/3}}"],
      answerIndex: 1,
      explanation:
        "Write both sides as powers of 3: {{3^(3x) = 3^(-2)}}, so 3x = −2 and {{x = -2/3}}. {{-3/2}} comes from dividing the wrong way round (3 ÷ −2); {{2/3}} forgets that {{1/9 = 3^(-2)}} has a negative index; {{-1/3}} treats {{1/9}} as {{3^(-1)}}.",
      difficulty: "core",
      guideRef: "index-equations",
      hints: ["27 and 9 are both powers of the same number.", "{{27 = 3^3}} and {{1/9 = 3^(-2)}}. Now compare the indices."],
      strategy: "Write with the same base",
    },
    {
      kind: "short",
      id: "indices-surds-quiz-q07",
      question: "Simplify {{sqrt(50) + sqrt(18)}}. Give your answer in the form {{k sqrt(2)}}.",
      answer: { type: "expression", expr: "8sqrt(2)", form: "surd", display: "{{8sqrt(2)}}" },
      solution: [
        "{{sqrt(50) = sqrt(25 * 2) = 5sqrt(2)}}.",
        "{{sqrt(18) = sqrt(9 * 2) = 3sqrt(2)}}.",
        "These are like surds: {{5sqrt(2) + 3sqrt(2) = 8sqrt(2)}}.",
      ],
      commonError: "Adding under the root: {{sqrt(50) + sqrt(18) = sqrt(68)}} — roots don't add like that.",
      traps: [
        { spec: { type: "expression", expr: "sqrt(68)" }, feedback: "{{sqrt(a) + sqrt(b) != sqrt(a + b)}}. Simplify each surd first, then collect like surds." },
        { spec: { type: "expression", expr: "2sqrt(17)" }, feedback: "That's {{sqrt(68)}} — you added under the root. Simplify {{sqrt(50)}} and {{sqrt(18)}} separately." },
      ],
      difficulty: "core",
      guideRef: "simplifying-surds",
      hints: ["Find the largest square factor of 50, and of 18.", "{{50 = 25 * 2}} and {{18 = 9 * 2}}.", "Now you have two multiples of {{sqrt(2)}} — collect them."],
      strategy: "Find a square factor",
    },
    {
      kind: "short",
      id: "indices-surds-quiz-q08",
      question: "Expand and simplify {{(3 + sqrt(2))(4 - sqrt(2))}}. Give your answer in the form {{a + b sqrt(2)}}.",
      answer: { type: "expression", expr: "10+sqrt(2)", form: "surd", display: "{{10 + sqrt(2)}}" },
      solution: [
        "Multiply every term by every term: {{3 * 4 = 12}}, {{3 * (-sqrt(2)) = -3sqrt(2)}}, {{sqrt(2) * 4 = 4sqrt(2)}}, {{sqrt(2) * (-sqrt(2)) = -2}}.",
        "Total: {{12 - 3sqrt(2) + 4sqrt(2) - 2}}.",
        "Collect: {{10 + sqrt(2)}}.",
      ],
      commonError: "Writing {{sqrt(2) * sqrt(2) = 4}} or forgetting that this term is negative.",
      traps: [
        { spec: { type: "expression", expr: "14+sqrt(2)" }, feedback: "Check the last term: {{sqrt(2) * (-sqrt(2)) = -2}}, so you subtract 2, not add it." },
        { spec: { type: "expression", expr: "12-2" }, feedback: "You've only multiplied the firsts and the lasts — don't forget the two middle terms." },
      ],
      difficulty: "core",
      guideRef: "surd-brackets",
      hints: ["Expand exactly as you would {{(3 + x)(4 - x)}}.", "Four products. What is {{sqrt(2) * sqrt(2)}}?", "{{sqrt(2) * (-sqrt(2)) = -2}}. Collect the whole numbers and the {{sqrt(2)}} terms."],
      strategy: "Grid method",
    },
    {
      kind: "mcq",
      id: "indices-surds-quiz-q09",
      question: "Rationalise the denominator of {{6/sqrt(3)}} and simplify fully.",
      options: ["{{6sqrt(3)}}", "{{sqrt(3)/2}}", "{{2sqrt(3)}}", "2"],
      answerIndex: 2,
      explanation:
        "Multiply top and bottom by {{sqrt(3)}}: {{(6sqrt(3))/3 = 2sqrt(3)}}. {{6sqrt(3)}} forgets to divide by 3 (the new denominator); {{sqrt(3)/2}} has the fraction upside down; 2 comes from wrongly cancelling {{sqrt(3)}} as if it were 3.",
      difficulty: "core",
      guideRef: "rationalising",
      hints: ["What can you multiply {{sqrt(3)}} by to get a whole number?", "Multiply top *and* bottom by {{sqrt(3)}}, then simplify."],
      strategy: "Multiply by a clever form of 1",
    },
    {
      kind: "short",
      id: "indices-surds-quiz-q10",
      question: "Rationalise the denominator of {{4/(3 - sqrt(5))}}. Give your answer in the form {{a + b sqrt(5)}}, where a and b are integers.",
      answer: { type: "expression", expr: "3+sqrt(5)", form: "surd", display: "{{3 + sqrt(5)}}" },
      solution: [
        "Multiply top and bottom by the conjugate {{3 + sqrt(5)}}.",
        "Denominator: {{(3 - sqrt(5))(3 + sqrt(5)) = 9 - 5 = 4}}.",
        "Numerator: {{4(3 + sqrt(5))}}.",
        "{{(4(3 + sqrt(5)))/4 = 3 + sqrt(5)}}.",
      ],
      commonError: "Multiplying by {{3 - sqrt(5)}} (the same bracket), which does not remove the surd from the denominator.",
      traps: [
        { spec: { type: "expression", expr: "(4(3+sqrt(5)))/14" }, feedback: "Check the denominator: {{(3 - sqrt(5))(3 + sqrt(5)) = 9 - 5 = 4}}, not 9 + 5." },
        { spec: { type: "expression", expr: "(12+4sqrt(5))/9" }, feedback: "{{(sqrt(5))^2 = 5}} must be subtracted from 9 — difference of two squares gives 9 − 5." },
      ],
      difficulty: "core",
      guideRef: "rationalising",
      hints: ["What could you multiply {{3 - sqrt(5)}} by so the surd disappears?", "Use the conjugate {{3 + sqrt(5)}} — difference of two squares.", "The denominator becomes {{9 - 5 = 4}}."],
      strategy: "Use the conjugate",
    },
  ],

  // =========================================================================
  // PRACTICE PAPERS
  // =========================================================================
  papers: [
    {
      id: "indices-surds-p1",
      title: "Practice Paper 1",
      questions: [
        {
          kind: "short",
          id: "indices-surds-p1-q01",
          question: "Simplify {{(x^5 * x^3)/x^2}}.",
          answer: { type: "expression", expr: "x^6", form: "simplified", display: "{{x^6}}" },
          solution: ["Multiply: add the indices, {{x^5 * x^3 = x^8}}.", "Divide: subtract the indices, {{x^8 / x^2 = x^6}}."],
          commonError: "Multiplying the indices ({{x^15}}) instead of adding them.",
          traps: [
            { spec: { type: "expression", expr: "x^13" }, feedback: "When you multiply powers of the same base, *add* the indices: 5 + 3 = 8, not 5 × 3 = 15." },
            { spec: { type: "expression", expr: "x^4" }, feedback: "When you divide, subtract the indices: 8 − 2 = 6, not 8 ÷ 2." },
          ],
          difficulty: "warmup",
          guideRef: "index-laws",
          hints: ["Same base, multiplying → add the indices. Dividing → subtract."],
          strategy: "Use the index laws",
        },
        {
          kind: "short",
          id: "indices-surds-p1-q02",
          question: "Without a calculator, find the value of {{125^(2/3)}}.",
          answer: { type: "number", value: 25 },
          solution: ["The denominator 3 means cube root: {{cbrt(125) = 5}}.", "The numerator 2 means square: {{5^2 = 25}}."],
          commonError: "Working out {{125 * 2/3}} instead of using roots and powers.",
          traps: [{ spec: { type: "number", value: 5 }, feedback: "That's the cube root — the 2 on top of the index means you square it as well." }],
          difficulty: "warmup",
          guideRef: "negative-fractional-indices",
          hints: ["The bottom of the index is the root, the top is the power.", "Cube root of 125 first."],
          strategy: "Root first, then power",
        },
        {
          kind: "short",
          id: "indices-surds-p1-q03",
          question: "Write {{4.06 * 10^5}} as an ordinary number.",
          answer: { type: "number", value: 406000, display: "406 000" },
          solution: ["{{10^5}} means move the decimal point 5 places to the right.", "4.06 → 406 000."],
          traps: [{ spec: { type: "number", value: 40600 }, feedback: "Count again: 4.06 needs the point to move 5 places → 406 000." }],
          difficulty: "warmup",
          guideRef: "standard-form",
          hints: ["Multiplying by {{10^5}} moves every digit 5 places to the left (or the point 5 places right)."],
          strategy: "Estimate first",
        },
        {
          kind: "short",
          id: "indices-surds-p1-q04",
          question: "{{sqrt(48)}} can be written in the form {{k sqrt(3)}}, where k is an integer. Find the value of k.",
          answer: { type: "number", value: 4 },
          solution: ["The largest square factor of 48 is 16.", "{{sqrt(48) = sqrt(16 * 3) = sqrt(16) * sqrt(3) = 4sqrt(3)}}.", "k = 4."],
          commonError: "Using a smaller square factor: {{sqrt(48) = 2sqrt(12)}} is true but not fully simplified.",
          traps: [{ spec: { type: "number", value: 16 }, feedback: "16 is the square factor — you need its square root: {{sqrt(16) = 4}}." }],
          difficulty: "warmup",
          guideRef: "simplifying-surds",
          hints: ["Which square number divides into 48? Choose the largest one.", "{{48 = 16 * 3}}."],
          strategy: "Find a square factor",
        },
        {
          kind: "short",
          id: "indices-surds-p1-q05",
          question: "Simplify fully {{(3x^2 y)^3 ÷ 9xy}}.",
          answer: { type: "expression", expr: "3x^5y^2", form: "simplified", display: "{{3x^5 y^2}}" },
          solution: [
            "{{(3x^2 y)^3 = 27x^6 y^3}} (cube the 3, multiply each index by 3).",
            "Divide the numbers: 27 ÷ 9 = 3.",
            "Subtract indices: {{x^(6-1) = x^5}}, {{y^(3-1) = y^2}}.",
            "Answer: {{3x^5 y^2}}.",
          ],
          commonError: "Writing {{(3x^2 y)^3 = 9x^6 y^3}} — the 3 must be cubed, giving 27.",
          traps: [
            { spec: { type: "expression", expr: "x^5y^2" }, feedback: "Check the number: {{3^3 = 27}}, and 27 ÷ 9 = 3." },
            { spec: { type: "expression", expr: "3x^4y^2" }, feedback: "{{(x^2)^3 = x^6}} (multiply indices), then {{x^6 / x = x^5}}." },
          ],
          difficulty: "core",
          guideRef: "index-laws",
          hints: [
            "Expand the bracket first: what is {{(3x^2 y)^3}}?",
            "{{3^3 = 27}} and {{(x^2)^3 = x^6}}.",
            "Now divide {{27x^6 y^3}} by {{9xy}}: numbers divide, indices subtract.",
          ],
          strategy: "Break it into parts",
        },
        {
          kind: "written",
          id: "indices-surds-p1-q06",
          question:
            "Jun writes: \"{{2^3 * 4^2 = 8^5}}, because you multiply the bases and add the powers.\"\n\nExplain why Jun is wrong, and write {{2^3 * 4^2}} as a single power of 2.",
          marks: 3,
          modelAnswer:
            "The index law {{a^m * a^n = a^(m+n)}} only works when the bases are the **same**. Here the bases are 2 and 4, so Jun can't add the powers, and he certainly can't multiply the bases.\n\nWrite 4 as {{2^2}}: {{4^2 = (2^2)^2 = 2^4}}.\n\nThen {{2^3 * 2^4 = 2^7}} (= 128). Jun's answer {{8^5 = 2^15}} is far too big.",
          markScheme: [
            { point: "States the index law only applies when the bases are the same", keywords: ["same base", "different bases", "bases are different", "same"] },
            { point: "Writes 4² as 2⁴ (or 4 = 2²)", keywords: ["2^4", "2^2", "2⁴", "2²", "16"] },
            { point: "Correct answer 2⁷ (= 128)", keywords: ["2^7", "2⁷", "128"] },
          ],
          commonError: "Saying only \"you can't do that\" without rewriting 4 as a power of 2.",
          difficulty: "core",
          guideRef: "index-laws",
          hints: [
            "When does {{a^m * a^n = a^(m+n)}} work? Check Jun's bases.",
            "Can you write 4 as a power of 2?",
            "{{4^2 = (2^2)^2}}. Now both terms have base 2.",
          ],
          strategy: "Spot the error",
        },
        {
          kind: "short",
          id: "indices-surds-p1-q07",
          question: "Without a calculator, work out {{(16/81)^(-3/4)}}. Give your answer as a fraction in its simplest form.",
          answer: { type: "fraction", n: 27, d: 8, simplest: true },
          solution: [
            "Flip for the negative index: {{(81/16)^(3/4)}}.",
            "Fourth root: {{(81/16)^(1/4) = 3/2}} (since {{3^4 = 81}} and {{2^4 = 16}}).",
            "Cube: {{(3/2)^3 = 27/8}}.",
          ],
          commonError: "Forgetting to flip, giving {{8/27}}.",
          traps: [
            { spec: { type: "fraction", n: 8, d: 27 }, feedback: "That's {{(16/81)^(3/4)}}. The negative index means take the reciprocal as well." },
            { spec: { type: "fraction", n: 9, d: 4 }, feedback: "The index is {{3/4}}: fourth root, then *cube* — not square." },
          ],
          difficulty: "core",
          guideRef: "negative-fractional-indices",
          hints: [
            "Three operations: reciprocal, a root, a power. Which root does the 4 give?",
            "Flip first: {{(81/16)^(3/4)}}.",
            "{{81 = 3^4}} and {{16 = 2^4}}, so the fourth root is {{3/2}}. Now cube it.",
          ],
          strategy: "Root first, then power",
        },
        {
          kind: "short",
          id: "indices-surds-p1-q08",
          question: "{{1/(x sqrt(x))}} can be written as {{x^n}}. Find the value of n.",
          answer: { type: "fraction", n: -3, d: 2, allowDecimal: true, display: "{{-3/2}}" },
          solution: [
            "{{sqrt(x) = x^(1/2)}}, so {{x sqrt(x) = x^1 * x^(1/2) = x^(3/2)}}.",
            "Reciprocal → negative index: {{1/x^(3/2) = x^(-3/2)}}.",
            "{{n = -3/2}}.",
          ],
          commonError: "Writing {{x sqrt(x) = x^(1/2)}} and forgetting the extra x, or forgetting the minus sign for the reciprocal.",
          traps: [
            { spec: { type: "fraction", n: 3, d: 2 }, feedback: "That's {{x sqrt(x)}}. It's on the bottom of a fraction, so the index is negative." },
            { spec: { type: "fraction", n: -1, d: 2 }, feedback: "Don't forget the x in front of the root: {{x * x^(1/2) = x^(3/2)}}." },
          ],
          difficulty: "core",
          guideRef: "negative-fractional-indices",
          hints: [
            "Write {{sqrt(x)}} as a power of x.",
            "{{x * x^(1/2)}} — add the indices.",
            "One over a power gives a negative index.",
          ],
          strategy: "Write everything as a power",
        },
        {
          kind: "short",
          id: "indices-surds-p1-q09",
          question:
            "Light travels at {{3.0 * 10^8}} m/s. The distance from the Earth to the Sun is {{1.5 * 10^11}} m.\n\nWork out the time it takes light to travel from the Sun to the Earth. Give your answer in **minutes**, correct to 3 significant figures.",
          answer: { type: "number", value: 8.33, tolerance: 0.005, display: "8.33 minutes" },
          solution: [
            "Time = distance ÷ speed = {{(1.5 * 10^11)/(3.0 * 10^8)}}.",
            "1.5 ÷ 3.0 = 0.5 and {{10^11 / 10^8 = 10^3}}, so the time is {{0.5 * 10^3 = 500}} seconds.",
            "500 ÷ 60 = 8.333… minutes = 8.33 minutes (3 s.f.).",
          ],
          commonError: "Giving 500 (the answer in seconds) or dividing the wrong way round.",
          traps: [
            { spec: { type: "number", value: 500 }, feedback: "500 is the time in seconds. The question asks for minutes." },
            { spec: { type: "number", value: 0.002 }, feedback: "Time = distance ÷ speed — you've divided the speed by the distance." },
          ],
          difficulty: "core",
          guideRef: "standard-form",
          hints: [
            "Which formula links distance, speed and time?",
            "Time = distance ÷ speed. Divide the numbers and subtract the powers of 10.",
            "You get 500 seconds — now convert to minutes.",
          ],
          strategy: "Check the units",
        },
        {
          kind: "short",
          id: "indices-surds-p1-q10",
          question: "Solve {{4^x = 8^(x-1)}}.",
          answer: { type: "number", value: 3 },
          solution: [
            "Write both sides as powers of 2: {{4^x = 2^(2x)}} and {{8^(x-1) = 2^(3(x-1)) = 2^(3x-3)}}.",
            "Same base, so the indices are equal: 2x = 3x − 3.",
            "x = 3.",
          ],
          solutions: [
            { label: "Check by substituting", steps: ["{{4^3 = 64}}.", "{{8^(3-1) = 8^2 = 64}}. ✓"] },
          ],
          commonError: "Writing {{8^(x-1) = 2^(3x-1)}} — the 3 multiplies the whole of (x − 1).",
          traps: [{ spec: { type: "number", value: 1 }, feedback: "Check {{(2^3)^(x-1) = 2^(3x-3)}}: the 3 multiplies both x and −1." }],
          difficulty: "core",
          guideRef: "index-equations",
          hints: [
            "4 and 8 are both powers of which number?",
            "{{4 = 2^2}} and {{8 = 2^3}}. Rewrite each side.",
            "When {{2^a = 2^b}}, a = b. Solve the linear equation.",
          ],
          strategy: "Write with the same base",
        },
        {
          kind: "written",
          id: "indices-surds-p1-q11",
          question: "Show that {{(5 + sqrt(2))^2 - (5 - sqrt(2))^2 = 20sqrt(2)}}.",
          marks: 3,
          modelAnswer:
            "{{(5 + sqrt(2))^2 = 25 + 10sqrt(2) + 2 = 27 + 10sqrt(2)}}\n\n{{(5 - sqrt(2))^2 = 25 - 10sqrt(2) + 2 = 27 - 10sqrt(2)}}\n\nSubtract: {{(27 + 10sqrt(2)) - (27 - 10sqrt(2)) = 20sqrt(2)}}, as required.\n\n(Or use the difference of two squares: {{(A + B)(A - B)}} with A = {{5 + sqrt(2)}}, B = {{5 - sqrt(2)}} gives {{10 * 2sqrt(2) = 20sqrt(2)}}.)",
          markScheme: [
            { point: "Correct expansion of (5 + √2)² = 27 + 10√2 (or 25 + 10√2 + 2)", keywords: ["27 + 10√2", "27+10sqrt(2)", "25", "10√2", "10sqrt(2)"] },
            { point: "Correct expansion of (5 − √2)² = 27 − 10√2", keywords: ["27 - 10√2", "27 − 10√2", "27-10sqrt(2)"] },
            { point: "Subtracts correctly to reach 20√2 (or difference of two squares: 10 × 2√2)", keywords: ["20√2", "20sqrt(2)", "10 × 2√2", "difference of two squares"] },
          ],
          commonError: "Writing {{(5 + sqrt(2))^2 = 25 + 2}} — forgetting the middle term {{10sqrt(2)}}.",
          solutions: [
            { label: "Expand both", steps: ["{{27 + 10sqrt(2)}} and {{27 - 10sqrt(2)}}.", "Subtract: {{20sqrt(2)}}."] },
            { label: "Difference of two squares (quicker)", steps: ["{{A^2 - B^2 = (A + B)(A - B)}}.", "A + B = 10, A − B = {{2sqrt(2)}}.", "Product: {{20sqrt(2)}}."] },
          ],
          difficulty: "core",
          guideRef: "surd-brackets",
          hints: [
            "Write each square as two brackets and expand. Watch for the middle term.",
            "{{(5 + sqrt(2))^2 = 25 + 5sqrt(2) + 5sqrt(2) + 2}}.",
            "Or: is the left-hand side a difference of two squares?",
          ],
          strategy: "Two ways",
        },
        {
          kind: "short",
          id: "indices-surds-p1-q12",
          question: "{{sqrt(8) + sqrt(18) + sqrt(32) = sqrt(n)}}, where n is an integer. Find the value of n.",
          answer: { type: "number", value: 162 },
          solution: [
            "Simplify each surd: {{sqrt(8) = 2sqrt(2)}}, {{sqrt(18) = 3sqrt(2)}}, {{sqrt(32) = 4sqrt(2)}}.",
            "Sum: {{9sqrt(2)}}.",
            "Put the 9 back inside the root: {{9sqrt(2) = sqrt(81) * sqrt(2) = sqrt(162)}}.",
            "n = 162.",
          ],
          commonError: "Adding under the roots: 8 + 18 + 32 = 58, so {{sqrt(58)}}.",
          traps: [
            { spec: { type: "number", value: 58 }, feedback: "{{sqrt(a) + sqrt(b) != sqrt(a + b)}}. Simplify each surd into a multiple of {{sqrt(2)}} first." },
            { spec: { type: "number", value: 18 }, feedback: "{{9sqrt(2)}} is not {{sqrt(18)}} — the 9 must be squared when it goes inside: {{sqrt(81 * 2)}}." },
          ],
          difficulty: "challenge",
          guideRef: "simplifying-surds",
          hints: [
            "Can you write all three surds as multiples of the same surd?",
            "Each one is a multiple of {{sqrt(2)}}.",
            "You get {{9sqrt(2)}}. To write it as one root, the 9 goes inside as {{9^2}}.",
          ],
          strategy: "Work backwards",
        },
        {
          kind: "short",
          id: "indices-surds-p1-q13",
          question:
            "Rationalise the denominator of {{5/(2 + sqrt(3))}}.\n\nGive your answer in the form {{a + b sqrt(3)}}, where a and b are integers. Enter a, then b.",
          answer: { type: "list", values: [10, -5], ordered: true, display: "a = 10, b = −5 (so {{10 - 5sqrt(3)}})" },
          solution: [
            "Multiply top and bottom by the conjugate {{2 - sqrt(3)}}.",
            "Denominator: {{(2 + sqrt(3))(2 - sqrt(3)) = 4 - 3 = 1}}.",
            "Numerator: {{5(2 - sqrt(3)) = 10 - 5sqrt(3)}}.",
            "So a = 10, b = −5.",
          ],
          commonError: "Multiplying by {{sqrt(3)}} only — that leaves a surd in the denominator.",
          traps: [
            { spec: { type: "list", values: [10, 5], ordered: true }, feedback: "Check the sign: the conjugate is {{2 - sqrt(3)}}, so b is negative." },
            { spec: { type: "list", values: [-10, 5], ordered: true }, feedback: "{{(2 + sqrt(3))(2 - sqrt(3)) = 4 - 3 = +1}}, not −1." },
          ],
          difficulty: "core",
          guideRef: "rationalising",
          hints: [
            "Which bracket, multiplied by {{2 + sqrt(3)}}, gives a whole number?",
            "The conjugate is {{2 - sqrt(3)}}. Use the difference of two squares on the bottom.",
            "The denominator is {{4 - 3 = 1}}, so the answer is just {{5(2 - sqrt(3))}}.",
          ],
          strategy: "Use the conjugate",
        },
        {
          kind: "short",
          id: "indices-surds-p1-q14",
          question: "Solve {{2^(2x) - 6 * 2^x + 8 = 0}}.\n\nGive both values of x.",
          answer: { type: "list", values: [1, 2], ordered: false, display: "x = 1 or x = 2" },
          solution: [
            "Notice {{2^(2x) = (2^x)^2}}. Let {{y = 2^x}}.",
            "The equation becomes {{y^2 - 6y + 8 = 0}}, so (y − 2)(y − 4) = 0.",
            "y = 2 or y = 4.",
            "{{2^x = 2}} gives x = 1; {{2^x = 4}} gives x = 2.",
          ],
          commonError: "Stopping at y = 2 and y = 4 — those are values of {{2^x}}, not of x.",
          traps: [{ spec: { type: "list", values: [2, 4], ordered: false }, feedback: "Those are the values of {{y = 2^x}}. Now solve {{2^x = 2}} and {{2^x = 4}}." }],
          difficulty: "challenge",
          guideRef: "harder-index-equations",
          hints: [
            "What is {{2^(2x)}} in terms of {{2^x}}?",
            "{{2^(2x) = (2^x)^2}}. Try substituting {{y = 2^x}}.",
            "Solve the quadratic in y, then turn each y back into x.",
          ],
          strategy: "Introduce a variable",
        },
        {
          kind: "written",
          id: "indices-surds-p1-q15",
          question:
            "Prove that {{1/(sqrt(2) + 1) + 1/(sqrt(3) + sqrt(2)) + 1/(sqrt(4) + sqrt(3)) = 1}}.",
          marks: 4,
          modelAnswer:
            "Rationalise each fraction using its conjugate. For example\n\n    {{1/(sqrt(2) + 1) = (sqrt(2) - 1)/((sqrt(2) + 1)(sqrt(2) - 1)) = (sqrt(2) - 1)/(2 - 1) = sqrt(2) - 1}}\n\nIn the same way {{1/(sqrt(3) + sqrt(2)) = sqrt(3) - sqrt(2)}} and {{1/(sqrt(4) + sqrt(3)) = sqrt(4) - sqrt(3)}} (each denominator becomes 1).\n\nAdding: {{(sqrt(2) - 1) + (sqrt(3) - sqrt(2)) + (sqrt(4) - sqrt(3))}}. The {{sqrt(2)}} and {{sqrt(3)}} terms cancel, leaving {{sqrt(4) - 1 = 2 - 1 = 1}}.",
          markScheme: [
            { point: "Multiplies a fraction by its conjugate (e.g. √2 − 1)", keywords: ["conjugate", "√2 - 1", "√2 − 1", "sqrt(2) - 1", "rationalise"] },
            { point: "Shows each denominator becomes 1 (difference of two squares)", keywords: ["2 - 1", "3 - 2", "4 - 3", "= 1", "difference of two squares"] },
            { point: "Writes the sum as (√2 − 1) + (√3 − √2) + (√4 − √3)", keywords: ["√3 - √2", "√4 - √3", "sqrt(3) - sqrt(2)", "sqrt(4) - sqrt(3)"] },
            { point: "Cancels the middle terms to get √4 − 1 = 1", keywords: ["cancel", "2 - 1", "√4 - 1", "telescop"] },
          ],
          commonError: "Trying to add the fractions over a common denominator — it becomes a huge mess. Rationalise each one first.",
          difficulty: "challenge",
          guideRef: "rationalising",
          hints: [
            "Adding these directly looks awful. Can you make each fraction simpler first?",
            "Rationalise {{1/(sqrt(2) + 1)}}. What's special about the denominator you get?",
            "Each fraction becomes a difference like {{sqrt(3) - sqrt(2)}}. Write all three out and look for cancelling.",
          ],
          strategy: "Make it simpler, then look for cancelling",
        },
      ],
    },
    {
      id: "indices-surds-p2",
      title: "Practice Paper 2",
      questions: [
        {
          kind: "short",
          id: "indices-surds-p2-q01",
          question: "Simplify {{(2p^3)^2 * p}}.",
          answer: { type: "expression", expr: "4p^7", form: "simplified", display: "{{4p^7}}" },
          solution: ["{{(2p^3)^2 = 4p^6}}.", "{{4p^6 * p^1 = 4p^7}}."],
          commonError: "Writing {{2p^6}} — forgetting to square the 2.",
          traps: [
            { spec: { type: "expression", expr: "2p^7" }, feedback: "The 2 is inside the bracket, so it gets squared too: {{2^2 = 4}}." },
            { spec: { type: "expression", expr: "4p^6" }, feedback: "Don't forget the final p: {{p^6 * p = p^7}}." },
          ],
          difficulty: "warmup",
          guideRef: "index-laws",
          hints: ["Square everything in the bracket first, then multiply by p (which is {{p^1}})."],
          strategy: "Use the index laws",
        },
        {
          kind: "short",
          id: "indices-surds-p2-q02",
          question: "Write {{2^(-3)}} as a fraction.",
          answer: { type: "fraction", n: 1, d: 8 },
          solution: ["A negative index means reciprocal: {{2^(-3) = 1/2^3}}.", "{{2^3 = 8}}, so {{2^(-3) = 1/8}}."],
          commonError: "Writing −8 or −6: a negative index does not make the number negative.",
          traps: [
            { spec: { type: "number", value: -8 }, feedback: "A negative index means *one over*, not a negative number: {{1/2^3}}." },
            { spec: { type: "number", value: -6 }, feedback: "{{2^(-3)}} is not 2 × (−3). It means {{1/2^3}}." },
          ],
          difficulty: "warmup",
          guideRef: "negative-fractional-indices",
          hints: ["What does a negative index tell you to do?"],
          strategy: "Use the index laws",
        },
        {
          kind: "short",
          id: "indices-surds-p2-q03",
          question: "Work out {{(3.2 * 10^4) ÷ (8 * 10^(-3))}}. Give your answer in standard form.",
          answer: { type: "number", value: 4000000, standardForm: true, display: "{{4 * 10^6}}" },
          solution: [
            "Divide the numbers: 3.2 ÷ 8 = 0.4.",
            "Subtract the powers: {{10^4 / 10^(-3) = 10^(4-(-3)) = 10^7}}.",
            "{{0.4 * 10^7 = 4 * 10^6}}.",
          ],
          commonError: "Working out 4 − 3 = 1 instead of 4 − (−3) = 7.",
          traps: [
            { spec: { type: "number", value: 4 }, feedback: "{{10^4 ÷ 10^(-3)}}: subtract the indices, 4 − (−3) = 7." },
            { spec: { type: "number", value: 40000000 }, feedback: "0.4 is not between 1 and 10. {{0.4 = 4 * 10^(-1)}}, so the power goes *down* by one." },
          ],
          difficulty: "warmup",
          guideRef: "standard-form",
          hints: ["Divide the numbers and subtract the powers of 10 separately.", "Watch the double negative: 4 − (−3)."],
          strategy: "Break it into parts",
        },
        {
          kind: "short",
          id: "indices-surds-p2-q04",
          question: "Work out {{sqrt(5) * sqrt(20)}}.",
          answer: { type: "number", value: 10 },
          solution: ["{{sqrt(a) * sqrt(b) = sqrt(ab)}}.", "{{sqrt(5 * 20) = sqrt(100) = 10}}."],
          traps: [{ spec: { type: "expression", expr: "sqrt(25)" }, feedback: "You've added 5 + 20. Surds *multiply* under the root: 5 × 20 = 100." }],
          difficulty: "warmup",
          guideRef: "simplifying-surds",
          hints: ["{{sqrt(a) * sqrt(b) = sqrt(ab)}}."],
          strategy: "Use a surd rule",
        },
        {
          kind: "short",
          id: "indices-surds-p2-q05",
          question: "Simplify fully {{(12a^5 b^(-2))/(4a^(-1) b^3)}}.",
          answer: { type: "expression", expr: "3a^6b^(-5)", form: "simplified", display: "{{3a^6 b^(-5)}} or {{(3a^6)/b^5}}" },
          solution: [
            "Numbers: 12 ÷ 4 = 3.",
            "a: {{a^(5-(-1)) = a^6}}.",
            "b: {{b^(-2-3) = b^(-5)}}.",
            "Answer {{3a^6 b^(-5)}}, which can also be written {{(3a^6)/b^5}}.",
          ],
          commonError: "Subtracting the a-indices as 5 − 1 = 4 (losing the negative sign).",
          traps: [
            { spec: { type: "expression", expr: "3a^4b^(-5)" }, feedback: "a: 5 − (−1) = 6, not 4. Subtracting a negative adds." },
            { spec: { type: "expression", expr: "3a^6b^(-1)" }, feedback: "b: −2 − 3 = −5. Check the b index again." },
          ],
          difficulty: "core",
          guideRef: "index-laws",
          hints: [
            "Deal with numbers, a's and b's separately.",
            "For each letter, subtract the bottom index from the top index.",
            "Careful: 5 − (−1) = 6 and −2 − 3 = −5.",
          ],
          strategy: "Break it into parts",
        },
        {
          kind: "short",
          id: "indices-surds-p2-q06",
          question: "Without a calculator, work out {{27^(-2/3) * 9^(1/2)}}. Give your answer as a fraction.",
          answer: { type: "fraction", n: 1, d: 3 },
          solution: [
            "{{27^(-2/3) = 1/27^(2/3) = 1/(cbrt(27))^2 = 1/9}}.",
            "{{9^(1/2) = 3}}.",
            "{{1/9 * 3 = 1/3}}.",
          ],
          solutions: [
            { label: "Everything as a power of 3", steps: ["{{27^(-2/3) = (3^3)^(-2/3) = 3^(-2)}}.", "{{9^(1/2) = (3^2)^(1/2) = 3^1}}.", "{{3^(-2) * 3^1 = 3^(-1) = 1/3}}."] },
          ],
          commonError: "Treating {{27^(-2/3)}} as −9.",
          traps: [
            { spec: { type: "number", value: -27 }, feedback: "A negative index gives a reciprocal, not a negative number: {{27^(-2/3) = 1/9}}." },
            { spec: { type: "number", value: 27 }, feedback: "{{27^(-2/3)}} is {{1/9}}, not 9. You've lost the reciprocal." },
          ],
          difficulty: "core",
          guideRef: "negative-fractional-indices",
          hints: [
            "Work out each part separately.",
            "{{27^(-2/3)}}: cube root, square, then reciprocal.",
            "Or write both as powers of 3 and add the indices.",
          ],
          strategy: "Write with the same base",
        },
        {
          kind: "written",
          id: "indices-surds-p2-q07",
          question: "Show that {{(8^(2/3) * 16^(-1/4))^2 = 4}}. Show each step of your working clearly.",
          marks: 3,
          modelAnswer:
            "{{8^(2/3) = (cbrt(8))^2 = 2^2 = 4}}.\n\n{{16^(-1/4) = 1/16^(1/4) = 1/2}}.\n\nSo the bracket is {{4 * 1/2 = 2}}, and {{2^2 = 4}}, as required.\n\n(Alternatively, as powers of 2: {{(2^2 * 2^(-1))^2 = (2^1)^2 = 4}}.)",
          markScheme: [
            { point: "8^(2/3) = 4 (cube root 2, squared)", keywords: ["8^(2/3) = 4", "cube root", "2^2", "= 4"] },
            { point: "16^(−1/4) = 1/2 (fourth root 2, reciprocal)", keywords: ["1/2", "0.5", "2^-1", "2^(-1)", "fourth root"] },
            { point: "Combines: 4 × ½ = 2, and 2² = 4", keywords: ["2^2", "4 × 1/2", "= 2", "squared"] },
          ],
          commonError: "Writing {{16^(-1/4) = -2}} — a negative index never makes the answer negative.",
          solutions: [
            { label: "Evaluate each part", steps: ["{{8^(2/3) = 4}}, {{16^(-1/4) = 1/2}}.", "{{(4 * 1/2)^2 = 2^2 = 4}}."] },
            { label: "Powers of 2", steps: ["{{8^(2/3) = 2^2}}, {{16^(-1/4) = 2^(-1)}}.", "{{(2^(2-1))^2 = 2^2 = 4}}."] },
          ],
          difficulty: "core",
          guideRef: "negative-fractional-indices",
          hints: [
            "Work inside the bracket first.",
            "{{8^(2/3)}}: cube root then square. {{16^(-1/4)}}: fourth root then reciprocal.",
            "Multiply the two results, then square.",
          ],
          strategy: "Break it into parts",
        },
        {
          kind: "short",
          id: "indices-surds-p2-q08",
          question:
            "The population of Singapore is about {{5.92 * 10^6}} people. Its land area is about 735 km².\n\nWork out the population density, in people per km². Give your answer in standard form, correct to 3 significant figures.",
          answer: { type: "number", value: 8050, standardForm: true, tolerance: 5, display: "{{8.05 * 10^3}} people per km²" },
          solution: [
            "Density = population ÷ area = {{(5.92 * 10^6) ÷ 735}}.",
            "= 8054.4… people per km².",
            "To 3 s.f. in standard form: {{8.05 * 10^3}}.",
          ],
          commonError: "Dividing area by population (giving a tiny number) or not writing the answer in standard form.",
          traps: [
            { spec: { type: "number", value: 0.000124, tolerance: 0.000001 }, feedback: "That's km² per person. Density here is *people* per km², so divide the population by the area." },
          ],
          difficulty: "core",
          guideRef: "standard-form",
          hints: [
            "Read the units: people per km² means people ÷ km².",
            "Work out {{5.92 * 10^6 ÷ 735}} on your calculator.",
            "Round 8054.4… to 3 s.f. and write it as A × {{10^n}}.",
          ],
          strategy: "Check the units",
        },
        {
          kind: "short",
          id: "indices-surds-p2-q09",
          question:
            "A red blood cell has a diameter of {{8 * 10^(-6)}} m.\n\nHow many red blood cells, placed side by side in a straight line, would stretch across 2 cm?",
          answer: { type: "number", value: 2500 },
          solution: [
            "Convert to the same units: 2 cm = 0.02 m = {{2 * 10^(-2)}} m.",
            "Number = {{(2 * 10^(-2)) ÷ (8 * 10^(-6))}} = {{0.25 * 10^4}} = 2500.",
          ],
          commonError: "Forgetting to convert 2 cm into metres, giving 250 000.",
          traps: [{ spec: { type: "number", value: 250000 }, feedback: "Units! 2 cm = 0.02 m. Convert before dividing." }],
          difficulty: "core",
          guideRef: "standard-form",
          hints: [
            "The two lengths must be in the same unit first.",
            "2 cm = {{2 * 10^(-2)}} m.",
            "Divide: numbers then powers of 10.",
          ],
          strategy: "Check the units",
        },
        {
          kind: "short",
          id: "indices-surds-p2-q10",
          question: "Solve {{9^(x+1) = 27^(2x)}}.",
          answer: { type: "fraction", n: 1, d: 2, allowDecimal: true, display: "{{x = 1/2}}" },
          solution: [
            "Write both sides as powers of 3: {{9^(x+1) = 3^(2x+2)}} and {{27^(2x) = 3^(6x)}}.",
            "Equate indices: 2x + 2 = 6x.",
            "4x = 2, so {{x = 1/2}}.",
          ],
          solutions: [{ label: "Check", steps: ["{{9^(3/2) = 27}}.", "{{27^1 = 27}}. ✓"] }],
          commonError: "Writing {{9^(x+1) = 3^(2x+1)}} — the 2 multiplies the whole bracket.",
          traps: [{ spec: { type: "fraction", n: 1, d: 4 }, feedback: "Check {{(3^2)^(x+1) = 3^(2x+2)}}, not {{3^(2x+1)}}." }],
          difficulty: "core",
          guideRef: "index-equations",
          hints: [
            "9 and 27 are both powers of 3.",
            "{{9^(x+1) = (3^2)^(x+1)}} — multiply out the index carefully.",
            "Set the indices equal: 2x + 2 = 6x.",
          ],
          strategy: "Write with the same base",
        },
        {
          kind: "short",
          id: "indices-surds-p2-q11",
          question: "Solve {{4x^(-3/2) = 1/2}}.",
          answer: { type: "number", value: 4 },
          solution: [
            "Divide by 4: {{x^(-3/2) = 1/8}}.",
            "Take reciprocals: {{x^(3/2) = 8}}.",
            "Raise both sides to the power {{2/3}}: {{x = 8^(2/3) = (cbrt(8))^2 = 4}}.",
          ],
          solutions: [{ label: "Check", steps: ["{{4^(-3/2) = 1/(sqrt(4))^3 = 1/8}}.", "{{4 * 1/8 = 1/2}}. ✓"] }],
          commonError: "Raising to the power {{-3/2}} instead of the inverse power {{-2/3}}, or forgetting to divide by 4 first.",
          traps: [
            { spec: { type: "fraction", n: 1, d: 4 }, feedback: "Check the sign: {{x^(3/2) = 8}}, so x is bigger than 1. Did you lose the reciprocal?" },
            { spec: { type: "number", value: 64 }, feedback: "{{x^(3/2) = 8}} is undone by the power {{2/3}} (cube root, then square): {{8^(2/3) = 4}}. Squaring 8 is not the inverse." },
          ],
          difficulty: "challenge",
          guideRef: "harder-index-equations",
          hints: [
            "Get {{x^(-3/2)}} on its own first.",
            "{{x^(-3/2) = 1/8}} means {{x^(3/2) = 8}}.",
            "To undo the power {{3/2}}, raise both sides to the power {{2/3}}.",
          ],
          strategy: "Use the inverse",
        },
        {
          kind: "short",
          id: "indices-surds-p2-q12",
          question: "Expand and simplify {{(2sqrt(3) - 1)^2}}. Give your answer in the form {{a + b sqrt(3)}}.",
          answer: { type: "expression", expr: "13-4sqrt(3)", form: "surd", display: "{{13 - 4sqrt(3)}}" },
          solution: [
            "{{(2sqrt(3) - 1)(2sqrt(3) - 1)}}.",
            "{{(2sqrt(3))^2 = 4 * 3 = 12}}; middle terms {{-2sqrt(3) - 2sqrt(3) = -4sqrt(3)}}; last term +1.",
            "{{12 - 4sqrt(3) + 1 = 13 - 4sqrt(3)}}.",
          ],
          commonError: "Writing {{(2sqrt(3))^2 = 6}} — the 2 must be squared too: 4 × 3 = 12.",
          traps: [
            { spec: { type: "expression", expr: "7-4sqrt(3)" }, feedback: "{{(2sqrt(3))^2 = 2^2 * (sqrt(3))^2 = 12}}, not 6." },
            { spec: { type: "expression", expr: "13" }, feedback: "{{(a - b)^2 != a^2 + b^2}}: don't forget the middle terms, {{-4sqrt(3)}}." },
          ],
          difficulty: "core",
          guideRef: "surd-brackets",
          hints: [
            "Write it as two brackets.",
            "What is {{2sqrt(3) * 2sqrt(3)}}? Square the 2 and the {{sqrt(3)}}.",
            "There are two middle terms, each {{-2sqrt(3)}}.",
          ],
          strategy: "Grid method",
        },
        {
          kind: "written",
          id: "indices-surds-p2-q13",
          question:
            "A rectangle has length {{(3 + sqrt(5))}} cm and width {{(3 - sqrt(5))}} cm.\n\nShow that the length of a diagonal of the rectangle is {{2sqrt(7)}} cm.",
          marks: 3,
          modelAnswer:
            "By Pythagoras, {{d^2 = (3 + sqrt(5))^2 + (3 - sqrt(5))^2}}.\n\n{{(3 + sqrt(5))^2 = 9 + 6sqrt(5) + 5 = 14 + 6sqrt(5)}} and {{(3 - sqrt(5))^2 = 14 - 6sqrt(5)}}.\n\nSo {{d^2 = 28}} and {{d = sqrt(28) = sqrt(4 * 7) = 2sqrt(7)}} cm.",
          markScheme: [
            { point: "Uses Pythagoras: d² = (3 + √5)² + (3 − √5)²", keywords: ["pythagoras", "d^2", "d²", "+ (3 - √5)"] },
            { point: "Expands correctly to 14 + 6√5 and 14 − 6√5 (sum 28)", keywords: ["14", "6√5", "6sqrt(5)", "28"] },
            { point: "Simplifies √28 = √4 × √7 = 2√7", keywords: ["√28", "sqrt(28)", "4 × 7", "2√7", "2sqrt(7)"] },
          ],
          commonError: "Multiplying the length and width (that's the area, 4 cm²) instead of using Pythagoras.",
          difficulty: "core",
          guideRef: "surd-brackets",
          hints: [
            "The diagonal is the hypotenuse of a right-angled triangle.",
            "Square each side: expand {{(3 + sqrt(5))^2}} and {{(3 - sqrt(5))^2}}.",
            "The {{sqrt(5)}} terms cancel. Simplify {{sqrt(28)}}.",
          ],
          strategy: "Draw a diagram",
        },
        {
          kind: "short",
          id: "indices-surds-p2-q14",
          question:
            "Rationalise the denominator of {{(sqrt(5) + 1)/(sqrt(5) - 1)}}. Give your answer in the form {{(a + sqrt(b))/c}}, where a, b and c are integers.",
          answer: { type: "expression", expr: "(3+sqrt(5))/2", form: "surd", display: "{{(3 + sqrt(5))/2}}" },
          solution: [
            "Multiply top and bottom by the conjugate {{sqrt(5) + 1}}.",
            "Denominator: {{(sqrt(5) - 1)(sqrt(5) + 1) = 5 - 1 = 4}}.",
            "Numerator: {{(sqrt(5) + 1)^2 = 5 + 2sqrt(5) + 1 = 6 + 2sqrt(5)}}.",
            "{{(6 + 2sqrt(5))/4 = (3 + sqrt(5))/2}} (divide every term by 2).",
          ],
          commonError: "Multiplying the numerator by {{sqrt(5) + 1}} but forgetting the middle terms when squaring it.",
          traps: [
            { spec: { type: "expression", expr: "6/4" }, feedback: "{{(sqrt(5) + 1)^2}} has a middle term: {{2sqrt(5)}}. Don't drop it." },
            { spec: { type: "expression", expr: "(6+2sqrt(5))/6" }, feedback: "The denominator is {{5 - 1 = 4}} (difference of two squares), not 6." },
          ],
          difficulty: "challenge",
          guideRef: "rationalising",
          hints: [
            "What do you multiply {{sqrt(5) - 1}} by to make a whole number?",
            "Multiply top and bottom by {{sqrt(5) + 1}}. The bottom becomes 4.",
            "Expand {{(sqrt(5) + 1)^2}} carefully, then divide everything by the common factor 2.",
          ],
          strategy: "Use the conjugate",
        },
        {
          kind: "written",
          id: "indices-surds-p2-q15",
          question: "Solve {{3^(2x+1) - 28 * 3^x + 9 = 0}}. Show clear algebraic working.",
          marks: 4,
          modelAnswer:
            "{{3^(2x+1) = 3 * 3^(2x) = 3(3^x)^2}}. Let {{y = 3^x}}.\n\nThen {{3y^2 - 28y + 9 = 0}}, which factorises as (3y − 1)(y − 9) = 0.\n\nSo {{y = 1/3}} or y = 9.\n\n{{3^x = 1/3 = 3^(-1)}} gives x = −1; {{3^x = 9 = 3^2}} gives x = 2.\n\nx = −1 or x = 2.",
          markScheme: [
            { point: "Writes 3^(2x+1) as 3(3^x)² and substitutes y = 3^x", keywords: ["y = 3^x", "3y^2", "3y²", "(3^x)^2", "let"] },
            { point: "Forms and factorises 3y² − 28y + 9 = 0 → (3y − 1)(y − 9)", keywords: ["3y - 1", "3y − 1", "y - 9", "y − 9", "factor"] },
            { point: "Finds y = 1/3 and y = 9", keywords: ["1/3", "y = 9", "9"] },
            { point: "Converts to x = −1 and x = 2", keywords: ["x = -1", "x = −1", "x = 2", "-1", "−1"] },
          ],
          commonError: "Writing {{3^(2x+1) = (3^x)^2 + 3}} or treating it as {{y^2}} without the factor 3.",
          difficulty: "challenge",
          guideRef: "harder-index-equations",
          hints: [
            "Can you write {{3^(2x+1)}} using {{3^x}}?",
            "{{3^(2x+1) = 3^1 * 3^(2x) = 3(3^x)^2}}. Let {{y = 3^x}}.",
            "Solve {{3y^2 - 28y + 9 = 0}}, then convert each y back to x.",
          ],
          strategy: "Introduce a variable",
        },
      ],
    },
  ],

  // =========================================================================
  // CHALLENGE SET — grade 9 / H+ / olympiad flavour
  // =========================================================================
  challenge: [
    {
      kind: "short",
      id: "indices-surds-ch-q01",
      question: "Given that {{3^x = 5}}, find the value of {{9^(x+1)}}.",
      answer: { type: "number", value: 225 },
      solution: [
        "{{9^(x+1) = 9 * 9^x}}.",
        "{{9^x = (3^2)^x = (3^x)^2 = 5^2 = 25}}.",
        "{{9^(x+1) = 9 * 25 = 225}}.",
      ],
      solutions: [
        { label: "Split the index", steps: ["{{9^(x+1) = 9^x * 9}}.", "{{9^x = (3^x)^2 = 25}}.", "225."] },
        { label: "Everything in base 3", steps: ["{{9^(x+1) = 3^(2x+2) = (3^x)^2 * 3^2}}.", "{{= 25 * 9 = 225}}."] },
      ],
      commonError: "Writing {{9^(x+1) = 9^x + 9}} — an index sum gives a *product* of powers.",
      traps: [
        { spec: { type: "number", value: 34 }, feedback: "{{9^(x+1) = 9^x * 9^1}}, a product, not {{9^x + 9}}." },
        { spec: { type: "number", value: 54 }, feedback: "{{9^x = (3^x)^2 = 25}}, not 5 + 1 or 6. Square the 5." },
      ],
      difficulty: "challenge",
      guideRef: "index-laws",
      hints: [
        "You can't find x neatly — so don't try. Write {{9^(x+1)}} in terms of {{3^x}}.",
        "Split the index: {{9^(x+1) = 9^x * 9}}.",
        "{{9^x = (3^2)^x = (3^x)^2}}.",
      ],
      strategy: "Don't solve — substitute",
    },
    {
      kind: "short",
      id: "indices-surds-ch-q02",
      question: "Without a calculator, work out {{(0.0016)^(-3/4)}}.",
      answer: { type: "number", value: 125 },
      solution: [
        "Notice {{0.2^2 = 0.04}} and {{0.2^4 = 0.0016}}.",
        "So {{(0.0016)^(-3/4) = (0.2^4)^(-3/4) = 0.2^(-3)}}.",
        "{{0.2 = 1/5}}, so {{0.2^(-3) = 5^3 = 125}}.",
      ],
      solutions: [
        { label: "As a fraction first", steps: ["{{0.0016 = 16/10000 = 1/625 = 5^(-4)}}.", "{{(5^(-4))^(-3/4) = 5^3 = 125}}."] },
        { label: "Spot the decimal power", steps: ["{{0.0016 = 0.2^4}}.", "{{0.2^(-3) = 1/0.008 = 125}}."] },
      ],
      commonError: "Losing track of the reciprocal and giving 0.008.",
      traps: [{ spec: { type: "number", value: 0.008 }, feedback: "That's {{0.2^3}}. The index is negative, so take the reciprocal: {{1/0.008}}." }],
      difficulty: "challenge",
      guideRef: "negative-fractional-indices",
      hints: [
        "Decimals are awkward with roots. Write 0.0016 as a fraction.",
        "{{0.0016 = 16/10000}}. Simplify — is it a power of a simple fraction?",
        "{{16/10000 = 1/625 = 5^(-4)}}. Now use {{(a^m)^n = a^(mn)}}.",
      ],
      strategy: "Write everything as a power",
    },
    {
      kind: "short",
      id: "indices-surds-ch-q03",
      question: "How many digits does the number {{4^10 * 5^25}} have when written out in full?",
      answer: { type: "number", value: 24 },
      solution: [
        "{{4^10 = 2^20}}.",
        "{{2^20 * 5^25 = 2^20 * 5^20 * 5^5 = 10^20 * 5^5}}.",
        "{{5^5 = 3125}}, so the number is {{3125 * 10^20 = 3.125 * 10^23}}.",
        "A number {{A * 10^23}} with 1 ≤ A < 10 has 24 digits.",
      ],
      solutions: [
        { label: "Pair 2s with 5s", steps: ["Each 2 × 5 makes a 10: twenty 10s.", "{{3125}} followed by twenty zeros: 4 + 20 = 24 digits."] },
        { label: "Standard form", steps: ["{{3.125 * 10^23}}.", "The power 23 means 23 digits after the first one: 24 digits."] },
      ],
      commonError: "Answering 23 — the power of 10 in standard form is one less than the number of digits.",
      traps: [{ spec: { type: "number", value: 23 }, feedback: "{{10^23}} itself is 1 followed by 23 zeros — that's 24 digits." }],
      difficulty: "challenge",
      guideRef: "standard-form",
      hints: [
        "Powers of 10 have easy-to-count digits. Can you make some 10s?",
        "Write {{4^10}} as a power of 2, then pair each 2 with a 5.",
        "You get {{10^20 * 5^5}}. Work out {{5^5}} and count.",
      ],
      strategy: "Make it simpler",
    },
    {
      kind: "short",
      id: "indices-surds-ch-q04",
      question:
        "Solve the simultaneous equations\n\n    {{2^x * 4^y = 32}}\n    {{3^x ÷ 9^y = 1/27}}\n\nGive your answer as (x, y).",
      answer: { type: "list", values: [1, 2], ordered: true, display: "x = 1, y = 2" },
      solution: [
        "First equation in base 2: {{2^x * 2^(2y) = 2^5}}, so x + 2y = 5.",
        "Second in base 3: {{3^x ÷ 3^(2y) = 3^(-3)}}, so x − 2y = −3.",
        "Add: 2x = 2, so x = 1. Then 2y = 4, so y = 2.",
      ],
      solutions: [{ label: "Check", steps: ["{{2^1 * 4^2 = 2 * 16 = 32}}. ✓", "{{3^1 ÷ 9^2 = 3/81 = 1/27}}. ✓"] }],
      commonError: "Writing {{1/27 = 3^3}} — it is {{3^(-3)}}.",
      traps: [{ spec: { type: "list", values: [4, 0.5], ordered: true }, feedback: "Check {{1/27 = 3^(-3)}}, so x − 2y = −3 (not +3)." }],
      difficulty: "challenge",
      guideRef: "index-equations",
      hints: [
        "Turn each equation into a linear equation by using one base per equation.",
        "{{4^y = 2^(2y)}} and {{9^y = 3^(2y)}}.",
        "You should get x + 2y = 5 and x − 2y = −3. Eliminate y.",
      ],
      strategy: "Write with the same base",
    },
    {
      kind: "short",
      id: "indices-surds-ch-q05",
      question: "Solve {{9^x - 10 * 3^x + 9 = 0}}. Give both values of x.",
      answer: { type: "list", values: [0, 2], ordered: false, display: "x = 0 or x = 2" },
      solution: [
        "{{9^x = (3^x)^2}}. Let {{y = 3^x}}.",
        "{{y^2 - 10y + 9 = 0}}, so (y − 1)(y − 9) = 0.",
        "y = 1 gives {{3^x = 1}}, so x = 0. y = 9 gives {{3^x = 9}}, so x = 2.",
      ],
      commonError: "Thinking {{3^x = 1}} has no solution — remember {{3^0 = 1}}.",
      traps: [
        { spec: { type: "list", values: [1, 9], ordered: false }, feedback: "Those are the values of {{3^x}}. Now find x." },
        { spec: { type: "list", values: [2], ordered: false }, feedback: "There's a second solution: {{3^x = 1}} gives x = 0." },
      ],
      difficulty: "challenge",
      guideRef: "harder-index-equations",
      hints: [
        "This is a quadratic in disguise. Which expression is being squared?",
        "{{9^x = (3^x)^2}}. Let {{y = 3^x}}.",
        "Solve {{y^2 - 10y + 9 = 0}}. Don't throw away y = 1.",
      ],
      strategy: "Introduce a variable",
    },
    {
      kind: "short",
      id: "indices-surds-ch-q06",
      question: "Solve {{x^(2/3) - 5x^(1/3) + 4 = 0}}. Give both values of x.",
      answer: { type: "list", values: [1, 64], ordered: false, display: "x = 1 or x = 64" },
      solution: [
        "Let {{u = x^(1/3)}}; then {{x^(2/3) = u^2}}.",
        "{{u^2 - 5u + 4 = 0}}, so (u − 1)(u − 4) = 0, giving u = 1 or u = 4.",
        "{{x = u^3}}: x = 1 or x = 64.",
      ],
      solutions: [
        { label: "Check x = 64", steps: ["{{64^(2/3) = 16}}, {{64^(1/3) = 4}}.", "16 − 20 + 4 = 0. ✓"] },
      ],
      commonError: "Stopping at u = 1 and u = 4, or squaring instead of cubing to get back to x.",
      traps: [
        { spec: { type: "list", values: [1, 4], ordered: false }, feedback: "Those are values of {{x^(1/3)}}. Cube them to get x." },
        { spec: { type: "list", values: [1, 16], ordered: false }, feedback: "{{u = x^(1/3)}} means {{x = u^3}}, so cube 4 (not square it)." },
      ],
      difficulty: "challenge",
      guideRef: "harder-index-equations",
      hints: [
        "How is {{x^(2/3)}} related to {{x^(1/3)}}?",
        "{{x^(2/3) = (x^(1/3))^2}}. Substitute {{u = x^(1/3)}}.",
        "Solve for u, then undo the cube root.",
      ],
      strategy: "Introduce a variable",
    },
    {
      kind: "short",
      id: "indices-surds-ch-q07",
      question:
        "{{sqrt(12 + 2sqrt(35))}} can be written in the form {{sqrt(a) + sqrt(b)}}, where a and b are integers and a > b.\n\nFind a and b. Enter a, then b.",
      answer: { type: "list", values: [7, 5], ordered: true, display: "a = 7, b = 5" },
      solution: [
        "Square the target form: {{(sqrt(a) + sqrt(b))^2 = a + b + 2sqrt(ab)}}.",
        "Match with {{12 + 2sqrt(35)}}: a + b = 12 and ab = 35.",
        "Two numbers with sum 12 and product 35: 7 and 5.",
        "Check: {{(sqrt(7) + sqrt(5))^2 = 7 + 5 + 2sqrt(35)}}. ✓",
      ],
      solutions: [
        { label: "Match coefficients", steps: ["a + b = 12, ab = 35.", "a = 7, b = 5."] },
        { label: "Guess and check with factor pairs of 35", steps: ["35 = 1 × 35 or 5 × 7.", "Only 5 + 7 = 12 works."] },
      ],
      commonError: "Writing {{sqrt(12 + 2sqrt(35)) = sqrt(12) + sqrt(2sqrt(35))}} — roots don't split over addition.",
      traps: [{ spec: { type: "list", values: [5, 7], ordered: true }, feedback: "Right numbers — but the question says a > b, so give 7 first." }],
      difficulty: "challenge",
      guideRef: "simplifying-surds",
      hints: [
        "Work backwards: what do you get when you square {{sqrt(a) + sqrt(b)}}?",
        "{{(sqrt(a) + sqrt(b))^2 = a + b + 2sqrt(ab)}}. Compare with {{12 + 2sqrt(35)}}.",
        "You need a + b = 12 and ab = 35.",
      ],
      strategy: "Work backwards",
    },
    {
      kind: "short",
      id: "indices-surds-ch-q08",
      question: "Expand and simplify {{(sqrt(3) + sqrt(2))^4}}. Give your answer in the form {{a + b sqrt(6)}}.",
      answer: { type: "expression", expr: "49+20sqrt(6)", form: "surd", display: "{{49 + 20sqrt(6)}}" },
      solution: [
        "Square first: {{(sqrt(3) + sqrt(2))^2 = 3 + 2sqrt(6) + 2 = 5 + 2sqrt(6)}}.",
        "Square again: {{(5 + 2sqrt(6))^2 = 25 + 20sqrt(6) + 4 * 6}}.",
        "{{= 49 + 20sqrt(6)}}.",
      ],
      solutions: [
        { label: "Square twice (quick)", steps: ["{{(sqrt(3) + sqrt(2))^2 = 5 + 2sqrt(6)}}.", "{{(5 + 2sqrt(6))^2 = 49 + 20sqrt(6)}}."] },
        { label: "Binomial expansion", steps: ["Coefficients 1, 4, 6, 4, 1.", "{{9 + 4 * 3sqrt(3) * sqrt(2) + 6 * 3 * 2 + 4 * sqrt(3) * 2sqrt(2) + 4}}.", "{{= 9 + 12sqrt(6) + 36 + 8sqrt(6) + 4 = 49 + 20sqrt(6)}}. Longer — squaring twice is quicker."] },
      ],
      commonError: "Writing {{(sqrt(3) + sqrt(2))^4 = 9 + 4}} — powers don't distribute over addition.",
      traps: [
        { spec: { type: "expression", expr: "13" }, feedback: "{{(a + b)^4 != a^4 + b^4}}. Square the bracket, then square the result." },
        { spec: { type: "expression", expr: "29+20sqrt(6)" }, feedback: "{{(2sqrt(6))^2 = 4 * 6 = 24}}, so 25 + 24 = 49." },
      ],
      difficulty: "challenge",
      guideRef: "surd-brackets",
      hints: [
        "A fourth power is a square of a square.",
        "{{(sqrt(3) + sqrt(2))^2 = 5 + 2sqrt(6)}}.",
        "Now square {{5 + 2sqrt(6)}}: remember {{(2sqrt(6))^2 = 24}}.",
      ],
      strategy: "Make it simpler",
    },
    {
      kind: "short",
      id: "indices-surds-ch-q09",
      question:
        "Rationalise the denominator of {{1/(1 + sqrt(2) + sqrt(3))}}. Give your answer in the form {{(a + sqrt(b) - sqrt(c))/d}}, where a, b, c and d are integers.",
      answer: { type: "expression", expr: "(2+sqrt(2)-sqrt(6))/4", form: "surd", display: "{{(2 + sqrt(2) - sqrt(6))/4}}" },
      solution: [
        "Group the denominator as {{(1 + sqrt(2)) + sqrt(3)}} and multiply top and bottom by {{(1 + sqrt(2)) - sqrt(3)}}.",
        "Denominator: {{(1 + sqrt(2))^2 - 3 = 3 + 2sqrt(2) - 3 = 2sqrt(2)}}.",
        "So far: {{(1 + sqrt(2) - sqrt(3))/(2sqrt(2))}}.",
        "Multiply top and bottom by {{sqrt(2)}}: numerator {{sqrt(2) + 2 - sqrt(6)}}, denominator 4.",
        "Answer: {{(2 + sqrt(2) - sqrt(6))/4}}.",
      ],
      solutions: [
        {
          label: "Group (1 + √2) + √3",
          steps: ["Multiply by {{1 + sqrt(2) - sqrt(3)}}: denominator {{2sqrt(2)}}.", "Then multiply by {{sqrt(2)}}: denominator 4."],
        },
        {
          label: "Group 1 + (√2 + √3)",
          steps: [
            "Multiply by {{1 - (sqrt(2) + sqrt(3))}}: denominator {{1 - (5 + 2sqrt(6)) = -4 - 2sqrt(6)}}.",
            "Still a surd — this route needs another conjugate and is longer. Choosing the grouping that cancels the whole numbers is the insight.",
          ],
        },
      ],
      commonError: "Thinking one multiplication will clear all the surds — with three terms you need two rounds.",
      traps: [
        { spec: { type: "expression", expr: "(1+sqrt(2)-sqrt(3))/6" }, feedback: "{{(1 + sqrt(2))^2}} is {{3 + 2sqrt(2)}}, not 3. The denominator after one step is {{2sqrt(2)}}." },
      ],
      difficulty: "challenge",
      guideRef: "rationalising",
      hints: [
        "Three terms in the denominator — treat two of them as one block.",
        "Write it as {{(1 + sqrt(2)) + sqrt(3)}} and multiply by the conjugate {{(1 + sqrt(2)) - sqrt(3)}}.",
        "The denominator becomes {{(1 + sqrt(2))^2 - 3 = 2sqrt(2)}}.",
        "One more step: multiply top and bottom by {{sqrt(2)}}.",
      ],
      strategy: "Use the conjugate (twice)",
    },
    {
      kind: "short",
      id: "indices-surds-ch-q10",
      question: "Given that {{x = 3 + 2sqrt(2)}}, find the exact value of {{x^2 + 1/x^2}}.",
      answer: { type: "number", value: 34 },
      solution: [
        "Rationalise {{1/x}}: {{1/(3 + 2sqrt(2)) = (3 - 2sqrt(2))/(9 - 8) = 3 - 2sqrt(2)}}.",
        "So {{x + 1/x = 6}}.",
        "{{(x + 1/x)^2 = x^2 + 2 + 1/x^2}}, so {{x^2 + 1/x^2 = 36 - 2 = 34}}.",
      ],
      solutions: [
        { label: "Use x + 1/x (elegant)", steps: ["{{x + 1/x = 6}}.", "{{x^2 + 1/x^2 = 6^2 - 2 = 34}}."] },
        { label: "Brute force", steps: ["{{x^2 = 9 + 12sqrt(2) + 8 = 17 + 12sqrt(2)}}.", "{{1/x^2 = (3 - 2sqrt(2))^2 = 17 - 12sqrt(2)}}.", "Sum: 34."] },
      ],
      commonError: "Writing {{(x + 1/x)^2 = x^2 + 1/x^2}}, forgetting the middle term 2.",
      traps: [{ spec: { type: "number", value: 36 }, feedback: "{{(x + 1/x)^2 = x^2 + 2 + 1/x^2}}. Subtract the 2." }],
      difficulty: "challenge",
      guideRef: "rationalising",
      hints: [
        "Start with {{1/x}}. Rationalise it — something surprising happens.",
        "{{1/x = 3 - 2sqrt(2)}} because {{(3 + 2sqrt(2))(3 - 2sqrt(2)) = 1}}.",
        "So {{x + 1/x = 6}}. How does {{(x + 1/x)^2}} relate to {{x^2 + 1/x^2}}?",
      ],
      strategy: "Look for an invariant",
    },
  ],
};
