import type { TopicPractice } from "../../types.ts";

export const practice: TopicPractice = {
  // =========================================================================
  // Quick-check quiz — 10 questions (3 mcq, 7 short) across the main sections
  // =========================================================================
  quiz: [
    {
      kind: "short",
      id: "solving-equations-quiz-q01",
      question: "Solve 5x − 7 = 2x + 11.",
      answer: { type: "number", value: 6, display: "x = 6" },
      solution: [
        "Subtract 2x from both sides: 3x − 7 = 11.",
        "Add 7 to both sides: 3x = 18.",
        "Divide by 3: x = 6.",
        "Check: 5 × 6 − 7 = 23 and 2 × 6 + 11 = 23. ✓",
      ],
      traps: [
        {
          spec: { type: "fraction", n: 4, d: 3 },
          feedback: "It looks like you did 11 − 7 instead of 11 + 7. To undo − 7 you **add** 7 to both sides: 3x = 18.",
        },
      ],
      commonError: "Moving −7 across as −7 instead of +7.",
      difficulty: "warmup",
      guideRef: "linear-equations",
      hints: ["Get all the x terms on the side with more x's first.", "Subtract 2x from both sides, then deal with the −7."],
      strategy: "Use the inverse",
    },
    {
      kind: "mcq",
      id: "solving-equations-quiz-q02",
      question: "Solve 3(2x − 5) = 4x + 1.",
      options: ["x = 3", "x = 8", "x = −7", "x = 1.6"],
      answerIndex: 1,
      explanation:
        "Expand: 6x − 15 = 4x + 1. Subtract 4x: 2x − 15 = 1, so 2x = 16 and x = 8. x = 3 comes from multiplying only the 2x by 3 (6x − 5); x = −7 from moving −15 across without changing its sign; x = 1.6 from adding 4x to the left instead of subtracting it.",
      difficulty: "warmup",
      guideRef: "linear-equations",
      hints: ["Multiply out the bracket first — every term inside gets multiplied by 3.", "6x − 15 = 4x + 1. Now collect the x terms on one side."],
      strategy: "Check by substituting",
    },
    {
      kind: "short",
      id: "solving-equations-quiz-q03",
      question: "Solve {{(x+3)/4 - (x-1)/3 = 1}}.",
      answer: { type: "number", value: 1, display: "x = 1" },
      solution: [
        "The LCD of 4 and 3 is 12. Multiply every term by 12: 3(x + 3) − 4(x − 1) = 12.",
        "Expand carefully: 3x + 9 − 4x + 4 = 12. (− 4 × − 1 = + 4.)",
        "Simplify: −x + 13 = 12, so −x = −1 and x = 1.",
        "Check: {{4/4 - 0/3 = 1}}. ✓",
      ],
      traps: [
        {
          spec: { type: "number", value: -7 },
          feedback: "Sign slip: −4(x − 1) = −4x **+ 4**, not −4x − 4. The minus in front of the fraction multiplies the whole numerator.",
        },
      ],
      commonError: "Writing −4(x − 1) as −4x − 4.",
      difficulty: "core",
      guideRef: "linear-equations",
      hints: [
        "Clear the fractions: what number do 4 and 3 both go into?",
        "Multiply every term — including the 1 on the right — by 12.",
        "Put the numerators in brackets before expanding: 3(x + 3) − 4(x − 1) = 12.",
      ],
      strategy: "Make it simpler",
    },
    {
      kind: "short",
      id: "solving-equations-quiz-q04",
      question:
        "The angles of a triangle are (x + 20)°, (2x − 10)° and (3x + 50)°. Work out the size of the **largest** angle. Give your answer in degrees.",
      answer: { type: "number", value: 110, display: "110°" },
      solution: [
        "Angles in a triangle add to 180°: (x + 20) + (2x − 10) + (3x + 50) = 180.",
        "6x + 60 = 180, so 6x = 120 and x = 20.",
        "The angles are 40°, 30° and 110°. The largest is 110°.",
      ],
      traps: [
        { spec: { type: "number", value: 20 }, feedback: "x = 20 is right — but the question asks for the largest angle. Substitute back: 3(20) + 50." },
      ],
      commonError: "Stopping at x = 20 instead of answering the question asked.",
      difficulty: "core",
      guideRef: "linear-equations",
      hints: ["What do the angles in a triangle add up to?", "Add the three expressions and set the total equal to 180.", "Once you have x, substitute it into each angle."],
      strategy: "Introduce a variable",
    },
    {
      kind: "short",
      id: "solving-equations-quiz-q05",
      question: "Make t the subject of v = u + at.",
      answer: { type: "expression", expr: "(v-u)/a", display: "{{t = (v - u)/a}}" },
      solution: ["Subtract u from both sides: v − u = at.", "Divide both sides by a: {{t = (v - u)/a}}."],
      traps: [
        { spec: { type: "expression", expr: "v/a-u" }, feedback: "Undo in reverse order: the u was added *last*, so subtract it *first*, then divide the whole of v − u by a." },
      ],
      commonError: "Dividing only v by a, giving {{v/a - u}}.",
      difficulty: "warmup",
      guideRef: "rearranging-once",
      hints: ["Which operation was done to t last? Undo that one first.", "Subtract u from both sides, then divide by a."],
      strategy: "Use the inverse",
    },
    {
      kind: "short",
      id: "solving-equations-quiz-q06",
      question: "Make x the subject of {{y = 2x^2 - 3}}, where x > 0.",
      answer: { type: "expression", expr: "sqrt((y+3)/2)", display: "{{x = sqrt((y + 3)/2)}}" },
      solution: [
        "Add 3 to both sides: {{y + 3 = 2x^2}}.",
        "Divide by 2: {{x^2 = (y + 3)/2}}.",
        "Square root (x > 0, so take the positive root): {{x = sqrt((y + 3)/2)}}.",
      ],
      traps: [
        { spec: { type: "expression", expr: "sqrt(y+3)/2" }, feedback: "The 2 was dividing *before* you took the square root, so it must stay inside the root: {{sqrt((y+3)/2)}}." },
      ],
      commonError: "Taking the square root before dividing by 2, leaving the 2 outside the root.",
      difficulty: "core",
      guideRef: "rearranging-once",
      hints: [
        "Think of the order of operations done to x: square, × 2, − 3. Undo them in reverse.",
        "Add 3, then divide by 2 — and only then square root.",
      ],
      strategy: "Work backwards",
    },
    {
      kind: "mcq",
      id: "solving-equations-quiz-q07",
      question: "Make p the subject of 3p + q = r(p − 2).",
      options: ["{{p = (q + 2r)/(3 - r)}}", "{{p = (q + 2)/(r - 3)}}", "{{p = (q + 2r)/(r - 3)}}", "{{p = (q + 2r)/(r + 3)}}"],
      answerIndex: 2,
      explanation:
        "Expand: 3p + q = rp − 2r. Collect p terms on the right: q + 2r = rp − 3p = p(r − 3). So {{p = (q + 2r)/(r - 3)}}. {{(q + 2r)/(3 - r)}} has a sign slip when collecting; {{(q + 2)/(r - 3)}} comes from expanding r(p − 2) as rp − 2; {{(q + 2r)/(r + 3)}} adds 3p instead of subtracting it.",
      difficulty: "core",
      guideRef: "rearranging-twice",
      hints: [
        "p appears twice. First expand the bracket.",
        "Get every p term on one side and everything else on the other.",
        "Factorise out p, then divide by the bracket.",
      ],
      strategy: "Collect, factorise, divide",
    },
    {
      kind: "short",
      id: "solving-equations-quiz-q08",
      question: "Make x the subject of {{y = (x + 2)/(x - 3)}}.",
      answer: { type: "expression", expr: "(3y+2)/(y-1)", display: "{{x = (3y + 2)/(y - 1)}}" },
      solution: [
        "Multiply both sides by (x − 3): y(x − 3) = x + 2.",
        "Expand: xy − 3y = x + 2.",
        "Collect x terms on one side: xy − x = 3y + 2.",
        "Factorise: x(y − 1) = 3y + 2, so {{x = (3y + 2)/(y - 1)}}.",
      ],
      traps: [
        { spec: { type: "expression", expr: "(2-3y)/(y-1)" }, feedback: "Check the sign when you move −3y across: xy − 3y = x + 2 gives xy − x = 3y + 2." },
      ],
      commonError: "Multiplying only x by y instead of the whole bracket (x − 3).",
      difficulty: "core",
      guideRef: "rearranging-twice",
      hints: [
        "Get rid of the fraction: multiply both sides by (x − 3).",
        "Expand and gather every term with an x on the left.",
        "Factorise the x out: x(y − 1) = …",
      ],
      strategy: "Collect, factorise, divide",
    },
    {
      kind: "short",
      id: "solving-equations-quiz-q09",
      question: "Solve the simultaneous equations\n\n    3x + 2y = 19\n    5x − 2y = 5\n\nGive x first, then y.",
      answer: { type: "list", values: [3, 5], ordered: true, display: "x = 3, y = 5" },
      solution: [
        "The y coefficients are +2 and −2, so **add** the equations: 8x = 24, x = 3.",
        "Substitute into the first: 9 + 2y = 19, so 2y = 10 and y = 5.",
        "Check in the second: 15 − 10 = 5. ✓",
      ],
      commonError: "Subtracting when the signs are different (that doubles y instead of removing it).",
      difficulty: "warmup",
      guideRef: "simultaneous-linear",
      hints: ["Look at the y terms: +2y and −2y. Add or subtract to make them vanish?", "Adding gives 8x = 24."],
      strategy: "Eliminate a variable",
    },
    {
      kind: "mcq",
      id: "solving-equations-quiz-q10",
      question:
        "At a Sentosa attraction, 2 adult tickets and 3 child tickets cost $47. 3 adult tickets and 2 child tickets cost $53. What is the price of one adult ticket?",
      options: ["$13", "$7", "$20", "$6"],
      answerIndex: 0,
      explanation:
        "2a + 3c = 47 and 3a + 2c = 53. Adding: 5a + 5c = 100, so a + c = 20. Subtracting the first from the second: a − c = 6. So a = 13 and c = 7. $7 is the child price; $20 is the cost of one adult **plus** one child; $6 is the difference between them.",
      difficulty: "core",
      guideRef: "simultaneous-linear",
      hints: [
        "Let a = adult price and c = child price. Write two equations.",
        "Try adding the equations, and try subtracting them — both give something neat.",
        "a + c = 20 and a − c = 6.",
      ],
      strategy: "Use symmetry",
    },
  ],

  // =========================================================================
  // Practice papers
  // =========================================================================
  papers: [
    {
      id: "solving-equations-p1",
      title: "Practice Paper 1",
      questions: [
        {
          kind: "short",
          id: "solving-equations-p1-q01",
          question: "Solve 7 − 2x = 3x − 8.",
          answer: { type: "number", value: 3, display: "x = 3" },
          solution: ["Add 2x to both sides: 7 = 5x − 8.", "Add 8 to both sides: 15 = 5x.", "So x = 3. Check: 7 − 6 = 1 and 9 − 8 = 1. ✓"],
          traps: [{ spec: { type: "number", value: -3 }, feedback: "Sign slip. Keep the x terms positive: add 2x to both sides to get 15 = 5x." }],
          commonError: "Losing a minus sign when moving −2x.",
          difficulty: "warmup",
          guideRef: "linear-equations",
          hints: ["Add 2x to both sides so the x term stays positive.", "Then add 8 to both sides."],
          strategy: "Keep the unknown positive",
        },
        {
          kind: "short",
          id: "solving-equations-p1-q02",
          question: "Solve 4(x + 3) − 2(x − 5) = 30.",
          answer: { type: "number", value: 4, display: "x = 4" },
          solution: [
            "Expand both brackets: 4x + 12 − 2x + 10 = 30. (−2 × −5 = +10.)",
            "Simplify: 2x + 22 = 30.",
            "2x = 8, so x = 4.",
          ],
          traps: [{ spec: { type: "number", value: 14 }, feedback: "−2(x − 5) = −2x **+ 10**. Multiplying two negatives gives a positive." }],
          commonError: "Expanding −2(x − 5) as −2x − 10.",
          difficulty: "warmup",
          guideRef: "linear-equations",
          hints: ["Expand each bracket — watch the −2 multiplying the −5.", "You should get 2x + 22 = 30."],
          strategy: "Check by substituting",
        },
        {
          kind: "short",
          id: "solving-equations-p1-q03",
          question: "The kinetic energy of a moving object is {{E = 1/2 m v^2}}. Make v the subject of the formula. (v > 0)",
          answer: { type: "expression", expr: "sqrt(2E/m)", display: "{{v = sqrt((2E)/m)}}" },
          solution: ["Multiply both sides by 2: {{2E = m v^2}}.", "Divide by m: {{v^2 = (2E)/m}}.", "Square root (v > 0): {{v = sqrt((2E)/m)}}."],
          traps: [
            { spec: { type: "expression", expr: "sqrt(E/(2m))" }, feedback: "To undo × {{1/2}} you multiply by 2 — so the 2 goes on top: {{v^2 = (2E)/m}}." },
            { spec: { type: "expression", expr: "2E/m" }, feedback: "That's {{v^2}}. One more step: square root it." },
          ],
          commonError: "Dividing by 2 instead of multiplying to undo the {{1/2}}.",
          difficulty: "warmup",
          guideRef: "rearranging-once",
          hints: ["Get {{v^2}} on its own first: undo the {{1/2}} and the m.", "Then square root the **whole** of the other side."],
          strategy: "Use the inverse",
        },
        {
          kind: "short",
          id: "solving-equations-p1-q04",
          question: "Solve the simultaneous equations\n\n    2x + y = 11\n    x − y = 1\n\nGive x first, then y.",
          answer: { type: "list", values: [4, 3], ordered: true, display: "x = 4, y = 3" },
          solution: ["Add the equations (the y terms cancel): 3x = 12, so x = 4.", "From x − y = 1: y = 4 − 1 = 3.", "Check: 2(4) + 3 = 11. ✓"],
          difficulty: "warmup",
          guideRef: "simultaneous-linear",
          hints: ["+y and −y: what happens if you add the equations?", "3x = 12."],
          strategy: "Eliminate a variable",
        },
        {
          kind: "short",
          id: "solving-equations-p1-q05",
          question: "Solve {{(3x + 1)/4 - (x - 2)/6 = 7}}.",
          answer: { type: "number", value: 11, display: "x = 11" },
          solution: [
            "LCD of 4 and 6 is 12. Multiply every term by 12: 3(3x + 1) − 2(x − 2) = 84.",
            "Expand: 9x + 3 − 2x + 4 = 84.",
            "7x + 7 = 84, so 7x = 77 and x = 11.",
            "Check: {{34/4 - 9/6 = 8.5 - 1.5 = 7}}. ✓",
          ],
          traps: [
            { spec: { type: "fraction", n: 85, d: 7 }, feedback: "Sign slip: −2(x − 2) = −2x **+ 4**. Bracket the numerators before you expand." },
          ],
          commonError: "Expanding −2(x − 2) as −2x − 4 instead of −2x + 4.",
          difficulty: "core",
          guideRef: "linear-equations",
          hints: [
            "What is the lowest common multiple of 4 and 6?",
            "Multiply **every** term by 12 — including the 7.",
            "12 × {{(3x+1)/4}} = 3(3x + 1) and 12 × {{(x-2)/6}} = 2(x − 2).",
          ],
          strategy: "Make it simpler",
        },
        {
          kind: "short",
          id: "solving-equations-p1-q06",
          question:
            "A rectangle has length (2x + 5) cm and width (x − 1) cm. A square has side (x + 4) cm. The rectangle and the square have the same perimeter. Work out the **area of the rectangle** in cm².",
          answer: { type: "number", value: 39, display: "39 cm²" },
          solution: [
            "Rectangle perimeter: 2(2x + 5) + 2(x − 1) = 6x + 8.",
            "Square perimeter: 4(x + 4) = 4x + 16.",
            "6x + 8 = 4x + 16, so 2x = 8 and x = 4.",
            "Rectangle: 13 cm by 3 cm, area = 39 cm².",
          ],
          traps: [
            { spec: { type: "number", value: 4 }, feedback: "x = 4 is the right value of x — now use it to find the rectangle's length and width." },
            { spec: { type: "number", value: 32 }, feedback: "32 cm is the (shared) perimeter. The question asks for the area of the rectangle." },
          ],
          commonError: "Adding only one length and one width for the perimeter.",
          difficulty: "core",
          guideRef: "linear-equations",
          hints: ["Write each perimeter as an expression in x.", "Set them equal and solve for x.", "Then find the length and width and multiply."],
          strategy: "Introduce a variable",
        },
        {
          kind: "short",
          id: "solving-equations-p1-q07",
          question:
            "At a hawker centre, Priya pays $7.30 for 3 kaya toasts and 2 cups of teh. Marcus pays $11.70 for 5 kaya toasts and 3 cups of teh. How much would 2 kaya toasts and 4 cups of teh cost? Give your answer in dollars.",
          answer: { type: "number", value: 8.6, display: "$8.60" },
          solution: [
            "Let k = price of a kaya toast, t = price of a teh: 3k + 2t = 7.30 and 5k + 3t = 11.70.",
            "Match the t terms: × 3 gives 9k + 6t = 21.90; × 2 gives 10k + 6t = 23.40.",
            "Subtract: k = 1.50.",
            "Substitute: 4.50 + 2t = 7.30, so 2t = 2.80 and t = 1.40.",
            "2k + 4t = 3.00 + 5.60 = $8.60.",
          ],
          traps: [{ spec: { type: "number", value: 1.5 }, feedback: "$1.50 is one kaya toast. Finish the question: find t, then 2k + 4t." }],
          commonError: "Multiplying only the left-hand side when scaling an equation.",
          difficulty: "core",
          guideRef: "simultaneous-linear",
          hints: [
            "Choose letters and write two equations.",
            "Scale the equations so the t coefficients match (6t in both).",
            "Subtract to find k, substitute to find t, then answer the actual question.",
          ],
          strategy: "Eliminate a variable",
        },
        {
          kind: "short",
          id: "solving-equations-p1-q08",
          question: "The volume of a sphere is {{V = 4/3 pi r^3}}. Make r the subject of the formula.",
          answer: { type: "expression", expr: "cbrt(3V/(4pi))", display: "{{r = cbrt((3V)/(4 pi))}}" },
          solution: [
            "Multiply both sides by 3: {{3V = 4 pi r^3}}.",
            "Divide by 4π: {{r^3 = (3V)/(4 pi)}}.",
            "Cube root: {{r = cbrt((3V)/(4 pi))}}.",
          ],
          traps: [
            { spec: { type: "expression", expr: "cbrt(4V/(3pi))" }, feedback: "You've flipped the fraction. Dividing by {{4/3}} is the same as multiplying by {{3/4}}." },
            { spec: { type: "expression", expr: "sqrt(3V/(4pi))" }, feedback: "r is **cubed**, so undo it with a cube root, not a square root." },
          ],
          commonError: "Multiplying by {{4/3}} instead of dividing.",
          difficulty: "core",
          guideRef: "rearranging-once",
          hints: [
            "What has happened to r? Cubed, × π, × {{4/3}}. Undo in reverse.",
            "Clear the fraction first: multiply both sides by 3.",
            "Get {{r^3}} alone, then cube root.",
          ],
          strategy: "Work backwards",
        },
        {
          kind: "short",
          id: "solving-equations-p1-q09",
          question: "Make x the subject of 3(x − a) = bx + 5.",
          answer: { type: "expression", expr: "(3a+5)/(3-b)", display: "{{x = (3a + 5)/(3 - b)}}" },
          solution: [
            "Expand: 3x − 3a = bx + 5.",
            "Collect x terms on the left, others on the right: 3x − bx = 5 + 3a.",
            "Factorise: x(3 − b) = 3a + 5.",
            "Divide: {{x = (3a + 5)/(3 - b)}}.",
          ],
          traps: [
            { spec: { type: "expression", expr: "(5-3a)/(3-b)" }, feedback: "Moving −3a to the other side makes it **+3a**." },
          ],
          commonError: "Trying to divide by b before collecting the x terms.",
          difficulty: "core",
          guideRef: "rearranging-twice",
          hints: [
            "x is on both sides. Expand, then collect the x terms together.",
            "3x − bx = 5 + 3a. What is the common factor on the left?",
            "x(3 − b) = 3a + 5.",
          ],
          strategy: "Collect, factorise, divide",
        },
        {
          kind: "written",
          id: "solving-equations-p1-q10",
          question:
            "In optics, the lens formula is {{1/u + 1/v = 1/f}}.\n\nShow that {{v = (uf)/(u - f)}}.",
          marks: 3,
          modelAnswer:
            "Multiply every term by uvf: vf + uf = uv.\n\nCollect the v terms on one side: uf = uv − vf.\n\nFactorise: uf = v(u − f).\n\nDivide by (u − f): {{v = (uf)/(u - f)}}, as required.",
          markScheme: [
            { point: "Clears the fractions correctly, e.g. multiplies by uvf to get vf + uf = uv (or writes {{1/v = 1/f - 1/u = (u - f)/(uf)}})", keywords: ["uvf", "vf + uf = uv", "vf+uf=uv", "(u-f)/uf", "common denominator"] },
            { point: "Collects the v terms and factorises: uf = v(u − f)", keywords: ["v(u - f)", "v(u-f)", "uv - vf", "uv-vf", "factorise"] },
            { point: "Divides to reach v = uf/(u − f) with no errors", keywords: ["uf/(u-f)", "uf/(u - f)", "divide"] },
          ],
          commonError: "Writing 1/u + 1/v = 1/(u + v) — fractions don't add like that.",
          solutions: [
            {
              label: "Isolate 1/v first",
              steps: [
                "{{1/v = 1/f - 1/u}}.",
                "Common denominator: {{1/v = (u - f)/(uf)}}.",
                "Flip both sides (reciprocals of equal numbers are equal): {{v = (uf)/(u - f)}}. Quicker — but only flip when each side is a *single* fraction.",
              ],
            },
          ],
          difficulty: "core",
          guideRef: "rearranging-twice",
          hints: [
            "What could you multiply every term by to clear all three denominators?",
            "After multiplying by uvf: vf + uf = uv. Where are the v terms?",
            "Gather the v terms on one side and factorise.",
          ],
          strategy: "Collect, factorise, divide",
        },
        {
          kind: "short",
          id: "solving-equations-p1-q11",
          question: "Solve the simultaneous equations\n\n    4x + 3y = 5\n    3x − 2y = 8\n\nGive x first, then y.",
          answer: { type: "list", values: [2, -1], ordered: true, display: "x = 2, y = −1" },
          solution: [
            "Make the y coefficients match: (first) × 2 gives 8x + 6y = 10; (second) × 3 gives 9x − 6y = 24.",
            "Add: 17x = 34, so x = 2.",
            "Substitute into 4x + 3y = 5: 8 + 3y = 5, so y = −1.",
            "Check in the second: 6 + 2 = 8. ✓",
          ],
          commonError: "Scaling the left-hand side but forgetting to scale the number on the right.",
          difficulty: "core",
          guideRef: "simultaneous-linear",
          hints: [
            "Neither coefficient matches yet. Which variable is easier to eliminate?",
            "Scale so the y terms become +6y and −6y.",
            "Different signs → add.",
          ],
          strategy: "Eliminate a variable",
        },
        {
          kind: "written",
          id: "solving-equations-p1-q12",
          question:
            "Mei tries to solve the simultaneous equations\n\n    6x − 4y = 10\n    9x − 6y = 12\n\nand gets stuck. Explain why these equations have **no** solution.",
          marks: 3,
          modelAnswer:
            "Divide the first equation by 2: 3x − 2y = 5. Divide the second equation by 3: 3x − 2y = 4.\n\nThe same expression 3x − 2y cannot equal both 5 and 4, so there is no pair (x, y) satisfying both — subtracting gives 0 = 1, a contradiction.\n\nGraphically, both lines have gradient {{3/2}} but different y-intercepts ({{-5/2}} and −2), so they are parallel and never meet.",
          markScheme: [
            { point: "Simplifies/scales both to the same left-hand side, 3x − 2y = 5 and 3x − 2y = 4 (or equivalent scaling to 18x − 12y)", keywords: ["3x - 2y", "3x-2y", "18x", "divide by 2", "divide by 3"] },
            { point: "States the contradiction: the same expression can't equal two different values (e.g. 0 = 1 or 5 ≠ 4)", keywords: ["contradiction", "0 = 1", "0=1", "5", "4", "cannot", "can't"] },
            { point: "Interprets: the lines are parallel (same gradient, different intercept) so they never intersect", keywords: ["parallel", "same gradient", "never meet", "do not intersect", "no point of intersection"] },
          ],
          commonError: "Saying 'the numbers don't work' without showing the contradiction.",
          difficulty: "core",
          guideRef: "simultaneous-linear",
          hints: [
            "Can you simplify each equation by dividing through?",
            "Compare the left-hand sides after simplifying.",
            "What does that mean for the two straight-line graphs?",
          ],
          strategy: "Look for an invariant",
        },
        {
          kind: "short",
          id: "solving-equations-p1-q13",
          question: "Make p the subject of {{q = sqrt((p + 4)/(p - 1))}}.",
          answer: { type: "expression", expr: "(q^2+4)/(q^2-1)", display: "{{p = (q^2 + 4)/(q^2 - 1)}}" },
          solution: [
            "Square both sides: {{q^2 = (p + 4)/(p - 1)}}.",
            "Multiply by (p − 1): {{q^2 p - q^2 = p + 4}}.",
            "Collect p terms: {{q^2 p - p = q^2 + 4}}.",
            "Factorise: {{p(q^2 - 1) = q^2 + 4}}, so {{p = (q^2 + 4)/(q^2 - 1)}}.",
          ],
          traps: [
            { spec: { type: "expression", expr: "(q+4)/(q-1)" }, feedback: "You need to **square** both sides first to remove the root — so every q becomes {{q^2}}." },
          ],
          commonError: "Forgetting to square q when removing the square root.",
          difficulty: "challenge",
          guideRef: "rearranging-twice",
          hints: [
            "The p's are trapped under a square root. What undoes a square root?",
            "Square both sides, then clear the fraction.",
            "{{q^2 p - q^2 = p + 4}}. Collect the p terms and factorise.",
          ],
          strategy: "Collect, factorise, divide",
        },
        {
          kind: "short",
          id: "solving-equations-p1-q14",
          question:
            "Solve the simultaneous equations\n\n    x + y + z = 6\n    2x − y + z = 3\n    x + 2y − z = 2\n\nGive your answer as x, y, z in that order.",
          answer: { type: "list", values: [1, 2, 3], ordered: true, display: "x = 1, y = 2, z = 3" },
          solution: [
            "Eliminate z twice. First + third: 2x + 3y = 8.",
            "Second + third: 3x + y = 5, so y = 5 − 3x.",
            "Substitute: 2x + 3(5 − 3x) = 8 → 2x + 15 − 9x = 8 → −7x = −7 → x = 1.",
            "y = 5 − 3 = 2, and from the first equation z = 6 − 1 − 2 = 3.",
            "Check the second: 2 − 2 + 3 = 3. ✓ Third: 1 + 4 − 3 = 2. ✓",
          ],
          commonError: "Eliminating different variables in the two pairs, so you don't end up with two equations in the same two unknowns.",
          difficulty: "challenge",
          guideRef: "simultaneous-three",
          hints: [
            "Pick one variable to eliminate — z has +z, +z and −z, so it's the easiest.",
            "Pair up (1) with (3) and (2) with (3). Each pair loses z.",
            "Solve the two-variable system 2x + 3y = 8, 3x + y = 5, then back-substitute.",
          ],
          strategy: "Make it simpler",
        },
        {
          kind: "written",
          id: "solving-equations-p1-q15",
          question:
            "Arjun says: \"The equation 3(2x − 4) = 6x + k has no solution, whatever the value of k.\"\n\nIs Arjun right? Explain your answer fully.",
          marks: 3,
          modelAnswer:
            "Expand: 6x − 12 = 6x + k. Subtract 6x from both sides: −12 = k.\n\nIf k ≠ −12 this is a false statement, so there is no solution.\n\nBut if k = −12 the statement −12 = −12 is always true, so **every** value of x is a solution (the equation is an identity). So Arjun is wrong: when k = −12 there are infinitely many solutions.",
          markScheme: [
            { point: "Expands and simplifies to −12 = k (the x terms cancel)", keywords: ["6x - 12", "6x-12", "-12 = k", "k = -12", "cancel"] },
            { point: "For k ≠ −12 the statement is false, so no solution", keywords: ["no solution", "false", "not equal", "≠"] },
            { point: "For k = −12 it is true for all x (identity / infinitely many solutions), so Arjun is wrong", keywords: ["infinitely many", "every value", "all x", "identity", "wrong", "-12"] },
          ],
          commonError: "Only noticing the 'no solution' case and agreeing with Arjun.",
          difficulty: "challenge",
          guideRef: "linear-equations",
          hints: [
            "Expand and try to solve it. What happens to the x terms?",
            "You're left with a statement about k only. When is it true?",
            "Consider the two cases: k = −12 and k ≠ −12.",
          ],
          strategy: "Split into cases",
        },
      ],
    },
    {
      id: "solving-equations-p2",
      title: "Practice Paper 2",
      questions: [
        {
          kind: "short",
          id: "solving-equations-p2-q01",
          question: "Solve 5(2x − 3) = 3(x + 2).",
          answer: { type: "number", value: 3, display: "x = 3" },
          solution: ["Expand: 10x − 15 = 3x + 6.", "Subtract 3x: 7x − 15 = 6.", "Add 15: 7x = 21, so x = 3."],
          traps: [{ spec: { type: "fraction", n: 5, d: 7 }, feedback: "Multiply **every** term inside each bracket: 5(2x − 3) = 10x − 15 and 3(x + 2) = 3x + 6." }],
          commonError: "Multiplying only the first term inside each bracket.",
          difficulty: "warmup",
          guideRef: "linear-equations",
          hints: ["Expand both brackets.", "10x − 15 = 3x + 6. Now collect x terms on the left."],
          strategy: "Check by substituting",
        },
        {
          kind: "short",
          id: "solving-equations-p2-q02",
          question: "Solve {{(4x + 1)/3 = x - 2}}.",
          answer: { type: "number", value: -7, display: "x = −7" },
          solution: ["Multiply both sides by 3: 4x + 1 = 3(x − 2) = 3x − 6.", "Subtract 3x and 1: x = −7.", "Check: {{(-28 + 1)/3 = -9}} and −7 − 2 = −9. ✓"],
          traps: [
            { spec: { type: "fraction", n: -7, d: 3 }, feedback: "When you multiply by 3, the **whole** right-hand side gets multiplied: 3(x − 2), not x − 6." },
          ],
          commonError: "Multiplying only the left-hand side by 3.",
          difficulty: "warmup",
          guideRef: "linear-equations",
          hints: ["Clear the fraction by multiplying both sides by 3.", "Bracket the right-hand side: 3(x − 2)."],
          strategy: "Make it simpler",
        },
        {
          kind: "short",
          id: "solving-equations-p2-q03",
          question: "The volume of a cylinder is {{V = pi r^2 h}}. Make r the subject of the formula. (r > 0)",
          answer: { type: "expression", expr: "sqrt(V/(pi*h))", display: "{{r = sqrt(V/(pi h))}}" },
          solution: ["Divide both sides by πh: {{r^2 = V/(pi h)}}.", "Square root (r > 0): {{r = sqrt(V/(pi h))}}."],
          traps: [{ spec: { type: "expression", expr: "V/(pi*h)" }, feedback: "That's {{r^2}}. One more step: square root it." }],
          commonError: "Forgetting the final square root.",
          difficulty: "warmup",
          guideRef: "rearranging-once",
          hints: ["Get {{r^2}} on its own.", "Divide by πh, then square root."],
          strategy: "Use the inverse",
        },
        {
          kind: "short",
          id: "solving-equations-p2-q04",
          question: "Solve the simultaneous equations\n\n    y = 2x − 1\n    3x + 2y = 19\n\nGive x first, then y.",
          answer: { type: "list", values: [3, 5], ordered: true, display: "x = 3, y = 5" },
          solution: [
            "Substitute y = 2x − 1 into the second: 3x + 2(2x − 1) = 19.",
            "3x + 4x − 2 = 19, so 7x = 21 and x = 3.",
            "y = 2(3) − 1 = 5.",
          ],
          commonError: "Writing 2(2x − 1) as 4x − 1.",
          difficulty: "warmup",
          guideRef: "simultaneous-linear",
          hints: ["y is already the subject of one equation — substitute it into the other.", "3x + 2(2x − 1) = 19."],
          strategy: "Substitute",
        },
        {
          kind: "short",
          id: "solving-equations-p2-q05",
          question:
            "Ethan's mother is 4 times as old as Ethan. In 6 years' time she will be 2.5 times as old as Ethan. How old is Ethan now?",
          answer: { type: "number", value: 6, display: "6 years old" },
          solution: [
            "Let Ethan be e now; his mother is 4e.",
            "In 6 years: 4e + 6 = 2.5(e + 6).",
            "4e + 6 = 2.5e + 15, so 1.5e = 9 and e = 6.",
            "Check: now 6 and 24; in 6 years 12 and 30, and 30 = 2.5 × 12. ✓",
          ],
          traps: [{ spec: { type: "number", value: 24 }, feedback: "24 is the mother's age. The question asks for Ethan's." }],
          commonError: "Adding 6 to Ethan's age but not to his mother's (or vice versa).",
          difficulty: "core",
          guideRef: "linear-equations",
          hints: ["Let Ethan's age be e. What is his mother's age now?", "Add 6 to **both** ages, then use the 2.5 times relationship.", "4e + 6 = 2.5(e + 6)."],
          strategy: "Introduce a variable",
        },
        {
          kind: "short",
          id: "solving-equations-p2-q06",
          question:
            "The angles of a quadrilateral are x°, 2x°, (3x − 20)° and (x + 30)°. Work out the size of the **largest** angle in degrees.",
          answer: { type: "number", value: 130, display: "130°" },
          solution: [
            "Angles in a quadrilateral add to 360°: x + 2x + 3x − 20 + x + 30 = 360.",
            "7x + 10 = 360, so 7x = 350 and x = 50.",
            "Angles: 50°, 100°, 130°, 80° (total 360° ✓). Largest = 130°.",
          ],
          traps: [{ spec: { type: "number", value: 50 }, feedback: "x = 50 — now substitute back to find each angle and pick the largest." }],
          commonError: "Using 180° instead of 360° for a quadrilateral.",
          difficulty: "core",
          guideRef: "linear-equations",
          hints: ["What do the angles in a quadrilateral add to?", "Collect like terms: 7x + 10 = 360.", "Substitute x back into each angle."],
          strategy: "Introduce a variable",
        },
        {
          kind: "short",
          id: "solving-equations-p2-q07",
          question: "Solve {{5/(x + 2) = 3/(x - 2)}}.",
          answer: { type: "number", value: 8, display: "x = 8" },
          solution: [
            "Multiply both sides by (x + 2)(x − 2): 5(x − 2) = 3(x + 2).",
            "5x − 10 = 3x + 6, so 2x = 16 and x = 8.",
            "Check: {{5/10 = 3/6 = 1/2}}. ✓",
          ],
          traps: [
            { spec: { type: "number", value: -8 }, feedback: "Cross-multiplying puts each numerator with the **other** denominator: 5(x − 2) = 3(x + 2)." },
          ],
          commonError: "Cross-multiplying with the wrong pairs: 5(x + 2) = 3(x − 2).",
          difficulty: "core",
          guideRef: "linear-equations",
          hints: [
            "Clear both denominators at once.",
            "Multiply both sides by (x + 2)(x − 2) — each numerator ends up with the other denominator.",
          ],
          strategy: "Make it simpler",
        },
        {
          kind: "short",
          id: "solving-equations-p2-q08",
          question: "The time period of a pendulum is {{T = 2 pi sqrt(l/g)}}. Make l the subject of the formula.",
          answer: { type: "expression", expr: "g*T^2/(4*pi^2)", display: "{{l = (g T^2)/(4 pi^2)}}" },
          solution: [
            "Divide by 2π: {{T/(2 pi) = sqrt(l/g)}}.",
            "Square both sides: {{T^2/(4 pi^2) = l/g}}.",
            "Multiply by g: {{l = (g T^2)/(4 pi^2)}}.",
          ],
          traps: [
            { spec: { type: "expression", expr: "g*T^2/(2*pi^2)" }, feedback: "When you square 2π you get {{4 pi^2}} — the 2 is squared too." },
            { spec: { type: "expression", expr: "g*T/(2*pi)" }, feedback: "You need to **square** both sides to remove the square root." },
          ],
          commonError: "Squaring π but not the 2: (2π)² = 4π², not 2π².",
          difficulty: "core",
          guideRef: "rearranging-once",
          hints: [
            "l is inside a root, inside a fraction, multiplied by 2π. Peel off the outside layers first.",
            "Divide by 2π, then square both sides.",
            "{{(2 pi)^2 = 4 pi^2}}. Finally multiply by g.",
          ],
          strategy: "Work backwards",
        },
        {
          kind: "short",
          id: "solving-equations-p2-q09",
          question: "Make w the subject of 2(w + k) = m(3 − w).",
          answer: { type: "expression", expr: "(3m-2k)/(m+2)", display: "{{w = (3m - 2k)/(m + 2)}}" },
          solution: [
            "Expand both sides: 2w + 2k = 3m − mw.",
            "Collect w terms on the left: 2w + mw = 3m − 2k.",
            "Factorise: w(2 + m) = 3m − 2k.",
            "Divide: {{w = (3m - 2k)/(m + 2)}}.",
          ],
          traps: [{ spec: { type: "expression", expr: "(3m-2k)/(2-m)" }, feedback: "Adding mw to both sides gives 2w **+** mw, so the bracket is (2 + m)." }],
          commonError: "Sign error moving −mw across.",
          difficulty: "core",
          guideRef: "rearranging-twice",
          hints: ["Expand both brackets first.", "Move every w term to the left, everything else to the right.", "Factorise out w."],
          strategy: "Collect, factorise, divide",
        },
        {
          kind: "written",
          id: "solving-equations-p2-q10",
          question:
            "Hana makes x the subject of {{y = (2x - 1)/(x + 3)}}. Her working is:\n\n    y(x + 3) = 2x − 1\n    xy + 3 = 2x − 1\n    xy − 2x = −4\n    x = {{-4/(y - 2)}}\n\nExplain the mistake she made and write the correct answer.",
          marks: 3,
          modelAnswer:
            "In line 2 Hana only multiplied the x by y. Expanding y(x + 3) gives xy + **3y**, not xy + 3.\n\nCorrect working: xy + 3y = 2x − 1, so xy − 2x = −1 − 3y, so x(y − 2) = −1 − 3y.\n\nTherefore {{x = (-1 - 3y)/(y - 2)}}, which can be written {{x = (3y + 1)/(2 - y)}}.",
          markScheme: [
            { point: "Identifies the error: y(x + 3) should expand to xy + 3y (she wrote + 3)", keywords: ["3y", "xy + 3y", "xy+3y", "expand", "bracket", "line 2"] },
            { point: "Correctly collects and factorises: x(y − 2) = −1 − 3y", keywords: ["x(y - 2)", "x(y-2)", "-1 - 3y", "-1-3y", "factorise"] },
            { point: "Correct final answer x = (3y + 1)/(2 − y) or equivalent", keywords: ["(3y+1)/(2-y)", "(3y + 1)/(2 - y)", "(-1-3y)/(y-2)", "(-1 - 3y)/(y - 2)"] },
          ],
          commonError: "Spotting the error but then making a sign slip in the correction.",
          difficulty: "core",
          guideRef: "rearranging-twice",
          hints: ["Check each line by expanding or substituting a value.", "Multiply out y(x + 3) yourself — what do you get?"],
          strategy: "Spot the error",
        },
        {
          kind: "short",
          id: "solving-equations-p2-q11",
          question: "Solve the simultaneous equations\n\n    5x + 2y = 4\n    3x + 5y = −9\n\nGive x first, then y.",
          answer: { type: "list", values: [2, -3], ordered: true, display: "x = 2, y = −3" },
          solution: [
            "Match the y coefficients: (first) × 5 gives 25x + 10y = 20; (second) × 2 gives 6x + 10y = −18.",
            "Subtract: 19x = 38, so x = 2.",
            "Substitute: 10 + 2y = 4, so y = −3.",
            "Check: 6 − 15 = −9. ✓",
          ],
          commonError: "Subtracting −18 as if it were +18: 20 − (−18) = 38.",
          difficulty: "core",
          guideRef: "simultaneous-linear",
          hints: [
            "Scale both equations so the y coefficients match (10y).",
            "Same signs → subtract. Be careful with 20 − (−18).",
          ],
          strategy: "Eliminate a variable",
        },
        {
          kind: "short",
          id: "solving-equations-p2-q12",
          question:
            "Siti has 30 coins. Each coin is either a 20-cent or a 50-cent coin. The total value of the coins is $9.30. How many 50-cent coins does she have?",
          answer: { type: "number", value: 11 },
          solution: [
            "Let a = number of 20c coins, b = number of 50c coins. Work in cents.",
            "a + b = 30 and 20a + 50b = 930.",
            "Multiply the first by 20: 20a + 20b = 600. Subtract: 30b = 330, so b = 11.",
            "Check: a = 19; 19 × 20 + 11 × 50 = 380 + 550 = 930. ✓",
          ],
          solutions: [
            {
              label: "Assume all the same, then adjust",
              steps: [
                "If all 30 were 20c coins the total would be 600c — that's 330c short.",
                "Swapping a 20c coin for a 50c coin adds 30c.",
                "330 ÷ 30 = 11 swaps, so 11 fifty-cent coins. This is elimination in disguise.",
              ],
            },
          ],
          traps: [{ spec: { type: "number", value: 19 }, feedback: "19 is the number of 20-cent coins. The question asks for 50-cent coins." }],
          commonError: "Mixing dollars and cents in the same equation (e.g. 20a + 50b = 9.30).",
          difficulty: "core",
          guideRef: "simultaneous-linear",
          hints: ["Two unknowns, two facts: the number of coins and their total value.", "Use cents throughout: 20a + 50b = 930.", "Eliminate a by multiplying a + b = 30 by 20."],
          strategy: "Introduce a variable",
        },
        {
          kind: "written",
          id: "solving-equations-p2-q13",
          question:
            "Three straight lines have equations\n\n    2y = 3x − 4\n    x + 2y = 12\n    y = 2x − 4\n\nShow that all three lines pass through the same point.",
          marks: 3,
          modelAnswer:
            "Solve the first two simultaneously. From the first, 2y = 3x − 4; substitute into the second: x + (3x − 4) = 12, so 4x = 16 and x = 4. Then 2y = 12 − 4 = 8, so y = 4.\n\nThe first two lines meet at (4, 4).\n\nCheck the third line at x = 4: y = 2(4) − 4 = 4. ✓ So (4, 4) lies on all three lines — they are concurrent.",
          markScheme: [
            { point: "Correct method to solve two of the equations simultaneously (substitution or elimination)", keywords: ["substitute", "eliminate", "4x = 16", "4x=16", "subtract", "add"] },
            { point: "Finds the intersection (4, 4)", keywords: ["(4, 4)", "(4,4)", "x = 4", "y = 4"] },
            { point: "Verifies the point satisfies the third equation and concludes", keywords: ["2(4) - 4", "8 - 4", "third", "all three", "same point", "concurrent"] },
          ],
          commonError: "Finding where two lines meet but never checking the third line.",
          difficulty: "challenge",
          guideRef: "simultaneous-linear",
          hints: [
            "Three lines meeting at one point means one point satisfies all three equations.",
            "Find where two of them meet first — notice 2y appears in both of the first two.",
            "Then substitute that point into the third equation.",
          ],
          strategy: "Check by substituting",
        },
        {
          kind: "short",
          id: "solving-equations-p2-q14",
          question:
            "At a hawker centre:\n\n- Ravi pays $6.10 for 2 roti prata, 1 teh tarik and 1 chendol.\n- Mei pays $6.50 for 1 roti prata, 2 teh tarik and 1 chendol.\n- Kenji pays $9.40 for 3 roti prata, 1 teh tarik and 2 chendol.\n\nWork out the price of one chendol in dollars.",
          answer: { type: "number", value: 2.1, display: "$2.10" },
          solution: [
            "Let p, t, c be the prices: 2p + t + c = 6.10, p + 2t + c = 6.50, 3p + t + 2c = 9.40.",
            "Eliminate c. (2) − (1): −p + t = 0.40.",
            "(3) − 2 × (1): 3p + t + 2c − 4p − 2t − 2c = 9.40 − 12.20, so −p − t = −2.80, i.e. p + t = 2.80.",
            "Add the two new equations: 2t = 3.20, so t = 1.60 and p = 1.20.",
            "From (1): c = 6.10 − 2.40 − 1.60 = 2.10. Chendol costs $2.10.",
            "Check (3): 3.60 + 1.60 + 4.20 = 9.40. ✓",
          ],
          traps: [
            { spec: { type: "number", value: 1.6 }, feedback: "$1.60 is the teh tarik. Keep going — substitute p and t back to find c." },
            { spec: { type: "number", value: 1.2 }, feedback: "$1.20 is the roti prata. Substitute back to find the chendol." },
          ],
          commonError: "Eliminating c from one pair but p from another — you need two equations in the *same* two unknowns.",
          difficulty: "challenge",
          guideRef: "simultaneous-three",
          hints: [
            "Three unknowns need three equations — write them down with letters p, t, c.",
            "Pick one letter to eliminate from two different pairs. c has small coefficients.",
            "(2) − (1) and (3) − 2 × (1) both remove c.",
            "Solve the 2 × 2 system, then substitute back into (1) for c.",
          ],
          strategy: "Make it simpler",
        },
        {
          kind: "written",
          id: "solving-equations-p2-q15",
          question:
            "(a) Make x the subject of {{y = (x + 1)/(x - 1)}}.\n\n(b) Hence explain why y can never equal 1.",
          marks: 3,
          modelAnswer:
            "(a) y(x − 1) = x + 1, so xy − y = x + 1, so xy − x = y + 1, so x(y − 1) = y + 1 and {{x = (y + 1)/(y - 1)}}.\n\n(b) If y = 1, the formula for x would need division by y − 1 = 0, which is impossible — so no value of x gives y = 1.\n\nDirectly: {{(x + 1)/(x - 1) = 1}} would mean x + 1 = x − 1, i.e. 1 = −1, which is false.",
          markScheme: [
            { point: "Multiplies out and collects x terms: x(y − 1) = y + 1", keywords: ["x(y - 1)", "x(y-1)", "xy - x", "xy-x", "factorise"] },
            { point: "Correct subject: x = (y + 1)/(y − 1)", keywords: ["(y+1)/(y-1)", "(y + 1)/(y - 1)"] },
            { point: "Explains y = 1 would give division by zero (or leads to 1 = −1), so impossible", keywords: ["divide by zero", "division by zero", "y - 1 = 0", "y-1=0", "1 = -1", "impossible", "undefined"] },
          ],
          commonError: "Saying 'because x can't be 1' — that's a different restriction (on x, not y).",
          difficulty: "challenge",
          guideRef: "rearranging-twice",
          hints: [
            "For (a): multiply by (x − 1), then collect the x terms.",
            "Look at your answer to (a). What happens to the denominator when y = 1?",
            "Alternatively, set the original fraction equal to 1 and try to solve.",
          ],
          strategy: "Consider extremes",
        },
      ],
    },
  ],

  // =========================================================================
  // Challenge set — 10 AoPS-style problems
  // =========================================================================
  challenge: [
    {
      kind: "short",
      id: "solving-equations-ch-q01",
      question: "Solve {{(x - 1)/5 + (x - 2)/4 + (x - 3)/3 = 3}}.",
      answer: { type: "number", value: 6, display: "x = 6" },
      solution: [
        "Write 3 as 1 + 1 + 1 and subtract 1 from each fraction:",
        "{{((x - 1)/5 - 1) + ((x - 2)/4 - 1) + ((x - 3)/3 - 1) = 0}}.",
        "Each bracket becomes {{(x - 6)/5}}, {{(x - 6)/4}}, {{(x - 6)/3}}.",
        "So {{(x - 6)(1/5 + 1/4 + 1/3) = 0}}. The second factor is positive, so x − 6 = 0 and x = 6.",
      ],
      solutions: [
        {
          label: "Brute force: clear the denominators",
          steps: [
            "LCD of 5, 4, 3 is 60: 12(x − 1) + 15(x − 2) + 20(x − 3) = 180.",
            "12x − 12 + 15x − 30 + 20x − 60 = 180, so 47x − 102 = 180.",
            "47x = 282 and x = 6. Reliable, but the first method reveals *why* the answer is so neat.",
          ],
        },
      ],
      traps: [{ spec: { type: "number", value: 2 }, feedback: "Substitute to check: {{1/5 + 0 + (-1/3)}} is nowhere near 3." }],
      difficulty: "challenge",
      guideRef: "linear-equations",
      hints: [
        "You could multiply by 60 — but look for something slicker first. Notice the pattern in the numerators and denominators.",
        "Try simplifying {{(x - 1)/5 - 1}}. Then {{(x - 2)/4 - 1}}. Anything in common?",
        "Split the 3 into 1 + 1 + 1 and give one to each fraction.",
        "Every fraction becomes (x − 6) over something.",
      ],
      strategy: "Find a pattern",
    },
    {
      kind: "short",
      id: "solving-equations-ch-q02",
      question:
        "The digits of a two-digit number add up to 11. When the digits are reversed, the new number is 27 more than the original. Find the original number.",
      answer: { type: "number", value: 47 },
      solution: [
        "Let the number be 10a + b (tens digit a, units digit b). Then a + b = 11.",
        "Reversed: 10b + a. So (10b + a) − (10a + b) = 27, i.e. 9b − 9a = 27, so b − a = 3.",
        "Add the equations: 2b = 14, b = 7; then a = 4. The number is 47.",
        "Check: 74 − 47 = 27. ✓",
      ],
      solutions: [
        {
          label: "Use the 'reverse-difference' fact",
          steps: [
            "Reversing a two-digit number always changes it by 9 × (difference of the digits).",
            "27 = 9 × 3, so the units digit is 3 more than the tens digit.",
            "Digits adding to 11 and differing by 3: 4 and 7, so 47.",
          ],
        },
      ],
      traps: [{ spec: { type: "number", value: 74 }, feedback: "74 is the reversed number. Reversing makes it *bigger*, so the original has the smaller tens digit." }],
      difficulty: "challenge",
      guideRef: "simultaneous-linear",
      hints: [
        "How do you write a two-digit number with digits a and b algebraically? (It isn't ab.)",
        "Tens digit a, units digit b: the number is 10a + b.",
        "Reversed, it's 10b + a. Write the '27 more' fact and simplify — everything is a multiple of 9.",
      ],
      strategy: "Introduce a variable",
    },
    {
      kind: "short",
      id: "solving-equations-ch-q03",
      question: "Given that {{(a + b)/(a - b) = 5}}, find the ratio a : b in its simplest form.",
      answer: { type: "ratio", parts: [3, 2], simplest: true, display: "3 : 2" },
      solution: [
        "Multiply by (a − b): a + b = 5a − 5b.",
        "Collect: 6b = 4a, so 3b = 2a.",
        "So {{a/b = 3/2}} and a : b = 3 : 2.",
        "Check with a = 3, b = 2: {{5/1 = 5}}. ✓",
      ],
      solutions: [
        {
          label: "Componendo–dividendo",
          steps: [
            "If {{p/q = 5/1}} then {{(p + q)/(p - q) = 6/4}}.",
            "With p = a + b, q = a − b: p + q = 2a and p − q = 2b, so {{a/b = 6/4 = 3/2}}.",
            "A neat trick from classical geometry — but the direct method is what an examiner expects.",
          ],
        },
      ],
      traps: [{ spec: { type: "ratio", parts: [2, 3] }, feedback: "Reversed. From 6b = 4a, a is the bigger one: try a = 3, b = 2 in the original." }],
      difficulty: "challenge",
      guideRef: "rearranging-twice",
      hints: [
        "You can't find a and b separately — only how they compare. Clear the fraction first.",
        "a + b = 5a − 5b. Collect a's on one side and b's on the other.",
        "4a = 6b. What is {{a/b}}?",
      ],
      strategy: "Collect, factorise, divide",
    },
    {
      kind: "short",
      id: "solving-equations-ch-q04",
      question:
        "The formula {{y = (kx + 5)/(3x - 4)}} has a special property: when you make x the subject, you get **exactly the same formula** with x and y swapped. Find the value of the constant k.",
      answer: { type: "number", value: 4, display: "k = 4" },
      solution: [
        "Multiply by (3x − 4): 3xy − 4y = kx + 5.",
        "Collect x terms: 3xy − kx = 4y + 5, so x(3y − k) = 4y + 5.",
        "So {{x = (4y + 5)/(3y - k)}}.",
        "For this to be the original formula with x and y swapped, {{(ky + 5)/(3y - 4)}}, we need k = 4 (both in the numerator and the denominator — consistent).",
      ],
      solutions: [
        {
          label: "Test a point",
          steps: [
            "If the formula is its own inverse, then whenever (x, y) fits, so does (y, x).",
            "x = 0 gives {{y = -5/4}}. So x = {{-5/4}} must give y = 0: k({{-5/4}}) + 5 = 0, so k = 4.",
            "Quick — but you should then confirm k = 4 really works for all x, which the algebra does.",
          ],
        },
      ],
      traps: [{ spec: { type: "number", value: -4 }, feedback: "Check your signs when collecting: 3xy − kx = 4y + 5 gives the denominator 3y − k." }],
      difficulty: "challenge",
      guideRef: "rearranging-twice",
      hints: [
        "Just do it: make x the subject, keeping k as a letter.",
        "x(3y − k) = 4y + 5.",
        "Compare {{(4y + 5)/(3y - k)}} with the original written in y: {{(ky + 5)/(3y - 4)}}.",
      ],
      strategy: "Use symmetry",
    },
    {
      kind: "short",
      id: "solving-equations-ch-q05",
      question: "For which value of k do the simultaneous equations\n\n    kx + 3y = 6\n    4x + 6y = 5\n\nhave **no** solution?",
      answer: { type: "number", value: 2, display: "k = 2" },
      solution: [
        "No solution means the lines are parallel but different: same gradient, different intercept.",
        "Rewrite: {{y = -k/3 x + 2}} and {{y = -2/3 x + 5/6}}.",
        "Same gradient: {{k/3 = 2/3}}, so k = 2.",
        "Then the equations are 2x + 3y = 6 and 2x + 3y = 2.5 — contradictory, so no solution. ✓",
      ],
      solutions: [
        {
          label: "Eliminate and look for 0 = something",
          steps: [
            "Double the first: 2kx + 6y = 12. Subtract the second: (2k − 4)x = 7.",
            "If 2k − 4 ≠ 0 we can divide and find x. If 2k − 4 = 0 we get 0 = 7 — impossible.",
            "So no solution exactly when k = 2.",
          ],
        },
      ],
      traps: [{ spec: { type: "number", value: 8 }, feedback: "For parallel lines compare the *ratio* of coefficients: k : 3 must equal 4 : 6, so k = 2." }],
      difficulty: "challenge",
      guideRef: "simultaneous-linear",
      hints: [
        "Think graphically: when do two straight lines never meet?",
        "Parallel lines have the same gradient. Find each gradient in terms of k.",
        "Alternatively, eliminate y and see when the x coefficient vanishes.",
      ],
      strategy: "Draw a diagram",
    },
    {
      kind: "short",
      id: "solving-equations-ch-q06",
      question:
        "Solve the simultaneous equations\n\n    2024x + 2026y = 6074\n    2026x + 2024y = 6076\n\nGive x first, then y.",
      answer: { type: "list", values: [2, 1], ordered: true, display: "x = 2, y = 1" },
      solution: [
        "Add the equations: 4050x + 4050y = 12150, so x + y = 3.",
        "Subtract the first from the second: 2x − 2y = 2, so x − y = 1.",
        "Add these: 2x = 4, x = 2; then y = 1.",
        "Check: 4048 + 2026 = 6074. ✓",
      ],
      solutions: [
        {
          label: "Standard elimination (painful)",
          steps: [
            "Multiply the first by 2026 and the second by 2024 and subtract… the numbers become millions.",
            "It works, but the symmetry shortcut takes four lines. When coefficients swap places, **add and subtract**.",
          ],
        },
      ],
      traps: [{ spec: { type: "list", values: [1, 2], ordered: true }, feedback: "Swapped. x − y = 1, so x is the bigger one." }],
      difficulty: "challenge",
      guideRef: "simultaneous-linear",
      hints: [
        "Don't multiply big numbers! Notice the coefficients swap places between the equations.",
        "What happens if you add the two equations? What if you subtract them?",
        "You get x + y = 3 and x − y = 1.",
      ],
      strategy: "Use symmetry",
    },
    {
      kind: "short",
      id: "solving-equations-ch-q07",
      question: "Solve the simultaneous equations\n\n    {{3/x + 2/y = 2}}\n    {{5/x - 4/y = 7}}\n\nGive x first, then y.",
      answer: { type: "list", values: [1, -2], ordered: true, display: "x = 1, y = −2" },
      solution: [
        "Let {{a = 1/x}} and {{b = 1/y}}: 3a + 2b = 2 and 5a − 4b = 7. Now they're linear!",
        "Double the first: 6a + 4b = 4. Add to the second: 11a = 11, so a = 1.",
        "Then 3 + 2b = 2, so {{b = -1/2}}.",
        "So x = {{1/a}} = 1 and y = {{1/b}} = −2.",
        "Check: 3 + 2 ÷ (−2) = 3 − 1 = 2 ✓; 5 − 4 ÷ (−2) = 5 + 2 = 7 ✓.",
      ],
      traps: [{ spec: { type: "list", values: [1, -0.5], ordered: true }, feedback: "{{-1/2}} is the value of {{1/y}}, not y. Flip it back." }],
      difficulty: "challenge",
      guideRef: "simultaneous-linear",
      hints: [
        "These aren't linear in x and y… but they are linear in something else.",
        "Introduce new variables a = {{1/x}} and b = {{1/y}}.",
        "Solve for a and b, then remember to take reciprocals.",
      ],
      strategy: "Introduce a variable",
    },
    {
      kind: "short",
      id: "solving-equations-ch-q08",
      question: "Three numbers a, b and c satisfy\n\n    a + b = 11\n    b + c = 15\n    c + a = 16\n\nFind the value of abc.",
      answer: { type: "number", value: 300 },
      solution: [
        "Add all three equations: 2a + 2b + 2c = 42, so a + b + c = 21.",
        "Subtract each original from this: c = 21 − 11 = 10, a = 21 − 15 = 6, b = 21 − 16 = 5.",
        "abc = 6 × 5 × 10 = 300.",
      ],
      solutions: [
        {
          label: "Substitute along the chain",
          steps: [
            "From the first, b = 11 − a. Then c = 15 − b = 4 + a.",
            "Third: (4 + a) + a = 16, so a = 6, b = 5, c = 10.",
            "Works fine — but adding all three uses the cyclic symmetry and is faster.",
          ],
        },
      ],
      traps: [{ spec: { type: "number", value: 21 }, feedback: "21 is a + b + c. The question asks for the product abc." }],
      difficulty: "challenge",
      guideRef: "simultaneous-three",
      hints: [
        "Each letter appears in exactly two equations. What if you add all three?",
        "2(a + b + c) = 42.",
        "Now take away each equation from a + b + c = 21 to get each letter on its own.",
      ],
      strategy: "Use symmetry",
    },
    {
      kind: "short",
      id: "solving-equations-ch-q09",
      question:
        "The curve {{y = ax^2 + bx + c}} passes through the points (1, 4), (2, 9) and (−1, 6). Find a, b and c. Give your answer as a, b, c in that order.",
      answer: { type: "list", values: [2, -1, 3], ordered: true, display: "a = 2, b = −1, c = 3" },
      solution: [
        "Substitute each point: a + b + c = 4; 4a + 2b + c = 9; a − b + c = 6.",
        "First − third: 2b = −2, so b = −1.",
        "Second − first: 3a + b = 5, so 3a = 6 and a = 2.",
        "c = 4 − a − b = 4 − 2 + 1 = 3.",
        "Check (2, 9): 8 − 2 + 3 = 9 ✓; (−1, 6): 2 + 1 + 3 = 6 ✓.",
      ],
      commonError: "Substituting x = −1 as −1 for {{x^2}} too: (−1)² = +1.",
      difficulty: "challenge",
      guideRef: "simultaneous-three",
      hints: [
        "Each point gives one equation in a, b and c.",
        "Points (1, 4) and (−1, 6) give equations that differ only in the sign of b — subtract them.",
        "Then subtract the (1, 4) equation from the (2, 9) equation to remove c.",
      ],
      strategy: "Make it simpler",
    },
    {
      kind: "short",
      id: "solving-equations-ch-q10",
      question:
        "Kenji cycles from home to school. At 15 km/h he arrives 4 minutes late. At 20 km/h he arrives 2 minutes early. How far is it from home to school? Give your answer in km.",
      answer: { type: "number", value: 6, display: "6 km" },
      solution: [
        "Let the distance be d km. The two journey times differ by 4 + 2 = 6 minutes = {{1/10}} hour.",
        "{{d/15 - d/20 = 1/10}}.",
        "Multiply by 60: 4d − 3d = 6, so d = 6 km.",
        "Check: 6 km takes 24 min at 15 km/h and 18 min at 20 km/h — a 6-minute difference. ✓",
      ],
      solutions: [
        {
          label: "Simultaneous equations with the 'on-time' time",
          steps: [
            "Let T hours be the time that gets him there exactly on time.",
            "{{d = 15(T + 1/15)}} and {{d = 20(T - 1/30)}} (4 min = {{1/15}} h, 2 min = {{1/30}} h).",
            "15T + 1 = 20T − {{2/3}}, so 5T = {{5/3}}, T = {{1/3}} h and d = 15 × {{2/5}} = 6 km. Longer, but you also learn he needs 20 minutes.",
          ],
        },
      ],
      traps: [
        { spec: { type: "number", value: 360 }, feedback: "Units! The 6 minutes must be converted to hours ({{1/10}} h) before using speeds in km/h." },
        { spec: { type: "number", value: 2 }, feedback: "The two times differ by 4 + 2 = 6 minutes — late *and* early are on opposite sides of the on-time arrival." },
      ],
      commonError: "Using 2 minutes (4 − 2) as the time difference instead of 6.",
      difficulty: "challenge",
      guideRef: "linear-equations",
      hints: [
        "How many minutes apart are the two arrival times?",
        "4 minutes late and 2 minutes early differ by 6 minutes. Convert that to hours.",
        "Time = distance ÷ speed. Write an equation for the difference in times.",
      ],
      strategy: "Introduce a variable",
    },
  ],
};
