// Functions — MCQ papers (3 × 15). Options are shuffled at display time.
import type { Paper } from "../../types.ts";

export const mcqPapers: Paper[] = [
  {
    id: "functions-m1",
    title: "MCQ Paper 1",
    questions: [
      {
        kind: "mcq",
        id: "functions-m1-q01",
        question: "f(x) = 3x − 7. Work out f(−2).",
        options: ["−13", "−1", "1", "13"],
        answerIndex: 0,
        explanation: "f(−2) means \"replace every x with −2\": 3 × (−2) − 7 = −6 − 7 = −13. −1 comes from using +2 instead of −2 (6 − 7). 1 comes from −6 − 7 being treated as −6 + 7. 13 has both signs flipped.",
        difficulty: "warmup",
        guideRef: "functions-as-mappings",
        hints: ["Put −2 in brackets wherever you see x: 3 × (−2) − 7. What is 3 × (−2)?"],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "functions-m1-q02",
        question: "g(x) = {{x^2 + 4}}. Work out g(−3).",
        options: ["−5", "13", "−2", "7"],
        answerIndex: 1,
        explanation: "{{(-3)^2 = 9}} (a negative times a negative is positive), so g(−3) = 9 + 4 = 13. −5 comes from writing {{(-3)^2}} as −9. −2 treats {{x^2}} as 2x. 7 forgets to square at all (3 + 4).",
        difficulty: "warmup",
        guideRef: "functions-as-mappings",
        hints: ["Square −3 with a bracket: {{(-3)^2}}. Is the result positive or negative?"],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "functions-m1-q03",
        question: "The function f is defined as f: x ↦ 5 − 2x. Given that f(a) = 11, find the value of a.",
        options: ["3", "8", "−3", "−17"],
        answerIndex: 2,
        explanation: "f(a) = 11 means 5 − 2a = 11, so −2a = 6 and a = −3. Check: 5 − 2(−3) = 5 + 6 = 11 ✓. −17 is f(11) — that answers a different question (input 11, not output 11). 3 is the sign slip when dividing 6 by −2. 8 comes from (11 + 5) ÷ 2, undoing the operations with the wrong signs.",
        difficulty: "warmup",
        guideRef: "functions-as-mappings",
        hints: ["11 is the **output**. Write the equation 5 − 2a = 11 and solve it."],
        strategy: "Work backwards",
      },
      {
        kind: "mcq",
        id: "functions-m1-q04",
        question: "f(x) = {{1/(x - 4)}}. Which value of x must be excluded from the domain of f?",
        options: ["x = −4", "x = 0", "x = {{1/4}}", "x = 4"],
        answerIndex: 3,
        explanation: "You cannot divide by zero, and the denominator x − 4 is zero when x = 4, so x = 4 must be excluded. x = −4 is the sign slip (x − 4 = 0 gives x = +4). x = 0 is fine: f(0) = {{-1/4}}. x = {{1/4}} gives a perfectly good output too.",
        difficulty: "warmup",
        guideRef: "domain-range",
        hints: ["Which value of x would make the denominator equal to zero?"],
        strategy: "Consider extremes",
      },
      {
        kind: "mcq",
        id: "functions-m1-q05",
        question: "f(x) = 2x + 1 and g(x) = {{x^2}}. Work out fg(3).",
        options: ["19", "49", "63", "37"],
        answerIndex: 0,
        explanation: "fg(3) = f(g(3)): do **g first**. g(3) = 9, then f(9) = 2 × 9 + 1 = 19. 49 is gf(3) = {{7^2}} — the functions applied in the wrong order. 63 multiplies f(3) × g(3) = 7 × 9; fg is not a product. 37 comes from writing fg(x) as {{(2x)^2 + 1}}, squaring the 2 as well.",
        difficulty: "core",
        guideRef: "composite-functions",
        hints: [
          "fg(3) means f(g(3)). Which function acts on 3 first?",
          "Work out g(3) first, then feed that answer into f.",
        ],
        strategy: "Work from the inside out",
      },
      {
        kind: "mcq",
        id: "functions-m1-q06",
        question: "f(x) = 3x − 2 and g(x) = x + 5. Find fg(x).",
        options: ["{{3x + 3}}", "{{3x + 13}}", "{{3x + 7}}", "{{3x^2 + 13x - 10}}"],
        answerIndex: 1,
        explanation: "fg(x) = f(x + 5): replace the x in f with the whole of (x + 5): 3(x + 5) − 2 = 3x + 15 − 2 = 3x + 13. 3x + 3 is gf(x) = (3x − 2) + 5 — the wrong order. 3x + 7 forgets to multiply the 5 by 3 (no bracket). {{3x^2 + 13x - 10}} is the product (3x − 2)(x + 5), which is not a composite.",
        difficulty: "core",
        guideRef: "composite-functions",
        hints: [
          "fg(x) = f(g(x)) = f(x + 5). What goes in place of x in f?",
          "Write 3(x + 5) − 2 with the bracket, then expand.",
        ],
        strategy: "Work from the inside out",
      },
      {
        kind: "mcq",
        id: "functions-m1-q07",
        question: "f(x) = 5x − 3. Find {{f^(-1)(x)}}.",
        options: ["{{1/(5x - 3)}}", "{{x/5 + 3}}", "{{(x + 3)/5}}", "{{(x - 3)/5}}"],
        answerIndex: 2,
        explanation: "Let y = 5x − 3. Rearrange: y + 3 = 5x, so x = {{(y + 3)/5}}. Swap the letters: {{f^(-1)(x) = (x + 3)/5}}. Check: f(1) = 2 and {{f^(-1)(2) = 5/5 = 1}} ✓. {{1/(5x - 3)}} is the reciprocal — the −1 in {{f^(-1)}} is **not** a power. {{x/5 + 3}} undoes the steps in the wrong order (÷5 then +3). {{(x - 3)/5}} repeats the −3 instead of reversing it.",
        difficulty: "core",
        guideRef: "inverse-functions",
        hints: [
          "Write y = 5x − 3 and make x the subject.",
          "f does ×5 then −3. The inverse undoes these in reverse order: +3 then ÷5.",
        ],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "functions-m1-q08",
        question: "g(x) = {{sqrt(x - 6)}}. Which values of x must be excluded from the domain of g?",
        options: ["x ≤ 6", "x < −6", "x > 6", "x < 6"],
        answerIndex: 3,
        explanation: "You can't take the square root of a negative number, so x − 6 must be ≥ 0, i.e. x ≥ 6. The excluded values are x < 6. x ≤ 6 wrongly excludes x = 6, but g(6) = {{sqrt(0)}} = 0 is fine. x < −6 is the sign slip. x > 6 lists the values that are **allowed**, not excluded.",
        difficulty: "core",
        guideRef: "domain-range",
        hints: [
          "What can't go inside a square root?",
          "Solve x − 6 < 0. Is x = 6 itself a problem?",
        ],
        strategy: "Consider extremes",
      },
      {
        kind: "mcq",
        id: "functions-m1-q09",
        question: "f(x) = {{x^2 + 3}}, where x can be any real number. Which of these is the range of f?",
        options: ["f(x) ≥ 3", "f(x) ≥ 0", "f(x) > 3", "f(x) ≥ −3"],
        answerIndex: 0,
        explanation: "{{x^2}} is never negative and equals 0 when x = 0, so the smallest output is 0 + 3 = 3, and every value above 3 is reached. Range: f(x) ≥ 3. f(x) > 3 forgets that 3 itself is reached (f(0) = 3). f(x) ≥ 0 is the range of {{x^2}}, ignoring the +3. f(x) ≥ −3 has the wrong sign on the shift.",
        difficulty: "core",
        guideRef: "domain-range",
        hints: [
          "What is the smallest possible value of {{x^2}}?",
          "Add 3 to that smallest value. Is that output actually reached?",
        ],
        strategy: "Consider extremes",
      },
      {
        kind: "mcq",
        id: "functions-m1-q10",
        question: "f(x) = 2x − 1 and g(x) = x + 3. Solve fg(x) = 15.",
        options: ["x = 6.5", "x = 5", "x = 35", "x = 10"],
        answerIndex: 1,
        explanation: "fg(x) = f(x + 3) = 2(x + 3) − 1 = 2x + 5. Then 2x + 5 = 15 gives x = 5. Check: g(5) = 8, f(8) = 15 ✓. x = 6.5 solves gf(x) = 2x + 2 = 15 — the wrong order. 35 is fg(15): the 15 is the **output**, not the input. x = 10 comes from 2x = 15 + 5, a sign slip.",
        difficulty: "core",
        guideRef: "composite-functions",
        hints: [
          "First find fg(x) as an expression in x.",
          "fg(x) = 2(x + 3) − 1. Simplify, then set it equal to 15.",
        ],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "functions-m1-q11",
        question: "f(x) = {{(x - 2)/4}}. Work out {{f^(-1)(5)}}.",
        options: ["{{3/4}}", "{{4/3}}", "22", "18"],
        answerIndex: 2,
        explanation: "{{f^(-1)(5)}} is the input that gives an output of 5: {{(x - 2)/4 = 5}}, so x − 2 = 20 and x = 22. (Or {{f^(-1)(x) = 4x + 2}}, so {{f^(-1)(5) = 22}}.) {{3/4}} is f(5), not {{f^(-1)(5)}}. {{4/3}} is {{1/f(5)}} — treating the −1 as a power. 18 = 4 × 5 − 2 reverses the operations but keeps the −2 instead of changing it to +2.",
        difficulty: "core",
        guideRef: "inverse-functions",
        hints: [
          "{{f^(-1)(5)}} asks: which input makes f give 5?",
          "Solve {{(x - 2)/4 = 5}}.",
        ],
        strategy: "Work backwards",
      },
      {
        kind: "mcq",
        id: "functions-m1-q12",
        question: "A function maps each input to **exactly one** output. Which of these mappings is **not** a function?",
        options: ["x ↦ {{x^2}}", "x ↦ 3 (for every x)", "x ↦ {{x^3 - x}}", "x ↦ ±{{sqrt(x)}} (for x > 0)"],
        answerIndex: 3,
        explanation: "x ↦ ±{{sqrt(x)}} sends 4 to both 2 and −2 — one input with two outputs, so it is not a function. x ↦ {{x^2}} sends 3 and −3 to the same output 9: many-to-one is allowed. x ↦ 3 is a constant function — every input has exactly one output (it just happens to be the same one). x ↦ {{x^3 - x}} gives one value for each x.",
        difficulty: "core",
        guideRef: "functions-as-mappings",
        hints: [
          "For each mapping, pick an input such as 4 and count the outputs.",
          "Two inputs sharing an output is fine. What is **not** allowed?",
        ],
        strategy: "Try small cases",
      },
      {
        kind: "mcq",
        id: "functions-m1-q13",
        question: "f(x) = x + 2 and g(x) = {{x^2}}. Solve gf(x) = fg(x).",
        options: ["x = {{-1/2}}", "x = −1", "x = 0", "There is no value of x"],
        answerIndex: 0,
        explanation: "gf(x) = {{(x + 2)^2 = x^2 + 4x + 4}} and fg(x) = {{x^2 + 2}}. Setting them equal, the {{x^2}} terms cancel: 4x + 4 = 2, so 4x = −2 and x = {{-1/2}}. Check: gf({{-1/2}}) = {{(3/2)^2 = 9/4}} and fg({{-1/2}}) = {{1/4 + 2 = 9/4}} ✓. x = −1 comes from 4x + 4 = 0 (dropping the 2 on the right). \"No value\" comes from writing {{(x + 2)^2}} as {{x^2 + 4}}, which leaves the impossible 4 = 2. x = 0 comes from expanding {{(x + 2)^2}} as {{x^2 + 2x + 2}}.",
        difficulty: "challenge",
        guideRef: "composite-functions",
        hints: [
          "Write gf(x) and fg(x) separately. Which one has a bracket squared?",
          "{{(x + 2)^2}} has three terms when expanded — don't forget the middle one.",
          "The {{x^2}} terms cancel, leaving a linear equation.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "functions-m1-q14",
        question: "f(x) = {{(ax + 2)/(x - 3)}}, x ≠ 3, where a is a constant. f is **self-inverse** ({{f^(-1)(x) = f(x)}}). Find the value of a.",
        options: ["a = −3", "a = 3", "a = 2", "a = {{2/3}}"],
        answerIndex: 1,
        explanation: "Let y = {{(ax + 2)/(x - 3)}}. Then xy − 3y = ax + 2, so x(y − a) = 3y + 2 and {{f^(-1)(x) = (3x + 2)/(x - a)}}. For this to equal {{(ax + 2)/(x - 3)}} for every x we need a = 3. Check with a = 3: f(0) = {{-2/3}} and f({{-2/3}}) = {{(-2 + 2)/(-2/3 - 3) = 0}} ✓ — f takes you back where you started. a = −3 is a sign slip when collecting the x terms. a = 2 and a = {{2/3}} come from matching the wrong coefficients.",
        difficulty: "challenge",
        guideRef: "inverse-functions",
        hints: [
          "Find {{f^(-1)(x)}} in terms of a: set y = f(x) and make x the subject.",
          "Multiply out y(x − 3) = ax + 2 and collect the x terms on one side.",
          "Compare {{f^(-1)(x) = (3x + 2)/(x - a)}} with f(x). What must a be?",
        ],
        strategy: "Use symmetry",
      },
      {
        kind: "mcq",
        id: "functions-m1-q15",
        question: "f(x) = {{2x^2 + 8x + 5}} with domain x ≥ 0. Which of these is the range of f?",
        options: ["f(x) ≥ −3", "f(x) ≥ 0", "f(x) ≥ 5", "f(x) ≥ 1"],
        answerIndex: 2,
        explanation: "Completing the square, f(x) = {{2(x + 2)^2 - 3}}, so the vertex is at (−2, −3). But −2 is **not in the domain**. For x ≥ 0 the curve is to the right of its vertex, so f is increasing and the least value is f(0) = 5. Range: f(x) ≥ 5. f(x) ≥ −3 would be the range for all real x — it ignores the restricted domain. f(x) ≥ 0 copies the domain across. f(x) ≥ 1 comes from completing the square without multiplying the 4 by 2.",
        difficulty: "challenge",
        guideRef: "domain-range",
        hints: [
          "Where is the turning point of {{y = 2x^2 + 8x + 5}}? Complete the square.",
          "Is the x-coordinate of the turning point allowed by the domain x ≥ 0?",
          "If not, is f increasing or decreasing for x ≥ 0? Where is its smallest value?",
        ],
        strategy: "Draw a diagram",
      },
    ],
  },
  {
    id: "functions-m2",
    title: "MCQ Paper 2",
    questions: [
      {
        kind: "mcq",
        id: "functions-m2-q01",
        question: "The mapping diagram shows the function f. Which rule could f have?",
        diagram: `<svg viewBox="0 0 360 260" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Mapping diagram for f: inputs 1, 2, 3, 4 map to outputs 3, 5, 7, 9 respectively"><rect x="0" y="0" width="360" height="260" fill="#ffffff"/><ellipse cx="80" cy="135" rx="45" ry="105" fill="#c7d2fe" stroke="#334155" stroke-width="1.5"/><ellipse cx="280" cy="135" rx="45" ry="105" fill="#bbf7d0" stroke="#334155" stroke-width="1.5"/><text x="80" y="22" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">Input x</text><text x="280" y="22" font-size="13" text-anchor="middle" font-family="sans-serif" fill="#1f2937">Output f(x)</text><text x="80" y="80" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937">1</text><text x="280" y="80" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937">3</text><line x1="96" y1="75" x2="256" y2="75" stroke="#1f2937" stroke-width="1.5"/><polygon points="264,75 254,70 254,80" fill="#1f2937"/><text x="80" y="120" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937">2</text><text x="280" y="120" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937">5</text><line x1="96" y1="115" x2="256" y2="115" stroke="#1f2937" stroke-width="1.5"/><polygon points="264,115 254,110 254,120" fill="#1f2937"/><text x="80" y="160" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937">3</text><text x="280" y="160" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937">7</text><line x1="96" y1="155" x2="256" y2="155" stroke="#1f2937" stroke-width="1.5"/><polygon points="264,155 254,150 254,160" fill="#1f2937"/><text x="80" y="200" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937">4</text><text x="280" y="200" font-size="14" text-anchor="middle" font-family="sans-serif" fill="#1f2937">9</text><line x1="96" y1="195" x2="256" y2="195" stroke="#1f2937" stroke-width="1.5"/><polygon points="264,195 254,190 254,200" fill="#1f2937"/><text x="180" y="250" font-size="14" text-anchor="middle" font-style="italic" font-family="sans-serif" fill="#1f2937">f</text></svg>`,
        options: ["f(x) = x + 2", "f(x) = 3x", "f(x) = 2x − 1", "f(x) = 2x + 1"],
        answerIndex: 3,
        explanation: "Test every pair: 2 × 1 + 1 = 3, 2 × 2 + 1 = 5, 2 × 3 + 1 = 7, 2 × 4 + 1 = 9 ✓. x + 2 and 3x both fit 1 ↦ 3 only (2 + 2 = 4, not 5; 3 × 2 = 6, not 5). 2x − 1 gives 1, 3, 5, 7 — every output 2 too small. A rule must work for **every** arrow, not just the first.",
        difficulty: "warmup",
        guideRef: "functions-as-mappings",
        hints: ["The outputs go up by 2 each time the input goes up by 1. Test each rule on **all four** arrows."],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "functions-m2-q02",
        question: "f(x) = {{x^2 - 2x}}. Work out f(3) + f(−1).",
        options: ["0", "2", "6", "4"],
        answerIndex: 2,
        explanation: "f(3) = 9 − 6 = 3 and f(−1) = {{(-1)^2 - 2(-1)}} = 1 + 2 = 3, so the total is 6. 0 is f(2): adding the inputs first (3 + (−1) = 2) — f(3) + f(−1) is **not** f(3 + (−1)). 2 comes from f(−1) = 1 − 2 = −1 (sign slip on −2 × −1). 4 comes from {{(-1)^2}} = −1.",
        difficulty: "warmup",
        guideRef: "functions-as-mappings",
        hints: ["Work out f(3) and f(−1) separately, using brackets for −1, then add."],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "functions-m2-q03",
        question: "f(x) = x − 5 and g(x) = 3x. Work out gf(4).",
        options: ["7", "−3", "−12", "−1"],
        answerIndex: 1,
        explanation: "gf(4) = g(f(4)): f acts first. f(4) = −1, then g(−1) = −3. 7 is fg(4) = 12 − 5, the wrong order. −12 is f(4) × g(4) = −1 × 12, a product not a composite. −1 is just f(4) — g was never applied.",
        difficulty: "warmup",
        guideRef: "composite-functions",
        hints: ["gf(4) = g(f(4)). The function nearest the 4 acts first."],
        strategy: "Work from the inside out",
      },
      {
        kind: "mcq",
        id: "functions-m2-q04",
        question: "f(x) = 4x + 1. Work out {{f^(-1)(9)}}.",
        options: ["2", "37", "{{1/37}}", "2.5"],
        answerIndex: 0,
        explanation: "{{f^(-1)(9)}} is the input that f sends to 9: 4x + 1 = 9, so x = 2. Check: f(2) = 9 ✓. 37 is f(9), going the wrong way. {{1/37}} is {{1/f(9)}} — the −1 is not a power. 2.5 = (9 + 1) ÷ 4 adds 1 instead of subtracting it.",
        difficulty: "warmup",
        guideRef: "inverse-functions",
        hints: ["Which input x makes 4x + 1 = 9?"],
        strategy: "Work backwards",
      },
      {
        kind: "mcq",
        id: "functions-m2-q05",
        question: "f(x) = {{6/(2x + 5)}}. Which value of x must be excluded from the domain of f?",
        options: ["x = 2.5", "x = −5", "x = 0", "x = −2.5"],
        answerIndex: 3,
        explanation: "The denominator is zero when 2x + 5 = 0, i.e. x = −2.5, and division by zero is impossible. x = 2.5 is the sign slip. x = −5 forgets to divide by 2. x = 0 is fine: f(0) = {{6/5}}.",
        difficulty: "core",
        guideRef: "domain-range",
        hints: [
          "Which value of x makes the denominator zero?",
          "Solve 2x + 5 = 0 carefully — two steps.",
        ],
        strategy: "Consider extremes",
      },
      {
        kind: "mcq",
        id: "functions-m2-q06",
        question: "f(x) = {{x^2}} and g(x) = x − 3. Which expression is gf(x)?",
        options: ["{{(x - 3)^2}}", "{{x^2 - 9}}", "{{x^2 - 3}}", "{{x^3 - 3x^2}}"],
        answerIndex: 2,
        explanation: "gf(x) = g(f(x)) = g({{x^2}}) = {{x^2 - 3}}: square first, then subtract 3. {{(x - 3)^2}} is fg(x) — subtract first, then square. {{x^2 - 9}} is a wrong expansion of {{(x - 3)^2}}. {{x^3 - 3x^2}} is the product {{x^2(x - 3)}}, not a composite.",
        difficulty: "core",
        guideRef: "composite-functions",
        hints: [
          "In gf(x), which function is applied to x first?",
          "f(x) = {{x^2}}. Now put {{x^2}} into g.",
        ],
        strategy: "Work from the inside out",
      },
      {
        kind: "mcq",
        id: "functions-m2-q07",
        question: "f(x) = 7 − 2x. Find {{f^(-1)(x)}}.",
        options: ["{{(x - 7)/2}}", "{{(7 - x)/2}}", "{{1/(7 - 2x)}}", "{{(x + 7)/2}}"],
        answerIndex: 1,
        explanation: "Let y = 7 − 2x. Then 2x = 7 − y, so x = {{(7 - y)/2}} and {{f^(-1)(x) = (7 - x)/2}}. Check: f(1) = 5 and {{f^(-1)(5) = 2/2 = 1}} ✓. {{(x - 7)/2}} has the sign of the whole numerator wrong (it gives −1, not 1). {{1/(7 - 2x)}} is the reciprocal. {{(x + 7)/2}} treats −2x as +2x.",
        difficulty: "core",
        guideRef: "inverse-functions",
        hints: [
          "Write y = 7 − 2x and make x the subject.",
          "Add 2x to both sides first to make the x term positive.",
          "Check your answer: f(1) = 5, so {{f^(-1)(5)}} must be 1.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "functions-m2-q08",
        question: "The graph shows y = f(x), where f(x) = {{x^2 - 4x + 1}} with domain −1 ≤ x ≤ 4. Which of these is the range of f?",
        diagram: `<svg viewBox="0 0 360 280" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Graph of y = f(x) for −1 ≤ x ≤ 4: a U-shaped curve starting at (−1, 6), falling to a minimum at (2, −3), then rising to end at (4, 1)"><rect x="0" y="0" width="360" height="280" fill="#ffffff"/><line x1="40" y1="20" x2="40" y2="240" stroke="#e2e8f0" stroke-width="1"/><line x1="80" y1="20" x2="80" y2="240" stroke="#e2e8f0" stroke-width="1"/><line x1="120" y1="20" x2="120" y2="240" stroke="#e2e8f0" stroke-width="1"/><line x1="160" y1="20" x2="160" y2="240" stroke="#e2e8f0" stroke-width="1"/><line x1="200" y1="20" x2="200" y2="240" stroke="#e2e8f0" stroke-width="1"/><line x1="240" y1="20" x2="240" y2="240" stroke="#e2e8f0" stroke-width="1"/><line x1="280" y1="20" x2="280" y2="240" stroke="#e2e8f0" stroke-width="1"/><line x1="320" y1="20" x2="320" y2="240" stroke="#e2e8f0" stroke-width="1"/><line x1="40" y1="240" x2="320" y2="240" stroke="#e2e8f0" stroke-width="1"/><line x1="40" y1="220" x2="320" y2="220" stroke="#e2e8f0" stroke-width="1"/><line x1="40" y1="200" x2="320" y2="200" stroke="#e2e8f0" stroke-width="1"/><line x1="40" y1="180" x2="320" y2="180" stroke="#e2e8f0" stroke-width="1"/><line x1="40" y1="160" x2="320" y2="160" stroke="#e2e8f0" stroke-width="1"/><line x1="40" y1="140" x2="320" y2="140" stroke="#e2e8f0" stroke-width="1"/><line x1="40" y1="120" x2="320" y2="120" stroke="#e2e8f0" stroke-width="1"/><line x1="40" y1="100" x2="320" y2="100" stroke="#e2e8f0" stroke-width="1"/><line x1="40" y1="80" x2="320" y2="80" stroke="#e2e8f0" stroke-width="1"/><line x1="40" y1="60" x2="320" y2="60" stroke="#e2e8f0" stroke-width="1"/><line x1="40" y1="40" x2="320" y2="40" stroke="#e2e8f0" stroke-width="1"/><line x1="40" y1="20" x2="320" y2="20" stroke="#e2e8f0" stroke-width="1"/><line x1="40" y1="160" x2="332" y2="160" stroke="#334155" stroke-width="1.5"/><line x1="120" y1="240" x2="120" y2="10" stroke="#334155" stroke-width="1.5"/><text x="334" y="164" font-size="13" font-style="italic" font-family="sans-serif" fill="#1f2937">x</text><text x="125" y="12" font-size="13" font-style="italic" font-family="sans-serif" fill="#1f2937">y</text><text x="40" y="174" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155">−2</text><text x="80" y="174" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155">−1</text><text x="160" y="174" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155">1</text><text x="200" y="174" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155">2</text><text x="240" y="174" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155">3</text><text x="280" y="174" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155">4</text><text x="320" y="174" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155">5</text><text x="116" y="244" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155">−4</text><text x="116" y="224" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155">−3</text><text x="116" y="204" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155">−2</text><text x="116" y="184" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155">−1</text><text x="116" y="144" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155">1</text><text x="116" y="124" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155">2</text><text x="116" y="104" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155">3</text><text x="116" y="84" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155">4</text><text x="116" y="64" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155">5</text><text x="116" y="44" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155">6</text><text x="116" y="24" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155">7</text><text x="116" y="174" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155">0</text><path d="M80.0 40.0 L82.0 45.95 L84.0 51.8 L86.0 57.55 L88.0 63.2 L90.0 68.75 L92.0 74.2 L94.0 79.55 L96.0 84.8 L98.0 89.95 L100.0 95.0 L102.0 99.95 L104.0 104.8 L106.0 109.55 L108.0 114.2 L110.0 118.75 L112.0 123.2 L114.0 127.55 L116.0 131.8 L118.0 135.95 L120.0 140.0 L122.0 143.95 L124.0 147.8 L126.0 151.55 L128.0 155.2 L130.0 158.75 L132.0 162.2 L134.0 165.55 L136.0 168.8 L138.0 171.95 L140.0 175.0 L142.0 177.95 L144.0 180.8 L146.0 183.55 L148.0 186.2 L150.0 188.75 L152.0 191.2 L154.0 193.55 L156.0 195.8 L158.0 197.95 L160.0 200.0 L162.0 201.95 L164.0 203.8 L166.0 205.55 L168.0 207.2 L170.0 208.75 L172.0 210.2 L174.0 211.55 L176.0 212.8 L178.0 213.95 L180.0 215.0 L182.0 215.95 L184.0 216.8 L186.0 217.55 L188.0 218.2 L190.0 218.75 L192.0 219.2 L194.0 219.55 L196.0 219.8 L198.0 219.95 L200.0 220.0 L202.0 219.95 L204.0 219.8 L206.0 219.55 L208.0 219.2 L210.0 218.75 L212.0 218.2 L214.0 217.55 L216.0 216.8 L218.0 215.95 L220.0 215.0 L222.0 213.95 L224.0 212.8 L226.0 211.55 L228.0 210.2 L230.0 208.75 L232.0 207.2 L234.0 205.55 L236.0 203.8 L238.0 201.95 L240.0 200.0 L242.0 197.95 L244.0 195.8 L246.0 193.55 L248.0 191.2 L250.0 188.75 L252.0 186.2 L254.0 183.55 L256.0 180.8 L258.0 177.95 L260.0 175.0 L262.0 171.95 L264.0 168.8 L266.0 165.55 L268.0 162.2 L270.0 158.75 L272.0 155.2 L274.0 151.55 L276.0 147.8 L278.0 143.95 L280.0 140.0" fill="none" stroke="#2563eb" stroke-width="2"/><circle cx="80" cy="40" r="3.5" fill="#2563eb"/><circle cx="280" cy="140" r="3.5" fill="#2563eb"/><text x="224.0" y="60" font-size="12" font-style="italic" font-family="sans-serif" fill="#2563eb">y = f(x)</text></svg>`,
        options: ["−3 ≤ f(x) ≤ 6", "1 ≤ f(x) ≤ 6", "−1 ≤ f(x) ≤ 4", "f(x) ≥ −3"],
        answerIndex: 0,
        explanation: "The range is the set of **y-values** the graph covers. The lowest point is the minimum (2, −3) and the highest is the endpoint (−1, 6), so −3 ≤ f(x) ≤ 6. 1 ≤ f(x) ≤ 6 only uses the two endpoints f(4) = 1 and f(−1) = 6, missing the dip to −3 in between. −1 ≤ f(x) ≤ 4 is the domain (x-values). f(x) ≥ −3 would be the range for all real x, ignoring that the graph stops at x = −1 and x = 4.",
        difficulty: "core",
        guideRef: "domain-range",
        hints: [
          "The range is about the y-values. What are the lowest and highest points of the graph?",
          "Look at the turning point **and** both ends of the curve.",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "functions-m2-q09",
        question: "f(x) = {{x^2 + 2x}}. Solve f(x) = 15.",
        options: ["x = −3 or x = 5", "x = 255", "x = 3 only", "x = 3 or x = −5"],
        answerIndex: 3,
        explanation: "{{x^2 + 2x = 15}} ⟹ {{x^2 + 2x - 15 = 0}} ⟹ (x + 5)(x − 3) = 0, so x = 3 or x = −5. Check: f(−5) = 25 − 10 = 15 ✓. x = −3 or 5 has the signs of the roots flipped. 255 is f(15) — 15 is the output, not the input. \"3 only\" misses the negative solution — a quadratic can have two inputs with the same output.",
        difficulty: "core",
        guideRef: "functions-as-mappings",
        hints: [
          "15 is the output. Write {{x^2 + 2x = 15}}.",
          "Rearrange to = 0 and factorise.",
          "You need two numbers that multiply to −15 and add to 2.",
        ],
        strategy: "Work backwards",
      },
      {
        kind: "mcq",
        id: "functions-m2-q10",
        question: "f(x) = 2x − 3. Find ff(x).",
        options: ["{{(2x - 3)^2}}", "{{4x - 6}}", "{{4x - 9}}", "{{4x - 3}}"],
        answerIndex: 2,
        explanation: "ff(x) = f(2x − 3) = 2(2x − 3) − 3 = 4x − 6 − 3 = 4x − 9. Check with x = 2: f(2) = 1, f(1) = −1, and 4(2) − 9 = −1 ✓. {{(2x - 3)^2}} treats ff as f × f. 4x − 6 forgets the second −3. 4x − 3 forgets to multiply the −3 inside the bracket by 2.",
        difficulty: "core",
        guideRef: "composite-functions",
        hints: [
          "ff(x) = f(f(x)). Replace x in f with (2x − 3).",
          "2(2x − 3) − 3. Expand carefully.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "functions-m2-q11",
        question: "The graph of y = f(x) passes through the point (2, 7). Which point must lie on the graph of {{y = f^(-1)(x)}}?",
        options: ["(−2, 7)", "(7, 2)", "(2, {{1/7}})", "(−7, −2)"],
        answerIndex: 1,
        explanation: "f(2) = 7, so {{f^(-1)(7) = 2}}: the point (7, 2) is on the inverse. Geometrically, {{y = f^(-1)(x)}} is the reflection of y = f(x) in the line y = x, which swaps the coordinates. (−2, 7) is a reflection in the y-axis. (2, {{1/7}}) treats {{f^(-1)}} as a reciprocal. (−7, −2) is a reflection in y = −x.",
        difficulty: "core",
        guideRef: "inverse-functions",
        hints: [
          "f sends 2 to 7. Where does {{f^(-1)}} send 7?",
          "The inverse graph is a reflection in y = x. What does that do to (a, b)?",
        ],
        strategy: "Use symmetry",
      },
      {
        kind: "mcq",
        id: "functions-m2-q12",
        question: "Which of these functions is defined for **every** real number x?",
        options: ["f(x) = {{1/(x^2 + 1)}}", "f(x) = {{1/(x^2 - 1)}}", "f(x) = {{sqrt(x - 1)}}", "f(x) = {{3/x}}"],
        answerIndex: 0,
        explanation: "{{x^2 + 1 >= 1}} for every x, so the denominator is never zero and {{1/(x^2 + 1)}} is always defined. {{1/(x^2 - 1)}} breaks at x = 1 and x = −1. {{sqrt(x - 1)}} needs x ≥ 1. {{3/x}} is not defined at x = 0. Don't be fooled by the similar-looking denominators: the sign in {{x^2 ± 1}} decides everything.",
        difficulty: "core",
        guideRef: "domain-range",
        hints: [
          "For each function ask: is there an x that makes a denominator zero, or a square root negative?",
          "Can {{x^2 + 1}} ever be 0? Can {{x^2 - 1}}?",
        ],
        strategy: "Eliminate options",
      },
      {
        kind: "mcq",
        id: "functions-m2-q13",
        question: "f(x) = 3x + k and g(x) = 2x − 1, where k is a constant. Given that fg(x) = gf(x) for **all** values of x, find k.",
        options: ["k = 2", "k = −3", "There is no such k", "k = −2"],
        answerIndex: 3,
        explanation: "fg(x) = 3(2x − 1) + k = 6x − 3 + k and gf(x) = 2(3x + k) − 1 = 6x + 2k − 1. The x terms already match, so we need −3 + k = 2k − 1, giving k = −2. Check: f(x) = 3x − 2; fg(x) = 6x − 5 and gf(x) = 6x − 5 ✓. k = 2 is a sign slip when solving. k = −3 comes from dropping the −1 in gf(x). \"No such k\" comes from forgetting to multiply k by 2 in gf (then −3 + k = k − 1 is impossible) — or from assuming fg can never equal gf.",
        difficulty: "challenge",
        guideRef: "composite-functions",
        hints: [
          "Find fg(x) and gf(x) in terms of x and k.",
          "In gf(x) = g(3x + k), the k gets multiplied by 2.",
          "The x terms match. Set the constant terms equal and solve for k.",
        ],
        strategy: "Introduce a variable",
      },
      {
        kind: "mcq",
        id: "functions-m2-q14",
        question: "f(x) = {{(x + 3)/(x - 2)}}, x ≠ 2. Find {{f^(-1)(x)}}.",
        options: ["{{(x - 2)/(x + 3)}}", "{{(x - 3)/(x + 2)}}", "{{(2x + 3)/(x - 1)}}", "{{(2x + 3)/(1 - x)}}"],
        answerIndex: 2,
        explanation: "Let y = {{(x + 3)/(x - 2)}}. Then xy − 2y = x + 3, so xy − x = 2y + 3, x(y − 1) = 2y + 3 and x = {{(2y + 3)/(y - 1)}}. So {{f^(-1)(x) = (2x + 3)/(x - 1)}}. Check: f(3) = 6 and {{f^(-1)(6) = 15/5 = 3}} ✓. {{(x - 2)/(x + 3)}} is the reciprocal {{1/f(x)}}. {{(x - 3)/(x + 2)}} just flips the signs. {{(2x + 3)/(1 - x)}} comes from a sign slip when factorising out x (it gives −3 at x = 6).",
        difficulty: "challenge",
        guideRef: "inverse-functions",
        hints: [
          "Set y = f(x) and multiply both sides by (x − 2).",
          "Get every term containing x on one side, everything else on the other.",
          "Factorise out x: x(y − 1) = …",
        ],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "functions-m2-q15",
        question: "A function f satisfies f(x + 1) = 2x + 7 for every value of x. Find f(x).",
        options: ["{{2x + 8}}", "{{2x + 5}}", "{{2x + 7}}", "{{2x + 6}}"],
        answerIndex: 1,
        explanation: "Let t = x + 1, so x = t − 1. Then f(t) = 2(t − 1) + 7 = 2t + 5, i.e. f(x) = 2x + 5. Check: f(x + 1) = 2(x + 1) + 5 = 2x + 7 ✓. 2x + 8 adds 1 to the output instead of adjusting the input. 2x + 7 assumes f(x + 1) and f(x) are the same rule. 2x + 6 subtracts 1 from the constant instead of subtracting 2 (the 1 is doubled).",
        difficulty: "challenge",
        guideRef: "functions-as-mappings",
        hints: [
          "Try a number: what is f(4)? Choose x so that x + 1 = 4.",
          "Introduce a new letter: let t = x + 1. What is x in terms of t?",
          "Substitute x = t − 1 into 2x + 7.",
        ],
        strategy: "Introduce a variable",
      },
    ],
  },
  {
    id: "functions-m3",
    title: "MCQ Paper 3 — Exam style",
    questions: [
      {
        kind: "mcq",
        id: "functions-m3-q01",
        question: "f(x) = {{(3x + 5)/2}}. Work out f(7).",
        options: ["23.5", "13", "3", "15.5"],
        answerIndex: 1,
        explanation: "The fraction line acts like a bracket: f(7) = {{(21 + 5)/2 = 26/2 = 13}}. 23.5 = 21 + 2.5 divides only the 5 by 2. 15.5 = 21 ÷ 2 + 5 divides only the 3x. 3 is {{f^(-1)(7)}} — solving f(x) = 7 instead of evaluating.",
        difficulty: "warmup",
        guideRef: "functions-as-mappings",
        hints: ["Work out the whole numerator 3 × 7 + 5 before dividing by 2."],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "functions-m3-q02",
        question: "The cost, in dollars, of a taxi journey of d km in Singapore is given by C(d) = 3.9 + 0.65d. What does C(12) = 11.7 mean?",
        options: ["A journey costing $12 is 11.7 km long", "C multiplied by 12 equals 11.7", "11.7 km of travel costs $12", "A 12 km journey costs $11.70"],
        answerIndex: 3,
        explanation: "In C(12), the 12 is the **input** (d, the distance in km) and 11.7 is the **output** (the cost in dollars): 3.9 + 0.65 × 12 = 3.9 + 7.8 = 11.7, so a 12 km journey costs $11.70. The other statements swap input and output, or read C(12) as \"C times 12\" — function brackets are not multiplication.",
        difficulty: "warmup",
        guideRef: "functions-as-mappings",
        hints: ["In C(d), d is the distance you put in. What comes out?"],
        strategy: "Explain in words",
      },
      {
        kind: "mcq",
        id: "functions-m3-q03",
        question: "f(x) = x + 4 and g(x) = {{2x^2}}. Work out fg(−1).",
        options: ["6", "18", "2", "8"],
        answerIndex: 0,
        explanation: "g acts first: g(−1) = {{2 * (-1)^2}} = 2 × 1 = 2, then f(2) = 6. 18 is gf(−1) = g(3) = 2 × 9 — the wrong order. 2 comes from g(−1) = −2 (a sign slip on the square), then f(−2) = 2. 8 comes from g(−1) = {{(2 * (-1))^2}} = 4, squaring the 2 as well.",
        difficulty: "warmup",
        guideRef: "composite-functions",
        hints: ["fg(−1) = f(g(−1)). In {{2x^2}}, only the x is squared."],
        strategy: "Work from the inside out",
      },
      {
        kind: "mcq",
        id: "functions-m3-q04",
        question: "f(x) = {{sqrt(x + 2)}}. Which of these values of x is **not** in the domain of f?",
        options: ["x = −2", "x = 0", "x = −3", "x = 2"],
        answerIndex: 2,
        explanation: "We need x + 2 ≥ 0, i.e. x ≥ −2. At x = −3, x + 2 = −1 and {{sqrt(-1)}} is not a real number, so −3 is excluded. x = −2 is allowed: f(−2) = {{sqrt(0)}} = 0. x = 0 and x = 2 give {{sqrt(2)}} and 2.",
        difficulty: "warmup",
        guideRef: "domain-range",
        hints: ["Substitute each value. Which one puts a negative number inside the square root?"],
        strategy: "Eliminate options",
      },
      {
        kind: "mcq",
        id: "functions-m3-q05",
        question: "f(x) = {{(2x - 1)/5}}. Express {{f^(-1)(x)}} in terms of x.",
        options: ["{{5/(2x - 1)}}", "{{(5x + 1)/2}}", "{{(5x - 1)/2}}", "{{(5x + 5)/2}}"],
        answerIndex: 1,
        explanation: "y = {{(2x - 1)/5}} ⟹ 5y = 2x − 1 ⟹ 2x = 5y + 1 ⟹ x = {{(5y + 1)/2}}, so {{f^(-1)(x) = (5x + 1)/2}}. Check: f(3) = 1 and {{f^(-1)(1) = 6/2 = 3}} ✓. {{5/(2x - 1)}} is the reciprocal. {{(5x - 1)/2}} keeps −1 instead of reversing it. {{(5x + 5)/2}} undoes in the wrong order: adds 1 before multiplying by 5.",
        difficulty: "core",
        guideRef: "inverse-functions",
        hints: [
          "Set y = {{(2x - 1)/5}} and make x the subject.",
          "Multiply by 5 first, then add 1, then divide by 2.",
        ],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "functions-m3-q06",
        question: "f(x) = 3 − x and g(x) = {{x^2 + 1}}. Work out fg(2) − gf(2).",
        options: ["4", "0", "−2", "−4"],
        answerIndex: 3,
        explanation: "fg(2) = f(g(2)) = f(5) = −2. gf(2) = g(f(2)) = g(1) = 2. So fg(2) − gf(2) = −2 − 2 = −4. 4 is gf(2) − fg(2), subtracting the wrong way round. 0 assumes fg = gf, which is rarely true. −2 is fg(2) on its own.",
        difficulty: "core",
        guideRef: "composite-functions",
        hints: [
          "Find fg(2) and gf(2) separately.",
          "For fg(2), apply g to 2 first. For gf(2), apply f to 2 first.",
        ],
        strategy: "Work from the inside out",
      },
      {
        kind: "mcq",
        id: "functions-m3-q07",
        question: "f(x) = {{1/(x^2 - 9)}}. Which values of x must be excluded from the domain of f?",
        options: ["x = 3 and x = −3", "x = 3 only", "x = 9", "x = 0"],
        answerIndex: 0,
        explanation: "The denominator is zero when {{x^2 = 9}}, i.e. x = 3 **or** x = −3 (since {{(-3)^2 = 9}} too). Both must be excluded. \"x = 3 only\" forgets the negative square root. x = 9 confuses {{x^2 = 9}} with x = 9. x = 0 is fine: f(0) = {{-1/9}}.",
        difficulty: "core",
        guideRef: "domain-range",
        hints: [
          "When is {{x^2 - 9}} equal to zero?",
          "{{x^2 = 9}} has two solutions.",
        ],
        strategy: "Consider extremes",
      },
      {
        kind: "mcq",
        id: "functions-m3-q08",
        question: "f(x) = {{x^2}} and g(x) = x − 2. Solve fg(x) = 25.",
        options: ["x = 7 only", "x = 3 or x = −7", "x = 7 or x = −3", "x = ±{{sqrt(27)}}"],
        answerIndex: 2,
        explanation: "fg(x) = f(x − 2) = {{(x - 2)^2}}. So {{(x - 2)^2 = 25}}, x − 2 = 5 or x − 2 = −5, giving x = 7 or x = −3. Check: g(−3) = −5 and f(−5) = 25 ✓. \"7 only\" forgets the negative square root. x = 3 or −7 is a sign slip when adding 2. ±{{sqrt(27)}} solves gf(x) = {{x^2 - 2}} = 25 — the wrong order.",
        difficulty: "core",
        guideRef: "composite-functions",
        hints: [
          "Find fg(x) first. Which function acts on x first?",
          "{{(x - 2)^2 = 25}}. Square-root both sides — remember ±.",
        ],
        strategy: "Work from the inside out",
      },
      {
        kind: "mcq",
        id: "functions-m3-q09",
        question: "f(x) = {{x^3 + 2}}. Work out {{f^(-1)(-6)}}.",
        options: ["−214", "−2", "2", "{{cbrt(-4)}}"],
        answerIndex: 1,
        explanation: "{{f^(-1)(-6)}} is the input that gives −6: {{x^3 + 2 = -6}}, so {{x^3 = -8}} and x = −2. Check: {{(-2)^3 + 2 = -8 + 2 = -6}} ✓. −214 is f(−6), going the wrong way. 2 forgets that the cube root of a negative number is negative. {{cbrt(-4)}} adds 2 instead of subtracting it.",
        difficulty: "core",
        guideRef: "inverse-functions",
        hints: [
          "Which input makes f(x) = −6?",
          "Solve {{x^3 + 2 = -6}}. Unlike square roots, cube roots of negatives exist.",
        ],
        strategy: "Work backwards",
      },
      {
        kind: "mcq",
        id: "functions-m3-q10",
        question: "f(x) = {{2x^2 - 3}}. Find f(2a), giving your answer in terms of a.",
        options: ["{{4a^2 - 3}}", "{{16a^2 - 3}}", "{{4a^2 - 6}}", "{{8a^2 - 3}}"],
        answerIndex: 3,
        explanation: "Replace x with (2a): f(2a) = {{2(2a)^2 - 3 = 2 * 4a^2 - 3 = 8a^2 - 3}}. {{4a^2 - 3}} squares only the a, not the 2. {{16a^2 - 3}} squares the coefficient 2 as well, as if it were {{(2 * 2a)^2}}. {{4a^2 - 6}} is 2f(a) — f(2a) is not 2 × f(a).",
        difficulty: "core",
        guideRef: "functions-as-mappings",
        hints: [
          "Put 2a in a bracket wherever you see x.",
          "{{(2a)^2}} = ? Then multiply by 2.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "functions-m3-q11",
        question: "f(x) = 3x − 1 with domain −2 ≤ x ≤ 4. Find the range of f.",
        options: ["−7 ≤ f(x) ≤ 11", "−2 ≤ f(x) ≤ 4", "−5 ≤ f(x) ≤ 13", "f(x) ≥ −7"],
        answerIndex: 0,
        explanation: "f is a straight line with positive gradient, so its least and greatest values are at the ends of the domain: f(−2) = −6 − 1 = −7 and f(4) = 12 − 1 = 11. Range: −7 ≤ f(x) ≤ 11. −2 ≤ f(x) ≤ 4 just copies the domain. −5 ≤ f(x) ≤ 13 uses +1 instead of −1. f(x) ≥ −7 forgets the domain stops at x = 4.",
        difficulty: "core",
        guideRef: "domain-range",
        hints: [
          "The range is the set of outputs. Is f increasing or decreasing?",
          "Work out f at both ends of the domain.",
        ],
        strategy: "Consider extremes",
      },
      {
        kind: "mcq",
        id: "functions-m3-q12",
        question: "A function is **self-inverse** if {{f^(-1)(x) = f(x)}}. Which of these functions is self-inverse?",
        options: ["f(x) = x + 10", "f(x) = 10x", "f(x) = 10 − x", "f(x) = {{x/10}}"],
        answerIndex: 2,
        explanation: "If y = 10 − x then x = 10 − y, so {{f^(-1)(x) = 10 - x}} = f(x). Applying it twice gets you back: f(3) = 7 and f(7) = 3. Its graph is symmetric about y = x. x + 10 has inverse x − 10; 10x has inverse {{x/10}}; {{x/10}} has inverse 10x — those last two are inverses of **each other**, not of themselves.",
        difficulty: "core",
        guideRef: "inverse-functions",
        hints: [
          "Self-inverse means doing f twice gets you back to the start. Try x = 3 in each.",
          "Find the inverse of each function and compare.",
        ],
        strategy: "Try small cases",
      },
      {
        kind: "mcq",
        id: "functions-m3-q13",
        question: "f(x) = 3x − 2. Solve {{f(x) = f^(-1)(x)}}.",
        options: ["x = {{1/2}}", "x = 1", "x = {{2/3}}", "x = −1"],
        answerIndex: 1,
        explanation: "{{f^(-1)(x) = (x + 2)/3}}. Then 3x − 2 = {{(x + 2)/3}} ⟹ 9x − 6 = x + 2 ⟹ 8x = 8 ⟹ x = 1. Shortcut: the graphs of f and {{f^(-1)}} are reflections in y = x, and for an increasing function like this they meet on that line, so solve f(x) = x: 3x − 2 = x, x = 1. x = {{1/2}} comes from using {{f^(-1)(x) = (x - 2)/3}}. x = {{2/3}} solves f(x) = 0. x = −1 is a sign slip in 8x = 8.",
        difficulty: "challenge",
        guideRef: "inverse-functions",
        hints: [
          "First find {{f^(-1)(x)}}.",
          "Set 3x − 2 equal to it and multiply both sides by 3.",
          "Can you see a quicker way using the line y = x?",
        ],
        strategy: "Use symmetry",
      },
      {
        kind: "mcq",
        id: "functions-m3-q14",
        question: "f(x) = {{1/(x - 1)}}, x ≠ 1. Find ff(x), simplified fully.",
        options: ["{{x - 1}}", "{{1/(x - 2)}}", "{{(x - 1)/(x - 2)}}", "{{(x - 1)/(2 - x)}}"],
        answerIndex: 3,
        explanation: "ff(x) = {{1/(1/(x - 1) - 1)}}. Combine the denominator over x − 1: {{1/(x - 1) - 1 = (1 - (x - 1))/(x - 1) = (2 - x)/(x - 1)}}. Taking the reciprocal, ff(x) = {{(x - 1)/(2 - x)}}. Check with x = 3: f(3) = {{1/2}}, f({{1/2}}) = {{1/(-1/2)}} = −2, and {{(3 - 1)/(2 - 3)}} = −2 ✓. {{(x - 1)/(x - 2)}} has the sign slip 1 − (x − 1) = x − 2. {{1/(x - 2)}} subtracts 1 twice. {{x - 1}} just flips {{1/(x - 1)}} and forgets the −1.",
        difficulty: "challenge",
        guideRef: "composite-functions",
        hints: [
          "Replace x in {{1/(x - 1)}} with {{1/(x - 1)}}.",
          "Write the denominator {{1/(x - 1) - 1}} as a single fraction.",
          "Be careful: 1 − (x − 1) = 2 − x.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "functions-m3-q15",
        question: "g(x) = {{(2x + 1)/(x - 4)}}, x ≠ 4. Which of these values is **not** in the range of g?",
        options: ["2", "4", "0", "{{-1/2}}"],
        answerIndex: 0,
        explanation: "Solve y = {{(2x + 1)/(x - 4)}} for x: xy − 4y = 2x + 1 ⟹ x(y − 2) = 4y + 1 ⟹ x = {{(4y + 1)/(y - 2)}}. Every y gives a valid x **except** y = 2, so 2 is not in the range. (As x gets large, g(x) gets close to {{2x/x}} = 2 but never reaches it.) 4 is excluded from the **domain**, not the range: g(8.5) = 4. 0 is reached at x = {{-1/2}}. {{-1/2}} is reached at x = 0.4.",
        difficulty: "challenge",
        guideRef: "domain-range",
        hints: [
          "The range is the set of outputs. Which output can never happen?",
          "Set y = g(x) and try to solve for x. When does that fail?",
          "x(y − 2) = 4y + 1. What goes wrong when y = 2?",
        ],
        strategy: "Use the inverse",
      },
    ],
  },
];
