import type { TopicPractice } from "../../types.ts";

export const practice: TopicPractice = {
  // =========================================================================
  // Quick-check quiz — 10 questions (3 mcq, 7 short) across the main sections
  // =========================================================================
  quiz: [
    {
      kind: "short",
      id: "functions-quiz-q01",
      question: "{{f(x) = 3x^2 - 5}}\n\nWork out f(−2).",
      answer: { type: "number", value: 7 },
      solution: [
        "Replace every x with (−2) — keep the brackets.",
        "{{f(-2) = 3(-2)^2 - 5 = 3 * 4 - 5}}",
        "= 12 − 5 = 7.",
      ],
      traps: [
        { spec: { type: "number", value: -17 }, feedback: "You worked out {{-2^2}} as −4. Square the whole input: {{(-2)^2 = +4}}, so 3 × 4 − 5 = 7." },
        { spec: { type: "number", value: 31 }, feedback: "You squared 3 × (−2) = −6 to get 36. Only the x is squared: {{3x^2}} means 3 × {{x^2}}, so it's 3 × 4 = 12, then 12 − 5." },
      ],
      commonError: "Typing −2² into a calculator without brackets, which gives −4 instead of 4.",
      difficulty: "warmup",
      guideRef: "functions-as-mappings",
      hints: ["Put (−2) in brackets wherever you see x.", "{{(-2)^2 = 4}}. Then multiply by 3 and subtract 5."],
      strategy: "Substitute with brackets",
    },
    {
      kind: "mcq",
      id: "functions-quiz-q02",
      question: "Which one of these graphs is **not** the graph of a function y = f(x)?",
      options: [
        "The parabola {{y = x^2 - 4}}",
        "The horizontal line y = 3",
        "The circle {{x^2 + y^2 = 25}}",
        "The curve {{y = 1/x}}, x ≠ 0",
      ],
      answerIndex: 2,
      explanation:
        "Use the vertical line test: a function gives **exactly one** y for each x, so no vertical line may cross its graph twice. The vertical line x = 3 meets the circle at (3, 4) and (3, −4) — one input, two outputs — so the circle is not a function. The parabola is many-to-one (x = 2 and x = −2 both give 0), which is allowed. The horizontal line y = 3 is a constant function: every x has one output. {{y = 1/x}} gives one y for every allowed x.",
      difficulty: "warmup",
      guideRef: "functions-as-mappings",
      hints: ["Every input x must give exactly one output y.", "Imagine a vertical line, such as x = 3, sliding across each graph. Can it ever cross the graph twice?"],
      strategy: "Test a specific value",
    },
    {
      kind: "short",
      id: "functions-quiz-q03",
      question: "{{g(x) = 4x - 7}}\n\nSolve g(x) = 13.",
      answer: { type: "number", value: 5 },
      solution: ["g(x) = 13 means 4x − 7 = 13.", "4x = 20.", "x = 5. Check: g(5) = 20 − 7 = 13 ✓."],
      traps: [{ spec: { type: "number", value: 45 }, feedback: "That's g(13) — you put 13 *in*. Here 13 is the *output*: solve 4x − 7 = 13." }],
      commonError: "Confusing g(x) = 13 (13 is the output) with g(13) (13 is the input).",
      difficulty: "warmup",
      guideRef: "functions-as-mappings",
      hints: ["Is 13 the input or the output here?", "Write 4x − 7 = 13 and solve."],
      strategy: "Use the inverse",
    },
    {
      kind: "short",
      id: "functions-quiz-q04",
      question: "{{f(x) = 5/(2x - 6)}}\n\nWhich value of x must be excluded from the domain of f?",
      answer: { type: "number", value: 3 },
      solution: [
        "You cannot divide by zero, so exclude the value that makes the denominator 0.",
        "2x − 6 = 0 gives x = 3.",
        "f(3) would be {{5/0}}, which has no value — division by zero is impossible.",
      ],
      traps: [{ spec: { type: "number", value: 6 }, feedback: "Set the whole denominator equal to zero: 2x − 6 = 0, so 2x = 6 and x = 3." }],
      commonError: "Excluding x = 0 out of habit — the problem input is whatever makes the denominator zero.",
      difficulty: "core",
      guideRef: "domain-range",
      hints: ["Which operation can never be done?", "Find x so that the denominator 2x − 6 equals 0."],
      strategy: "Look for the forbidden operation",
    },
    {
      kind: "mcq",
      id: "functions-quiz-q05",
      question: "{{f(x) = 5 - x^2}}, for all real values of x.\n\nWhich of these is the range of f?",
      options: ["f(x) ≥ 5", "f(x) ≤ 5", "f(x) < 5", "All real numbers"],
      answerIndex: 1,
      explanation:
        "{{x^2 >= 0}} for every real x, so {{5 - x^2}} is 5 minus something never negative: it can never be **more** than 5. The value 5 is reached (at x = 0), and as x grows the outputs fall without limit, so the range is f(x) ≤ 5. f(x) ≥ 5 points the wrong way — the graph is an upside-down ∩ with its top at (0, 5). f(x) < 5 forgets that 5 itself is reached. \"All real numbers\" describes the domain, not the outputs.",
      difficulty: "core",
      guideRef: "domain-range",
      hints: ["What is the smallest possible value of {{x^2}}? So what is the largest possible value of {{5 - x^2}}?", "Is that largest output actually reached? Then use ≤, not <."],
      strategy: "Consider extremes",
    },
    {
      kind: "short",
      id: "functions-quiz-q06",
      question: "{{f(x) = x^2 - 1}} and {{g(x) = 2x - 5}}\n\nWork out fg(4).",
      answer: { type: "number", value: 8 },
      solution: ["fg(4) means f(g(4)) — do g first.", "g(4) = 2 × 4 − 5 = 3.", "f(3) = {{3^2 - 1}} = 8."],
      traps: [
        { spec: { type: "number", value: 25 }, feedback: "That's gf(4): f(4) = 15, then g(15) = 25. In fg(4) the function **next to the 4** acts first — that's g." },
        { spec: { type: "number", value: 45 }, feedback: "fg(4) is not f(4) × g(4) = 15 × 3. Put 4 into g, then put that answer into f." },
      ],
      commonError: "Applying f first because it is written first.",
      difficulty: "core",
      guideRef: "composite-functions",
      hints: ["Which function is closest to the 4?", "Find g(4), then put that answer into f."],
      strategy: "Work from the inside out",
    },
    {
      kind: "short",
      id: "functions-quiz-q07",
      question: "{{f(x) = 4 - x}} and {{g(x) = 3x + 2}}\n\nFind gf(x). Simplify your answer.",
      answer: { type: "expression", expr: "14-3x", form: "simplified", display: "gf(x) = 14 − 3x" },
      solution: ["gf(x) = g(f(x)) = g(4 − x).", "Replace x in g by (4 − x): 3(4 − x) + 2.", "= 12 − 3x + 2 = 14 − 3x.", "Check with x = 1: f(1) = 3, g(3) = 11, and 14 − 3 = 11 ✓."],
      traps: [
        { spec: { type: "expression", expr: "2-3x" }, feedback: "That's fg(x) = 4 − (3x + 2). For gf(x), f acts first: g(4 − x) = 3(4 − x) + 2." },
        { spec: { type: "expression", expr: "6-3x" }, feedback: "The 3 multiplies the whole bracket: 3(4 − x) = 12 − 3x, then add 2." },
      ],
      commonError: "Writing 3 × 4 − x + 2 — forgetting to multiply the whole of (4 − x) by 3.",
      difficulty: "core",
      guideRef: "composite-functions",
      hints: ["gf(x) means g(f(x)). Which function acts first?", "Wherever g has an x, write (4 − x) in brackets.", "Expand 3(4 − x) + 2."],
      strategy: "Substitute with brackets",
    },
    {
      kind: "short",
      id: "functions-quiz-q08",
      question: "{{f(x) = (x + 5)/3}}\n\nFind f⁻¹(x).",
      answer: { type: "expression", expr: "3x-5", display: "f⁻¹(x) = 3x − 5" },
      solution: [
        "Write y = {{(x + 5)/3}} and make x the subject.",
        "3y = x + 5, so x = 3y − 5.",
        "Swap the letters: f⁻¹(x) = 3x − 5.",
        "Check: f(f⁻¹(x)) = {{(3x - 5 + 5)/3 = x}} ✓.",
      ],
      traps: [{ spec: { type: "expression", expr: "3/(x+5)" }, feedback: "The inverse undoes the function — it is not the reciprocal {{1/f(x)}}. Rearrange y = {{(x + 5)/3}} for x." }],
      commonError: "Confusing f⁻¹(x) with the reciprocal {{1/f(x)}}.",
      difficulty: "core",
      guideRef: "inverse-functions",
      hints: ["f does: add 5, then divide by 3. What undoes that, and in what order?", "Undo ÷ 3 first (× 3), then undo + 5 (− 5)."],
      strategy: "Use the inverse",
    },
    {
      kind: "mcq",
      id: "functions-quiz-q09",
      question: "The graph of y = f⁻¹(x) can be obtained from the graph of y = f(x) by a reflection. In which line?",
      options: ["The x-axis", "The y-axis", "The line y = −x", "The line y = x"],
      answerIndex: 3,
      explanation:
        "If (a, b) is on y = f(x), then f(a) = b, so f⁻¹(b) = a and (b, a) is on y = f⁻¹(x). Swapping the coordinates of every point is a reflection in **y = x**. Reflecting in the x-axis gives y = −f(x), and in the y-axis gives y = f(−x) — different transformations. The line y = −x would send (a, b) to (−b, −a).",
      difficulty: "core",
      guideRef: "inverse-functions",
      hints: ["If (2, 7) is on y = f(x), which point must be on y = f⁻¹(x)?", "Inputs and outputs swap places. Which reflection swaps x and y?"],
      strategy: "Test a specific point",
    },
    {
      kind: "short",
      id: "functions-quiz-q10",
      question: "{{f(x) = 2x - 9}}\n\nWork out f⁻¹(5).",
      answer: { type: "number", value: 7 },
      solution: [
        "f⁻¹(5) is the input that f sends to 5. Solve 2x − 9 = 5.",
        "2x = 14, so x = 7.",
        "Or: f⁻¹(x) = {{(x + 9)/2}}, so f⁻¹(5) = {{14/2}} = 7.",
      ],
      traps: [{ spec: { type: "number", value: 1 }, feedback: "That's f(5) = 10 − 9 = 1. f⁻¹(5) asks: which input gives an output of 5?" }],
      commonError: "Working out f(5) instead of f⁻¹(5).",
      difficulty: "core",
      guideRef: "inverse-functions",
      hints: ["f⁻¹(5) = the x for which f(x) = 5.", "Solve 2x − 9 = 5."],
      strategy: "Work backwards",
    },
  ],

  // =========================================================================
  // Practice papers
  // =========================================================================
  papers: [
    {
      id: "functions-p1",
      title: "Practice Paper 1",
      questions: [
        {
          kind: "short",
          id: "functions-p1-q01",
          question: "The function f is defined as f: x ↦ 7 − 2x.\n\nFind f(−3).",
          answer: { type: "number", value: 13 },
          solution: ["f: x ↦ 7 − 2x means f(x) = 7 − 2x.", "f(−3) = 7 − 2(−3) = 7 + 6 = 13."],
          traps: [{ spec: { type: "number", value: 1 }, feedback: "−2 × −3 is **+6**, so 7 − 2(−3) = 7 + 6 = 13." }],
          commonError: "Sign slip: 7 − 2 × (−3) written as 7 − 6.",
          difficulty: "warmup",
          guideRef: "functions-as-mappings",
          hints: ["f: x ↦ 7 − 2x is the same as f(x) = 7 − 2x.", "Negative × negative is positive."],
          strategy: "Substitute with brackets",
        },
        {
          kind: "short",
          id: "functions-p1-q02",
          question: "{{h(x) = x^3 - 2x}}\n\nWork out h(−2).",
          answer: { type: "number", value: -4 },
          solution: ["{{h(-2) = (-2)^3 - 2(-2)}}", "= −8 + 4 = −4."],
          traps: [
            { spec: { type: "number", value: -12 }, feedback: "Check the second term: −2 × (−2) = **+4**, so −8 + 4 = −4." },
            { spec: { type: "number", value: 4 }, feedback: "A negative number cubed stays negative: {{(-2)^3 = -8}}." },
          ],
          commonError: "Treating {{(-2)^3}} as +8.",
          difficulty: "warmup",
          guideRef: "functions-as-mappings",
          hints: ["Replace each x with (−2).", "{{(-2)^3 = -8}} and −2 × (−2) = +4."],
          strategy: "Substitute with brackets",
        },
        {
          kind: "short",
          id: "functions-p1-q03",
          question: "{{f(x) = 5x + 3}}\n\nSolve f(x) = −12.",
          answer: { type: "number", value: -3 },
          solution: ["5x + 3 = −12.", "5x = −15.", "x = −3. Check: f(−3) = −15 + 3 = −12 ✓."],
          traps: [{ spec: { type: "number", value: -57 }, feedback: "That's f(−12). Here −12 is the output, so solve 5x + 3 = −12." }],
          commonError: "Substituting −12 for x instead of setting the expression equal to −12.",
          difficulty: "warmup",
          guideRef: "functions-as-mappings",
          hints: ["−12 is the output. Write an equation.", "5x + 3 = −12. Subtract 3, then divide by 5."],
          strategy: "Use the inverse",
        },
        {
          kind: "short",
          id: "functions-p1-q04",
          question: "{{f(x) = sqrt(x - 4)}}, where f(x) must be a real number.\n\nState the domain of f. Give your answer as an inequality in x.",
          answer: { type: "inequality", ineq: "x>=4", display: "x ≥ 4" },
          solution: ["You can't square root a negative number (in real numbers).", "So x − 4 ≥ 0, i.e. x ≥ 4.", "x = 4 itself is allowed: f(4) = √0 = 0. Domain: x ≥ 4."],
          traps: [{ spec: { type: "inequality", ineq: "x>=-4" }, feedback: "Try x = −4: √(−8) is not real. You need x − 4 ≥ 0, so x ≥ +4." }],
          commonError: "Writing x > 4 and leaving out 4 itself — √0 = 0 is allowed.",
          difficulty: "warmup",
          guideRef: "domain-range",
          hints: ["What can't go inside a square root?", "Solve x − 4 ≥ 0."],
          strategy: "Look for the forbidden operation",
        },
        {
          kind: "short",
          id: "functions-p1-q05",
          question: "{{f(x) = x^2 - 3x}}\n\nFind f(2a). Give your answer in terms of a, fully simplified.",
          answer: { type: "expression", expr: "4a^2-6a", form: "simplified", display: "{{4a^2 - 6a}}" },
          solution: ["Replace every x with (2a).", "{{f(2a) = (2a)^2 - 3(2a)}}", "{{= 4a^2 - 6a}}"],
          traps: [{ spec: { type: "expression", expr: "2a^2-6a" }, feedback: "Square the whole input: {{(2a)^2 = 4a^2}}, not {{2a^2}}." }],
          commonError: "Writing {{2a^2}} for {{(2a)^2}}.",
          difficulty: "core",
          guideRef: "functions-as-mappings",
          hints: ["The input is now 2a — it goes in brackets wherever x was.", "{{(2a)^2 = 2a * 2a}}."],
          strategy: "Substitute with brackets",
        },
        {
          kind: "short",
          id: "functions-p1-q06",
          question: "{{f(x) = 2x^2 + 3x}}\n\nSolve f(x) = 9.",
          answer: { type: "list", values: [1.5, -3], display: "x = 1.5 or x = −3" },
          solution: [
            "{{2x^2 + 3x = 9}}, so {{2x^2 + 3x - 9 = 0}}.",
            "Factorise: (2x − 3)(x + 3) = 0.",
            "x = 1.5 or x = −3. Check: f(1.5) = 4.5 + 4.5 = 9 ✓; f(−3) = 18 − 9 = 9 ✓.",
          ],
          traps: [
            { spec: { type: "list", values: [-1.5, 3] }, feedback: "Both signs are flipped: 2x − 3 = 0 gives x = +1.5, and x + 3 = 0 gives x = −3." },
            { spec: { type: "list", values: [0, -1.5] }, feedback: "Those solve f(x) = 0. Move the 9 across first: {{2x^2 + 3x - 9 = 0}}." },
          ],
          commonError: "Forgetting to move the 9 across before factorising.",
          difficulty: "core",
          guideRef: "functions-as-mappings",
          hints: ["Set the expression equal to 9, then rearrange to = 0.", "{{2x^2 + 3x - 9 = 0}}. Try brackets (2x  )(x  ) — the numbers must multiply to −9.", "(2x − 3)(x + 3): check the middle term is +3x."],
          strategy: "Rearrange to = 0 first",
        },
        {
          kind: "short",
          id: "functions-p1-q07",
          question: "{{g(x) = 3/(x^2 - x - 12)}}\n\nFind the two values of x that must be excluded from the domain of g.",
          answer: { type: "list", values: [4, -3], display: "x = 4 and x = −3" },
          solution: [
            "Exclude any x that makes the denominator zero.",
            "{{x^2 - x - 12 = 0}}, so (x − 4)(x + 3) = 0.",
            "x = 4 or x = −3.",
          ],
          traps: [
            { spec: { type: "list", values: [-4, 3] }, feedback: "Sign slip: (x − 4)(x + 3) = 0 gives x = +4 and x = −3." },
            { spec: { type: "list", values: [0] }, feedback: "x = 0 is fine: g(0) = {{3/(-12)}}. Set the **denominator** equal to zero and solve the quadratic." },
          ],
          commonError: "Giving the roots with the wrong signs, or excluding x = 0 out of habit.",
          difficulty: "core",
          guideRef: "domain-range",
          hints: ["What value can a denominator never take?", "Solve {{x^2 - x - 12 = 0}}: two numbers multiplying to −12 and adding to −1."],
          strategy: "Look for the forbidden operation",
        },
        {
          kind: "short",
          id: "functions-p1-q08",
          question: "{{f(x) = 4/(x + 1)}}, with domain x ≥ 1.\n\nFind the range of f. Give your answer as an inequality, using y for the output (so the range of {{x^2}} would be written y ≥ 0).",
          answer: { type: "inequality", ineq: "0<y<=2", display: "0 < f(x) ≤ 2" },
          solution: [
            "As x increases, x + 1 increases, so {{4/(x + 1)}} decreases. The largest output comes from the smallest input.",
            "Smallest input x = 1: f(1) = {{4/2}} = 2.",
            "As x gets very large, f(x) gets close to 0 but never reaches it (a fraction with numerator 4 is never 0). So the range is 0 < f(x) ≤ 2.",
          ],
          traps: [
            { spec: { type: "inequality", ineq: "0<y<=4" }, feedback: "f(0) = 4, but x = 0 is not in the domain (x ≥ 1). Start from x = 1." },
            { spec: { type: "inequality", ineq: "y<=2" }, feedback: "Right top value — but can f(x) ever be 0 or negative when x ≥ 1? {{4/(x + 1)}} is always positive, so there is a lower bound too." },
          ],
          commonError: "Using x = 0 when the domain starts at x = 1.",
          difficulty: "core",
          guideRef: "domain-range",
          hints: ["Is f increasing or decreasing as x gets bigger?", "Decreasing — so the largest output comes from the smallest allowed input.", "Work out f(1)."],
          strategy: "Consider extremes",
        },
        {
          kind: "short",
          id: "functions-p1-q09",
          question: "{{f(x) = x^2}} and {{g(x) = x - 4}}\n\nFind fg(x). Give your answer in expanded form.",
          answer: { type: "expression", expr: "x^2-8x+16", form: "expanded", display: "{{x^2 - 8x + 16}}" },
          solution: ["fg(x) = f(g(x)) = f(x − 4).", "f squares its input: {{(x - 4)^2}}.", "{{= x^2 - 8x + 16}}"],
          traps: [
            { spec: { type: "expression", expr: "x^2-4" }, feedback: "That's gf(x): square first, then subtract 4. For fg(x), g acts first: {{(x - 4)^2}}." },
            { spec: { type: "expression", expr: "x^2+16" }, feedback: "{{(x - 4)^2}} is not {{x^2 + 16}} — expand both brackets: {{(x - 4)(x - 4) = x^2 - 8x + 16}}." },
          ],
          commonError: "Expanding {{(x - 4)^2}} as {{x^2 + 16}} or {{x^2 - 16}}.",
          difficulty: "core",
          guideRef: "composite-functions",
          hints: ["fg(x) = f(g(x)). What does f do to its input?", "f squares whatever goes in, so fg(x) = {{(x - 4)^2}}.", "Write (x − 4)(x − 4) and expand."],
          strategy: "Work from the inside out",
        },
        {
          kind: "written",
          id: "functions-p1-q10",
          question:
            "{{f(x) = 1/(x - 2)}}\n\nHana says, \"The domain of f is all real numbers.\"\n\n(a) Explain why Hana is wrong, and state the value that must be excluded.\n\n(b) Explain why 0 is not in the range of f.",
          marks: 3,
          modelAnswer:
            "(a) When x = 2 the denominator is 2 − 2 = 0, and you cannot divide by zero, so f(2) cannot be worked out. The domain is all real x except x = 2 (x ≠ 2).\n\n(b) If {{1/(x - 2) = 0}} then multiplying both sides by (x − 2) would give 1 = 0, which is impossible. A fraction with numerator 1 can never equal zero, so f(x) ≠ 0: 0 is not in the range.",
          markScheme: [
            { point: "Explains that x = 2 makes the denominator zero (you cannot divide by zero)", keywords: ["divide by zero", "division by zero", "denominator", "zero", "undefined", "0"] },
            { point: "States the excluded value x = 2 (domain x ≠ 2)", keywords: ["x = 2", "x=2", "x ≠ 2", "x != 2", "2"] },
            { point: "Explains f(x) = 0 is impossible, e.g. 1/(x − 2) = 0 leads to 1 = 0, or numerator is never zero", keywords: ["1 = 0", "1=0", "numerator", "never", "impossible", "cannot"] },
          ],
          commonError: "In (b), saying \"because x can't be 2\" — that is about the domain (inputs), not the range (outputs).",
          difficulty: "core",
          guideRef: "domain-range",
          hints: ["What happens to the denominator when x = 2?", "For (b): try to solve {{1/(x - 2) = 0}}. Multiply both sides by (x − 2)."],
          strategy: "Look for the forbidden operation",
        },
        {
          kind: "short",
          id: "functions-p1-q11",
          question: "{{f(x) = (3x + 2)/4}}\n\nFind f⁻¹(x).",
          answer: { type: "expression", expr: "(4x-2)/3", display: "f⁻¹(x) = {{(4x - 2)/3}}" },
          solution: [
            "Let y = {{(3x + 2)/4}}.",
            "Multiply by 4: 4y = 3x + 2.",
            "Subtract 2: 4y − 2 = 3x, so x = {{(4y - 2)/3}}.",
            "Swap letters: f⁻¹(x) = {{(4x - 2)/3}}.",
            "Check: f(6) = {{20/4}} = 5 and f⁻¹(5) = {{18/3}} = 6 ✓.",
          ],
          solutions: [
            {
              label: "Flowchart reversal",
              steps: [
                "f: x → × 3 → + 2 → ÷ 4.",
                "Reverse the order and undo each step: x → × 4 → − 2 → ÷ 3.",
                "f⁻¹(x) = {{(4x - 2)/3}}.",
              ],
            },
          ],
          traps: [
            { spec: { type: "expression", expr: "4/(3x+2)" }, feedback: "f⁻¹ is the inverse (undo), not the reciprocal. Rearrange y = {{(3x + 2)/4}} for x." },
            { spec: { type: "expression", expr: "(4x+2)/3" }, feedback: "To undo + 2 you **subtract** 2: 4y = 3x + 2 gives 3x = 4y − 2." },
            { spec: { type: "expression", expr: "(4x)/3-2" }, feedback: "Undo the steps in **reverse** order: subtract 2 before dividing by 3, giving {{(4x - 2)/3}}." },
          ],
          commonError: "Undoing the steps in the original order instead of the reverse order.",
          difficulty: "core",
          guideRef: "inverse-functions",
          hints: ["Write y = {{(3x + 2)/4}} and make x the subject.", "First multiply both sides by 4.", "4y − 2 = 3x. Divide by 3, then swap x and y."],
          strategy: "Use the inverse",
        },
        {
          kind: "written",
          id: "functions-p1-q12",
          question: "{{f(x) = 4x - 3}} and {{g(x) = (x + 3)/4}}\n\nShow that fg(x) = x and gf(x) = x, and explain what this tells you about f and g.",
          marks: 3,
          modelAnswer:
            "fg(x) = f({{(x + 3)/4}}) = {{4 * (x + 3)/4 - 3}} = x + 3 − 3 = x.\n\ngf(x) = g(4x − 3) = {{(4x - 3 + 3)/4 = (4x)/4}} = x.\n\nEach function undoes the other, so g is the inverse of f: g(x) = f⁻¹(x) (and f is the inverse of g). Their graphs are reflections of each other in y = x.",
          markScheme: [
            { point: "fg(x): substitutes g into f and simplifies 4(x + 3)/4 − 3 to x", keywords: ["4(x+3)/4", "x + 3 - 3", "x+3-3", "x + 3 − 3", "fg(x) = x", "fg(x)=x"] },
            { point: "gf(x): substitutes f into g and simplifies (4x − 3 + 3)/4 to x", keywords: ["(4x-3+3)/4", "4x/4", "gf(x) = x", "gf(x)=x"] },
            { point: "Concludes g is the inverse of f (g = f⁻¹)", keywords: ["inverse", "f⁻¹", "f^-1", "undo", "undoes"] },
          ],
          commonError: "Only checking one composition, or checking with a single number (e.g. x = 1) — that is an example, not a proof for all x.",
          difficulty: "core",
          guideRef: "inverse-functions",
          hints: ["fg(x): replace the x in f with the whole of {{(x + 3)/4}}.", "The 4 and the ÷ 4 cancel. What's left?", "If each function undoes the other, what's the word for that relationship?"],
          strategy: "Check by substituting",
        },
        {
          kind: "short",
          id: "functions-p1-q13",
          question:
            "{{g(x) = 1/(2x^2 - 12x + 23)}}, for all real values of x.\n\nFind the largest value that g(x) can take.",
          answer: { type: "fraction", n: 1, d: 5, allowDecimal: true, display: "{{1/5}}" },
          solution: [
            "g is largest when its denominator is smallest (the denominator is always positive).",
            "Complete the square: {{2x^2 - 12x + 23 = 2(x^2 - 6x) + 23 = 2(x - 3)^2 - 18 + 23 = 2(x - 3)^2 + 5}}.",
            "{{2(x - 3)^2 >= 0}}, so the denominator is at least 5, with 5 reached at x = 3.",
            "So the largest value of g is {{1/5}}.",
          ],
          solutions: [
            {
              label: "Use the vertex formula",
              steps: [
                "The minimum of {{2x^2 - 12x + 23}} is at {{x = -b/(2a) = 12/4 = 3}}.",
                "Denominator at x = 3: 18 − 36 + 23 = 5. So the maximum of g is {{1/5}}.",
              ],
            },
          ],
          traps: [
            { spec: { type: "number", value: 5 }, feedback: "5 is the smallest value of the **denominator**. g is 1 divided by that." },
            { spec: { type: "fraction", n: 1, d: 23 }, feedback: "That's g(0). The denominator gets smaller than 23 — find its minimum by completing the square." },
          ],
          commonError: "Finding the minimum of the denominator and forgetting to take the reciprocal.",
          difficulty: "challenge",
          guideRef: "domain-range",
          hints: [
            "A fraction {{1/D}} with D positive is biggest when D is …?",
            "Find the minimum value of {{2x^2 - 12x + 23}}.",
            "Complete the square: take out the 2 first — {{2(x^2 - 6x) + 23}}.",
            "{{2(x - 3)^2 + 5}} — the minimum is 5. Now what is g?",
          ],
          strategy: "Consider extremes",
        },
        {
          kind: "short",
          id: "functions-p1-q14",
          question:
            "{{f(x) = 2x - 3}} and {{g(x) = x^2 + 1}}\n\nSolve gf(x) = 15. Give your answers correct to 3 significant figures.",
          answer: { type: "list", values: [3.37, -0.371], tolerance: 0.005, display: "x = 3.37 or x = −0.371 (exactly {{(3 +- sqrt(14))/2}})" },
          solution: [
            "gf(x) = g(2x − 3) = {{(2x - 3)^2 + 1}}.",
            "{{(2x - 3)^2 + 1 = 15}}, so {{(2x - 3)^2 = 14}}.",
            "{{2x - 3 = +- sqrt(14) = +- 3.7417...}}",
            "2x = 6.7417… or 2x = −0.7417…, so x = 3.3708… or x = −0.37083…",
            "x = 3.37 or x = −0.371 (3 s.f.).",
          ],
          traps: [
            { spec: { type: "list", values: [2.83, -2.83], tolerance: 0.005 }, feedback: "You solved fg(x) = 15, i.e. {{2(x^2 + 1) - 3 = 15}}. In gf(x), f acts first: g(2x − 3) = {{(2x - 3)^2 + 1}}." },
            { spec: { type: "list", values: [3.37], tolerance: 0.005 }, feedback: "{{(2x - 3)^2 = 14}} gives 2x − 3 = +√14 **or** −√14 — don't forget the negative root." },
          ],
          commonError: "Forming fg(x) instead of gf(x), or missing the negative square root.",
          difficulty: "core",
          guideRef: "composite-functions",
          hints: [
            "Build gf(x) first as an expression: which function acts first?",
            "Replace the x in {{x^2 + 1}} with (2x − 3).",
            "{{(2x - 3)^2 = 14}}. Don't expand — square root both sides.",
            "Square root — both signs, then solve two linear equations.",
          ],
          strategy: "Work from the inside out",
        },
        {
          kind: "written",
          id: "functions-p1-q15",
          question:
            "{{f(x) = (x + 1)/(x - 1)}}, x ≠ 1.\n\n(a) Show that ff(x) = x.\n\n(b) Hence write down f⁻¹(x), explaining your reasoning.",
          marks: 3,
          modelAnswer:
            "(a) {{ff(x) = ((x + 1)/(x - 1) + 1)/((x + 1)/(x - 1) - 1)}}.\n\nMultiply the top and bottom of the big fraction by (x − 1):\n\n    {{ff(x) = ((x + 1) + (x - 1))/((x + 1) - (x - 1)) = (2x)/2 = x}}\n\n(b) Applying f twice gets you back to x, so f undoes itself: f⁻¹(x) = f(x) = {{(x + 1)/(x - 1)}}. f is *self-inverse*.",
          markScheme: [
            { point: "Substitutes f(x) into f correctly", keywords: ["(x+1)/(x-1) + 1", "(x+1)/(x-1)+1", "f((x+1)/(x-1))", "f(f(x))"] },
            { point: "Simplifies to 2x/2 = x (e.g. by multiplying through by x − 1)", keywords: ["2x/2", "2x", "x - 1", "x-1", "multiply", "= x"] },
            { point: "States f⁻¹(x) = (x + 1)/(x − 1) because f undoes itself (self-inverse)", keywords: ["self-inverse", "self inverse", "f⁻¹(x) = f(x)", "f^-1(x)=f(x)", "same", "undoes itself"] },
          ],
          solutions: [
            {
              label: "Find the inverse directly",
              steps: [
                "y = {{(x + 1)/(x - 1)}} → y(x − 1) = x + 1 → xy − y = x + 1.",
                "xy − x = y + 1 → x(y − 1) = y + 1 → x = {{(y + 1)/(y - 1)}}.",
                "Same formula as f, confirming f⁻¹ = f. The 'hence' route in (b) is quicker because part (a) has done the work.",
              ],
            },
          ],
          commonError: "Adding 1 to the numerator only: {{(x + 1)/(x - 1) + 1}} is NOT {{(x + 2)/(x - 1)}} — write 1 as {{(x - 1)/(x - 1)}}.",
          difficulty: "challenge",
          guideRef: "inverse-functions",
          hints: [
            "Replace each x in {{(x + 1)/(x - 1)}} with the whole fraction {{(x + 1)/(x - 1)}}.",
            "You get a fraction inside a fraction. Multiply its top and bottom by (x − 1).",
            "Top: (x + 1) + (x − 1). Bottom: (x + 1) − (x − 1).",
            "If doing f twice returns x, what must f⁻¹ be?",
          ],
          strategy: "Make it simpler",
        },
      ],
    },
    {
      id: "functions-p2",
      title: "Practice Paper 2",
      questions: [
        {
          kind: "short",
          id: "functions-p2-q01",
          question: "The function f is defined as f: x ↦ {{x/4 + 3}}.\n\nFind f(10).",
          answer: { type: "number", value: 5.5, display: "5.5" },
          solution: ["f(10) = {{10/4 + 3}}", "= 2.5 + 3 = 5.5."],
          traps: [{ spec: { type: "number", value: 3.25 }, feedback: "Only the x is divided by 4: {{x/4 + 3}}, not {{(x + 3)/4}}. So 10 ÷ 4 = 2.5, then add 3." }],
          commonError: "Reading {{x/4 + 3}} as {{(x + 3)/4}}.",
          difficulty: "warmup",
          guideRef: "functions-as-mappings",
          hints: ["Divide first, then add — order of operations.", "10 ÷ 4 = 2.5."],
        },
        {
          kind: "short",
          id: "functions-p2-q02",
          question:
            "The function g(x) = {{x^2}} has domain {−2, −1, 0, 1, 2}, as shown in the mapping diagram.\n\nHow many numbers are in the range of g?",
          diagram: `<svg viewBox="0 0 320 210" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Mapping diagram: the domain set containing minus 2, minus 1, 0, 1, 2 maps by g to a range set marked with a question mark"><rect x="0" y="0" width="320" height="210" fill="#ffffff"/><ellipse cx="80" cy="110" rx="46" ry="84" fill="#c7d2fe" stroke="#334155"/><ellipse cx="240" cy="110" rx="46" ry="84" fill="#fde68a" stroke="#334155"/><text x="80" y="18" font-size="13" font-family="sans-serif" text-anchor="middle" fill="#1f2937">Domain</text><text x="240" y="18" font-size="13" font-family="sans-serif" text-anchor="middle" fill="#1f2937">Range</text><text x="80" y="54" font-size="14" font-family="sans-serif" text-anchor="middle" fill="#1f2937">−2</text><text x="80" y="84" font-size="14" font-family="sans-serif" text-anchor="middle" fill="#1f2937">−1</text><text x="80" y="114" font-size="14" font-family="sans-serif" text-anchor="middle" fill="#1f2937">0</text><text x="80" y="144" font-size="14" font-family="sans-serif" text-anchor="middle" fill="#1f2937">1</text><text x="80" y="174" font-size="14" font-family="sans-serif" text-anchor="middle" fill="#1f2937">2</text><text x="240" y="118" font-size="22" font-family="sans-serif" text-anchor="middle" fill="#1f2937">?</text><line x1="132" y1="110" x2="188" y2="110" stroke="#1f2937" stroke-width="2"/><polygon points="188,104 198,110 188,116" fill="#1f2937"/><text x="160" y="98" font-size="13" font-family="sans-serif" text-anchor="middle" fill="#1f2937">g: x ↦ x²</text></svg>`,
          answer: { type: "number", value: 3 },
          solution: [
            "Work out every output: g(−2) = 4, g(−1) = 1, g(0) = 0, g(1) = 1, g(2) = 4.",
            "The range is the set of outputs, each listed once: {0, 1, 4}.",
            "So the range has 3 numbers. (Two inputs can share an output — g is many-to-one, which is allowed.)",
          ],
          traps: [{ spec: { type: "number", value: 5 }, feedback: "There are 5 inputs, but some outputs repeat: (−2)² and 2² are both 4. List each output once." }],
          commonError: "Counting outputs with repeats, or thinking a function must give different outputs for different inputs.",
          difficulty: "warmup",
          guideRef: "domain-range",
          hints: ["Work out g of each of the five inputs.", "Write the set of outputs — a set lists each value only once."],
          strategy: "Make a table",
        },
        {
          kind: "short",
          id: "functions-p2-q03",
          question: "{{f(x) = x + 5}} and {{g(x) = 3x}}\n\nWork out gf(2).",
          answer: { type: "number", value: 21 },
          solution: ["gf(2) = g(f(2)) — f acts first.", "f(2) = 7.", "g(7) = 21."],
          traps: [{ spec: { type: "number", value: 11 }, feedback: "That's fg(2) = f(6) = 11. In gf(2), f is next to the 2, so f acts first." }],
          commonError: "Doing the left-hand function first.",
          difficulty: "warmup",
          guideRef: "composite-functions",
          hints: ["Which function sits next to the 2?", "Find f(2), then put the answer into g."],
          strategy: "Work from the inside out",
        },
        {
          kind: "short",
          id: "functions-p2-q04",
          question: "{{f(x) = 6x + 1}}\n\nFind f⁻¹(x).",
          answer: { type: "expression", expr: "(x-1)/6", display: "f⁻¹(x) = {{(x - 1)/6}}" },
          solution: ["y = 6x + 1.", "y − 1 = 6x, so x = {{(y - 1)/6}}.", "f⁻¹(x) = {{(x - 1)/6}}."],
          traps: [{ spec: { type: "expression", expr: "x/6-1" }, feedback: "Undo the steps in **reverse** order: f does × 6 then + 1, so f⁻¹ does − 1 first, then ÷ 6: {{(x - 1)/6}}." }],
          commonError: "Undoing in the wrong order, giving {{x/6 - 1}}.",
          difficulty: "warmup",
          guideRef: "inverse-functions",
          hints: ["Write y = 6x + 1 and make x the subject.", "Subtract 1 first, then divide by 6."],
          strategy: "Use the inverse",
        },
        {
          kind: "short",
          id: "functions-p2-q05",
          question: "{{f(x) = (3x + 1)/(x - 2)}}, x ≠ 2.\n\nFind the value of x for which f(x) = 4.",
          answer: { type: "number", value: 9 },
          solution: [
            "{{(3x + 1)/(x - 2) = 4}}",
            "Multiply both sides by (x − 2): 3x + 1 = 4(x − 2) = 4x − 8.",
            "1 + 8 = 4x − 3x, so x = 9.",
            "Check: f(9) = {{28/7}} = 4 ✓.",
          ],
          traps: [{ spec: { type: "number", value: -7 }, feedback: "Check the expansion: 4(x − 2) = 4x − **8**. Then 3x + 1 = 4x − 8 gives x = 9." }],
          commonError: "Multiplying only the x by 4: writing 4x − 2 instead of 4x − 8.",
          difficulty: "core",
          guideRef: "functions-as-mappings",
          hints: ["Set the fraction equal to 4.", "Multiply both sides by (x − 2) — bracket it!", "3x + 1 = 4x − 8. Collect the x terms."],
          strategy: "Clear the fraction",
        },
        {
          kind: "short",
          id: "functions-p2-q06",
          question:
            "A taxi in Singapore charges according to the function C(d) = 4.1 + 0.6d, where C(d) is the fare in dollars for a journey of d km.\n\nArjun's fare was $16.10. How far did he travel? Give your answer in km.",
          answer: { type: "number", value: 20 },
          solution: [
            "C(d) = 16.10, so 4.1 + 0.6d = 16.1.",
            "0.6d = 12.",
            "d = 12 ÷ 0.6 = 20 km.",
          ],
          traps: [{ spec: { type: "number", value: 13.76 }, feedback: "That's C(16.1) — the fare for a 16.1 km trip. Here $16.10 is the output; solve C(d) = 16.1." }],
          commonError: "Substituting the fare as d instead of solving C(d) = 16.1.",
          difficulty: "core",
          guideRef: "functions-as-mappings",
          hints: ["Is $16.10 the input or the output of C?", "Solve 4.1 + 0.6d = 16.1.", "0.6d = 12. Divide by 0.6."],
          strategy: "Work backwards",
        },
        {
          kind: "short",
          id: "functions-p2-q07",
          question: "{{f(x) = sqrt(10 - 2x)}}, where f(x) must be a real number.\n\nState the domain of f. Give your answer as an inequality in x.",
          answer: { type: "inequality", ineq: "x<=5", display: "x ≤ 5" },
          solution: ["The expression under the root must not be negative: 10 − 2x ≥ 0.", "10 ≥ 2x, so x ≤ 5.", "x = 5 is allowed (f(5) = √0 = 0), so the domain is x ≤ 5."],
          traps: [
            { spec: { type: "inequality", ineq: "x>=5" }, feedback: "Test x = 6: √(10 − 12) = √(−2) is not real. Solve 10 − 2x ≥ 0 by adding 2x to both sides: 10 ≥ 2x, so x ≤ 5." },
            { spec: { type: "inequality", ineq: "x>=-5" }, feedback: "Test x = 6: √(10 − 12) = √(−2) is not real, so large x must be excluded. Solve 10 − 2x ≥ 0." },
          ],
          commonError: "Forgetting to reverse the inequality when dividing by −2, giving x ≥ 5.",
          difficulty: "core",
          guideRef: "domain-range",
          hints: ["What must be true of the number under the square root?", "Solve 10 − 2x ≥ 0. Add 2x to both sides first to avoid dividing by a negative."],
          strategy: "Look for the forbidden operation",
        },
        {
          kind: "short",
          id: "functions-p2-q08",
          question:
            "{{f(x) = 7 - 2x}}, with domain −1 ≤ x ≤ 3.\n\nFind the range of f. Give your answer as an inequality, using y for the output.",
          answer: { type: "inequality", ineq: "1<=y<=9", display: "1 ≤ f(x) ≤ 9" },
          solution: [
            "f is a straight line with negative gradient, so it is decreasing: the ends of the domain give the extremes.",
            "f(−1) = 7 + 2 = 9 and f(3) = 7 − 6 = 1.",
            "The smallest output is 1 and the largest is 9: 1 ≤ f(x) ≤ 9.",
          ],
          traps: [
            { spec: { type: "inequality", ineq: "-1<=y<=3" }, feedback: "−1 ≤ x ≤ 3 is the domain (inputs). The range is the set of outputs: work out f(−1) and f(3)." },
            { spec: { type: "inequality", ineq: "1<=x<=9" }, feedback: "Right numbers, but a range describes **outputs** — write it with y (or f(x)), not x." },
          ],
          commonError: "Copying the domain across, or assuming f(left end) is always the minimum — not for a decreasing function.",
          difficulty: "core",
          guideRef: "domain-range",
          hints: ["Work out f at each end of the domain.", "f is decreasing, so which end gives the smaller output?"],
          strategy: "Consider extremes",
        },
        {
          kind: "short",
          id: "functions-p2-q09",
          question: "{{f(x) = 1/(x + 2)}} and {{g(x) = 3x - 1}}\n\nFind fg(x). Give your answer as a single fraction, simplified.",
          answer: { type: "expression", expr: "1/(3x+1)", form: "simplified", display: "fg(x) = {{1/(3x + 1)}}" },
          solution: ["fg(x) = f(3x − 1).", "f(input) = {{1/(input + 2)}}, so fg(x) = {{1/(3x - 1 + 2)}}.", "{{= 1/(3x + 1)}}"],
          traps: [{ spec: { type: "expression", expr: "3/(x+2)-1" }, feedback: "That's gf(x) = 3f(x) − 1. For fg(x), put g(x) = 3x − 1 *into* f." }],
          commonError: "Composing in the wrong order.",
          difficulty: "core",
          guideRef: "composite-functions",
          hints: ["fg(x) = f(g(x)). What does f do to its input?", "f adds 2 to its input and takes the reciprocal.", "Input is 3x − 1: {{1/(3x - 1 + 2)}}."],
          strategy: "Work from the inside out",
        },
        {
          kind: "written",
          id: "functions-p2-q10",
          question:
            "{{f(x) = x + 3}} and {{g(x) = x^2}}\n\nShow that there is exactly one value of x for which fg(x) = gf(x), and find it.",
          marks: 3,
          modelAnswer:
            "fg(x) = f({{x^2}}) = {{x^2 + 3}}.\n\ngf(x) = g(x + 3) = {{(x + 3)^2 = x^2 + 6x + 9}}.\n\nSetting them equal: {{x^2 + 3 = x^2 + 6x + 9}}. The {{x^2}} terms cancel, leaving the linear equation 3 = 6x + 9, so 6x = −6 and x = −1.\n\nA linear equation has exactly one solution, so there is exactly one such value: x = −1. Check: fg(−1) = 1 + 3 = 4 and gf(−1) = {{2^2}} = 4 ✓.",
          markScheme: [
            { point: "Correct fg(x) = x² + 3 and gf(x) = (x + 3)²", keywords: ["x^2 + 3", "x^2+3", "x² + 3", "(x+3)^2", "(x + 3)²", "(x+3)²"] },
            { point: "Expands to x² + 6x + 9, sets equal and cancels x² to get a linear equation", keywords: ["x^2+6x+9", "x² + 6x + 9", "6x + 9", "6x+9", "cancel", "linear"] },
            { point: "x = −1, with a reason there is only one (linear equation / one solution)", keywords: ["x = -1", "x=-1", "x = −1", "-1", "−1", "one solution", "linear"] },
          ],
          commonError: "Expanding {{(x + 3)^2}} as {{x^2 + 9}}, which gives the impossible 3 = 9 and the wrong conclusion that there are no solutions.",
          difficulty: "core",
          guideRef: "composite-functions",
          hints: ["Write out fg(x) and gf(x) separately.", "Expand {{(x + 3)^2}} fully — three terms.", "Set them equal. What happens to the {{x^2}} terms?"],
          strategy: "Introduce a variable",
        },
        {
          kind: "short",
          id: "functions-p2-q11",
          question: "{{f(x) = 5 - 2x}}\n\nFind f⁻¹(x). Write just the expression in x.",
          answer: { type: "expression", expr: "(5-x)/2", display: "f⁻¹(x) = {{(5 - x)/2}}" },
          solution: ["y = 5 − 2x.", "2x = 5 − y.", "x = {{(5 - y)/2}}, so f⁻¹(x) = {{(5 - x)/2}}.", "Check: f⁻¹(f(1)) = f⁻¹(3) = {{(5 - 3)/2}} = 1 ✓."],
          traps: [
            { spec: { type: "expression", expr: "(x-5)/2" }, feedback: "Sign slip. From y = 5 − 2x, add 2x and subtract y: 2x = 5 − y, so x = {{(5 - y)/2}}." },
            { spec: { type: "expression", expr: "1/(5-2x)" }, feedback: "f⁻¹ undoes f — it is not the reciprocal of f." },
          ],
          commonError: "Losing the minus sign when the x-term is negative.",
          difficulty: "core",
          guideRef: "inverse-functions",
          hints: ["Write y = 5 − 2x.", "Move the x-term to the side where it will be positive: 2x = 5 − y.", "Divide by 2 and swap letters."],
          strategy: "Check by substituting",
        },
        {
          kind: "short",
          id: "functions-p2-q12",
          question: "{{f(x) = x^2 - 3}}, with domain x ≥ 0.\n\nFind f⁻¹(x).",
          answer: { type: "expression", expr: "sqrt(x+3)", display: "f⁻¹(x) = {{sqrt(x + 3)}}" },
          solution: [
            "y = {{x^2 - 3}}, so {{x^2 = y + 3}}.",
            "x = {{sqrt(y + 3)}} — positive root only, because the domain of f is x ≥ 0.",
            "f⁻¹(x) = {{sqrt(x + 3)}}, with domain x ≥ −3 (the range of f).",
            "Check: f(2) = 1 and f⁻¹(1) = √4 = 2 ✓.",
          ],
          traps: [{ spec: { type: "expression", expr: "sqrt(x)+3" }, feedback: "Undo in reverse order: add 3 **first**, then square root: {{sqrt(x + 3)}}, not {{sqrt(x) + 3}}." }],
          commonError: "Square rooting before adding 3.",
          difficulty: "core",
          guideRef: "inverse-functions",
          hints: ["f does: square, then − 3. Undo in reverse order.", "Add 3, then square root.", "Why only the positive root? Look at the domain of f."],
          strategy: "Use the inverse",
        },
        {
          kind: "written",
          id: "functions-p2-q13",
          question:
            "{{f(x) = (x + 1)^2}}\n\n(a) Explain why f has no inverse function when its domain is all real numbers.\n\n(b) The domain of f is now restricted to x ≤ −1. Find f⁻¹(x).",
          marks: 3,
          modelAnswer:
            "(a) f is many-to-one: for example f(0) = 1 and f(−2) = 1. An inverse would have to send 1 back to both 0 and −2, so it would not be a function. So f has no inverse on all real numbers.\n\n(b) Let y = {{(x + 1)^2}}. Since x ≤ −1, x + 1 ≤ 0, so x + 1 is the **negative** square root: x + 1 = {{-sqrt(y)}}.\n\nSo x = {{-1 - sqrt(y)}}, and f⁻¹(x) = {{-1 - sqrt(x)}} (for x ≥ 0).\n\nCheck: f⁻¹(4) = −1 − 2 = −3, and f(−3) = {{(-2)^2}} = 4 ✓.",
          markScheme: [
            { point: "Explains f is many-to-one with an example (two inputs give the same output), so the inverse would be one-to-many", keywords: ["many-to-one", "many to one", "two inputs", "same output", "f(0)", "f(-2)", "not one-to-one"] },
            { point: "Rearranges to x + 1 = ±√y and chooses the negative root because x + 1 ≤ 0", keywords: ["negative root", "-sqrt", "−√", "x + 1 ≤ 0", "x+1<=0", "negative"] },
            { point: "f⁻¹(x) = −1 − √x", keywords: ["-1 - sqrt(x)", "-1-sqrt(x)", "−1 − √x", "-1 - √x", "-1-√x"] },
          ],
          commonError: "Taking the positive root and getting {{sqrt(x) - 1}} — that gives outputs ≥ −1, which are not in the restricted domain.",
          difficulty: "challenge",
          guideRef: "inverse-functions",
          hints: [
            "Find two different inputs with the same output.",
            "For (b): y = {{(x + 1)^2}} gives x + 1 = ±√y. Which sign?",
            "If x ≤ −1, is x + 1 positive or negative?",
          ],
          strategy: "Test a specific value",
        },
        {
          kind: "short",
          id: "functions-p2-q14",
          question:
            "The function f is given by f(x) = ax + b, where a and b are constants and a > 0.\n\nff(x) = 9x − 8.\n\nFind a and b. Give a first, then b.",
          answer: { type: "list", values: [3, -2], ordered: true, display: "a = 3, b = −2" },
          solution: [
            "ff(x) = f(ax + b) = a(ax + b) + b = {{a^2 x + ab + b}}.",
            "Compare with 9x − 8: {{a^2 = 9}} and ab + b = −8.",
            "a > 0, so a = 3. Then 3b + b = 4b = −8, so b = −2.",
            "Check: f(x) = 3x − 2, ff(x) = 3(3x − 2) − 2 = 9x − 8 ✓.",
          ],
          traps: [
            { spec: { type: "list", values: [-3, 4], ordered: true }, feedback: "a = −3 does give ff(x) = 9x − 8 (with b = 4) — but the question says a > 0." },
            { spec: { type: "list", values: [3, -8], ordered: true }, feedback: "The constant term of ff(x) is ab + b, not just b. With a = 3: 4b = −8." },
          ],
          commonError: "Assuming the constant in ff(x) equals b.",
          difficulty: "challenge",
          guideRef: "composite-functions",
          hints: [
            "Write ff(x) in terms of a and b.",
            "f(ax + b) = a(ax + b) + b. Expand.",
            "Compare coefficients: the x-coefficient and the constant term.",
            "{{a^2 = 9}} with a > 0, then solve ab + b = −8.",
          ],
          strategy: "Compare coefficients",
        },
        {
          kind: "written",
          id: "functions-p2-q15",
          question:
            "{{f(x) = x^2 - 4x + 7}}, with domain x ≥ 2.\n\n(a) Write f(x) in the form {{(x - p)^2 + q}}.\n\n(b) State the range of f.\n\n(c) Find f⁻¹(x) and state its domain.",
          marks: 4,
          modelAnswer:
            "(a) Half of −4 is −2: {{x^2 - 4x + 7 = (x - 2)^2 - 4 + 7 = (x - 2)^2 + 3}}.\n\n(b) For x ≥ 2, {{(x - 2)^2 >= 0}} with 0 reached at x = 2, so f(x) ≥ 3.\n\n(c) y = {{(x - 2)^2 + 3}}, so {{(x - 2)^2 = y - 3}} and x − 2 = {{sqrt(y - 3)}} (positive root, since x ≥ 2 means x − 2 ≥ 0).\n\nSo f⁻¹(x) = {{2 + sqrt(x - 3)}}. Its domain is the range of f: x ≥ 3.",
          markScheme: [
            { point: "(x − 2)² + 3", keywords: ["(x-2)^2+3", "(x - 2)² + 3", "(x-2)²+3", "(x - 2)^2 + 3"] },
            { point: "Range f(x) ≥ 3", keywords: ["f(x) >= 3", "f(x) ≥ 3", "f(x)>=3", "≥ 3", ">= 3", "y ≥ 3"] },
            { point: "f⁻¹(x) = 2 + √(x − 3), using the positive root because x ≥ 2", keywords: ["2 + sqrt(x-3)", "2+sqrt(x-3)", "2 + √(x − 3)", "2+√(x-3)", "positive root"] },
            { point: "Domain of f⁻¹ is x ≥ 3 (the range of f)", keywords: ["x >= 3", "x ≥ 3", "x>=3", "range of f"] },
          ],
          commonError: "Writing f⁻¹(x) = {{2 +- sqrt(x - 3)}}: the ± would make it one-to-many. The restriction x ≥ 2 picks the + sign.",
          difficulty: "challenge",
          guideRef: "inverse-functions",
          hints: [
            "Halve the coefficient of x to complete the square.",
            "The minimum of {{(x - 2)^2 + 3}} is at x = 2 — which is the edge of the domain.",
            "Rearrange y = {{(x - 2)^2 + 3}} for x. Which sign of the square root fits x ≥ 2?",
            "The domain of f⁻¹ is always the range of f.",
          ],
          strategy: "Make it a perfect square",
        },
      ],
    },
  ],

  // =========================================================================
  // Challenge set — 10 AoPS-hard problems
  // =========================================================================
  challenge: [
    {
      kind: "short",
      id: "functions-ch-q01",
      question: "{{f(x) = 2x + 1}}\n\nSolve fff(x) = 63.",
      answer: { type: "number", value: 7 },
      solution: [
        "ff(x) = 2(2x + 1) + 1 = 4x + 3.",
        "fff(x) = 2(4x + 3) + 1 = 8x + 7.",
        "8x + 7 = 63, so 8x = 56 and x = 7.",
      ],
      solutions: [
        {
          label: "Work backwards with f⁻¹",
          steps: [
            "f⁻¹(x) = {{(x - 1)/2}}. Apply it three times to 63.",
            "f⁻¹(63) = 31, f⁻¹(31) = 15, f⁻¹(15) = 7.",
            "So x = 7 — no algebra needed. Quicker here because 63 unwinds to whole numbers.",
          ],
        },
      ],
      traps: [{ spec: { type: "number", value: 31 }, feedback: "That solves f(x) = 63 — one application of f. You need three: fff(x) = 8x + 7." }],
      commonError: "Writing fff(x) = 6x + 3 (multiplying the function by 3) instead of composing.",
      difficulty: "challenge",
      guideRef: "composite-functions",
      hints: [
        "fff(x) means f(f(f(x))). Build it up one step at a time.",
        "ff(x) = 4x + 3. Now apply f once more.",
        "fff(x) = 8x + 7. Solve.",
        "Alternative: what input gives 63? Then what gives that?",
      ],
      strategy: "Work backwards",
    },
    {
      kind: "short",
      id: "functions-ch-q02",
      question: "A function f satisfies\n\n    f(x) + 2f(1 − x) = 3x\n\nfor every real number x. Find f(0).",
      answer: { type: "number", value: 2 },
      solution: [
        "Put x = 0: f(0) + 2f(1) = 0.",
        "Put x = 1: f(1) + 2f(0) = 3.",
        "From the first, f(0) = −2f(1). Substitute: f(1) + 2(−2f(1)) = 3, so −3f(1) = 3 and f(1) = −1.",
        "Then f(0) = −2 × (−1) = 2.",
      ],
      solutions: [
        {
          label: "Find f(x) in general",
          steps: [
            "Replace x by 1 − x: f(1 − x) + 2f(x) = 3(1 − x).",
            "Call A = f(x), B = f(1 − x): A + 2B = 3x and 2A + B = 3 − 3x.",
            "Double the second and subtract the first: 3A = 6 − 6x − 3x = 6 − 9x, so f(x) = 2 − 3x.",
            "f(0) = 2. Check: (2 − 3x) + 2(2 − 3(1 − x)) = 2 − 3x − 2 + 6x = 3x ✓.",
          ],
        },
      ],
      traps: [{ spec: { type: "number", value: -1 }, feedback: "That's f(1). You need f(0) = −2f(1)." }],
      commonError: "Substituting only x = 0 and trying to solve one equation in two unknowns.",
      difficulty: "challenge",
      guideRef: "functions-as-mappings",
      hints: [
        "Substitute a value of x that makes things simple. x = 0?",
        "x = 0 gives one equation in f(0) and f(1). Which other x gives an equation in the same two unknowns?",
        "x = 1 gives f(1) + 2f(0) = 3. Now solve simultaneously.",
      ],
      strategy: "Use symmetry",
    },
    {
      kind: "short",
      id: "functions-ch-q03",
      question: "{{f(x) = (3x - 2)/(x + 4)}}, x ≠ −4.\n\nFind f⁻¹(x), giving your answer as a single fraction.",
      answer: { type: "expression", expr: "(4x+2)/(3-x)", display: "f⁻¹(x) = {{(4x + 2)/(3 - x)}}" },
      solution: [
        "y = {{(3x - 2)/(x + 4)}}, so y(x + 4) = 3x − 2.",
        "xy + 4y = 3x − 2.",
        "Collect the x terms on one side: xy − 3x = −2 − 4y, so x(y − 3) = −(4y + 2).",
        "x = {{(4y + 2)/(3 - y)}}. So f⁻¹(x) = {{(4x + 2)/(3 - x)}} (x ≠ 3).",
        "Check: f(1) = {{1/5}}, and f⁻¹({{1/5}}) = {{(4/5 + 2)/(3 - 1/5) = (14/5)/(14/5)}} = 1 ✓.",
      ],
      traps: [{ spec: { type: "expression", expr: "(x+4)/(3x-2)" }, feedback: "That's the reciprocal of f, not its inverse. Rearrange y = {{(3x - 2)/(x + 4)}} to make x the subject." }],
      commonError: "Not collecting both x terms on one side — the subject appears twice, so you must factorise x out.",
      difficulty: "challenge",
      guideRef: "inverse-functions",
      hints: [
        "Write y = f(x) and clear the fraction.",
        "xy + 4y = 3x − 2. x appears twice — get both x terms on one side.",
        "Factorise: x(y − 3) = …",
        "Divide, then swap x and y. Tidy the signs.",
      ],
      strategy: "Change the subject (factorise)",
    },
    {
      kind: "short",
      id: "functions-ch-q04",
      question:
        "{{f(x) = sqrt(x^2 - 4x - 12)}}, where f(x) must be a real number.\n\nThe domain of f is x ≤ a or x ≥ b. Find a and b. Give a first, then b.",
      answer: { type: "list", values: [-2, 6], ordered: true, display: "x ≤ −2 or x ≥ 6" },
      solution: [
        "Need {{x^2 - 4x - 12 >= 0}}.",
        "Factorise: (x − 6)(x + 2) ≥ 0. Critical values x = −2 and x = 6.",
        "The parabola {{y = x^2 - 4x - 12}} is ∪-shaped, so it is ≥ 0 *outside* the roots.",
        "Domain: x ≤ −2 or x ≥ 6, so a = −2, b = 6.",
      ],
      traps: [{ spec: { type: "list", values: [2, -6], ordered: true }, feedback: "Sign slip: (x − 6)(x + 2) = 0 gives x = 6 and x = −2." }],
      commonError: "Giving −2 ≤ x ≤ 6 — that's where the quadratic is negative, exactly where the root fails.",
      difficulty: "challenge",
      guideRef: "domain-range",
      hints: [
        "What must be true of the expression inside the square root?",
        "Solve {{x^2 - 4x - 12 >= 0}}. Factorise first.",
        "Sketch y = (x − 6)(x + 2). Where is it above the x-axis?",
      ],
      strategy: "Draw a diagram",
    },
    {
      kind: "short",
      id: "functions-ch-q05",
      question:
        "{{f(x) = x^2 - 2x}} and g(x) = x + k, where k is a non-zero constant.\n\nThe equation fg(x) = gf(x) has the solution x = 2. Find k.",
      answer: { type: "number", value: -1 },
      solution: [
        "fg(x) = {{(x + k)^2 - 2(x + k) = x^2 + 2kx + k^2 - 2x - 2k}}.",
        "gf(x) = {{x^2 - 2x + k}}.",
        "fg(x) − gf(x) = {{2kx + k^2 - 3k}}.",
        "At x = 2: {{4k + k^2 - 3k = k^2 + k = k(k + 1) = 0}}.",
        "k ≠ 0, so k = −1. Check: fg(2) = f(1) = −1 and gf(2) = g(0) = −1 ✓.",
      ],
      solutions: [
        {
          label: "Substitute x = 2 straight away",
          steps: [
            "fg(2) = f(2 + k) = {{(2 + k)^2 - 2(2 + k) = k^2 + 2k}}.",
            "gf(2) = g(0) = k, since f(2) = 4 − 4 = 0.",
            "{{k^2 + 2k = k}}, so {{k^2 + k = 0}}, k = 0 or −1. Quicker — no general expansion needed.",
          ],
        },
      ],
      traps: [{ spec: { type: "number", value: 1 }, feedback: "Check the sign: {{k^2 + k = 0}} gives k(k + 1) = 0, so k = −1 (k = 0 is excluded)." }],
      commonError: "Dividing by k too early and losing track, or forgetting the −2k from expanding −2(x + k).",
      difficulty: "challenge",
      guideRef: "composite-functions",
      hints: [
        "You only need the equation at x = 2. Can you substitute early?",
        "f(2) = 0, so gf(2) = g(0) = k.",
        "fg(2) = f(2 + k). Expand and set equal to k.",
        "k² + k = 0 — and k ≠ 0.",
      ],
      strategy: "Make it simpler",
    },
    {
      kind: "short",
      id: "functions-ch-q06",
      question:
        "{{f(x) = x^2 - 2}}, with domain x ≥ 0.\n\nThe graphs of y = f(x) and y = f⁻¹(x) meet at one point. Find the x-coordinate of this point.",
      answer: { type: "number", value: 2 },
      solution: [
        "f is increasing on x ≥ 0. For an increasing function, the graphs of f and f⁻¹ are reflections in y = x and they meet on y = x.",
        "So solve f(x) = x: {{x^2 - 2 = x}}, i.e. {{x^2 - x - 2 = 0}}.",
        "(x − 2)(x + 1) = 0, so x = 2 or x = −1.",
        "x = −1 is not in the domain (x ≥ 0), so x = 2. Check: f(2) = 2 and f⁻¹(2) = √(2 + 2) = 2 ✓.",
      ],
      solutions: [
        {
          label: "Find f⁻¹ and equate",
          steps: [
            "f⁻¹(x) = {{sqrt(x + 2)}}.",
            "{{x^2 - 2 = sqrt(x + 2)}} — awkward to solve directly (squaring gives a quartic).",
            "The y = x shortcut turns a quartic into a quadratic: this is why it's worth knowing.",
          ],
        },
      ],
      traps: [{ spec: { type: "number", value: -1 }, feedback: "x = −1 solves {{x^2 - x - 2 = 0}}, but it is outside the domain x ≥ 0." }],
      commonError: "Keeping x = −1, which is not in the domain of f.",
      difficulty: "challenge",
      guideRef: "inverse-functions",
      hints: [
        "How are the graphs of f and f⁻¹ related geometrically?",
        "They're reflections in y = x. Where would an increasing curve meet its own reflection?",
        "Solve f(x) = x.",
        "Check each solution against the domain.",
      ],
      strategy: "Use symmetry",
    },
    {
      kind: "short",
      id: "functions-ch-q07",
      question: "{{f(x) = 2x + 3}} and {{g(x) = x^3}}\n\nWork out (fg)⁻¹(19).",
      answer: { type: "number", value: 2 },
      solution: [
        "(fg)⁻¹(19) is the input x for which fg(x) = 19.",
        "fg(x) = {{2x^3 + 3}}. So {{2x^3 + 3 = 19}}, {{x^3 = 8}}, x = 2.",
      ],
      solutions: [
        {
          label: "Undo in reverse: (fg)⁻¹ = g⁻¹f⁻¹",
          steps: [
            "To undo 'g then f' you undo f first, then g — like taking off shoes before socks.",
            "f⁻¹(19) = {{(19 - 3)/2}} = 8.",
            "g⁻¹(8) = {{cbrt(8)}} = 2.",
          ],
        },
      ],
      traps: [{ spec: { type: "number", value: 13721 }, feedback: "That's fg(19) = 2 × 19³ + 3. The ⁻¹ asks which input gives 19." }],
      commonError: "Undoing in the wrong order: g⁻¹ first then f⁻¹ gives {{(cbrt(19) - 3)/2}} — that's (gf)⁻¹(19).",
      difficulty: "challenge",
      guideRef: "inverse-functions",
      hints: [
        "(fg)⁻¹(19) = the x such that fg(x) = 19.",
        "Build fg(x), or undo the functions one at a time.",
        "fg does g first, then f — so undo f first.",
      ],
      strategy: "Work backwards",
    },
    {
      kind: "short",
      id: "functions-ch-q08",
      question:
        "{{f(x) = 1/(1 - x)}}, x ≠ 0, 1.\n\nLet {{f^n}} mean f applied n times, so {{f^2(x) = ff(x)}}.\n\nWork out {{f^2027(3)}}. Give your answer as a fraction.",
      answer: { type: "fraction", n: 2, d: 3, display: "{{2/3}}" },
      solution: [
        "Try small cases: f(3) = {{1/(1 - 3) = -1/2}}.",
        "f(−{{1/2}}) = {{1/(1 + 1/2) = 2/3}}.",
        "f({{2/3}}) = {{1/(1 - 2/3) = 3}}. Back to the start!",
        "The values cycle with period 3: 3 → −{{1/2}} → {{2/3}} → 3 → …",
        "2027 = 3 × 675 + 2, so {{f^2027(3) = f^2(3) = 2/3}}.",
      ],
      solutions: [
        {
          label: "Show fff(x) = x algebraically",
          steps: [
            "ff(x) = {{1/(1 - 1/(1 - x)) = (1 - x)/((1 - x) - 1) = (x - 1)/x}}.",
            "fff(x) = {{1/(1 - (x - 1)/x) = x/(x - (x - 1)) = x}}.",
            "So {{f^3}} is the identity for every allowed x — the cycle is not a fluke of the number 3.",
          ],
        },
      ],
      traps: [
        { spec: { type: "fraction", n: -1, d: 2 }, feedback: "Nearly — check the remainder: 2027 = 3 × 675 + **2**, so you need {{f^2(3)}}, not f(3)." },
        { spec: { type: "number", value: 3 }, feedback: "{{f^3(3)}} = 3, but 2027 is not a multiple of 3. Find the remainder when 2027 is divided by 3." },
      ],
      commonError: "Off-by-one with the remainder: a remainder of 2 means two applications after completing the cycles.",
      difficulty: "challenge",
      guideRef: "composite-functions",
      hints: [
        "2027 applications by hand? No — try small cases first.",
        "Work out f(3), then f of that, then f of that.",
        "You're back at 3 after three steps. What does that tell you?",
        "Divide 2027 by 3 — the remainder tells you where you land.",
      ],
      strategy: "Find a pattern",
    },
    {
      kind: "short",
      id: "functions-ch-q09",
      question: "f is a linear function, f(x) = ax + b.\n\nf(2) = 7 and ff(2) = 22.\n\nWork out f⁻¹(40).",
      answer: { type: "number", value: 13 },
      solution: [
        "ff(2) = f(f(2)) = f(7) = 22.",
        "So 2a + b = 7 and 7a + b = 22. Subtract: 5a = 15, a = 3, b = 1.",
        "f(x) = 3x + 1. f⁻¹(40): solve 3x + 1 = 40, x = 13.",
      ],
      solutions: [
        {
          label: "Use the gradient",
          steps: [
            "The points (2, 7) and (7, 22) lie on the line y = f(x): gradient {{(22 - 7)/(7 - 2) = 3}}.",
            "From (7, 22), output 40 is 18 higher, so the input is {{18/3}} = 6 further along: 7 + 6 = 13.",
          ],
        },
      ],
      traps: [{ spec: { type: "number", value: 121 }, feedback: "That's f(40) = 3 × 40 + 1. f⁻¹(40) asks which input gives 40." }],
      commonError: "Reading ff(2) = 22 as f(4) = 22 or 2f(2) = 22.",
      difficulty: "challenge",
      guideRef: "functions-as-mappings",
      hints: [
        "ff(2) = f(f(2)). What is f(2)?",
        "So f(7) = 22. Now you have two facts about a straight line.",
        "Find a and b, then solve f(x) = 40.",
      ],
      strategy: "Work from the inside out",
    },
    {
      kind: "written",
      id: "functions-ch-q10",
      question:
        "a, b and c are constants with {{a^2 + bc != 0}} and c ≠ 0.\n\n{{f(x) = (ax + b)/(cx - a)}}, for x ≠ {{a/c}}.\n\nProve that f is self-inverse, i.e. f⁻¹(x) = f(x).",
      marks: 3,
      modelAnswer:
        "Let y = {{(ax + b)/(cx - a)}}. Multiply by (cx − a): cxy − ay = ax + b.\n\nCollect the x terms: cxy − ax = ay + b, so x(cy − a) = ay + b.\n\nTherefore x = {{(ay + b)/(cy - a)}}. Swapping letters, f⁻¹(x) = {{(ax + b)/(cx - a)}} = f(x), so f is self-inverse.\n\n(The condition {{a^2 + bc != 0}} stops f being constant: if {{a^2 + bc = 0}} the numerator is a multiple of the denominator and f has no inverse.)",
      markScheme: [
        { point: "Clears the fraction: y(cx − a) = ax + b, i.e. cxy − ay = ax + b", keywords: ["cxy", "y(cx - a)", "y(cx-a)", "cxy - ay", "cxy-ay"] },
        { point: "Collects x terms and factorises: x(cy − a) = ay + b", keywords: ["x(cy - a)", "x(cy-a)", "ay + b", "ay+b", "factorise"] },
        { point: "Concludes f⁻¹(x) = (ax + b)/(cx − a) = f(x)", keywords: ["(ax+b)/(cx-a)", "(ax + b)/(cx - a)", "f⁻¹(x) = f(x)", "f^-1(x)=f(x)", "self-inverse", "same"] },
      ],
      solutions: [
        {
          label: "Show ff(x) = x",
          steps: [
            "ff(x) = {{(a * (ax + b)/(cx - a) + b)/(c * (ax + b)/(cx - a) - a)}}. Multiply top and bottom by (cx − a).",
            "Top: {{a(ax + b) + b(cx - a) = a^2 x + bcx = (a^2 + bc)x}}.",
            "Bottom: {{c(ax + b) - a(cx - a) = bc + a^2}}.",
            "So ff(x) = x (dividing by {{a^2 + bc != 0}}), hence f⁻¹ = f. This route shows exactly where the condition is needed.",
          ],
        },
      ],
      commonError: "Testing with particular numbers (e.g. a = 1, b = 2, c = 3) — an example is not a proof.",
      difficulty: "challenge",
      guideRef: "inverse-functions",
      hints: [
        "Find f⁻¹ the usual way: y = f(x), make x the subject.",
        "After clearing the fraction, x appears twice. Get both x terms on one side.",
        "Factorise x out. Compare your answer with f.",
      ],
      strategy: "Change the subject (factorise)",
    },
  ],
};
