// Straight-line graphs & coordinate geometry — MCQ papers (3 × 15). Options are shuffled at display time.
import type { Paper } from "../../types.ts";

export const mcqPapers: Paper[] = [
  {
    id: "linear-graphs-m1",
    title: "MCQ Paper 1",
    questions: [
      {
        kind: "mcq",
        id: "linear-graphs-m1-q01",
        question: "Work out the gradient of the straight line through the points (1, 3) and (4, 12).",
        options: ["3", "{{1/3}}", "−3", "5"],
        answerIndex: 0,
        explanation:
          "Gradient = change in y ÷ change in x: {{(12 - 3)/(4 - 1) = 9/3 = 3}}. {{1/3}} is run over rise — upside down. −3 mixes the order of subtraction ({{(12 - 3)/(1 - 4)}}). 5 comes from adding the coordinates, {{(12 + 3)/(4 - 1)}}, instead of finding the differences.",
        difficulty: "warmup",
        guideRef: "y-mx-c",
        hints: ["Gradient = change in y ÷ change in x. Subtract in the same order on the top and the bottom."],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m1-q02",
        question: "What is the gradient of the line {{5x + 3y = 15}}?",
        options: ["5", "{{-3/5}}", "{{-5/3}}", "{{5/3}}"],
        answerIndex: 2,
        explanation:
          "Make y the subject: {{3y = -5x + 15}}, so {{y = -5/3 x + 5}} and the gradient is {{-5/3}}. 5 is the coefficient of x *before* rearranging — m can only be read off when the equation is y = mx + c. {{5/3}} forgets that 5x changes sign when it moves across. {{-3/5}} divides the wrong way round.",
        difficulty: "warmup",
        guideRef: "y-mx-c",
        hints: ["Rearrange into the form y = mx + c first — subtract 5x, then divide everything by 3."],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m1-q03",
        question: "A is the point (−2, 5) and B is the point (6, −1). Find the coordinates of the midpoint of AB.",
        options: ["(4, −3)", "(2, 2)", "(4, 4)", "(2, 3)"],
        answerIndex: 1,
        explanation:
          "Midpoint = average of the coordinates: {{((-2 + 6)/2, (5 + (-1))/2) = (2, 2)}}. (4, −3) halves the *differences* (that is half the journey from A to B, not the point reached). (4, 4) adds but forgets to halve. (2, 3) treats −1 as +1 in the y-coordinate.",
        difficulty: "warmup",
        guideRef: "midpoint-distance",
        hints: ["The midpoint's coordinates are the means of the x-coordinates and of the y-coordinates."],
        strategy: "Use symmetry",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m1-q04",
        question: "Which line is parallel to {{y = 4x - 3}}?",
        options: ["{{y = 7x - 3}}", "{{y = -1/4 x - 3}}", "{{y = -4x + 1}}", "{{y = 4x + 7}}"],
        answerIndex: 3,
        explanation:
          "Parallel lines have **equal gradients**; the intercept can be anything. {{y = 4x + 7}} has gradient 4. {{y = 7x - 3}} shares the intercept, not the gradient. {{y = -1/4 x - 3}} is *perpendicular* (gradients multiply to −1). {{y = -4x + 1}} has the opposite slope.",
        difficulty: "warmup",
        guideRef: "parallel-perpendicular",
        hints: ["Which part of y = mx + c controls the steepness of a line?"],
        strategy: "Eliminate options",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m1-q05",
        question: "A straight line has gradient −3 and passes through the point (2, −5). Find its equation.",
        options: ["{{y = -3x + 11}}", "{{y = -3x - 11}}", "{{y = -3x + 1}}", "{{y = -3x - 5}}"],
        answerIndex: 2,
        explanation:
          "Use {{y - y_1 = m(x - x_1)}}: {{y - (-5) = -3(x - 2)}}, so {{y + 5 = -3x + 6}} and {{y = -3x + 1}}. Check: −3 × 2 + 1 = −5 ✓. {{y = -3x + 11}} writes y − 5 instead of y + 5. {{y = -3x - 11}} uses x + 2 instead of x − 2. {{y = -3x - 5}} wrongly takes the y-coordinate of the point as the intercept — the point is not on the y-axis.",
        difficulty: "core",
        guideRef: "point-gradient-form",
        hints: [
          "Which form of a line uses one point and the gradient?",
          "Substitute into {{y - y_1 = m(x - x_1)}} with {{x_1 = 2}} and {{y_1 = -5}}.",
          "Careful: {{y - (-5)}} is y + 5. Then expand −3(x − 2).",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m1-q06",
        question: "Work out the length of the line segment joining (−2, 3) and (6, −3).",
        options: ["10", "14", "{{sqrt(52)}}", "100"],
        answerIndex: 0,
        explanation:
          "Horizontal change 6 − (−2) = 8, vertical change −3 − 3 = −6. By Pythagoras, length = {{sqrt(8^2 + (-6)^2) = sqrt(100) = 10}}. 14 adds the two changes — that is the walk along the grid, not the straight line. {{sqrt(52)}} uses 6 − 2 = 4 for the horizontal change (losing the double negative). 100 forgets the square root.",
        difficulty: "core",
        guideRef: "midpoint-distance",
        hints: [
          "Sketch the right-angled triangle with the segment as its hypotenuse.",
          "The legs are the change in x and the change in y — watch the negative coordinate.",
          "Length = √((change in x)² + (change in y)²).",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m1-q07",
        question: "Find the gradient of a line perpendicular to {{2x - 5y = 10}}.",
        options: ["{{-2/5}}", "{{-1/2}}", "{{5/2}}", "{{-5/2}}"],
        answerIndex: 3,
        explanation:
          "Rearrange: {{5y = 2x - 10}}, so {{y = 2/5 x - 2}} with gradient {{2/5}}. The perpendicular gradient is the negative reciprocal: {{-5/2}} (check: {{2/5 * (-5/2) = -1}}). {{-2/5}} changes the sign but forgets to flip. {{5/2}} flips but forgets the sign. {{-1/2}} uses the coefficient 2 as if the equation were already y = 2x + c.",
        difficulty: "core",
        guideRef: "parallel-perpendicular",
        hints: [
          "First find the gradient of the given line — rearrange to y = mx + c.",
          "The given gradient is {{2/5}}. Perpendicular gradients multiply to −1.",
        ],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m1-q08",
        question: "Find the point where the lines {{y = 2x + 1}} and {{y = -x + 7}} intersect.",
        options: ["(5, 2)", "(2, 5)", "(6, 13)", "(−2, 9)"],
        answerIndex: 1,
        explanation:
          "At the intersection both y-values are equal: {{2x + 1 = -x + 7}}, so {{3x = 6}}, x = 2 and y = 2(2) + 1 = 5. Check in the other line: −2 + 7 = 5 ✓. (5, 2) swaps the coordinates. (6, 13) comes from 2x − x = 7 − 1 (moving −x across without changing its sign). (−2, 9) moves both the 1 and the 7 the wrong way, getting 3x = −6.",
        difficulty: "core",
        guideRef: "intersections",
        hints: [
          "At the crossing point, both equations give the same y. Set them equal.",
          "Solve {{2x + 1 = -x + 7}}, then substitute x back to find y.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m1-q09",
        question: "The diagram shows the straight line L. Find the equation of L.",
        diagram: `<svg viewBox="0 0 228 264" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Grid from −1 to 4 on the x-axis and −1 to 5 on the y-axis with a straight line L crossing the y-axis at 4 and the x-axis at 2"><rect x="0" y="0" width="228" height="264" fill="#ffffff"/><line x1="24" y1="240" x2="24" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="60" y1="240" x2="60" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="96" y1="240" x2="96" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="132" y1="240" x2="132" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="168" y1="240" x2="168" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="204" y1="240" x2="204" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="240" x2="204" y2="240" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="204" x2="204" y2="204" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="168" x2="204" y2="168" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="132" x2="204" y2="132" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="96" x2="204" y2="96" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="60" x2="204" y2="60" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="24" x2="204" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="204" x2="212" y2="204" stroke="#334155" stroke-width="1.5"/><line x1="60" y1="240" x2="60" y2="16" stroke="#334155" stroke-width="1.5"/><text x="214" y="208" font-size="13" font-style="italic" font-family="sans-serif" fill="#334155">x</text><text x="65" y="14" font-size="13" font-style="italic" font-family="sans-serif" fill="#334155">y</text><text x="24" y="218" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−1</text><text x="96" y="218" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">1</text><text x="132" y="218" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">2</text><text x="168" y="218" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">3</text><text x="204" y="218" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">4</text><text x="55" y="244" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−1</text><text x="55" y="172" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">1</text><text x="55" y="136" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">2</text><text x="55" y="100" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">3</text><text x="55" y="64" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">4</text><text x="55" y="28" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">5</text><text x="55" y="218" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155">O</text><line x1="42" y1="24" x2="150" y2="240" stroke="#1d4ed8" stroke-width="2"/><text x="153.6" y="225.6" font-size="12" font-family="sans-serif" fill="#1d4ed8" stroke="#ffffff" stroke-width="3" paint-order="stroke">L</text><circle cx="60" cy="60" r="3.5" fill="#1f2937"/><circle cx="132" cy="204" r="3.5" fill="#1f2937"/></svg>`,
        options: ["{{y = 2x + 4}}", "{{y = -2x + 4}}", "{{y = -1/2 x + 4}}", "{{y = -2x + 2}}"],
        answerIndex: 1,
        explanation:
          "L crosses the y-axis at (0, 4), so c = 4. From (0, 4) to (2, 0) y falls by 4 while x rises by 2, so m = {{-4/2 = -2}}: {{y = -2x + 4}}. {{y = 2x + 4}} misses that the line slopes *down* to the right. {{y = -1/2 x + 4}} is run over rise. {{y = -2x + 2}} uses the x-intercept as c — c is where the line crosses the **y**-axis.",
        difficulty: "core",
        guideRef: "y-mx-c",
        hints: [
          "Where does L cross the y-axis? That gives c.",
          "Pick two clear points on L and find change in y ÷ change in x. Is the line going uphill or downhill?",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m1-q10",
        question: "A line passes through (2, 5) and (6, −3). Find its equation in the form {{ax + by + c = 0}}, where a, b and c are integers.",
        options: ["{{2x - y + 9 = 0}}", "{{x + 2y - 12 = 0}}", "{{2x + y - 1 = 0}}", "{{2x + y - 9 = 0}}"],
        answerIndex: 3,
        explanation:
          "Gradient {{(-3 - 5)/(6 - 2) = -8/4 = -2}}. Then {{y - 5 = -2(x - 2)}} gives {{y = -2x + 9}}, i.e. {{2x + y - 9 = 0}}. Check (6, −3): 12 − 3 − 9 = 0 ✓. {{2x - y + 9 = 0}} is y = 2x + 9 (gradient sign lost). {{x + 2y - 12 = 0}} uses gradient {{-1/2}} (run over rise). {{2x + y - 1 = 0}} comes from y − 5 = −2(x + 2), a sign slip with the point.",
        difficulty: "core",
        guideRef: "point-gradient-form",
        hints: [
          "Find the gradient first.",
          "Use {{y - y_1 = m(x - x_1)}} with either point.",
          "Collect everything on one side so that the x term is positive.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m1-q11",
        question: "Find the point of intersection of the lines {{3x + 2y = 16}} and {{y = x - 2}}.",
        options: ["(4, 2)", "(2, 4)", "(3.6, 1.6)", "(2.4, 0.4)"],
        answerIndex: 0,
        explanation:
          "Substitute y = x − 2: {{3x + 2(x - 2) = 16}}, so {{5x - 4 = 16}}, 5x = 20, x = 4 and y = 2. Check: 12 + 4 = 16 ✓. (3.6, 1.6) expands 2(x − 2) as 2x − 2. (2.4, 0.4) moves the −4 across without changing sign (5x = 12). (2, 4) swaps x and y.",
        difficulty: "core",
        guideRef: "intersections",
        hints: [
          "One equation already says what y is. Substitute it into the other.",
          "Put x − 2 in a bracket: 3x + 2(x − 2) = 16.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m1-q12",
        question: "A is (1, 2) and B is (5, 6). Find the equation of the perpendicular bisector of AB.",
        options: ["{{y = x + 1}}", "{{y = -x + 3}}", "{{y = -x + 7}}", "{{y = -x + 11}}"],
        answerIndex: 2,
        explanation:
          "The perpendicular bisector passes through the **midpoint** (3, 4) and is **perpendicular** to AB. Gradient of AB = {{4/4 = 1}}, so the bisector has gradient −1: {{y - 4 = -(x - 3)}}, giving {{y = -x + 7}}. {{y = x + 1}} is the line AB itself. {{y = -x + 3}} and {{y = -x + 11}} have the right gradient but pass through A and B instead of the midpoint.",
        difficulty: "core",
        guideRef: "parallel-perpendicular",
        hints: [
          "\"Bisector\" tells you a point it goes through; \"perpendicular\" tells you its gradient.",
          "Midpoint of AB is (3, 4). Gradient of AB is 1.",
          "Use gradient −1 through (3, 4).",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m1-q13",
        question: "The diagram shows the lines {{y = 2x + 4}} and {{y = -x + 4}}. Work out the area of the shaded triangle formed by the two lines and the x-axis.",
        diagram: `<svg viewBox="0 0 288 258" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Grid showing the lines y = 2x + 4 and y = −x + 4 meeting on the y-axis at (0, 4); the triangle they form with the x-axis is shaded"><rect x="0" y="0" width="288" height="258" fill="#ffffff"/><line x1="24" y1="234" x2="24" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="54" y1="234" x2="54" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="84" y1="234" x2="84" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="114" y1="234" x2="114" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="144" y1="234" x2="144" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="174" y1="234" x2="174" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="204" y1="234" x2="204" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="234" y1="234" x2="234" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="264" y1="234" x2="264" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="234" x2="264" y2="234" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="204" x2="264" y2="204" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="174" x2="264" y2="174" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="144" x2="264" y2="144" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="114" x2="264" y2="114" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="84" x2="264" y2="84" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="54" x2="264" y2="54" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="24" x2="264" y2="24" stroke="#e2e8f0" stroke-width="1"/><polygon points="54,204 234,204 114,84" fill="#fde68a" stroke="none" opacity="0.8"/><line x1="24" y1="204" x2="272" y2="204" stroke="#334155" stroke-width="1.5"/><line x1="114" y1="234" x2="114" y2="16" stroke="#334155" stroke-width="1.5"/><text x="274" y="208" font-size="13" font-style="italic" font-family="sans-serif" fill="#334155">x</text><text x="119" y="14" font-size="13" font-style="italic" font-family="sans-serif" fill="#334155">y</text><text x="24" y="218" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−3</text><text x="54" y="218" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−2</text><text x="84" y="218" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−1</text><text x="144" y="218" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">1</text><text x="174" y="218" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">2</text><text x="204" y="218" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">3</text><text x="234" y="218" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">4</text><text x="264" y="218" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">5</text><text x="109" y="238" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−1</text><text x="109" y="178" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">1</text><text x="109" y="148" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">2</text><text x="109" y="118" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">3</text><text x="109" y="88" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">4</text><text x="109" y="58" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">5</text><text x="109" y="28" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">6</text><text x="109" y="218" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155">O</text><line x1="39" y1="234" x2="144" y2="24" stroke="#1d4ed8" stroke-width="2"/><text x="147" y="42" font-size="12" font-family="sans-serif" fill="#1d4ed8" stroke="#ffffff" stroke-width="3" paint-order="stroke">y = 2x + 4</text><line x1="54" y1="24" x2="264" y2="234" stroke="#b91c1c" stroke-width="2"/><text x="192" y="138" font-size="12" font-family="sans-serif" fill="#b91c1c" stroke="#ffffff" stroke-width="3" paint-order="stroke">y = −x + 4</text></svg>`,
        options: ["24", "8", "4", "12"],
        answerIndex: 3,
        explanation:
          "x-intercepts: {{2x + 4 = 0}} gives x = −2; {{-x + 4 = 0}} gives x = 4. So the base runs from −2 to 4, length 6. Both lines pass through (0, 4), so the height is 4. Area = {{1/2 * 6 * 4 = 12}}. 24 forgets the {{1/2}}. 8 uses only the part of the base from 0 to 4. 4 takes the first x-intercept as +2 instead of −2, giving a base of 2.",
        difficulty: "challenge",
        guideRef: "intersections",
        hints: [
          "Find the three corners: where each line meets the x-axis, and where the lines meet each other.",
          "Set y = 0 in each equation. Careful with the sign for y = 2x + 4.",
          "The base is the distance between the x-intercepts; the height is the y-coordinate of the top vertex.",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m1-q14",
        question: "A is (2, −1) and B is (14, 7). The point P lies on AB with AP : PB = 3 : 1. Find the coordinates of P.",
        options: ["(11, 5)", "(5, 1)", "(8, 3)", "(10.5, 5.25)"],
        answerIndex: 0,
        explanation:
          "AP is {{3/4}} of AB. {{B - A = (12, 8)}}, so {{P = A + 3/4(12, 8) = (2 + 9, -1 + 6) = (11, 5)}}. (5, 1) goes only {{1/4}} of the way — the ratio read from the wrong end. (8, 3) is the midpoint. (10.5, 5.25) is {{3/4}} of B's coordinates, forgetting to start from A.",
        difficulty: "challenge",
        guideRef: "dividing-a-line",
        hints: [
          "AP : PB = 3 : 1 means AB is split into 4 equal parts. What fraction of the way from A to B is P?",
          "Find the step from A to B: subtract A from B.",
          "P = A + {{3/4}}(B − A).",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m1-q15",
        question: "A is (1, 2) and B is (5, 4). The point C lies on the x-axis and is the same distance from A as from B. Find the coordinates of C.",
        options: ["(3, 0)", "(4.5, 0)", "(9, 0)", "(−3, 0)"],
        answerIndex: 1,
        explanation:
          "Let C = (x, 0). Then {{CA^2 = CB^2}}: {{(x - 1)^2 + 4 = (x - 5)^2 + 16}}. Expanding, {{x^2 - 2x + 5 = x^2 - 10x + 41}}, so 8x = 36 and x = 4.5. (Equivalently, C is where the perpendicular bisector of AB, {{y - 3 = -2(x - 3)}}, meets y = 0.) (3, 0) is just below the midpoint — that only works if AB is horizontal. (9, 0) uses gradient {{-1/2}} instead of −2 for the bisector. (−3, 0) uses AB's own gradient, {{1/2}}.",
        difficulty: "challenge",
        guideRef: "midpoint-distance",
        hints: [
          "Call the point (x, 0). Write an expression for its distance to A and to B.",
          "Square both distances so the roots disappear, then set them equal.",
          "The {{x^2}} terms cancel, leaving a linear equation.",
        ],
        strategy: "Introduce a variable",
      },
    ],
  },
  {
    id: "linear-graphs-m2",
    title: "MCQ Paper 2",
    questions: [
      {
        kind: "mcq",
        id: "linear-graphs-m2-q01",
        question: "Which of these points lies on the line {{y = 3x - 5}}?",
        options: ["(0, 5)", "(2, 1)", "(1, 2)", "(5, 0)"],
        answerIndex: 1,
        explanation:
          "Substitute x = 2: 3 × 2 − 5 = 1 ✓, so (2, 1) is on the line. (0, 5) gets the sign of the intercept wrong (the line crosses at (0, −5)). (1, 2) swaps the coordinates: at x = 1, y = −2. (5, 0) treats 5 as the x-intercept; the line actually crosses the x-axis at {{x = 5/3}}.",
        difficulty: "warmup",
        guideRef: "y-mx-c",
        hints: ["Substitute the x-coordinate of each point into 3x − 5 and see whether you get its y-coordinate."],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m2-q02",
        question: "Where does the line {{4x - 3y = 12}} cross the y-axis?",
        options: ["(0, 4)", "(3, 0)", "(0, 12)", "(0, −4)"],
        answerIndex: 3,
        explanation:
          "On the y-axis x = 0, so {{-3y = 12}} and y = −4: the point is (0, −4). (0, 4) loses the minus sign. (3, 0) is where it crosses the **x**-axis (put y = 0). (0, 12) reads the constant straight off without rearranging.",
        difficulty: "warmup",
        guideRef: "y-mx-c",
        hints: ["Every point on the y-axis has x = 0. Substitute and solve for y."],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m2-q03",
        question: "A is (−3, 1) and B is (2, 13). Work out the length of AB.",
        options: ["13", "17", "{{sqrt(145)}}", "169"],
        answerIndex: 0,
        explanation:
          "Changes: 2 − (−3) = 5 and 13 − 1 = 12. Length = {{sqrt(5^2 + 12^2) = sqrt(169) = 13}}. 17 adds 5 + 12 (the grid walk). {{sqrt(145)}} uses 2 − 3 = −1 for the x-change. 169 forgets the square root.",
        difficulty: "warmup",
        guideRef: "midpoint-distance",
        hints: ["Find the change in x and the change in y, then use Pythagoras."],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m2-q04",
        question: "Write down the gradient of a line perpendicular to {{y = -3x + 2}}.",
        options: ["{{-1/3}}", "3", "{{1/3}}", "−3"],
        answerIndex: 2,
        explanation:
          "Negative reciprocal of −3: flip to {{-1/3}}, then change the sign to {{1/3}}. Check: {{-3 * 1/3 = -1}} ✓. {{-1/3}} flips but does not change sign. 3 changes sign but does not flip. −3 is the *parallel* gradient.",
        difficulty: "warmup",
        guideRef: "parallel-perpendicular",
        hints: ["Perpendicular gradients multiply to give −1. What times −3 gives −1?"],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m2-q05",
        question: "Find the equation of the line through (−1, 4) that is parallel to {{y = 5x + 2}}.",
        options: ["{{y = 5x + 2}}", "{{y = 5x - 1}}", "{{y = 5x + 4}}", "{{y = 5x + 9}}"],
        answerIndex: 3,
        explanation:
          "Parallel means gradient 5. {{y - 4 = 5(x - (-1)) = 5(x + 1)}}, so {{y = 5x + 9}}. Check: 5(−1) + 9 = 4 ✓. {{y = 5x + 2}} is the original line — it does not pass through (−1, 4). {{y = 5x - 1}} uses x − 1 instead of x + 1. {{y = 5x + 4}} takes the y-coordinate of the point as the intercept.",
        difficulty: "core",
        guideRef: "point-gradient-form",
        hints: [
          "What gradient does a parallel line have?",
          "Use {{y - y_1 = m(x - x_1)}} with (−1, 4). What is x − (−1)?",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m2-q06",
        question: "M(3, −2) is the midpoint of PQ. P is the point (−1, 5). Find the coordinates of Q.",
        options: ["(1, 1.5)", "(7, −9)", "(4, −7)", "(−5, 12)"],
        answerIndex: 1,
        explanation:
          "From P to M the step is (+4, −7). Repeat the same step from M to reach Q: (3 + 4, −2 − 7) = (7, −9). Check: midpoint of (−1, 5) and (7, −9) is (3, −2) ✓. (1, 1.5) is the midpoint of P and M. (4, −7) is the step itself, not the point. (−5, 12) steps the wrong way, back past P.",
        difficulty: "core",
        guideRef: "midpoint-distance",
        hints: [
          "M is halfway, so Q is as far beyond M as M is beyond P.",
          "Work out the step from P to M, then add it on to M.",
        ],
        strategy: "Work backwards",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m2-q07",
        question: "A line passes through (−2, 7) and (4, −2). Find its gradient.",
        options: ["{{-3/2}}", "{{-2/3}}", "{{3/2}}", "{{-9/2}}"],
        answerIndex: 0,
        explanation:
          "{{(-2 - 7)/(4 - (-2)) = -9/6 = -3/2}}. {{-2/3}} is run over rise. {{3/2}} drops the sign — the line goes down to the right. {{-9/2}} uses 4 − 2 for the change in x, losing the double negative.",
        difficulty: "core",
        guideRef: "y-mx-c",
        hints: [
          "Gradient = change in y ÷ change in x.",
          "The change in x is 4 − (−2). What is that?",
        ],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m2-q08",
        question: "The diagram shows the lines {{y = x - 2}} and {{x + y = 4}}. Use the graph to solve the simultaneous equations\n\n    {{y = x - 2}}\n    {{x + y = 4}}",
        diagram: `<svg viewBox="0 0 228 288" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Grid showing the straight lines y = x − 2 and x + y = 4 crossing each other"><rect x="0" y="0" width="228" height="288" fill="#ffffff"/><line x1="24" y1="264" x2="24" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="54" y1="264" x2="54" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="84" y1="264" x2="84" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="114" y1="264" x2="114" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="144" y1="264" x2="144" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="174" y1="264" x2="174" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="204" y1="264" x2="204" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="264" x2="204" y2="264" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="234" x2="204" y2="234" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="204" x2="204" y2="204" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="174" x2="204" y2="174" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="144" x2="204" y2="144" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="114" x2="204" y2="114" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="84" x2="204" y2="84" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="54" x2="204" y2="54" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="24" x2="204" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="174" x2="212" y2="174" stroke="#334155" stroke-width="1.5"/><line x1="54" y1="264" x2="54" y2="16" stroke="#334155" stroke-width="1.5"/><text x="214" y="178" font-size="13" font-style="italic" font-family="sans-serif" fill="#334155">x</text><text x="59" y="14" font-size="13" font-style="italic" font-family="sans-serif" fill="#334155">y</text><text x="24" y="188" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−1</text><text x="84" y="188" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">1</text><text x="114" y="188" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">2</text><text x="144" y="188" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">3</text><text x="174" y="188" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">4</text><text x="204" y="188" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">5</text><text x="49" y="268" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−3</text><text x="49" y="238" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−2</text><text x="49" y="208" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−1</text><text x="49" y="148" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">1</text><text x="49" y="118" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">2</text><text x="49" y="88" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">3</text><text x="49" y="58" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">4</text><text x="49" y="28" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">5</text><text x="49" y="188" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155">O</text><line x1="24" y1="264" x2="204" y2="84" stroke="#1d4ed8" stroke-width="2"/><text x="153" y="78" font-size="12" font-family="sans-serif" fill="#1d4ed8" stroke="#ffffff" stroke-width="3" paint-order="stroke">y = x − 2</text><line x1="24" y1="24" x2="204" y2="204" stroke="#b91c1c" stroke-width="2"/><text x="66" y="36" font-size="12" font-family="sans-serif" fill="#b91c1c" stroke="#ffffff" stroke-width="3" paint-order="stroke">x + y = 4</text></svg>`,
        options: ["x = 1, y = 3", "x = 2, y = 0", "x = 3, y = 1", "x = 4, y = 0"],
        answerIndex: 2,
        explanation:
          "The solution is the point that lies on **both** lines — where they cross, (3, 1). Check: 1 = 3 − 2 ✓ and 3 + 1 = 4 ✓. x = 1, y = 3 reads the coordinates the wrong way round. (2, 0) and (4, 0) are where each line crosses the x-axis — each is on only one line.",
        difficulty: "core",
        guideRef: "intersections",
        hints: [
          "A solution has to make both equations true at once. Which point is on both lines?",
          "Read off the crossing point, then check it in both equations.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m2-q09",
        question: "Find the equation of the line that passes through (4, 1) and is perpendicular to {{2x + 3y = 6}}.",
        options: ["{{y = -2/3 x + 11/3}}", "{{y = 3/2 x + 7}}", "{{y = 3/2 x - 5}}", "{{y = -3/2 x + 7}}"],
        answerIndex: 2,
        explanation:
          "{{2x + 3y = 6}} gives {{y = -2/3 x + 2}}, gradient {{-2/3}}. Perpendicular gradient = {{3/2}}. {{y - 1 = 3/2(x - 4)}}, so {{y = 3/2 x - 5}}. Check: {{3/2 * 4 - 5 = 1}} ✓. {{y = -2/3 x + 11/3}} is the *parallel* line through the point. {{y = 3/2 x + 7}} uses x + 4. {{y = -3/2 x + 7}} flips the gradient but keeps the minus sign.",
        difficulty: "core",
        guideRef: "parallel-perpendicular",
        hints: [
          "Rearrange 2x + 3y = 6 to read off its gradient.",
          "Take the negative reciprocal of {{-2/3}}.",
          "Use {{y - 1 = m(x - 4)}} with the new gradient.",
        ],
        strategy: "Use the inverse",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m2-q10",
        question: "A line has gradient {{3/4}} and passes through (3, −2). Which is its equation in the form {{ax + by + c = 0}}?",
        options: ["{{3x - 4y - 17 = 0}}", "{{3x - 4y + 17 = 0}}", "{{4x - 3y - 18 = 0}}", "{{3x - 4y - 1 = 0}}"],
        answerIndex: 0,
        explanation:
          "{{y + 2 = 3/4(x - 3)}}. Multiply by 4: {{4y + 8 = 3x - 9}}, so {{3x - 4y - 17 = 0}}. Check (3, −2): 9 + 8 − 17 = 0 ✓. {{3x - 4y + 17 = 0}} has the wrong sign on the constant — it does not pass through (3, −2). {{4x - 3y - 18 = 0}} uses gradient {{4/3}}. {{3x - 4y - 1 = 0}} writes y − 2 instead of y + 2.",
        difficulty: "core",
        guideRef: "point-gradient-form",
        hints: [
          "Start with {{y - y_1 = m(x - x_1)}}. Careful: y − (−2).",
          "Multiply both sides by 4 to clear the fraction.",
          "Check your final answer by substituting (3, −2).",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m2-q11",
        question: "Which statement about the simultaneous equations {{y = 3x - 2}} and {{6x - 2y = 4}} is true?",
        options: [
          "No solutions — the lines are parallel",
          "Exactly one solution, x = 0, y = −2",
          "Exactly one solution, x = 1, y = 1",
          "Infinitely many solutions — they are the same line",
        ],
        answerIndex: 3,
        explanation:
          "Rearrange the second: {{2y = 6x - 4}}, so {{y = 3x - 2}} — the **same line**. Every point on it solves both, so there are infinitely many solutions. \"Parallel\" checks only the gradients; parallel lines must also have *different* intercepts. (0, −2) and (1, 1) do satisfy both equations, but they are just two of infinitely many solutions.",
        difficulty: "core",
        guideRef: "intersections",
        hints: [
          "Rearrange 6x − 2y = 4 into the form y = mx + c.",
          "Compare both the gradients and the intercepts.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m2-q12",
        question: "The points A(1, 0), C(5, 2) and B(13, 6) lie on a straight line. Find the ratio AC : CB.",
        options: ["2 : 1", "1 : 2", "1 : 3", "5 : 13"],
        answerIndex: 1,
        explanation:
          "A to C is the step (4, 2); C to B is (8, 4) — exactly twice as long in the same direction. So AC : CB = 1 : 2. 2 : 1 reverses the order. 1 : 3 is AC : AB (C is a third of the way along). 5 : 13 compares the x-coordinates of C and B instead of the distances.",
        difficulty: "core",
        guideRef: "dividing-a-line",
        hints: [
          "Find the step from A to C and the step from C to B.",
          "How many times longer is the second step than the first?",
        ],
        strategy: "Find a pattern",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m2-q13",
        question: "The lines {{y = 3x + 1}} and {{y = -x + 9}} and the y-axis form a triangle. Work out its area.",
        options: ["8", "16", "28", "9"],
        answerIndex: 0,
        explanation:
          "The lines cross where {{3x + 1 = -x + 9}}: x = 2, y = 7. They meet the y-axis at (0, 1) and (0, 9), so the base along the y-axis is 9 − 1 = 8. The height is the horizontal distance to (2, 7), which is 2. Area = {{1/2 * 8 * 2 = 8}}. 16 forgets the {{1/2}}. 28 uses the y-coordinate 7 as the height. 9 uses the intercept 9 as the base.",
        difficulty: "challenge",
        guideRef: "intersections",
        hints: [
          "Sketch it. The base of this triangle lies along the y-axis.",
          "Find both y-intercepts and the point where the lines cross.",
          "The height is measured perpendicular to the base — horizontally, so it is the x-coordinate of the crossing point.",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m2-q14",
        question: "A is (−3, 4) and B is (9, −4). P lies on AB such that AP : PB = 1 : 3. Find the coordinates of P.",
        options: ["(6, −2)", "(3, 0)", "(0, 2)", "(1, {{4/3}})"],
        answerIndex: 2,
        explanation:
          "1 : 3 means 4 equal parts, P is {{1/4}} of the way from A. {{B - A = (12, -8)}}, so {{P = (-3 + 3, 4 - 2) = (0, 2)}}. (6, −2) is {{3/4}} of the way — the ratio applied from B's end. (3, 0) is the midpoint. (1, {{4/3}}) goes {{1/3}} of the way, treating 1 : 3 as \"one third\".",
        difficulty: "challenge",
        guideRef: "dividing-a-line",
        hints: [
          "How many equal parts is AB divided into? What fraction of AB is AP?",
          "Work out B − A.",
          "P = A + {{1/4}}(B − A).",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m2-q15",
        question: "A is (2, 3), B is (6, 5) and C is (k, −1). Angle ABC is a right angle. Find the value of k.",
        options: ["3", "18", "−6", "9"],
        answerIndex: 3,
        explanation:
          "Gradient of AB = {{2/4 = 1/2}}, so BC must have gradient −2. Gradient BC = {{(-1 - 5)/(k - 6) = -6/(k - 6)}}. Setting this equal to −2 gives k − 6 = 3, so k = 9. 3 comes from k − 6 = −3 (a sign slip). 18 uses {{-1/2}} for the perpendicular gradient. −6 makes BC *parallel* to AB (gradient {{1/2}}).",
        difficulty: "challenge",
        guideRef: "parallel-perpendicular",
        hints: [
          "The right angle is at B, so AB is perpendicular to BC.",
          "Find the gradient of AB, then the gradient BC must have.",
          "Write the gradient of BC in terms of k and solve.",
        ],
        strategy: "Introduce a variable",
      },
    ],
  },
  {
    id: "linear-graphs-m3",
    title: "MCQ Paper 3 — Exam style",
    questions: [
      {
        kind: "mcq",
        id: "linear-graphs-m3-q01",
        question: "The line L has equation {{2y = 6x - 8}}. Write down the gradient of L and the coordinates of the point where L crosses the y-axis.",
        options: [
          "Gradient 6, (0, −8)",
          "Gradient 3, (0, −8)",
          "Gradient 6, (0, −4)",
          "Gradient 3, (0, −4)",
        ],
        answerIndex: 3,
        explanation:
          "Divide every term by 2: {{y = 3x - 4}}. Gradient 3, y-intercept (0, −4). Gradient 6, (0, −8) reads the numbers before making y the subject. The two mixed options halve only one of the terms — dividing by 2 must apply to every term.",
        difficulty: "warmup",
        guideRef: "y-mx-c",
        hints: ["Get y on its own first: divide every term by 2."],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m3-q02",
        question: "On a planning map, two MRT stations are at A(2, 7) and B(10, 3). A new station is to be built exactly halfway between them. Find its coordinates.",
        options: ["(6, 5)", "(4, −2)", "(12, 10)", "(8, −4)"],
        answerIndex: 0,
        explanation:
          "Midpoint = {{((2 + 10)/2, (7 + 3)/2) = (6, 5)}}. (12, 10) adds but forgets to halve. (8, −4) is the change from A to B. (4, −2) is half of that change — the step to the midpoint, not the midpoint itself.",
        difficulty: "warmup",
        guideRef: "midpoint-distance",
        hints: ["Average the x-coordinates and average the y-coordinates."],
        strategy: "Use symmetry",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m3-q03",
        question: "A line with gradient 2 passes through (5, 4). Where does it cross the y-axis?",
        options: ["(0, 14)", "(0, 4)", "(0, −6)", "(3, 0)"],
        answerIndex: 2,
        explanation:
          "Substitute into y = 2x + c: 4 = 10 + c, so c = −6 and the line crosses at (0, −6). (0, 14) adds 10 instead of subtracting. (0, 4) assumes the given point is on the y-axis. (3, 0) is where the line crosses the **x**-axis.",
        difficulty: "warmup",
        guideRef: "point-gradient-form",
        hints: ["Write y = 2x + c and substitute x = 5, y = 4 to find c."],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m3-q04",
        question: "Which pair of lines is perpendicular?",
        options: [
          "{{y = 2x + 1}} and {{y = -2x + 3}}",
          "{{y = 2x + 1}} and {{y = -1/2 x + 3}}",
          "{{y = 2x + 1}} and {{y = 1/2 x - 4}}",
          "{{y = 3x}} and {{y = 3x - 1}}",
        ],
        answerIndex: 1,
        explanation:
          "Perpendicular gradients multiply to −1: {{2 * (-1/2) = -1}} ✓. 2 and −2 multiply to −4 (sign changed, but not flipped). 2 and {{1/2}} multiply to +1 (flipped, but no sign change). 3x and 3x − 1 are parallel.",
        difficulty: "warmup",
        guideRef: "parallel-perpendicular",
        hints: ["Multiply the two gradients in each pair. Which product is −1?"],
        strategy: "Eliminate options",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m3-q05",
        question: "The cost, C dollars, of a taxi journey of d km is given by a straight-line graph. A 5 km journey costs $7.20 and a 12 km journey costs $11.40. What does the gradient of the graph represent?",
        options: [
          "$4.20 — the fixed starting fare",
          "$0.60 — the cost of each extra kilometre",
          "$1.44 — the cost per kilometre",
          "1.67 — the number of kilometres per dollar",
        ],
        answerIndex: 1,
        explanation:
          "Gradient = {{(11.40 - 7.20)/(12 - 5) = 4.20/7 = 0.60}} dollars per km: each extra kilometre adds $0.60. $4.20 is the *intercept* (7.20 − 5 × 0.60), the fixed flag-down fare. $1.44 = 7.20 ÷ 5 is the average cost per km for one journey, which ignores the fixed charge. 1.67 is {{7/4.2}}, run over rise.",
        difficulty: "core",
        guideRef: "y-mx-c",
        hints: [
          "Gradient = change in cost ÷ change in distance. What are its units?",
          "Use the two journeys: (5, 7.20) and (12, 11.40).",
        ],
        strategy: "Estimate first",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m3-q06",
        question: "AB is a diameter of a circle. A is (−1, 2) and B is (7, 8). Work out the radius of the circle.",
        options: ["10", "7", "25", "5"],
        answerIndex: 3,
        explanation:
          "AB = {{sqrt(8^2 + 6^2) = sqrt(100) = 10}}, so the radius is half of that: 5. 10 is the diameter. 7 halves 8 + 6 (adding instead of Pythagoras). 25 is {{100/4}} — it is {{r^2}}, the root was never taken.",
        difficulty: "core",
        guideRef: "midpoint-distance",
        hints: [
          "Find the length AB first.",
          "AB is a diameter — how does the radius compare?",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m3-q07",
        question: "The line L has equation {{y = 1/2 x + 3}}. The point P on L has x-coordinate 4. Find the equation of the normal to L at P.",
        options: ["{{y = -2x + 13}}", "{{y = -2x + 3}}", "{{y = 2x - 3}}", "{{y = -1/2 x + 7}}"],
        answerIndex: 0,
        explanation:
          "At x = 4, y = 2 + 3 = 5, so P = (4, 5). The normal is perpendicular to L: gradient −2. {{y - 5 = -2(x - 4)}} gives {{y = -2x + 13}}. {{y = -2x + 3}} keeps L's intercept — it does not pass through P. {{y = 2x - 3}} forgets the negative. {{y = -1/2 x + 7}} changes the sign without taking the reciprocal.",
        difficulty: "core",
        guideRef: "parallel-perpendicular",
        hints: [
          "First find the y-coordinate of P.",
          "The normal is perpendicular to L. What is its gradient?",
          "Use {{y - 5 = m(x - 4)}}.",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m3-q08",
        question: "Find the coordinates of the point of intersection of the lines {{2x + 3y = 12}} and {{x - y = 1}}.",
        options: ["(2, 3)", "(6, 0)", "(3, 2)", "(3.2, 2.2)"],
        answerIndex: 2,
        explanation:
          "From the second equation x = y + 1. Substitute: {{2(y + 1) + 3y = 12}}, so 5y = 10, y = 2 and x = 3. Check: 6 + 6 = 12 ✓, 3 − 2 = 1 ✓. (2, 3) swaps the coordinates. (6, 0) is only on the first line (its x-intercept). (3.2, 2.2) expands 2(y + 1) as 2y + 1.",
        difficulty: "core",
        guideRef: "intersections",
        hints: [
          "Make x the subject of the simpler equation.",
          "Substitute into 2x + 3y = 12 and expand the bracket carefully.",
        ],
        strategy: "Make it simpler",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m3-q09",
        question: "A line passes through P(−2, 3) and Q(4, 7). Find its equation in the form {{ax + by = c}}, where a, b and c are integers.",
        options: ["{{3x - 2y = -12}}", "{{2x - 3y = -5}}", "{{2x + 3y = 5}}", "{{2x - 3y = -13}}"],
        answerIndex: 3,
        explanation:
          "Gradient {{(7 - 3)/(4 - (-2)) = 4/6 = 2/3}}. {{y - 3 = 2/3(x + 2)}}; multiply by 3: {{3y - 9 = 2x + 4}}, so {{2x - 3y = -13}}. Check Q: 8 − 21 = −13 ✓. {{3x - 2y = -12}} uses gradient {{3/2}}. {{2x - 3y = -5}} uses x − 2 instead of x + 2. {{2x + 3y = 5}} has gradient {{-2/3}}.",
        difficulty: "core",
        guideRef: "point-gradient-form",
        hints: [
          "Find the gradient — watch 4 − (−2).",
          "Use {{y - y_1 = m(x - x_1)}}, then multiply through by 3 to clear the fraction.",
          "Check your answer with the other point.",
        ],
        strategy: "Check by substituting",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m3-q10",
        question: "The diagram shows triangle ABC with A(1, 2), B(4, 6) and C(8, 3). Which statement is correct?",
        diagram: `<svg viewBox="0 0 318 258" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Triangle ABC drawn on a grid with A at (1, 2), B at (4, 6) and C at (8, 3)"><rect x="0" y="0" width="318" height="258" fill="#ffffff"/><line x1="24" y1="234" x2="24" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="54" y1="234" x2="54" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="84" y1="234" x2="84" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="114" y1="234" x2="114" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="144" y1="234" x2="144" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="174" y1="234" x2="174" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="204" y1="234" x2="204" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="234" y1="234" x2="234" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="264" y1="234" x2="264" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="294" y1="234" x2="294" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="234" x2="294" y2="234" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="204" x2="294" y2="204" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="174" x2="294" y2="174" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="144" x2="294" y2="144" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="114" x2="294" y2="114" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="84" x2="294" y2="84" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="54" x2="294" y2="54" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="24" x2="294" y2="24" stroke="#e2e8f0" stroke-width="1"/><polygon points="54,174 144,54 264,144" fill="#c7d2fe" stroke="none" opacity="0.8"/><line x1="24" y1="234" x2="302" y2="234" stroke="#334155" stroke-width="1.5"/><line x1="24" y1="234" x2="24" y2="16" stroke="#334155" stroke-width="1.5"/><text x="304" y="238" font-size="13" font-style="italic" font-family="sans-serif" fill="#334155">x</text><text x="29" y="14" font-size="13" font-style="italic" font-family="sans-serif" fill="#334155">y</text><text x="54" y="248" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">1</text><text x="84" y="248" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">2</text><text x="114" y="248" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">3</text><text x="144" y="248" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">4</text><text x="174" y="248" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">5</text><text x="204" y="248" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">6</text><text x="234" y="248" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">7</text><text x="264" y="248" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">8</text><text x="294" y="248" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">9</text><text x="19" y="208" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">1</text><text x="19" y="178" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">2</text><text x="19" y="148" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">3</text><text x="19" y="118" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">4</text><text x="19" y="88" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">5</text><text x="19" y="58" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">6</text><text x="19" y="28" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">7</text><text x="19" y="248" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155">O</text><line x1="54" y1="174" x2="144" y2="54" stroke="#1f2937" stroke-width="2"/><line x1="144" y1="54" x2="264" y2="144" stroke="#1f2937" stroke-width="2"/><line x1="264" y1="144" x2="54" y2="174" stroke="#1f2937" stroke-width="2"/><circle cx="54" cy="174" r="3.5" fill="#1f2937"/><text x="38" y="170" font-size="13" font-weight="bold" font-family="sans-serif" fill="#1f2937" stroke="#ffffff" stroke-width="3" paint-order="stroke">A</text><circle cx="144" cy="54" r="3.5" fill="#1f2937"/><text x="140" y="46" font-size="13" font-weight="bold" font-family="sans-serif" fill="#1f2937" stroke="#ffffff" stroke-width="3" paint-order="stroke">B</text><circle cx="264" cy="144" r="3.5" fill="#1f2937"/><text x="271" y="148" font-size="13" font-weight="bold" font-family="sans-serif" fill="#1f2937" stroke="#ffffff" stroke-width="3" paint-order="stroke">C</text></svg>`,
        options: [
          "ABC is equilateral",
          "ABC is right-angled and isosceles, with the right angle at B",
          "ABC is right-angled, with the right angle at A",
          "ABC is isosceles but not right-angled",
        ],
        answerIndex: 1,
        explanation:
          "AB = {{sqrt(3^2 + 4^2) = 5}}, BC = {{sqrt(4^2 + 3^2) = 5}}, AC = {{sqrt(7^2 + 1^2) = sqrt(50)}}. Two equal sides, and {{5^2 + 5^2 = 50 = AC^2}}, so by the converse of Pythagoras the angle opposite AC — at B — is 90°. (Also: gradients {{4/3}} and {{-3/4}} multiply to −1.) It is not equilateral because AC ≠ 5. \"Isosceles but not right-angled\" misses the Pythagoras check. The right angle is never at A: the longest side AC touches A.",
        difficulty: "core",
        guideRef: "midpoint-distance",
        hints: [
          "Work out the three side lengths.",
          "Two are equal. Do the squares of the two shorter sides add up to the square of the longest?",
          "The right angle is opposite the longest side.",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m3-q11",
        question: "A is (−2, 1) and B is (4, 5). Find the equation of the perpendicular bisector of AB.",
        options: ["{{2x + 3y = 11}}", "{{3x - 2y = -3}}", "{{3x + 2y = 9}}", "{{3x + 2y = -4}}"],
        answerIndex: 2,
        explanation:
          "Midpoint (1, 3). Gradient AB = {{4/6 = 2/3}}, so the bisector has gradient {{-3/2}}. {{y - 3 = -3/2(x - 1)}}; times 2: {{2y - 6 = -3x + 3}}, so {{3x + 2y = 9}}. Check (1, 3): 3 + 6 = 9 ✓. {{2x + 3y = 11}} uses gradient {{-2/3}} (sign changed, not flipped). {{3x - 2y = -3}} uses {{3/2}} (flipped, sign not changed). {{3x + 2y = -4}} goes through A instead of the midpoint.",
        difficulty: "core",
        guideRef: "parallel-perpendicular",
        hints: [
          "You need a point (the midpoint) and a gradient (perpendicular to AB).",
          "Midpoint (1, 3); gradient of AB is {{2/3}}.",
          "Use gradient {{-3/2}} through (1, 3), then clear the fraction.",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m3-q12",
        question: "A is (3, −6) and B is (12, 0). P is the point on AB such that AP : PB = 1 : 2. Find the coordinates of P.",
        options: ["(6, −4)", "(7.5, −3)", "(9, −2)", "(4, 0)"],
        answerIndex: 0,
        explanation:
          "P is {{1/3}} of the way from A to B. {{B - A = (9, 6)}}, so {{P = (3 + 3, -6 + 2) = (6, -4)}}. (7.5, −3) is the midpoint. (9, −2) is {{2/3}} of the way — measured from the wrong end. (4, 0) is {{1/3}} of B's coordinates, forgetting to start at A.",
        difficulty: "core",
        guideRef: "dividing-a-line",
        hints: [
          "1 : 2 splits AB into 3 equal parts. What fraction of the way along is P?",
          "Add {{1/3}} of the step (B − A) on to A.",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m3-q13",
        question: "The diagram shows the lines {{y = 2x}} and {{x + 2y = 10}}. Work out the area of the shaded triangle formed by the two lines and the x-axis.",
        diagram: `<svg viewBox="0 0 360 230" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Grid showing the lines y = 2x and x + 2y = 10 with the triangle they make with the x-axis shaded"><rect x="0" y="0" width="360" height="230" fill="#ffffff"/><line x1="24" y1="206" x2="24" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="50" y1="206" x2="50" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="76" y1="206" x2="76" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="102" y1="206" x2="102" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="128" y1="206" x2="128" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="154" y1="206" x2="154" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="180" y1="206" x2="180" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="206" y1="206" x2="206" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="232" y1="206" x2="232" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="258" y1="206" x2="258" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="284" y1="206" x2="284" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="310" y1="206" x2="310" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="336" y1="206" x2="336" y2="24" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="206" x2="336" y2="206" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="180" x2="336" y2="180" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="154" x2="336" y2="154" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="128" x2="336" y2="128" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="102" x2="336" y2="102" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="76" x2="336" y2="76" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="50" x2="336" y2="50" stroke="#e2e8f0" stroke-width="1"/><line x1="24" y1="24" x2="336" y2="24" stroke="#e2e8f0" stroke-width="1"/><polygon points="50,180 310,180 102,76" fill="#bbf7d0" stroke="none" opacity="0.8"/><line x1="24" y1="180" x2="344" y2="180" stroke="#334155" stroke-width="1.5"/><line x1="50" y1="206" x2="50" y2="16" stroke="#334155" stroke-width="1.5"/><text x="346" y="184" font-size="13" font-style="italic" font-family="sans-serif" fill="#334155">x</text><text x="55" y="14" font-size="13" font-style="italic" font-family="sans-serif" fill="#334155">y</text><text x="24" y="194" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−1</text><text x="76" y="194" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">1</text><text x="102" y="194" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">2</text><text x="128" y="194" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">3</text><text x="154" y="194" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">4</text><text x="180" y="194" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">5</text><text x="206" y="194" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">6</text><text x="232" y="194" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">7</text><text x="258" y="194" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">8</text><text x="284" y="194" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">9</text><text x="310" y="194" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">10</text><text x="336" y="194" font-size="11" text-anchor="middle" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">11</text><text x="45" y="210" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">−1</text><text x="45" y="158" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">1</text><text x="45" y="132" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">2</text><text x="45" y="106" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">3</text><text x="45" y="80" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">4</text><text x="45" y="54" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">5</text><text x="45" y="28" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155" stroke="#ffffff" stroke-width="3" paint-order="stroke">6</text><text x="45" y="194" font-size="11" text-anchor="end" font-family="sans-serif" fill="#334155">O</text><line x1="37" y1="206" x2="128" y2="24" stroke="#1d4ed8" stroke-width="2"/><text x="130.6" y="37" font-size="12" font-family="sans-serif" fill="#1d4ed8" stroke="#ffffff" stroke-width="3" paint-order="stroke">y = 2x</text><line x1="24" y1="37" x2="336" y2="193" stroke="#b91c1c" stroke-width="2"/><text x="206" y="102" font-size="12" font-family="sans-serif" fill="#b91c1c" stroke="#ffffff" stroke-width="3" paint-order="stroke">x + 2y = 10</text></svg>`,
        options: ["40", "20", "4", "10"],
        answerIndex: 1,
        explanation:
          "The lines meet where {{x + 2(2x) = 10}}: x = 2, y = 4. y = 2x meets the x-axis at O; x + 2y = 10 meets it at (10, 0). Base 10, height 4: area = {{1/2 * 10 * 4 = 20}}. 40 forgets the {{1/2}}. 4 uses the x-coordinate 2 as the base. 10 uses the x-coordinate 2 as the height.",
        difficulty: "challenge",
        guideRef: "intersections",
        hints: [
          "Find the three vertices of the triangle.",
          "Solve the equations simultaneously for the top vertex; set y = 0 for the x-intercepts.",
          "The height is the y-coordinate of the top vertex.",
        ],
        strategy: "Draw a diagram",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m3-q14",
        question: "A is (1, 3). The point P(5, 1) lies on the line segment AB with AP : PB = 2 : 3. Find the coordinates of B.",
        options: ["(9, −1)", "(7, 0)", "(10, −5)", "(11, −2)"],
        answerIndex: 3,
        explanation:
          "AP is {{2/5}} of AB. {{P - A = (4, -2)}} covers 2 parts, so one part is (2, −1) and AB is 5 parts: (10, −5). So B = A + (10, −5) = (11, −2). (9, −1) treats P as the midpoint. (7, 0) treats AP as {{2/3}} of AB. (10, −5) is the step from A to B, not the point B.",
        difficulty: "challenge",
        guideRef: "dividing-a-line",
        hints: [
          "AP : PB = 2 : 3. How many parts make up the whole of AB?",
          "The step from A to P is 2 parts. Find one part.",
          "AB is 5 parts. Add that step on to A.",
        ],
        strategy: "Work backwards",
      },
      {
        kind: "mcq",
        id: "linear-graphs-m3-q15",
        question: "The lines {{(k + 1)x + 2y = 5}} and {{3x - y = 4}} are perpendicular. Find the value of k.",
        options: ["−7", "{{-5/3}}", "{{-1/3}}", "{{-2/3}}"],
        answerIndex: 2,
        explanation:
          "Second line: y = 3x − 4, gradient 3. First line: {{y = -(k + 1)/2 x + 5/2}}, gradient {{-(k + 1)/2}}. Perpendicular: {{3 * (-(k + 1)/2) = -1}}, so {{k + 1 = 2/3}} and {{k = -1/3}}. −7 makes the lines *parallel* ({{-(k + 1)/2 = 3}}). {{-5/3}} loses the minus sign in the first gradient. {{-2/3}} forgets to divide by 2 when making y the subject.",
        difficulty: "challenge",
        guideRef: "parallel-perpendicular",
        hints: [
          "Write each line in the form y = mx + c; the first gradient will involve k.",
          "The first gradient is {{-(k + 1)/2}}.",
          "Set the product of the gradients equal to −1 and solve for k.",
        ],
        strategy: "Introduce a variable",
      },
    ],
  },
];
