import type { TopicPractice } from "../../types.ts";

export const practice: TopicPractice = {
  // =========================================================================
  // Quick-check quiz — 10 questions (3 mcq, 7 short) across the main sections
  // =========================================================================
  quiz: [
    {
      kind: "short",
      id: "linear-graphs-quiz-q01",
      question: "Work out the gradient of the straight line that passes through (2, 5) and (6, 17).",
      answer: { type: "number", value: 3 },
      solution: [
        "Gradient = {{(change in y)/(change in x)}} = {{(17 - 5)/(6 - 2)}}.",
        "= {{12/4}} = 3.",
      ],
      traps: [
        { spec: { type: "fraction", n: 1, d: 3 }, feedback: "That's run over rise. Gradient is the change in **y** divided by the change in **x**: {{12/4}}, not {{4/12}}." },
      ],
      commonError: "Dividing the change in x by the change in y.",
      difficulty: "warmup",
      guideRef: "y-mx-c",
      hints: ["Gradient = rise ÷ run. How far up, and how far across?", "Rise = 17 − 5, run = 6 − 2."],
      strategy: "Draw a diagram",
    },
    {
      kind: "mcq",
      id: "linear-graphs-quiz-q02",
      question: "A straight line has equation 3x + 2y = 12. Which gives its gradient and y-intercept?",
      options: [
        "gradient {{-3/2}}, y-intercept 6",
        "gradient 3, y-intercept 12",
        "gradient {{-2/3}}, y-intercept 4",
        "gradient {{3/2}}, y-intercept 6",
      ],
      answerIndex: 0,
      explanation:
        "Make y the subject: 2y = −3x + 12, so {{y = -3/2 x + 6}}. The gradient is {{-3/2}} and the line crosses the y-axis at 6. \"Gradient 3, intercept 12\" reads the numbers straight off without rearranging; {{-2/3}} with 4 divides by the wrong coefficient (that's the x-intercept, 4, mixed up with the y-intercept); {{3/2}} forgets that moving 3x across makes it negative.",
      difficulty: "warmup",
      guideRef: "y-mx-c",
      hints: ["m and c can only be read off once the equation is in the form y = mx + c.", "Subtract 3x from both sides, then divide everything by 2."],
      strategy: "Make it simpler",
    },
    {
      kind: "short",
      id: "linear-graphs-quiz-q03",
      question: "Find the equation of the line with gradient −2 that passes through the point (3, 1). Give your answer in the form y = mx + c.",
      answer: { type: "equation", eq: "y=-2x+7", display: "y = −2x + 7" },
      solution: [
        "Use y − y₁ = m(x − x₁) with m = −2 and (x₁, y₁) = (3, 1).",
        "y − 1 = −2(x − 3) = −2x + 6.",
        "y = −2x + 7.",
        "Check: when x = 3, y = −6 + 7 = 1. ✓",
      ],
      traps: [
        { spec: { type: "equation", eq: "y=-2x-5" }, feedback: "Sign slip in the bracket: −2(x − 3) = −2x **+ 6**. Check your line actually passes through (3, 1)." },
      ],
      commonError: "Expanding −2(x − 3) as −2x − 6.",
      difficulty: "core",
      guideRef: "point-gradient-form",
      hints: ["You know a point and the gradient — which form of a line uses exactly those?", "y − 1 = −2(x − 3). Expand carefully, then add 1."],
      strategy: "Check by substituting",
    },
    {
      kind: "short",
      id: "linear-graphs-quiz-q04",
      question: "A is the point (−3, 4) and B is the point (5, −2). Find the coordinates of the midpoint of AB. Give your answer as (x, y).",
      answer: { type: "list", values: [1, 1], ordered: true, display: "(1, 1)" },
      solution: [
        "Midpoint = (average of the x's, average of the y's).",
        "x: {{(-3 + 5)/2 = 1}}. y: {{(4 + (-2))/2 = 1}}.",
        "Midpoint (1, 1).",
      ],
      traps: [
        { spec: { type: "list", values: [4, -3], ordered: true }, feedback: "You've halved the *differences*. The midpoint uses the *averages*: add the coordinates, then halve." },
      ],
      commonError: "Subtracting the coordinates instead of adding them.",
      difficulty: "warmup",
      guideRef: "midpoint-distance",
      hints: ["The midpoint is halfway — average the x-coordinates, then the y-coordinates."],
      strategy: "Use symmetry",
    },
    {
      kind: "short",
      id: "linear-graphs-quiz-q05",
      question: "A is the point (1, −2) and B is the point (7, 6). Work out the length of AB.",
      answer: { type: "number", value: 10 },
      solution: [
        "Across: 7 − 1 = 6. Up: 6 − (−2) = 8.",
        "AB is the hypotenuse of a right-angled triangle: {{AB^2 = 6^2 + 8^2 = 100}}.",
        "AB = 10.",
      ],
      traps: [
        { spec: { type: "number", value: 14 }, feedback: "6 + 8 is the route along two sides of the triangle. The straight line is the hypotenuse: use Pythagoras." },
        { spec: { type: "expression", expr: "sqrt(40)" }, feedback: "Careful with the double negative: 6 − (−2) = 8, not 4." },
      ],
      commonError: "Writing 6 − (−2) as 4.",
      difficulty: "core",
      guideRef: "midpoint-distance",
      hints: ["Sketch A and B. Can you see a right-angled triangle with AB as its longest side?", "The two short sides are the change in x and the change in y.", "Then Pythagoras: {{6^2 + 8^2}}."],
      strategy: "Draw a diagram",
    },
    {
      kind: "mcq",
      id: "linear-graphs-quiz-q06",
      question: "What is the gradient of a line perpendicular to y = 4x − 1?",
      options: ["−4", "4", "{{-1/4}}", "{{1/4}}"],
      answerIndex: 2,
      explanation:
        "Perpendicular gradients multiply to −1, so m = {{-1/4}} (the negative reciprocal of 4). 4 is the gradient of a *parallel* line; −4 only changes the sign; {{1/4}} only flips it — you need both.",
      difficulty: "core",
      guideRef: "parallel-perpendicular",
      hints: ["For perpendicular lines, {{m_1 * m_2 = -1}}.", "4 × ? = −1."],
      strategy: "Use the inverse",
    },
    {
      kind: "short",
      id: "linear-graphs-quiz-q07",
      question: "Find the equation of the line parallel to y = 3x + 2 that passes through (2, −1). Give your answer in the form y = mx + c.",
      answer: { type: "equation", eq: "y=3x-7", display: "y = 3x − 7" },
      solution: [
        "Parallel lines have equal gradients, so m = 3.",
        "y = 3x + c through (2, −1): −1 = 6 + c, so c = −7.",
        "y = 3x − 7.",
      ],
      traps: [
        { spec: { type: "equation", eq: "y=3x+2" }, feedback: "That's the original line — it doesn't pass through (2, −1). Keep m = 3 but find a new c." },
        { spec: { type: "equation", eq: "y=3x+5" }, feedback: "Check the arithmetic for c: −1 = 3(2) + c gives c = −1 − 6 = −7." },
      ],
      commonError: "Reusing the old intercept, or getting the sign of c wrong.",
      difficulty: "core",
      guideRef: "parallel-perpendicular",
      hints: ["What do parallel lines have in common?", "m = 3. Substitute x = 2, y = −1 into y = 3x + c to find c."],
      strategy: "Check by substituting",
    },
    {
      kind: "short",
      id: "linear-graphs-quiz-q08",
      question: "Find the coordinates of the point where the lines y = 2x − 1 and x + y = 8 intersect. Give your answer as (x, y).",
      answer: { type: "list", values: [3, 5], ordered: true, display: "(3, 5)" },
      solution: [
        "At the intersection both equations are true, so substitute y = 2x − 1 into x + y = 8.",
        "x + 2x − 1 = 8, so 3x = 9 and x = 3.",
        "y = 2(3) − 1 = 5. Check: 3 + 5 = 8. ✓",
      ],
      traps: [
        { spec: { type: "list", values: [5, 3], ordered: true }, feedback: "Right numbers, wrong order — coordinates go (x, y)." },
      ],
      commonError: "Solving for x and forgetting to find y.",
      difficulty: "core",
      guideRef: "intersections",
      hints: ["The intersection is the one point that lies on both lines — it solves both equations at once.", "Substitute y = 2x − 1 into the second equation."],
      strategy: "Eliminate a variable",
    },
    {
      kind: "mcq",
      id: "linear-graphs-quiz-q09",
      question: "A line passes through (1, 2) and (4, 11). Which is its equation, written in the form ax + by + c = 0?",
      options: ["3x − y + 1 = 0", "x − 3y + 5 = 0", "3x + y − 5 = 0", "3x − y − 1 = 0"],
      answerIndex: 3,
      explanation:
        "Gradient = {{(11 - 2)/(4 - 1) = 3}}. y − 2 = 3(x − 1) gives y = 3x − 1, i.e. 3x − y − 1 = 0. Check (4, 11): 12 − 11 − 1 = 0 ✓. 3x − y + 1 = 0 has the wrong sign on c (it misses both points); x − 3y + 5 = 0 uses the gradient upside down ({{1/3}}); 3x + y − 5 = 0 has gradient −3.",
      difficulty: "core",
      guideRef: "point-gradient-form",
      hints: ["First find the gradient from the two points.", "Then y − 2 = 3(x − 1). Rearrange so everything is on one side.", "Quick check: substitute both points into each option."],
      strategy: "Check by substituting",
    },
    {
      kind: "short",
      id: "linear-graphs-quiz-q10",
      question: "Find the equation of the line that is perpendicular to y = 2x + 3 and passes through (4, 1). Give your answer in the form y = mx + c.",
      answer: { type: "equation", eq: "y=-x/2+3", display: "{{y = -1/2 x + 3}}" },
      solution: [
        "Perpendicular gradient: {{-1/2}} (since {{2 * (-1/2) = -1}}).",
        "{{y - 1 = -1/2 (x - 4)}}, so {{y - 1 = -1/2 x + 2}}.",
        "{{y = -1/2 x + 3}}. Check: x = 4 gives −2 + 3 = 1. ✓",
      ],
      traps: [
        { spec: { type: "equation", eq: "y=2x-7" }, feedback: "That line is *parallel* to y = 2x + 3. A perpendicular line needs the negative reciprocal gradient, {{-1/2}}." },
        { spec: { type: "equation", eq: "y=-2x+9" }, feedback: "You changed the sign but didn't flip the fraction. Perpendicular gradient = {{-1/m}} = {{-1/2}}." },
      ],
      commonError: "Using −2 (sign change only) instead of {{-1/2}}.",
      difficulty: "core",
      guideRef: "parallel-perpendicular",
      hints: ["What is the gradient of a line perpendicular to one with gradient 2?", "{{m = -1/2}}. Now use y − y₁ = m(x − x₁) with (4, 1)."],
      strategy: "Use the inverse",
    },
  ],

  // =========================================================================
  // Practice papers — 15 questions each, 3 written per paper
  // =========================================================================
  papers: [
    {
      id: "linear-graphs-p1",
      title: "Practice Paper 1",
      questions: [
        {
          kind: "short",
          id: "linear-graphs-p1-q01",
          question: "Write down the gradient and the y-intercept of the line y = 5 − 2x. Give the gradient first.",
          answer: { type: "list", values: [-2, 5], ordered: true, display: "gradient −2, y-intercept 5" },
          solution: ["Reorder as y = −2x + 5.", "m = −2 (the coefficient of x) and c = 5."],
          traps: [
            { spec: { type: "list", values: [5, -2], ordered: true }, feedback: "m is the number multiplying x, not the first number you see. Rewrite as y = −2x + 5." },
            { spec: { type: "list", values: [2, 5], ordered: true }, feedback: "The gradient carries the sign in front of it: −2x means m = −2." },
          ],
          commonError: "Taking the first number written as the gradient.",
          difficulty: "warmup",
          guideRef: "y-mx-c",
          hints: ["Rewrite it so the x term comes first: y = …x + …"],
        },
        {
          kind: "short",
          id: "linear-graphs-p1-q02",
          question: "Work out the gradient of the line through (−1, 7) and (3, −5).",
          answer: { type: "number", value: -3 },
          solution: ["Gradient = {{(-5 - 7)/(3 - (-1))}} = {{-12/4}} = −3.", "Sense check: the line goes down from left to right, so the gradient is negative. ✓"],
          traps: [{ spec: { type: "number", value: 3 }, feedback: "As x increases from −1 to 3, y *falls* from 7 to −5, so the gradient must be negative." }],
          commonError: "Losing the minus sign.",
          difficulty: "warmup",
          guideRef: "y-mx-c",
          hints: ["Change in y ÷ change in x — keep the points in the same order top and bottom.", "{{(-5 - 7)/(3 - (-1))}}."],
          strategy: "Estimate first",
        },
        {
          kind: "short",
          id: "linear-graphs-p1-q03",
          question: "Find the midpoint of the line segment joining (2, 9) and (8, −3). Give your answer as (x, y).",
          answer: { type: "list", values: [5, 3], ordered: true, display: "(5, 3)" },
          solution: ["x: {{(2 + 8)/2 = 5}}.", "y: {{(9 + (-3))/2 = 3}}.", "Midpoint (5, 3)."],
          traps: [{ spec: { type: "list", values: [5, 6], ordered: true }, feedback: "9 + (−3) = 6, and then halve it: 3." }],
          commonError: "Forgetting to halve the y total.",
          difficulty: "warmup",
          guideRef: "midpoint-distance",
          hints: ["Average the x-coordinates; average the y-coordinates."],
        },
        {
          kind: "short",
          id: "linear-graphs-p1-q04",
          question: "P is the point (−1, 3) and Q is the point (4, −9). Work out the length of PQ.",
          answer: { type: "number", value: 13 },
          solution: ["Across: 4 − (−1) = 5. Down: −9 − 3 = −12.", "{{PQ^2 = 5^2 + 12^2 = 25 + 144 = 169}}.", "PQ = 13."],
          traps: [{ spec: { type: "number", value: 17 }, feedback: "5 + 12 is not the straight-line distance. Square, add, then square root." }],
          commonError: "Adding the differences instead of using Pythagoras.",
          difficulty: "warmup",
          guideRef: "midpoint-distance",
          hints: ["Find the horizontal and vertical distances, then use Pythagoras."],
          strategy: "Draw a diagram",
        },
        {
          kind: "short",
          id: "linear-graphs-p1-q05",
          question: "M(4, 1) is the midpoint of the line segment AB. A is the point (−2, 5). Find the coordinates of B. Give your answer as (x, y).",
          answer: { type: "list", values: [10, -3], ordered: true, display: "(10, −3)" },
          solution: [
            "From A to M: x goes up by 6, y goes down by 4.",
            "M is halfway, so do the same again from M to B: x = 4 + 6 = 10, y = 1 − 4 = −3.",
            "B = (10, −3). Check: midpoint of (−2, 5) and (10, −3) is (4, 1). ✓",
          ],
          solutions: [
            { label: "Use the formula backwards", steps: ["{{(-2 + x)/2 = 4}} gives x = 10.", "{{(5 + y)/2 = 1}} gives y = −3."] },
          ],
          traps: [{ spec: { type: "list", values: [1, 3], ordered: true }, feedback: "That's the midpoint of A and M. M is the *middle*, so B is as far beyond M as A is before it." }],
          commonError: "Averaging A and M instead of stepping past M.",
          difficulty: "core",
          guideRef: "midpoint-distance",
          hints: ["How do you get from A to M? Write it as a step across and a step up/down.", "M is halfway — so B is one more identical step from M.", "Step: +6 in x, −4 in y."],
          strategy: "Work backwards",
        },
        {
          kind: "short",
          id: "linear-graphs-p1-q06",
          question: "Find the equation of the straight line through (−2, 1) and (4, 4). Give your answer in the form y = mx + c.",
          answer: { type: "equation", eq: "y=x/2+2", display: "{{y = 1/2 x + 2}}" },
          solution: [
            "m = {{(4 - 1)/(4 - (-2)) = 3/6 = 1/2}}.",
            "{{y = 1/2 x + c}} through (4, 4): 4 = 2 + c, so c = 2.",
            "{{y = 1/2 x + 2}}. Check (−2, 1): −1 + 2 = 1. ✓",
          ],
          traps: [{ spec: { type: "equation", eq: "y=2x-4" }, feedback: "Your gradient is upside down: it's {{3/6}}, change in y over change in x." }],
          commonError: "Gradient upside down (run over rise).",
          difficulty: "core",
          guideRef: "y-mx-c",
          hints: ["Two steps: find m, then find c.", "m = {{3/6}}. Substitute one point into {{y = 1/2 x + c}}."],
          strategy: "Check by substituting",
        },
        {
          kind: "short",
          id: "linear-graphs-p1-q07",
          question:
            "The line L passes through (5, −2) and has gradient {{-3/4}}. Find an equation of L in the form ax + by + c = 0, where a, b and c are integers and a > 0.",
          answer: {
            type: "text",
            accept: ["3x+4y-7=0", "4y+3x-7=0", "3x+4y=7", "4y+3x=7", "0=3x+4y-7", "7=3x+4y", "3x-7+4y=0"],
            display: "3x + 4y − 7 = 0",
          },
          solution: [
            "{{y - (-2) = -3/4 (x - 5)}}, i.e. {{y + 2 = -3/4 (x - 5)}}.",
            "Multiply by 4 to clear the fraction: 4y + 8 = −3(x − 5) = −3x + 15.",
            "Bring everything to one side: 3x + 4y + 8 − 15 = 0, so 3x + 4y − 7 = 0.",
            "Check (5, −2): 15 − 8 − 7 = 0. ✓",
          ],
          commonError: "Writing y − 2 instead of y + 2 for the point (5, −2).",
          difficulty: "core",
          guideRef: "point-gradient-form",
          hints: [
            "Start with y − y₁ = m(x − x₁). What is y − (−2)?",
            "Multiply both sides by 4 to get rid of the fraction.",
            "Collect all terms on the side that makes the x coefficient positive.",
          ],
          strategy: "Make it simpler",
        },
        {
          kind: "short",
          id: "linear-graphs-p1-q08",
          question: "Work out the exact distance between (1, 2) and (5, 10). Give your answer as a surd in its simplest form.",
          answer: { type: "expression", expr: "4sqrt(5)", form: "surd", display: "{{4 sqrt(5)}}" },
          solution: ["Across 4, up 8.", "{{d^2 = 4^2 + 8^2 = 80}}, so {{d = sqrt(80)}}.", "{{sqrt(80) = sqrt(16 * 5) = 4 sqrt(5)}}."],
          traps: [{ spec: { type: "number", value: 12 }, feedback: "4 + 8 is the 'staircase' route. Use Pythagoras for the straight line." }],
          commonError: "Leaving the answer as √80, or giving a decimal.",
          difficulty: "core",
          guideRef: "midpoint-distance",
          hints: ["Pythagoras first: what is {{d^2}}?", "{{d = sqrt(80)}}. What is the largest square number that divides 80?"],
          strategy: "Make it simpler",
        },
        {
          kind: "written",
          id: "linear-graphs-p1-q09",
          question: "Show that the lines 2y = 3x + 4 and 3y + 2x = 9 are perpendicular.",
          marks: 3,
          modelAnswer:
            "First line: {{y = 3/2 x + 2}}, so {{m_1 = 3/2}}.\n\nSecond line: 3y = −2x + 9, so {{y = -2/3 x + 3}} and {{m_2 = -2/3}}.\n\n{{m_1 * m_2 = 3/2 * (-2/3) = -1}}, so the lines are perpendicular.",
          markScheme: [
            { point: "Gradient of the first line is 3/2", keywords: ["3/2", "1.5", "y = 3/2x + 2", "y=1.5x+2"] },
            { point: "Gradient of the second line is −2/3", keywords: ["-2/3", "−2/3", "-0.666", "y = -2/3x + 3"] },
            { point: "Shows the product of the gradients is −1 (or one is the negative reciprocal of the other) and concludes", keywords: ["-1", "−1", "negative reciprocal", "product", "perpendicular"] },
          ],
          commonError: "Reading the gradient as 3 and −2 without first making y the subject.",
          difficulty: "core",
          guideRef: "parallel-perpendicular",
          hints: ["Rearrange each equation into y = mx + c.", "Two lines are perpendicular exactly when {{m_1 * m_2 = -1}}."],
          strategy: "Make it simpler",
        },
        {
          kind: "short",
          id: "linear-graphs-p1-q10",
          question:
            "Find the equation of the line that passes through (6, 1) and is perpendicular to the line 3x − y = 4. Give your answer in the form y = mx + c.",
          answer: { type: "equation", eq: "y=-x/3+3", display: "{{y = -1/3 x + 3}}" },
          solution: [
            "3x − y = 4 rearranges to y = 3x − 4, gradient 3.",
            "Perpendicular gradient: {{-1/3}}.",
            "{{y - 1 = -1/3 (x - 6) = -1/3 x + 2}}, so {{y = -1/3 x + 3}}.",
          ],
          traps: [
            { spec: { type: "equation", eq: "y=x/3-1" }, feedback: "The given line has gradient +3 (y = 3x − 4), so the perpendicular gradient is {{-1/3}}, not {{+1/3}}." },
            { spec: { type: "equation", eq: "y=3x-17" }, feedback: "That's parallel to 3x − y = 4. You need the negative reciprocal gradient." },
          ],
          commonError: "Reading the gradient of 3x − y = 4 as −3.",
          difficulty: "core",
          guideRef: "parallel-perpendicular",
          hints: ["Find the gradient of 3x − y = 4 by making y the subject.", "Gradient 3, so the perpendicular gradient is …?", "Now use the point (6, 1)."],
          strategy: "Make it simpler",
        },
        {
          kind: "short",
          id: "linear-graphs-p1-q11",
          question: "The lines 3x + 2y = 7 and y = x − 4 meet at the point P. Find the coordinates of P. Give your answer as (x, y).",
          answer: { type: "list", values: [3, -1], ordered: true, display: "(3, −1)" },
          solution: [
            "Substitute y = x − 4: 3x + 2(x − 4) = 7.",
            "5x − 8 = 7, so x = 3.",
            "y = 3 − 4 = −1. Check: 9 − 2 = 7. ✓",
          ],
          traps: [{ spec: { type: "list", values: [-1, 3], ordered: true }, feedback: "Coordinates are written (x, y) — x first." }],
          commonError: "Writing 2(x − 4) as 2x − 4.",
          difficulty: "core",
          guideRef: "intersections",
          hints: ["P is on both lines, so its coordinates satisfy both equations.", "Replace y in the first equation with x − 4."],
          strategy: "Eliminate a variable",
        },
        {
          kind: "written",
          id: "linear-graphs-p1-q12",
          question: "A is the point (1, 3), B is (4, 9) and C is (−2, −3). Show that A, B and C lie on the same straight line.",
          marks: 3,
          modelAnswer:
            "Gradient AB = {{(9 - 3)/(4 - 1) = 6/3 = 2}}.\n\nGradient AC = {{(-3 - 3)/(-2 - 1) = (-6)/(-3) = 2}}.\n\nAB and AC have the same gradient and share the point A, so they are parts of the same line: A, B and C are collinear.",
          markScheme: [
            { point: "Gradient of AB (or BC) = 2", keywords: ["ab", "6/3", "2"] },
            { point: "Gradient of AC (or BC) = 2", keywords: ["ac", "bc", "-6/-3", "12/6", "2"] },
            { point: "States equal gradients AND a common point, so collinear", keywords: ["same gradient", "equal gradient", "common point", "share", "point a", "same line", "collinear"] },
          ],
          solutions: [
            { label: "Find the line, then test the third point", steps: ["Line AB: gradient 2, y = 2x + 1.", "C: 2(−2) + 1 = −3 ✓, so C lies on line AB."] },
          ],
          commonError: "Saying 'same gradient' without mentioning the shared point — parallel lines also have equal gradients.",
          difficulty: "core",
          guideRef: "y-mx-c",
          hints: ["Work out the gradient of AB and the gradient of AC.", "Equal gradients alone could mean parallel lines. What else do AB and AC have in common?"],
          strategy: "Look for an invariant",
        },
        {
          kind: "short",
          id: "linear-graphs-p1-q13",
          question: "A is the point (2, 1) and B is the point (6, 9). Find the equation of the perpendicular bisector of AB. Give your answer in the form y = mx + c.",
          answer: { type: "equation", eq: "y=-x/2+7", display: "{{y = -1/2 x + 7}}" },
          solution: [
            "Midpoint of AB: (4, 5). The bisector passes through here.",
            "Gradient of AB = {{8/4 = 2}}, so the perpendicular gradient is {{-1/2}}.",
            "{{y - 5 = -1/2 (x - 4) = -1/2 x + 2}}, so {{y = -1/2 x + 7}}.",
            "Check: A and B should be equally far from any point on it — e.g. (0, 7): {{4 + 36 = 40}} and {{36 + 4 = 40}}. ✓",
          ],
          traps: [
            { spec: { type: "equation", eq: "y=-x/2+2" }, feedback: "The bisector must pass through the **midpoint** (4, 5), not through A." },
            { spec: { type: "equation", eq: "y=2x-3" }, feedback: "That's the line AB itself. The bisector is *perpendicular* to AB." },
          ],
          commonError: "Using point A instead of the midpoint.",
          difficulty: "challenge",
          guideRef: "parallel-perpendicular",
          hints: [
            "'Perpendicular bisector' has two jobs: what does 'bisector' tell you, and what does 'perpendicular' tell you?",
            "It passes through the midpoint of AB …",
            "… and its gradient is the negative reciprocal of AB's gradient.",
            "Midpoint (4, 5), gradient {{-1/2}}.",
          ],
          strategy: "Split into cases",
        },
        {
          kind: "short",
          id: "linear-graphs-p1-q14",
          question:
            "The diagram shows the lines y = x + 2 and y = −2x + 8. Work out the area of the shaded triangle formed by the two lines and the x-axis.",
          diagram: `<svg viewBox="0 0 320 330" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Axes with the lines y = x + 2 and y = −2x + 8; the triangle between the two lines and the x-axis is shaded"><rect x="0" y="0" width="320" height="330" fill="#ffffff"/><polygon points="50,290 170,170 230,290" fill="#c7d2fe" stroke="none"/><line x1="10" y1="290" x2="305" y2="290" stroke="#334155" stroke-width="1.5"/><line x1="110" y1="325" x2="110" y2="12" stroke="#334155" stroke-width="1.5"/><line x1="26" y1="314" x2="254" y2="86" stroke="#1f2937" stroke-width="2"/><line x1="122" y1="74" x2="242" y2="314" stroke="#1f2937" stroke-width="2"/><text x="300" y="306" font-size="13" font-family="sans-serif" fill="#1f2937">x</text><text x="116" y="20" font-size="13" font-family="sans-serif" fill="#1f2937">y</text><text x="98" y="304" font-size="12" font-family="sans-serif" fill="#1f2937">O</text><text x="200" y="88" font-size="12" font-family="sans-serif" fill="#1f2937">y = x + 2</text><text x="250" y="250" font-size="12" font-family="sans-serif" fill="#1f2937">y = −2x + 8</text><text x="160" y="320" font-size="11" font-family="sans-serif" fill="#334155">Not drawn to scale</text></svg>`,
          answer: { type: "number", value: 12 },
          solution: [
            "Where the lines meet: x + 2 = −2x + 8, so 3x = 6, x = 2, y = 4. Apex (2, 4).",
            "x-intercepts: y = x + 2 meets the x-axis at x = −2; y = −2x + 8 meets it at x = 4.",
            "Base = 4 − (−2) = 6; height = 4 (the y-coordinate of the apex).",
            "Area = {{1/2 * 6 * 4 = 12}} square units.",
          ],
          traps: [
            { spec: { type: "number", value: 24 }, feedback: "Triangle area is *half* base × height." },
            { spec: { type: "number", value: 4 }, feedback: "Check the base: from x = −2 to x = 4 is 6 units, not 2." },
          ],
          commonError: "Taking the base as 4 − 2 instead of 4 − (−2).",
          difficulty: "challenge",
          guideRef: "intersections",
          hints: [
            "You need the three corners of the triangle. Which two are on the x-axis?",
            "Set y = 0 in each equation to find the base corners.",
            "The top corner is where the lines cross — solve x + 2 = −2x + 8.",
            "Base 6, height 4.",
          ],
          strategy: "Draw a diagram",
        },
        {
          kind: "written",
          id: "linear-graphs-p1-q15",
          question: "A is the point (−1, 2), B is (3, 4) and C is (5, 0). Prove that triangle ABC is a right-angled isosceles triangle.",
          marks: 4,
          modelAnswer:
            "Gradient AB = {{(4 - 2)/(3 - (-1)) = 2/4 = 1/2}}. Gradient BC = {{(0 - 4)/(5 - 3) = -2}}.\n\n{{1/2 * (-2) = -1}}, so AB is perpendicular to BC: angle ABC = 90°.\n\n{{AB^2 = 4^2 + 2^2 = 20}} and {{BC^2 = 2^2 + 4^2 = 20}}, so AB = BC = {{sqrt(20)}}.\n\nSo ABC is right-angled (at B) and isosceles (AB = BC).",
          markScheme: [
            { point: "Gradients of AB and BC: 1/2 and −2", keywords: ["1/2", "0.5", "-2", "−2"] },
            { point: "Product of gradients is −1, so right angle at B", keywords: ["-1", "−1", "perpendicular", "right angle", "90"] },
            { point: "Lengths AB and BC both √20 (or squares both 20)", keywords: ["20", "sqrt(20)", "√20", "2√5", "2sqrt(5)"] },
            { point: "Concludes right-angled AND isosceles", keywords: ["isosceles", "ab = bc", "equal", "right-angled"] },
          ],
          solutions: [
            {
              label: "All by lengths (converse of Pythagoras)",
              steps: [
                "{{AB^2 = 20}}, {{BC^2 = 20}}, {{AC^2 = 6^2 + 2^2 = 40}}.",
                "{{AB^2 + BC^2 = 40 = AC^2}}, so by the converse of Pythagoras angle B = 90°; and AB = BC.",
                "One method, two facts — often the quickest route.",
              ],
            },
          ],
          commonError: "Proving only one of the two properties.",
          difficulty: "challenge",
          guideRef: "parallel-perpendicular",
          hints: [
            "Sketch it. Which corner looks like the right angle?",
            "Perpendicular sides: compare the gradients of the two sides meeting there.",
            "Isosceles: compare the lengths of those two sides.",
          ],
          strategy: "Draw a diagram",
        },
      ],
    },
    {
      id: "linear-graphs-p2",
      title: "Practice Paper 2",
      questions: [
        {
          kind: "short",
          id: "linear-graphs-p2-q01",
          question: "Find the gradient of the line 4x − 3y = 12. Give your answer as a fraction.",
          answer: { type: "fraction", n: 4, d: 3, display: "{{4/3}}" },
          solution: ["Rearrange: 3y = 4x − 12.", "{{y = 4/3 x - 4}}, so the gradient is {{4/3}}."],
          traps: [
            { spec: { type: "fraction", n: -4, d: 3 }, feedback: "Moving −3y to the other side makes it +3y: 3y = 4x − 12, so the gradient is positive." },
            { spec: { type: "number", value: 4 }, feedback: "Divide by the coefficient of y as well: y = {{4/3}}x − 4." },
          ],
          commonError: "Reading the x coefficient (4) as the gradient.",
          difficulty: "warmup",
          guideRef: "y-mx-c",
          hints: ["Make y the subject first — watch the sign of the y term."],
        },
        {
          kind: "short",
          id: "linear-graphs-p2-q02",
          question: "Find the equation of the line with gradient 5 passing through (2, 3). Give your answer in the form y = mx + c.",
          answer: { type: "equation", eq: "y=5x-7", display: "y = 5x − 7" },
          solution: ["y − 3 = 5(x − 2) = 5x − 10.", "y = 5x − 7."],
          traps: [{ spec: { type: "equation", eq: "y=5x+3" }, feedback: "3 is the y-coordinate of the point, not the y-intercept (the point isn't on the y-axis)." }],
          commonError: "Using the y-coordinate of the point as c.",
          difficulty: "warmup",
          guideRef: "point-gradient-form",
          hints: ["Use y − y₁ = m(x − x₁) with (2, 3) and m = 5."],
        },
        {
          kind: "short",
          id: "linear-graphs-p2-q03",
          question: "Find the midpoint of (−4, −1) and (3, 6). Give your answer as (x, y), using decimals where needed.",
          answer: { type: "list", values: [-0.5, 2.5], ordered: true, display: "(−0.5, 2.5)" },
          solution: ["x: {{(-4 + 3)/2 = -0.5}}.", "y: {{(-1 + 6)/2 = 2.5}}."],
          traps: [{ spec: { type: "list", values: [3.5, 3.5], ordered: true }, feedback: "Half the *difference* gives the distance from each end, not the midpoint. Add the coordinates and halve." }],
          commonError: "Halving the difference instead of the sum.",
          difficulty: "warmup",
          guideRef: "midpoint-distance",
          hints: ["Add the x's and halve; add the y's and halve. Negatives are fine."],
        },
        {
          kind: "short",
          id: "linear-graphs-p2-q04",
          question: "Write down the gradient of a line perpendicular to {{y = -2/5 x + 1}}.",
          answer: { type: "fraction", n: 5, d: 2, allowDecimal: true, display: "{{5/2}}" },
          solution: ["Negative reciprocal of {{-2/5}}: flip it to {{-5/2}}, change the sign to {{5/2}}.", "Check: {{-2/5 * 5/2 = -1}}. ✓"],
          traps: [
            { spec: { type: "fraction", n: -5, d: 2 }, feedback: "Flip *and* change the sign. The original is negative, so the perpendicular gradient is positive." },
            { spec: { type: "fraction", n: 2, d: 5 }, feedback: "Changing the sign is only half the job — you also need to flip the fraction." },
          ],
          commonError: "Flipping without changing the sign (or vice versa).",
          difficulty: "warmup",
          guideRef: "parallel-perpendicular",
          hints: ["Perpendicular gradients multiply to −1: flip and change sign."],
          strategy: "Use the inverse",
        },
        {
          kind: "short",
          id: "linear-graphs-p2-q05",
          question: "The line L passes through (0, −3) and (4, 5). The point (k, 13) lies on L. Find the value of k.",
          answer: { type: "number", value: 8 },
          solution: [
            "Gradient = {{(5 - (-3))/(4 - 0) = 8/4 = 2}}; y-intercept −3. So L is y = 2x − 3.",
            "Substitute (k, 13): 13 = 2k − 3, so 2k = 16 and k = 8.",
          ],
          traps: [{ spec: { type: "number", value: 23 }, feedback: "k is the **x**-coordinate. Substitute y = 13 and solve for x, rather than putting 13 in for x." }],
          commonError: "Substituting 13 as the x value.",
          difficulty: "core",
          guideRef: "y-mx-c",
          hints: ["First find the equation of L. (0, −3) gives you c for free.", "y = 2x − 3. A point lies on a line when its coordinates satisfy the equation."],
          strategy: "Check by substituting",
        },
        {
          kind: "short",
          id: "linear-graphs-p2-q06",
          question:
            "Find an equation of the line through (−3, 4) and (1, −2). Give your answer in the form ax + by + c = 0, where a, b and c are integers and a > 0.",
          answer: {
            type: "text",
            accept: ["3x+2y+1=0", "2y+3x+1=0", "3x+2y=-1", "2y+3x=-1", "0=3x+2y+1", "-1=3x+2y", "3x+1+2y=0"],
            display: "3x + 2y + 1 = 0",
          },
          solution: [
            "Gradient = {{(-2 - 4)/(1 - (-3)) = -6/4 = -3/2}}.",
            "{{y - 4 = -3/2 (x + 3)}}. Multiply by 2: 2y − 8 = −3x − 9.",
            "3x + 2y + 1 = 0.",
            "Check (1, −2): 3 − 4 + 1 = 0. ✓ Check (−3, 4): −9 + 8 + 1 = 0. ✓",
          ],
          commonError: "Writing (x − 3) instead of (x + 3) for the point (−3, 4).",
          difficulty: "core",
          guideRef: "point-gradient-form",
          hints: ["Gradient first.", "Use y − 4 = m(x − (−3)), then multiply by 2 to clear the fraction.", "Collect everything on the left so the x term is positive."],
          strategy: "Check by substituting",
        },
        {
          kind: "short",
          id: "linear-graphs-p2-q07",
          question: "A is the point (2, k) and B is the point (8, 3). The length of AB is 10 units. Find the two possible values of k.",
          answer: { type: "list", values: [11, -5], ordered: false, display: "k = 11 or k = −5" },
          solution: [
            "Across: 8 − 2 = 6. So {{6^2 + (k - 3)^2 = 10^2}}.",
            "{{(k - 3)^2 = 64}}, so k − 3 = 8 or k − 3 = −8.",
            "k = 11 or k = −5.",
          ],
          traps: [{ spec: { type: "list", values: [11], ordered: false }, feedback: "A square root has two signs: k − 3 = ±8. A could be above or below B." }],
          commonError: "Forgetting the negative square root.",
          difficulty: "core",
          guideRef: "midpoint-distance",
          hints: [
            "Draw it: a right-angled triangle with hypotenuse 10 and one side 6.",
            "The vertical side must be 8 — but which way?",
            "{{(k - 3)^2 = 64}}.",
          ],
          strategy: "Split into cases",
        },
        {
          kind: "written",
          id: "linear-graphs-p2-q08",
          question: "A circle has centre C(1, 2) and passes through the point A(4, 6). Show that the point B(−4, 2) also lies on the circle.",
          marks: 3,
          modelAnswer:
            "Radius = CA = {{sqrt((4 - 1)^2 + (6 - 2)^2) = sqrt(9 + 16) = 5}}.\n\nCB = {{sqrt((-4 - 1)^2 + (2 - 2)^2) = sqrt(25 + 0) = 5}}.\n\nCB = CA = radius, so B is the same distance from the centre as A: B lies on the circle.",
          markScheme: [
            { point: "Finds CA = 5 (radius)", keywords: ["ca", "9 + 16", "25", "5"] },
            { point: "Finds CB = 5", keywords: ["cb", "25 + 0", "-5", "5"] },
            { point: "Concludes equal distances from the centre, so B is on the circle", keywords: ["same distance", "equal", "radius", "on the circle", "lies on"] },
          ],
          commonError: "Finding the distance AB instead of comparing distances from the centre.",
          difficulty: "core",
          guideRef: "midpoint-distance",
          hints: ["Every point on a circle is the same distance from the centre. What distance is that here?", "Compare CA with CB."],
          strategy: "Look for an invariant",
        },
        {
          kind: "written",
          id: "linear-graphs-p2-q09",
          question:
            "Hana says the simultaneous equations 2x + 3y = 6 and 4x + 6y = 9 have no solution. Show that she is right, explaining your answer in terms of the graphs of the two lines.",
          marks: 3,
          modelAnswer:
            "2x + 3y = 6 gives {{y = -2/3 x + 2}}.\n\n4x + 6y = 9 gives {{y = -2/3 x + 3/2}}.\n\nBoth lines have gradient {{-2/3}}, so they are parallel, but their y-intercepts (2 and {{3/2}}) are different, so they are not the same line. Parallel, distinct lines never meet, so there is no point on both lines — the equations have no solution.",
          markScheme: [
            { point: "Rearranges both to show gradient −2/3 for each", keywords: ["-2/3", "−2/3", "same gradient", "gradient"] },
            { point: "Different intercepts (2 and 1.5), so distinct lines", keywords: ["2", "1.5", "3/2", "different", "intercept"] },
            { point: "Parallel lines never meet, so no intersection / no solution", keywords: ["parallel", "never meet", "no intersection", "do not cross", "no solution"] },
          ],
          solutions: [
            { label: "Algebra", steps: ["Double the first equation: 4x + 6y = 12.", "But 4x + 6y = 9 as well, and 12 ≠ 9 — a contradiction, so no solution.", "This is the algebraic shadow of the picture: same left-hand side, different constant = parallel lines."] },
          ],
          commonError: "Saying 'same gradient' without checking the intercepts — the lines could be identical (infinitely many solutions).",
          difficulty: "core",
          guideRef: "intersections",
          hints: ["Rewrite each equation as y = mx + c.", "Compare the gradients and the intercepts.", "What does a solution to a pair of simultaneous equations look like on the graph?"],
          strategy: "Draw a diagram",
        },
        {
          kind: "short",
          id: "linear-graphs-p2-q10",
          question:
            "The line L has equation y = 3x − 2. The point P(2, 4) lies on L. Find the equation of the normal to L at P. Give your answer in the form ax + by + c = 0, where a, b and c are integers and a > 0.",
          answer: {
            type: "text",
            accept: ["x+3y-14=0", "3y+x-14=0", "x+3y=14", "3y+x=14", "0=x+3y-14", "14=x+3y", "x-14+3y=0"],
            display: "x + 3y − 14 = 0",
          },
          solution: [
            "The normal at P is the line through P perpendicular to L.",
            "Gradient of L = 3, so gradient of the normal = {{-1/3}}.",
            "{{y - 4 = -1/3 (x - 2)}}. Multiply by 3: 3y − 12 = −x + 2.",
            "x + 3y − 14 = 0. Check P: 2 + 12 − 14 = 0. ✓",
          ],
          commonError: "Using the gradient of L (3) — that gives the line itself, not the normal.",
          difficulty: "core",
          guideRef: "parallel-perpendicular",
          hints: ["'Normal' means perpendicular. What is its gradient?", "{{-1/3}} through (2, 4). Clear the fraction by multiplying by 3."],
          strategy: "Use the inverse",
        },
        {
          kind: "short",
          id: "linear-graphs-p2-q11",
          question: "Find the coordinates of the point of intersection of 2x + 3y = 12 and 5x − 2y = 11. Give your answer as (x, y).",
          answer: { type: "list", values: [3, 2], ordered: true, display: "(3, 2)" },
          solution: [
            "Make the y coefficients match: ×2 gives 4x + 6y = 24; ×3 gives 15x − 6y = 33.",
            "Add: 19x = 57, so x = 3.",
            "2(3) + 3y = 12, so y = 2. Check: 15 − 4 = 11. ✓",
          ],
          commonError: "Subtracting instead of adding when the y terms have opposite signs.",
          difficulty: "core",
          guideRef: "intersections",
          hints: ["Neither equation is 'y = …', so elimination is neat here.", "Multiply to make the y coefficients 6 and −6, then add."],
          strategy: "Eliminate a variable",
        },
        {
          kind: "short",
          id: "linear-graphs-p2-q12",
          question:
            "A is the point (2, −1) and B is the point (10, 7). The point P lies on AB such that AP : PB = 1 : 3. Find the coordinates of P. Give your answer as (x, y).",
          answer: { type: "list", values: [4, 1], ordered: true, display: "(4, 1)" },
          solution: [
            "AP : PB = 1 : 3 means P is {{1/4}} of the way from A to B (1 part out of 1 + 3 = 4).",
            "From A to B: +8 in x, +8 in y. A quarter of that: +2, +2.",
            "P = (2 + 2, −1 + 2) = (4, 1).",
          ],
          traps: [
            { spec: { type: "list", values: [14 / 3, 5 / 3], ordered: true }, feedback: "1 : 3 means 4 equal parts in total, so P is {{1/4}} of the way — not {{1/3}}." },
            { spec: { type: "list", values: [8, 5], ordered: true }, feedback: "That's {{3/4}} of the way from A. AP is the *small* part, so P is nearer A." },
          ],
          commonError: "Using {{1/3}} of the way instead of {{1/4}}.",
          difficulty: "core",
          guideRef: "dividing-a-line",
          hints: ["How many equal parts is AB split into?", "P is {{1/4}} of the way from A to B. What is the full step from A to B?", "Add a quarter of (8, 8) to A."],
          strategy: "Use a bar model",
        },
        {
          kind: "written",
          id: "linear-graphs-p2-q13",
          question: "Show that the three lines y = 2x − 1, x + y = 5 and 4x − y = 5 all pass through the same point.",
          marks: 3,
          modelAnswer:
            "Solve the first two: x + (2x − 1) = 5, so 3x = 6, x = 2 and y = 3. They meet at (2, 3).\n\nTest (2, 3) in the third line: 4(2) − 3 = 8 − 3 = 5. ✓\n\n(2, 3) lies on all three lines, so they are concurrent (they all pass through (2, 3)).",
          markScheme: [
            { point: "Solves two of the equations simultaneously", keywords: ["3x = 6", "x + 2x - 1", "x = 2", "substitute"] },
            { point: "Intersection point (2, 3)", keywords: ["(2, 3)", "(2,3)", "y = 3", "x = 2"] },
            { point: "Verifies the point satisfies the third equation and concludes", keywords: ["8 - 3", "= 5", "satisfies", "lies on", "all three", "same point"] },
          ],
          commonError: "Finding where two lines meet and stopping, without checking the third.",
          difficulty: "challenge",
          guideRef: "intersections",
          hints: ["Two lines (not parallel) always meet somewhere. Find where the first two meet.", "Three lines share a point only if that point also lies on the third line.", "Substitute (2, 3) into 4x − y."],
          strategy: "Check by substituting",
        },
        {
          kind: "short",
          id: "linear-graphs-p2-q14",
          question: "The lines y = x + 1 and y = 7 − 2x meet at P. Work out the area of the triangle formed by these two lines and the y-axis.",
          answer: { type: "number", value: 6 },
          solution: [
            "P: x + 1 = 7 − 2x, so x = 2 and y = 3.",
            "The lines cross the y-axis at (0, 1) and (0, 7): a base of 6 along the y-axis.",
            "The 'height' is the horizontal distance from the y-axis to P: 2.",
            "Area = {{1/2 * 6 * 2 = 6}} square units.",
          ],
          traps: [
            { spec: { type: "number", value: 9 }, feedback: "With the base on the y-axis, the height is the *horizontal* distance to P (its x-coordinate, 2), not its y-coordinate." },
            { spec: { type: "number", value: 12 }, feedback: "Remember the half in {{1/2}} × base × height." },
          ],
          commonError: "Using P's y-coordinate as the height when the base is vertical.",
          difficulty: "challenge",
          guideRef: "intersections",
          hints: [
            "Sketch it. Which side of the triangle lies along the y-axis?",
            "The two y-intercepts give the base. Where is the third vertex?",
            "Base 6 is vertical, so the height is measured horizontally.",
          ],
          strategy: "Draw a diagram",
        },
        {
          kind: "short",
          id: "linear-graphs-p2-q15",
          question:
            "The line x + 2y = 10 meets the x-axis at A and the y-axis at B. The perpendicular bisector of AB meets the x-axis at C. Find the x-coordinate of C. Give your answer as a decimal.",
          answer: { type: "number", value: 3.75, allowFraction: false },
          solution: [
            "A = (10, 0) and B = (0, 5).",
            "Midpoint of AB = (5, 2.5). Gradient of AB = {{-5/10 = -1/2}}, so the bisector has gradient 2.",
            "Bisector: y − 2.5 = 2(x − 5). At C, y = 0: −2.5 = 2x − 10, so x = 3.75.",
            "Check: CA = 10 − 3.75 = 6.25 and {{CB = sqrt(3.75^2 + 5^2) = sqrt(39.0625) = 6.25}}. ✓",
          ],
          solutions: [
            {
              label: "Equidistance",
              steps: [
                "Every point on the perpendicular bisector is equally far from A and B. Let C = (c, 0).",
                "{{(10 - c)^2 = c^2 + 25}}, so 100 − 20c = 25 and c = 3.75.",
                "Quicker: one equation, no gradients needed.",
              ],
            },
          ],
          traps: [{ spec: { type: "number", value: 6.25 }, feedback: "6.25 is the distance CA (and CB). The question asks for the x-coordinate of C." }],
          commonError: "Using the gradient of AB rather than the perpendicular gradient.",
          difficulty: "challenge",
          guideRef: "parallel-perpendicular",
          hints: [
            "Find A and B first: set y = 0, then x = 0.",
            "The perpendicular bisector goes through the midpoint of AB at right angles to AB.",
            "Alternatively: C is equally far from A and B. Let C = (c, 0).",
          ],
          strategy: "Introduce a variable",
        },
      ],
    },
  ],

  // =========================================================================
  // Challenge — 10 grade-9 / H+ problems
  // =========================================================================
  challenge: [
    {
      kind: "short",
      id: "linear-graphs-ch-q01",
      question:
        "A is the point (−1, 1) and B is (2, 7). The point C(k, k²) is different from A, and A, B and C lie on a straight line. Find the value of k.",
      answer: { type: "number", value: 3 },
      solution: [
        "Line AB: gradient {{(7 - 1)/(2 - (-1)) = 2}}, so y − 1 = 2(x + 1), i.e. y = 2x + 3.",
        "C on the line: {{k^2 = 2k + 3}}, so {{k^2 - 2k - 3 = 0}}, (k − 3)(k + 1) = 0.",
        "k = −1 gives C = (−1, 1) = A, which is excluded. So k = 3 and C = (3, 9).",
        "Check: 2(3) + 3 = 9. ✓",
      ],
      solutions: [
        {
          label: "Equal gradients",
          steps: [
            "Gradient AC = gradient AB: {{(k^2 - 1)/(k + 1) = 2}}.",
            "{{(k^2 - 1)/(k + 1) = ((k - 1)(k + 1))/(k + 1) = k - 1}} (allowed since k ≠ −1).",
            "k − 1 = 2, so k = 3. The cancelling shows *why* −1 disappears: it's the point A itself.",
          ],
        },
      ],
      traps: [{ spec: { type: "number", value: -1 }, feedback: "k = −1 puts C at (−1, 1) — that's A itself, which the question excludes." }],
      difficulty: "challenge",
      guideRef: "y-mx-c",
      hints: [
        "The points of a line all satisfy one equation. Find the equation of AB.",
        "Line AB is y = 2x + 3. What must be true of the coordinates of C?",
        "{{k^2 = 2k + 3}} — a quadratic, so expect two answers. Do both fit the question?",
      ],
      strategy: "Split into cases",
    },
    {
      kind: "short",
      id: "linear-graphs-ch-q02",
      question:
        "A straight line through (3, 4) meets the x-axis at P and the y-axis at Q, where neither P nor Q is at the origin. Given that OP = OQ, find the two possible gradients of the line.",
      answer: { type: "list", values: [1, -1], ordered: false, display: "1 or −1" },
      solution: [
        "OP = OQ means triangle OPQ is right-angled and isosceles, so the line makes 45° with the axes.",
        "A 45° line has gradient 1 or −1.",
        "Gradient 1: y = x + 1 (P(−1, 0), Q(0, 1)). Gradient −1: y = −x + 7 (P(7, 0), Q(0, 7)). Both avoid the origin. ✓",
      ],
      solutions: [
        {
          label: "Algebra",
          steps: [
            "Line: y − 4 = m(x − 3). Q has y = 4 − 3m; P has {{x = 3 - 4/m}}.",
            "{{|4 - 3m| = |3 - 4/m|}}. Same signs: {{3m^2 - m - 4 = 0}}, so m = −1 or {{4/3}}.",
            "Opposite signs: {{3m^2 - 7m + 4 = 0}}, so m = 1 or {{4/3}}.",
            "m = {{4/3}} gives y = {{4/3}}x through the origin — excluded. So m = ±1. The geometry is far quicker.",
          ],
        },
      ],
      traps: [{ spec: { type: "list", values: [-1], ordered: false }, feedback: "The intercepts can also have opposite signs — P on the negative x-axis, Q on the positive y-axis. Try gradient +1." }],
      difficulty: "challenge",
      guideRef: "point-gradient-form",
      hints: [
        "Sketch triangle OPQ. If OP = OQ, what kind of triangle is it?",
        "Right-angled and isosceles — so what angle does PQ make with the axes?",
        "45°. Which gradients give a 45° line? Don't forget the sign.",
        "Check each candidate line actually passes through (3, 4) without going through O.",
      ],
      strategy: "Draw a diagram",
    },
    {
      kind: "short",
      id: "linear-graphs-ch-q03",
      question: "Find the point on the y-axis that is the same distance from A(2, 3) as from B(6, 1). Give its y-coordinate.",
      answer: { type: "number", value: -6 },
      solution: [
        "Let the point be (0, k). Equal squared distances:",
        "{{2^2 + (k - 3)^2 = 6^2 + (k - 1)^2}}.",
        "{{4 + k^2 - 6k + 9 = 36 + k^2 - 2k + 1}}; the {{k^2}} cancel: 13 − 6k = 37 − 2k.",
        "−4k = 24, so k = −6. The point is (0, −6). Check: 4 + 81 = 85 and 36 + 49 = 85. ✓",
      ],
      solutions: [
        {
          label: "Perpendicular bisector",
          steps: [
            "Points equidistant from A and B lie on the perpendicular bisector of AB.",
            "Midpoint (4, 2); gradient AB = {{-2/4 = -1/2}}, so the bisector has gradient 2: y − 2 = 2(x − 4).",
            "On the y-axis x = 0: y = 2 − 8 = −6.",
          ],
        },
      ],
      traps: [{ spec: { type: "number", value: 2 }, feedback: "(0, 2) is level with the midpoint of AB, but it's {{sqrt(5)}} from A and {{sqrt(37)}} from B. Equidistant points lie on the *perpendicular bisector*." }],
      difficulty: "challenge",
      guideRef: "midpoint-distance",
      hints: [
        "Name the unknown point: (0, k).",
        "Write the distance to A and the distance to B. Squaring both avoids square roots.",
        "Expand — the {{k^2}} terms cancel, leaving a linear equation.",
        "Or: where are *all* the points equidistant from A and B?",
      ],
      strategy: "Introduce a variable",
    },
    {
      kind: "short",
      id: "linear-graphs-ch-q04",
      question: "ABCD is a parallelogram (vertices in that order) with A(1, 2), B(7, 4) and C(9, 10). Find the coordinates of D. Give your answer as (x, y).",
      answer: { type: "list", values: [3, 8], ordered: true, display: "(3, 8)" },
      solution: [
        "The diagonals of a parallelogram bisect each other, so AC and BD have the same midpoint.",
        "Midpoint of AC = (5, 6).",
        "D is as far beyond (5, 6) as B is before it: D = (2 × 5 − 7, 2 × 6 − 4) = (3, 8).",
        "Check: AB goes (+6, +2) and DC goes (9 − 3, 10 − 8) = (+6, +2). ✓",
      ],
      solutions: [
        { label: "Same step", steps: ["In ABCD, the step from B to C equals the step from A to D.", "B → C is (+2, +6). So D = (1 + 2, 2 + 6) = (3, 8)."] },
      ],
      traps: [{ spec: { type: "list", values: [15, 12], ordered: true }, feedback: "(15, 12) completes the parallelogram ABDC — the letters must go round in the order A, B, C, D, so D is opposite B." }],
      difficulty: "challenge",
      guideRef: "midpoint-distance",
      hints: [
        "Sketch the three points and decide where D must go so that the vertices run A → B → C → D.",
        "Which property of a parallelogram involves midpoints?",
        "The diagonals AC and BD share a midpoint.",
      ],
      strategy: "Use symmetry",
    },
    {
      kind: "short",
      id: "linear-graphs-ch-q05",
      question: "Find the shortest distance from the point P(7, 1) to the line y = 2x + 2. Give your answer as a surd in its simplest form.",
      answer: { type: "expression", expr: "3sqrt(5)", form: "surd", display: "{{3 sqrt(5)}}" },
      solution: [
        "The shortest route is along the perpendicular from P to the line.",
        "Perpendicular gradient {{-1/2}}: {{y - 1 = -1/2 (x - 7)}}, i.e. {{y = -1/2 x + 9/2}}.",
        "Meet the line: {{2x + 2 = -1/2 x + 9/2}}, so {{5/2 x = 5/2}}, x = 1, y = 4. Foot F(1, 4).",
        "{{PF = sqrt(6^2 + 3^2) = sqrt(45) = 3 sqrt(5)}}.",
      ],
      solutions: [
        {
          label: "Minimise the distance",
          steps: [
            "A general point on the line is (t, 2t + 2). Distance² to P = {{(t - 7)^2 + (2t + 1)^2 = 5t^2 - 10t + 50}}.",
            "Complete the square: {{5(t - 1)^2 + 45}}. Smallest when t = 1, giving {{sqrt(45) = 3 sqrt(5)}}.",
            "Same answer — and it *proves* the perpendicular is shortest.",
          ],
        },
      ],
      traps: [{ spec: { type: "number", value: 13 }, feedback: "That's the vertical distance from P up to the line (at x = 7, y = 16). The shortest distance is perpendicular to the line, not vertical." }],
      difficulty: "challenge",
      guideRef: "parallel-perpendicular",
      hints: [
        "Imagine dropping from P to the line. Which direction gives the shortest route?",
        "At right angles to the line. Find the equation of the perpendicular through P.",
        "Find where it meets y = 2x + 2 — that's the foot F.",
        "Then the distance PF by Pythagoras.",
      ],
      strategy: "Consider extremes",
    },
    {
      kind: "short",
      id: "linear-graphs-ch-q06",
      question: "The point A(−3, 5) is reflected in the line y = 2x + 1. Find the coordinates of its image A′. Give your answer as (x, y).",
      answer: { type: "list", values: [5, 1], ordered: true, display: "(5, 1)" },
      solution: [
        "The mirror line is the perpendicular bisector of AA′, so AA′ is perpendicular to the mirror and is cut in half by it.",
        "Perpendicular through A, gradient {{-1/2}}: {{y - 5 = -1/2 (x + 3)}}.",
        "Meets y = 2x + 1 where {{2x + 1 = -1/2 x + 7/2}}: {{5/2 x = 5/2}}, x = 1, y = 3. So M(1, 3) is the midpoint of AA′.",
        "A′ = (2 × 1 − (−3), 2 × 3 − 5) = (5, 1).",
        "Check: midpoint of A and A′ is (1, 3), on the mirror ✓; gradient AA′ = {{-4/8 = -1/2}} ✓.",
      ],
      traps: [{ spec: { type: "list", values: [1, 3], ordered: true }, feedback: "(1, 3) is where the perpendicular hits the mirror — the *midpoint* of AA′. Go the same distance again." }],
      difficulty: "challenge",
      guideRef: "parallel-perpendicular",
      hints: [
        "What is the relationship between a mirror line and the segment joining a point to its image?",
        "The mirror is the perpendicular bisector of AA′. So first find the line through A perpendicular to the mirror.",
        "Find where that meets the mirror: that point is the midpoint of AA′.",
        "Step on from the midpoint by the same amount.",
      ],
      strategy: "Use symmetry",
    },
    {
      kind: "short",
      id: "linear-graphs-ch-q07",
      question: "The three lines y = x + 1, y = −x + 7 and y = 3x − 9 form a triangle. Work out its area.",
      answer: { type: "number", value: 2 },
      solution: [
        "Vertices: y = x + 1 and y = −x + 7 meet at (3, 4); y = x + 1 and y = 3x − 9 meet at (5, 6); y = −x + 7 and y = 3x − 9 meet at (4, 3).",
        "Spot it: gradients 1 and −1 multiply to −1, so the angle at (3, 4) is 90°.",
        "Legs: from (3, 4) to (5, 6) is {{sqrt(8)}}; from (3, 4) to (4, 3) is {{sqrt(2)}}.",
        "Area = {{1/2 * sqrt(8) * sqrt(2) = 1/2 * 4 = 2}} square units.",
      ],
      solutions: [
        {
          label: "Bounding box",
          steps: [
            "The vertices fit in the box 3 ≤ x ≤ 5, 3 ≤ y ≤ 6: area 2 × 3 = 6.",
            "Subtract the three corner triangles: {{1/2 * 2 * 2 = 2}}, {{1/2 * 1 * 3 = 1.5}}, {{1/2 * 1 * 1 = 0.5}}.",
            "6 − 2 − 1.5 − 0.5 = 2. Works for any triangle, right-angled or not.",
          ],
        },
      ],
      traps: [{ spec: { type: "number", value: 4 }, feedback: "{{sqrt(8) * sqrt(2) = 4}} is base × height — halve it for the triangle." }],
      difficulty: "challenge",
      guideRef: "intersections",
      hints: [
        "Find all three vertices — each is the intersection of a pair of lines.",
        "Before reaching for a formula, look at the gradients. Are any two lines perpendicular?",
        "y = x + 1 and y = −x + 7 are perpendicular, so you have a right-angled triangle.",
      ],
      strategy: "Look for an invariant",
    },
    {
      kind: "short",
      id: "linear-graphs-ch-q08",
      question: "The lines kx + 2y = 5 and 3x + (k + 1)y = 4 do not intersect. Find the two possible values of k.",
      answer: { type: "list", values: [2, -3], ordered: false, display: "k = 2 or k = −3" },
      solution: [
        "Lines that never meet are parallel (and distinct), so their gradients are equal.",
        "Gradients: {{-k/2}} and {{-3/(k + 1)}}. Set equal: k(k + 1) = 6.",
        "{{k^2 + k - 6 = 0}}, so (k + 3)(k − 2) = 0: k = 2 or k = −3.",
        "Check they're distinct, not the same line: k = 2 gives 2x + 2y = 5 and 3x + 3y = 4, i.e. x + y = 2.5 and x + y = {{4/3}} ✓. k = −3 gives −3x + 2y = 5 and 3x − 2y = 4, i.e. −3x + 2y = −4 ✓.",
      ],
      solutions: [
        {
          label: "Proportional coefficients",
          steps: [
            "Parallel lines ax + by = c have proportional (a, b): {{k/3 = 2/(k + 1)}}.",
            "Cross-multiply: k(k + 1) = 6 — the same quadratic, without rearranging either line.",
          ],
        },
      ],
      traps: [{ spec: { type: "list", values: [2], ordered: false }, feedback: "The quadratic has two roots — check k = −3 as well. Both give parallel, distinct lines." }],
      difficulty: "challenge",
      guideRef: "intersections",
      hints: [
        "When do two straight lines never meet?",
        "Parallel: equal gradients. Find each gradient in terms of k.",
        "{{-k/2 = -3/(k + 1)}} — clear the fractions.",
        "Finally check neither value makes the two lines identical.",
      ],
      strategy: "Consider extremes",
    },
    {
      kind: "short",
      id: "linear-graphs-ch-q09",
      question:
        "The point P(2, 4) lies on the line segment AB, where A is (−4, 1) and AP : PB = 2 : 3. Find the coordinates of B. Give your answer as (x, y), using decimals where needed.",
      answer: { type: "list", values: [11, 8.5], ordered: true, display: "(11, 8.5)" },
      solution: [
        "AP is 2 parts out of 5, so P is {{2/5}} of the way from A to B.",
        "Step A → P = (6, 3), which is 2 parts. One part = (3, 1.5).",
        "B is 5 parts from A: (−4 + 15, 1 + 7.5) = (11, 8.5).",
        "Check: {{2/5}} of (15, 7.5) = (6, 3), and A + (6, 3) = (2, 4) = P. ✓",
      ],
      solutions: [
        { label: "From P", steps: ["PB is 3 parts = 3 × (3, 1.5) = (9, 4.5).", "B = (2 + 9, 4 + 4.5) = (11, 8.5)."] },
      ],
      traps: [
        { spec: { type: "list", values: [6.5, 6.25], ordered: true }, feedback: "You've moved 3 parts from A — B is 5 parts (2 + 3) from A." },
      ],
      difficulty: "challenge",
      guideRef: "dividing-a-line",
      hints: [
        "Draw a bar split into 2 + 3 = 5 equal parts, A at the start and B at the end.",
        "The step from A to P covers 2 parts. What is one part?",
        "One part = (3, 1.5). How many parts from A to B?",
      ],
      strategy: "Use a bar model",
    },
    {
      kind: "written",
      id: "linear-graphs-ch-q10",
      question:
        "Triangle ABC has vertices A(0, 0), B(8, 2) and C(4, 10). M is the midpoint of BC and N is the midpoint of AC.\n\n(a) The point G divides AM in the ratio 2 : 1. Find G.\n(b) Show that G also divides BN in the ratio 2 : 1, so G lies on both medians.",
      marks: 4,
      modelAnswer:
        "(a) M = (6, 6). G is {{2/3}} of the way from A to M: G = (0, 0) + {{2/3}}(6, 6) = (4, 4).\n\n(b) N = (2, 5). The point {{2/3}} of the way from B to N is (8, 2) + {{2/3}}(2 − 8, 5 − 2) = (8, 2) + {{2/3}}(−6, 3) = (8 − 4, 2 + 2) = (4, 4).\n\nThis is G again, so G lies on median BN and divides it in the ratio 2 : 1. (G is the centroid: {{((0 + 8 + 4)/3, (0 + 2 + 10)/3) = (4, 4)}}.)",
      markScheme: [
        { point: "Midpoints M(6, 6) and N(2, 5)", keywords: ["(6, 6)", "(6,6)", "(2, 5)", "(2,5)"] },
        { point: "G = (4, 4) from 2/3 of the way along AM", keywords: ["2/3", "(4, 4)", "(4,4)"] },
        { point: "Point 2/3 of the way from B to N computed correctly", keywords: ["(-6, 3)", "(-6,3)", "-4", "8 - 4", "2 + 2"] },
        { point: "Concludes it is the same point (4, 4), so G is on both medians", keywords: ["same point", "also", "both medians", "centroid", "(4, 4)"] },
      ],
      solutions: [
        {
          label: "Why it always works",
          steps: [
            "For any triangle, the point {{2/3}} of the way from A to the midpoint of BC is A + {{2/3}}({{(B + C)/2}} − A) = {{(A + B + C)/3}}.",
            "That expression is symmetric in A, B and C, so the same point is {{2/3}} of the way along every median — the three medians are concurrent at the centroid.",
          ],
        },
      ],
      commonError: "Using 1/2 or 1/3 of the way instead of 2/3 (ratio 2 : 1 means 3 parts, G after 2).",
      difficulty: "challenge",
      guideRef: "dividing-a-line",
      hints: [
        "Ratio 2 : 1 means 3 equal parts. How far along AM is G?",
        "Find M first, then go {{2/3}} of the way from A to M.",
        "For (b), do the same for B to N. Do you land on the same point?",
        "Look at the coordinates of G compared with A + B + C. Coincidence?",
      ],
      strategy: "Find a pattern",
    },
  ],
};
